firefox-devtools/debugger

.gitignore, README.md, package.json, webpack.config.js
+ Moved the gecko-dev path to an environment.js file
+ Added a start command
+ Added a README
=> Improve Getting Started experience

js/components/Editor.js, package.json, webpack.config.js
This is an MVP version, I didn't try to think about whether this would work with our redux setup and whether these were patterns we would like, just wanted to get something working and try selecting source. Sharing early so you can weigh in.
This depends on the CSS Loader to load the codemirror.css
=> Add Codemirror component

js/actions/sources.js, js/components/App.js, js/components/Editor.js, js/components/Sources.js, js/components/SplitBox.js
Here's another WIP branch to share what I was working on to add source. There are some rough edges, but honestly it came together really nicely.
> this depends on this [pr](https://github.com/jlongster/ff-devtools-libs/pull/1/files) and the CSS Loader PR. Also I assume we'll merge the codemirror work first and then clean this up.
=> Selecting Source

js/components/Accordion.js, js/components/App.js, js/components/TabList.js, js/components/Tabs.js
Runs like a charm on Linux now.
=> Changed imports to correct case

js/components/Editor.js
Breakpoints list reported with line numbers off by one
=> fix breakpoint linenums - off by one

js/components/Editor.css, js/components/Editor.js, js/lib/variables.css
Adding styles for debugger/source code viewing
=> Editor styles

README.md
Added Firefox configuration options and local server to readme
=> Added configuration options and local server

README.md
Added a definition section for the environment variable
Linked to the sample file
Added a NOTE about the the gecko source
=> improve the advanced section of the README

js/components/App.js, js/components/Editor.css, js/components/Editor.js, js/components/Sources.css
1. replaces %s with flex 1
2. rename code-editor class to editor class
3. remove unecessary app div
=> Fix chrome layout styles

bin/server-browser-test.js, bin/server.js, bin/test-node, karma.conf.js, mocha-runner.html, webpack.config.js
@jasonLaster I tested everything and they all still work from my end. For something like this, definitely want you to review the code though.
=> move build directory to public to consolidate static assets

public/js/actions/breakpoints.js, public/js/actions/sources.js, public/js/actions/tabs.js, public/js/actions/tests/loadSourceText.js, public/js/actions/tests/newSource.js, public/js/actions/tests/selectSource.js, public/js/components/App.js, public/js/components/Breakpoints.js, public/js/components/Editor.js, public/js/components/RightSidebar.js, public/js/components/SourceTabs.js, public/js/components/Sources.js, public/js/components/TabList.js, public/js/components/Tabs.js, public/js/reducers/breakpoints.js, public/js/selectors.js, public/js/util/test-head.js
simple find and replace. More to come
=> Replace queries with selectors

public/images/pause-circle.svg, public/images/pause.svg, public/images/resume.svg, public/js/components/Breakpoints.css, public/js/components/Breakpoints.js
Adds a pause circle next to the breakpoint that is at the pause
location.
=> Highlight the currently paused breakpoint

public/js/components/Breakpoints.js, public/js/components/Editor.js
Adds simple navigation for selecting a breakpoint.
=> Add selectBreakpoint handler on breakpoint list

karma.conf.js
Randomly ran into this and thought I’d make the karma config file pass
the eslint.
=> eslint karma.conf

public/js/components/Editor.js, public/js/util/editor.js
=> Disable APZ for source editors. Fixes #129.

public/js/create-store.js
This is an addition for issue #166. It adds support for the extension without affecting any other users.
=> Add Redux Devtools Extensions support

public/js/clients/chrome.js, public/js/clients/chrome/api.js, public/js/clients/chrome/docs.md, public/js/clients/chrome/protocol.json
WIP
Ignore the first commit that adds the chrome tabs. That's in a separate PR.
Sharing an early version of some of the chrome client work i'm prototyping. It does two things here that are both interesting:
1) sets up the websocket connection with chrome and sends some bootstrap messages over the wire
> this is the debug tab commit
2) adds the chrome inspector backend
> You can think of this piece as chromes version of our client, fronts, and protocol api. It's split into two pieces:
1) InsepctorBackend - holds onto what they call agents (our fronts)
2) protocol.json - spec of the protocol, which is used to build the agents (fronts) ([gist](https://gist.github.com/jasonLaster/f1609e7764164e829caec7814ebff533) of the dynamically built fronts)
=> WIP Chrome Client (2)

.eslintignore, package.json, public/js/actions/breakpoints.js, public/js/actions/tests/selectSource.js, public/js/clients/chrome.js, public/js/reducers/breakpoints.js, public/js/reducers/pause.js, public/js/reducers/sources.js, public/js/reducers/tabs.js, public/js/types.js, public/js/util/fromJS.js, public/js/util/imstruct.js
Just realized I haven't linted this, so there's probably a lot to do. Especially imstruct.js which is a copy from an internal tcomb file. But if you ignore that file, the rest of the changes are minimal.
=> create a few types and prepare code to handle typed objects

public/js/util/sources-tree.js, public/js/util/tests/sources-tree.js
Not quite ready for a review yet, but I wanted to get this uploaded for now.
I am running into one issue where some nodes can share a path. I'm not sure how this was previously handled. Looks like the same path, loaded twice, with a different hash... Not sure if the content was different.
```
[
{
"id":"server3.conn16.child2/167",
"url":"http://ads.pubmatic.com/AdServer/js/showad.js",
"actor":"server3.conn16.child2/167",
"pathname":"/AdServer/js/showad.js",
"filename":"showad.js"
},
{
"id":"server3.conn16.child2/196",
"url":"http://ads.pubmatic.com/AdServer/js/showad.js#PIX&p=32575&s=39805&a=60123&it=0&kdntuid=1",
"actor":"server3.conn16.child2/196",
"pathname":"/AdServer/js/showad.js",
"filename":"showad.js"
}
]
```
=> Added ability to collapse folders, resolves #160

public/js/components/Editor.css, public/js/components/Editor.js, public/js/components/EditorBreakpoint.js, public/js/util/editor.js
Breakpoints before looked a little off and it was driving me crazy. This makes them align perfectly with the line numbers, and also load instantly. 
On my computer, I'm still having the issue where line numbers are slightly off, so the breakpoints are 1px off for me but they should be perfectly aligned for everyone else. I still need to figure out the line number issue that I'm seeing.
=> pixel-perfect breakpoint icons

public/js/components/RightSidebar.css, public/js/components/SourceTabs.css, public/js/components/Sources.css
=> Undo top-bar spacing change from issue #188 as it looks weird in the

public/js/util/fromJS.js
We have to do this when integrating into Firefox. The protocol gives us JS objects that were created in a different JS context, so `Object !== Object`. The previous method for detecting objects didn't pass, so they weren't being converted into immutable objects. This was breaking the frames list and the scope inspector.
The good thing is this will all go away once we have tcomb immutable types. It will know how to convert JS objects automatically and we can turn anything into typed objects without needing to check them.
=> make fromJS more loosely detect objects for cross-frame support

karma.conf.js, public/js/components/Frames.js, public/js/components/stories/Frames.js, public/js/components/stories/Scopes.js, public/js/components/stories/SplitBox.js, public/js/components/stories/editor.js, public/js/components/stories/index.js, public/js/components/stories/utils.js, public/js/components/test-utils.js, public/js/components/tests/Frames.js, public/js/components/tests/Scopes.js, public/js/components/util/Arrow.js, public/js/test/utils/renderComponentFromFixture.js
+ Add frames unit tests
+ DRY up the unit tests / and stories with a new `renderComponentWithFixture` helper.
=> Update Unit Tests

CONTRIBUTING.md
Here's my first pass at a CONTRIBUTING document for #51
Things I would like to finalize but didn't get to:
* Git commit message style guide
* We don't seem to really have a style guide for commit messages yet so I didn't want to generate one
* Better way to describe the JS and CSS style guides
* The .*rc files do this but I'd like to give an overall description
=> initial pass at a CONTRIBUTING guide

CONTRIBUTING.md
Found the previous version of this sentence a tad confusing.
=> Modified sentence in the contributing doc to be more clear

bin/development-server.js, public/js/clients/firefox.js, public/js/configs/development.json, public/js/configs/feature.js, public/js/main.js, webpack.config.js
As a first step to switching towards a tool like nconfig,
this patch organizes the config data in feature.js
There are a couple other cleanups in here, but they're relatively minor
=> Organize configs

package.json
Hi @jasonLaster I cloned the repo and had to add this dependency for `npm start` to work.
After that it works like a charm
=> add minimist to dependencies

bin/development-server.js, circle.yml
Just doing this to get a failed circle run so I can investigate it
=> fix development-server.js to work on node <6 (fixes cypress tests)

README.md
Trying to help people find their way to our IRC room. I punted on a new channel name as i don't think that should be a blocker.
=> Add Getting Involved Section

package.json, public/js/actions/sources.js, public/js/clients/chrome/events.js, public/js/clients/firefox/events.js, public/js/clients/index.js, public/js/main.js, public/js/types.js, public/js/util/networkRequest.js, public/js/util/source-map.js
Fixes #306 and #304. 
I'll look into showing sources in the editor next. Also, the `source-map` utility is still being thought through. I'm working on using the smallest APIs so that i can explore the problem.
Note, the domain is not properly parsed in some cases. I can fix this later
=> Show original files in sources tree

public/js/actions/sources.js, public/js/types.js, public/js/util/source-map.js
This work builds on the initial PR. It was done before you reviewed the first one so there are things that you commented on that I have not touched yet.
=> Show original sources in editor

config/feature.js, public/js/components/Editor.js
=> Only handle wheel events in firefox

circle.yml
Forgot to actually make flow run in CI
=> add flow to CI

public/images/angle-brackets.svg, public/images/close.svg, public/images/globe.svg, public/images/magnifying-glass.svg, public/images/pause-circle.svg
=> Add SVG License header

public/js/components/App.js
=> Fix Windows search

public/js/actions/sources.js, public/js/util/source-map.js
+ underscore private methods
+ rename setSourceMap to setConsumer and make it private
+ move some methods around
=> Additional source-map util refactors

CONTRIBUTING.md, README.md, docs/remotely-debuggable-browsers.md
(don't merge this yet, I need to update the contributions page to match)
no screenshots yet, those may come
focused on a headline, getting started, getting involved, and getting in contact
=> Rewrite of the README (WIP)

public/js/lib/tree.js
goes from dom.scrollTo to dom.scrollTop, which is chrome compat
=> Update tree scroll

public/js/actions/pause.js
Small PR for translating the pause frame to the original location
=> translate pause frame

package.json, public/js/reducers/sources.js
I'm only making a PR to test that flow will actually fail now. It should.
These fixes aren't ideal but we'll probably need to refactor this code some for easier typing.
=> quick fixes for flow in sources reducer

config/development.json
=> remove reduxDevtools from config/development.json

CONTRIBUTING.md, config/README.md, config/development.json
also fix up the `npm run firefox` command
=> update the configuration settings

CONTRIBUTING.md, README.md, config/README.md
A bunch of the links were incorrect as titles have changed.
=> fix up the links in the docs

public/js/utils/sources-tree.js, public/js/utils/tests/sources-tree.js
After looking into so many things, it turned out to be easier than I thought. @jasonLaster 
Let me know if this is fine.
=> Fix source map domain issue and decoding URI (#328)

bin/development-server.js
localhost restricts the development server to the local system where
0.0.0.0 allows for external access
added a message to indicate when hot reloading is disabled
lots of other cleanups in the file
=> allow development server to be publicly reachable

public/images/pause-exceptions.svg
=> Add new pause on exception icon

config/config.js, config/feature.js, webpack.config.devtools.js, webpack.config.js
=> introduce TARGET env variable for config

docs/remotely-debuggable-browsers.md
=> #458, How to connect to Firefox on Android

public/js/components/Tabs.css, public/js/components/Tabs.js
Added target instructions on the landing page according to the comments in #378.
=> add target instructions (#378)

public/js/components/SourceFooter.js
@jasonLaster added feature flag for blackbox icon
=> add feature flag for blackbox icon (#437)

.gitignore
=> Add webstorm and vscode files to .gitignore

public/js/components/App.js, public/js/components/Autocomplete.css, public/js/components/Autocomplete.js
Basic handling of up/down/enter/escape.
This is WIP, but I'm not sure how to advance. Here are my issues:
1) When list of sources overflows the container, scrolling doesn't happen automatically. I tried another solution which uses tabindex to focus the "li" but it didn't behave well and I don't think it's right. I was thinking about doing the scroll by myself, but it feels like there should be a ScrollView component for consistency (e.g. with the left pane's list of sources)
2) I wasn't sure if there are tests for components and where I should write tests for my code
3) getSearchResults is called on every keydown event, since it's needed in case of down/enter. I noticed it is also called on every input change, and figured it's not as expensive as I thought.
4) I wasn't able to …
=> re #337 - file search keyboard navigation

public/js/components/RightSidebar.js, public/js/components/SourceFooter.js
added tooltips to icons (#476)
=> added tooltip to icons (#476)

circle.yml, config/ci.json, config/config.js
This adds a ci.json config that lets us have separate features / configs for our ci environment.
It also removes the chrome flagging which in comparison seems like debt.
=> Setup ci.json

public/js/test/cypress/commands/debugger.js, public/js/test/integration/todomvc.js
Adds a pretty print test
Also cleans up some of integration test timing
=> Test improvements

public/js/test/cypress/commands.js, public/js/test/cypress/commands/utils.js, public/js/test/fixtures/pythagorean.json, public/js/test/fixtures/todomvc.json, public/js/test/fixtures/todomvc.updateOnEnter.json, public/js/test/integration/fixtures.js
This is a follow up from the client logging PR.
=> Sanitize the app state

bin/development-server.js
I forgot to make a pull request for this one. @clarkbw
=> prevent http get crash (#389)

bin/development-server.js, circle.yml, config/feature.js, config/tests/feature.js, docs/feature-flags.md, public/js/actions/sources.js, public/js/clients/chrome.js, public/js/components/RightSidebar.js, public/js/components/SourceFooter.js, public/js/components/SourceTabs.js, public/js/utils/source-map.js, webpack.config.js
=> Update isEnabled api

public/js/components/Sources.css, public/js/components/Sources.js, public/js/components/tests/Frames.js, public/js/components/tests/Scopes.js, public/js/test/cypress/commands/utils.js, public/js/test/fixtures/pythagorean.json, public/js/test/fixtures/todomvc.json, public/js/test/fixtures/todomvc.updateOnEnter.json, public/js/test/integration/fixtures.js
=> add sources header back to the sources tree

README.md
=> add headline screenshot to README

public/js/components/Scopes.js, public/js/test/cypress/commands/debugger.js, public/js/test/examples/debugger-statements.html, public/js/test/examples/exceptions.html, public/js/test/examples/iframe.html, public/js/test/integration/todomvc.js
This is a work in progress. There are several things in here is like to discuss
Tests:
* Pausing in an Iframe
* stepping over an exception (viewing it in the scopes pane)
=> Additional Test Coverage

public/js/clients/firefox/events.js, public/js/components/App.js, public/js/components/RightSidebar.js, public/js/test/cypress/commands/debugger.js, public/js/test/examples/evals.html, public/js/test/integration/todomvc.js, public/js/utils/event-emitter.js, public/js/utils/sources-tree.js
This is the follow up issue to #531.
=> Add Break On Next and eval tests

CONTRIBUTING.md
With links to the updated wiki page
https://wiki.mozilla.org/DevTools/CodingStandards
Fixes #513
=> adds a coding standards section

public/js/components/Breakpoints.js, public/js/components/Editor.js
Fixes #525.
This fixes a problem we were seeing where breakpoints would be updated while loading, which caused an exception.
=> Breakpoints loading

public/js/components/SourceFooter.js, public/js/utils/source-map-worker.js, public/js/utils/source-map.js
=> Hide pretty-print button from mapped files

public/js/test/integration/tests.js
The integration tests now test far more than todomvc and should reflect that.
this is the smallest pr you will see all day
=> Rename todomvc to tests

public/js/components/SourceFooter.css, public/js/components/SourceFooter.js, public/js/reducers/sources.js, public/js/selectors.js, public/js/test/integration/tests.js, public/js/utils/source-map-utils.js, public/js/utils/source-map-worker.js, public/js/utils/source-map.js, public/js/utils/source.js, public/js/utils/sources-tree.js
=> Pretty Print UX

public/js/components/App.js, public/js/components/RightSidebar.js, public/js/lib/devtools-sham/client/shared/key-shortcuts.js
This is a follow up PR from #540.
I'll file an `m-c` issue soon to address the change
=> Add keyboard shortcuts for the debugger

public/js/components/App.js, public/js/test/cypress/commands/debugger.js
Follow up from #585 with a platform fix as well for search. Borrows from the Services check as well
=> File search all platforms

public/js/components/Scopes.js
This fixes an issue caused by the recent scopes refactor where the special variables were not being added.
Thanks integration tests for letting me know. Sorry I didn't believe you the first time :/
=> Fix special variables

public/js/components/Scopes.js
This fixes some things mentioned in the last scopes PR #579
=> Scopes touch up changes

CONTRIBUTING.md
#596 mentioned this port change.
=> Update contributing.md to have the right port value for Chrome.

public/js/components/ObjectInspector.js, public/js/components/Rep.js, public/js/lib/devtools/client/shared/components/reps/rep.js
Issue #594 - Not 100% sure I exposed the prop right so some review is nice.
=> Replace Object formatting with text

public/js/components/RightSidebar.css
Fixes #605
Simple change of the container to make it a flex container and add the proper scroll support for the accordion.
=> Fixed right sidebar header

public/js/components/Scopes.js, public/js/test/fixtures/pythagorean.json, public/js/test/fixtures/todomvc.json, public/js/test/fixtures/todomvc.updateOnEnter.json, public/js/test/integration/fixtures.js, public/js/utils/dehydrate-state.js
+ updates the fixtures 
+ updates `getScopes` to not allow null selectedFrame
+ updates `dehydrateState` to include selected frames
=> Fix scope storybook stories

public/js/clients/chrome.js, public/js/clients/firefox.js, public/js/lib/devtools-sham/shared/client/main.js, public/js/utils/networkRequest.js
Pulled in  #577  and did a quick rebase and the tests passed.
=> move network timeout code to connect()

public/js/components/SourceFooter.js
=> Hide pretty print button for original sources

public/js/components/SourceTabs.css, public/js/lib/themes/variables.css
Naming things in ```variables.css``` is hard and I dislike it
=> Fix #653, finesse selected tab designs

public/js/components/Breakpoints.css, public/js/components/Breakpoints.js
@jasonLaster, this includes code from your patch in #604. I've never committed with someone before, do you know how that's done? (I just copied and pasted what you had left in the comments.)
=> Format breakpoints in sidebar with @jasonLaster, fix #604

docs/mochitests.md, public/js/test/mochitest/head.js
Simple way to pause and then resume a test which lets you interact with the debugger.
=> Add pauseTest command

public/js/test/mochitest/.eslintrc, public/js/test/mochitest/browser.ini, public/js/test/mochitest/browser_dbg_chrome-create.js, public/js/test/mochitest/browser_dbg_chrome-debugging.js
Fixes #638 
As a side-note, it amazes me how much cleaner the `yield` syntax can be than promises.
=> Test Toolbox

public/js/components/RightSidebar.js, public/js/test/mochitest/.eslintrc, public/js/test/mochitest/browser.ini, public/js/test/mochitest/browser_dbg_keyboard-shortcuts.js, public/js/test/mochitest/head.js
It took me some time but I think I'm almost there. thanks to @jlongster and @jasonLaster's previous tests. I tried to replicate the original test to a good extent.
I would like to know if there is a better way `ensureThreadResumed` than what I did? Let me know what you think and I will make changes accordingly.
=> add tests for keyboard shortcuts (#642)

bin/make-firefox-bundle
Jumped the gun on #723. Here's an updated version
=> use installed version of webpack

public/js/components/RightSidebar.js, public/js/test/mochitest/browser_dbg_keyboard-shortcuts.js, public/js/test/mochitest/head.js
**WIP**
This is how Chrome deals with it. After it is resolved, I'll go ahead and file a bug/patch in m-c for the old debugger.
PS: I took that test because it seemed the easiest of the lot, but turned out to be a rabbit hole. Haha.
=> fix key shortcut on linux (#715)

public/js/test/mochitest/head.js
Honestly, this is mostly driven from my editor not finding these two functions when they're assignments.
With that said, I think it's nice for the functions not to be decorated in this way. But it's just style...
=> Inline test Tasks

public/js/components/App.js, public/js/test/mochitest/browser.ini, public/js/test/mochitest/browser_dbg-console.js
This is ready to be merged once the [m-c patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1302202) lands.
=> Add tests for console split panel

CONTRIBUTING.md, bin/firefox-driver.js, docs/remotely-debuggable-browsers.md
after a few hours trying to figure out why I cant run this on a windows machine,  I found these changes will make it work.
BTW, the tests cant even start on windows, so I couldent run them locally either :(
=> fix flag for windows

docs/remotely-debuggable-browsers.md
=> add docs for connecting to safari on iOS

CONTRIBUTING.md, docs/mochitests.md
I'm making small updates to the docs as they are a little outdated. I noticed that API list is not exhaustive. If you'd like I can update that in this PR also.
=> update mochitest docs

public/js/components/SplitBox.css, public/js/components/SplitBox.js
This should fix #669. My first PR here, mostly to try things out really. Let me know what you think. There was comment in the issue that seemed to indicate that this issue was fixed by some other work, but I wasn't sure. So I took a stab at it anyway.
=> Fixes #669 by adding a wider splitter handle

public/js/clients/firefox.js, public/js/main.js
This also requires a small fix on mc's panel.js but the main idea is here.
=> Wait on sources

bin/download-firefox-artifact, docs/mochitests.md
Didn't realize that `hg pull` doesn't actually change the local files, which is really confusing.
=> Actually update local files when updating local firefox repo (fixes #772)

public/images/breakpoint.svg, public/js/components/EditorBreakpoint.js
Refactors the editor breakpoint to re-use the svg
=> Refactor editor breakpoint

config/development.json, public/js/components/App.css, public/js/components/App.js, public/js/components/Editor.css, public/js/components/Editor.js, public/js/components/SourceFooter.css, public/js/components/SourceFooter.js, public/js/utils/source-editor.js
The easiest thing to do is to just look at the second commit.
=> Fixes the code search ui (part 1)

public/js/components/SourceTabs.css
=> Remove active tab border

public/js/lib/devtools-sham/sdk/util/uuid.js, public/js/utils/redux/middleware/promise.js
@jlongster since we talked on irc.
=> Use just an incrementing number rather than fake uuid

public/js/components/App.css
See #670 for before and after.
=> Fix 670 - remove font-family

CONTRIBUTING.md
Updates the need for running unit tests, not necessarily all tests
Adds a line item to the PR section for the required review
Includes links to the GitHub Review system.
=> include the review system in the the PR section of the docs

public/js/components/Editor.css, public/js/components/Sources.css, public/js/components/Sources.js
I still need info from @helenvholmes regarding the font-size and CSS styling. 
This is what I have at the moment:
=> Add search keycommand info above Sources. Fixes #622

.github/PULL_REQUEST_TEMPLATE
* add a PR template
@jlongster @jasonLaster this a very bare bones template but I figured it's a good start. I'll adjust it to any feedback.
=> Enhancement: Add a PR template to guide contributors in what to put in their PRs.

package.json
=> Fixed Check Node Version

public/js/components/App.js, public/js/components/Sources.js, public/js/utils/text.js
* Use the ⌘ symbol instead of the text `Cmd`
* Made the text in the centre pane more direct
* `⌘+P to search for files`
=> use the ⌘ 'place of interest' icon for mac

public/js/components/Breakpoints.css, public/js/components/Breakpoints.js, public/js/components/CloseButton.css, public/js/components/CloseButton.js, public/js/components/SourceTabs.css, public/js/components/SourceTabs.js
Associated Issue: #606 
* add breakpoint remove button
=> Add breakpoint remove button.

CONTRIBUTING.md
Associated Issue: #781 
* document the logging options
=> Add a section to the contributing docs cover the logging options.

public/js/components/ObjectInspector.css, public/js/components/RightSidebar.css
Associated Issue: #700
* adjust padding of scope items
* change background color for zebra striping scope items to a more noticeable one.
Hover effect? @SezginEge suggested this.
=> Right sidebar tweaks

index.html
Associated Issue: #852 
* add `dir` attribute to the main html element of index.html
=> Add `dir=""` to the html tag on the index.html

public/js/components/SourcesTree.js
Associated Issue: #864 
* remove an inline style that was overriding the proper tree overflow
=> Fix Source Tree Scrolling

public/js/components/App.js
=> Fix #856 - right sidebar width

public/js/components/App.css, public/js/components/App.js, public/js/components/Autocomplete.js, public/js/components/Editor.css, public/js/components/Editor.js, public/js/components/EditorSearchBar.css, public/js/components/EditorSearchBar.js, public/js/components/RightSidebar.js, public/js/components/SourceFooter.js, public/js/components/SourcesTree.js
Associated Issue: #792 
* summary is on the right because i was not sure how to position it next to the query. Also, not sure if it would look good as you are typing
* i left the close button out because the summary is on the right and cmd+f and escape close. This feels like enough in practice
* i select the text when the search bar is opened so you have the cursor in the right spot and can delete before you type
* the results summary wraps
=> Style search bar

bin/preinstall
Associated Issue: #936 
* change the preinstall script's lerna finding behavior and install @jasonLaster's fork in either case
=> Improve the detection of lerna and make sure we install the local fork

packages/devtools-local-toolbox/bin/development-server.js
=> replaced registerConfig call

packages/devtools-config/registerConfig.js, public/js/actions/tests/sources.js, public/js/test/node-unit-tests.js
+ fix npm test for node 6.1 - 6.3 as well as node 5.x
+ suppress test warnings for node >6.6
here's the convo w/r/t node 6.1-6.3 https://twitter.com/jasonlaster11/status/789155482594271232
=> Fix node 6.5 npm test

public/js/components/Editor.css, public/js/components/Editor.js, public/js/components/SourceFooter.js, public/js/utils/editor.js
Associated Issue: #891, #949
- The footer no longer overlays the editor
- The footer is hidden when there is nothing to show
- Remove eroneous things
- Don't let users pretty print pretty files or bundle files
=> Improve editor layout

public/js/components/Editor.js
=> Fix footr2

docs/local-development.md, packages/devtools-config/configs/development.json, packages/devtools-local-toolbox/public/js/components/Root.js, packages/devtools-local-toolbox/public/js/index.js, packages/devtools-local-toolbox/public/js/lib/themes/dark-theme.css, public/js/components/App.js
Fixes #934
Associated Issue: #370 
* removes redundant class
* makes it easy to change themes locally
=> Clean up themes

public/js/components/Autocomplete.css, public/js/components/Autocomplete.js, public/js/components/SourceSearch.css, public/js/components/SourceSearch.js
Associated Issue: #780 
* rework file search UX to match the spec linked in issue more closely
=> File Search UX Updates

public/js/constants.js, public/js/reducers/breakpoints.js, public/js/reducers/pause.js
Small tweaks to help the flow score. Also removes spurious AppState calls
=> Small flow tweaks

docs/local-development.md, packages/devtools-local-toolbox/public/js/index.js, packages/devtools-local-toolbox/public/js/lib/themes/firebug-theme.css
Associated Issue: #996
* adds firebug for local development
=> Add firebug theme

docs/local-development.md
Adds some simple flow docs to help contributors make use of flow
=> Add flow docs

public/js/main.js
We always should be able to do `NODE_ENV=production npm start`.
=> Allow running in production mode locally

public/js/components/SourceSearch.js, public/js/utils/assert.js
Associated Issue: #1039
* Filtering out pretty sources
=> Source search hide pretty

public/js/actions/breakpoints.js, public/js/actions/sources.js
Saw this in an associated greenkeeper PR.
I'm not sure why eslint has been silent here...
=> cleanup spacing

packages/devtools-config/src/feature.js, public/js/actions/sources.js, public/js/utils/assert.js
Associated Issue: #1034
- Adding missing flow type annotations and conditional check got deferred
=> Adding missing annotations and conditional check got deferred

packages/devtools-local-toolbox/public/js/components/LandingPage.css
=> Fix #1027: fixes colors for langing page in light theme and dark theme

public/js/actions/sources.js
=> close source search when a source is selected

public/js/types.js, public/js/utils/path.js, public/js/utils/source-map-util.js, public/js/utils/source-map-worker.js, public/js/utils/source.js
Associated Issue: #1005
- Type the Source Map Worker
=> add flow types to source maps worker

public/js/components/Frames.js, public/js/test/mochitest/browser.ini, public/js/test/mochitest/browser_dbg-call-stack.js, public/js/test/mochitest/examples/doc-frames.html, public/js/test/mochitest/examples/frames.js, public/js/test/mochitest/head.js
Fix #1056 
* hides expand rows when there aren't enough frames
* refactors frames to cleanup the frame rendering logic + toggle button logic
=> Expand rows

public/js/components/SourcesTree.js
Fixes #1099
This is a step in the right direction I think. Showing everything can be jarring.
=> Show 1 level in the Source Tree

public/js/components/Editor.js, public/js/components/SourceTabs.js
* fix an id
* fix access keys (and tested access keys in panel)
* tabs touchup
=> Fix context menu properties

public/js/components/Autocomplete.css, public/js/components/Autocomplete.js, public/js/strings.json
Associated Issue: https://github.com/devtools-html/debugger.html/issues/1068
* Add a summary for the number of results
=> Result count in search

public/js/utils/source-map.js
* Added boolean type to shoudSourceMap() for flow
=> Added boolean type to shoudSourceMap()

public/debugger.properties, public/js/components/SourceTabs.js, public/js/strings.json
Associated Issue: #1104
* Add new properties
* Added new closeOtherTabs and closeTabsToRight
=> Additional close items

public/js/components/Autocomplete.css, public/js/components/Autocomplete.js
Associated Issue: #1141
* Add spacing around the "instances" text
* Don't show anything when 0 search results
=> Clean summary field

public/js/test/mochitest/browser.ini, public/js/test/mochitest/browser_dbg-breakpoints-cond.js, public/js/test/mochitest/browser_dbg-breakpoints.js, public/js/test/mochitest/browser_dbg-searching.js
Tests are failing on try. The breakpoints test is taking too long (I was worried about that) and for some reason the searching test can't find an element, so I'm hoping waiting for it fixes it.
=> Split breakpoints mochitests up and tweak searching test

public/debugger.properties, public/js/components/Breakpoints.js, public/js/components/Editor.js, public/js/components/EditorConditionalPanel.js, public/js/components/Expressions.js, public/js/components/SourceFooter.js, public/js/strings.json
Moved from https://github.com/devtools-html/debugger.html/pull/1148
=> [L10N] Fix hardcoded strings. Fixes #1143

README.md
* Fresh screenshot with some of the latest layout updates
Nope, did this all via the web interface.
See Rich Diff mode.
=> Update screenshot of the debugger in the README

package.json, public/js/components/RightSidebar.js, yarn.lock
This should help resolve the issues we're seeing with eslint where the newest version has the one lint issue. Once we land this, the webdriver fix will be unblocked
=> Bump eslint

docs/local-development.md
Noticed wee didn't have any local dev docs for RTL.
=> Add RTL docs

.stylelintignore, .stylelintrc, package.json, packages/devtools-local-toolbox/src/components/Root.css
Associated Issue: None, discussed directly with @jasonLaster in IRC.
* Updated css lint script to check over package files.
* Removed comment stylelinting since there are quite a few non-alignable things existing. We should document a standard structure on how/when to comment and then update the codebase's comments along with that.
* Updated all remaining issues within the files to pass the linting.
=> chore(stylelint): Lint package styles and address existing problems.

assets/locales/debugger.properties, src/components/Breakpoints.js, src/components/Editor.js, src/components/EditorConditionalPanel.js, src/components/Expressions.js, src/components/SourceFooter.js, src/strings.json
Re-opening the L10N strings PR
=> L10n strings

src/components/EditorSearchBar.js
Associated Issue: #1177 
* get the selected text and place it in the searchbar when pressing cmd/ctrl+f
=> File Search uses selected text

bin/getConfig.js
This broke with the toolbox change
=> [toolbox] Fix local config

configs/development.json, configs/firefox-panel.json, packages/devtools-config/src/feature.js, src/actions/sources.js, src/components/SourceTabs.js, src/utils/editor.js, src/utils/source-map.js
Associated Issue: #1205 
* Remove Tabs, SourceMaps, Pretty Print feature flags.
=> Remove feature flags

.github/PULL_REQUEST_TEMPLATE
One question I always have when reviewing a PR is "what could break?". 
It would be great to see what scenarios the author tested to get a sense of what edge cases were already explored and what edge cases might not have been explored.
I'm not quite sure if I like the language
>  Tell us a little a bit about how you tested the patch.
it could probably be word smithed. 
I removed the two check boxes because with husky we now require that these two checks pass and I have not found a case where it's been helpful. If others feel like it is keeping authors honest I don't feel strongly.
Lastly, I think it would be helpful to prompt people to take a look at our testing script document that will give them an idea of what to check for all of the possible PRs. We're working on this now and when …
=> Add a test plan

bin/getConfig.js, configs/application.json, configs/firefox-panel.json, package.json, packages/devtools-config/README.md, packages/devtools-config/src/feature.js, packages/devtools-local-toolbox/src/clients/firefox.js, packages/devtools-local-toolbox/src/components/LandingPage.js, packages/devtools-local-toolbox/webpack.config.js
* Adds an application.json for App specific configs and update configs
* Adds a hostURL so that the application knows how to resolve paths
* firefox tab connection
* worker paths ...
* Adds a new Source header... (mostly for show)
* Where'e the app code? [repo](https://github.com/jasonLaster/debugger.app)
=> Start iterating on the standalone application

packages/devtools-local-toolbox/webpack.config.js
Quick fix for the debugger toolbox.
@juliandescottes mind taking a look?
=> Fix toolbox

package.json, packages/devtools-local-toolbox/package.json, yarn.lock
Bump the toolbox dep to pull in @juliandescottes's changes. 
This will help the inspector and other tools use the toolbox.
=> Bump toolbox

README.md
It would be great to offer a venue for contributors to 
* talk with the team
* ask questions. 
* meet each other
I think it would also be nice to promote the team [weekly call](https://wiki.mozilla.org/DevTools) as well.
@clarkbw, @jlongster, @helenvholmes, @jbhoosreddy thoughts?
@wldcordeiro, @Zacqary, @Garbee, @bomsy, @jacobjzhang, @kareniel, @amitzur, @ThomasCrevoisier, @jagtalon, @Dalimil interested?
=> Add an Open Office Hours section

configs/local.sample.json, docs/local-development.md, packages/devtools-config/README.md, packages/devtools-local-toolbox/src/components/Root.js
Associated Issue: #1307, #1297
* improve config
* improve local config
* improve themes
* add SVG section
=> Improve the docs

packages/devtools-modules/client/shared/components/splitter/SplitBox.js, src/components/App.js
Associated Issue: #1266
* switch debugger to the vertical layout when it's less than 700px wide
=> Vertical layout

configs/development.json, src/components/App.js
=> [Vertical Layout] feature flag

src/components/SourceTabs.css
As a follow up to #1305,
please share what you think,
@jasonLaster @wldcordeiro
=> fixed active tab header seperation

packages/devtools-sham-modules/client/shared/components/tree.js, src/components/SourcesTree.js
See https://github.com/devtools-html/debugger.html/issues/1337#issuecomment-264318724
=> [Source Tree] show first root #1337

README.md
Rest of the README.md is also in "we" form and not "I"
=> [typo] "we" recommend not "I"

packages/devtools-local-toolbox/package.json
Associated Issue: #1361 
* here's the PR https://github.com/smikhalevski/single-module-instance-webpack-plugin/pull/2
* hopefully it gets merged and we can go back to the branch
@juliandescottes and I worked on this today. He deserves half of the credit and blame
CC @juliandescottes
=> Add HMR support to SMP

configs/development.json, configs/firefox-panel.json, src/components/SourceTabs.js
Associated Issue: #1336
* Add "Copy Link Address" function for source tabs
=> (WIP) [Source Tabs] context menu copy source url + view source

yarn.lock
I recently bumped the debugger's package.json without bumping the yarn lock...
this should be pretty simple to approve
=> bump yarn lock

assets/locales/debugger.properties, configs/development.json, src/actions/event-listeners.js, src/components/EventListeners.css, src/components/EventListeners.js, src/components/RightSidebar.js, src/reducers/breakpoints.js, src/reducers/event-listeners.js, src/strings.json
Associated Issue: ???
* I paired with @quodlibetor to create a minimal event listeners UI
* I added support for adding/removing associated breakpoints as well
* The styling and UX is all very prototypy and will definitely change
=> Event Listeners (part 1)

assets/images/refresh.svg, src/components/Accordion.css, src/components/Accordion.js, src/components/RightSidebar.js
Associated Issue:#1347
* added "refresh" button in Watch Expressions as SVG
* added "add" button in Watch Expressions as char
https://github.com/devtools-html/debugger.html/issues/1347#issue-192350493
Enable watch expressions in config/local.json
The new buttons should look like lin Chrome https://cloud.githubusercontent.com/assets/254562/20721502/f53bf546-b630-11e6-8472-bc36ff1a2b7a.png
[Before](https://cloud.githubusercontent.com/assets/254562/20721494/e8cd2f82-b630-11e6-8080-02c092e5272b.png)
[After](https://cloud.githubusercontent.com/assets/922368/21114739/0053ea22-c0a6-11e6-8d2c-38b252e6ab24.png)
=>  #1347 final fixes for watch expression

package.json, packages/devtools-client-adapters/package.json, packages/devtools-client-adapters/src/chrome.js, packages/devtools-client-adapters/src/chrome/commands.js, packages/devtools-client-adapters/src/chrome/events.js, packages/devtools-local-toolbox/webpack.config.js, webpack.config.js
Associated Issue: #1310
* drop chrome-remote-debugging-protocol
* use chrome-remote-interface
This requires https://github.com/cyrus-and/chrome-remote-interface/pull/65 to land first.
=> (WIP) Start using CRI

assets/locales/debugger.properties, src/components/RightSidebar.js, src/strings.json
Fix header button keys
* fixes watch expression header button keys
* also internationalizes them
=> Fix header button keys

assets/images/Svg.js, assets/images/toggle-panes.svg, package.json, src/components/App.js, src/components/Dropdown.css, src/components/SourceTabs.css, src/components/SourceTabs.js, src/components/SplitBox.css, yarn.lock
Associated Issue: #1317 
* Add collapse buttons that toggle the width of the sidebars
=> Add collapsible sidebars

package.json
Associated Issue: #1463
* update devtools-launchpad to version 0.0.17
Closes #1463
https://greenkeeper.io/
=> fix(package): update devtools-launchpad to version 0.0.17

src/components/ObjectInspector.js
Associated Issue: #1452 
* add sort method to scope properties 
=> sort properties by name

circle.yml
https://circleci.com/docs/configuration/#artifacts
=> Add yarn-error.log as an artifact

src/components/SourceTabs.css, src/components/SourceTabs.js
=> #1460 Polish: Add pretty print icon to source tabs, remove ':formatted' from file name

src/components/Frames.css
Associated Issue: #1119
changed styling of callstack component to flex.
@jasonLaster you can open a seperate issue for rtl-styling of the breakpoints component and I'll tackle that one as well.
=> callstack component - switched to flex

README.md, docs/getting-setup.md
Associated Issue: #1483
* Update Yarn docs to refer to the latest version of Yarn `0.18.1`
=> Yarn update docs

package.json
Twice now, i've run into a bug where the debugger implicitly bumps to react 15 and this fixes the problem.
=> Add React Version

docs/local-development.md
Noticed some ways these could get better
CC @amitzur, @gasolin, @clarkbw, @liorpr
=> Update rtl docs

circle.yml
* copy the `ci.json` file instead of move it (prevents unneeded change in repo)
* add `$MOCHA_FILE` env so it correctly lands in the artifacts area
=> some small fixes to the circleci config

src/components/Autocomplete.js
Fixes : #1467
* use both the id and value for a unique React key
(on cnn.com)
=> ensure unique keys for Source Search React elements

src/components/SourceTabs.js, src/utils/sources-tree.js, src/utils/tests/sources-tree.js
Associated Issue: #1476
* Fixes incorrect tab name
=> Fixes #1476: odd/incorrect tab name

circle.yml
tried following the docs more closely
https://github.com/jasonLaster/circleci-docs/blob/48d7cb611e143aacf334a0abbd998a942532f10d/jekyll/_docs/install-and-use-yarn.md
Not really sure what this will do :)
=> Yarn + CI == yikes

src/reducers/pause.js, src/utils/prefs.js
Associated Issue: #880
* Add pref defaults
* Set the pref variables
* Save the prefs on `PAUSE_ON_EXCEPTIONS`.
* Use the prefs settings on creation of the state
=> Persist poe state

docs/feature-flags.md
Fixed the documentation broken links to the configs directory
=> Fix documentation broken links to configs directory

src/components/Dropdown.css, src/components/SourceTabs.css
Associated Issue: #1489 
* toggle-button-start flexed 1
* toggle-button-end flexed 1
* source-header displayed flex and row wrapped
* new-tab btn now has 20px margin start
=> update flexs for source header and tabs (fixes #1489)

src/components/Expressions.css
Associated Issue: #1523
* Only show the close button on hover.
* Add flexbox for the expression.
=> [Watch Expressions] cleanup close button

configs/development.json, docs/local-development.md
Updates our docs on RTL based on this launchpad change: https://github.com/devtools-html/devtools-core/pull/44
CC @nchevobbe, @juliandescottes, @clarkbw
=> Dir config

assets/locales/debugger.properties, src/components/App.js, src/components/EditorSearchBar.js, src/components/SourceSearch.js, src/components/Sources.js, src/strings.json
Associated Issue: #1078 
* l10n cmd+F and cmd+G shortcuts
* l10n cmd+P shortcut
=> L10N shortcuts #1078

bin/update-yarn-lock-file
The final git push was failing because it needs to be `git push origin $CIRCLE_BRANCH`, other fixes are just nice things to make it work a bit better.
=> some updates to make this work

README.md
Fixed the Open Office Hours link
=> Fix Open Office Hours link

docs/local-development.md
Update the docs to give an example of adding a style to just one theme
=> [docs] update theme color docs

assets/locales/debugger.properties, src/actions/pause.js, src/components/Expressions.css, src/components/Expressions.js, src/components/SecondaryPanes.js
Associated Issue: #1491
* removed the "+" button
* improve style for light and dark themes
* improved watch expressions UI
=> make UI changes to Watch Expressions Component (#1491)

src/components/Editor.js
=> Fix gutter context menu

src/lib/codemirror-mozilla.css, src/utils/source-search.js
Associated Issue: #1329
* Rewrite the tokenize function to do a character based search rather that a token based
* Add css styles for highlight search
=> Selection highlight

src/components/SourceTabs.js
=> Fix Pretty Print context menu

src/actions/pause.js, src/components/Editor.js, src/strings.json
Associated Issue: #1596 
* Add context menu when string is selected in editor to add watch expression
=> Add watch expressions by context menu in editor (#1596)

bin/copy-assets.js
We need to copy the default prefs over when we copy assets.
=> Add prefs to copy-assets

src/components/WhyPaused.css
Associated Issue: #1604 
Just minor CSS changes such as 
* background
* border
* font-size
=> Styling the [WhyPaused] UI

src/components/Editor.js, src/utils/source-search.js
Associated Issue: #1633
* Highlight and search on editor selection by double click
* remove highlight when selection removed
* select previous and next text with key shortcuts.
=> highlight and search on editor selection (#1633)

docs/local-development.md
* Noticed that we were missing some top level TOC items. 
* also the two config items could be merged
=> update local config

src/components/ObjectInspector.js
Associated Issue: #1601 
* when we updated reps we didn't use the new MODEs, this fixes that.
* you'll see that the previews are tiny again
=> Use reps modes

webpack.config.js
Fixes https://github.com/devtools-html/devtools-core/issues/77
=> Fix the entry files

assets/locales/debugger.properties, src/components/Editor.js
Following up here: 
https://github.com/devtools-html/debugger.html/pull/1678#pullrequestreview-16050192
=> Fix search again

src/actions/expressions.js, src/actions/index.js, src/actions/pause.js, src/components/Expressions.css, src/components/Expressions.js, src/components/SecondaryPanes.js, src/reducers/expressions.js, src/reducers/index.js, src/reducers/pause.js, src/selectors.js
Associated Issues:  #1610, #1650
* now that the Reps are tiny, using overflow hidden for horizontal scrolls is fine
* switches to a new action / reducer
CC @jbhoosreddy
=> Update Watch Expressions

assets/default-prefs.js, src/actions/sources.js, src/actions/tests/sources.js, src/actions/types.js, src/components/SourceFooter.js, src/components/SourceTabs.js, src/reducers/sources.js, src/test/mochitest/browser_dbg-sources.js, src/test/mochitest/head.js, src/utils/prefs.js
Associated Issue: #583
* Add persistTabs code to reducers and restore tabs in actions
=> Persist tabs across debuggee refreshes

bin/mocha-server.js, src/actions/tests/sources.js, src/test/node-unit-tests.js
Fix unit test bustage after merging #1691 and fix a few nits from the review.
cc @jasonLaster
=> Update Mocha runner: fix unit tests and nits from review #1691

src/lib/codemirror-mozilla.css
Pulls in changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1320053
Test Plan:
CC @juliandescottes
=> update codemirror styles

assets/images/refresh.svg
Associated Issue: #1723
* Updates refresh icon
=> Update refresh icon

src/components/SourceSearch.js
Associated Issue: #1733
Increased path to 100 chars
Heres a screen shot after the change on wide view and narrow one.
=> increase search results subtitle size to 100 chars

src/components/Scopes.css, src/components/shared/ObjectInspector.js
=> Update non-enumerable styling. Fixes #1603

README.md, circle.yml, docs/getting-setup.md
* Bump the Yarn version in CircleCI
* Update the docs that reference the old version of Yarn
=> Yarn 0.19.1

src/reducers/pause.js, src/utils/client.js
Associated Issue: #1710 
use [exceptions](https://devtools-html.github.io/debugger-examples/examples/exceptions.html)
=> Fix pause on exceptions

.flowconfig
Associated Issue #1754 
our flowconfig was too mean and removed some devtools-client-adapter stuff
=> Fix client-adapter type imports

README.md
Just added a link to the README page. Let me know if it looks good
=> Add link to tracking page from README

configs/application.json, configs/development.json, configs/firefox-panel.json, configs/local.sample.json, src/components/App.js, src/components/Editor.js, src/components/Editor/SearchBar.js, src/components/SourceTabs.js
* remove feature flag usage for the following features
* vertical layout
* editor search
* copy source
* show source
* update configs to only include incomplete features
=> Remove feature flagging on "completed" features.

src/main.js
Associated Issue: #1333
* fixed issue where debugger cannot find the true container node while unmounting
thank you @juliandescottes!
=> unmount root

docs/getting-setup.md
Just a quarterly review of our setup instructions.
=> update the getting setup instructions

CONTRIBUTING.md, docs/local-development.md
Updated some of the contributing, but mostly the local development docs.
=> update the contributing and local development docs

CONTRIBUTING.md
Associated Issue: #1777 
* swap out @jasonLaster with the @devtools-html/debugger team
=> mention the team @devtools-html/debugger

bin/update-docker
This switches the docker image to my account.
* I used james' script https://github.com/jlongster/build-docker-mochitest
* it's 4.6gb so we can see how much faster it is
* @juliandescottes it should have the changes we need for reps, so if this works we can switch the reps script and start running tests tomorrow
=> Switch docker

bin/run-mochitests-docker, src/reducers/breakpoints.js
Oops, realized i didn't update the mochitest runner.
When this passes, we'll likely want to clear the cache again to make sure that the james' docker is rm'd. 
CC @juliandescottes
=> Update mochitest Runner

package.json
You can't improve what you're not measuring...
Associated Issue: #1034 
This adds some helpful report cards for different components of our app.
=> add flow report cards

src/components/Editor/Tabs.js
Small PR for an issue spotted while investigating memory leaks last week. 
(most importantly I want to trigger a CI run and see if docker update times out here as well :) )
cc @jasonLaster
=> rename invalid componentDidDismount to componentWillUnmount

src/components/SecondaryPanes/CommandBar.js
Associated Issue: #1503 
1. Moved the debugBtn function into the CommandBar component. The problem was that the event is being triggered by the keyboard, so I couldn't access the button with the event object. so I used the ref callback attribute for saving the button inside the component, and needed the "this" variable.
2. The animation with css was problematic, because the state transitions from pause: null to pause:Map(...) with every button press, so the css class toggling happens so fast you don't get to see it animates! ok well I'm not 100% percent about this but I noticed that although the state changes(and so the component's props being passed down) the span itself does not change! just being updated so I animated the element with javascript and it works.
=> Flash pressed command buttons

CONTRIBUTING.md, docs/pull-requests.md
I feel like we've been doing some really great things in our PRs which deserve to be documented.
* Added more content to screenshots
* Added a section for updates, which i've wanted for awhile
=> Update Pull Requests

src/utils/log.js
Associated Issue: #1785
yvrdev meetup - adding documentation as per Issue #1785
=> Adding Documentation - log.js

docs/local-development.md
Adds a section for creating feature flags
=> add feature flag docs

docs/pull-requests.md
This adds some additional docs for PRs. I'm trying to get coverage on different tasks related to PRs like:
1. checking out locally
2. pushing to a branch
=> Update PR docs

README.md
Associated Issue: #1826 
* added Slack link to Discussion section or README.md
I committed it to my fork, then viewed
=> added slack link into discussion section

src/components/WelcomeBox.css
Associated Issue: #1867 
* Changed a css selector to increase specificity
=> Fix position of toggle-button-end in vertical layout

CONTRIBUTING.md
Add a section to the contributing guide about **Joining the Team**.
=> added the Joining the Team section

docs/flow.md, docs/local-development.md
Here are some updates based on my discussion with @rpl and stealing from their docs: https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md#check-for-flow-errors
CC @rpl, @clarkbw, @thejameskyle
=> update flow docs

README.md, docs/local-development.md
Associated Issue: #1872 
:1st_place_medal: 
CC @clarkbw 
@bomsy, @wldcordeiro, @Zacqary, @jbhoosreddy, @arthur801031, @clarkbw are you okay fielding questions on slack?
=> 💃  Add more collaboration options

CONTRIBUTING.md, docs/issues.md
* fix links
* improve the team section 
* add talk, blog post, and meetup section
=> Update Contributing Page

configs/application.json, configs/ci.json, configs/development.json, configs/firefox-panel.json, configs/local.sample.json, docs/local-development.md, yarn.lock
Associated Issue: devtools-html/devtools-core#136
* Changed the default schemas which are tracked in the repository to a new format.
* local.json will need to be updated, but should still work with old format
=> [Features] change schema

.eslintrc, package.json, src/components/SecondaryPanes/Breakpoints.js, src/components/SecondaryPanes/ChromeScopes.js, src/components/SecondaryPanes/CommandBar.js, src/components/SecondaryPanes/EventListeners.js, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/Frames.js, src/components/SecondaryPanes/Scopes.js, src/components/SecondaryPanes/index.js
* worked on Secondary Panes
trusting integration tests and an initial page refresh
=> Es6 modules

src/components/Editor/Breakpoint.js, src/components/Editor/ConditionalPanel.js, src/components/Editor/HitMarker.js, src/components/Editor/Tabs.js
Associated Issue: #1894 
* Skipped the footer because it got difficult with the selector typing, I'll come back to it
* Skipped the index but I'll come back to that later unless someone else gets it
* I tried using `SyntheticClipboardEvent` but it doesn't seem to be typed correctly to use in the `doCopy` function.
=> Flow editor

src/components/shared/ManagedTree.js
Fixes ESLint warnings and unneeded `> 0`
=> ESLint cleanup of ManagedTree.js

src/main.js, src/test/integration/tests/pretty-print.js, src/test/integration/utils/assert.js, src/test/integration/utils/commands.js, src/test/integration/utils/mocha.js, src/test/integration/utils/mochi.js, src/test/integration/utils/shared.js, src/test/integration/utils/wait.js, src/test/mochitest/head.js
Associated Issue: #1511 
* pulls the helpers into discrete files
* adds a mocha and mochi helper file. I think i can switch them in webpack which will be cool...
mochitests pass
=> WTF: step 2 Add helpers

docs/client.md
@bomsy mentioned we should have docs for describing the relationship with the server.
This is a start
=> client docs

src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/utils/source-search.js
Issue #1832 
* selects empty queries too quickly
* searches on every cursor
=> (WIP) fix search bugs

configs/development.json, src/components/Editor/SearchBar.css, src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/utils/source-search.js
Associated Issue: #1637 
This is the remaining work for bringing search modifiers to the debugger.
* Added common search modifiers UI
* case sensitive (default true)
* whole word (default false)
* regular expressions (default false)
=> Adds search modifier UI

bin/run-mochitests-docker, package.json, src/test/integration/runner.js, src/test/integration/tests.js, src/test/integration/tests/breaking.js, src/test/integration/tests/pretty-print.js, src/test/integration/utils/commands.js, src/test/integration/utils/mocha.js, src/test/integration/utils/mochitest.js, src/test/integration/utils/shared.js, src/test/integration/utils/wait.js, src/test/mochitest/browser_dbg-breaking.js, yarn.lock
Associated Issue: #1919 
* Adds the breaking test
* update some helpers
=> [WTR] Add breaking test

src/test/integration/utils/mochitest.js, src/test/mochitest/browser_dbg-console.js, src/test/mochitest/head.js
* Copied in test change from https://bugzilla.mozilla.org/show_bug.cgi?id=1317485#c6, confirmed was passing at https://treeherder.mozilla.org/#/jobs?repo=try&revision=1abffb9a66feb8a22dd64b205701dcdd6144db74 but probably should re-run after Bug 1317819
* Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1317819 landing
=> Add regression test for bug 1317819 - webconsole logging

bin/run-mochitests-docker, src/actions/sources.js, src/components/SecondaryPanes/Frames.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-console.js, src/utils/pause.js, yarn.lock
I broke the test reporting last week when I started grepping the output. I also broke the tests earlier today with the tcomb work.
=> test fixes

docs/local-development.md
=> Adds docs on color usage

src/actions/navigation.js, src/actions/sources.js, src/components/Editor/EditorMenu.js, src/components/Editor/index.js, src/test/node-unit-tests.js, src/utils/editor/index.js, src/utils/tests/build-query.js, src/utils/tests/source-search.js
* refactor the editor and utilities further to ease cognitive load and addition of tests.
=> Further Editor refactors

docs/pull-requests.md
=> Tiny change for checkout branch

src/components/Editor/index.js, src/utils/editor/index.js
* was in the editor and wanted to do some small cleanup 
tests should pass
=> [Editor] follow up refactor

src/components/App.js, src/components/SourceSearch.js, src/components/Sources.js, src/components/SourcesTree.js
Associated Issue: #1894 
* a few Flow conversions of components, more to come
* there be dragons in the SourcesTree! I think we need a separate issue for that one as it will require a lot of in depth work to be done right.
=> Add Flow to more components

package.json
We can point contributors here when there setup is busted
=> Add a nom command for clearing out the node modules

src/utils/pretty-print.js, src/utils/source.js
Associated Issue: #1785
* Add flow to pretty-print.js
Passed
-  `yarn run flow`
- `npm run lint-css -s; npm run lint-js -s`
- `node src/test/node-unit-tests.js --dots`
=> Add flow to pretty-print.js

assets/panel/debugger.properties
Forgot one localization key in #1996 cc @jasonLaster
=> fix localization note for sourceTabs.closeTab.key

src/components/Editor/EditorMenu.js, src/components/SecondaryPanes/Frames.js, src/components/SourcesTree.js
* enables the "copy file path to clipboard"
=> enable copy

src/utils/fromJS.js, src/utils/tests/fromJS.js
Associated Issue: #1375
* updates fromJS hydrations.
* added unit tests
* tested the `array` example
=> Fix arraylike serialization

src/components/shared/ObjectInspector.js
Associated Issue: #1991
* Add function to `ObjectInspector.js` to sort (numbers in ascending order and strings in lexicographical order.)
=> [Scopes] sort properties with numbers in ascending order

src/components/SecondaryPanes/Frames.css
Associated Issue: #962
* Focused and selected state splitted up.
=> Selected and focused state splitted.

package.json, src/components/SecondaryPanes/ChromeScopes.js, src/components/SecondaryPanes/EventListeners.js, src/components/SecondaryPanes/Frames.js, src/components/shared/Button/PaneToggle.js, src/components/shared/ObjectInspector.js, src/test/mochitest/browser_dbg-asm.js, src/test/mochitest/browser_dbg-breaking-from-console.js, src/test/mochitest/browser_dbg-chrome-create.js, src/test/mochitest/browser_dbg-chrome-debugging.js, src/test/mochitest/browser_dbg-editor-gutter.js, src/test/mochitest/browser_dbg-editor-highlight.js, src/test/mochitest/browser_dbg-scopes.js, src/utils/tests/parser.js, src/utils/tests/sources-tree.js
Associated Issue: #1932
* fixed eslint so that it matches all sources
* lots of small fixes
mochitests pass.
=> fix eslint

configs/development.json, src/actions/sources.js, src/components/Editor/Editor.css, src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/utils/editor/index.js, src/utils/parser.js, src/utils/tests/parser.js
Associated Issue: #1845 #1846
* takes advantage of the parser function for finding sources added in the previous PR
* adds a simple function search UI that is prompted by `<cmd>+r` which is probably the wrong handle
* we should think through the right UX and UI. Currently the UI has a bad default label "search sources", takes up too much space, and doesn't factor in variable search, and other search modifiers that will be available in a bottom search bar...
* I'll add a feature flag once the parser functions land so that we can work on it darkly
=> (WIP) Function search

src/test/integration/runner.js, src/test/integration/tests.js, src/test/integration/tests/asm.js, src/test/integration/tests/breaking.js, src/test/integration/tests/breakpoints-cond.js, src/test/integration/tests/index.js, src/test/integration/tests/keyboard-navigation.js, src/test/integration/tests/keyboard-shortcuts.js, src/test/integration/tests/pretty-print.js, src/test/integration/utils/commands.js, src/test/integration/utils/index.js, src/test/integration/utils/mocha.js, src/test/integration/utils/mochitest.js, src/test/integration/utils/shared.js, src/test/integration/utils/type.js, src/test/mochitest/browser_dbg-asm.js, src/test/mochitest/browser_dbg-breaking.js, src/test/mochitest/browser_dbg_keyboard-shortcuts.js, src/test/mochitest/browser_dbg_keyboard_navigation.js
#1919 
* ported two more tests
* organized tests 
* organized helpers
I skipped these two tests for different reasons:
* navigation I got `Escape` and `Enter` working, but `Tab` failed
* shortcuts we need to get the shortcuts for function keys working in the web runner
=> WTR - update more tests

src/test/integration/runner.js, src/test/integration/tests.js, src/test/integration/tests/call-stack.js, src/test/integration/tests/debugger-buttons.js, src/test/integration/tests/iframes.js, src/test/integration/tests/index.js, src/test/integration/tests/pause-exceptions.js, src/test/integration/tests/pretty-print-paused.js, src/test/integration/tests/scopes.js, src/test/integration/tests/sourcemaps-bogus.js, src/test/integration/tests/sourcemaps.js, src/test/integration/tests/sourcemaps2.js, src/test/integration/tests/sources.js, src/test/integration/utils/commands.js, src/test/integration/utils/index.js, src/test/integration/utils/mocha.js, src/test/integration/utils/mochitest.js, src/test/integration/utils/shared.js, src/test/integration/utils/wait.js, src/test/mochitest/browser_dbg-call-stack.js, src/test/mochitest/browser_dbg-debugger-buttons.js, src/test/mochitest/browser_dbg-iframes.js, src/test/mochitest/browser_dbg-pause-exceptions.js, src/test/mochitest/browser_dbg-pretty-print-paused.js, src/test/mochitest/browser_dbg-scopes.js, src/test/mochitest/browser_dbg-sourcemaps-bogus.js, src/test/mochitest/browser_dbg-sourcemaps.js, src/test/mochitest/browser_dbg-sourcemaps2.js, src/test/mochitest/browser_dbg-sources.js, src/test/mochitest/examples/doc-sources.html
Associated Issue: #1919 
* did a lot more tests in batch, it's getting easier
* there are some tests that fail in the web test runner, but I think that's okay as long as they're ported over we can work on getting them passing in a second pass.
mochitests pass
=> Add additional tests

src/components/shared/ObjectInspector.js, src/utils/object-inspector.js, src/utils/tests/object-inspector.js
Associated Issue: #2021
I started working on bucketing object and array keys. As a first step I'd like to extract the helpers to a new utility file and add some test coverage to give me some confidence.
* mochitests
* new unit tests
=> extract object inspector helpers

src/utils/create-store.js, src/utils/redux/middleware/history.js, src/utils/redux/middleware/wait-service.js
Associated Issue: #1785 
@arthur801031 inspired me last night with his two util files. Now we just have one left :)
=> Additional flow utils

src/components/shared/ObjectInspector.js, src/reducers/pause.js, src/utils/object-inspector.js
r? @jasonLaster
server-side at https://bugzilla.mozilla.org/show_bug.cgi?id=881480
=> Add support for ES6 symbols

package.json, src/actions/pause.js, src/reducers/pause.js, src/selectors.js, src/utils/client.js, yarn.lock
Associated Issue: #2009
* Adds caching to `loadObjectProperties`
* Needs https://github.com/devtools-html/devtools-core/pull/190/files to work
* We should pull in the client adapters change before we merge this
* We should add a test once we update the client adapter
=> Fix updating objects in the scopes pane

src/utils/parser.js, src/utils/tests/parser.js
Associated Issue: #1842
* adds a helper for finding the variables in scope
* unit test
=> vars in scope

src/components/Editor/Editor.css, src/components/Editor/index.js, src/components/SourceSearch.js, src/components/shared/Autocomplete.css, src/components/shared/Autocomplete.js, src/strings.json
Associated Issue:  #2007
* implement the compact design for function search results
=> implement the function search compact design

src/components/Editor/index.js
Associated Issue: #1845
* create unique id for function results such that duplicate names appear
=> use a unique id to show multiple matches in function search

src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/utils/editor/index.js, src/utils/editor/source-search.js, src/utils/parser.js, src/utils/tests/source-search.js
Associated Issue: #1967 
* `countMatches` find all matches and save the positions, pass `ctx` as a parameter.
* `doSearch` return the current index of the matches
=> source-search count

src/actions/tests/sources.js
Associated Issue: #2059
* Fixed the invalid sources
* Supports #2061
=> fix the invalid source texts in the failing tests

src/utils/parser.js
=> fix failing tests

src/components/SecondaryPanes/WhyPaused.js
* fixes key issue with why paused
* refactors component to be easier on the eyes
* pause
* mochitests
=> refactor why-paused

package.json
Fixes #2036
* add script to list symlinks in your `node_modules` directory
=> add yarn run links script

package.json, yarn.lock
Associated Issue: #2101
* Bump remark version
=> Bump remark version

docs/integration-tests.md
=> (WIP) integration test docs

src/test/integration/runner.js, src/test/integration/tests/call-stack.js, src/test/integration/tests/pause-exceptions.js, src/test/integration/tests/scopes.js, src/test/integration/tests/sourcemaps-bogus.js, src/test/integration/tests/sources.js, src/test/integration/utils/index.js, src/test/integration/utils/mocha.js, src/test/integration/utils/mochitest.js, src/test/integration/utils/wait.js, src/test/mochitest/examples/doc-frames.html, src/test/mochitest/examples/doc-script-switching.html, src/test/mochitest/examples/frames.js, src/test/mochitest/examples/script-switching-01.js
Associated Issue: #1919 
* Adds a test for persisting expand state
* Adds support for a lot more web tests
* mochitests
=> Additional integration tests

src/components/Editor/index.js, src/components/shared/Popover.css, src/components/shared/Popover.js
Associated Issue: #1840 
* a very initial popover component. I plan to make changes to almost everything there :)
* on hover and pause for 500ms over the editor - show the popover
* a small refactor that extracted codeMirror (and its wrapper element) into a variable instead of accessing it repeatedly with this.editor
no tests currently, I saw that ui components aren't covered yet
=> Editor popover

src/components/shared/ObjectInspector.js
Associated Issue: #2112 and possibly #2032
* Added the local actors cache
=> fixes the  watch expression issue

bin/getConfig.js, docs/local-development.md, package.json, src/components/SourcesTree.js, src/utils/parser.js, src/utils/redux/middleware/promise.js, src/utils/utils.js, yarn.lock
Associated Issue: #???
* drop unused utils functions
* convert used utils functions to lodash equivalents
* optimize lodash webpacking by using `lodash/function` where possible
=> clean out the utils/utils module using lodash utils where possible

src/components/SecondaryPanes/Scopes.js, src/test/integration/runner.js, src/test/integration/tests/index.js, src/test/integration/tests/returnvalues.js, src/test/integration/utils/assert.js, src/test/integration/utils/commands.js, src/test/integration/utils/index.js, src/test/integration/utils/mochitest.js, src/test/integration/utils/shared.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-returnvalues.js, src/test/mochitest/examples/doc-return-values.html
* adds a test for return values
* adds pauseTest, assertNotPaused
* cleans up the utils
* shows return false, 0
=> Test Return values

assets/panel/debugger.properties, src/components/Editor/EditorMenu.js, src/components/Editor/Tabs.js, src/components/SecondaryPanes/Frames.js, src/components/SourcesTree.js, src/strings.json, yarn.lock
* updated l10n keys according to https://bugzilla.mozilla.org/show_bug.cgi?id=1338567 @francesc
* pulling in a launchpad update which fixes the dark theme
=> Bundle updates

src/components/App.css, src/components/Editor/SearchBar.css, src/components/Editor/SearchBar.js, src/components/SourceSearch.css, src/components/shared/Autocomplete.css, src/components/shared/Autocomplete.js, src/components/shared/ResultList.css, src/components/shared/ResultList.js, src/components/shared/SearchInput.css, src/components/shared/SearchInput.js, src/utils/parser.js, src/utils/result-list.js
Associated Issue: #2151 
Test plan:
=> [WIP] Refactor `SearchBar`, `SourceSearch` and `Autocomplete` and clean up function search UI

src/actions/sources.js, src/actions/types.js, src/reducers/sources.js
Associated Issue: #2100
I just investigated with @gregtatum and we found three things
1. `loadSourceMap` is very slow
2. `doSearch->getSearchState` is very GC intensive
3. one other thing i forgot (200ms)
=> (WIP) Address some perf issues

configs/development.json, src/components/Editor/Preview.js, src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/components/SecondaryPanes/Expressions.js, src/components/shared/Popover.css, src/components/shared/Popover.js
Associated Issue: #1843 
* Adds a popup
=> Popup Preview V1

CONTRIBUTING.md, docs/local-development.md, docs/maintainer.md, docs/pull-requests.md
You've probably felt it, but the Debugger is growing and it's more important than ever that we work as a team to help maintain the project.
Here are a collection of tips for maintaining as i think about it. It'd be great to evolve this doc as we evolve other docs like development, issues, PR tips.
=> Add some maintainer docs

src/components/Editor/index.js
Associated Issue: #2156
First pass at preview on hover
* Add mouseover event
* use offsetX
=> Preview hover

src/components/SecondaryPanes/Frames.js
Associated Issue: #2014
* add keydown event listener to Frames component
* save hovered frame in component state on mouseEnter and delete it from state on mouseLeave
=> [Frames] select frame on enter

docs/maintainer.md
This is a small PR that fixes typos and also replaces unnecessarily gendered language with a neutral form
=> fix typos and stuff

src/components/Editor/SearchBar.js
Associated Issue: #2172 
* when function search is enabled show a result count for functions rather than code search
=> Add summary messages for the function searching

src/utils/result-list.js
* the result list scrolling behavior was pretty unusable without this polyfill
=> add chrome scroll polyfill

src/components/Editor/Preview.css, src/components/Editor/Preview.js, src/components/Editor/index.js, src/components/SecondaryPanes/Expressions.css, src/components/shared/Popover.css, src/components/shared/Popover.js, src/components/shared/previewFunction.js, src/utils/object-inspector.js, src/utils/source.js
Associated Issue: #2158
* show the function link in the header
* show the children as roots to remove one of the depth levels
* highlight a selected node
* use reps for primitive nodes
todolist
=> (WIP) Preview different things

src/components/SecondaryPanes/Scopes.js, src/test/integration/tests/returnvalues.js
Associated Issue: #2134
* fix some esilnt nits
* don't display <return> when the return value is undefined
* add a test case
* add a test case for the string "undefined" just to be sure
=> Undefined return value

src/utils/client.js
Associated Issue: #2148
see #2165
=> Persist Pause On Exceptions

configs/firefox-panel.json, src/components/Editor/SearchBar.css, src/components/shared/SearchInput.css
* enable features
* tweak styles
=> Enable features + style tweaks

docs/local-development.md
Associated Issue: #2258 
* adjust the markdown for the table and add headings
=> Fix linting table

src/actions/sources.js
Associated Issue: None
Keep consistent with other actions in this file
=> Hardcoded string to contants in actions/sources

src/reducers/pause.js
Looks like we never removed this and it's not used
=> Remove unused expressions field

docs/updates/february-28th.md
* starts a weekly updates section of the docs that follows the conventions from this [doc](https://docs.google.com/document/d/1RAMSzE4JQlOMSE_3FRNznYiupOu3He45qp2FV1KVnV0/edit#)
* please feel free to make grammatical changes with the online editor and suggest any changes that make sense
* images and gifs coming soon
* here's a link to a [queries](https://github.com/jasonLaster/debugger-queries/tree/master) repo i created for generating a weekly update template [gist](https://gist.github.com/jasonLaster/214d98c8242b80940683b48c907ba0b0)
=> February 28th

docs/updates/updates-3-7-2017.md
=> Updates 3/7

docs/local-development.md, src/components/Editor/Footer.css, src/components/Editor/SearchBar.css, src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/components/SecondaryPanes/Expressions.css, src/components/SourceSearch.css, src/components/SourceSearch.js, src/components/Sources.css, src/components/shared/Autocomplete.js, src/components/shared/Button/Close.css, src/components/shared/ResultList.css, src/components/shared/ResultList.js, src/components/shared/SearchInput.css, src/components/shared/SearchInput.js
* clean up the colors
* adjust the heights to be more consistent
**Next Steps**
* Fix Source search height (keep it 40px)
* dark theme
* Make the sidebar headers less prominent
* remove the zebra call stack frames
* fix very blue selection
----
=> (WIP) Tweak the search bar appearance

src/components/SecondaryPanes/CommandBar.css
=> Fix command bar background

configs/development.json, src/components/Editor/Preview.js, src/components/Editor/index.js, src/utils/editor/index.js, src/utils/parser.js, src/utils/tests/parser.js
Associated Issue: #2219
WIP !!
* Add `getExpression` function to the parser
* Highlight member expressions and show full expression in the popup
* Evaluate expression and show in popup
* Add test for `getExpression`
=> Wip member expressions 2

src/components/shared/ObjectInspector.js
Associated Issue: #2326
* Implemented the fix @jasonLaster suggested.
=> fix for bucket range showing up backwards

src/utils/object-inspector.js
=> fix the object inspector bug

src/components/Editor/Preview.js, src/components/SecondaryPanes/Expressions.js
Associated Issue: #2336
@jcreighton
=> Follow up actors fix

src/components/App.js, src/main.js
* Migrated `src/components/App.js` to use es6 classes
=> converted src/components/App.js to es6

src/components/App.js, src/components/Sources.js, src/main.js
* Migrated Sources to es6 class
=> Refactor(ES6) src/components/Sources.js

src/components/Editor/index.js
Associated Issue: #2333 
Removed isRequired property from selectedLocation and add sanity checks for yarn errors.
=> fix console error for selectedLocation

src/components/Editor/Editor.css, src/components/Editor/Footer.css, src/components/variables.css
Closed #2324
Associated Issue: #2324 
* Added a variable for Heigh of Editor Footer
* Used this variable to calculate  Editor Mount height
=> Fixes Editor Height

src/components/App.js, src/components/WelcomeBox.js
This is part of the #1884 work
=> convert WelcomeBox to es modules

src/components/App.js, src/components/Sources.js, src/components/SourcesTree.js
* src/components/SourcesTree.js is changed
=> Refactor(ES6) src/components/SourcesTree.js

package.json
Tests weren't quitting. This cleans up the commands
=> update jest command

src/components/shared/Button/Close.css
Minor fix
* Fix typo in `transition-timing-function` property value
=> Fix typo in transition timing property value

docs/getting-setup.md
Associated Issue: #2335 
* Update `docs/getting-setup.md`
=> #2335 : Mention the debugger examples repo on the getting setup docs

package.json, src/components/App.js, src/components/SecondaryPanes/index.js
This is part of the #1884 work
=> Es module secondary panes

src/components/App.js, src/components/SourceSearch.js
Associated Issue: #1890 #1884 
* converted src/components/SourceSearch
=> Refactor(ES6) src/components/SourceSearch.js

src/components/shared/menu.js
Associated Issue: #1592 
* Add preventDefault on mask context menu
=> preventDefault on mask context menu. Fixes #1592

src/components/Editor/Tabs.js
Associated Issues: #1890 #1884 
* converted Tabs.js
=> Refactor(ES6) components/Editor/Tabs.js

src/components/SecondaryPanes/Breakpoints.css, src/components/shared/Button/Close.css
Associated Issue: #1997 
* Fix overlapping of scrollbar on breakpoints remove button
* Fix remove button not aligned to center
* Fix animation issue with border-radius
* Followed #1997 steps
=> Overlap breakpoints list scrollbar (#1997) #goodnessSquad

CONTRIBUTING.md, docs/issues.md, docs/maintainer.md
(as discussed in https://groups.google.com/forum/#!topic/mozilla.dev.developer-tools/ZtGZdelWt7o )
=> Rename `up for grabs` with `available` 

src/components/Editor/ConditionalPanel.js, src/components/Editor/Footer.js, src/components/Editor/Tabs.js, src/components/SecondaryPanes/Expressions.js, src/components/WelcomeBox.js, src/components/shared/Button/Close.js, src/components/shared/Button/PaneToggle.js, src/components/shared/SearchInput.js
Associated Issue: #1884 #1890 
* converted components/shared/Button/PaneToggle.js
* converted components/shared/Button/Close.js
=> Refactor(ES6) components/shared/Button/*

assets/panel/debugger.properties, src/strings.json, src/utils/text.js
Associated Issue: #2382
* localized keyshortcuts
=> chore: localized keyshortcuts - #goodnessSquad (#2382)

.eslintrc, src/components/Editor/index.js, src/utils/editor/expression.js, src/utils/editor/index.js, src/utils/makeRecord.js, src/utils/parser/utils.js, src/utils/scopes.js, src/utils/tests/expression.js, src/utils/tests/scopes.js
=> Preview variables from outer scopes

src/actions/navigation.js, src/actions/types.js, src/components/SourcesTree.js, src/reducers/pause.js, src/selectors.js, src/utils/sources-tree.js, src/utils/tests/sources-tree.js
Associated Issue: #1374 
This was pushed with --no-verify and still needs a clean-up.
=> Show hostname first (#1374)

assets/panel/prefs.js, src/actions/breakpoints.js, src/actions/sources.js, src/components/Editor/index.js, src/reducers/breakpoints.js, src/selectors.js, src/test/integration/runner.js, src/test/mochitest/head.js, src/utils/prefs.js
Associated Issue: #2167
* Add `sourceUrl` to breakpoints. 
* Add methods for `pendingBreakpoints` .
- Check if breakpoints persist across sessions.
- Pass flow, lint check, and Mocha tests.
=> [Breakpoints] persist across sessions

.eslintignore, package.json, webpack.config.js
Lint `webpack.config.js` with eslint
=> lint fix for webpack.config.js

README.md
Associated Issue: #<NONE>
* Fix table layout for markdown on GitHub
=> Fix table layout for markdown on GitHub

.remarkrc, package.json, yarn.lock
This will help us keep our styles consistent for tables.
As a side note, I can't get remark to fail for anything, so trying to hunt that down too :)
=> [docs] add table markdown linting

.gitignore, circle.yml, package.json, src/components/shared/Accordion.css
Associated Issue: #2319
* add `test-coverage` script
* add coverage reporting to circleci and upload to codecov
=> Jest coverage

assets/panel/debugger.properties, src/components/ProjectSearch.js
Comes from here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1346698
=> Fix duplicate locale

CONTRIBUTING.md
=> broken table fixed

src/utils/parser/utils.js, src/utils/tests/parser.js
Associated Issue: #2451
- added assignementExpression code
- added and modified test cases
=> Fixing Bug #2451 - AssignmentExpression Functions in search

src/components/Editor/Tabs.js, src/components/shared/Dropdown.js
=> Refactor(ES6) components/shared/Dropdown.js

docs/local-development.md
Docs to help working with other packages
=> 3rd party docs

docs/updates/README.md, docs/updates/updates-3-21-2017.md
=> 3/21 Updates

src/utils/pause.js
Associated Issue: #<1884>
* changed require to import
* replaced export module with export 2 functions directly
tried debugger pause button on firefox webpage on to do project.
check in was clean - no issues.
=> updated file to es module

src/components/Editor/Preview.js, src/components/shared/ObjectInspector.js, src/components/shared/Rep.js
=> Convert es module rep

src/components/Editor/SearchBar.js, src/components/SecondaryPanes/index.js, src/components/shared/Accordion.js, src/components/shared/Autocomplete.js, src/components/shared/ResultList.js
* Convert `Accordion` to ES module
* Convert `ResultList` to ES module
=> Convert ResultList and Accordion to es modules

src/components/Editor/Footer.js, src/components/Editor/SearchBar.js, src/components/Editor/index.js, src/main.js
Associated Issue: #1885 
* Fix some additional require calls
I had missed these require calls that needed to import the default.
=> Fix ES6 actions imports

src/components/Editor/SearchBar.js, src/components/Editor/index.js
=> Polish updateSearchResults

src/components/Editor/SearchBar.js, src/utils/parser/utils.js, src/utils/tests/parser.js
Associated Issue: #2471
- Removed unwanted class search button
- Updated variables list with class list
- Updated test cases
=> Fixes 2471 - Merge Class search into variables list

README.md
Associated Issue: #None
* Improved setup instruction.
* Clarified how to verify it's working.
n/a
=> improve readibility of readme

README.md, circle.yml, docs/getting-setup.md
Associated Issue: #2497 and #2475
* change the docs to remove the yarn version mentions
* upgrade yarn in our CI to match the latest available version
=> Upgrade yarn and docs

src/test/mochitest/browser_dbg-editor-highlight.js, src/test/mochitest/head.js
I missed a couple of comments in the last pr
=> followup tweaks

.github/PULL_REQUEST_TEMPLATE
* Pull Request Documentation now accessible on Pull Request Template
=> Add pull request documentation link

src/actions/tests/breakpoints.js, src/actions/tests/sources.js
Thanks @jlongster and prettier for helping us see the light!
=> Prettify the tests

src/components/Editor/SearchBar.js, src/components/shared/Autocomplete.js, src/components/shared/SearchInput.js
Associated Issue: #1884 #1890
Summary of changes
* Convert `SearchInput` to es module and es6 class
=> Convert SearchInput to es modules and es6 class

src/components/Editor/Footer.js, src/components/Editor/index.js
* Convert Footer.js
This is my first-time contribution to open source project, please correct me if there is a mistake. I will happy to make it right.
=> Convert Footer.js to ES6 class

src/components/Editor/Footer.js
=> Fix vertical footer

docs/maintainer.md
=> Tiny text fix

bin/prettier.js, src/components/Editor/SearchBar.js
=> [Prettier] fix arguments

assets/panel/debugger.properties, configs/development.json, flow-typed/debugger-html.js, src/actions/sources.js, src/actions/types.js, src/client/firefox/commands.js, src/client/firefox/create.js, src/client/firefox/types.js, src/components/Editor/EditorMenu.js, src/components/Editor/Footer.css, src/components/Editor/Footer.js, src/components/Editor/index.js, src/components/SecondaryPanes/Breakpoints.js, src/components/SecondaryPanes/Frames.js
Associated Issue: #1535 
adds a POC blackbox feature with a footer toggle button and filtered frames
Next Steps:
* persist blackboxed frames
* don't show button for original sources 
* update the button and tooltip
| blackboxed | unblackboxed |
|----|----|
| <img width="676" alt="screen shot 2017-04-03 at 8 40 15 pm" src="https://cloud.githubusercontent.com/assets/254562/24637275/db4d4394-18ad-11e7-9c60-9c62209c3e4e.png"> | <img width="700" alt="screen shot 2017-04-03 at 8 40 08 pm" src="https://cloud.githubusercontent.com/assets/254562/24637276/db4e73d6-18ad-11e7-8e54-1f5aac1f79db.png">|
=> (WIP) Add Blackbox

src/components/Editor/Preview.js, src/components/Editor/index.js, src/components/shared/previewFunction.js, src/utils/editor/expression.js, src/utils/editor/index.js
Associated Issue: #1843
* Fix previewing `this`
* Fix previewing native functions like apply
* Fix previewing functions that don't have a location
=> Fixup preview

configs/development.json, src/components/Outline.js, src/components/ProjectSearch.js, src/components/Sources.js
* Adds an initial implementation of the source outline view that is hidden behind a config
* Removed some unused selectedSource
Enable "Source Outline" and behold the new world.
=> Add initial source outline

src/actions/tests/breakpoints.js, src/actions/tests/expressions.js
=> Expression actions tests

src/components/Editor/Preview.css, src/components/shared/Popover.css
=> style preview popup

src/components/Editor/index.js
* Update Editor/index.js to use ES6 classes
=> Convert Editor/Editor to ES6 class

src/components/Editor/Preview.css, src/components/Editor/Preview.js, src/components/shared/Popover.css, src/components/shared/Popover.js
Associated Issue: #2567 
* Add tooltip class
* Use tooltip instead of popover in function previews
=> Use tooltip for function preview

src/components/Editor/ConditionalPanel.js, src/components/Editor/EditorMenu.js, src/components/Editor/GutterMenu.js, src/components/Editor/index.js
* Convert `ConditionalPanel`, `EditorMenu`, `GutterMenu` to es module.
=> Convert ConditionalPanel, EditorMenu, GutterMenu to es module

src/components/Editor/Preview.css, src/components/shared/Popover.js
Fixes the mouse over tooltip problem
=> add tooltip-gap

src/components/WelcomeBox.js
* Convert the WelcomeBox to ES6 classes.
Almost done with all the components! 😄
=> Convert WelcomeBox to ES6 class

assets/panel/debugger.properties, src/components/Editor/SearchBar.js
Fixes: #2555 
* Localize search type toggle title
I think the name and localization note can be improved. Let me know if you have any suggestions.
=> Localize search type toggle title

src/components/App.js, src/components/Editor/index.js, src/components/SecondaryPanes/ChromeScopes.js, src/components/SourcesTree.js, src/components/shared/ManagedTree.js, src/components/shared/ObjectInspector.js
=> Convert Editor/index.js to es6 module

src/components/SecondaryPanes/Expressions.css
Associated Issue: #2575
* Fix css selector for close button
=> [SecondaryPanes] Align close button on watch expression

src/components/Editor/Preview.js, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/Scopes.js, src/components/shared/ObjectInspector.js, src/components/shared/Popover.js, src/components/shared/Svg.js, src/components/shared/previewFunction.js
Converted modules: 
* Editor/shared/ObjectInspector.js
=> Convert Editor/shared/ to es6 module

src/utils/parser/utils.js
@ryanjduffy will work on parsing HTML in a bit here https://github.com/devtools-html/debugger.html/issues/2378, but for now lets limit babel to just things it can do :)
@jbhoosreddy we will likely want to include JSX and typescript too later
=> Only parse js

docs/local-development.md, package.json, src/components/tests/__snapshots__/closeButton.js.snap, src/components/tests/closeButton.js, src/test/integration/tests/editor-preview.js, src/test/integration/utils/commands.js, src/test/integration/utils/mocha.js, yarn.lock
Associated Issue: #2618 
* Using enzyme to test react components
=> Add jest test for CloseButton

src/test/integration/index.html, src/test/integration/runner.js, src/utils/parser/utils.js
This fixes some additional WTR tests by making sure the state clears between tests.
=> Fix call stack test

src/test/integration/index.html, src/test/integration/tests/call-stack.js, src/test/integration/tests/expressions.js, src/test/integration/tests/scopes.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-call-stack.js, src/test/mochitest/browser_dbg-expressions.js, src/test/mochitest/browser_dbg-pretty-print.js, src/test/mochitest/browser_dbg-scopes.js, src/test/mochitest/examples/doc-frames.html, src/test/mochitest/head.js
Fixes expressions, call stack which are two tests that are not run w/ mochitests
=> Fix WTR tests - expressions, call stack

docs/updates/call-stack-4-10-2017.md
Updating the post with some improved visuals and an inception example
=> Updates to the call stack post

assets/panel/debugger.properties, src/components/ProjectSearch.js
=> remove duplicate prop

assets/module-manifest.json, assets/panel/debugger.properties, assets/panel/panel.js, bin/copy-assets.js, configs/application.json, configs/development.json, configs/firefox-panel.json, src/components/Editor/EditorMenu.js, src/test/mochitest/browser_dbg-sourcemaps-bogus.js, src/test/mochitest/browser_dbg-sourcemaps.js, src/test/mochitest/browser_dbg-sourcemaps2.js
Regular Update with some changes:
* updated some properties
* assets manifest
* updated some feature flags
🛑  lets not merge this until firefox is updated
=> (WIP) 4-7 update

src/test/tests-setup.js, src/utils/scopes.js, src/utils/tests/scopes.js
Associated Issue: #2694
* adds an ID to scope keys
* adds some test coverage
=> Fix issue with multiple scopes having the same path

src/components/SecondaryPanes/WhyPaused.css, src/components/SecondaryPanes/WhyPaused.js, src/components/tests/WhyPaused.js, src/components/tests/__snapshots__/WhyPaused.js.snap
Associated Issue: #2677
* Add exceptions message
=> Show the exception message if one exists

src/actions/tests/breakpoints.js
Associated Issue: #
* Added tests for breakpoint actions
=> add tests for breakpoint actions

src/test/integration/tests/tabs.js, src/test/integration/utils/commands.js
Associated Issue: #1865 #2638  #1150 
* adds a test for reloading the debugger
* updates the debuggee reloading test
=> Test Tabs with reloading

circle.yml
See https://github.com/devtools-html/debugger.html/issues/2702 - it was
out-of-date.
Associated Issue: #2702
* change 1
* change 2
yarn run test-all
=> Update the yarn version in circle.yml.

docs/debugging.md
add screenshots of react/redux devtools
=> add dt docs

docs/remotely-debuggable-browsers.md
Use --profile and temp directory env variables
=> Update docs for remotely debuggable browsers

configs/application.json, configs/ci.json, configs/development.json, configs/firefox-panel.json, configs/local.sample.json, src/components/Editor/SearchBar.js, src/components/Editor/index.js
Associated Issue: #2686 
* remove feature flag for symbol search
=> re #2686 - remove feature flag for symbol search

src/components/Editor/Tabs.css, src/components/Editor/Tabs.js
Associated Issue: #2743
* Added source annotation prop.
* Calculate source annotation. Currently prettyPrint and blackbox
* Fixed minor style issues in the source tab
Manually test the fix
Local unit test
=> Blackbox source icon

src/components/tests/__snapshots__/resultList.js.snap, src/components/tests/resultList.js
Associated Issue: #2630 
* Added tests for ResultList
=> Add jest test for ResultList

src/components/App.js, src/components/Editor/Tabs.js, src/components/ProjectSearch.js, src/components/SecondaryPanes/ChromeScopes.js, src/components/SecondaryPanes/CommandBar.js, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/Frames.js, src/components/SecondaryPanes/Scopes.js, src/components/Sources.js, src/components/SourcesTree.js, src/components/WelcomeBox.js, src/components/shared/Accordion.js, src/components/shared/Popover.js, src/components/shared/Rep.js, src/components/shared/previewFunction.js
Did some changes to make all components consistent.
- Converted createFactor(require("component")) to use imports
- Converted require("x.css") to use imports
=> Refactored components

src/components/tests/previewFunction.js
Associated Issue: #2630 
* change 1
* change 2
=> Preview function unit tests

configs/application.json, configs/ci.json, configs/development.json, configs/firefox-panel.json, configs/local.sample.json, src/components/Editor/EditorMenu.js, src/components/SecondaryPanes/index.js
Associated Issue: #2678
* removed the watchExpressions feature flag
I removed all references from watchExpressions from the config and made sure that the WatchExpressions still appear.
=> removed feature flag for Watch Expressions #2678

src/test/integration/runner.js, src/test/integration/tests/scopes.js
Test changing the selected frame and checking the scopes
=> Add a test for changing the selected frame

configs/development.json, src/actions/sources.js, src/components/Editor/ColumnBreakpoint.js, src/components/Editor/Editor.css, src/components/Editor/index.js, src/reducers/breakpoints.js, src/utils/editor/index.js
Associated Issue: #2390 
* column breakpoint component
* update actions & prefs for breakpoints to account for columns
* editor `toggleColumnBreakpoint` function
=> Column breakpoints

README.md
Adds a link to the changelog podcast.
Not sure where to mention it
=> changelog podcast

src/utils/redux/middleware/log.js
Associated Issue: 
Fix broken UI due to es module refactor
* Remove `default`
=> fixes broken ui

.babelrc, .storybook/config.js, .storybook/webpack.config.js, package.json, src/components/stories/tabs.js, yarn.lock
Re-Adds Storybook to the Debugger
* borrows similar patterns from the splitter package
* borrows patterns from our jest snapshot tests
* hopefully will be hooked up with percy.io soon for visual regression checks
* would have really helped while working on framework grouping
=> re-add storybook

assets/panel/index.html
=> Drop version number

package.json, src/utils/parser/utils.js, src/utils/tests/fixtures/parseScriptTags.html, src/utils/tests/parser.js, yarn.lock
Associated Issue: #2378 
* Adds parser support for HTML files
TBD
Opening this up for discussion and some outside testing.
=> Add parser support for HTML files

docs/local-development.md, src/components/Outline.js, src/components/tests/Outline.js, src/components/tests/__snapshots__/Outline.js.snap
Associated Issue: #2630
* Added unit tests for Outline.js
=>  #2630 Add jest test for Outline

src/components/SecondaryPanes/Frames/index.js, src/reducers/sources.js
Associated Issue: #2727 
This PR has a few more performance improvements identified by the 500-script page.
- Add memoized selectors for data needed by the `Frames` component.
- Remove unnecessary loops to find source by id.
=> More performance improvements

docs/local-development.md
* added error section to doc
* added solution for fixing common error when pulling
=> add error section to dev doc

src/components/shared/ManagedTree.css, src/components/shared/ResultList.css
Associated Issue: #2444
Also fixes bugs related to weird borders, which were collapsing.
Final result can be seen below.
=> Improve source tree and search results

.storybook/config.js, src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.js.snap, src/components/stories/frames.js
* refactors props
* adds stories
* moves the `copyStackTrace` logic into frames so Frame doesn't need to know about the list of frames
=> refactor frames

assets/panel/debugger.properties
=> update the properties

assets/panel/debugger.properties, src/components/Editor/SearchBar.js, src/components/Editor/Tabs.js, src/components/Editor/index.js, src/components/ProjectSearch.js, src/components/Sources.js, src/components/WelcomeBox.js
Fixes the shortcut property labels, which need to be re-translated
=> fix keyshortcut labels

configs/development.json, configs/firefox-panel.json
=> enable search nav

assets/images/Svg.js, assets/images/column-breakpoint.svg, src/components/Editor/ColumnBreakpoint.js, src/components/Editor/Editor.css
Associated Issue: #2786
* Changed the icon for the column breakpoint
* Fixed enabling/disabling a column breakpoint
=> Column breakpoint improvements

.flowconfig, circle-2.0.yml, circle.yml, package.json, yarn.lock
* Add devtools-license-checker dependency and command
* Change circle.yml to invoke it
=> Use the license checker

.babelrc, .storybook/config.js, package.json, src/components/stories/Preview.js
=> add a story for preview

src/actions/ui.js
Associated Issue: #2800
I made the necessary changes looking at the issue description. However, the test fails when I try to push the changes.
Am only beginning to learn Redux now, how do I proceed further?
=> fixed the unnecessary firing of TOGGLE_PROJECT_SEARCH action

src/components/SecondaryPanes/Breakpoints.js
Associated Issue: #2864 
* Added a column line to breakpoint label (only for column breakpoint)
Added column breakpoint and line breakpoint. Made sure everything's working super.
=> Column number breakpoint

assets/module-manifest.json, src/components/shared/ObjectInspector.js, src/components/stories/Preview.js, src/test/integration/tests/scopes.js, src/test/mochitest/browser_dbg-scopes.js, src/utils/object-inspector.js, src/utils/tests/object-inspector.js, yarn.lock
Associated Issue: #2857
We are currently showing `[default properties]` incorrectly when an object happens to have a window property like location.
This fixes that by explicitly checking to see if the object is a window. 
* adds unit tests
* adds storybook stories
=> Fix default bucketing

src/components/SecondaryPanes/EventListeners.js, src/utils/clipboard.js, src/utils/frame.js, src/utils/fromJS.js, src/utils/makeRecord.js, src/utils/object-inspector.js, src/utils/parser/index.js, src/utils/parser/utils.js, src/utils/path.js, src/utils/pretty-print/index.js
=> Convert utils to es6 modules

flow-typed/debugger-html.js, src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/FrameMenu.js, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/tests/Frame.js, src/components/SecondaryPanes/Frames/tests/FrameMenu.js, src/components/SecondaryPanes/Frames/tests/Group.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.js.snap
Associated Issue: #2843 
* refactor Context Menu in Frame component
* refactor new FrameMenu component
* add tests to Frame component for mouse actions
* add tests to FrameMenu to make sure things work as expected
behavior should not be changed, so integration tests should stay the test. Added a couple of unit tests
no visual changes
=> [Frames] Add a group context menu       

src/components/SecondaryPanes/CommandBar.js
small fix from the props change
=> fix commandbar shortcut types

src/client/index.js
=> add some inline docs

src/client/index.js
=> update inline docs

src/components/Editor/HighlightLines.js
Associated Issue: #2933
Fixes the issue where we were jumping at random times
=> Fix bp adding

.babelrc, assets/panel/panel.js, flow-typed/debugger-html.js, src/actions/pause.js, src/actions/sources.js, src/components/Editor/Preview.js, src/components/Editor/index.js, src/components/SecondaryPanes/Breakpoints.js, src/components/SecondaryPanes/ChromeScopes.js, src/components/SecondaryPanes/CommandBar.js, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Scopes.js, src/components/SecondaryPanes/WhyPaused.js, src/components/SecondaryPanes/index.js, src/components/stories/Preview.js, src/components/tests/WhyPaused.js, src/components/tests/__snapshots__/WhyPaused.js.snap, src/reducers/pause.js, src/test/integration/utils/assert.js, src/test/integration/utils/wait.js, src/test/mochitest/head.js, src/utils/pause.js, src/utils/scopes.js, src/utils/tests/scopes.js
Associated Issue: #2283
* Refactor pause reducer to remove immutable
=> WIP Remove immutable from the pause reducer 

README.md
It would be nice to have a more european / asia friendly call time :)
=> Update community calls

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/FrameMenu.js, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/Frame.js, src/components/SecondaryPanes/Frames/tests/FrameMenu.js, src/components/SecondaryPanes/Frames/tests/Frames.js, src/components/SecondaryPanes/Frames/tests/Group.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.js.snap
Associated Issue: #2744 
* Add `blackbox source` in call stack item's context menu
=> Support blackboxing from call stack

src/components/SecondaryPanes/Frames/Frame.js
This should fix the 6 failing storybook stories.
=> Fix frames stories

src/components/Editor/Preview.css
Associated Issue: #2898 
* Fix max-width of function preview popover
=> Fix function preview max width

src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/Frames.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.js.snap
We recently stopped filtering blackboxed frames, this fixes it and adds some nice tests
=> Fix blackbox frame filtering

src/components/shared/Popover.js
=> Better position tooltip horizontally

src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.js.snap, src/components/tests/__snapshots__/WhyPaused.js.snap, src/test/tests-setup.js
Associated Issue: #2952
* Use L10N for unit test `tests-setup.js`
* Fix some testcases
Let me know if there is a better method for this one.
=> Use L10N for unit test

src/actions/tests/breakpoints.js, src/actions/tests/expressions.js, src/actions/tests/pending-breakpoints.js, src/actions/tests/sources.js, src/actions/tests/ui.js, src/reducers/tests/sources.js, src/reducers/tests/ui.js, src/utils/parser/tests/closest.js, src/utils/parser/tests/getSymbols.js, src/utils/parser/tests/resolveToken.js, src/utils/parser/tests/scopes.js, src/utils/tests/build-query.js, src/utils/tests/fromJS.js, src/utils/tests/object-inspector.js, src/utils/tests/scopes.js, src/utils/tests/source-search.js, src/utils/tests/source.js, src/utils/tests/sources-tree.js
Migrate all test using expect assertions to jest
Delete mocha-runner.html
Associated Issue: 2995
* Migrate tests to use jest assertions
* Delete mocha-runner.html
All changes were in test file so just ran tests using
yarn test
=> Use jest assertion in place of expect

docs/updates/README.md, docs/updates/when-the-world-stops.md
quick blog post on the debugger server
=> When the world stops

assets/panel/debugger.properties, src/components/SecondaryPanes/Frames/FrameMenu.js
Fixes: #2969
We shouldn't use an accesskey in two different places.
=> Fix accesskeys

src/components/shared/Accordion.css
Associated Issue: #2979  
* center aligned labels  
N/A
=> [SecondaryPane] aligned labels vertically 

src/actions/tests/__snapshots__/ast.js.snap, src/utils/parser/getSymbols.js, src/utils/parser/tests/getSymbols.js, src/utils/parser/utils/getFunctionParameterNames.js
Fixes https://github.com/devtools-html/debugger.html/issues/2735
* Adds function params while loading symbols for a file
Added a new test, updated existing tests.
=> gets function params while loading symbols for a file

src/components/shared/Button/PaneToggle.js
* Switch `PaneToggle` from PropTypes to flow props
=> Switch PaneToggle from PropTypes to flow props

src/actions/expressions.js, src/actions/tests/expressions.js
=> Expressions cleanup

package.json, src/actions/sources.js, src/actions/types.js, src/reducers/types.js
Gets the application state typed. Really excited about this change. Probably needs more massaging to get in though...
=> Add application state types

src/components/Editor/Preview.css
Associated Issue: #2984 
* changed highlight expression color to more contrast 
N/A
=> [Preview] Highlight expression yellow #2984

src/components/Editor/index.js
=> Show column breakpoints in the gutter

src/components/Editor/index.js, src/utils/parser/tests/__snapshots__/closest.js.snap, src/utils/parser/utils/closest.js, src/utils/parser/utils/helpers.js
Associated Issue: #3019
The first PR updated the tests to use snapshots and added a test to reproduce the issue. This PR adds a simple fix.
=> Fix member expressions with a call expression

src/utils/parser/getOutOfScopeLocations.js, src/utils/parser/tests/__snapshots__/getOutOfScopeLocations.js.snap, src/utils/parser/tests/fixtures/outOfScope.js, src/utils/parser/tests/getOutOfScopeLocations.js, src/utils/parser/types.js, src/utils/parser/utils/closest.js, src/utils/parser/utils/helpers.js, src/utils/parser/worker.js
Associated Issue: #2964
* Adds a new method to find out of scope locations
* Minor refactoring of parser helpers to use new `containsPosition` function
* Unit tests!
=> Add parser function to determine out of scope locations

src/actions/ast.js, src/actions/sources.js, src/actions/tests/__snapshots__/ast.js.snap, src/actions/tests/ast.js, src/actions/tests/sources.js, src/components/Editor/Editor.css, src/components/Editor/index.js, src/reducers/ast.js, src/reducers/sources.js, src/selectors.js, src/utils/parser/getOutOfScopeLocations.js, src/utils/parser/index.js, src/utils/parser/tests/__snapshots__/getOutOfScopeLocations.js.snap, src/utils/parser/types.js
Associated Issue: #2964 
* redux ast work
* editor render work
* unit tests
=> Highlight Lines V1

src/components/SecondaryPanes/Expressions.js
=> fix annoying expression duplicate keys warning

src/utils/object-inspector.js, src/utils/tests/__snapshots__/object-inspector.js.snap, src/utils/tests/object-inspector.js
@bomsy and I found some things while looking at HTML Elements
* promise properties should include state, reason, and value
* __proto__ should be at the bottom.
=> Promise fixes

src/components/shared/SearchInput.css
=> Fix input font size

package.json, src/utils/editor/index.js, yarn.lock
Fixes #2982 
This removes the selected line, which is similar to what chrome does.
=> Disable active line

src/components/Sources.css, src/components/SourcesTree.js
* fixes moving with key up and down. previously the height was off so it would get out of line
* fixes the footer so that it is flexed and doesn't overlay the tree
=> cleanup source tree

flow-typed/debugger-html.js, src/components/Editor/Footer.js, src/components/Editor/SearchBar.js, src/reducers/sources.js
Associated Issue: #3078
I started refactoring the sources store to remove SourceText. The reason is that it is not needed and creates extra complexity around selectors and typing in our components, actions, and utilities.
=> [WIP] consolidate source text

assets/panel/prefs.js, flow-typed/debugger-html.js, src/actions/breakpoints.js, src/actions/sources.js, src/actions/tests/__snapshots__/pending-breakpoints.js.snap, src/actions/tests/helpers/breakpoints.js, src/actions/tests/pending-breakpoints.js, src/actions/types.js, src/client/firefox/commands.js, src/components/Editor/index.js, src/components/SecondaryPanes/Breakpoints.js, src/reducers/breakpoints.js, src/utils/breakpoint/index.js, src/utils/prefs.js, src/utils/utils.js
=> [Breakpoints] + [SourceMaps] breakpoints are out of sync with the server on reload       

ROADMAP.md
Issue: #2241
Leaving this open for a bit to gather input:
* are we missing a priority
* should we focus more
* does a feature need more description
=> Q3 Roadmap

src/client/firefox.js, src/main.js, src/test/fixtures/index.js, src/test/integration/runner.js, src/test/tests-framework.js, src/test/tests-setup.js, src/utils/parser/tests/helpers/index.js, src/utils/prefs.js, src/utils/scopes.js, src/utils/tests/build-query.js, src/utils/tests/fromJS.js, src/utils/tests/scopes.js, src/utils/tests/source-search.js, src/utils/tests/source.js, src/utils/tests/sources-tree.js
=> replace commonjs with imports

configs/firefox-panel.json
=> stop folding in the panel

package.json, yarn.lock
Associated Issue: #3141 
* remove [firefox-profile](https://www.npmjs.com/package/firefox-profile) which was pulled in for integration tests 59821b238c5904796c9ddbfabb1b466234449b6a but that work has moved to the launchpad and this module doesn't work well with selenium now anyway.
* WIP
=> Update outdated deps

package.json, yarn.lock
=> fix(package): update devtools-launchpad to version 0.0.84

src/components/Outline.css
Associated Issue: #2901 
* Removed bullet points and decreased left padding for functions in outline view
* Added pointer and hover effect to functions in outline view
=> Style functions in outline view

docs/updates/README.md, docs/updates/updates-6-13-2017.md
=> Weekly update June 12 2017

src/client/index.js
This will make it easy to see/change a pref in the console
=> Make it easy to test prefs

docs/updates/5-1-2017-flow.md, docs/updates/5-1-2017-tests.md
This starts a blog post on the state of our testing and type coverage. I hope to write one quarterly to summarize our progress and next steps.
This is helping me better understand what some good next steps are:
1. adding `State` types in our actions
2. adding types to our tests 
3. adding types to our component props
4. adding immutable types
=> Test report

src/components/ProjectSearch/ProjectSearch.js, src/components/ProjectSearch/TextSearch.css, src/components/ProjectSearch/TextSearch.js, src/utils/parser/tests/fixtures/var.js, src/utils/project-search.js, src/utils/tests/__snapshots__/project-search.js.snap
Associated Issue: #1108
* connects the dots between ProjectSearch, TextSearch, and searchSource
* wires up SearchInput and knows how to show the count
Lots to do, but this is a start
=> Start project search

.stylelintrc, bin/prettier.js, src/components/Editor/Editor.css, src/components/Editor/Tabs.css, src/components/ProjectSearch/ProjectSearch.css, src/components/SecondaryPanes/Breakpoints.css, src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/Frames/Group.css, src/components/SecondaryPanes/Frames/WhyPaused.css, src/components/SecondaryPanes/Scopes.css, src/components/Sources.css, src/components/shared/Accordion.css, src/components/shared/Autocomplete.css, src/components/shared/BracketArrow.css, src/components/shared/Button/PaneToggle.css, src/components/shared/SearchInput.css, src/components/shared/Svg.css, src/components/shared/previewFunction.css, src/components/shared/reps.css, src/components/variables.css, src/utils/parser/tests/fixtures/var.js
prettier now supports CSS. Lets use it!
=> prettify css

src/components/SourcesTree.js, src/utils/sources-tree.js, src/utils/tests/sources-tree.js
=> [SourceTree] fails to render the root directory

src/utils/parser/tests/__snapshots__/getOutOfScopeLocations.js.snap, src/utils/parser/tests/getOutOfScopeLocations.js
This makes the parser results easier to read
=> format snapshots

src/components/SecondaryPanes/CommandBar.css, src/components/SecondaryPanes/CommandBar.js
Our step animations were taking much longer than the time it took to step, which was crazy. This fixes that!
=> Style command bar animations

flow-typed/debugger-html.js, src/actions/ast.js, src/actions/sources.js, src/actions/tests/sources.js, src/components/Editor/index.js, src/components/Editor/tests/__snapshots__/Editor.js.snap, src/reducers/sources.js, src/selectors.js, src/test/mochitest/browser_dbg-editor-highlight.js, src/test/mochitest/head.js, src/types.js, src/utils/editor/index.js, src/utils/pretty-print/index.js, src/utils/source.js, src/utils/tests/source.js
Associated Issue: #3078
* cleans up actions/ast
* a couple more places to cleanup
=> (WIP) Replace sourcetext w/ source

package.json
no issue associated
I got tired of doing `./node_modules/.bin/jest --watch`
=> add jest:watch command

src/actions/ast.js, src/actions/tests/__snapshots__/ast.js.snap, src/actions/types.js, src/components/Editor/Editor.css, src/components/Editor/Preview.css, src/components/Editor/Preview.js, src/components/Editor/index.js, src/components/Editor/tests/__snapshots__/Editor.js.snap, src/components/shared/Popover.js, src/components/stories/Preview.js, src/reducers/ast.js, src/test/mochitest/head.js, src/utils/editor/expression.js, src/utils/editor/index.js
Associated Issue: #3109
WIP - Highlight the entire expression on hover
=> Support highlighting the full expression

src/components/shared/BracketArrow.css, src/components/shared/BracketArrow.js, src/components/shared/Popover.js
Associated Issue: #3109 
* Revive the small arrow pointing to the variable that the preview popup shows 
Start debugging a file and mouse over a variable while stepping through code.  The poup
has a small arrow pointing to the variable.
=> get bracketarrow working again

flow-typed/debugger-html.js, src/actions/sources.js, src/actions/types.js, src/reducers/sources.js, src/types.js, src/utils/parser/getOutOfScopeLocations.js, src/utils/parser/getSymbols.js, src/utils/parser/utils/ast.js, src/utils/parser/utils/closest.js
=> removes SourceText type

src/selectors.js
=> simplify selectors

src/components/Editor/index.js
Found that this prop wasn't being used :)
=> Remove editor expression prop

src/utils/source.js, yarn.lock
Associated Issue: #3222
* fixes html syntax highlighting
=> Html syntax highlight bug

.gitignore
I am using ctags for navigation and would like to have the file ignored; might be useful for others
=> ignore tag files

src/actions/sources.js, src/components/ProjectSearch/SourceSearch.js, src/components/ProjectSearch/TextSearch.js, src/components/ProjectSearch/index.js, src/test/mochitest/browser.ini
=> Fix source search

src/components/ProjectSearch/index.js
fixing a small lint error on master
=> fix selectSource prop

src/actions/breakpoints.js, src/actions/thunks/breakpoints.js, src/actions/utils/breakpoints.js, src/utils/breakpoint/index.js
I was debugging an issue with reloading + breakpoint sliding and found it hard to reason about breakpoints, so i extracted some thunks and utils
=> Refactor breakpoints actions

src/components/SecondaryPanes/Scopes.css
Associated Issue: #3107 
* Visual change, see screencap
=> [Scopes] Horizontal scrolling

src/actions/breakpoints.js, src/actions/thunks/breakpoints.js, src/actions/utils/breakpoints.js, src/components/Editor/Breakpoint.js, src/components/Editor/index.js, src/components/ProjectSearch/index.js, src/reducers/breakpoints.js, src/reducers/tests/breakpoints.js, src/test/mochitest/browser_dbg-breakpoints-reloading.js, src/test/mochitest/browser_dbg-sourcemaps.js, src/utils/breakpoint/index.js, src/utils/editor/index.js, yarn.lock
Associated Issue: #3167 
Screenshot:
=> Bugfix: Cannot set debugger breakpoint on generatedSource

src/actions/sources.js, src/components/Editor/Tabs.js, src/components/ProjectSearch/TextSearch.css, src/components/ProjectSearch/TextSearch.js, src/components/ProjectSearch/index.js, src/components/stories/TextSearch.js, src/reducers/sources.js, src/utils/search/project-search.js, src/utils/search/tests/project-search.js
* WIP of project text search
TODO
* Open the  text search as a new tab
* Style cleanups
=> Project text search wip

src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/SecondaryPanes.css, src/components/SecondaryPanes/index.js
=> Fix watch expression inputs

src/components/SecondaryPanes/Scopes.css
=> fix scopes width

src/components/shared/ManagedTree.css
Associated Issue: #3304
* add bottom padding
=> add bottom padding

src/actions/sources.js, src/actions/tests/sources.js
Associated Issue: #3331
* Added `loadAllSources` action to load all the texts for all the available sources
* Added test
=> Load sources text

src/components/Editor/Tabs.js, src/components/ProjectSearch/SourceSearch.js, src/components/ProjectSearch/index.js
* fix the close buttons
* stop showing the search tabs, which have some issues
=> Tidy up project search

src/components/Editor/Breakpoint.js
Associated Issue: #3288
* updates the breakpoint pane so that it is document aware
* we'll need to update codemirror in the docker image, so once codemirror lands on MC I can do a docker update
=> [Breakpoints] Toggle between original and generated files

src/components/PrimaryPanes/Sources.css, src/components/PrimaryPanes/SourcesTree.js, src/components/shared/ManagedTree.css
Associated Issue: #3356
* Add the css padding for the tree node
=> fix source tree items moving

assets/panel/panel.js, src/client/firefox.js, src/client/firefox/commands.js
=> fix service workers

src/actions/ast.js, src/actions/tests/__snapshots__/ast.js.snap, src/actions/tests/ast.js, src/utils/editor/expression.js, src/utils/parser/getSymbols.js, src/utils/parser/tests/__snapshots__/getSymbols.js.snap
=> WIP Feature/3263 preview start using symbols in preview

src/components/Editor/Editor.css, src/components/Editor/index.js, src/components/Editor/tests/__snapshots__/Editor.js.snap
=> [Breakpoints] Breakpoints disappear on layout change

src/components/PrimaryPanes/index.js, src/reducers/types.js
=> Fix source search shortcut

assets/images/Svg.js, assets/images/vuejs.svg, src/utils/frame.js
Associated Issue:  #3385
* Add VueJS logo
* Add VueJS Frame collapsing
Jest seems to be broken right now, manually tested.
=> Vuejs callstack

src/utils/parser/tests/__snapshots__/getSymbols.js.snap, src/utils/parser/tests/fixtures/es6.js, src/utils/parser/tests/getSymbols.js, src/utils/parser/utils/ast.js
* fixes a bug where i couldn't use preview in actions/ast.js lol
* found the babylon plugin here: https://github.com/babel/babylon
=> fix rest spread

src/components/Editor/CallSite.js, src/components/Editor/Preview.js, src/components/Editor/index.js, src/utils/editor/index.js, src/utils/editor/types.js, src/utils/wasm.js
Associated Issue: #3403
* Provided types for EditorPosition and EditorRange
STR is provided in #3403
=> Adding types to the editor position/range objects.

src/components/Editor/Breakpoint.js, src/components/Editor/CallSite.js, src/components/Editor/HighlightLines.js, src/components/Editor/HitMarker.js, src/components/Editor/index.js, src/components/Editor/tests/__snapshots__/Editor.js.snap, yarn.lock
1. protects against cases where editor is not set
2. removes unnecessary guards
there is likely an abstraction we can add in the future to protect us further
=> Fix editor state

src/components/SecondaryPanes/index.js
=> Fix input warning

src/components/Editor/index.js
=> BugFix: Debug Line hangs around when the layout changes

package.json, src/actions/sources.js, src/actions/tests/sources.js, src/actions/tests/tabs.js, src/components/Editor/Breakpoint.js, src/components/Editor/CallSite.js, src/components/Editor/HighlightLines.js, src/components/Editor/HitMarker.js, src/components/Editor/index.js, src/components/Editor/tests/__snapshots__/Editor.js.snap, src/components/PrimaryPanes/Sources.css, src/components/SymbolModal.js, src/components/shared/ManagedTree.css, src/components/shared/ManagedTree.js, src/reducers/sources.js, src/utils/parser/tests/__snapshots__/getSymbols.js.snap, src/utils/parser/tests/fixtures/es6.js, src/utils/parser/tests/getSymbols.js, src/utils/parser/utils/ast.js, yarn.lock
includes patches from next slated for master
=> Bump master

package.json, yarn.lock
Associated Issue: #3357 
pulls in this fix: https://github.com/devtools-html/devtools-core/pull/515
=> bump source editor

src/components/Editor/SearchBar.js, src/components/Editor/tests/SearchBar.js, src/components/Editor/tests/__snapshots__/SearchBar.js.snap, src/test/tests-framework.js, src/test/tests-setup.js, src/utils/search/get-matches.js, src/utils/search/tests/get-matches.js
Associated Issue: #3433 
* ensure query is not empty
Gif
=> FileSearch does not update match count

src/components/Editor/index.js
Associated Issue: #3411 
* fixes line scrolling by appropriately setting the pending jump line
* we'll update the webconsole test when we make a new release
=> Scroll onload

src/components/SecondaryPanes/Frames/tests/Frames.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.js.snap
=> add tests for framework grouping

src/components/ProjectSearch/ProjectSearch.css, src/components/ProjectSearch/TextSearch.css, src/components/ProjectSearch/TextSearch.js, src/utils/sources-tree.js, src/utils/tests/sources-tree.js
* Added scrolling of search list
* Show just the relative url i.e remove domains
* Show file icons for the file paths
* add test for `getRelativePath`
* Change the font for results
=> cleanups and fixes

src/components/App.css, src/components/SecondaryPanes/Breakpoints.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Expressions.js
Associated Issue: #3465 
* added a util that we need anyway
* cleaned up the css a bit (had an unused flexbox
* adjusted html elements to be a bit more semantically informative
=> Watch Expression the remove button is often hidden by the scroll bar

src/components/Editor/index.js, src/test/mochitest/browser_dbg-breakpoints-cond.js
Associated Issue: #3463
* got confused between editor and source lines
=> show conditional breakpoint panels on the correct line

src/actions/pause.js, src/test/mochitest/browser_dbg-expressions.js, src/test/mochitest/head.js
=> Clear expressions

src/components/ProjectSearch/TextSearch.js
Associated Issue: #3467
* Add the line option to `searchSource`
=> flashing the line that the text was found on

src/test/mochitest/browser_dbg-breakpoints-reloading.js
=> longer timeout

src/components/ProjectSearch/TextSearch.css, src/components/ProjectSearch/TextSearch.js, src/utils/sources-tree.js
Associated Issue: #3501
* Changed the font to match the editor
* Expand/ Collapse the list on pressing enter
* Open source file on pressing enter
=> Keyboard access

src/components/Editor/Preview.css, src/components/Editor/Tabs.css, src/components/PrimaryPanes/Sources.css, src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/SecondaryPanes.css, src/components/SymbolModal.css, src/components/shared/Dropdown.css, src/components/shared/Modal.css, src/components/shared/ObjectInspector.css
=> Dark theme tweaks

src/actions/project-text-search.js, src/actions/sources.js, src/actions/tests/__snapshots__/project-text-search.js.snap, src/actions/tests/project-text-search.js, src/actions/tests/tabs.js, src/utils/search/index.js, src/utils/search/worker.js
Associated Issue: #3510 
* updates the project text search test to actually be async
=> Fix race condition with project text search tests

README.md
I joined the hangout instead of the Vidyo .
My hope is that with this change won't happen to anyone else.
Timezone conversions are a pain.
* change 1
* change 2
=> readme clarification

src/actions/sources.js, src/actions/tests/__snapshots__/breakpoints.js.snap, src/actions/tests/breakpoints.js, src/actions/tests/sources.js
Associated Issue: #3531 
Added tests
=> [PrettyPrint] add unit tests for toggle pretty print

src/components/Editor/Breakpoints.js
=> Convert Breakpoints component to jsx

src/actions/sources.js, src/components/Editor/Tabs.js, src/components/SymbolModal.js, src/reducers/ui.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-editor-search.js, src/test/mochitest/head.js
Associated Issue: #3475
* add some logic to selectSource
* drop redundant tab logic
* add a test
=> File Search - selecting another source

src/client/index.js
=> Fix typo in client console message

src/components/Editor/index.js
* Convert the Editor component to JSX
=> Convert Editor component to JSX.

src/components/stories/tabs.js
Associated Issue: #3557
* add setActiveSearch property to storybook
=> Add setActiveSearch function to tab storybook

src/components/shared/Button/Close.js
Had a few more minutes, did one more
=> Update CloseButton to use jsx

CONTRIBUTING.md
=> Add Yulia and Victoria

assets/images/Svg.js
=> Convert Svg() to JSX

src/components/shared/Dropdown.js
* Convert React.createElement calls to JSX in Dropdown.js
Desk testing functionality and staring at the code really hard to make sure nothing seems too weird.
=> Dropdown to JSX

src/components/Editor/Tabs.js
Associated Issue: #3506
* JSX all the things
=> Tabs to jsx

src/components/SymbolModal.js, src/components/tests/SymbolModal.js, src/components/tests/__snapshots__/SymbolModal.js.snap
Associated Issue: #3584
the input wrapper was surrounding results as well. looks like we can easily mess up the dom heirarchy.
=> Show result list

package.json, src/components/ProjectSearch/TextSearch.js, src/components/SymbolModal.js, src/components/shared/Autocomplete.js, src/components/shared/Modal.css, src/components/shared/Modal.js, src/components/shared/SearchInput.js, src/components/tests/__snapshots__/SymbolModal.js.snap, src/test/mochitest/browser_dbg-searching.js, yarn.lock
Associated Issue: #3495 
* Fixes the focus issue across all search inputs. They now take focus when enabled.
* Bump yarn.lock to match updated devtools-reps version
* CSS got reformatted by prettier?
=> Fix focus issues

bin/copy-assets.js
Associated Issue: no issue
* Added handling of the promise rejection in `bin\copy-assets.js` script
- just perform `yarn copy-assets`
=> handle promise rejection

src/components/shared/Autocomplete.js, src/components/shared/ResultList.js, src/components/shared/SearchInput.js, src/components/tests/__snapshots__/SymbolModal.js.snap
=> Convert Autocomplete, ResultList, and SearchInput to JSX

src/components/SecondaryPanes/Scopes.js
* Replace all React.createElement calls to JSX in Scopes.js
Desk testing. No snapshot test to confirm against. Are we wanting to increase our snapshot coverage going forward?
=> Scopes to JSX

src/test/mochitest/browser_dbg-pretty-print.js, src/test/mochitest/head.js
addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1282269#c30
fixes #3336
* resolves toolbox intermittent
* fixes another intermittent with pretty-print
=> Fix timing issue

src/components/Editor/SearchBar.js, src/components/Editor/tests/__snapshots__/SearchBar.js.snap
=> Convert SearchBar to JSX

assets/panel/debugger.properties, src/actions/breakpoints.js, src/components/SecondaryPanes/Breakpoints.js
Associated Issue: #3575 
* Added option to remove currently selected breakpoint
* Added option to remove all breakpoints
=> Added option to remove all breakpoints

src/components/ProjectSearch/SourceSearch.js, src/components/ProjectSearch/TextSearch.js, src/components/ProjectSearch/ToggleSearch.js, src/components/ProjectSearch/index.js
Associated Issue: #3506
Converted the files
src/components/ProjectSearch/index.js
src/components/ProjectSearch/SourceSearch.js
src/components/ProjectSearch/TextSearch.js
src/components/ProjectSearch/ToggleSearch.js
To JSX.
The behaviour should be as before.  See
https://github.com/devtools-html/debugger.html/pull/3396
For an example gif showing the expected behaviour.
=> convert ProjectSearch/*.js files to JSX

src/components/SecondaryPanes/Breakpoints.js, src/components/shared/ManagedTree.js
Add  missing propTypes that the linter was complaining about
=> add missing proptypes

assets/images/Svg.js
Associated Issue: #3596 
* added existing ng svg to List
* replaced throwing error in dev mode with console.warn
1. open http://todomvc.com/examples/angularjs/#/
2. set a breakpoint
3. verify that icon gets displayed
=> add angular icon

src/components/shared/Modal.js
Changed Modal to JSX syntax
I am quite unsure about the "Slide"-component...
=> Convert modal to jsx

assets/panel/debugger.properties, src/actions/breakpoints.js, src/components/Editor/Breakpoints.js, src/components/SecondaryPanes/Breakpoints.js, src/reducers/breakpoints.js, src/reducers/pending-breakpoints.js, src/reducers/types.js
Associated Issue: #3630 
Added the following menuitems to breakpoint context menu:
* Enable breakpoint
* Disable breakpoint
* Enable others
* Disable others
* Remove others
* Enable all breakpoints
* Disable all breakpoints
=> Added additional menuitems to context menu

assets/panel/prefs.js, configs/development.json, configs/firefox-panel.json, src/components/ProjectSearch/index.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-search-project.js, src/utils/prefs.js
I'm adding a mochitest so that we can have a simple smoke test. Also, importantly i'm using prefs instead of configs to flag project search because we need to be able to flip it in the test.
=> test project search

src/components/PrimaryPanes/Outline.js
Associated Issue: ##3506
Swapped Outline js over to JSX 
Since I was converting a working component to JSX 
I tested this by running the master  branch in a different window and ensuring all the functionality from Outline  exists
=> Convert Outline to JSX

configs/development.json
this feature should be on for people locally
=> Turn on features

src/components/ProjectSearch/TextSearch.css, src/components/stories/TextSearch.js, src/components/stories/helpers/shortcuts.js
Associated Issue: #1108
* fix storybook
* tweak colors
=> minor project search improvements

docs/mochitests.md, src/test/mochitest/browser_dbg-search-project.js
* fixes a new intermittent
* adds some docs
=> fix project search intermittent

src/components/Editor/DebugLine.js, src/components/Editor/index.js, src/components/Editor/tests/DebugLine.js, src/components/tests/__snapshots__/SymbolModal.spec.js.snap
=> [DebugLine] expressions are not marked when selecting sources

src/components/Editor/SearchBar.js, src/components/ProjectSearch/TextSearch.css, src/components/ProjectSearch/TextSearch.js
Associated Issue: #3650 
*TextSearch.css
* TextSearch.js
Do a Project search on the files hit by debugger and the search bar should be fixed
=> Project search

src/components/Editor/Preview.css, src/components/Editor/Preview.js, src/components/stories/Preview.js
Associated Issue: #3506  #3487 
* Convert Preview and its story to JSX, fixing a bug along the way.
=> Convert Preview component to JSX.

src/components/shared/Accordion.js
=> Convert Accordion to JSX

src/components/shared/ManagedTree.js
* use JSX
* remove dead code
I only opened ManagedTree on master & my branch and looked if it looks and behaves the same
=> Convert ManagedTree to JSX

package.json, yarn.lock
Associated Issue: #3162 
smallest change ever
=> add immutable

src/test/mochitest/browser_dbg-search-project.js
=> update project search test

src/components/SecondaryPanes/EventListeners.js
* use JSX syntax
I only opened EventListeners on master & my branch and looked if it looks and behaves the same
=> Convert EventListeners to JSX

package.json, src/components/ProjectSearch/TextSearch.css, src/components/ProjectSearch/TextSearch.js, src/test/mochitest/head.js, src/test/tests-framework.js, src/utils/parser/utils/ast.js
* small embarrassing US issues
* filter results that don't have a file path
=> Fix two small project text search bugs

src/components/PrimaryPanes/SourcesTree.js, src/utils/sources-tree/addToTree.js, src/utils/sources-tree/createTree.js, src/utils/sources-tree/getURL.js, src/utils/sources-tree/index.js, src/utils/sources-tree/sortTree.js, src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap, src/utils/sources-tree/tests/__snapshots__/sortTree.spec.js.snap, src/utils/sources-tree/tests/addToTree.spec.js, src/utils/sources-tree/tests/collapseTree.spec.js, src/utils/sources-tree/tests/sortTree.spec.js, src/utils/sources-tree/tests/utils.spec.js, src/utils/sources-tree/utils.js
associated issue: #3430 
screenshot:
=> [SourceTree] fails on https://facebook.github.io/react/

src/components/App.css, src/components/Editor/CallSite.css, src/components/Editor/Editor.css, src/components/Editor/Footer.css, src/components/Editor/Preview.css, src/components/Editor/SearchBar.css, src/components/Editor/Tabs.css, src/components/PrimaryPanes/Outline.css, src/components/PrimaryPanes/Sources.css, src/components/ProjectSearch/ProjectSearch.css, src/components/SecondaryPanes/Breakpoints.css, src/components/SecondaryPanes/CommandBar.css, src/components/SecondaryPanes/EventListeners.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Frames/Frames.css, src/components/shared/Accordion.css, src/components/shared/BracketArrow.css, src/components/shared/Button/Close.css, src/components/shared/Button/PaneToggle.css, src/components/shared/Dropdown.css, src/components/shared/ManagedTree.css, src/components/shared/ResultList.css, src/components/shared/SearchInput.css, src/components/shared/menu.css, src/components/shared/reps.css
Associated Issue: #3669
- Removed the "cursor: pointer" css property from all the css files. Now all the buttons use default pointer arrow
=> Removed pointer cursor for buttons

assets/panel/prefs.js, flow-typed/debugger-html.js, package.json, src/actions/breakpoints.js, src/actions/breakpoints/addBreakpoint.js, src/actions/pause.js, src/actions/tests/__snapshots__/breakpoints.spec.js.snap, src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap, src/actions/tests/helpers/breakpoints.js, src/components/Editor/Breakpoint.js, src/components/SecondaryPanes/Breakpoints.js, src/reducers/breakpoints.js, src/selectors/visibleBreakpoints.js, src/test/mochitest/browser_dbg-expressions.js, src/test/mochitest/examples/doc-scripts.html, src/utils/breakpoint/index.js, src/utils/parser/index.js, src/utils/parser/steps.js, src/utils/parser/utils/helpers.js, src/utils/parser/worker.js, src/utils/pause.js, src/utils/prefs.js, yarn.lock
Associated Issue: #3106
* adds stepping over async call support
=> add await stepping

bin/nom.js, package.json
Associated Issue: #2426
I was only able to test nom-script on Windows so this should be checked on Mac before merging.
=> Make nom script work cross platform
