- src/components/shared/Button/PaneToggle.css
Associated Issue: #2676 
- Added RTL styling for .toggle-button-end & .toggle-button-start.
Test Plan
- Opened the app in RTL mode and tested the changes.
- Opened the app again in the usual LTR mode and tested for correctness.
Screenshot
> #2676- PaneToggle.css Change

- src/feature.js
- src/utils/DevToolsUtils.js
- src/utils/assert.js
- src/utils/bootstrap.js
- src/utils/create-store.js
- src/utils/defer.js
- src/utils/editor/build-query.js
- src/utils/editor/expression.js
- src/utils/editor/index.js
- src/utils/editor/source-documents.js
- src/utils/editor/source-search.js
- src/utils/pretty-print/index.js
- src/utils/pretty-print/worker.js
- src/utils/redux/middleware/history.js
- src/utils/redux/middleware/log.js
- src/utils/redux/middleware/promise.js
- src/utils/sources-tree.js
- src/utils/test-head.js
(WIP) Refactor the following files to use ES module syntax:
- utils
- editor
- redux
- middleware
- pretty-print
> (WIP) Refactor to es modules

- src/utils/result-list.js
- src/utils/source.js
- src/utils/sources-tree.js
- src/utils/task.js
- src/utils/text.js
- src/utils/utils.js
- src/utils/worker.js
> Convert to ES modules

- src/components/SecondaryPanes/CommandBar.css
Closes #2676 
Second part of issue. Splitter appears to stop before command-bar.
* Add right border to command bar in rtl mode
|Before|After|
|--------|------|
|![s1](https://cloud.githubusercontent.com/assets/1755089/25670806/80a91df4-304b-11e7-8e08-4a4d3ae6882a.png)|![s2](https://cloud.githubusercontent.com/assets/1755089/25670812/850e7a10-304b-11e7-8a0f-9fe9484fab21.png)|
> Add right border to command bar in rtl mode

- flow-typed/debugger-html.js
- src/components/Editor/Tabs.js
- src/reducers/sources.js
- src/test/integration/runner.js
- src/test/integration/tests/tabs.js
- src/test/integration/utils/shared.js
* big change for a small fix. 
* added lots of types
* updated the integration test to check for tabs in the UI
> Fix tabs reselect

- src/components/Editor/Footer.js
Associated Issue: #2804 
* convert from PropTypes to props
> Switch Footer from PropTypes to flow props

- src/components/Editor/Footer.js
* use PureComponent
* cleanup import
> SourceFooter to extend PureComponent instead of Component

- src/components/Editor/index.js
There was a small typo in the selector used to query the expression values in the editor.
This PR fixes the problem but doesn't address how to automate preventing it from recurring. Writing an integration test for this seems like it would be quite tricky. Another path would be to get more Flow type coverage of these selectors, though that has been a bit tricky.
- Repro steps in #2814 should no longer reproduce
> Fix #2814: previewing values in editor when paused

- assets/panel/debugger.properties
- src/components/ProjectSearch.js
we just broke the symbol shortcut, but it's an easy fix.
> Fix symbol search shortcut

- src/components/Editor/Breakpoint.js
- src/components/Editor/ColumnBreakpoint.js
Associated Issue: #2804 
* Convert Breakpoint and ColumnBreakpoint from PropTypes to Flow
> Use Flow instead of PropTypes in Breakpoint and ColumnBreakpoint.

- configs/application.json
- configs/development.json
- configs/local.sample.json
- src/test/integration/utils/shared.js
- src/utils/bootstrap.js
- src/utils/create-store.js
- src/utils/redux/middleware/timing.js
Logs User Timing into the performance timeline view
* created a timing middleware for Redux
* created a `performance.actions` config for turning on the timing middleware
> Redux performance user timing middleware

- src/components/Editor/Preview.js
- src/components/SecondaryPanes/Expressions.js
- src/components/SecondaryPanes/Scopes.js
- src/components/shared/ManagedTree.js
- src/components/shared/ObjectInspector.js
- src/test/integration/tests/scopes-mutations.js
- src/test/mochitest/browser_dbg-scopes-mutations.js
- src/test/mochitest/browser_dbg-scopes.js
- src/utils/object-inspector.js
- src/utils/tests/object-inspector.js
Associated Issue:
Based on discussions with @jasonLaster, we decided to take out all the expand and actor caching for now, due to various issues found. We would be looking at better ways to fix this interesting problem in the near future.
One noticeable change would be that during stepping the expand states of the scope tree is no longer maintained, the user would have to expand the scopes again ... this way we are guaranteed to have correct scope information.
* Remove all the expand and actor caching across files
> Remove expand actor caching

- src/components/SecondaryPanes/EventListeners.js
* Converted PropTypes to flow types in EventListeners.js
`yarn flow` :trollface: 
so I think we could extract `Listener` type so it could be used by selectors etc. Wasnt sure where it should be located though. Also what should be in fact `Listener` is now extended by me with `breakpoint` property, as that is what `mapStateToProps` returns (extended `Listener`) - so this should ideally become some composite type of `Listener` and `{ breakpoint: ?Breakpoint }`
> Converted PropTypes to flow types in EventListeners.js

- src/components/WelcomeBox.css
- src/components/shared/Button/PaneToggle.css
Associated Issue: #2792
Also fixes vertical alignment in both horizontal and vertical toggle buttons.
Pretty consistent now! 😎
> Fix secondary pane toggle button in vertical mode

- src/components/App.js
- src/components/WelcomeBox.js
Associated Issue: #2804 
* Convert `App` and `WelcomeBox` to Flow Props
> Convert propTypes to Flow Props

- src/actions/sources.js
- src/actions/types.js
- src/actions/ui.js
- src/components/Editor/SearchBar.js
- src/components/Editor/index.js
- src/reducers/ui.js
- src/utils/makeRecord.js
* Converted PropTypes to flow types in `SearchBar.js`
* extracted few types in other files too, so they can be imported in `SearchBar.js`
* added `equals` method on `Record`'s type
> Converted PropTypes to flow types in SearchBar.js

- docs/getting-setup.md
> `--inspect=9223` - tells node to open a debugger server on 9223 instead of 9229.
This is **not necessary** for connecting debugger.html to node and is confusing: "am I supposed to change the port??"
----
This is a small doc fixup, no testing plan is included.
> Remove extraneous note on node.js setup

- src/components/SecondaryPanes/Expressions.js
- src/components/shared/ObjectInspector.css
- src/components/shared/ObjectInspector.js
- src/test/integration/tests/expressions.js
- src/test/mochitest/browser_dbg-expressions.js
Associated Issue: #2704 
* Modified Expressions.js to capture objects of exception type
* Modified ObjectInspector.js to capture unavailable objects
Test Plan
- Create watch for objects which wouldn't be available once the scope ends
- Once scope ends, the watched object must read "unavailable"
> Format Reference Errors

- src/components/Editor/Tabs.css
Associated Issue: #2790
I've removed the fixed height and also decreased tab's `padding` in order to improve UI alignments. (see Firefox note). I think using a negative margin does the job very well for the expected visual here, hope that's not a problem. :)
Styles are consistent among browsers.
Note: Please notice the tab height difference between the current debugger's tab (bottom) and my version (top).
> Fix tab height flusing with the header bug

- src/actions/sources.js
- src/reducers/sources.js
- src/test/integration/runner.js
- src/test/integration/tests/tabs.js
- src/test/integration/utils/commands.js
- src/test/integration/utils/shared.js
Associated Issue: #2615 and maybe #2638
* Make sure the `pendingSelectedLocation` is updated
> Fix for the last closed tab not getting persisted

- src/components/Outline.css
- src/components/Outline.js
- src/components/Sources.js
- src/components/shared/previewFunction.js
- src/components/tests/Outline.js
- src/components/tests/__snapshots__/Outline.js.snap
- src/test/integration/utils/shared.js
Associated Issue: #2562 
This is the styling ticket for the OutlineList view, which introduces a function list for a given file
- style the list of functions
- jump to the source location 
How to test:
- After starting the app and navigating to localhost:8000, click on the "settings" in the sidebar, and make sure that the "Source Outline" feature is enabled. 
- launch a browser and open a debugger from localhost:8000
- click through the source tree until you reach a .js file
- you should see an outline at the bottom
this needs a few more things like integrations tests
> OutlineView style the list of functions

- src/components/SecondaryPanes/Breakpoints.css
Associated Issue: #2841 
* The "remove breakpoint" button (X) is now aligned vertically.
* The "remove breakpoint" button (X) is now aligned with the checkbox above it.
* When breakpoints are added, the "Breakpoint" title bar will not get a height larger than the other titles.
* The checkbox for each item is now aligned with the file name.
Tested how the breakpoints menu looks on Firefox, Chrome and Edge on Windows 10.
Verified the functionality of all the items in it still work as expected (enable/disable breakpoints, remove breakpoints and clicking the file name).
> [Breakpoints] Needs polishing in alignment

- src/components/Editor/Tabs.css
- src/components/shared/Dropdown.css
- src/components/stories/tabs.js
Associated Issue: #2791 and #2858
* Improved tab UI vertical alignments and spacing, including **special tabs with icons**.
* Improved Storybook's tab factory: now`document.dir` is configured according. (This one is important, because it was preventing styles from `postcss-bidirection` to apply, so tests weren't consistent.)
* Fixed dropdown alignment.
> Make source tab's UI and tests consistent in RTL mode

- src/components/Editor/Preview.js
- src/components/Editor/index.js
- src/utils/editor/expression.js
> Don't show undef

- src/utils/fromJS.js
- src/utils/tests/fromJS.js
* fixes a scary wtf bug in `fromJS` caused by a value that happens to have a `hasOwnProperty` field that we want to format. Note, this is one of the perils of building a product for JS in JS.
* unit test the hell out of it
> fix weird fromJS bug

- src/components/SecondaryPanes/Scopes.js
- src/components/shared/ObjectInspector.js
* We had some issues where variables would not expand when you clicked on a label. The reason for that was that we had a special event handler for label clicks which was overriding the default.
* There are three components to look at when testing (Scopes, Expressions, Preview). The GIF below tests all three.
> Fix Object Inspector toggling

- circle.yml
- flow-typed/debugger-html.js
- package.json
- src/actions/breakpoints.js
- src/actions/sources.js
- src/actions/tests/breakpoints.js
- src/actions/tests/helpers/breakpoints.js
- src/actions/tests/pending-breakpoints.js
- src/actions/tests/sources.js
- src/client/firefox/commands.js
- src/reducers/breakpoints.js
- src/test/mochitest/browser_dbg-sources.js
- src/test/tests-setup.js
- src/types.js
Associated Issue: #2817
* Refactor how pending breakpoints are stored and updated in the reducer
* add lots of tests
* update checkPendingBreakpoints
> Refactor Pending Breakpoints to fix reloading

- package.json
- src/components/Editor/Editor.css
- src/components/SecondaryPanes/WhyPaused.css
- yarn.lock
Associated Issue: #1948
* updates the source editor to pull in the new debug line styles
* removes an unused style in the debugger
* updates why paused a bit, I think we'll want to do more going forward in  #2889 but atleast it's no longer an eye sore
> Update paused styles

- src/test/mochitest/head.js
Fixes some issues referencing CM from the window
> query CM from the dom

- src/components/App.js
- src/components/Editor/index.js
Associated Issue: #2317
* Add `startPanelSize` and `endPanelSize` property to `Editor` component.
* Refresh editor size when the size is changed
> Resize conditional breakpoint panel after splitbox is resized

- src/components/Editor/Editor.css
- src/components/Editor/index.js
This updates the strategy for styling the pause line so that we use a new class instead of trying to override the old styles.
> Update pause styles (try 2)

- circle.yml
yarn 0.24.5 is the latest stable version, we were at 0.23.2
> Update circle to use yarn@0.24.5

- src/utils/parser/utils.js
- src/utils/tests/fixtures/resolveToken.js
- src/utils/tests/parser.js
Associated Issue: #2941 
* Adds `isBlockStatement` test to determine lexical scope to support `let`/`const` declarations
* Adds unit tests for retrieving variables within various scopes (`if`, simple block `{}`, IIFE, functions)
> add block statements to lexical scope determination

- src/components/Editor/Preview.js
- src/components/Editor/index.js
- src/utils/editor/expression.js
Associated Issue: #2692 
This is a **work in progress**... the screenshot below shows the desired enhancement, however, this introduces a `TypeError` when hovering over functions (screenshot of error added after the animation).
* add type check so getExpression does not return undefined
* All existing unit tests pass
Action shot:
Error:
> (WIP) Show preview on hovering over false booleans

- src/components/App.js
Minor bugfix
When left splitter (in LTR mode) is used to resize editor tabs were not being refreshed.
* Add `startPanelSize` property to `EditorTabs` so it gets refreshed when `startPanelSize` changes
|  |  |
|---------|------|
|Before|![recored-2017-05-22_201258-opt](https://cloud.githubusercontent.com/assets/1755089/26314454/a4d96712-3f2b-11e7-8a88-68daafbecd9d.gif)|
|After|![recored-2017-05-18_233304-opt](https://cloud.githubusercontent.com/assets/1755089/26314475/b418f418-3f2b-11e7-94df-831186b6e5f1.gif)|
> Show dropdown when resizing with splitter

- assets/panel/prefs.js
- src/reducers/ui.js
- src/utils/prefs.js
Associated Issue: #2850 
Preferences added for File Search options:
- Case-sensitive
- Regex
- Whole word
Test Plan
- Open the application and toggle the search options
- Go back/close application
- Open search options and the previously set values should be retained
> Save Search Modifiers as Prefs

- src/components/Sources.js
Associated Issue: #2993
* Check if outline is enabled before displaying outline toggle button
> Hide outline toggle button when outline is disabled

- src/client/firefox.js
- src/client/firefox/tests/onconnect.js
This fixes a race where panel.js can report that the debugger has
started, but where getSources will still return null for a source that
does in fact exist.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1364526
> Have firefox onConnect wait for newSources

- src/components/Editor/Highlight.css
- src/components/Editor/index.js
Fixes: #2983
Associated PR: https://github.com/devtools-html/devtools-core/pull/377 
This moves the highlight CSS back into the launchpad, which also means that the highlighting gets the yellow background.
> Add search highlighting

- src/utils/editor/source-search.js
Associated Issue: #2355
* removes `search.results` because it is too slow 
* the UI now just shows the number of results
* we should build a better algorithm for getting the match location
> Disable text search match index

- src/actions/breakpoints.js
- src/actions/sources.js
- src/actions/tests/helpers/breakpoints.js
- src/actions/tests/pending-breakpoints.js
- src/reducers/breakpoints.js
- src/test/integration/tests/breakpoints.js
- src/test/mochitest/browser_dbg-breakpoints.js
Associated Issue: #2817 
* updated pending breakpoint tests to use jest instead of expectjs
* made initialState for breakpoints be the initialState for the update function in the breakpoints reducer, rather than using a stale copy from when the file was initialized
* wrote tests for the bug
* fixed bug
This feature is unit / integration tested
set breakpoint:
disable breakpoint:
reload debugger:
> Bug/2817 breakpoints nightly won't delete breakpoints

- src/actions/sources.js
- src/actions/types.js
- src/reducers/sources.js
- src/selectors.js
Associated Issue: #2715
WIP 
Todo - Fix issue causing failing test
* Call the `selectSource` action on `closeTab/s` to select the next available tab
* If no source is found dispatch an action to trigger clearing of the currently loaded source
* export `getNewSelectedSourceId`
> make sure we deselect sources

- src/components/Editor/index.js
Associated Issue: #2908
* Check for `optimizedOut` property on the value
> remove optimized away values

- src/client/firefox/commands.js
- src/client/firefox/tests/__snapshots__/commands.js.snap
- src/client/firefox/tests/commands.js
- src/test/mochitest/browser_dbg-scopes.js
Associated Issue: #2849
* Fix logic for copying Safe getter values
* Fix tests
> Fix DOM event properties not showing up in the OI

- src/components/SecondaryPanes/Frames/index.js
Minor fix.
When callstack has `NUM_FRAMES_SHOWN` frames, `Collapse Rows` button does nothing.
| | |
|---|---|
|![recored-2017-06-03_222808-opt](https://cloud.githubusercontent.com/assets/1755089/26755580/99f4a39e-48ad-11e7-9a7b-fedd5526b486.gif)|![screenshot from 2017-06-03 22-25-31](https://cloud.githubusercontent.com/assets/1755089/26755582/9f9240fe-48ad-11e7-8237-0f2f4db8040b.png)|
> [Frames] Show collapse row button when there are more than NUM_FRAMES_SHOWN frames

- src/components/shared/ObjectInspector.js
Associated Issue: #3063
In the `ObjectInspector` component I added a check if `item` is primitive, and if true, increase the left margin by 15px.
---
> [ObjectInspector] Vertically align variable keys when inspecting objects

- src/components/Sources.css
- src/components/Sources.js
Associated Issue: #2901
As part of the outline view, the SVG button toggling the outline view of the sources pane has been replaced with tabs
* Replaced the toggle SVG with footer tabs for sources and outline view
> Add footer tabs to sources pane for outline view

- src/components/shared/ObjectInspector.js
- src/utils/object-inspector.js
- src/utils/tests/object-inspector.js
Associated Issue: #2946
* Adds additional logic so that window property names render properly on objects
Visual Testing
1. Run debugger
2. Enter expression in watch expression: `a = { aLocation: 1, location: 2};`
3. Both properties should display in the same design.
> fix object property styling on window property names (#2946)

- .babelrc
- src/components/Editor/Breakpoint.js
- src/components/Editor/ColumnBreakpoint.js
- src/components/Editor/ConditionalPanel.js
- src/components/Editor/SearchBar.js
- src/components/Editor/index.js
- src/components/SecondaryPanes/CommandBar.js
- src/components/shared/Autocomplete.js
- src/components/shared/Popover.js
- src/utils/bootstrap.js
Looks like we had a misconfiguration in the .babelrc
I did this because the weird path with `../node_modules/react-dom/dist/react-dom` was doing weird things to editor component tests. I swapped it out. things seem to be working as expected.
* remove line which was causing a recursive `react-dom/dist/react-dom/dist` address from babel-rc
* rename all instances of `../../../[etc]/node_modules/react-dom/dist/react-dom` to `react-dom`
- All Unit tests are passing. Need to double check if the build still works
> Use "react-dom" instead of "../../node_modules/react-dom/dist/react-dom"

- src/components/Editor/ConditionalPanel.css
- src/components/Editor/Editor.css
- src/components/Editor/index.js
Associated Issue: #2918 
* added new color for conditional breakpoint text in dark theme
* center the guillemet >> in the gutter
* made conditional breakpoint more resposive
One drawback is that conditional breakpoint is very tightly coupled with Codemirror's linewidget, where re-drawing logic resides. I turned off `noHScroll` flag, but in turn it made the close button to hide when editor windows becomes to narrow (check video)
Visual test is required:
- Open an editor
- Right-click on line numbers and select "Add Conditional Breakpoint"
- Check the visuals of the conditional breakpoint (text color, alighment, responsiveness)
> Polish conditional breakpoint

- src/utils/parser/index.js
- src/utils/parser/worker.js
* Moves getClosestExpression usage into the worker to decouple parser-related dependencies (babylon, parse-script-tags) from debugger.js
* Run `node bin/copy-assets.js` to verify babylon et al aren't included in debugger.js
* Launch debugger and verify that:
* expressions are resolved in preview
* getClosestExpression is called within the worker
> Move getClosestExpression into worker

- docs/updates/README.md
- src/components/Editor/SearchBar.js
Associated Issue: #2526 
* search query is cleared when search is closed
> [FunctionSearch] clear query after selecting an item #2526

- src/actions/tests/__snapshots__/ast.js.snap
looks like switching the call to the worker w/ the dispatcher util causes the flow data to be lost
> fix actions/ast test

- src/actions/pause.js
- src/actions/tests/ast.js
- src/actions/types.js
- src/client/firefox/commands.js
- src/client/firefox/create.js
- src/client/firefox/types.js
- src/components/Editor/Tabs.js
- src/components/Editor/index.js
- src/components/SecondaryPanes/Scopes.js
- src/reducers/pause.js
- src/selectors.js
- src/utils/frame.js
- src/utils/parser/tests/fixtures/var.js
- src/utils/scopes.js
- src/utils/tests/scopes.js
Associated Issue: #3072
This adds support for the new on demand frame scopes. It's important though that we don't remove the old system until the server has switched over.
* adds a firefox command for getting an environment
* adds a redux action and reducer for saving frame scopes
* updates the scopes component and util to support frame scopes
* Add some action unit tests
* Add the debugger client method
* Add the server endpoint
> Get environment

- src/actions/breakpoints.js
- src/actions/sources.js
- src/actions/tests/__snapshots__/pending-breakpoints.js.snap
- src/actions/tests/helpers/breakpoints.js
- src/client/firefox/commands.js
- src/reducers/breakpoints.js
- src/utils/breakpoint/index.js
This fixes an issue we were seeing with breakpoints being added when they already existed on the server.
This fix is basically reverting the behavior we had before.
> Revert breakpoint clearing

- assets/module-manifest.json
- package.json
- src/components/Editor/Editor.css
- src/components/Editor/SearchBar.css
- src/components/Editor/Tabs.js
- src/components/Outline.js
- src/components/SecondaryPanes/Expressions.js
- src/test/mochitest/head.js
* Updates from the past week
* Small fixes for the editor footer and a couple small details for tests
> Release a new version of the debugger

- src/client/chrome.js
- src/client/chrome/commands.js
- src/client/chrome/create.js
- src/client/chrome/events.js
- src/client/firefox/commands.js
- src/client/firefox/create.js
- src/client/firefox/events.js
- src/client/index.js
- src/components/Editor/Tabs.js
- src/components/SecondaryPanes/Breakpoints.js
- src/components/SecondaryPanes/WhyPaused.js
- src/utils/log.js
- src/utils/pause.js
- src/utils/redux/middleware/thunk.js
- src/utils/redux/middleware/wait-service.js
Refactor the following files to use ES module syntax:
> Continue conversion from commonjs to es modules

- src/components/Editor/Tabs.js
Associated Issue: #3083 
* change 'Copy Link Address' id from 'node-menu-close-tabs-to-right' to 'node-menu-copy-source-url'
> #3083: change 'Copy Link Address' id

- src/components/Editor/index.js
- src/utils/editor/index.js
Associated Issue: #3042 
* Removing the column breakpoints
- Set a bp on an empty line/comment that slides to the next line.
- Clicking on the bp on the gutter removes it
> Remove column breakpoint

- src/components/SecondaryPanes/Frames/WhyPaused.css
- src/components/SecondaryPanes/Frames/WhyPaused.js
- src/components/tests/__snapshots__/WhyPaused.js.snap
- src/utils/parser/tests/__snapshots__/closest.js.snap
- yarn.lock
Associated Issue: #3130 
* Changed the color of error message to var(--theme-graphs-full-red) and made it bold
- open the debugger
- turn on "Pause on uncaught exceptions"
- open this [example page](https://devtools-html.github.io/debugger-examples/examples/exceptions.html)
- when debugger pauses on exception you should see the error details in red
> style exceptions in WhyPaused as red

- src/actions/sources.js
- src/actions/types.js
- src/components/Editor/Tabs.js
- src/components/Editor/index.js
- src/components/stories/tabs.js
- src/reducers/sources.js
- src/utils/editor/index.js
Associated Issue: #3146
This fixes an annoying issue where the debugger would occasionally forget to jump to a line. the issue was that when you wanted to go to a source that was hidden, the first attempt would be to go to the line, then a second attempt would be to move the tab. The second attempt cleared the line number. The fix is to introduce a new action
> Fix 3146 - editor occassionaly doesn't jump to a line

- src/components/Editor/SearchBar.js
Associated Issue: #3152
* the method `toggleSearch` was called, which in turn calls `selectSearchInput` which selects the entire range in the input. But it doesn't focus.
I just added focus() inside `selectSearchInput`.
> Search bar doesn't get focus if already open

- src/utils/frame.js
Quick mapping for the new marketing page:
> Add render mapping

- bin/wtr-runner.js
- src/test/integration/runner.js
Associated Issue: #2634
This re-introduces the work done here: https://github.com/devtools-html/debugger.html/pull/2852 to have a wtr headless runner. The test runs fail, but it's still good to have in the codebase so that we can get the tests passing and then run it in CI.
NOTE: you need to start chrome headlessly to run the tests
canary --headless --remote-debugging-port=9222 https://chromium.org
> Add WTR Runner

- README.md
- docs/running-as-firefox-panel.md
Associated Issue: #3169 
Add documentation about how to run as a panel
> [Documentation] running the debugger as part of a firefox build

- .eslintignore
- configs/development.json
- src/actions/ast.js
- src/actions/tests/__snapshots__/ast.js.snap
- src/actions/tests/ast.js
- src/actions/tests/fixtures/scopes.js
- src/actions/tests/helpers/readFixture.js
- src/components/Editor/Editor.css
- src/components/Editor/index.js
- src/reducers/ast.js
- src/selectors/linesInScope.js
- src/utils/scopes.js
Associated Issue: #3180
This refactors out of scope lines a bit to support getting a list of in scope lines that can be used by the editor to check if a token is in scope on hover.
Jest tests
> Speed up Out Of Scope lines

- src/components/Editor/index.js
Associated Issue: #2668 
Added a check in `onGutterClick` to early return if the user right clicked using <kbd>ctrl</kbd>-click.
> Bugfix: ctrl-clicking gutter prematurely added breakpoint

- assets/panel/prefs.js
- src/utils/prefs.js
Associated Issue: #3068 
* Change the default case sensitive search modifier to be turned off, meaning the search is case-insensitive by default.
#goodnessSquad
> Change default case sensitive search modifier to off

- src/actions/navigation.js
- src/actions/tests/navigation.js
- src/client/firefox.js
- src/client/firefox/tests/onconnect.js
- src/components/SourcesTree.js
- src/test/mochitest/browser_dbg-sources.js
- src/utils/sources-tree.js
- src/utils/tests/sources-tree.js
Associated Issue: #2448 
This seems to work.
But I'm still not sure why the navigate action removes all sources from the state.
> [SoucesTree] Show the host domain first when the debugger opens

- src/components/Editor/Editor.css
- src/components/Editor/index.js
- src/test/mochitest/head.js
This updates our debug line highlighter so that it starts at the column we're paused at. This is more informative because we're often not paused at the beginning of a line.
I'd like to update `editor-highlight`
> highlight pause expressions

- src/components/Editor/Preview.js
- src/components/Editor/index.js
Associated Issue: #3058
* Show `undefined` and `null` in a tooltip.
1. Hover over variables with value undefined and null.
> [Preview] Show undefineds in a tooltip

- src/actions/tests/__snapshots__/ast.js.snap
- src/utils/parser/getOutOfScopeLocations.js
- src/utils/parser/getSymbols.js
- src/utils/parser/utils/closest.js
Associated Issue: #3209 
This offers much needed perf wins when debugging large 10K+ files (a.k.a. the debugger.js file). Previously the perf times were a couple seconds for finding the closest expression and out of scope lines and now they're a couple hundred milliseconds or less...
It's amazing how much it pays to be lazy.
I got these rough stats from adding logging to our worker utils
```js
37         var t0 = performance.now();
38         this.worker.postMessage({ id, method, args });
39
40         const listener = ({ data: result }) => {
41           if (result.id !== id) {
42             return;
43           }
44
45           this.worker.removeEventListener("message", listener);
46           var t1 = performance.now();
47           console.log(`${method} took:` + (t1 - t0) + " …
```
> bail early on closestExpression

- src/components/Editor/SearchBar.js
The latest redux refactor broke some basic commands. When we have the search modal we should revisit our tests
> fix toggling function search

- flow-typed/debugger-html.js
- src/actions/breakpoints.js
- src/actions/tests/__snapshots__/pending-breakpoints.js.snap
- src/client/chrome/commands.js
- src/client/chrome/create.js
- src/client/firefox/commands.js
- src/client/firefox/create.js
- src/client/firefox/types.js
- src/reducers/breakpoints.js
- src/test/integration/runner.js
- src/test/integration/tests/index.js
- src/test/integration/tests/sourcemaps-reloading.js
- src/test/integration/tests/sourcemaps.js
- src/test/integration/tests/tabs.js
- src/test/integration/utils/commands.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-sourcemaps-reloading.js
- src/test/mochitest/head.js
Associated Issue: #3182
* I ran into an issue debugging [devtools-reporter](https://github.com/jasonLaster/devtools-reporter). The issue was that on reload the BP id had changed, but the source id and location were the same... Which got me thinking we should be consistent and use location ids
* I also set about adding some integration tests and cleaning them up. I'll do a mochitest for this as well before it lands
> switch bpclient ids to location ids

- src/components/App.js
- src/components/Editor/Tabs.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-toggling-tools.js
- src/test/mochitest/head.js
- src/utils/ui.js
Associated Issue: #3168 #3033
* the problem was that we were unmounting codemirror when we toggled tools. We fix that, by first checking if the app is visible when we might unmount the editor.
* simple integration test for toggling tools
> Stop scrolling when we toggle tools

- src/actions/navigation.js
- src/actions/tests/navigation.js
- src/client/firefox.js
- src/client/firefox/tests/onconnect.js
- src/reducers/pause.js
- src/reducers/sources.js
- src/reducers/tests/sources.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-breakpoints-reloading.js
- src/test/mochitest/browser_dbg-tabs.js
- src/test/mochitest/head.js
Fixes: #3221
We were seeing two issues:
1. tabs were not selected on reload
2. breakpoints were jumping (we saw this same kinda thing earlier) the root cause is when we try to add the same bp again
how is everything fixed? I changed the action from navigate to connect which now just sets the debuggee url and does not clear any state. I also added lots of tests!
> Fix reloading issue with selected tabs + breakpoints

- src/components/SecondaryPanes/Breakpoints.js
Associated Issue: #3170
* use the `getFilename` utility function instead of the `basename`, for consistency with Tabs and the Sourcetree
> Fix empty index.html breakpoints

- configs/development.json
- src/actions/tests/__snapshots__/ast.js.snap
- src/utils/parser/getOutOfScopeLocations.js
- src/utils/parser/getSymbols.js
- src/utils/parser/tests/__snapshots__/getOutOfScopeLocations.js.snap
- src/utils/parser/tests/fixtures/outOfScopeComment.js
- src/utils/parser/tests/getOutOfScopeLocations.js
- src/utils/parser/utils/ast.js
Associated Issue: #3055
* in getOutOfScopeLocations.js changed function findFunctions to findSymbols and concat functions to comments
the only reason this PR is under my account is that @giladartzi's machine didn't compile the code properly. Beautiful work in #goodnessSquad
> Include comments in "out of scope" locations

- bin/check-warn-yarn-changed.js
- bin/post-checkout.js
- bin/post-merge.js
- bin/post-rewrite.js
- package.json
- yarn.lock
Associated Issue: no issue
* Add yarn.lock checks for `git checkout` and `git rebase` too, in addition to the existing `git pull`
* Use npm-run-all to run push scripts in parallel
I tried to move back and forth between branches, tried to rebase, tried to merge another branch, and tried to push, all with `yarn.lock` changes.
> Add more cases to warn for yarn lock changes, and run prepush script in parallel

- src/actions/breakpoints.js
- src/actions/tests/__snapshots__/pending-breakpoints.js.snap
- src/actions/tests/breakpoints.js
- src/actions/tests/helpers/breakpoints.js
- src/actions/utils/breakpoints.js
- src/components/Editor/Breakpoint.js
- src/components/Editor/Breakpoints.js
- src/components/Editor/CallSites.js
- src/components/Editor/GutterMenu.js
- src/components/Editor/index.js
- src/components/Editor/tests/Editor.js
- src/components/Editor/tests/__snapshots__/Editor.js.snap
- src/reducers/breakpoints.js
- src/reducers/types.js
- src/selectors.js
- src/selectors/breakpointAtLocation.js
- src/selectors/linesInScope.js
- src/selectors/visibleBreakpoints.js
- src/test/mochitest/browser_dbg-editor-select.js
- src/test/mochitest/browser_dbg-sourcemaps2.js
- src/utils/breakpoint/index.js
- src/utils/editor/expression.js
- src/utils/editor/index.js
- src/utils/editor/source-documents.js
This is a follow up refactor. The goal is to provide some abstractions so that BPs are better represented in the components:
1. Components don't know/nor care if they're original or generated
2. Components only care about showing BPs
3. Toggle BP takes a line and column and does the rest
4. The reducer formats a generic BP with the "right" location
> Refactor Breakpoints to be location symmetric

- src/components/Editor/Breakpoint.js
- src/utils/editor/source-documents.js
I found this small issue when reviewing the recent refactor.
The problem was that `currentDoc` was our of sync with what codemirror believed was current. This replaces the new state by using codeMirror as the authoritative source.
> fix toggling sources

- src/components/Editor/Tabs.js
- src/components/ProjectSearch/TextSearch.css
- src/components/ProjectSearch/TextSearch.js
Associated Issue: #3326
- stop showing files that have no matches
-  add "results" to the tab title to indicate its showing results
- fixed jumpy text when line is focused on
> Project text search styling

- src/components/PrimaryPanes/Sources.css
Associated Issue: #3253 
* Changed the CSS of the class `.no-sources-messages` so message appears centered vertically and not at the top.
- Launch the debugger and open a website with no sources. I used https://devtools-html.github.io/debugger-examples/
- See in the sources panel how the message looks like. It should appear aligned at the center, both horizontally and vertically.
- Open a new website that has sources. I used https://www.github.com
- See that the sources panel appears as usual
How the "This page has no sources" messages looks like now:
When the page does have sources, it looks OK:
---
I'm running into trouble setting up the project locally on my machine with yarn. I had to bypass the pre-push hook, but since this is only a CSS change…
> fix 'this page has no sources' misalignment (issue 3253)

- src/utils/parser/worker.js
* Exposes the clearSymbols handler on `parser` worker. Fixes minor error on worker.
> parser error fix: expose clearSymbols handler on worker

- src/components/SymbolModal.js
Associated Issue: #3327
This is a workaround to prevent the bookmarks organizer from opening under Linux.
> prevent Ctrl+Shift+O from opening bookmarks organizer under Linux

- assets/images/Svg.js
- assets/images/vuejs.svg
- flow-typed/debugger-html.js
- package.json
- src/actions/navigation.js
- src/client/firefox.js
- src/client/firefox/create.js
- src/client/firefox/tests/onconnect.js
- src/components/Editor/Breakpoint.js
- src/components/Editor/CallSite.js
- src/components/Editor/CallSites.js
- src/components/Editor/Editor.css
- src/components/Editor/index.js
- src/components/Editor/tests/__snapshots__/Editor.js.snap
- src/components/PrimaryPanes/index.js
- src/components/SecondaryPanes/Breakpoints.js
- src/reducers/types.js
- src/selectors/linesInScope.js
- src/utils/breakpoint/index.js
- src/utils/editor/index.js
- src/utils/editor/source-documents.js
- src/utils/frame.js
- src/utils/source.js
- src/utils/tests/source.js
- src/utils/tests/wasm.js
- src/utils/wasm.js
- yarn.lock
* adds code generation for editor
* better source-to-editor text line mapping
Example test plan (for original source):
1. Open https://devtools-html.github.io/debugger-examples/examples/wasm/fib/fib.index.html
2. Open debugger and refresh fib.index.html page (the latter is to enable wasm debugging)
3. Find/open "fib.c"
4. Set breakpoint at line 4
5. Refresh refresh fib.index.html page
Alternative test plan (for wasm):
3a. Find/open "wasm:https://devtools-html.github.io/debugger-examples/examples/wasm/fib/fib.index.html:d65901927dbe8357"
4a. Set breakpoint at the beginnig of $func5 @0000027D
5a. Refresh refresh fib.index.html page
Expected results: stop at set breakpoint(s).
Some other defects found:
> WebAssembly text generation on debugger side

- src/components/PrimaryPanes/Sources.css
- src/components/shared/ManagedTree.css
- src/components/shared/ManagedTree.js
Associated Issue: #3381 
* makes sure the managed tree styles are applied
* we can drop the extra div when we have a better story for shared componenets
> Fix source tree jumpiness

- src/actions/sources.js
- src/actions/tests/sources.js
- src/actions/tests/tabs.js
- src/reducers/sources.js
Fixes: #3318
* stop showing tabs that don't have a URL (was causing issues and showing the wrong source)
* stop selecting sources that don't have a URL
Unit test
> [WatchExpressions] The debugger is wrongfully showing a watch expression as a source

- src/components/PrimaryPanes/Sources.css
- src/components/SymbolModal.js
- yarn.lock
Associated Issue: #3404 
* Clear the query for SymbolModal when you close it.
* yarn.lock updated for some reason and prettier did its thing.
> Clear the symbol search query on close.

- src/components/SymbolModal.js
this keeps cmd+shift+o from opening the devtools settings pane
tested in the panel
> fix popup shortcut

- configs/development.json
- src/utils/editor/source-documents.js
Associated Issue: #3383
* Fixes a situation where toggling sources causes 1px BPs
[STR] 
1. navigate to https://devtools-html.github.io/debugger-examples/examples/todomvc/
2. add a bp in todo-view.js and todo.js
3. reload (view a bp in todo.js)
4. click on the todo-view.js in the bp panel
AR: see the BP in todo-view
ER: see a 1px bp
> Disable updating line number formats

- package.json
- yarn.lock
Associated Issue: #3032 
* Added `box-shadow` to rule `.popover .preview` in `preview.css`
Since this is a visual change, no tests, but there's a screenshot below.
#GoodnessSquad
> #3032: added drop shadow to preview popup

- src/components/SecondaryPanes/Frames/index.js
* fixes collapsing for both frames that are not grouped
> Fix framework grouping collapsing

- src/components/Editor/Breakpoints.js
- src/components/Editor/tests/Breakpoints.js
- src/components/Editor/tests/__snapshots__/Breakpoints.js.snap
Associated Issue: #3439 
When I started working on this issue, I wasn't sure what was wrong and it looked quite concerning, so i went ahead and started on it.
It looks like the error was coming from column breakpoints being ignored when column bps are enabled, and since all breakpoints which come from original sources have columns, these were being ignored. I removed the filter, as the breakpoints render correctly without it.
Caveat: Not sure if this is how it should work, or if column breakpoints are enabled by default.
I tested in a couple of spots:
TODO mvc: https://devtools-html.github.io/debugger-examples/examples/todomvc/
Sourcemapped files: http://wbamberg.github.io/example-websites/source-mapping/index.html
messy sourcemapped files: …
> breakpoints disappear on sourcemapped sources

- src/components/Editor/index.js
We were blowing up when the function search modal was open and highlighting text and you changed layouts. On the bright side, i found this today because i use function search ALL the time now.
> Editor state (part 3)

- src/actions/tests/breakpoints.js
- src/actions/tests/helpers/breakpoints.js
- src/actions/tests/helpers/threadClient.js
- src/actions/tests/pending-breakpoints.js
- src/actions/tests/sources.js
- src/actions/tests/tabs.js
> Bugfix: TypeError: client.sourceContents is not a function

- src/utils/prefs.js
Associated Issue: #3449
should clear the pending breakpoints
> bump prefs schema

- src/components/SecondaryPanes/SecondaryPanes.css
- src/components/SecondaryPanes/index.js
Associated Issue: #3426 
* Overflow the secondary panel that contains the commandbar
Pause on a breakpoint. Open up window/this vars until you have plenty of place to scroll. Scroll beyond the height of your viewport.
Notice the commandbar will now keep stuck all the way to the bottom.
> Fix commandbar stopping 

- configs/development.json
- src/client/firefox.js
- src/client/firefox/commands.js
- src/client/firefox/create.js
- src/client/firefox/events.js
- src/client/firefox/types.js
- src/utils/editor/source-documents.js
Associated Issue: https://devtools-html.slack.com/archives/C3VTWQ4KZ/p1500478468288028
Old Firefox browsers cannot return binary source. So we need to disable source.isWasm for these.
*  disable source.isWasm for browsers that does not support binary source
Observe no console errors about `getSourceLineCount`
> Do not set source.isWasm attribute for old Firefox.

- src/components/App.css
- src/utils/sources-tree.js
- src/utils/tests/__snapshots__/sources-tree.js.snap
- src/utils/tests/sources-tree.js
Associated Issue: #3430
* bail early when we get to a case we can't handle in the source tree
* screenshot shows the files in source search, but not in the source tree
* add a unit test to verify the behavior
> Support complex file trees

- src/components/SecondaryPanes/index.js
previously we would toggle the pane when you click the checkbox. Now we just toggle the bps.
> Fix bp toggling

- src/components/shared/previewFunction.css
Associated Issue: #3447
* Remove `line-height` of `.function-signature` 
|After |Before |
|---|---|
|![scr1](https://user-images.githubusercontent.com/1755089/28746149-108662b4-74a4-11e7-86bc-b25d3f64422c.png)|![scr2](https://user-images.githubusercontent.com/1755089/28746150-1426ce40-74a4-11e7-8ba9-2d2a3647cd11.png)|
> [Expressions] Items should be of same height

- assets/panel/debugger.properties
- src/components/App.css
- src/components/Editor/tests/__snapshots__/SearchBar.js.snap
- src/components/shared/Autocomplete.css
- src/components/shared/Autocomplete.js
- src/components/shared/SearchInput.js
- src/components/stories/SearchInput.js
- src/components/tests/__snapshots__/SymbolModal.js.snap
Associated Issue: #3469 
* add absolute-center util
* remove flexbox
* update message
* add noNegativity option to allow sad face opt-out
Before:
After:
Other places where search input is used still have the same styles:
> [SourceSearch] Improve not-found UI

- src/components/stories/Outline.js
* Changing `300` to `300px` with this story to prevent an invalid value warning within the console.
Visit the Storybook "Outline" examples, see no warning.
> Prevent width value warning error in outline stories

- src/components/SecondaryPanes/CommandBar.css
Associated Issue: #3369 
* Added simple selector modification to not highlight disabled buttons
Hover over disabled buttons -- no more background color change.
> Fix #3369 - Remove button hover color if button is disabled

- src/components/stories/tabs.js
Clicking any tab in the "Editor Tabs" stories triggers an error because `closeActiveSearch` is not provided as a prop
* Add a stub `closeActiveSearch` function to prevent the error
Click any tab and you no longer see the `closeActiveSearch` error.
> Add stub 'closeActiveSearch' so Tabs stories don't error out

- src/utils/parser/tests/__snapshots__/closest.js.snap
- src/utils/parser/tests/__snapshots__/getSymbols.js.snap
- src/utils/parser/tests/fixtures/func.js
Associated Issue: #3158
* Add examples of export, async and export async functions to the func.js parser tests.
* Update the corresponding snapshot files.
> Test symbol extraction for async/exported functions

- assets/panel/debugger.properties
- src/components/ProjectSearch/ProjectSearch.css
- src/components/ProjectSearch/SourceSearch.js
- src/components/ProjectSearch/TextSearch.css
- src/components/ProjectSearch/TextSearch.js
- src/components/ProjectSearch/ToggleSearch.js
- src/components/ProjectSearch/index.js
- src/components/shared/Autocomplete.js
The code is not too pretty, but it does what is required and since this
is a temporary ui I think it is ok.
Autocomplete was modified to render children before results
Associated Issue: #3091 
* This adds UI for the project text search and files search (CMD or CTRL + o and CMD or CTRL + Shift + f) as shown in the image in issue 3091 
* This is temporary UI
* Enable "projectTextSearch" in `configs/local.json`
* Press the above key combos to bring up the search bar
* Click on the active "files" or "text" link to change the UI
> [ProjectSearch] toggle between project text search and file name search

- assets/panel/debugger.properties
Associated Issue: #3355
Removed following string from debugger.properties since it is not used any more.:
1. `showSourcesTooltip` string
2. `showOutlineTooltip` string
> Removed two unsused strings from debugger.properties

- src/components/PrimaryPanes/SourcesTree.js
- src/components/ProjectSearch/TextSearch.js
- src/components/SecondaryPanes/ChromeScopes.js
- src/components/SecondaryPanes/tests/Expressions.js
- src/components/SecondaryPanes/tests/__snapshots__/Expressions.js.snap
- src/components/shared/ManagedTree.js
- src/components/shared/ObjectInspector.js
- src/components/stories/ManagedTree.js
Associated Issue: #3496 
* change getKey to getPath to maybe make it clearer that it has more
tasks than setting the key
* make objectInspector getPath method create a unique path, even if the
element is undefined
Unit tests
> [Expressions] should have a unique key

- src/components/SymbolModal.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-editor-search.js
- src/test/mochitest/head.js
Associated Issue: #1928 
* add a test
* take modal out of the dom on close
> Fix editor search iteration

- src/components/Editor/Footer.js
- src/components/shared/Button/PaneToggle.js
We may want to consider a size standard for the stuff like `classnames()` which can get large; maybe use a `const` defined before the JSX starts.  Let me know.
> Convert editor footer and PaneToggle to jsx

- src/test/tests-framework.js
Associated Issue: #3544
* bump timeout cause parsing can be slow
* clear the caches after each test
* i tried starting and stopping processes and tests went from ~10 seconds to ~40. we might need to do that someday, but i want to avoid it if we can.
> Fix flakiness

- src/actions/pause.js
- src/actions/tests/pause.js
- src/actions/types.js
- src/reducers/pause.js
Associated Issue: #3493
* Added a new command property to the pause reducer
* Added `isStepping` to enable us know when we are stepping
* Do not evaluate expressions when we resume, if we are stepping
> Do not evaluate expressions on stepping

- src/components/Editor/Editor.css
Associated Issue: #3577 
#goodnessSquad
* Aligned the conditional breaking point text color to use the same color as used in the source code section.
Tested the color of the conditional breaking point input color is updated correctly.
Before:
After:
> Use theme body color for conditional breaking point

- src/components/SecondaryPanes/Expressions.js
* Replace React.createElement calls with JSX in Expressions.js
Desk testing of Expressions functionality, as well as continuing to pass the [previous snapshot test](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/tests/__snapshots__/Expressions.js.snap)
> Expressions to JSX

- src/components/SecondaryPanes/Frames/WhyPaused.js
* Replace all React.createElement calls to JSX.
Previous [snapshot test](https://github.com/devtools-html/debugger.html/blob/master/src/components/tests/WhyPaused.js) passes.
> #3506 WhyPaused to JSX

- src/components/shared/Autocomplete.css
Associated Issue: #3547 
* set autocomplete height to 100% so the message centers properly.
> Fix positioning of source search no results message

- assets/panel/debugger.properties
- src/components/Editor/SearchBar.css
- src/components/Editor/SearchBar.js
- src/components/Editor/tests/__snapshots__/SearchBar.js.snap
Associated Issue: #3233
* Add a link that pops up the functions search modal when clicked to the find text UI.
* Press CmdOrCtrl + F to bring up the text search dialog
* Click the "Search functions..." text to bring up the functions search modal
> click "functions" to open symbol search modal

- src/test/mochitest/browser_dbg-breakpoints-reloading.js
Associated Issue: #3336
* start listening before reloads, which helps catch some stray events
> Fix reloading intermittent

- assets/images/Svg.js
Associated Issue: #3596 
We have an embarrassing bug where angular is missing an svg so it throws an error in the panel. This fixes that
> SVG - only throw in development

- src/components/shared/Dropdown.css
Associated Issue: #3625
* Adds overflow:scroll to dropdown element
Before:
After:
> Add overflow:scroll to dropdown element

- bin/run-mochitests-docker
- webpack.config.js
Associated Issue: #3514
We're seeing a webpack warning now that there's nothing to build any more.
> Exclude integration tests in webpack build

- src/components/ProjectSearch/TextSearch.js
- src/components/shared/ManagedTree.js
* fixes issues introduced by
https://github.com/devtools-html/debugger.html/pull/3636
Associated Issue: #3638
Note: There is a flow issue with this PR.  Running `yarn flow` gives this error:
```sh
yarn flow v0.24.6
$ flow
Error: src/components/PrimaryPanes/SourcesTree.js:250
v------------
250:     const tree = ManagedTree({
251:       key: isEmpty ? "empty" : "full",
252:       getParent: item => {
...:
270:     });
-^ function call
38:   props: Props;
^^^^^ property `disabledFocus`. Property not found in. See: src/components/shared/ManagedTree.js:38
v
250:     const tree = ManagedTree({
251:       key: isEmpty ? "empty" : "full",
252:       getParent: item => {
...:
270:     });
^ object literal
Found 1 error
error Command failed with exit code 2.
```
Which i cannot find a good solution …
> fix problems introduced in text search

- docs/local-development.md
Associated Issue: #3506
* remove the "FAQ"-section because it only contains info of why not using JSX. This is no longer true
> remove FAQ about not using JSX

- src/components/Editor/Editor.css
Associated Issue: #3524
* changes the width of `.editor-wrapper`
- Be sure to enable the dark theme in debugger app setttings
- Use `cmd + shift + f` to toggle the text search capabiity
Here, the `splitter` div between the `search-container` and the `secondary panes` were most susceptible to show text between the gap. The best way to examine this is simply to drag the splitter from left to right and check for any text that shows through.
Because of the nature of this issue, any written test(s) have been skipped. Please see before and after shots below:
Before: 
After:
> fixes text showing between panels in dark theme

- docs/updates/README.md
Based on the feedback provided by slack-channel I changed the sort order of the update/readme overview page
> Change Updates Readme sortorder

- src/components/ProjectSearch/TextSearch.css
- src/components/ProjectSearch/TextSearch.js
Associated Issue: #3665 
* Updated CSS in TextSearch.css to set the height of elements to 24px.
* Set the height of parent and grandparent of tree node for scroll on focus
> Fix height of text search result items

- src/components/shared/Accordion.css
Associated Issue: #3720 
* Remove border-bottom from the last child of accordions
Check both the different responsive views of the debugger (horizontal and vertical) and observe that the accordions don't have a trailing border-bottom for the last accordion's content.
> [Photon] Remove border-bottom from the last child of accordions (#3720)

- src/components/stories/ManagedTree.js
Story book managed tree was throwing an error that it couldnt find the dark theme
> fix storybook theme for managed tree

- src/components/Editor/CallSite.js
- src/components/Editor/CallSites.js
Associated Issue: #3296
* Remove using `toSourceLine` because for some reason editor line maps directly to the source line, (same for the columns)
* Allow clicking to remove breakpoints even though alt is not pressed
* Add tests for callsites breakpoints
> fix breakpoints offset issue, Remove breakpoint on click

- src/components/Editor/Tabs.css
Associated Issue: https://github.com/devtools-html/debugger.html/issues/3732
* Added background-color on hover for new-tab button. 
* Changed padding and margin for cleaner look on hover.
> Add hover color to new-tab button

- bin/mochi.js
small convenience so you can run `yarn mochi async-stepping` or `yarn mochi browser_dbg-async-stepping`
> update mochi to make browser_dbg optional

- src/actions/breakpoints.js
- src/actions/tests/breakpoints.spec.js
> [Breakpoints] setting a condition should enable a breakpoint

- assets/panel/debugger.properties
Right-clicking in the source area is currently triggering an error.  Looks like we accidentally mis-named a localization key.
> Fix 'copySource.accesskey' error when right-clicking

- src/components/Editor/CallSites.js
By the book, we're supposed to add `React` to use JSX, so adding it in.
> Add React for CallSites JSX

- src/components/WelcomeBox.css
- src/components/WelcomeBox.js
Associated Issue: #3734
* Two text labels are left-aligned 
* Keys Ctrl+P and Ctrl+Shift+F are bold
> Labels are aligned and keys are bold now

- package.json
this will automatically fix things like incorrectly declared vars, missing semicolons, etc
it will not automatically fix things that are more complex, so eslint might still throw errors that need human intervention. 
Why: this will save everyone frustration from eslint!
filed under codehealth!
> autofix simple eslint errors

- bin/mochi.js
- bin/run-mochitests-docker
Associated Issue: #3660
Mochitests are now be formatted w/ mochi. 
PROs:
* the 40K file you had to download to see you can now skim
* test errors are easier to find
CONs:
* the full run will be saved as an artifact, but not as discoverable
> Mochi exit

- src/actions/breakpoints.js
- src/components/Editor/index.js
Associated Issue: #3801 
I mimic the Chrome behavior:
- add a breakpoint if there is none
- disable or enable breakpoint when Shift+Click on an existing one
> Add breakpoint or toggle enabled state on Shift+Click

- src/utils/editor/source-documents.js
Associated Issue: #3383
* Caches line formatter type, only for wasm source
* Resizes gutter after the change to avoid baby bp
Example test plan as listed at #3383
> Caches line formatter type; resizes gutter after the change.

- src/components/PrimaryPanes/Sources.css
Associated Issue: #3758 
* Changed margin around source view tab from 4px to 0px
> Fix Margin around view-source tab

- bin/intermitents.js
* `bin/intermittent.js` relied on you having Jest installed globally because it was running from `/bin/sh` this makes it so we use the locally installed Jest.
> Modify the path to point to the local Jest installation.

- src/actions/index.js
- src/actions/source-search.js
- src/components/ProjectSearch/SourceSearch.js
- src/components/ProjectSearch/index.js
- src/components/shared/Autocomplete.js
- src/reducers/index.js
- src/reducers/source-search.js
- src/selectors.js
Associated Issue: #3714 
* Added actions and reducer functions to set and clear source-search query string in store.
* Update Autocomplete.js to allow execution of above actions.
- use Command-P to open search panel.
- enter a query string in the search bar.
- resize browser to below responsive breakpoint.
- confirm the query string is preserved.
> Save source-search query in store

- src/actions/navigation.js
- src/utils/parser/index.js
- src/utils/parser/utils/ast.js
- src/utils/parser/worker.js
We were not clearing the AST on navigate. this resulted in a stale ast tree when a source was reloaded and changed.
> clear ast tree on navigate

- src/components/Editor/Tabs.css
- src/components/shared/Button/Close.css
This is just a rough proposal.  My opinion is that the tab hover transitions are slow and appear labored.  The labored feeling is due to speed, so I drastically sped up the transitions and they seem much more quick and elegant.
I know the project has loads of transitions so I guess I'd like to hear some opinions on this faster effect and see if we'd like to speed things up globally.
> Make the source tab hover effects feel more responsive

- src/actions/index.js
- src/actions/sources.js
- src/actions/sources/loadSourceText.js
load source text has been moved into its own file
> refactor loadSourceText

- assets/panel/prefs.js
- src/actions/pause.js
- src/test/mochitest/browser_dbg-async-stepping.js
- src/test/mochitest/examples/doc-async.html
- src/utils/parser/steps.js
- src/utils/parser/tests/fixtures/async.js
- src/utils/parser/tests/steps.spec.js
- src/utils/prefs.js
Associated Issue: #3807 
* adds support for last statement awaits
* adds support for landing in call expressions (helps when stepping out of the async function
* refactors astcommand to do the next step deciding
* uses babel paths internally a lot more see `getSibling` `getFunctionParent`
* turns it on 💚 
* adds some unit tests
> Update async stepping

- src/components/SecondaryPanes/Expressions.css
At present the Expressions list has more padding than likewise child list labels:
Before:
After:
> Make Expression line height equal to likewise labels

- src/components/ProjectSearch/TextSearch.js
- src/components/shared/ManagedTree.js
Associated Issue: #3652
* Adds a focused property to Managedtree
* Focuses on the the first match in first initial result
* Allows you start moving through the matches with more content is coming in
> Fix focus issues

- assets/panel/debugger.properties
Search shows two option:  "Search Sources" and "Find in files".  I find the change in case odd, so changing "sources" to lowercase makes the labels more consistent.
> Make case consistent for search sources

- src/components/shared/Accordion.css
Associated Issue: #3868 
* Changed the padding from 5px to 4px for the accordion header. We need to apply a box-sizing: border-box CSS reset to the whole panel to get the 24px in height that we want. That is being done in issue #3869
> Accordion header should have a height of 24px (#3868)

- src/components/ProjectSearch/ProjectSearch.css
The "search sources" and "find in files" labels are both clickable, yet the inactive item has the default text cursor instead of default.  As they're both clickable, they should have the same cursor.
> Make cursors consistent between search options regardless of status

- src/actions/project-text-search.js
- src/actions/tests/__snapshots__/project-text-search.spec.js.snap
- src/actions/tests/project-text-search.spec.js
- src/components/ProjectSearch/TextSearch.js
- src/components/ProjectSearch/index.js
- src/reducers/project-text-search.js
Associated Issue: #3876
* Change the results from a `Map` to a `List` for order consistensy
* Added new action and reducer to clear search results for every new search
* Added test for `clearSearchResults`
* Remove unused `getTextSearchResult` selector
* There was need for `inputFocused` to be a state property, it was causing unnecessary re-renders
*  Fixed the focused issue. it should now focus on the first match of the first result found by default
- New results get added any where (ordered by the sourceId), so the initially focused item moves
- New results always get added to the bottom (in order of how the results are found), so the focused node is always at the top
> Search results order

- src/components/SecondaryPanes/ChromeScopes.js
In a remote session with @codehag I found that ChromeScopes component throws Error because react is not defined.
> ChromeScopes: import react

- src/reducers/pause.js
Associated Issue: #3731 
@codehag was right: listening on the "Navigate" action fixed it.
> Set debuggeeUrl on navigate

- assets/panel/debugger.properties
- src/components/Editor/Footer.js
Spotted this, thought it would be best to move to l10n.
> Move code coverage button title to l10n

- src/actions/sources.js
- src/actions/tests/ui.spec.js
- src/actions/ui.js
- src/components/App.js
- src/components/Editor/SearchBar.js
- src/components/Editor/Tabs.js
- src/components/Editor/index.js
- src/components/PrimaryPanes/index.js
- src/components/ProjectSearch/SourceSearch.js
- src/components/ProjectSearch/TextSearch.js
- src/components/ProjectSearch/index.js
- src/components/SymbolModal.js
- src/reducers/ui.js
- src/test/mochitest/browser_dbg-console.js
- src/test/mochitest/browser_dbg-search-file.js
- src/test/mochitest/browser_dbg-search-project.js
- src/test/mochitest/browser_dbg-search-sources.js
- src/test/mochitest/browser_dbg-search-symbols.js
- src/test/mochitest/browser_dbg-sources.js
- src/test/mochitest/head.js
- src/utils/prefs.js
While looking into why the project search test would time out I found that we had some funky escape handling. It turned out that Symbol Modal never un-mounted, which meant that it was always handling escape keys.
* the symbol modal is now conditionally rendered
* Escape handling is now in App.js
* some custom handling has been moved to clearActiveSearch 
* project and text search are a bit cleaner now too
> Fix project search test

- src/components/PrimaryPanes/Outline.js
- src/components/tests/__snapshots__/Outline.spec.js.snap
I enjoy a function list but I find that list not very helpful without knowing also knowing the parameter names.
This requires a test fix but I wanted to take the temperature on adding paramaters to the outline panel.  I much prefer it.
> Show parameter signature within outline

- src/components/Editor/EditorMenu.js
There's no reason not to show the full context menu for blackboxed sources.  We still want to copy, get the URL, etc.
> Show full editor context menu for blackboxed tab

- src/components/Editor/Tabs.js
Associated Issue: #3910
* Use the `selectSource` instead as it moves the tab to the first spot and also selects the source.
1. Launch Firefox.
2. Access the https://devtools-html.github.io/debugger-examples/examples/todomvc/ webpage.
3. Open multiple files from the source list pane.
4. Open the list view dropdown.
5. Select a file from the dropdown.
[Expected result]:
The selected file is focused and it's code is displayed in the Source pane.
[Actual result]:
The selected file is not focused and the code from the previously selected file is displayed in the source pane.
> fix hidden tabs click not showing the source

- src/components/WelcomeBox.css
Associated Issue: #3917 
* .welcomebox should use --theme-body-background for its background-color.
> Welcome box should have a --theme-body-background (#3917)

- src/components/SecondaryPanes/Expressions.css
Associated Issue: #3939 
* Remove unused CSS rules in Expressions.css
* Search for each CSS class name and see no results show up
> Remove unused CSS rules in Expressions.css

- src/components/ProjectSearch/TextSearch.js
Associated Issue: #3926
* Remove auto-focus on search results
* Now the focus remains in the search input box until the user tabs to move the the result list
> remove auto-focus on the search results

- src/utils/editor/expression.js
Associated Issue: #3824
* Add =, <, >, +, -, *, / tokens as invalid tokens when doing `updatePreview`
1. Visit any website with codes using =, <, >, +, -, *, / tokens
2. Pause on lines having the above invalid tokens
3. Hover mouse over the above invalid tokens and make sure no preview for them triggered
Please see [1] for the screenshots gif
[1] https://github.com/devtools-html/debugger.html/issues/3824#issuecomment-328278484
> 3824 - ignore =, <, >, +, -, *, / tokens

- assets/panel/debugger.properties
- src/components/ProjectSearch/TextSearch.css
- src/components/ProjectSearch/TextSearch.js
- src/components/ProjectSearch/tests/TextSearch.js
- src/components/ProjectSearch/tests/__snapshots__/TextSearch.js.snap
Associated Issue: #3924 
* Added 'No-Results' state in ProjectSearch - Search in File
* Added TextSearch unit-test - snapshot file checked in
> [ProjectSearch][3924] - Add 'No Results' state in ProjectSearch - Search in File

- assets/panel/debugger.properties
I have an issue open for case auditing but as we move closer to 57 I wanted to get this in.
Firefox itself uses uppercase labels so, for the sake of consistency, I'm going with that.
> Update label case for tab and editor context menus

- src/components/Editor/Tabs.css
- src/components/PrimaryPanes/Outline.css
- src/components/PrimaryPanes/Sources.css
- src/components/SecondaryPanes/Breakpoints.css
- src/components/SecondaryPanes/Frames/Group.css
- src/components/SecondaryPanes/Frames/WhyPaused.css
- src/components/SecondaryPanes/SecondaryPanes.css
- src/components/shared/Accordion.css
Associated Issue: #3872
change cursor style to default in following locations:
* source tab
* accordion (and inside items)
* source footer
* outline
We searched the app for places with wrong cursor (input cursor) and verified the cursor is now default one (simple arrow)
> change cursor

- src/components/ProjectSearch/ProjectSearch.css
There doesn't appear to be a reason to allow the overall search container to scroll.  Now only one scrollbar is shown when scrolling via mouse or moving via keyboard.
> Fix #4002 - Prevent duel scrollbars in project search

- src/components/ProjectSearch/SourceSearch.js
- src/utils/source.js
- src/utils/tests/source.spec.js
Associated Issue: #3987 
* adds a new 3rd party function
* excludes 3rd party files from source search
Should we add an option to see 3rd party files it back?  Perhaps, but i think it's less important given there's a source tree.
Is this faster? Oh man, it's now blazing fast!
unit tests
> add source search filtering

- assets/panel/debugger.properties
- src/components/Editor/EditorMenu.js
- src/components/Editor/index.js
- src/utils/breakpoint/astBreakpointLocation.js
- src/utils/function.js
- src/utils/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/utils/parser/tests/fixtures/func.js
- src/utils/tests/__snapshots__/function.spec.js.snap
- src/utils/tests/function.spec.js
Small fun feature for copying a function.
unit tests
> Copy function

- src/components/ProjectSearch/TextSearch.css
Associated Issue: #3651
An attempt at making the ProjectSearch Look and Feel UI look like Atom's Search UI 
* changed the text color on  a focused result
* changed the text color for the line number of a focused result
* changed the margin for focused item to align it to the file path
* changed the text color for the file path of a search result
Opened the debugger and chose a project to debug
> [WIP] Stealing Atom look and feel for the Search UI

- flow-typed/debugger-html.js
- package.json
- src/actions/navigation.js
- src/actions/sources.js
- src/actions/tests/__snapshots__/breakpoints.spec.js.snap
- src/utils/parser/getScopes.js
- src/utils/parser/index.js
- src/utils/parser/worker.js
- yarn.lock
Associated Issue: #3817 
* allows to send source text independent from parsing of the scopes
* parsing scopes to extract positions and its scope of every symbol in the source code
> Parse to extract all scopes and bindings.

- src/components/Editor/Tabs.css
Fixes a photon css bug w/ tabs
> Fixup Tab CSS

- src/actions/project-text-search.js
- src/actions/sources.js
- src/actions/sources/loadSourceText.js
- src/actions/tests/__snapshots__/project-text-search.spec.js.snap
- src/actions/tests/project-text-search.spec.js
- src/components/Editor/tests/Editor.spec.js
- src/components/Editor/tests/__snapshots__/Editor.spec.js.snap
- src/utils/source.js
The initial project search fails after loading one source. This is because of some edge cases w/ how we switch source loaded state. This should fix that by updating the loaded state field and also adding some other necessary fields. 
It also adds 3rd party filtering so we only search first party code.
STR:
1. get perf.html
2. open, cmd+shift+f
3. search for `this`
you'll see: failed to get name from undefined
unit tests
> [ProjectSearch] Fix initial search

- src/components/App.js
- src/components/PrimaryPanes/Outline.js
- src/components/ProjectSearch/index.js
- src/components/SecondaryPanes/Scopes.js
- src/components/SecondaryPanes/Workers.js
- src/components/SecondaryPanes/index.js
> Fix linting warnings

- assets/panel/prefs.js
- docs/local-development.md
- src/utils/prefs.js
This removes the devtools.debugger.client-source-maps-enabled pref, in
favor of the pref that will be used across all tools.
I've copied over the relevant from devtools.js; the next time the
debugger lands, we will want to remove that definition from M-C.
I'll handle other aspects of the unification in M-C; namely, updating
the options panel.
> Remove devtools.debugger.client-source-maps-enabled pref

- src/actions/sources.js
- src/actions/tests/sources.spec.js
Associated Issue: #3899 
Extension evals all have the same source actor id. This causes the debugger to try to add the same source every time react devtools evals (once a second). 
We should bail early when we see the same source again, because the server treats it as the same source.
Lets not land this until we have tests for this behavior
> Ignore new identical sources

- wallaby.conf.js
* add a wallaby.conf.js file to the project (credit for the config goes to @ArtemGovorov over at https://github.com/wallabyjs/public/issues/1255)
I've been using Wallaby as a testing tool lately. I had put this in my local ignore (`.git/info/exclude`) but after showing @jasonLaster he suggested adding it so others can use Wallaby if they choose to and won't need to figure out how to configure it themselves.
> Add a wallaby config to the project.

- assets/panel/prefs.js
Julian pointed out that prefs.js is only used in the panel, so we don't
need to define the shared pref here.
Also, we need to temporarily leave the old pref in place until
https://bugzilla.mozilla.org/show_bug.cgi?id=1371849 lands, to avoid
errors from the options pane.
> Tweak source-map prefs in prefs.js

- src/components/SecondaryPanes/Expressions.css
This prevents scrollbars on expression items all together.  Coupled with an ellipsis (https://github.com/devtools-html/debugger.html/issues/3901), this will look great!
> Fix #4046 - Prevent scrollbars for watch expression items

- .travis.yml
- bin/ci/build-firefox.sh
- bin/ci/clone-gecko.sh
- bin/ci/run-tests.sh
Associated Issue #3986 
This switches our mochitests to travis.
**advantages**
* tests run in parallel 
* we don't use docker
* mc is up to date
> add travis

- src/components/Editor/Editor.css
Fixes the issue mentioned in #4074.
> Fix 4074 - Align tabs to the bottom of the editor header

- src/actions/expressions.js
- src/actions/pause.js
- src/actions/sources.js
- src/actions/tests/pause.spec.js
- src/reducers/pause.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-expressions-error.js
- src/test/tests-framework.js
- src/test/utils/history.js
- src/types.js
- src/utils/redux/middleware/history.js
- src/utils/test-head.js
- yarn.lock
Associated Issue: #3597
* stops evaluating when we're paused at an expression that threw
* bails early when `resumed` is called but we're not paused. This prevents unnecessary evals when a bp is added.
* a mochitest that shows that watch expressions still work when we we're paused due to an exception in an expression.
> Pausing due to an errored watch expression

- src/components/PrimaryPanes/Sources.css
- src/components/PrimaryPanes/index.js
Putting this in quick to see how people like it.
> Fix #4031 - Move source and outline tabs to the top of the left pane

- src/actions/tests/__snapshots__/ast.spec.js.snap
- src/utils/parser/getSymbols.js
- src/utils/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/utils/parser/tests/fixtures/component.js
- src/utils/parser/tests/getSymbols.spec.js
Associated Issue: #4021
- parsing function symbols now includes the name of the closest ancestor class, or `null` if there is no containing class
- can be used like this:
```diff
diff --git a/src/components/PrimaryPanes/Outline.js b/src/components/PrimaryPanes/Outline.js
index 5c0fac6..97359e6 100644
--- a/src/components/PrimaryPanes/Outline.js
+++ b/src/components/PrimaryPanes/Outline.js
@@ -45,7 +45,7 @@ export class Outline extends Component {
}
renderFunction(func: SymbolDeclaration) {
-    const { name, location, parameterNames } = func;
+    const { name, location, parameterNames, klass } = func;
return (
<li
@@ -54,6 +54,8 @@ export class Outline extends Component {
onClick={() => this.selectItem(location)}
>
<PreviewFunction func={{ name, parameterNames }} />
+        {" - "}
+ …
```
> Parse the closest class for functions and properties

- src/components/Editor/EditorMenu.js
> Group the copy items in the edit context menu

- src/components/shared/ManagedTree.js
* move the expanded state set up to `componentWillMount`
* Fix the react warning
> stop setting state in componentDidMount

- src/components/Editor/SearchBar.js
- src/components/SecondaryPanes/ChromeScopes.js
hi! first PR, hoping to help :) 
Associated Issue: [#2804](https://github.com/devtools-html/debugger.html/issues/2804)
Changed PropTypes to Flow Props
> Switch SearchBar and ChromeScopes Proptypes to flow props

- src/actions/expressions.js
- src/utils/expressions.js
- src/utils/tests/__snapshots__/expressions.spec.js.snap
- src/utils/tests/expressions.spec.js
Associated Issue: #4106
* wraps expressions in a try/catch
unit tests
> Make watch expressions safe

- assets/panel/debugger.properties
- src/client/firefox/create.js
- src/utils/scopes.js
Associated Issue: #3974 
* Simplify the display name
* Added Localization for `(anonymous)`
I used Jason's test example https://cray-scopes.glitch.me/
In this example `stuff/Foo<` has been changed to `Foo`.
> Simplify scope display names

- src/components/App.css
- src/components/shared/Button/PaneToggle.css
- src/components/shared/Button/PaneToggle.js
Associated Issue: #4073
* Buttons were made reachable with the keyboard 
* hover/focus styling were added to buttons
* Buttons are made actionable with the keyboard - return/Space collapses/expands panes
> Accessible collapse pane buttons

- src/components/Editor/Footer.js
- src/utils/pretty-print/index.js
- src/utils/source.js
- src/utils/tests/source.spec.js
Associated Issue: #2782
* pass source object to `isJavaScript` function instead 
* remove uneccessary shouldPrettyPrint check
* add tests
> fix issue where minified files without js extns do get detected

- src/components/PrimaryPanes/Sources.css
- src/components/PrimaryPanes/index.js
Associated Issue: #4110
* Remove the tab header search shortcut
> Remove tab header search shortcut

- src/utils/sources-tree/getURL.js
Associated Issue: #4138
* Display 'Webpack' (project name) as Sources node title, instead of the protocol
> Display 'Webpack' (project name) as Sources node

- src/utils/sources-tree/index.js
- src/utils/sources-tree/tests/utils.spec.js
- src/utils/sources-tree/utils.js
Associated Issue: #4137
* Files with extensions .css, .png and .svg are filtered out from the Sources file tree.
> Filter out all .css, .png and .svg files from showing up in Sources tree

- src/components/shared/Button/Close.js
* Change shared/Button/Close from PropTypes to Flow Props
> Switch Close Button from PropType to Flow Props

- src/actions/tests/pending-breakpoints.spec.js
- src/reducers/pending-breakpoints.js
Associated Issue: #4055 
* adopted pending_breakpoint reducer to not handle adding or removing hidden breakpoints
* added a test, but was not able to run it on my machine
> Don't persist pending breakpoints if hidden

- src/components/Editor/EditorMenu.js
- src/components/Editor/index.js
- src/test/mochitest/browser_dbg-breakpoints-cond.js
- src/utils/editor/index.js
Associated Issue: #4062 
* Created mouse click event listener for codeMirror
* Created onClick(e: MouseEvent) function shortcut to jump to source location
> Shortcut to jump to mapped location

- assets/panel/debugger.properties
- src/actions/ui.js
- src/components/SecondaryPanes/Breakpoints.js
It was ways faster to add my changes on top of master than merging the existing ones. Especially all the debugger.properties changes were hard to track...
So closing https://github.com/devtools-html/debugger.html/pull/4094 in favor of this
> Adding "Add condition" to breakpoints context menu

- src/components/PrimaryPanes/Outline.js
- src/components/PrimaryPanes/Sources.css
- src/components/PrimaryPanes/SourcesTree.js
- src/components/PrimaryPanes/index.js
Associated Issue: NONE
While fiddling around I found that the "No sources" hint gets displayed even when the sources panel is hidden.
STR:
- Open debuggee with "about:blank"
- Switch from sources panel to outline
Before:
After:
> Don't show "No sources" hint if sources panel is hidden

- flow-typed/debugger-html.js
- package.json
- src/actions/ast.js
- src/actions/pause.js
- src/actions/tests/expressions.spec.js
- src/client/chrome/create.js
- src/client/firefox/create.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-minified.js
- src/test/mochitest/examples/doc-minified2.html
- src/test/mochitest/examples/sum/sum.js
- src/test/mochitest/examples/sum/sum.min.js
- src/test/mochitest/examples/sum/sum.min.js.map
- src/utils/pause.js
- src/utils/scopes.js
- yarn.lock
Associated Issue: #3427
* adds the `generatedLocation` to a frame
* adds building of scopes database for the generated source
* updates/adds original mapped names to the scopes
The top scope needs to have `current`, `buffer` variables shown.
<del>P.S. needs some modification to the devtools-source-map</del>
> Show mapped names in scopes bindings

- src/client/firefox/commands.js
Associated Issue: #3715
the jumping comes from trying to remove a breakpoint when the client does not have it registered yet.
held cmd+b down for 3 minutes. Created literally thousands of breakpoints at the same line
> Fix breakpoint jumping

- package.json
- src/components/Editor/EditorMenu.js
- src/components/Editor/index.js
- src/utils/editor/index.js
- src/utils/sources-tree/tests/utils.spec.js
- src/utils/sources-tree/utils.js
- yarn.lock
So I just got my 2 year Mozilla laptop refresh and I can't lint with debugger.html "out of the box" because I'm missing `eslint-plugin-mozilla`.
This PR could be totally wrong somehow, or we've all had moz-central, and we've taken advantage of having stuff installed already.
> Fix ESLint Dependencies from Fresh Install

- src/components/SecondaryPanes/Breakpoints.css
- src/components/SecondaryPanes/Breakpoints.js
- src/components/SecondaryPanes/Expressions.css
- src/components/SecondaryPanes/SecondaryPanes.css
Associated Issue: #4044 
* Handle the overflow case for watch expressions
* Make clicking on label text toggle corresponding checkbox as well
* Adjust the vertical align between label text and checkbox
* Make label text become the ellipsis style when script filename is too long.
- In Chrome, for a too long script filename, it would have the ellipsis style  
- But currently, in Firefox debugger page, a long filename would push away the close button out of view and cause a broken payout.
* The solution in action
- Screenshot 1
- Screenshot 2
> Small style improvements on breakpoint and watch expression

- src/components/SecondaryPanes/CommandBar.css
- src/components/SecondaryPanes/index.js
Associated Issue: #4032
* Removed inline styles for Split-Box
* Removed `command-box.vertical` style
Before:
After:
> Scroll bar is not ignored in vertical mode calculations

- src/components/PrimaryPanes/Sources.css
> Fix source tabs not lining up with file tabs

- src/components/Editor/index.js
- src/utils/editor/source-documents.js
Associated Issue: #3988
This fixes a big problem of codemirror touches by memoizing loading:
* [before](https://perfht.ml/2k9wYBf)
* [after](https://perfht.ml/2k9dD3h)
Here is the time spent in `setText`, before the change it was about 22s after the fix it was about 1s.
> Memoize loading

- src/components/Editor/Preview/Popup.js
- src/utils/editor/expression.js
Associated Issue: #3966 
* Numbers and string < 10 letters moved to tooltip
* Removed mouseover events from value assignments in strings, numbers, and "atom" items (null)
> Issue #3966: Show small values inside tooltip

- src/components/WelcomeBox.css
- src/components/WelcomeBox.js
Associated Issue: #3999
* Changed WelcomeBox divs in order to look better on responsive
> Fix responsive issue on WelcomeBox

- src/components/PrimaryPanes/SourcesTree.js
looks like we lost this in the shuffle during the ucosp wknd
> Fix webpack icon matching

- src/actions/expressions.js
- src/actions/pause.js
- src/reducers/pause.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-expressions-error.js
- src/test/mochitest/head.js
- src/utils/expressions.js
- src/utils/function.js
- src/utils/indentation.js
- src/utils/redux/middleware/log.js
- src/utils/tests/__snapshots__/expressions.spec.js.snap
- src/utils/tests/__snapshots__/indentation.spec.js.snap
- src/utils/tests/indentation.spec.js
Associated Issue: #4220, #4223, ...
* the `eval` was unnecessary and made us susceptible to `eval` monkey patches
* our old approach of ignoring re-evaluating when pausing and resuming did help protect the server. It turns out that if you have "pause on all exceptions" you will naively re-evaluate when you're pausing in and resuming from an expression that threw. We should catch both cases...
STR:
1. set POE to all (blue)
2. add `foo.bar` *(you should only pause once)*
3. add `foo.bat` *(you should only pause once)*
4. add `3` *(you should see the result)*
Yeah... we'll write some unit tests :)
And bring back the mochitest
> Fix some lingering POE + Exception bugs

- src/components/ShortcutsModal.css
- src/components/shared/Modal.css
Associated Issue: #4122
The shortcuts modal was super long in Firefox because of `height: fit-content` => use `display: table` instead
In Firefox before:
In Firefox after:
> firefox doesn't like fit-content

- src/actions/pause.js
- src/test/mochitest/browser.ini
Associated Issue: wasm source maps
See doc-wasm-sourcemaps.html mochitest
> Disables updateScopeBindings for wasm source maps.

- src/components/Editor/Tabs.js
- src/utils/source.js
- src/utils/tests/source.spec.js
Associated Issue: #4203 
The source tab tooltip now shows the full file url instead of just the file name.
- Open the debugger panel
- Open an example source file
- Tab titles should be the file name
- Hover over the tab - the tooltip should be the file url
> Show the full url of a file in the source tab tooltip (#4203)

- src/components/shared/Svg.css
No associated issue.
* Changed the vertical alignment on the webpack icon from `bottom` to `sub`.
Tested on both Firefox and Chrome.
> Fixed Webpack Alignment

- src/components/WelcomeBox.js
`.shortcutKey` sets `display: inline-block` so we can use a `span` here without issue.
> Fix 4246 - Prevent validateDOMNesting warning

- package.json
- src/components/Editor/tests/__snapshots__/Breakpoints.spec.js.snap
- src/components/Editor/tests/__snapshots__/Editor.spec.js.snap
- yarn.lock
Resolves many of the console warnings when running tests.
Per Enzyme's documentation for v15.5 and up, react-test-renderer should be included instead of the old test utils. See https://github.com/airbnb/enzyme/pull/876.
There are still some warnings about using `React.PropTypes` that I haven't tracked down yet, and they may be coming from dependencies. Additionally, there are some for using `React.createClass` that will take some more code changes to fix.
Associated Issue: #4221 
* Removed `react-addons-test-utils`
* Added `react-test-renderer`
Ran the tests, all of which are green.
> Fix some react test warnings

- src/components/Editor/tests/Breakpoints.spec.js
- src/components/Editor/tests/DebugLine.js
- src/components/Editor/tests/Editor.spec.js
- src/components/Editor/tests/SearchBar.spec.js
- src/components/ProjectSearch/tests/TextSearch.js
- src/components/SecondaryPanes/Frames/Group.js
- src/components/SecondaryPanes/Frames/index.js
- src/components/SecondaryPanes/Frames/tests/Frame.js
- src/components/SecondaryPanes/Frames/tests/Frames.js
- src/components/SecondaryPanes/Frames/tests/Group.js
- src/components/SecondaryPanes/tests/Expressions.spec.js
- src/components/tests/Outline.spec.js
- src/components/tests/closeButton.spec.js
- src/components/tests/resultList.spec.js
Per [React's top-level API documentation](https://reactjs.org/docs/react-api.html#createfactory), using `createFactory` isn't really intended for a project to use if it's using JSX. Also, more developers will be familiar with using JSX.
For these reasons, this PR removes most instances of `createFactory` and replaces them with JSX.
Whereas before there would be something like:
```js
const Component = createFactory(_Component)
const rendered = new Component({some: "prop"});
```
Now there will be:
```jsx
const rendered = <Component some="prop" />
```
The `ManagedTree` component still uses `createFactory`. Changing that over revealed some prop-type failures, and will take some more digging to resolve.
Let me know if there's some good reasons for staying with `createFactory` instead of just …
> Remove usage of create factory

- src/components/shared/ManagedTree.js
Removes dangling propTypes definition for the ManagedTree component, since it already uses Flow's props.
> Migrate ManagedTree proptypes to flow

- src/components/SecondaryPanes/Breakpoints.css
- src/components/SecondaryPanes/Breakpoints.js
Associated Issue: #4262
* Stops the click on a breakpoint from toggling it as well
* Preserves the more semantic `<label>` and `<input>` tag pattern introduced [here](https://github.com/devtools-html/debugger.html/pull/4057), without breaking the click
* Centers the label text correctly (compare to bottom alignment [here](http://g.recordit.co/6gGbbS07dG.gif))
Clicking in the debugger
> Stop breakpoint label click from toggling breakpoint

- src/components/Editor/tests/Breakpoints.spec.js
- src/components/Editor/tests/SearchBar.spec.js
Follow up to #4260. This PR extracts some temp variables in a couple of the tests.
> Extract temp variables for wrapped components in their tests

- src/components/PrimaryPanes/SourcesTree.js
- src/utils/sources-tree/addToTree.js
- src/utils/sources-tree/createTree.js
- src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap
- src/utils/sources-tree/tests/addToTree.spec.js
- src/utils/sources-tree/tests/collapseTree.spec.js
- src/utils/sources-tree/tests/sortTree.spec.js
- src/utils/sources-tree/tests/utils.spec.js
- src/utils/sources-tree/treeOrder.js
Associated Issue: #4168
* don't use sortTree  for sources
* improve the performance of addToTree
Added console.time() in the SourcesTree.js and createTree.js around addToTree+sortTree operations.
Measured performance of https://yurydelendik.github.io/old-man-sandbox/create-30k/f3k.html tree.
Before:
After:
Performance improved from 1186ms->291ms also affected subsequent/incremental tree update operations 180ms->2ms.
> Optimize addToTree function.

- src/components/Editor/Preview/index.js
I noticed this when searching for lodash usage.  Only one that's different.
> Fix one case of different lodash import format

- assets/panel/debugger.properties
- src/components/SecondaryPanes/UtilsBar.js
"shortcuts" doesn't mean much and doesn't follow the "Uppercase lower lower" pattern used elsewhere.
> Make keyboard shortcuts button more specific and localized

- src/components/PrimaryPanes/Sources.css
- src/components/PrimaryPanes/SourcesTree.js
Associated Issue: #4168
I cannot properly measure, but for 3k files win is about 10%-20% (e.g. 2500ms->2000ms) during forceUpdate() of the SourceTree.
> Removes unneeded SVG DOM elements for source tree arrows.

- src/workers/parser/steps.js
- src/workers/parser/tests/fixtures/async.js
- src/workers/parser/tests/fixtures/generators.js
- src/workers/parser/tests/steps.spec.js
- src/workers/parser/utils/helpers.js
Associated Issue: #4232
* Added step over functionality for `yield`
Opened with @longitude @mjfrancoeur.
> Added step over functionality for yield (#4232)

- .babelrc
- package.json
- src/components/Editor/index.js
Associated Issue: #3172
Using https://babeljs.io/docs/plugins/transform-class-properties/ to use class properies instead of giant ```self.<fn> = <fn>.bind(this); ... ``` blocks
Also in the es class field proposal https://github.com/tc39/proposal-class-fields
> Proposal for closing #3172

- docs/debugging-the-debugger.md
debugging-the-debugger.md included a couple of misleading, outdated
diffs that didn't reflect the current state of the world.
I updated the diffs to work against the current HEAD. 
This might not be the optimal place to put the pause examples but it's [where I ended up when trying to go through the document myself.](https://gist.github.com/jfo/a005b89d926bdd46fec5901a14055f6f)
[Here](https://gist.githubusercontent.com/jfo/ae3c69c43069242cd3ca0f96eeec4d8a/raw/8a4e4f6917a44d501bd03e914900f77d9d32ee66/foo.diff) is a diff which can be applied to current master and which illustrates the proposed diffs for the doc. Debugging the debugger and diffing diffs for doc diffs too 😮
> Updating docs

- src/components/Editor/CallSite.js
- src/components/Editor/SearchBar.js
- src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
- src/components/SecondaryPanes/Frames/Group.js
- src/components/SymbolModal.js
- src/components/shared/Accordion.js
- src/components/shared/ManagedTree.js
- src/components/shared/Modal.js
Associated Issue: #4299
Changed the following components to have functions as class properties instead of using bind:
CallSite.js
SearchBar.js
Frame.js
Group.js
Accordion.js
ManagedTree.js
Modal.js
SymbolModal.js
`yarn prepush`
> Change component function binding to class properties

- assets/panel/debugger.properties
- src/components/Editor/Tabs.js
Associated Issue: #4325 
* removed sourceTabs.copyLink and all its occurrences
* substituted copySourceUri2 instead
Launched yarn and compared the right-click response in both windows 
http://g.recordit.co/KTpdMyLWck.gif
> - unifies right click "Copy source URI" for tree view & tab view (#4325)

- src/client/firefox.js
Add's a guard statement to protect against unsafe `listWorker` calls
> Protect Worker and Browser Content Toolboxes

- src/components/PrimaryPanes/SourcesTree.js
* Replace React Prop Types with flow typechecking
* Organize Imports
`yarn test`
> Use Flow for Proptype checking in Source Tree

- src/components/PrimaryPanes/Sources.css
Associated Issue: #4185 
* Changed Empty message styling.
* As indicated by @gabrielluong I changed empty message of Sources tab as that of Outline tab.
> Align empty message in Source Tab

- assets/panel/prefs.js
devtools.debugger.client-source-maps-enabled is no longer needed, and so
this removes the definition of it.
> Remove last vestige of devtools.debugger.client-source-maps-enabled

- src/components/ShortcutsModal.css
Set media query @640px or smaller to respect the containers width.
Associated Issue: #4291
* Made shortcuts section responsive to narrow widths
> Fixed issue #4291

- src/components/PrimaryPanes/SourcesTree.js
- src/components/shared/ManagedTree.js
Associated Issue: #4061
Expand/Collapse all nodes in the source tree when doing alt click on the tree item(folder)
> Make alt click expand/collapse all the nodes

- src/components/Editor/CallSites.js
- src/components/PrimaryPanes/Outline.js
Associated Issue: #4343
Replaced all usage of lodash's `find` with `Array::find`.
> Replace lodash find with native Array::find. Fixes #4343.

- assets/panel/debugger.properties
- src/components/App.js
- src/components/GotoLineModal.js
- src/reducers/ui.js
Associated Issue: #4210 
This commit adds a gotoline modal/functionality triggered with `:` in
the main debugger source window.
This is not ready to merge but it is ready for feedback. I've commented on the diff with some things! Also needs tests, would like some guidance on that via [SymbolModal.spec.js](https://github.com/devtools-html/debugger.html/blob/master/src/components/tests/SymbolModal.spec.js), I assume.
> add a GotoLineModal

- bin/diff.js
- package.json
- yarn.lock
Associated Issue: NONE
The goal of this PR is to create an improved maintainer experience that works cross-platform.
I'll move this & other scripts into a standalone package so this can be easily used by others too.
* `yarn diff` creates a git diff, adds formating for Github markdown and copies it to clipboard
> (WIP) Improve maintainer experience

- src/client/firefox.js
- src/utils/sources-tree/treeOrder.js
related issue: #4346 
There was an issue with debuggerUrl not being defined in the browser toolbox context and listWorkers being present but not a function on the threadClient._parent
both need more investigation, this is just to get the browser toolbox working again.
> fix browser toolbox issues

- src/components/ShortcutsModal.css
- src/components/shared/Modal.css
* modal max-height changed to 40vh to make it scrollable when there are too many items to fit vertically
* Jason asked to put the modal at the top so we did it!
> modal height and position changed

- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-wasm-sourcemaps.js
Associated Issue: Failure at https://bugzilla.mozilla.org/show_bug.cgi?id=1406551#c5
> Attempt to address "Debugger.Frame is not live".

- assets/panel/debugger.properties
- src/components/Editor/Tabs.js
Associated Issue: #4312
Removed:
* import of formatKeyShortcut
* onclick
* render newButton method
* property sourceTabs.newTabButtonTooltip
Kept:
* SVG plus icon
Within Firefox debugger tab
> Removed tabs + button

- src/components/App.js
Associated Issue: #4288 
* Added the shortcuts modal logic to the vertical mode component.
> add shortcuts modal in vertical mode (#4288)

- src/components/Editor/Editor.css
IMO a monospaced font for the editor looks better:
Before:
After:
> Use a monospace font for editor line numbers

- src/actions/ui.js
- src/components/App.js
- src/reducers/types.js
- src/reducers/ui.js
- src/test/mochitest/head.js
It would be nice to move the horizontal state to the UI reducer as an "orientation" field. The benefit is this:
1. persistence
2. other components can hook in fetch state/set it
3. tests are easier here
> Move "horizontal" state to Redux

- src/components/Editor/Editor.css
So it turns out that this is simply a dev environment problem -- Nightly currently shows monospaced line numbers and code.  
We should, however, find a way to include the common.css file so that we see monospaced code in dev.
> Revert "Use a monospace font for editor line numbers"

- src/utils/expressions.js
- src/utils/tests/__snapshots__/expressions.spec.js.snap
- src/utils/tests/expressions.spec.js
@bomsy and i found that "3" watch expressions were showing a syntax error. The problem was how we escaped the watch expression: 
this is what we want:
```
"try {
\\"2\\"
} catch (e) {
e
}"
```
unit tests
> Fix "3" expressions

- configs/development.json
* Change port 9000 to 8112 to fix "Port in use" errors that sometimes occur
* Changed port, everything proceeding to function properly
N/A
> Change port 9000 default to 8116 default

- src/components/Editor/index.js
* As a follow-up to #4143
* Fixes an issue where the `line` being `0` returns a falsy, causing the not to highlight for single line minifed files
* Use `loadedState` to check if the text has fully loaded
> fix bug where the line being 0 returns a falsy

- assets/panel/debugger.properties
Associated Issue: #4378
* Reverts editor.addConditionalBreakpoint string changes
> Undo string change to editor.addConditionalBreakpoint

- src/actions/tests/__snapshots__/ast.spec.js.snap
- src/workers/parser/frameworks.js
- src/workers/parser/getSymbols.js
- src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/workers/parser/tests/fixtures/frameworks/component.js
- src/workers/parser/tests/framework.spec.js
- src/workers/parser/tests/getSymbols.spec.js
Associated Issue: #4151
This is the first step towards getting React icons displaying for their appropriate tab in the debugger.
* AST grabs imports and classes
* Framework check for React Component
* Added test for React Component
> Add Classes and Imports to the AST

- assets/images/Svg.js
- assets/images/aframe.svg
- src/utils/frame.js
> support framework frames for Aframe #2980

- src/components/shared/SearchInput.js
- src/workers/parser/tests/scopes.spec.js
Converted remaining vars to const to fix warnings in tests
> Fix warnings for var usage

- .flowconfig
- package.json
- src/workers/parser/tests/getSymbols.spec.js
- yarn.lock
Adds support for cases aka data providers, via the `jest-in-case` package. Note our tests don't change at all
> Add Jest Cases

- docs/debugging-the-debugger.md
- docs/getting-setup.md
Associated Issue: #4455 
* Fixed Link issues in [getting setup](http://firefox-dev.tools/debugger.html/docs/getting-setup.html) page. Corrected Link [here](http://pradeepgangwar.tech/debugger.html/docs/getting-setup.html)
* Fixed Link issues in [debugging the debugger](http://firefox-dev.tools/debugger.html/docs/debugging-the-debugger.html) page. Corrected Link [here](http://pradeepgangwar.tech/debugger.html/docs/debugging-the-debugger.html)
> Fix link issues in docs 

- src/components/Editor/Tabs.css
- src/components/Editor/index.js
- src/components/shared/Button/PaneToggle.css
- src/utils/editor/source-documents.js
- src/utils/ui.js
Associated Issue: #3846 
* Pane toggle button padding changed to make it wider
* Margin left removed from first tab
> Fixes 3846 Source Tabs and Gutter Column Don't Line Up

- src/actions/pause.js
Associated Issue: #4471
*  Expand the right sidebar on pausing at breakpoint
> fix #4471 - expand the right sidebar on pausing at breakpoint

- src/components/PrimaryPanes/Sources.css
- src/components/PrimaryPanes/SourcesTree.js
- src/components/shared/Svg.css
Associated Issue: #4350 
Converted the Source Tree SVG's to images using CSS styles.  This also includes the newly added Blackbox SVG.
> Converted Source Tree SVG's (including Blackbox) to images using CSS styles (#4350)

- src/actions/ast.js
- src/utils/ast.js
- src/utils/tests/__snapshots__/ast.spec.js.snap
- src/utils/tests/ast.spec.js
- src/workers/parser/getSymbols.js
- src/workers/parser/tests/fixtures/computed-props.js
- yarn.lock
Associated Issue: #4020
* Add the computed property to the member expression objects returned from getSymbols
* Differentiate computed from un-computed memberexpressions
> Differentiate between computed and uncomputed member expressions

- src/components/Editor/EditorMenu.js
Associated Issue: #4394 
I also checked the other occurences of  `coordsChar` but they are ok.
> Fix "Copy function"

- docs/mochitests.md
- src/components/PrimaryPanes/Sources.css
- src/components/QuickOpenModal.js
- src/test/mochitest/browser_dbg-breaking.js
- src/test/mochitest/browser_dbg-debugger-buttons.js
- src/test/mochitest/browser_dbg-editor-select.js
- src/test/mochitest/browser_dbg-iframes.js
- src/test/mochitest/browser_dbg-navigation.js
- src/test/mochitest/browser_dbg-quick-open.js
- src/test/mochitest/browser_dbg-scopes.js
- src/test/mochitest/browser_dbg-wasm-sourcemaps.js
- src/test/mochitest/browser_dbg_keyboard-shortcuts.js
- src/test/mochitest/head.js
* Fix up the quick open mochitest that had a failure. Not 100% certain if it was just racy before or if this was to adjust to changes from @jasonLaster's recent work. 🙁 
* Doc some tips based on what I did here.
* Prettier did its thing here.
> Fix quick open mochi

- src/components/shared/Modal.js
Associated Issue: #4485 
One set of createClass and PropTypes warnings were removed by avoiding use of `import * as React from "react";` facebook/react#10583
The remaining three sets of createClass and Proptypes warnings are from packages that are part of https://github.com/devtools-html/devtools-core
> Remove createClass and PropTypes warning

- src/components/SecondaryPanes/CommandBar.css
- src/components/SecondaryPanes/CommandBar.js
Associated Issue: #4350 
Converted the Step Button SVG's to images using CSS styles in the Command Bar.  Functionality remains the same, however I made a change that I think reflects pausing during exceptions in a very logical manner.  I used traffic lights as my inspiration for this and therefore used colors **Green**, **Orange**, and **Red** .  
When ignoring them, the User would not experience any halts and therefore Green was used to signify that.  When clicking on the `pause-exceptions` button to change it to pausing during uncaught exceptions, the image would be Orange as we are pausing only some of the time.  Finally, when clicking on the `pause-exceptions` button once again to change it to pausing on all exceptions, the image would be Red where the User is coming to a halt for all …
> (#4350) Converted Step Button SVG's to images using CSS Styles

- src/components/QuickOpenModal.js
- src/components/tests/QuickOpenModal.spec.js
- src/reducers/ui.js
Associated Issue: #4490 
* removed reference to CLEAR_HIGHLIGHT_LINES
* hooked clearing highlightedLineRange directly to window close
Performed searches
http://g.recordit.co/cy8JFnonNG.gif
> Unselects highlight on search window close

- src/components/ShortcutsModal.css
Associated Issue: #4432
* removed Mac specific behavior for Shortcut Modal
> Fixing Shortcut Modal Dark Theme Legibility on Mac

- src/test/mochitest/browser_dbg-sourcemaps2.js
- src/workers/parser/getSymbols.js
- src/workers/parser/tests/__snapshots__/getEmptyLines.spec.js.snap
- src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/workers/parser/tests/fixtures/class.js
- src/workers/parser/utils/ast.js
- src/workers/parser/utils/getFunctionName.js
- src/workers/parser/utils/helpers.js
Associated Issue: #3239 
* enable additional parser features
* parse out some additional function types
> 🎨: Update our symbol parsing code to extract additional function types

- src/test/mochitest/browser_dbg-quick-open.js
- src/utils/quick-open.js
Associated Issue: #4488 
* `:` is removed from the line numbers in search results
> Style line numbers in search results

- src/workers/parser/tests/__snapshots__/validate.spec.js.snap
- src/workers/parser/tests/validate.spec.js
- src/workers/parser/utils/ast.js
- src/workers/parser/validate.js
switches to validating scripts as opposed to expressions to accomodate new mapped expressions
> Validate scripts

- bin/ci/run-tests.sh
- package.json
- yarn.lock
One of the biggest pain points w/ mochitests is that it is hard to find the error in the test log. This will make it much easier by only showing the test logs for failing tests 🔥
> Dont show Mochi output for passing tests

- src/actions/ui.js
- src/components/Editor/index.js
Associated Issue: #4517 
The line number parameter is passed to the toggle function
Test Plan
Move the cursor to the desired line and press cmd+shift+b
The conditional breakpoint pane is toggled
> FIX - cmd+shift+b is no longer bound

- bin/mochi-intermittents.js
Mochi Intermittents is a small script for running the full mochitest
suite several times to look for intermittent failures.
There are two commands:
* run - runs the full suite N times
* uniqErrors - scans the logs for uniq test errors and their count
It is easy to pick up on trends by running `less logs`
and looking for `TEST-START <test-name>`
> Mochi intermittent script

- src/actions/tests/pause.spec.js
- src/client/firefox/tests/onconnect.spec.js
- src/test/tests-setup.js
We were allowing uncaught exceptions in our unit tests, which is a bad practice:
We now throw when we see it.
> Disallow uncaught exceptions

- src/components/SecondaryPanes/index.js
- src/components/shared/Accordion.js
Associated Issue: #4575
* Added new property cssClass to getScopeItem, getWatchItem and getStartItems responsible for keeping the css class name of the item.
* added new property to typeCheck
* removed generation of class name based on header as it caused bugs now and might complicate things further in future.
End result:
> Fixes secondary pane css classes being localized

- src/workers/parser/getSymbols.js
- src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/workers/parser/tests/fixtures/flow.js
- src/workers/parser/tests/getSymbols.spec.js
Fixes: #3462
Previously we were using the full identifier location, which included the type annotation range: e.g `name: string`. We now update the identifiers end column to just include `name`.
Unit test
> Exclude flow types from identifier locations

- flow-typed/debugger-html.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-returnvalues.js
- src/test/mochitest/head.js
- src/utils/scopes.js
- src/utils/tests/scopes.spec.js
Associated Issue: #3390
* **[`scopes.spec.js`]: Don't supply scope in `pauseData`.**
With [Bug 1370923], frames delivered to the new debugger no longer have `scope`
properties. This commit changes the mock pause data to omit the scope property.
However, since the tests don't actually check for `<return>` or `<throw>`
pseudovars, nothing fails --- yet.
* **[`getScopes`]: Fix `<return>` and `<exception>` pseudo-vars.**
As of [Bug 1370923], frames in "paused" packets from the server no longer include
an environment form. This broke [`getScopes`], which assumed it could recognize the
scope of the frame that is currently returning by comparing the scope's actor
name with that given in the "paused" packet's frame.
Since only one frame at a time will ever have a `frameFinished` property, it's …
> Fix display of return value / thrown exception in scopes

- bin/download-firefox-artifact
Associated Issue: avoiding error during ./bin/prepare-mochitests-dev command
> Adds mk_add_options AUTOCLOBBER=1 to .mozconfig

- .flowconfig
- package.json
- src/actions/utils/middleware/promise.js
- src/client/chrome/commands.js
- src/client/firefox/commands.js
- src/utils/test-head.js
- src/utils/utils.js
- src/utils/wasm.js
- yarn.lock
Associated Issue: #4528
* Fix flow errors 
* Pass `yarn run flow`
> [Flow] update to 57

- src/actions/ui.js
- src/components/Editor/EditorMenu.js
Associated Issue: feature #4022
* when selecting `copy Function` in the editor the function will be highlighted for 0.2 seconds
> flash function when it is copied - feature #4022

- src/components/Editor/EditorMenu.js
Associated Issue: #4420 
* Get if selected source is pretty-printed. If yes, disable "Reveal in tree" and "Blackbox script"
* Get open tabs list. Get pretty url for the selected source. If pretty tab is open, disable "Jump to Original Location"
> #4420 Context Menu "Jump to Original Location" should be disabled when not pretty-printed

- src/utils/wasm.js
Associated Issue: https://github.com/yurydelendik/sqlite-playground wast is truncated
> Display more wast text lines

- src/test/mochitest/head.js
Associated Issue: #4642 
The recent release was pulled out twice due to `browser_dbg-wasm-sourcemaps`. It looks like it was pulled out this time because we call: `waitForLoadedSource` before `doc-wasm-sourcemaps` has been loaded... This should be fine because we don't assume it here... The problem is that `findSource` was designed as a util for invoking actions like `selectSource(dbg, findSource(dbg, "simple1"))` where if the source didn't exist we wanted a clear error. 
This fix adds a `silent` mode, which allows findSource to return quietly if the source does not exist.
```
16:13:14     INFO - Buffered messages finished
16:13:14     INFO - TEST-UNEXPECTED-FAIL | devtools/client/debugger/new/test/mochitest/browser_dbg-wasm-sourcemaps.js | Uncaught exception - at …
```
> Relax findSource

- src/components/SecondaryPanes/index.js
Associated Issue: #4631 
Removed react-immutable-proptypes and replaced with proptypes
Test Plan
Secondary pane functionality should work as intended
> Drop react-immutable-proptypes

- src/components/Editor/EditorMenu.js
Associated Issue: #4607 
Specify the ids of the jump and the add-watch-expression menuitems
> Specify the ids of the jump and the add-watch-expression menuitems

- src/components/shared/Dropdown.css
Associated Issue: #4609
Use `overflow: auto` on the dropdown so the scroll bar will appear only when seeing overflow
> 4609 - Hide scrollbar of Dropdown when no overflow

- package.json
- yarn.lock
Associated Issue: #3307 
Updates the dependency to `parse-script-tags` to version 0.1.4 which supports   omitting script tags that have non-JS types.
* Added breakpoints on a Wordpress site (http://davidwalsh.name) with non-JS `<script>`s
* Created a simple sample with non-JS `<script>`:
```html
<html>
<script type="application/ld+json">
var notScript = true;
alert(notScript);
</script>
<script>
console.log('from script');
</script>
<body>
Not Script
</body>
</html>
```
> Fix including non-JS scripts from HTML source

- src/components/SecondaryPanes/index.js
- src/test/mochitest/browser_dbg-wasm-sourcemaps.js
Associated Issue: #4651
Make the call stack not open automatically on pause
> 4651-call-stack-should-not-open-automatically

- src/actions/types.js
- src/components/PrimaryPanes/SourcesTree.js
- src/test/mochitest/browser_dbg-debugger-buttons.js
- src/test/mochitest/browser_dbg-editor-select.js
- src/test/mochitest/browser_dbg-expressions-error.js
- src/test/mochitest/browser_dbg-sourcemaps2.js
- src/test/mochitest/head.js
Hey folks, when working on SourcesTree.js I noticed that the redux usage can be made more readable using a more explicit approach.
* explicit import of used actions
* ditch bindActionsCreators in favour of `() => dispatch(myImportedAction())`
* explicitly name and define connect props
I think this makes it more readable and more accessible for newbies who don't have to follow a trail of imports to see where props are coming from.
> [Refacoring] Make Redux Connect more explicit in Sources Tree

- assets/panel/debugger.properties
- src/components/Editor/Footer.css
- src/components/Editor/Footer.js
- src/reducers/sources.js
- src/test/mochitest/browser_dbg-pretty-print.js
- src/test/mochitest/browser_dbg-sourcemaps2.js
- src/test/mochitest/head.js
- src/utils/editor/index.js
Associated Issue: #4242
* Footer shows a short message in the bottom for generated with a link to the root original directory aka webpack "(From bundle.js)"
* Hover over message, tooltip comes up and shows full message "(source mapped from bundle.js)"
* Click on short message "(From bundle.js)" to jump to the start of the original file in the generated bundle
> [Editor] Show a link to a generated file - ultimate PR

- src/components/shared/PreviewFunction.css
Associated Issue: #4604 
* As suggested in the associated issue #4604, the color of param in Outline is changed.
Before  | After
:--|:--
> [Outline] Use magenta for param color, fixes #4604

- src/components/Editor/SearchBar.css
- src/components/Editor/Tabs.css
- src/components/ProjectSearch/TextSearch.css
- src/components/SecondaryPanes/Breakpoints.css
- src/components/SecondaryPanes/Expressions.css
- src/components/shared/Button/Close.css
- src/components/shared/Button/Close.js
- src/components/shared/Modal.css
- src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
- src/components/tests/__snapshots__/closeButton.spec.js.snap
Associated Issue: #4350 
* Converted Close Button SVG's in tab, breakpoint, watch expression, and the search bar.
I used the close button styling from the Atom text editor.  Their close button change in color when they are hovered over.  A GIF follows for representation:
> Converted tab, breakpoint, watch expression, and search bar Close Button SVG's to Images

- package.json
- yarn.lock
[PrettyPrint] uncaught exception: SyntaxError: Unexpected character '`' (709:32) #4619
Issue: #4619
any JS code with template string seems to fail with that exception
example code:
const code = `
\`\${ foo({class: 1}) }\`
`
> [PrettyPrint] uncaught exception: SyntaxError: Unexpected character '`' (709:32) #4619

- docs/issues.md
Associated Issue: None
* Fix a typo in 2 urls that broke some links.
> Fix a typo for the difficulty level filter urls

- src/components/Editor/Breakpoints.js
- src/components/Editor/Preview/Popup.js
- src/components/Editor/Preview/index.js
Associated Issue: #4532
Update the mapDispatchToProps calls for 
- src/components/Editor/Breakpoints.js
- src/components/Editor/Preview/Popup.js
- src/components/Editor/Preview/index.js
> 4532 - Part 1: Update the mapDispatchToProps calls for Breakpoints.js, Popup.js, Preview/index.js

- src/reducers/ast.js
Fixes #4692
- the JSX patch introduced sourceMetaData, which when not set would be a new empty object every time, this fixes that by sharing the same object.
- i think it can be a bit cleaner
I'd like to add a unit test that adds a source and checks to make sure the editor did not render.
> Prevent unecessary renders

- src/actions/project-text-search.js
- src/actions/tests/__snapshots__/project-text-search.spec.js.snap
- src/actions/tests/project-text-search.spec.js
- src/components/App.js
- src/components/ProjectSearch/TextSearch.js
- src/components/ProjectSearch/index.js
- src/components/ProjectSearch/tests/TextSearch.js
- src/reducers/project-text-search.js
- src/reducers/ui.js
Associated Issue: #4526 
- Press ⌘ + ⇧ + F
- Enter a search term
- Press 'x'
- Press ⌘ + ⇧ + F
- The older search results are now cleared
> [Search] Clear results while closing project search

- assets/panel/prefs.js
- src/components/SecondaryPanes/CommandBar.js
- src/utils/prefs.js
* Command bar buttons appear only when paused
> Toggle Command Bar Buttons

- src/components/SecondaryPanes/Expressions.css
Associated Issue: #4688
* remove `margin-top` from the container in order to fix vertical positioning. Fixed only positioning for the 'Watch Expression' panel.
#goodnessSquad
> Fix weird position of 'X' close button

- assets/panel/panel.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-console-link.js
- src/test/mochitest/browser_dbg-pretty-print-console.js
- src/test/mochitest/browser_dbg-toggling-tools.js
- src/test/mochitest/examples/script-switching-02.js
- src/test/mochitest/head.js
Associated Issue: #3411
When we switched to selectSource accepting a location we missed some call sites. This fixes that an adds a mochitest.
> Clicking a console link should navigate to the correct line

- src/utils/source.js
Associated Issue: #3392
* Added modes for syntax highlighting some non-js languages for WASM (C, C++, Kotlin, Rust)
First, this is dependent of https://github.com/devtools-html/devtools-core/pull/798
After the above is merged and new version of the source-editor is released, this would be tested:
test plan:
- 
> Add syntax highlight for non-js languages

- src/components/Editor/Editor.css
- src/components/Editor/Tabs.css
- src/components/PrimaryPanes/Sources.css
- src/components/SecondaryPanes/CommandBar.css
Associated Issue: #4756 
Modified header variable to actually match the given value: https://github.com/devtools-html/debugger.html/blob/master/src/components/Editor/Tabs.css#L8
Visual change, looks neat now.
The issue was actually always there, not just in the dark theme. See the picture below:
It was not obvious in the other themes because the background was white.
> #4756 Remove stray line

- docs/mochitests.md
There didn't seem to be information as to where to run the command, which might cause confusion.
> Specifies the location where to run firefox setup

- src/components/PrimaryPanes/Outline.css
> Fix #4776 - Ensure no whitespace breakage in outline items

- src/actions/breakpoints.js
Associated Issue: #4534 
Toggle breakpoint method has been changed to check existence of breakpoint on commented out line
Test Plan
- Open the source file to be debugged
- Place a breakpoint on any valid line in the file
- Make changes to the source file by commenting out the line where debugger was placed
- Click back in the browser and click on the file to be debugged again (or click forward in browser)
- The breakpoint should be visible on the commented out line
- Click on the breakpoint and it should be removed
> Remove breakpoint in codemirror commented line

- assets/panel/debugger.properties
"Jump to Generated location" -> "Jump to generated location"
> Ensure the 'jump to' context menu label cases are consistent

- src/utils/breakpoint/astBreakpointLocation.js
Associated Issue: #4519
* gets shortcut for getASTLocation logic
> Don't parse symbols for WASM

- src/actions/sources.js
- src/client/firefox/events.js
- src/client/firefox/types.js
- src/reducers/sources.js
- src/test/mochitest/browser_dbg-breaking.js
Associated Issue: #4705 
This throttles the firefox newSource event so that we fire at most one newSources action every 50ms. 
* Not sure if we need a test
* Not sure if we want to debounce in the event or the actions. Events seem easier now
The performance savings is significant ⏲ 
~ 9 seconds. Lots of thrashing here :P
3 seconds. The editor update holds up the main thread so we also do more newSources calls :) vicious cycle
1.5 sec
> Throttle new sources

- src/components/SecondaryPanes/Frames/index.js
Associated Issue: #2804 
* Removed redundant PropTypes declaration. It was already migrated to using flow Props
- Opened todoMVC example. 
- put a break anywhere
- resfresh a page to break
- check that secondary panes and frames are working as usual
> Removed PropTypes for Frames/index.js

- src/components/Editor/ConditionalPanel.css
- src/components/Editor/ConditionalPanel.js
- src/components/Editor/Editor.css
Associated Issue: #4703 
This is achieved by adding some right padding to the breakpoint panel, and removing the minimum width of the `.CodeMirror-sizer`. I haven't noticed any side effects related to disabling the min-width.
The gutters seem to be fixed in place the same way: they listen for `scroll` events on the `.CodeMirror-scroll` div, and then move themselves `x` pixels to the left, where `x` is `.CodeMirror-scroll`'s `scrollLeft`. If we need to fix more things this way, we might be able to abstract the scroll-listening logic from `ConditionalPanel.js` in the future.
(scroll repositioning is a bit jankier in horizontal mode, though the number gutters suffer from this too)
> Conditional breakpoint panel responsiveness and visual fixes

- src/components/Editor/index.js
Associated Issue: #4767 
* Check if ConditonalPanel is open and closing it before trying to set a regular breakpoint
> Editor: close ConditionalPanel before adding breakpoint

- src/components/ProjectSearch/TextSearch.css
**Post fix:**
**Prior to fix:**
> Fixed whitespace at the bottom of center pane after searching files

- src/actions/sources.js
there was an issue in which new sources that are added via sourcemapped
sources, would disappear on reload.
> use newSources for sourcemapped sources

- src/actions/sources.js
Associated Issue: #3996
* separated check for non-existing and not loaded source
* made source load if exists and not previously loaded
> Loads non-loaded source before trying to prettyPrint

- src/test/mochitest/examples/doc-asm.html
- src/test/mochitest/examples/doc-async.html
- src/test/mochitest/examples/doc-content-script-sources.html
- src/test/mochitest/examples/doc-debugger-statements.html
- src/test/mochitest/examples/doc-exceptions.html
- src/test/mochitest/examples/doc-frames.html
- src/test/mochitest/examples/doc-iframes.html
- src/test/mochitest/examples/doc-minified.html
- src/test/mochitest/examples/doc-minified2.html
- src/test/mochitest/examples/doc-return-values.html
- src/test/mochitest/examples/doc-script-mutate.html
- src/test/mochitest/examples/doc-script-switching.html
- src/test/mochitest/examples/doc-scripts.html
- src/test/mochitest/examples/doc-sourcemap-bogus.html
- src/test/mochitest/examples/doc-sourcemaps.html
- src/test/mochitest/examples/doc-sourcemaps2.html
- src/test/mochitest/examples/doc-sourcemaps3.html
- src/test/mochitest/examples/doc-sources.html
- src/test/mochitest/examples/doc-wasm-sourcemaps.html
Associated Issue: #4870 
-  License header added to all examples in mochitest directory
> Added license header to all examples in mochitest directory

- src/actions/pause/fetchScopes.js
- src/utils/pause.js
`updateScopeBindings` is particularly confusing at the moment. It is a function in `utils/pause` that wraps a function from devtools-map-bindings. It uses sourceMap functions and dispatches actions. 
This refactor moves it to `fetchScopes` where it will be treated as an action and is simpler.
> Refactor updateScopeBindings

- package.json
- src/workers/parser/utils/ast.js
- yarn.lock
Associated Issue: #3307 
* Updates `parse-script-tags` dependency to 0.1.5
* Change parser to use `customParse` submodule to avoid including the `babylon` dependency in the build
> Address memory leak introduced by parse-script-tags

- src/components/Editor/CallSites.js
- src/components/Editor/index.js
Associated Issue: #4896
Our callsite flag which is used to feature flag the Column Breakpoints UI previously rendered the breakpoints in the background and just disabled the event handling so they wouldn't be shown. 
This means that we were paying the price of fetching and rendering the breakpoints with codemirror, with none of the benefits.
Here are the perf wins we'll see in minified files. Most of the time is spent fetching the column breakpoints:
The first half of the time is spent in `setText` the second half is spent in `getCallSites`
We'll want to look into speeding up `setText` as well.
> Update CallSites flag

- src/components/Editor/index.js
Associated Issue: #4868
This addresses a recent issue where reloading the debugger would no longer show the selected source.
The issue was timing related where the source loaded before the editor had been setup. This fixes it by showing the source text when the editor is created.
> Show source text when devtools opens

- .travis.yml
- src/test/mochitest/browser_dbg-console.js
* Synchronize changes from [Bug 1408949](https://bugzilla.mozilla.org/show_bug.cgi?id=1408949)
* updated the m-c changeset so that shared-head.js clears `Services.prefs.clearUserPref("devtools.toolbox.splitconsoleHeight");`
> Synchronize test changes to getSplitConsole from bug 1408949

- src/components/QuickOpenModal.js
To test:
- Press `Command + P` to open the search pane
- Type a few letters, then delete them; "0 results" should be the final label.
> Fix #4924 - Prevent NaN result count

- src/components/ProjectSearch/index.js
* Removed PropTypes to Props in ProjectSearch
> Switch ProjectSearch PropTypes to Props

- src/test/tests-framework.js
- src/test/tests-setup.js
Associated Issue: #4927 #4894 
I found the source of the maxEventListeners bug in Jest while hunting down an intermittent on CI.
It turns out that we were binding our unhandledRejection listener on every test run.
> Fis CI intermittent and maxListeners

- src/actions/sources.js
- src/client/firefox/events.js
- src/client/firefox/types.js
- src/reducers/sources.js
- src/test/mochitest/browser_dbg-breaking.js
Reverts the throttle optimization because it had a memory leak w/ try.
We're working on a fix now
> Revert "Throttle new sources (#4749)"

- src/components/SecondaryPanes/Frames/Frame.js
Associated Issue: #4864
* Do not select the frame if its already selected
> Do not select the frame if the frame is already selected

- src/components/shared/Modal.css
- src/components/shared/ResultList.css
Associated Issue: #4504
* makes .modal height dependent on viewport
* removes properties with no visual impact
> Makes search modal results scroll

- src/actions/tests/__snapshots__/ast.spec.js.snap
- src/actions/tests/ast.spec.js
- src/actions/tests/preview.spec.js
While removing the preview tests, i noticed that we're testing some of the ast methods w/ and w/o pretty print prefs. We dont need to do that as it doesn't affect how the ast actions work.
> NOTE, we need to first land the preview fix
> [WIP] Cleanup AST spec

- assets/panel/WASMPARSER_UPGRADING
- bin/copy-assets.js
Associated Issue: automation of bug1426251-like tasks
* Copies WasmParser.js/WasmDis.js files into
* Produces valid WASMPARSER_UPGRADING help file
> Synchronize wasmparser with m-c.

- src/client/README.md
- src/client/firefox/events.js
Watch expressions are currently re-evaluated when breakpoints are added. The reason for this is that adding a breakpoint is a temporary interrupt, which triggers a pause and resume event. 
We currently suppress the pause action because it's useless, now we suppress the resumed event as well so that redux is none the wiser.
> Suppress interrupt resumed events

- src/components/Editor/DebugLine.js
- src/test/mochitest/head.js
- src/utils/editor/index.js
Associated Issue: #4968 
A last minute change to toEditorPosition broke the clearing mechanism for debug line. This fixes that and adds a test so that we don't have multiple debug lines in the future.
> Fix clearing debug line

- src/components/SecondaryPanes/index.js
- src/test/mochitest/browser_dbg-minified.js
- src/test/mochitest/browser_dbg-navigation.js
Associated Issue: #4651
We recently updated the frames component so that it wouldn't auto-open on pause. This is nice because users often want to step w/o seeing the call stack. 
This changes applies strategy for the scopes pane. It's useful because: 
1) it feels bad to see the scopes pane auto-open and not the frames pane.
2) users sometimes want to quickly step.
> [Scopes] dont expand on pause

- assets/panel/panel.js
- assets/panel/prefs.js
- src/actions/toolbox.js
- src/actions/types.js
- src/components/SecondaryPanes/Workers.css
- src/components/SecondaryPanes/Workers.js
- src/components/SecondaryPanes/index.js
- src/reducers/debuggee.js
Associated Issue: #4033
* Add `openWorkerToolbox` action
* Added selectors
TODO
* Fix bug with worker not connectiing on opening the toolbox
> Open worker in toolbox

- src/actions/navigation.js
- src/actions/sources.js
- src/actions/sources/blackbox.js
- src/actions/sources/index.js
- src/actions/sources/newSources.js
- src/actions/sources/tabs.js
* extract newSources
* extract tabs
* extract blackbox
Currently this is sitting on top of the pause refactor, so it's blocked by that work
> Refactor source actions (1/x)

- src/workers/parser/getSymbols.js
- src/workers/parser/tests/getSymbols.spec.js
- src/workers/parser/utils/helpers.js
I'm seeing some errors when i try to add a breakpoint `elements.map is undefined` I believe this is coming from a case in `getVariables`, but i have not been able to fully track it down yet
This change is the start of a fix, where we try/catch extractSymbol so that we don't fail if we don't understand a path
> Protect getSymbols

- src/actions/sources/loadSourceText.js
Regressed after 81b70c614cfbc2
* Changes loadSourceText logic to allow wasm source to finish the request
1. Open https://mdn.github.io/webassembly-examples/js-api-examples/memory.html
2. Start debugger
3. Refresh the debuggee
4. Locate/open wasm source and set breakpoint at 0x52 address (at "i32.load")
5. Refresh the debuggee
Notice at source is loaded and stopped at the desired location
> Fixes loadSourceText async loading for wasm.

- src/workers/parser/getSymbols.js
- src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/workers/parser/tests/fixtures/destructuring.js
- src/workers/parser/utils/helpers.js
#5013 fixed the issue where we could throw an exception while getting symbols. This fixes the bug we were seeing in the debugger bundle.
As a fun fact, I found the bug by dropping the bundle into a test fixture and running it directly. This was easier than debugging the browser toolbox's parser worker :)
> Fix destructuring

- assets/panel/prefs.js
this fixes a bug we introduced in #4945 where the old debugger's worker pref became un-available
+ failing test `browser_jsterm_autocomplete_in_debugger_stackframe.js`
+ [workersEnabled](https://searchfox.org/mozilla-central/source/devtools/client/debugger/debugger-controller.js#1220)
> Fix old debugger workers pref

- assets/panel/debugger.properties
Forgot to synchronize https://bugzilla.mozilla.org/show_bug.cgi?id=1425280 here, sorry about that.
(however this shows that we really need a tool to check this kind of things).
Fixes localization notes in debugger's properties file. Please include it in the current release to avoid overriding this in m-c.
> Synchronize localization note fixes from Bug 1425280

- docs/issues.md
Associated Issue: #5044
* adds docs as possible issue title start tag
* expands on examples on how to use start tags
> [Docs] Adds docs as possible issue title start tag

- src/test/mochitest/browser.ini
We are seeing some failing tests on windows for `browser_dbg-preview-source-maps` I'm guessing that it is due to the cursor position.
I'm going to try also enabling the other preview test for all platforms, sans windows too
> Skip preview test on windows

- src/components/SecondaryPanes/index.js
When we landed the #4974 work, we accidentally flipped the ordering of the scopes and call stack panes.
> Fix pane ordering

- src/actions/navigation.js
- src/actions/tests/navigation.spec.js
- src/client/firefox.js
This test `devtools/client/netmonitor/test/browser_net_open_in_debugger.js` found a timing issue where we needed to wait for connect to finish fetching the workers before we concluded the debugger was open...
> Fix timing connect issue

- src/actions/navigation.js
- src/client/firefox/events.js
- src/test/mochitest/browser_dbg-sourcemaps-reloading.js
- src/utils/source-queue.js
Associated Issue: #5057 
When we pause we need to wait for sources to be registered in redux and the parser worker. This is why when we pause we flush the newSources queue. The issue is we also need to wait on original sources  to be fetched from the source map worker :)
| Before | After |
| -- | --- |
| ![b] | ![a] |
[b]: https://user-images.githubusercontent.com/254562/34797795-97a8bbe8-f627-11e7-83d9-92519b673696.png
[a]: https://user-images.githubusercontent.com/254562/34797796-97b52748-f627-11e7-97a1-53ec01d44faa.png
> Support pausing immediately

- src/utils/editor/create-editor.js
- src/utils/prefs.js
I think that this broke when we consolidated feature flags w/ prefs... 
As a side-note, it would be nice to revisit folding in a couple of weeks
> Fix codefolding

- src/components/Editor/SearchBar.js
Associated Issue: #5082 
* Refresh search results when search modifier is changed
> Refresh search results on modifier change

- src/utils/sources-tree/utils.js
Associated Issue: #5029
We were skipping sources that were loading, which was bad because they would not be added in the future. If we want to be safer we can keep loading sources out of the newSet, but i don't know if it's needed and it is slower:
```diff
diff --git a/src/components/PrimaryPanes/SourcesTree.js b/src/components/PrimaryPanes/SourcesTree.js
index f58b121..b5d593a 100644
--- a/src/components/PrimaryPanes/SourcesTree.js
+++ b/src/components/PrimaryPanes/SourcesTree.js
@@ -175,7 +175,9 @@ class SourcesTree extends Component<Props, State> {
// TODO: do not run this every time a source is clicked,
// only when a new source is added
-    const next = Set(nextProps.sources.valueSeq());
+    const next = Set(nextProps.sources.valueSeq()).filter(
+      source => …
```
> [SourceTree] show loading sources

- src/actions/sources/newSources.js
I noticed while testing https://reactjs.org/ that it had a bad map, which was causing an exception so i wrapped the API.
> Make loading source maps safer

- src/actions/tests/ast.spec.js
- src/utils/test-head.js
- src/utils/tests/function.spec.js
- src/workers/parser/tests/closest.spec.js
- src/workers/parser/tests/framework.spec.js
- src/workers/parser/tests/getEmptyLines.spec.js
- src/workers/parser/tests/getSymbols.spec.js
- src/workers/parser/tests/helpers/index.js
- src/workers/parser/utils/ast.js
Associated Issue: #5096 
Working on #5096, the biggest slow down comes from parsing + traversing the large generated files (aka bundles). The debugger bundles can take ~12 seconds in the debugger worker. When it's parsed in a jest test it's about ~7 seconds. 
When we parse the file without the babylon plugins, the time goes down to ~3 seconds. This could be a big savings in the debugger as we only need to parse + traverse the bundle once.
> Speed up generated source parsing

- src/actions/breakpoints/tests/syncing.js
- src/actions/sources/newSources.js
Small refactor to consolidate the logic between `newSource` and `newSources`. We don't use `newSource` in the app, but we do in the tests. In the future, it might be nice to have around too...
> Refactor newSource

- assets/panel/prefs.js
We're currently mapping the scopes and bindings when we pause. This is causing some weird results w/ several transforms which we should investigate before we re-enable it.
> Disable map scopes

- src/actions/ast.js
- src/actions/sources/loadSourceText.js
- src/actions/sources/select.js
- src/actions/sources/tests/select.spec.js
- src/actions/tests/ast.spec.js
- src/actions/tests/helpers/threadClient.js
- src/actions/tests/pause.spec.js
- src/utils/test-head.js
Associated Issue: #5096 
* Moves `getSymbols` from `loadSourceText` to `selectLocation`.
* The rationale is that loadSource could happen much on debuggee load, which is unnecessary
> Get symbols in select

- src/test/mochitest/browser_dbg-minified.js
- src/test/mochitest/browser_dbg-sourcemaps3.js
Associated Issue: #5111 
We recently disabled the map-scopes feature because there are some issues with some of the mappings. This caused the tests to fail w/o flagging the feature on in those cases.
> Enable the map-scopes in the related tests

- src/test/mochitest/browser_dbg-async-stepping.js
- src/test/mochitest/browser_dbg-chrome-create.js
- src/test/mochitest/browser_dbg-minified.js
- src/test/mochitest/browser_dbg-search-project.js
- src/test/mochitest/browser_dbg-sourcemaps3.js
Use the pushPref helper whenever possible in mochitests, otherwise the preference changes leak from one test to another. 
Also simplified some tests that used to set the preference and restore it on cleanup. First, there was no added value compared to pushPref. Secondly, the restore was not wrong. It should restore to the original value (read at the beginning of the test) rather than to a random set value (eg. false).
Let's see if tests still pass.
> Use pushPref helper in mochitests to set temporary pref values

- src/components/QuickOpenModal.js
- src/components/SecondaryPanes/CommandBar.css
before:
after:
* Changed height of Command Bar
> fix alignment of command bar

- src/actions/project-text-search.js
- src/actions/tests/__snapshots__/project-text-search.spec.js.snap
- src/actions/tests/project-text-search.spec.js
- src/reducers/sources.js
#5109 
* Removed sources that have a minified version in project search
- Open https://arewesmoothyet.com/?mode=track&trackedStat=Devtools%20Hangs
- CMD-SHIFT-F for "trackedStat"
- Click on the first result
- Prettify file; needs some time
- Go back to search with CMD-SHIFT-F
- Focus search field and search again
- The non-minified file should be gone
With changes:
Before changes:
> [Project Search] Removed sources that have a minified version

- src/components/SecondaryPanes/Scopes.css
Associated Issue: #5151 
* Added a 4px padding to the left-hand side of ```scopes-list``` class
* A visual check that the Block node aligns with the Parent Scopes node.
> [Scopes]-fixed missing padding in scopes tree

- src/actions/project-text-search.js
- src/actions/tests/project-text-search.spec.js
- src/actions/types.js
- src/components/ProjectSearch.js
- src/components/shared/SearchInput.js
- src/components/tests/ProjectSearch.spec.js
- src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
- src/reducers/project-text-search.js
Associated Issue: #5108
With this commit, the Status behavior is stored differently in reducers.
- INITIAL -> Search not yet performed
- FETCHING -> Search in progress
- DONE -> Search completed | Smiley Shown | After all sources searched
- (not fired after each source as before)
- Render error emoji only on done
- Removes a slight jitter in the UI when the results are still inflight.
- Use the shouldShowErrorEmoji predicate instead of passing status
- CmdOrCtrl+Shift+F
- As per above
> (refactor) [Project search] Modify status update and error emoji (#5108)

- src/components/PrimaryPanes/Outline.css
- src/components/PrimaryPanes/Sources.css
- src/components/shared/ManagedTree.css
* fix height in sources tree, there was blue line under selected item 
* unify padding around items in outline list
* and fix https://github.com/devtools-html/debugger.html/issues/5149
* sources tree BEFORE
* sources tree AFTER
* outline list BEFORE
* outline list AFTER
> [Sources] - fix paddings in sources tree and outline list

- src/utils/prefs.js
We recently disabled map scopes when we're in the panel. I think we should do the same thing in dev because it is pretty slow and makes it difficult to do performance testing.
> Disable map scopes in dev

- postcss.config.js
I think a majority of user use modern browsers for running this debugger, so some prefixes for really old browsers are not needed.
> Disable CSS auto-prefixes for old IE

- src/actions/breakpoints/syncBreakpoint.js
- src/actions/breakpoints/tests/__snapshots__/syncing.js.snap
- src/actions/breakpoints/tests/syncing.js
Associated Issue: #5140
This fixes a bug where we were not removing old disabled breakpoints when the breakpoint moved on sync.
I'm working on a follow up PR where I cleanup the unit tests and increase the coverage
> Fix syncing disabled breakpoints

- .travis.yml
- docs/local-development.md
- src/actions/sources/loadSourceText.js
- src/test/tests-framework.js
Associated Issue: #4158 
* needs shims from devtools-core
* needs some sync w/ releasing so we can have the histograms/scalar.yml work done
> Add telemetry probes

- src/client/firefox/commands.js
- src/reducers/breakpoints.js
- src/test/mochitest/browser_dbg-sourcemaps-reload.js
Associated Issue: #3982
When the breakpoint is at an original location that is no longer mapped to a generated source we want to remove it. In those cases we need to make sure that the breakpoint is removed from the breakpoint redux & client store.
> Fix syncing breakpoints when bps are removed

- src/components/QuickOpenModal.js
- src/components/tests/QuickOpenModal.spec.js
Associated Issue: #5085 #4996
* limit fuzz aldrin to 1000 results
* limit result list to 100 items
* show tabs on initial render... not sure about the UX here...
> Speedup quick open

- src/components/Editor/EditorMenu.js
Associated Issue: #5131
* Changing the line number of the copy functionality to prevent error described in the issue
Open a JS file, right-click on a function line and select `Copy function`.  There should be no error.
> Fix 5131 - Use correct line for copying function

- bin/ci/run-tests.js
WIP.
Added all the tests I could find the devtools that rely on the new debugger. In theory they should all be tested as well. If it increases the testing time too much, we can look in more details on try to remove  tests that seem redundant regarding their usage of the debugger.
Let's see what the CI says.
> CI: add mochitests using the debugger and located in non-debugger test suites

- .travis.yml
This new sha should unblock browser_browser_toolbox_debugger.js
> Update mozilla-central sha for travis

- src/test/mochitest/browser_dbg-reload.js
accidentally removed a mochitest in the revert PR...
As a note, the `mochii -ci` passed w/o no error output when mochitest had a fatal error. We should improve the CI runner so that it fails in these cases and shows the errors
> Re-add accidentally removed mochitest

- src/components/PrimaryPanes/SourcesTree.js
- src/components/tests/SourcesTree.spec.js
- src/components/tests/__snapshots__/SourcesTree.spec.js.snap
- src/test/mochitest/browser_dbg-sources.js
- src/utils/sources-tree/createTree.js
- src/utils/sources-tree/index.js
- src/utils/sources-tree/tests/__snapshots__/updateTree.spec.js.snap
- src/utils/sources-tree/tests/addToTree.spec.js
- src/utils/sources-tree/tests/updateTree.spec.js
- src/utils/sources-tree/updateTree.js
- yarn.lock
Pull request #5004 introduced an issue where the SourcesTree was not updated when navigating to a new URL. In reality it was setting the tree using `props.blah` instead of `nextProps.blah`.
This also fixes a couple of undefined errors I was randomly getting in the console.
> Reset SourcesTree when necessary

- src/actions/pause/fetchScopes.js
- src/actions/tests/pause.spec.js
Associated Issue: #5185
- A non-existent pauseInfo was called which resulted in an empty selector and the test passing with an error in the console despite the generatedSourceRecord in fetchScopes.js being undefined.  It seems the test now fails like it should.
> Calls the correct pause info

- src/components/QuickOpenModal.js
- src/components/tests/QuickOpenModal.spec.js
- src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
Associated Issue: #5086
* Added case for preventing goto from performing a search
Tested by typing alphabetical characters after ":", and observed the behavior to work how it should.
before: 
after:
> [QuickOpen] Fix for go to line showing matching files

- package.json
when firefox was installed, jest was searching there as well
> Fix jest directory excludes

- src/actions/breakpoints/addBreakpoint.js
- src/utils/breakpoint/astBreakpointLocation.js
- src/utils/breakpoint/tests/astBreakpointLocation.spec.js
Associated Issue: #5096
Replaces a call to the parser getSymbols w/ a fetch from the redux store.
> [breakpoints] Use symbols from store

- src/components/Editor/Editor.css
- src/components/Editor/tests/Editor.spec.js
- src/utils/editor/index.js
- src/utils/editor/tests/editor.spec.js
Associated Issue: #5138 
-Check if the line is currently visible.
-Only realign the line to be centered if the line is out of bounds.
N/A
Before: 
- As can be seen before, on every step in the debugger the editor was being realigned horizontally and vertically.
After:
- After the changes the editor will only be realigned when the line goes out of the bounds of the editor.
Before:
- Negative on the margin on the right side of the scroll area was increasing the clientWidth of the scrollArea.
After:
- Removed extra margin on the right side of …
> Change horizontal and vertical realignment to only occur when line is out of bounds.

- src/test/mochitest/head.js
Adds a screenshot helper
```diff
diff --git a/src/test/mochitest/browser_dbg-sources.js b/src/test/mochitest/browser_dbg-sources.js
index 217baf6..caf2dcd 100644
--- a/src/test/mochitest/browser_dbg-sources.js
+++ b/src/test/mochitest/browser_dbg-sources.js
@@ -32,6 +32,7 @@ add_task(async function() {
assertSourceCount(dbg, 2);
await clickElement(dbg, "sourceArrow", 2);
+  await takeScreenshot(dbg);
assertSourceCount(dbg, 7);
await clickElement(dbg, "sourceArrow", 3);
```
https://bitty.io/anonymous/ecb38f683670af8a0aa34905689b349a
> Add takeScreenshot API

- src/components/PrimaryPanes/Sources.css
Associated Issue: #5250
* Fix indentation of non-expandable tree nodes
> Fix indentation of non-expandable tree nodes

- src/components/Editor/SearchBar.css
- src/components/WelcomeBox.css
- src/components/shared/SearchInput.css
@jasonLaster 
Associated Issue: #4544
* darken search box placeholder text
* darken welcome box shortcut text
* darken search-modifiers
* so far, things are appearing a little too dark
* the pale disclosure arrow icons, plus button icon, "add watch expression", and x buttons in the file tabs should be grey-40 also
> increase contrast in welcomebox and search placeholder

- src/components/SecondaryPanes/Breakpoints.js
- src/components/SecondaryPanes/BreakpointsContextMenu.js
- src/components/shared/Svg.css
- src/test/mochitest/browser_dbg-sourcemaps-reloading.js
- src/test/mochitest/browser_dbg-sourcemaps.js
- src/test/mochitest/browser_dbg-sources-named-eval.js
- src/test/mochitest/browser_dbg-sources.js
- src/test/mochitest/head.js
fixes issue 5223
Clean up extracted context menu
rearranged imports and fixed vairable names
Passed all original test
> [Breakpoints] Clean up extracted context menu #5223 completed

- src/actions/pause/fetchScopes.js
- src/actions/pause/mapScopes.js
- src/actions/tests/expressions.spec.js
- src/actions/tests/helpers/threadClient.js
- src/actions/tests/pause.spec.js
- src/actions/types.js
- src/components/SecondaryPanes/Scopes.js
- src/components/shared/Svg.css
- src/reducers/pause.js
- src/test/mochitest/browser_dbg-sourcemaps-reloading.js
- src/test/mochitest/browser_dbg-sourcemaps.js
- src/test/mochitest/browser_dbg-sources-named-eval.js
- src/test/mochitest/browser_dbg-sources.js
- src/test/mochitest/head.js
Associated Issue: #5254
* Add a general "Loading..." state for the scope list pane
* Change the scope state to be asynchronous with status
* Split the scope list state into two separate sets for generated and mapped scopes, and render based on which file you are viewing.
> Render mapped scope list only when viewing original file

- assets/panel/debugger.properties
Fixes #4701
* Moves CmdOrCtrl to a string
* bumps locale keys
> Update locales to not include cmdOrCtrl

- src/components/shared/SearchInput.js
Associated Issue: #5214
- Selects the text in the input of the search modal if there is text to be selected
=== Video
> Selects input text value on re-opening modal

- src/components/PrimaryPanes/Outline.js
Associated Issue: #5258 
* Adds a separate class heading and list for functions of the class
* Will use the same color highlighting as the editor highlighter
I'm using the following test file:  https://gist.github.com/darkwing/3946523182fb40cdd1d10e1401ef481d
- Open file linked above, ensure that functions are under correct class heading
> Fix #5258 - Group class functions within Outline Panel

- src/actions/pause/mapScopes.js
- src/utils/pause/scopes/getScope.js
- src/utils/pause/scopes/utils.js
- src/workers/parser/visitor.js
Associated Issue: #5252
* Fixes a few bugs in the visitor scope analysis
* Uses scope information to try to map `this` and `arguments`
Kind of hard to test this one because Babel at least doesn't generate maps with good mappings for these. I'll make a PR for babel to map them properly.
These shots are taken with a local copy of Babel that actually generates good maps for `this` and `arguments` 😬 
* Note the successful inclusion of the correct `this` in this case, even though the user is inside of a transformed arrow function.
* Here note that `this` can only be transformed if there is a `this` reference in the same function scope as the breakpoint itself, as the debugger server does not send us binding information about `this` in other scopes. `arguments` still works because the parent …
> Map original 'this' and 'arguments' to correct bindings where possible

- assets/dictionary.txt
- src/actions/ast.js
- src/actions/tests/ast.spec.js
- src/actions/types.js
- src/reducers/ast.js
- src/utils/tabs.js
- src/workers/parser/frameworks.js
- src/workers/parser/index.js
- src/workers/parser/tests/framework.spec.js
- src/workers/parser/worker.js
> Set up logic to allow checking for frameworks

- src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
- src/components/QuickOpenModal.js
- src/components/shared/ResultList.js
- src/components/shared/SearchInput.js
- src/components/shared/tests/__snapshots__/ResultList.spec.js.snap
- src/components/shared/tests/__snapshots__/SearchInput.spec.js.snap
- src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
- src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
Associated Issue: #4071 
Test Plan
Original pull request authors used ChromeVox for Google Chrome as our screenreader.
1. Open TodoMVC example
From debugger:
2. Command-P opens the panel
3. type in ‘js’
4. you should here the first result’s filepath
5. you should be read the next items filepath as you scroll through the result list
> Making search sources autocomplete functionality accessible.

- docs/getting-setup.md
Associated Issue: #5295 
`--inspect --debug-brk` is deprecated, so it should be replaced with `--inspect-brk`
No testing required
> [Update Doc] - Remove --debug-brk

- assets/panel/debugger.properties
- src/components/ShortcutsModal.js
Associated Issue: #4804 
* Add go to line shortcut `CtrlorCmd+:` in shortcut modal.
> Add go to line shortcut in shortcuts modal

- src/components/Editor/index.js
cmd+shift+b should toggle the cb panel without opening the bookmarks bar :)
> Toggling the conditional bp pane should not open bookmarks

- src/components/QuickOpenModal.js
- src/components/shared/Modal.js
- src/utils/result-list.js
Fixes #5284.
* Apply delay if modal has just been enabled or if query didn't change. *(although `nowEnabled` is always `false` since `prevProps.enabled` is always `true` for some reason 🤔. maybe it's the because the `Modal` is wrapped with a `Transition`)*
* modify `scrollList` to accept optional delay flag
> Fix [QuickOpenModal] initial scroll

- src/components/ProjectSearch.css
Associated Issue: #5283
Set result node in project search take full width
> Fix #5283 : Unclickable search result in project search 

- src/components/shared/Button/PaneToggle.css
Associated Issue: #5268
Fix for left side collapse pane icon
> [ToggleButton] Fix for left side collapse pane icon was blurry

- src/components/PrimaryPanes/Sources.css
- src/components/SecondaryPanes/Expressions.css
- src/components/SecondaryPanes/SecondaryPanes.css
- src/components/WelcomeBox.css
- src/components/shared/Accordion.css
- src/components/shared/Button/Close.css
- src/components/shared/SearchInput.css
- src/components/shared/Svg.css
@violasong 
@jasonLaster 
Associated Issue: #4544
* slightly darken "add watch expression" placeholder - matches search input now.
* slightly lighten welcomebox shortcut message - `var(--theme-comment)`;
* darken, override styling from https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-components/src/tree.css#L73-L79 to have the svg arrows on the right side be `var(--theme-comment)` color.
* darken the svg arrows on the left side to be the same color.
* darken the x button in the search input
* darken the magnifying glass and ellipse in the search input
* I'm not sure about the modifiers - right now they are all set to `var(--theme-body-color);` perhaps they should also be `var(--theme-comment);`
> color fixes

- docs/running-as-firefox-panel.md
I had to do a local.json file like this in order to make `yarn copy-assets` to work.
> Fix firefox.mcPath documentation.

- src/components/SecondaryPanes/Frames/Frame.js
Associated Issue: #5084 
Do `selectFrame` still on `onMouseDown`/`onKeyUp` even the frame given is selected already. To re-select the frame will trigger `selectLocation` again [1] so it will jump back to the paused line if scroll the line out of the view. If the line was within the view, then it just select the selected frame more one time.
[1] [https://github.com/devtools-html/debugger.html/blob/7985f7e5e17de7ae026b609b7e740696663c8a2b/src/actions/pause/selectFrame.js#L25](https://github.com/devtools-html/debugger.html/blob/7985f7e5e17de7ae026b609b7e740696663c8a2b/src/actions/pause/selectFrame.js#L25)
> 5084 - [CallStack] clicking the selected frame does not jump

- src/components/App.js
@jasonLaster 
Associated Issue: #4928
* add a second match listener
* listen for either one to change and trigger prop changes only when one is correctly matched.
to view the bug:
* open dev tools
* click on console
* toggle to the side
* flip to debugger
* observe that it is in horizontal layout
* if you click toggle while the debugger tab is displayed it does not do this
with this fix:
* It was tested on mozilla-central code, since with the web debugger you cannot toggle between vertical and horizontal modes.
* test by pasting this code into the appropriate spots in debugger.js and building firefox.
> correctly show vertical mode when toggling between modes

- src/components/PrimaryPanes/Outline.css
- src/components/PrimaryPanes/Outline.js
Since we're representing code in the outline, it would be sweet to have the code highlighted like the editor:
> Fix #5326 - Make outline's code look like the editor

- src/components/Editor/Tab.js
> Fix #5353 - Don't show 'close tabs to the right' context menu item when there's only one source open

- src/components/WelcomeBox.css
- src/components/WelcomeBox.js
Associated Issue: #5201
* remove the entire `.normal-layout` div, use the `.small-size-layout` type for all cases
* restyle using flexbox to fit any size layout.
* can someone please test this on windows, I find it difficult since I'm running a VM for it. Let me know if the two fonts are misaligned.
> remove unused parts of the welcome box and restyle with flexbox

- src/components/PrimaryPanes/Outline.css
This is just a nit.  The "No functions" text should display with the basic text font, not monospace.  Moving the font declaration to the list fixes this issue.
> Apply monospace font only to lists, not to 'No functions' text

- src/utils/sources-tree/utils.js
At present we can right-click the `(index)` item in the source tree and set as root directory -- that isn't ideal.  It was happening because `isDirectory` was returning `true` for `(index)`, so we should change that.
> The (index) is not a directory

- src/test/mochitest/browser_dbg-sources.js
- src/test/mochitest/head.js
Stepping backward, short of a full revert, to see the easiest way to fix this test issue.
> Remove special selector to see if tests pass on CI

- src/components/PrimaryPanes/SourcesTree.js
- src/components/PrimaryPanes/index.js
- src/reducers/ui.js
- src/utils/utils.js
Associated Issue: #5288 
* Remove unnecessary throttling of source tree
* Sets default `projectDirectoryRoot` to preference value.
* You can now set a directory root, refresh, and see the source tree default to that root
1.  Set a root directory
2.  Refresh the page
3.  Ensure that root directory is still the root of the source tree
4.  Unset root directory
5.  All resources should display
> Fix #5288 - Save directory root preference upon refresh; remove throttling

- src/components/ProjectSearch.css
- src/components/SecondaryPanes/Frames/Frame.js
Associated Issue: #5324
* removed the word-break property from `no-result-msg` css class in `ProjectSearch.css` file
* added `overflow-wrap` to break word if it exceed the parent (`max-width: 100%`)
* `hyphens: auto` to insert hyphens when word break on letters
> Issue 5324

- src/test/mochitest/browser_dbg-quick-open.js
I accidentally left a spurious timer in the test
> [QuickOpen] Remove timer from test

- src/components/SecondaryPanes/Frames/Frames.css
- src/components/SecondaryPanes/Frames/index.js
- src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap
At present it's a `<div>` but for the sake of a11y it should be a button.  I was inspired to do this because hovering over the text I saw the text cursor; I was just going to change its cursor but decided a button was best.
To test, add a few breakpoints somewhere and you should see the expand/collapse button.  Should look the same as before.
> Change 'Expand/Collapse' Rows element to <button>

- src/components/PrimaryPanes/SourcesTree.js
- src/test/mochitest/browser_dbg-asm.js
- src/test/mochitest/browser_dbg-sources.js
- src/test/mochitest/head.js
Associated Issue: #5358 
* Since clicking the entire directory node is meant to toggle its expanded state, the arrow `onClick` should be irrelevant
* The functionality was broken in (https://github.com/devtools-html/debugger.html/commit/d7d1bae3374f45deca7203753e9646a8d53ac8b0), not with the reps upgrade.
- Click the different directories, ensure they open and close properly.
- Navigate directories and sources with keyboard
> Fix #5358 - SourcesTree directory focus/highlight

- src/components/Editor/SearchBar.js
- src/components/Editor/tests/SearchBar.spec.js
- src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
- src/components/ProjectSearch.js
- src/components/QuickOpenModal.js
- src/components/shared/SearchInput.js
- src/components/shared/tests/SearchInput.spec.js
- src/components/shared/tests/__snapshots__/SearchInput.spec.js.snap
- src/components/tests/ProjectSearch.spec.js
- src/components/tests/QuickOpenModal.spec.js
- src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
- src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
Associated Issue: #5157 
Gist:
The error emoji should appear only when there is an actual error.  This creates two situations:
a.) where we are searching for a line number - in this case anything but a number should trigger the error emoji and
b.) where we are searching for text. In this case the emoji should only trigger if there is a search query AND the result count is 0.
p.s. The case of an @ or # is already handled well, so no need to address it
Vid:
> Makes error emoji behave sensibly

- src/actions/preview.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-preview-module.js
- src/test/mochitest/browser_dbg-preview-source-maps.js
- src/test/mochitest/browser_dbg-preview.js
- src/test/mochitest/examples/doc-on-load.html
- src/test/mochitest/examples/top-level.js
- src/test/mochitest/head.js
- Previously we assumed files would always have one function if we wanted to preview them.
- now we check for atleast one identifier, which is more general.
> Fix previewing a file w/ no functions

- src/components/App.js
Associated Issue: #5342 
* combine renderHorizontalLayout and renderVerticalLayout methods into one.
* change the sizes of the panels
in horizontal mode: 
* primary panel is 250px wide 
* secondary panel is 300px wide
in vertical mode:
* primary panel is 150px wide
* secondary panel is 400px tall
This is in conjunction with a change necessary to devtools-splitter component.
PR: https://github.com/devtools-html/devtools-core/pull/930
> reduce to one layout type and rearrange sizes of panels

- src/components/PrimaryPanes/index.js
These aren't used anymore, thanks to:
```
{selectedTab === "sources" ? <SourcesTree /> : <Outline />}
```
https://github.com/devtools-html/debugger.html/commit/22dd6f73257bee91a2c2372c03395937b9737ea3
> Remove functions we no longer use

- src/components/Editor/EditorMenu.js
- src/components/Editor/Tab.js
The context menu's "Copy Source URI" menu item for pretty tabs is outputting the `:formatted` URL; let's remote that internal `:formatted` signifier from the source.
> Ensure correct URL copied from tab context menu

- src/components/ProjectSearch.js
- src/components/tests/ProjectSearch.spec.js
- src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
Associated Issue: #5278
* Show loading message while results are fetched
* Add test for loading
- Open some large website 
- Do text search
- See if `Loading` is displayed while search is going on
Follow the gif please
> Bring back loading message to project text search

- src/actions/preview.js
- src/test/mochitest/browser_dbg-chrome-create.js
- src/test/mochitest/browser_dbg-chrome-debugging.js
Needed for release 16
Sync changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1434374
> Sync Bug 1434374 - use ChromeUtils.import instead Cu.import

- src/components/shared/Svg.css
Associated Issue: #2545
* upped the opacity, for light theme, on the angular and webpack icons.
* change the color to --theme-comment for the JS icon (also affected , TypeScript, coffeescript, react)
* I did not make the file or folder icons bolder, once the color matched with the other icons I don't think they look too soft.
before:
after:
webpack before:
after:
> change svg colors

- package.json
Associated Issue: #5418
Fixes error messages while running yarn scripts.
Before fix example:
After fix example:
> Fixes yarn warnings

- src/components/Editor/ConditionalPanel.css
- src/components/Editor/ConditionalPanel.js
- src/components/Editor/Editor.css
Associated Issue: #5302
* Reverted min-width: 0 for CodeMirror-sizer that modified the codemirror's fundamental behaviour, hiding the rightmost columns.
* Removed close button which was aligned with the previously moving code-mirror-sizer as it was not needed since the close conditional breakpoint panel action is also invoked onBlur.
* Switched CodeMirror-linewidget overflow to hidden to prevent infinite horizontal scrolling when repositioning the conditional breakpoint panel (when the conditional breakpoint panel is open).
Before, as can be seen in the gif below, the rightmost columns are unable to be seen when horizontally scrolling to the right.
After, as can be seen in the gif below, the rightmost columns are now accessible when scrolling horizontally to the right.
> Show rightmost columns of the editor.

- src/components/QuickOpenModal.js
Associated Issue: ##4488
* Small fix for a bug with fuzzy match, so now when you type '@' results are shown, while still providing highlighting on every character after the modifier
Before
After
> [QuickOpen] fix for fuzzymatch

- src/test/mochitest/browser_dbg-preview-module.js
- src/test/mochitest/browser_dbg-quick-open.js
- src/workers/parser/utils/ast.js
this reduces the parser worker bundle from 60K to 54K
dropping babel-traverse will bring us down to 30K...
> Use babel7 imports

- package.json
This reverts commit 8b930f56f7460000f06090f1324e5f86443586a0.
For some reason we need the dashes so that `yarn mochih dbg-sources` only runs the sources tests
> Revert "Fixes yarn warnings (#5419)"

- src/components/PrimaryPanes/Sources.css
In #5269, we introduced an override for non-expandable nodes on the Tree component,
since we don't use the provided arrow in the project.
But, by doing that, we introduced a regression in the ObjectInspector indent,
since it also uses the Tree component.
Here we add more specificity to the overriding rule so we don't target ObjectInspector anymore.
> Fix ObjectInspector indent issue.

- src/actions/ui.js
- src/components/Editor/EditorMenu.js
- src/components/Editor/Tab.js
"Reveal in Tree" context menu items should be globally available regardless of pretty or not.
> Allow 'Reveal in Tree' for pretty tabs

- src/components/PrimaryPanes/SourcesTree.js
So this has been really bugging me, had to fix it.
At present, if you open a pretty print tab (which now happens automagically when selecting a source from tree), the file is no longer highlighted in the tree.  This is because we were comparing sources; since PP and Original are different sources, and the pretty print URL was requested to highlight, but doesn't exit in the tree, nothing would be highlighted.
Additionally, I tried using an additional check:
```js
!selectedSource || selectedSource.get("url") != nextProps.selectedSource.get("url")
```
... but if you clicked on the tab you were already looking at, the highlight would go away.
In the end, I get why we did the checks we did but they have side effects.  I think simplifying this highlight check will do us wonders!
> Ensure the source tree highlights the correct item, regardless of pretty or original print

- src/actions/sources/newSources.js
- src/test/mochitest/browser_dbg-sourcemaps-reload.js
Associated Issue: #1661
Reliant on https://github.com/devtools-html/devtools-core/pull/921 so `fetchSourceMap` properly throws error
*  Started clearing the sourceMapURL on fail to load source maps
* Added unit test to test the above
Setup to get a source with a source map that fails on load:
$ npm install
$ cd authorization_code
$ node app.js
To test the patch
Before:
After:
> [WIP] Clear the sourceMapURL on fail to load source maps in order to enable pretty printing

- src/actions/pause/commands.js
- src/actions/tests/pause.spec.js
currently we miss the opportunity to use our await stepping if we're paused at `await <here>foo()` this fixes that by updating the regexy check
> Fix stepping w/ await

- src/utils/prefs.js
I noticed in about:config that i couldnt reset the directory root. Turns out that the prefhelper was pointing to the wrong pref field
> Fix project directory root

- assets/panel/prefs.js
1. Original scopes is plenty fast
2. I'm a bit disappointed with module dependencies, which won't be mapped until apps upgrade babel...
3. I'm thrilled with how much cleaner scopes are!
> Enable original scopes in nightly

- src/components/PrimaryPanes/SourcesTree.js
For some reason this commit breaks the last test in dbg-sources:
```js
// Make sure new sources appear in the list.
ContentTask.spawn(gBrowser.selectedBrowser, null, function() {
const script = content.document.createElement("script");
script.src = "math.min.js";
content.document.body.appendChild(script);
});
await waitForSourceCount(dbg, 9);
is(
getLabel(dbg, 7),
"math.min.js",
"math.min.js - The dynamic script exists"
);
```
While this makes absolutely no sense to me as to why this test could time out, the problem started with this commit and reverting will hopefully turn the candle green again.
> Revert "Ensure the source tree highlights the correct item, regardless of pretty or original print (#5455)"

- src/components/QuickOpenModal.js
Associated Issue: #5373
STR:
- press `ctrl+;`
- remove character
- type `?`
- notice result count = 3
- type `[space]`
ER:
- suggestions show up immediately after typing `?`
AR:
- suggestions require `? ` being typed to show up
> Fixes ? in QOM needing a space to show results

- .vscode/settings.json
- src/components/SecondaryPanes/Frames/tests/Frames.spec.js
- src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap
Associated Issue: #5150 
* Increased test coverage of existing framework grouping functionality before I change it. More specifically, I added a snapshot test for the Webpack edge case.
* Little change to vscode config for peace of mind
> [CallStack] More test coverage for framework grouping

- src/components/QuickOpenModal.js
If you do `Command+P`, the type `@`, then use your arrow keys, you get a `items[selectedIndex] is undefined` error.  Let's prevent that.
> Prevent items[selectedIndex] error

- src/components/SecondaryPanes/index.js
Alternative to PR 5391.
* Only show call stack or scope panes if there are frames on the stack.
> Don't show scopes/frames panes if there are no frames.

- assets/panel/prefs.js
Disabling Original Scopes for a couple of reasons
- it is throwing errors 
- it does not have a clear way to see the generated scopes
- it does not show generated scopes if it fails to find mappings.
> Revert "Enable original scopes in nightly (#5492)"

- src/actions/pause/resumed.js
- src/reducers/pause.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-pause-on-navigate.js
- src/test/mochitest/examples/doc-scripts-debugger.html
- src/test/mochitest/head.js
Fixes #5509
The issue was that we were only clearing the pause state when the debugger would fire a command like step or resume. Another time we resume is when we navigate. In this case there is a navigate event and resumed event. We should also make sure we clear the pause state when we were resumed by the server.
> Fix re-evaluate on resume

- src/workers/parser/getSymbols.js
- src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
- src/workers/parser/tests/fixtures/flow.js
- src/workers/parser/tests/getSymbols.spec.js
Associated Issue: #5482 
* Exclude identifier from symbols if it's a type annotation
> Exclude flow annotations from symbol identifiers

- src/components/PrimaryPanes/SourcesTree.js
- src/utils/source.js
More updates are needed to make the source tree behave but this should be fairly easy:  don't try to highlight pretty-printed `:formatted` addresses that don't exist in the tree.  Instead highlight its original counterpart.
> Highlight original source for sources tree

- assets/panel/debugger.properties
- src/components/PrimaryPanes/Outline.js
Associated Issue: #5266 
'No file selected' message is displayed in the Outline tab when there is no source selected.
> Display message to indicate no selected source in Outline tab (#5266)

- src/components/SecondaryPanes/CommandBar.css
- src/components/shared/Button/CommandBarButton.css
Associated Issue: #5534
* Changed the flexbox alignment as it was preventing buttons from reaching full height and has no visible effect on icons being centered
* Also removed the margin-inline-end property as it was separating the buttons from one another on hover, if that is the intended effect while keeping the button height full on hover, I can put it back :)
> Give command bar buttons full background on hover

- src/actions/types.js
- src/components/Editor/Tab.js
- src/reducers/ast.js
- src/utils/tabs.js
Associated Issue: #4773
* remove `sourceMetaData` which uses the selectedSource
* added a `getMetaData` function which would take the current source id
> fix tabs using the selected source

- src/utils/editor/create-editor.js
- src/utils/editor/tests/__snapshots__/create-editor.spec.js.snap
Associated Issue: #5366 
By adding the "Ctrl-F" key override we no longer see the double search box issue.
> Fix #5366 - Prevent multiple search boxes from opening on Windows

- src/workers/parser/getSymbols.js
#5557 
Removes last reference to babel-types. This saves 200KB
> [Parser] Remove reference to babel-types

- src/actions/sources/tests/__snapshots__/prettyPrint.spec.js.snap
- src/reducers/sources.js
> [Sources] Use Immutable records

- src/components/QuickOpenModal.js
Associated Issue: #5428
- Removes sad face when using source+goto queries in QOM search
- handles source goto queries
Vid:
> Removes sad face when source+goto

- webpack-loaders/rewrite-lodash-imports.js
- webpack.config.js
The changes here allow to use the vendored lodash for all lodash imports. It rewrites all the require("lodash/foo") to require("lodash").foo, which allows to leverage our existing external rule for lodash. 
On top of that we import lodash via importScript ([example](https://searchfox.org/mozilla-central/rev/61d400da1c692453c2dc2c1cf37b616ce13dea5b/devtools/client/shared/widgets/GraphsWorker.js#11)) as a Banner inside of the worker bundles.
On my computer the size of the bundles evolve as follows:
- debugger.js: 1 656 738 -> 1 612 925 (-40k)
- parser-worker.js: 1 529 483 -> 1 361 640 (-160k)
- search-worker.js: 22 600 -> 13 517 (-10k)
Overall this leads to a 200k win in the bundle size here.
> Externalize lodash

- assets/panel/debugger.properties
- assets/panel/prefs.js
- src/components/PrimaryPanes/Outline.css
- src/components/PrimaryPanes/Outline.js
- src/components/PrimaryPanes/index.js
- src/components/tests/__snapshots__/Outline.spec.js.snap
- src/test/mochitest/browser_dbg-outline.js
- src/utils/prefs.js
I find the Outline pane much easier to use when the functions are in alphabetical order.  This PR provides a place for discussion about a feature for alphabetizing and restoring original order:
> Provide a method for Alphabetizing the outline functions and classes

- src/components/Editor/EditorMenu.js
- src/components/Editor/GutterMenu.js
- src/components/SecondaryPanes/Breakpoints.js
- src/components/SecondaryPanes/Expressions.js
Associated Issue: #5589 
It seems that react 16 has a new useful warning about using shouldComponentUpdate inside a PureComponent.
> Fix warning about PureComponent & shouldComponentUpdate

- src/components/App.js
- src/components/Editor/SearchBar.js
- src/components/Editor/index.js
- src/components/ProjectSearch.js
- src/components/SecondaryPanes/CommandBar.js
- src/components/SecondaryPanes/index.js
- src/components/shared/Modal.js
Associated Issue: #5587 
Reverts #5579  as it it not possible to statically type context
> Revert using Flow to type context

- src/components/SecondaryPanes/Expressions.css
- src/components/SecondaryPanes/Expressions.js
- src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
Associated Issue: 5500
* Change in Expressions.css: onHover background-color of expression-container changes to blue( --theme-selection-background-hover). Earlier it used change only for expression text.
* Change in Expressions.js: Add doubleClick listener to expression container instead of expression text. 
> Bugfix watch expression hover

- src/actions/pause/continueToHere.js
- src/actions/preview.js
- src/components/Editor/EditorMenu.js
- src/components/Editor/GutterMenu.js
- src/components/SecondaryPanes/CommandBar.css
- src/components/SecondaryPanes/CommandBar.js
* groups similar stepping buttons (play, step over, step in/out)
* adds reverse continue to here
* it does not have isRewinding ui state
* this should not affect the regular UI at all
> Time travel ui tweaks

- src/test/mochitest/browser_dbg-babel-scopes.js
Synchronizing changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1440102 
I haven't changed the browser.ini in the sync since the previous m-c change (skip on win + ccov) had not been synchronized here.
> Update timeout in browser_dbg-babel.js (sync m-c bug 1440102)

- src/components/ShortcutsModal.css
This is super minor but for consistency we should remove the text cursor upon hover since this isn't text anyone interacts with (i.e. copies)
> Change shortcuts modal cursor to default for consistency

- src/components/SecondaryPanes/CommandBar.js
Associated Issue: #5456
* Disabled forward/backward stepping when history is of size 1 in the debugger's command bar. 
Example used: Debugger Statements
> Disabled forward/backward stepping for a single history item

- .github/PULL_REQUEST_TEMPLATE
> Change PR template for issue clarification

- assets/panel/prefs.js
- src/actions/sources/newSources.js
- src/reducers/sources.js
- src/utils/prefs.js
Associated Issue: #3601
Introduce "devtools.debugger.tabsBlackBoxed" pref to save the blackboxed sources and restore blackboxed states while receiving new sources.
> 3601 - [blackbox] sources should be persisted

- src/components/QuickOpenModal.css
- src/components/QuickOpenModal.js
Fixes Issue: #5584
Replaces `<strong>` in highlights with `<mark>`
> Changes highlight from <strong> to <mark>

- src/components/shared/ResultList.css
Fixes Issue: #5034 
* changed background-color of selected item to be same as background when doing for eg. function search
| Firebug | Dark | Light |
| --- | --- | --- |
|![screenshot from 2018-03-11 23-27-36](https://user-images.githubusercontent.com/4532171/37256750-07e1957e-2585-11e8-95eb-85a7dc93c3fb.png)|![screenshot from 2018-03-11 23-28-09](https://user-images.githubusercontent.com/4532171/37256751-087c8af2-2585-11e8-82bb-d65d98733e20.png)|![screenshot from 2018-03-11 23-28-49](https://user-images.githubusercontent.com/4532171/37256752-0a65ae66-2585-11e8-9907-168dbfa946a9.png)|
> Fix issue: #5034 - change colors for selected result item-big

- src/actions/sources/loadSourceText.js
- src/actions/sources/newSources.js
- src/actions/sources/tests/newSources.spec.js
- src/reducers/sources.js
Fixes Issue: #5639
This PR #5296 started updating every source that did not have a generatedSourceURL, the effect was that sources would go from being loaded to unloaded. This fixes that and cleans up loadSourceMap a bit.
Another nice effect is that it cleaned up our redux actions quite a bit
Given that this was a race condition it is difficult to have a mochitest for it. I'll investigate some options tomorrow.
> Fix permanent loading state

- src/components/PrimaryPanes/Outline.css
The "Sort by name" button to alphabetize the outline isn't visible in the dark theme because the button text is dark.  This fixes the issue:
> Ensure sort by name button is visible in dark theme

- src/actions/preview.js
- src/actions/types.js
- src/components/PrimaryPanes/Outline.js
- src/test/mochitest/browser_dbg-pretty-print-console.js
- src/test/mochitest/browser_dbg-sourcemaps2.js
- src/types.js
- src/utils/ast.js
- src/utils/breakpoint/astBreakpointLocation.js
- src/utils/breakpoint/tests/astBreakpointLocation.spec.js
- src/utils/editor/source-documents.js
- src/utils/tests/ast.spec.js
- src/utils/tests/function.spec.js
- src/workers/parser/findOutOfScopeLocations.js
- src/workers/parser/frameworks.js
- src/workers/parser/getSymbols.js
- src/workers/parser/index.js
- src/workers/parser/types.js
- src/workers/parser/utils/formatSymbols.js
- src/workers/parser/worker.js
* adds flow types for utils/ast
* exports types from parser/index
* fixes a recursion issue caused by defining types in getSymbols
> Lock down parser flow type exports

- src/components/PrimaryPanes/Outline.css
- src/components/PrimaryPanes/Outline.js
At present, if no source is selected, the Outline tab shows `Loading...`, which is not good.  The formatting was also off, so I fixed that.
> Fix message and formatting of Outline when no functions

- .travis.yml
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-chrome-create.js
- src/test/mochitest/head.js
+ Backport Bug 1442312 - Stop using deprecated-sync-thenables in DebuggerServerConnection._queueResponse
+ Backport - Bug 1440321 - Convert Task.jsm to async/await in devtools/client. r=jryans
+ Add toolbox test
+ backport browser.ini
> Backport changes from MC

- src/client/index.js
- src/utils/dbg.js
This lets us use `dbg` in the browser toolbox, which is fine because it is not a performance cost
> Allow dbg in the browser toolbox

- src/components/QuickOpenModal.js
- src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
Fixes Issue: #5623 
* Loading indicator to show only when searching up symbols, and only with a source tab selected
* update snapshot
> [QuickOpen] Fix loading for searching symbols

- src/components/App.js
- src/components/shared/VisibilityHandler.js
Added VisibilityHandler to handle the mounting and unmounting of child components of App when changing panel tabs.
Fixes Issue: #4852 -- Does not address the scrolling issue directly. The fix will unmount the child components of App when the visibility of the tab is hidden, and mount the components of App when the tab is visible. Therefore the previous position in the editor is ignored, and is reloaded to the top of the editor. 
- Addition of the VisibilityHandler from [here](https://hg.mozilla.org/mozilla-central/raw-file/tip/devtools/client/shared/components/VisibilityHandler.js). (With a slight modification to only render the children when the tab is visible.)
- Wrap the contents of the App component in the modified VisibilityHandler.
Before:
After:
Just showing how the editor is …
> Added VisibilityHandler to handle the mounting and unmounting of child components of App when changing panel tabs.

- src/actions/expressions.js
- src/actions/pause/fetchScopes.js
- src/actions/pause/mapScopes.js
- src/actions/pause/paused.js
- src/actions/preview.js
- src/actions/types.js
- src/reducers/pause.js
- src/test/mochitest/browser.ini
- src/test/mochitest/browser_dbg-babel-preview.js
- src/test/mochitest/head.js
- src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js
- src/workers/parser/index.js
- src/workers/parser/mapOriginalExpression.js
- src/workers/parser/tests/mapOriginalExpression.spec.js
- src/workers/parser/worker.js
Related Issue: #5561
* Adds expression-mapping logic to scope mappings
* Uses expression mappings to process watch and preview expressions
> Use original scope mappings to rewrite preview and watch expressions

- src/actions/sources/loadSourceText.js
- src/components/App.js
- src/components/Editor/Breakpoints.js
- src/components/Editor/DebugLine.js
- src/components/Editor/EmptyLines.js
- src/components/Editor/Footer.js
- src/components/Editor/HighlightLine.js
- src/components/Editor/Preview/index.js
- src/components/Editor/SearchBar.js
- src/components/Editor/Tab.js
- src/components/Editor/Tabs.js
- src/components/PrimaryPanes/Outline.js
- src/components/PrimaryPanes/SourcesTree.js
- src/components/QuickOpenModal.js
- src/components/SecondaryPanes/CommandBar.js
- src/reducers/sources.js
- src/reducers/types.js
- src/types.js
- src/utils/editor/source-documents.js
- src/utils/isMinified.js
- src/utils/source.js
- src/utils/sources-tree/addToTree.js
- src/utils/sources-tree/types.js
- src/utils/sources-tree/utils.js
- src/utils/tabs.js
- src/workers/pretty-print/index.js
Fixes: #5657 
* Make source record fields read-only
> Make SourceRecord fields Read-Only

- assets/panel/debugger.properties
- src/components/Editor/EditorMenu.js
- src/components/Editor/Tab.js
- src/utils/tabs.js
Fixes Issue: #5341
* Add item "Copy to clipboard" to editor context menu
* Add item "Copy to clipboard" to source tab context menu
> Enhancement add contenxt menu copy to clipboard

- src/components/PrimaryPanes/SourcesTree.js
Fixes Issue: #5658
* changing `svg` icons for multiple files into `img` tags to help with performance gains
> update file icons to use img instead of svg

- src/utils/pause/scopes/getScope.js
Now that Reps 0.21.0 landed, we can use the BLOCK node type to style scopes block.
Here's how it looks: 
Fixes #5426
> Add a proper type to  scopes Block nodes

- src/components/PrimaryPanes/Sources.css
For some reason postCSS was breaking the CSS rule in a weird way which causes
the non-expandable node to be off in the Scopes panel.
Putting the whole selector on the same line fixes the issue.
See `ENTER_KEY` and `ESC_KEY` node in the screenshot below:
> Fix Sources.css issues.

- src/actions/expressions.js
- src/components/SecondaryPanes/Expressions.js
Fixes Issue: #5204 
* Now the wrong expression is not cleaned
* The red borders now are displaying only when there is an error
> Expression syntax errors are cleared on save

- src/components/QuickOpenModal.js
Fixes Issue: #5698 
* Prevent input cursor position from changing when pressing down/up arrow key in Quick Open.
Before:
After: Up/Down arrow key no longer moves input cursor
> Fixes issue#5698

- src/actions/navigation.js
This shouldn't go in as-is, since any nav change clears the root.  Ideally we'd only do this upon hostname change.
> Revert 5740, which clears the root upon any navigation change

- src/actions/ast.js
- src/actions/tests/ast.spec.js
- src/actions/tests/helpers/threadClient.js
- src/actions/tests/preview.spec.js
- src/client/firefox/commands.js
- src/client/firefox/types.js
- src/client/index.js
- src/reducers/ast.js
- src/utils/dbg.js
- src/utils/pause/pausePoints.js
- src/workers/parser/pausePoints.js
- src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
- src/workers/parser/tests/fixtures/pause-points.js
- src/workers/parser/tests/pausePoints.spec.js
- src/workers/parser/utils/simple-path.js
Fixes #4013
1. adds a `setPausePoints` client command
2. adds a `sendPacket` helper for simple protocol calls
3. moves `formatPausePoints` to a helper so that it can be used in `dbg`
4. tweak pause points for some cases
> Send pause points to the server

- src/components/QuickOpenModal.css
Fixes Issue: #5679 
* Changed selected quick open element text be bolded white
> Issue 5679:  Quick Open - style selected matches

- src/actions/ast.js
- src/actions/breakpoints.js
- src/actions/breakpoints/addBreakpoint.js
Edited 3 files to remove possible toJS calls from actions:
- ast.js,
- breakpoints.js,
- addBreakpoint.js
Investigate: `getGeneratedLocation` uses source records, so it would be nice to remove the toJS from here as well
> Removes toJS from 3 files

- src/actions/sources/select.js
- src/actions/types.js
The `tabIndex` field is no longer needed because we use `moveTab`. I believe we could have removed it then.
> Remove tabIndex field

- src/actions/sources/select.js
- src/components/Editor/Tab.js
- src/components/Editor/Tabs.js
This PR provides a method for selecting a source without the pretty print logic dance.  This is a good first step in avoiding the side effects of pretty print.
> Add method to select a specific source or location without attempting to detect pretty print

- src/client/firefox/commands.js
- src/client/firefox/fronts-device.js
- src/client/firefox/types.js
- webpack.config.js
This is a client side workaround for fixing connection to Fennec v59, for the issue mentioned on [Bug 1443550](https://bugzilla.mozilla.org/show_bug.cgi?id=1443550)
It assumes that the root issue will be fixed after 59. We get device information and check the application type and the version. If we are on Fennec 59, we do not attempt to fetch workers.
Another possible workaround is to use Promise.race to timeout the listWorkers call after N seconds. I will submit another PR for this second approach and we can decide which one we like best.
> Avoid listing workers if connected to Fennec v59

- src/client/firefox/types.js
- yarn.lock
`listTabs` is bad for performance and should be avoided where possible.  In most
cases of interest to the debugger, a `target` is already prepared by the toolbox
with all data it would need.
The debugger doesn't actually seem to use `listTabs` currently, so we should
remove these types as well to avoid the suggestion that it's a good idea to use.
> Remove references to `listTabs` API

- src/components/QuickOpenModal.js
- src/components/shared/ResultList.css
- src/utils/quick-open.js
Fixes Issue: #5630
* Now the path is in the same line of the filename
* Added truncation to filename and path
> QuickOpen File Search rows can be quite tall

- .travis.yml
- src/test/mochitest/browser_dbg-editor-select.js
- src/test/mochitest/browser_dbg-sourcemaps.js
- src/test/mochitest/browser_dbg-stepping.js
- src/workers/parser/pausePoints.js
- src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
- src/workers/parser/tests/fixtures/pause-points.js
* fixes up two tests whose behavior changed (largely) for the better
* removes a check about adding a breakpoint w/ sliding bc pausepoints prevents users from adding bps in that spot
* added a `return foo()` check in pause points to prevent pausing at a return when there is a subsequent call
> Pause points tweaks
