firefox-devtools/debugger

src/components/SecondaryPanes/CommandBar.css
src/components/SecondaryPanes/CommandBar.js
src/components/SecondaryPanes/index.js

Associated Issue: #3719 
* Fixed width of command bar

Fix horizontal scrolling

---

src/actions/expressions.js
src/actions/tests/expressions.spec.js
src/actions/types.js
src/components/SecondaryPanes/Expressions.js
src/reducers/expressions.js

[Expressions] Remove visible field

---

docs/local-development.md

Access Keys

---

src/reducers/expressions.js

Associated Issue: #3490
omit the value field

Expression values are dropped

---

src/actions/ast.js
src/actions/tests/__snapshots__/ast.spec.js.snap
src/actions/tests/ast.spec.js
src/actions/types.js
src/components/Editor/Preview.js
src/components/Editor/Preview/Popup.css
src/components/Editor/Preview/Popup.js
src/components/Editor/Preview/index.js
src/components/Editor/index.js
src/components/Editor/tests/Editor.spec.js
src/components/Editor/tests/__snapshots__/Editor.spec.js.snap
src/components/shared/Popover.js
src/reducers/ast.js
src/reducers/sources.js
src/reducers/types.js
src/selectors.js
src/selectors/isSelectedFrameVisible.js
src/utils/editor/expression.js

Associated Issue: #3626 #3589 #3264
* Don't show loading state
* Don't show preview when selecting text
* Extract Preview logic from editor
* rename selection to preview because it was confusing

Improve preview

---

docs/local-development.md
src/actions/sources/createPrettySource.js

Fix intermittent

---

src/components/Editor/CallSites.js

I opted not to do the mapping with JSX, will be cleaner without it IMO.

Convert CallSites to JSX

---

src/components/PrimaryPanes/index.js

Convert PrimaryPanes/index to JSX

---

src/components/Editor/ConditionalPanel.js

Need to break for now but need to do some more manual testing.

Transform ConditionalPanel to JSX

---

src/components/PrimaryPanes/SourcesTree.js

Convert SourcesTree to JSX

---

src/components/SecondaryPanes/index.js

Big change but everything works locally and tests passing.

Convert SecondaryPanes/index to JSX

---

.flowconfig
src/components/SecondaryPanes/Frames/Frame.js
src/components/SecondaryPanes/Frames/Group.js
src/components/SecondaryPanes/Frames/index.js
src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.js.snap
src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.js.snap

* convert Frame, Group and Frames components to JSX
* fix usage of dom.div in TextSearch component

JSX Conversions for Frame components.

---

assets/images/Svg.js
src/components/Editor/Breakpoint.js
src/components/Editor/Footer.js
src/components/Editor/SearchBar.js
src/components/Editor/Tabs.js
src/components/Editor/tests/__snapshots__/Breakpoints.spec.js.snap
src/components/Editor/tests/__snapshots__/Editor.spec.js.snap
src/components/PrimaryPanes/SourcesTree.js
src/components/ProjectSearch/TextSearch.js
src/components/SecondaryPanes/ChromeScopes.js
src/components/SecondaryPanes/CommandBar.js
src/components/SecondaryPanes/Frames/Frame.js
src/components/SecondaryPanes/Frames/Group.js
src/components/SecondaryPanes/index.js
src/components/shared/Accordion.js
src/components/shared/Button/Close.js
src/components/shared/Button/PaneToggle.js
src/components/shared/SearchInput.js
src/components/tests/__snapshots__/SymbolModal.spec.js.snap
src/components/tests/__snapshots__/closeButton.spec.js.snap

It's nicer to use this class as JSX.  I still have some cleanup to do but must break for now.

WIP: Convert SVG icon usage to JSX

---

src/components/SecondaryPanes/Breakpoints.js

Convert Breakpoints to JSX

---

src/client/index.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-async-stepping.js
src/test/mochitest/examples/async.js
src/test/mochitest/examples/doc-async.html
src/test/mochitest/head.js

Associated Issue: #3106
* starts a test

Async stepping test

---

src/utils/parser/getEmptyLines.js
src/utils/parser/index.js
src/utils/parser/tests/__snapshots__/getEmptyLines.js.snap
src/utils/parser/tests/getEmptyLines.js
src/utils/parser/worker.js

Associated Issue: #3525 
just has the utils

Add empty line utils

---

src/actions/ast.js
src/actions/sources.js
src/actions/tests/__snapshots__/ast.spec.js.snap
src/actions/tests/ast.spec.js
src/reducers/ast.js

#3483
Cherry picks some more work from #3525

Add Empty Lines to AST reducer

---

src/components/stories/ManagedTree.js
src/components/stories/Outline.js
src/components/stories/Preview.js
src/components/stories/ResultList.js
src/components/stories/SearchInput.js
src/components/stories/TextSearch.js
src/components/stories/frames.js
src/components/stories/helpers/shortcuts.js
src/components/stories/tabs.js

Bombing on PropTypes for direction and theme, so added those to prevent annoying warnings.

Fix linting issues inside Storybook due to missing prop types

---

src/actions/sources.js
src/components/Editor/EmptyLines.css
src/components/Editor/EmptyLines.js
src/components/Editor/index.js
src/reducers/ast.js
src/test/mochitest/browser_dbg-breakpoints-reloading.js
src/test/mochitest/browser_dbg-editor-gutter.js

As @jasonLaster merged the redux piece, this PR is for the UI piece of displaying empty vs. executable lines

Display empty lines UI

---

package.json
yarn.lock

bump pretty fast

---

src/components/Editor/tests/Editor.spec.js
src/components/Editor/tests/__snapshots__/Editor.spec.js.snap

I intruduced this issue with my last PR so I thought it might be a good idea to fix it :-)

Fix Editor spec proptypes

---

flow-typed/debugger-html.js
package.json
src/actions/breakpoints/addBreakpoint.js
src/actions/tests/__snapshots__/breakpoints.spec.js.snap
src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap
src/utils/breakpoint/astBreakpointLocation.js
src/utils/breakpoint/index.js
src/utils/prefs.js

add astLocation to addBreakpoint

---

assets/panel/debugger.properties
src/components/WelcomeBox.css
src/components/WelcomeBox.js
src/utils/text.js

Associated Issue: #3830 
* change style of command and info text
* add a new shortcut
* remove "+" sign from commands
* Currently It looks like this. So I need further help.

Style Welcome Box

---

src/utils/source.js
src/utils/tests/source.spec.js

add marko syntax highlighting

---

assets/panel/debugger.properties
src/components/PrimaryPanes/index.js

* Renamed Sources View tab to Sources 
* Renamed Outline View tab to Outline

Renamed Primary Panes

---

CONTRIBUTING.md

Really excited to have David on the contributor team! His first contribution was to cleanup tab tooltips a year ago. His latest was to disable empty lines in the gutter. He's helped mentor new comers in the channel and review PRs on Github. I'm looking forward to see what comes next, now that he can click the green button :P

:bowtie: David Walsh joins contributor team

---

CONTRIBUTING.md

It's hard to say goodbye to Bryan (even in markdown), but it's exciting to welcome Harald.

:wave: Hello Harald, :cry: Goodbye Bryan

---

src/components/shared/ManagedTree.js

Just a few nits I stumbled upon

Fix nits in ManagedTree

---

src/components/ProjectSearch/TextSearch.js

Associated Issue: #3891
* Remove extra regex check
* Cleanup the match value render

Refactor match rendering

---

src/actions/ast.js

Fix preview for falsy values

---

src/utils/editor/expression.js

Associated Issue: #3824
Found another case

Disallow pipes

---

assets/panel/debugger.properties
src/actions/pause.js
src/components/Editor/GutterMenu.js
src/components/Editor/index.js
src/utils/redux/middleware/promise.js

Associated Issue: #3503 
I really don't know why but the debugger doesn't stop at the hidden breakpoint.
Maybe someone of the core team can pair up with me so I can solve this...

[WIP] Stepping: Continue to here

---

assets/panel/prefs.js
configs/development.json
configs/firefox-panel.json
src/client/firefox.js
src/utils/prefs.js

[WIP] convert from featureFlag to prefs system

---

src/components/Editor/Editor.css
src/components/WelcomeBox.css

we should have removed this css earlier.

remove unecessary css

---

src/utils/prefs.js

Add missing semicolon in prefs.js

---

src/components/WelcomeBox.js

WelcomeBox: make shortcuts clickable

---

src/components/PrimaryPanes/Outline.js
src/components/PrimaryPanes/index.js

small prettier fixes from the outline work

prettier fixes

---

src/actions/navigation.js
src/utils/parser/index.js
src/utils/parser/sources.js
src/utils/parser/tests/sources.spec.js
src/utils/parser/worker.js

Associated Issue: Fixes #3953
* Adds sources cache on the parser worker side

Use a source cache in parser worker.

---

src/actions/breakpoints.js

We previously had better protection in the components against these bad cases. Now that our call sites will pass anything through, lets just bail early

gracefully support bad bp cases

---

.gitignore
src/components/SecondaryPanes/Frames/WhyPaused.css

Associated Issue: #3316 
* change color of component part from one theme color to another theme color
* add vim temp file to gitignore
Run yarn test-all

Us#3361 excepion details in dark theme

---

flow-typed/debugger-html.js
package.json
src/actions/sources.js
src/actions/tests/__snapshots__/breakpoints.spec.js.snap
src/client/index.js
src/utils/source-maps.js
yarn.lock

Associated Issue: #3399
This pulls in the update for symmetric bps in the service worker. It also adds some of the undefined logic for the debugger now that it's not in the worker.
test in perf.html

Support symmetric BPs

---

src/components/SecondaryPanes/Frames/Frames.css
src/components/shared/ResultList.css

Small photon tweaks

---

assets/panel/prefs.js
src/utils/prefs.js

small clean up for the project search flag

fix project search flag

---

assets/panel/prefs.js
src/test/mochitest/browser.ini

now that we have an uptodate version of MC, we can sync prefs and browser.ini w/ mc.

sync changes w/ mc

---

src/test/mochitest/browser_dbg-expressions.js

test watch expressions w/ an active debuggee

---

src/components/Editor/index.js

Associated Issue: #4063 
I only did manual testing. Works really nice and I think it is a huge enhancement for users :-)

Alt click -> continue to here

---

package.json
yarn.lock

Associated Issue: #3468 
upgrades codemirror. We can add ops later

Upgrade CodeMirror

---

CONTRIBUTING.md

I'd like to be the first to welcome Martin to the team!
Martin has helped in almost every capacity: code health, new features, windows compat, bug fixes. More importantly, he's been a friendly voice in the community. He's helped new comers feel welcome and has also helped us triage and keep the bug list actionable. 
Cheers 🍺

Add Martin to the Core Team :wave:

---

src/components/SecondaryPanes/ChromeScopes.js

Just a few nits where we don't need {}

Cleanup with ChromeScopes

---

src/components/shared/ManagedTree.js

move expanded to the constructor

---

src/components/SecondaryPanes/CommandBar.js

Fix tier 3 OS keyboard shortcuts

---

.travis.yml
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-pretty-print-console.js

This is a mochitest that landed in https://bugzilla.mozilla.org/show_bug.cgi?id=952127

Backport mochitest from bug 952127

---

src/components/Editor/Editor.css
src/components/Editor/index.js

Associated Issue: #4111
This fixes an issues where we would try and set the text before the editor was instantiated
.

Protect against a missing editor

---

assets/panel/debugger.properties
src/components/SecondaryPanes/Frames/tests/Frames.js~
src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.js.snap
src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
src/components/tests/__snapshots__/SymbolModal.spec.js.snap
src/test/mochitest/browser_dbg-call-stack.js

Associated Issue: #3904 
* Consistent text case; capitalized first word.

correct text case

---

flow-typed/debugger-html.js
src/actions/expressions.js
src/actions/pause.js
src/actions/tests/expressions.spec.js
src/components/SecondaryPanes/Expressions.js
src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
src/reducers/pause.js
src/utils/expressions.js
src/utils/tests/expressions.spec.js

While I was looking at Expressions I found somethings to tweak:
* Errors should be shown
* Reference Errors should be `(unavailable)`

Expressions tweaks

---

assets/panel/debugger.properties

just updated the properties ids

fixed localization ids

---

src/components/Editor/Preview/Popup.js

Preview: Show numbers inside a tooltip

---

src/actions/tests/pending-breakpoints.spec.js

* Fix the failing pending-breakpoints tests

fix the failing pending breakpoints tests

---

src/components/SecondaryPanes/Scopes.js

* Change SecondaryPanes/Scopes from PropTypes to Flow Props

Switch Scopes form PropTypes to Flow Props

---

src/actions/breakpoints.js
src/actions/tests/pending-breakpoints.spec.js

Associated Issue: #4173
* Cleanup breakpoint actions options

Cleanup addbreakpoints

---

src/components/Editor/Breakpoint.js
src/components/Editor/Breakpoints.js
src/components/Editor/Footer.js

* Fix flow-types error Footer
* Fix flow-types error Breakpoint, Breakpoints

Flow types

---

assets/panel/debugger.properties
docs/local-development.md
src/components/Editor/EditorMenu.js
src/components/Editor/Tabs.js
src/components/PrimaryPanes/SourcesTree.js
src/components/SecondaryPanes/Frames/FrameMenu.js
src/components/SecondaryPanes/Frames/tests/FrameMenu.js

Associated Issue: #4043 
* change localization note of `copySourceUrl` and `errorLoadingText2`

Fix #4043 - Change localization note and errorLoadingText

---

src/actions/ui.js
src/components/PrimaryPanes/SourcesTree.js
src/components/PrimaryPanes/index.js
src/components/SecondaryPanes/Breakpoints.js

Fix linting warnings

---

assets/module-manifest.json
assets/panel/debugger.properties
package.json
src/actions/ui.js
src/components/Editor/EditorMenu.js
src/components/Editor/Footer.js
src/components/Editor/index.js
src/components/PrimaryPanes/SourcesTree.js
src/components/PrimaryPanes/index.js
src/components/SecondaryPanes/Breakpoints.js
src/test/mochitest/browser.ini
src/utils/editor/index.js
src/utils/sources-tree/tests/utils.spec.js
src/utils/sources-tree/utils.js
yarn.lock

just another bundle. notably nothing changed here :)
https://bugzilla.mozilla.org/show_bug.cgi?id=1403736

9-27 update

---

src/components/App.js
src/components/ProjectSearch/ProjectSearch.css
src/components/ShortcutsModal.css
src/components/ShortcutsModal.js
src/components/shared/Modal.css
src/utils/text.js

Associated Issue: #4122
Tiny style changes suggested by @violasong

Shortcuts style tweak

---

package.json
src/components/shared/ManagedTree.css
src/components/shared/ManagedTree.js
yarn.lock

This upgrades our version of the tree component, which will be a big perf win for scrolling

(WIP) Upgrade tree component

---

package.json
src/components/shared/ManagedTree.css
src/components/shared/ManagedTree.js
yarn.lock

This reverts the new tree component.
The tree component references a ref from a child component... and errors

Revert "Upgrade tree component (#4215)"

---

src/components/shared/Popover.js

Switch Popover PropTypes to flow props
- `yarn test`

Switch Popover PropTypes to flow props

---

README.md

give a bit of info of how to report vulnerabilities

add line about vulnerabilities

---

bin/copy-assets.js
bin/writeReadme.js

Associated Issue: will help with bisecting

Adds readme with debugger.html version information to mc.

---

src/components/App.js

Associated Issue: #4213
* Added keyboard shortcut

Add Command Slash Shortcut

---

src/utils/tests/DevToolsUtils.spec.js

Associated Issue: #4270
* Add tests for functions in `src/utils/DevToolsUtils.js`

[#4270] Add tests for DevToolsUtils

---

src/utils/editor/source-documents.js

Getting hit with this every commit so I may as well submit it.

Fixing source-documents linting error

---

src/components/SecondaryPanes/Breakpoints.js

Started this before realizing that @nyrosmith had started it :/ .  
Anyways, this was my solution.  Hoping @nyrosmith has something prettier coming :)

Fix 4261 - Sort breakpoints by line number

---

src/selectors.js

Associated Issue: #4267
Written in the related issue

Remove object.assign from selectors.js close #4267

---

src/test/mochitest/browser_dbg-wasm-sourcemaps.js

Associated Issue: intermittent failures for wasm-sourcemaps mochitest

Attempt to reduce intermittent failures for wasm-sourcemaps test.

---

src/components/PrimaryPanes/Sources.css
src/components/PrimaryPanes/SourcesTree.js

Associated Issue: #4253 
* Add left padding on Source Tree. 
* Add padding top on Source Tree.
Tested on Firefox.

Fix Source Tree padding left

---

bin/dev-server.js
package.json
webpack.config.js
yarn.lock

This lands the new launchpad w/ support for MC-CSS files, variables, and SVGs. It also provides a path for us to switch to CSS defined SVGS

Upgrade Launchpad

---

.gitignore
bin/copy-assets.js
package.json
postcss.config.js
src/components/PrimaryPanes/Sources.css
src/components/PrimaryPanes/SourcesTree.js
src/components/shared/Svg.css
yarn.lock

Associated Issue: #4350
Switch to the tree arrow to a CSS SVG

Update sources arrow

---

src/utils/sources-tree/tests/treeOrder.spec.js

Added the test jlast asked for the in the fix browser toolbox pr

add getDomain tst

---

CONTRIBUTING.md
assets/dictionary.txt
docs/maintainer.md

- reference steve's article
- outline the steps for making a bug actionable

Improve triaging docs

---

src/components/shared/Popover.js

Associated Issue: #4362
* removed left margin offset
http://g.recordit.co/fFtkzFhjVm.gif

Fixes mis-aligned tooltip

---

src/actions/ast.js
src/actions/tests/__snapshots__/ast.spec.js.snap
src/actions/types.js
src/components/Editor/Preview/Popup.css
src/components/Editor/Preview/Popup.js
src/components/Editor/Preview/index.js
src/reducers/ast.js

Associated Issue: #4287
Show the react component display name in the preview

React preview display name

---

assets/panel/debugger.properties
src/components/Editor/EditorMenu.js
src/components/Editor/GutterMenu.js

Associated Issue: #4345
* replaced hard-coded access keys with a reference to debugger.properties
* added access keys if they did not already exist

Adds L10N for  previously hardcoded keybindings

---

.gitignore
assets/dictionary.txt
docs/getting-setup.md
docs/local-development.md
docs/most-common-issues.md

docs most-common-issues

---

.babelrc
bin/prettier.js
package.json
src/components/ProjectSearch/TextSearch.js
yarn.lock

* preset-env
* drop asyncToGenerator
* run prettier on install. ✋

Cleanup babel

---

flow-typed/debugger-html.js
src/components/SecondaryPanes/Scopes.js
src/utils/scopes.js

Associated Issue: FIXME comments at debugger-html.js

Adds flow types to the Scope declaration.

---

.travis.yml
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-browser-content-toolbox.js
src/test/mochitest/head.js

* synchronize new test from [Bug 1407426](https://bugzilla.mozilla.org/show_bug.cgi?id=1407426)
* update m-c commit in travis yml to retrieve some changes necessary to run the new test

Synchronize smoke test for browser content toolbox from m-c

---

src/components/Editor/ConditionalPanel.js

Associated Issue: #4422
* Added clickhandler to listen to changes in box
Clicked a lot
http://g.recordit.co/iXs7CldKz5.gif

Keeps focus on input field

---

bin/ci/run-tests.sh
bin/prettier.js
package.json
src/components/App.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-layout-changes.js
src/test/mochitest/browser_dbg-reload.js

Associated Issue: #3389
* switch layouts
* makes mochii interactive (so we can do re-runs)

add layout test

---

src/actions/ast.js
src/actions/pause.js
src/actions/sources.js
src/actions/tests/ast.spec.js
src/actions/tests/sources.spec.js
src/actions/types.js
src/components/Editor/DebugLine.js
src/components/Editor/index.js
src/components/ProjectSearch/TextSearch.js
src/reducers/sources.js
src/test/mochitest/browser_dbg-editor-highlight.js
src/test/mochitest/head.js
src/utils/editor/index.js

Associated Issue: #3892
* Scroll to does not seems to be working
* Tests are breaking for `getOutOfScopeLocations`
I also need to clean some things up.
Coming soon...
* Search sources still opens source correctly
* Search files still opens source correctly
* Sources tree still opens source correctly
* Searching by files opens to line and column

Scroll to column

---

assets/images/Svg.js
assets/images/marko.svg
src/utils/frame.js

Associated Issue: #2980 
* Support framework frames for Marko

Support framework frames for Marko

---

assets/images/Svg.js
assets/images/nextjs.svg
src/utils/frame.js

Associated Issue: #2980 
* Add Next.js support to Framework Frames

Add Next.js to framework frames

---

src/components/Editor/Editor.css
src/components/Editor/Footer.css

Associated Issue: #4421 
* changed some CSS files.

Fix footer background length in dark theme

---

package.json
yarn.lock

we get actions in the logs
and we also get a try catch to prevent bad issues

bump mochi

---

src/components/Editor/ConditionalPanel.js

Close ConditionalPanel on blur

---

src/workers/parser/tests/contains.spec.js
src/workers/parser/utils/contains.js

4369-[Previews] some lines are incorrectly marked as out of scope

---

.travis.yml

not sure if this is right
https://docs.travis-ci.com/user/notifications/

notify on failure

---

src/components/ProjectSearch/TextSearch.js

Associated Issue: #4505
Converted file SVG to an image.

Fixes #4505 - Convert file SVG to image

---

assets/panel/debugger.properties
src/components/Editor/EditorMenu.js

Fix l10n accesskey/label

---

src/components/Editor/Preview/index.js

Associated Issue: #3822
* Removal of listeners on componentWillUnmount
Tested the memory footprint by repeatedly opening and closing a tab 
Shows memory consumption before the change, and with 2 variations of changes implemented (the fix contains variation 2). 
http://prntscr.com/gyziln

removes declared hooks on componentWillUnmount

---

src/components/PrimaryPanes/SourcesTree.js

Associated Issue: #4259
* add domain class

Style debuggee domain

---

src/utils/source.js
src/utils/tests/source.spec.js

Remove query strings when displaying call stack frames

---

src/utils/tests/assert.js

Associated Issue: #4545 
* added tests for `src/utils/assert.js`
* compare test suite results before / after results
* eliminated any new warnings or errors reported by the git commit hooks

[#4545] Add tests for src/utils/assert.js

---

src/utils/tests/log.spec.js

Create tests for `src/utils/log.js`.

Add tests for src/utils/log.js

---

src/components/ProjectSearch/TextSearch.js
src/components/ProjectSearch/tests/TextSearch.js
src/components/ProjectSearch/tests/__snapshots__/TextSearch.js.snap

Associated Issue: #4506 
* moved variables to state to be able to assign initial state and update
* update based on boolean updateCount and difference of current state from previous state
tested by performing searches
http://g.recordit.co/bEQ4fkre8s.gif

Displays result count only after initiating search

---

src/components/Editor/index.js

Associated Issue: #4435
- Improve flow type definitions
- use new action for traversing

Use new redux action in editor

---

src/components/SecondaryPanes/Scopes.js
src/reducers/pause.js
src/test/mochitest/browser_dbg-breaking.js
src/test/mochitest/browser_dbg-debugger-buttons.js
src/test/mochitest/browser_dbg-expressions-error.js
src/test/mochitest/browser_dbg-scopes-mutations.js
src/test/mochitest/browser_dbg-sourcemaps.js
src/test/mochitest/browser_dbg-sourcemaps2.js
src/test/mochitest/head.js

lets make waitForPaused smarter so that it knows to wait for the scopes and objects to be fetched.

rethink waitForPaused

---

src/test/tests-setup.js

otherwise we get nothing in this case

show better error messages in jest

---

src/client/index.js
src/utils/timings.js

We can add this to the bottom of mochitests, we can also use it in other ways too :)

Add timing data

---

src/actions/pause/commands.js
src/actions/tests/pause.spec.js
src/actions/types.js
src/components/SecondaryPanes/Scopes.js
src/reducers/pause.js
src/test/mochitest/browser_dbg-breaking.js
src/test/mochitest/browser_dbg-debugger-buttons.js
src/test/mochitest/browser_dbg-expressions-error.js
src/test/mochitest/browser_dbg-scopes-mutations.js
src/test/mochitest/browser_dbg-sourcemaps.js
src/test/mochitest/browser_dbg-sourcemaps2.js
src/test/mochitest/head.js

Simplifies command so that it uses the promise middleware. Depends on the prior PR to finish first.

Refactor command action to use PROMISE

---

src/actions/pause/fetchScopes.js
src/actions/pause/index.js
src/actions/pause/paused.js
src/actions/pause/selectFrame.js
src/reducers/pause.js
src/test/mochitest/head.js

A refactor based on talking w/ @jimblandy about how scopes are fetched from the server. I realized that map scopes does more than advertised

Refactor map scopes to fetch scopes

---

src/actions/tests/ui.spec.js
src/actions/ui.js

Associated Issue: #4482 
Refactor togglePaneCollapse check before dispatch

togglePaneCollapse update

---

src/components/SecondaryPanes/Scopes.js

do not expand all scope objects

---

package.json
src/utils/editor/index.js
yarn.lock

Fix jest intermittent - quick open

---

src/reducers/pause.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-pause-exceptions.js
src/test/mochitest/head.js

This enables a bunch of tests as well as fixes some errors we were seeing in pause on exceptions:

Re-enable tests

---

docs/most-common-issues.md

document an edge case w/ yarn start

Competing Scripts - break webpack

---

src/actions/pause/paused.js
src/actions/sources.js
src/client/firefox/create.js
src/components/Editor/Editor.css
src/components/PrimaryPanes/Sources.css
src/components/SecondaryPanes/Breakpoints.js
src/test/mochitest/browser_dbg-editor-select.js
src/test/mochitest/head.js
src/utils/editor/index.js

@jbhoosreddy and I looked at some panel bugs today and fixed some of the big ones
* gap in the welcome box
* jump to line when selecting a breakpoint
* jump to line when stepping
* gutter disappearing while stepping
I'll add some mochitests for the gutter and jumping, they're tougher to test because we need to actually test to see if the line is "visible" not just highlighted

Panel fixes

---

src/actions/pause/fetchScopes.js

Associated Issue: we can have ADD_SCOPES for wasm files.

Issue ADD_SCOPES even for wasm files.

---

src/actions/breakpoints/tests/syncing.js
src/actions/index.js
src/actions/tests/helpers/threadClient.js
src/actions/tests/pending-breakpoints.spec.js
src/actions/utils/middleware/promise.js
src/client/chrome/events.js
src/client/firefox/create.js
src/components/Editor/GutterMenu.js
src/components/ProjectSearch/tests/TextSearch.js
src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/EventListeners.js
src/components/SecondaryPanes/Frames/index.js
src/components/SecondaryPanes/Frames/tests/Frame.js
src/components/SecondaryPanes/Frames/tests/Frames.js
src/components/SecondaryPanes/Frames/tests/Group.js
src/reducers/pause.js
src/test/tests-setup.js
src/utils/bootstrap.js
src/utils/editor/index.js
src/utils/frame.js
src/utils/pause.js
src/utils/scopes.js
src/utils/test-head.js
src/workers/parser/utils/ast.js

Associated Issue: #4568
* replaced all instances of Object.assign with ... spread
a lot of "yarn test"

Replaces Object.assign with ... spread

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-wasm-sourcemaps.js
src/test/mochitest/head.js

Re-enable wasm test

---

src/actions/tests/pause.spec.js

Associated Issue: #3696
* Added a unit test for making sure breakpoint stepping work while paused
* Added a unit test for making sure breakpoint stepping doesn't work while not paused

Breakpoint setting unit tests

---

src/components/Editor/EditorMenu.js
src/components/Editor/GutterMenu.js
src/components/Editor/Tabs.js
src/components/PrimaryPanes/SourcesTree.js
src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/Frames/FrameMenu.js
src/components/SecondaryPanes/Frames/tests/FrameMenu.js

Associated Issue: #4630
* switch devtools-launchpad to devtools-contextmenu
context menu should work without any issues.
tested, it worked, no issues

Contextmenu

---

src/components/App.css
src/components/SecondaryPanes/Frames/Frames.css
src/components/SecondaryPanes/Frames/Group.css
src/components/SecondaryPanes/Frames/Group.js
src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.js.snap
src/components/shared/Badge.css
src/components/shared/Badge.js

Associated Issue: #4659 
* new react component - `<Badge>{...}</Badge>` is intended to show a number with rounded background
* added some css utility classes a la bootstrap. If this is considered good, I'd add more and do some refactoring in existing css.
I updated the snapshot for Group.js test.
This is pretty similar to GitHub's UI (even though I saw that only after I implemented):

Frame count badge

---

src/components/Editor/Breakpoint.js
src/components/Editor/Breakpoints.js

Associated Issue: #4579 
* Remove `showSourceText` from Breakpoint component

Remove Breakpoint Editor management

---

docs/local-development.md

* #Testing section, paragraph two local-development.md was missing the word 'you'.

fixed typo in local-development.md in section #Testing. 

---

assets/dictionary.txt
docs/local-development.md
docs/performance.md
package.json
yarn.lock

bumping to pad 110 to enable auto react perf timings

Add content for profiling

---

package.json
yarn.lock

Bumps some modules:
- editor to get clike and rust (not used in panel)
- modules - to get telemetry shims

Bump mod editor

---

src/actions/project-text-search.js
src/actions/tests/project-text-search.spec.js
src/actions/types.js
src/components/ProjectSearch/TextSearch.js
src/components/ProjectSearch/index.js
src/components/ProjectSearch/tests/__snapshots__/TextSearch.js.snap
src/reducers/project-text-search.js

Associated Issue: #4685
*  Added a new action creator for updating the status of search result fetching
*  based on the above action, in reducer I have added a new case branch which basically updates the status variable in the reducer.

added a loading message while search results are being fetched 

---

src/actions/types.js
src/components/Editor/Tabs.css
src/components/Editor/Tabs.js

Associated Issue: #4151
* Add React icon to React components tabs
The icon seems a little small, thoughts?

WIP - React Components Show React Logo

---

src/components/PrimaryPanes/Outline.js
src/components/PrimaryPanes/index.js
src/components/tests/Outline.spec.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-outline.js
src/test/mochitest/head.js

Associated Issue: #4616
* fix selectSource so that it gets a location
* add a mochitest

Fix selecting an item in the outline

---

src/components/shared/Badge.js

Associated Issue: #4727
* Add types for badge

fix for the lint issue

---

src/components/Editor/CallSites.js
src/components/Editor/ConditionalPanel.js

Associated Issue: #4532
Update mapDispatchToProps for
- src/components/Editor/CallSites.js
- src/components/Editor/ConditionalPanel.js

4532 - Part 2: Update mapDispatchToProps for CallSites.js, ConditionalPanel.js

---

src/components/PrimaryPanes/SourcesTree.js
src/components/shared/Svg.css
src/utils/sources-tree/getURL.js

Associated Issue: #4733
added angular icon in the source pane for angular projects

added angular icon in the source pane for angular projects

---

src/actions/sources.js
src/utils/prefs.js

Associated Issue: #4731 
* Add auto prettyprint option in prefs

Enable auto prettyprint pref

---

src/components/ProjectSearch/TextSearch.js
src/reducers/project-text-search.js

 Switch TextSearch from PropTypes to Flow props #4739 

---

src/components/shared/Popover.css
src/components/shared/Popover.js

Associated Issue: #4583
Add block div in line 136/145  in src/components/shared/Popover.js
Tested in https://event-handler.glitch.me/

[Preview] Tooltip position

---

src/utils/sources-tree/addToTree.js
src/utils/sources-tree/getURL.js
src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap
src/utils/sources-tree/tests/addToTree.spec.js

Fixes #4721 
* Better format data urls in sources tree

Sources better display data uri

---

src/components/Editor/Tabs.js
src/workers/parser/frameworks.js

Associated Issue: #4773
* Fixed displaying react logo on non-React tabs when React tab is selected

Display React logo only on active tab

---

package.json
src/test/mochitest/browser_dbg-console-link.js
src/test/mochitest/browser_dbg-outline.js
src/test/mochitest/head.js
src/utils/expressions.js
src/utils/tests/expressions.spec.js

Associated Issue: #4551
* Removed replace of backslashes in expressions.js
* Removed test case referencing the replace in expressions.spec.js

Permits backslash in expressions

---

src/actions/sources/loadSourceText.js
src/actions/sources/tests/loadSourceText.spec.js
src/actions/tests/breakpoints.spec.js
src/actions/tests/project-text-search.spec.js
src/actions/tests/sources.spec.js
src/reducers/sources.js
src/test/mochitest/browser_dbg-console-link.js
src/test/mochitest/browser_dbg-outline.js
src/utils/source.js
src/utils/test-head.js

Associated Issue: #4705 
* updates load source text so only one source is loaded at a time
* starts a unit test

only load sources once

---

src/components/Editor/EditorMenu.js
src/components/Editor/EmptyLines.js

Associated Issue: #4532 
Update mapDispatchToProps for EditorMenu.js and EmptyLines.js

4532 - Part 3: Update mapDispatchToProps for EditorMenu.js and EmptyLines.js

---

assets/dictionary.txt
assets/panel/panel.js
src/actions/pause/paused.js
src/actions/pause/selectFrame.js
src/actions/sources.js
src/actions/tests/__snapshots__/ast.spec.js.snap
src/actions/tests/ast.spec.js
src/actions/tests/breakpoints.spec.js
src/actions/tests/sources.spec.js
src/actions/tests/tabs.spec.js
src/components/Editor/Tabs.js
src/components/PrimaryPanes/Outline.js
src/components/PrimaryPanes/SourcesTree.js
src/components/ProjectSearch/TextSearch.js
src/components/QuickOpenModal.js
src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/EventListeners.js
src/components/tests/Outline.spec.js
src/test/mochitest/head.js
src/utils/location.js

Associated Issue: #4844 
This fixes the inconsistency and the test. however it also seems to have fixed pretty print, which was not working and not noticed until now. the CI tests are failing, they need to be updated to reflect that we pretty print automatically now. will revisit in the morning!

fix selectLocation action

---

src/components/Editor/Tabs.js
src/components/shared/Dropdown.css
src/components/variables.css

Associated Issue: #4807
* Adds file, prettyPrint and blackBox icons to dropdown

Adds file, prettyPrint and blackBox icons to dropdown

---

.travis.yml
src/test/mochitest/browser_dbg-chrome-debugging.js

Synchronize changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1416711

Synchronize browser_dbg-chrome-debugging.js from m-c

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-content-script-sources.js
src/test/mochitest/examples/doc-content-script-sources.html

Bug 1416928 - Test content script debugging on the new debugger UI.

---

src/workers/parser/frameworks.js
src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/tests/fixtures/frameworks/es5Component.js
src/workers/parser/tests/framework.spec.js
src/workers/parser/utils/formatSymbols.js

Associated Issue: #4730 
* Detect `require("react")` and accept it as an import
* Detect `React.Component` and accept as a component extension

Improve isReactComponent

---

src/workers/parser/getOutOfScopeLocations.js
src/workers/parser/tests/__snapshots__/getOutOfScopeLocations.spec.js.snap
src/workers/parser/tests/fixtures/outOfScope.js
src/workers/parser/tests/getOutOfScopeLocations.spec.js

[Preview] mis-judge in scope inner locations

---

bin/ci/run-tests.js
package.json

Associated Issue: #4629
* we recently introduced a dependency that ballooned the parser-worker. We previously were checking to see if we ballooned the debugger, so it is easy to generalize this check.

check for larger bundle sizes

---

src/actions/sources.js
src/utils/isMinified.js
src/utils/source.js
src/utils/tests/isMinified.spec.js

* extracts  isMinified
* adds a unit test
* we should add several more
Next Steps
* i don't think we want to consider small files w/ < 200 chars minified... the case i have in the test is the current, behavior but it feels off to me.
* I think we should remove the minified cache and replace it w/ a Source isMinified field... that would be simpler going forward because caches can go stale, consume memory, etc...

Extracts isMinified

---

src/actions/ast.js
src/actions/tests/__snapshots__/ast.spec.js.snap
src/actions/types.js
src/components/Editor/Preview/Popup.css
src/components/Editor/Preview/Popup.js

* check if variable is an Immutable
* show "Immutable" in the header
* filter relevant roots (`tail`, `root`, and `size`)
Before:
After:

immutable variable hover

---

src/actions/ast.js
src/actions/sources.js
src/actions/sources/loadSourceText.js
src/actions/tests/ast.spec.js
src/actions/tests/pending-breakpoints.spec.js
src/actions/tests/sources.spec.js
src/components/Editor/Tabs.js
src/test/mochitest/browser_dbg-editor-highlight.js
src/test/mochitest/browser_dbg-minified.js
src/test/mochitest/browser_dbg-outline.js
src/test/mochitest/browser_dbg-reload.js
src/test/mochitest/head.js
src/utils/test-head.js

Associated Issue: #4705 
* Removes await 
* moves loadSourceText to checkPendingBreakpoints (we might not need it at all)

Do work in the background

---

assets/images/resume.svg
src/components/Editor/Tabs.css
src/components/SecondaryPanes/CommandBar.css
src/components/SecondaryPanes/CommandBar.js
src/components/shared/Button/CommandBarButton.css
src/components/shared/Button/CommandBarButton.js
src/components/shared/Button/PaneToggle.css
src/components/shared/Button/PaneToggle.js

Associated Issue: #4906
* Refactored common code into `CommandBarButton` component and used in `PaneToggle` and command bar
* Cleaned up CSS to resolve alignment problem

Refactor common button code into CommandBarButton

---

assets/images/Svg.js
package.json
yarn.lock

Upgrade svg-inline-react to v3.0.0
Blocks #4885

Upgrade svg-inline-react to v3.0.0

---

src/actions/tests/__snapshots__/ast.spec.js.snap
src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/tests/fixtures/jsx.js
src/workers/parser/tests/getSymbols.spec.js
src/workers/parser/utils/formatSymbols.js

[WIP] [Parser] detect if files use JSX

---

src/test/mochitest/browser_dbg-iframes.js

Add longer timeout x3 for browser_dbg-iframes.js

Add longer timeout for browser_dbg-iframes.js

---

docs/updates/README.md
docs/updates/updates-6-20-2017.md

Fix some misspell

---

src/components/SecondaryPanes/CommandBar.css

Associated Issue: #4907 
* Fixes footer height in right sidebar.
This was fixable by changing only one property from css. Please let me know if this requires some more work. :)

Fix right sidebar footer height

---

CONTRIBUTING.md

Add Lukas to the Core Team

---

src/components/Editor/EditorMenu.js

Associated Issue: #4933
* grouped and ordered variable assignments and localization definitions, unified naming conventions, added minor comments
- tested functionality of menu compared to version before

Cleans up EditorMenu.js

---

package.json
src/workers/parser/utils/ast.js
yarn.lock

Associated Issue: #3307 #4882
Reverting p-s-t because it still has a memory leak :/
Happy to help investigate.

Revert Parse Script Tags

---

docs/debugging-the-debugger.md

Made the code we are adding a little easier, and made an alert popup when we set a breakpoint to make it exciting

Updated Documentation

---

src/components/Editor/Footer.css

Associated Issue: #4292 
Changed the background hover for Two buttons under footer.css.

Changed background hover

---

CONTRIBUTING.md
ROADMAP.md
docs/debugger-html-react-redux-overview.md
docs/issues.md
docs/local-development.md
docs/mochitests.md
docs/most-common-issues.md
docs/pull-requests.md
docs/running-as-firefox-panel.md
docs/updates/5-1-2017-flow.md
docs/updates/5-1-2017-tests.md
docs/updates/README.md
docs/updates/updates-2-28-2017.md
docs/updates/updates-3-14-2017.md
docs/updates/updates-3-21-2017.md
docs/updates/updates-3-28-2017.md
docs/updates/updates-3-7-2017.md
docs/updates/updates-4-18-2017.md
docs/updates/updates-5-16-2017.md
docs/updates/updates-5-23-2017.md
docs/updates/updates-6-20-2017.md
docs/updates/updates-7-25-2017.md
docs/updates/updates-8-1-2017.md
docs/updates/updates-9-26-2017.md
src/components/Editor/EditorMenu.js

* Fixed a few typos in documentation.

docs: fix typos

---

src/components/shared/ResultList.css
src/utils/quick-open.js
src/utils/source.js

* fixes quick open
* simplifies a helper
* simplifies styling

fix quick open

---

flow-typed/debugger-html.js

Prettify types

---

src/actions/preview.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-preview-source-maps.js
src/test/mochitest/head.js

* Fix preview for original sources
* I broke it when I fixed some other preview bugs
Adding a mochitest. The mochitest still needs work.

Fix preview for original sources

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Add a .vscode folder so we can share settings with everyone that is contributing which is a recommendation from the team at
https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

add .vscode folder so we can share settings with everyone that is contributing

---

package.json
src/actions/types.js
src/reducers/ast.js
src/reducers/pending-breakpoints.js
src/reducers/project-text-search.js
yarn.lock

* Upgrade Flow to 0.61.0 
* Ran test suite
* Ran through app scenarios (stepping, breakpoints, etc to ensure no odd regressions)

⬆️: Upgrading Flow to 0.61

---

package.json
src/actions/README.md
src/actions/sources/createPrettySource.js
src/actions/sources/loadSourceText.js
src/actions/sources/tests/__snapshots__/createPrettySource.spec.js.snap
src/actions/types.js
src/components/Editor/Footer.js
src/reducers/sources.js
src/test/mochitest/browser_dbg-pretty-print.js
src/utils/defer.js

Associated Issue: #4833
* Prevent multiple execution of pretty print heavy task when button is pressed again.
- Need to represent this in a test case, need help with this

Call prettyprint only once

---

src/components/Editor/index.js
src/utils/editor/source-documents.js
src/utils/source.js
src/utils/tests/source.spec.js

Associated Issue: #4943
* Follow up on #4943, uses hasJsx and removes sourcesMetadata

[Editor] Use hasJsx

---

src/utils/prefs.js

Associated Issue: #3815 #4033 
* adds some local feature flags

Setup worker feature flag

---

flow-typed/debugger-html.js
src/actions/event-listeners.js
src/actions/pause/commands.js
src/actions/sources.js
src/actions/utils/middleware/log.js
src/components/Editor/DebugLine.js
src/components/Editor/GutterMenu.js
src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/ChromeScopes.js
src/components/SecondaryPanes/CommandBar.js
src/components/SecondaryPanes/Expressions.js
src/components/SecondaryPanes/Frames/WhyPaused.js
src/components/SecondaryPanes/Frames/index.js
src/components/SecondaryPanes/Scopes.js
src/components/SecondaryPanes/index.js
src/components/tests/WhyPaused.spec.js
src/reducers/pause.js
src/test/mochitest/browser_dbg-navigation.js
src/test/mochitest/browser_dbg-pretty-print-paused.js
src/test/mochitest/head.js
src/utils/pause.js
src/utils/pause/scopes/getScope.js
src/utils/pause/scopes/index.js
src/utils/pause/scopes/synthesizeScopes.js
src/utils/pause/scopes/tests/getFramePopVariables.spec.js
src/utils/pause/scopes/tests/scopes.spec.js
src/utils/pause/scopes/utils.js

Associated Issue: #4556
doesn't change any logic, just makes it easier to follow
* cleanup frame mapping for original locations
* extract togglePrettyPrint
* remove pause.pause field as it was no longer needed
* start using isPaused

Refactor pause (2/2)

---

src/components/WelcomeBox.css

toggle-button-end is not displayed when displaying welcomebox in portrait mode

---

src/utils/source.js

Export source utils

---

src/components/Editor/Preview/index.js

* Switches to *selection* state so that mouse down clears the preview popup.
* checked context menu 
* double click

Cleanup preview selection

---

.eslintrc
package.json
src/actions/breakpoints/tests/syncing.js
src/actions/sources/tests/select.spec.js
src/actions/tests/navigation.spec.js
src/actions/tests/pause.spec.js
src/client/firefox/tests/onconnect.spec.js
src/components/Editor/tests/Breakpoints.spec.js
src/components/ProjectSearch/textSearch/tests/__snapshots__/textSearch.spec.js.snap
src/components/ProjectSearch/textSearch/tests/textSearch.spec.js
src/components/SecondaryPanes/Frames/tests/Frames.js
src/components/tests/PreviewFunction.spec.js
src/utils/pause/scopes/tests/getFramePopVariables.spec.js
src/utils/pause/scopes/tests/scopes.spec.js
src/utils/sources-tree/tests/addToTree.spec.js
src/utils/sources-tree/tests/collapseTree.spec.js
src/utils/sources-tree/tests/sortTree.spec.js
src/workers/parser/tests/validate.spec.js
src/workers/search/tests/get-matches.spec.js
yarn.lock

* Add eslint jest plugin
* Clean up some tests
https://www.npmjs.com/package/eslint-plugin-jest

Add eslint jest plugin

---

docs/issues.md

Associated Issue: #5044
Added additional spaces needed:
- for table to work
- for suggestions to be multiline

Resolves styling issues

---

src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/BreakpointsContextMenu.js

Associated Issue: #4597 
Extract the breakpints context menu

4597 - [Breakpoints] Extract Context menu

---

src/components/QuickOpenModal.js
src/components/tests/QuickOpenModal.spec.js
src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
src/utils/tests/quick-open.spec.js

* Add some additional tests for `QuickOpenModal`
* Add tests for `parseLineColumn` utility
* trim some code around the modal

🔨: Cleaning up some quick open code and adding tests.

---

src/components/App.js
src/components/Editor/index.js
src/test/mochitest/browser_dbg-layout-changes.js

Opening the debugger below the width bp was not triggering vertical mode.
mochitests

Show vertical mode on open

---

bin/writeReadme.js

async-await refactor

---

package.json
src/actions/breakpoints.js
src/actions/file-search.js
src/actions/ui.js
src/components/Editor/SearchBar.js
src/components/Editor/index.js
src/utils/editor/create-editor.js
src/utils/editor/index.js
src/utils/editor/source-documents.js
src/utils/editor/source-editor.css
src/utils/editor/source-editor.js
webpack.config.js
yarn.lock

* Bring devtools-source-editor back into the debugger
* Switch `module.exports` to `export function`
* Add some more types 
* Add some safety guards e.g. `if (!line)`

Refactor Editor utils

---

src/actions/event-listeners.js

* Added the `services` which was being used but never defined.

Add the services argument

---

assets/images/Svg.js

Associated Issue: #5023
* return `null` from instead of `undefined` which broke react rendering
Steps to Reproduce:
- go to https://jovandemo.modulentwicklung.de:8001/admin
- login with User: anyone@mozilla.org PW: 123456789
- go to Orders > Orders
- Open Debugger and search for file: Shared/Directives/DataTable/DataTableController.ts
- Set a breakpoint in line 197
- Move cursor inside the view-port to trigger angular
)

fix to return null instead of undefined

---

.travis.yml
bin/ci/run-tests.js
package.json
src/actions/utils/middleware/log.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-wasm-sourcemaps.js
yarn.lock

Summary:
1. we were not seeing the wasm failure
2. we only see the mochih summary, we should save the mochitest log for failure cases
3. we should run the inspector/console/netmonitor debugger tests
We're seeing issues now where tests are completing but returning a status code 1...

fix logging

---

flow-typed/debugger-html.js
src/actions/breakpoints/syncBreakpoint.js
src/actions/preview.js
src/actions/tests/__snapshots__/preview.spec.js.snap
src/actions/tests/pause.spec.js
src/actions/tests/preview.spec.js
src/client/firefox/commands.js
src/components/Editor/Preview/Popup.js
src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/Frames/WhyPaused.js
src/utils/preview.js
src/workers/parser/sources.js

Associated Issue: #4829
* Separate out functions for rendering react and immutable
* remove `size` and `entries`
Todo
* Fix react rendering errors
* Cleanups
Test
* Go to https://accessible-walrus.glitch.me/
* Set breakpoint on line 20
* Refresh page
* When breakpoint gets hit 
* Preview all the possible values above

[Preview] Separate out functions for react and immutable

---

assets/images/Svg.js
src/components/shared/Dropdown.css

Associated Issue:  #5024 
* changed height of dropdown button 
* added display for icons

Dropdown styling

---

.flowconfig
package.json
yarn.lock

Upgrade flow to 63.1

---

src/components/ProjectSearch/TextSearch.js

Associated Issue: #5050 
Here is the screen shot for the rectified error message

Changed error to 'No results found'

---

src/components/PrimaryPanes/Sources.css

Associated Issue: #4950 
Changed **Sources.css** file to fetch required output

Icons are made Brighter

---

assets/panel/debugger.properties
src/actions/sources/loadSourceText.js
src/actions/sources/tests/loadSource.spec.js
src/components/Editor/index.js
src/components/Editor/tests/Editor.spec.js
src/utils/editor/source-documents.js
src/utils/source.js

Associated Issue: #4547 and also general error during source text loading
TODO:

Fixes loading error

---

src/components/shared/ManagedTree.js
src/components/shared/Popover.js
src/components/shared/tests/ManagedTree.spec.js
src/components/shared/tests/Popover.spec.js
src/components/shared/tests/__snapshots__/ManagedTree.spec.js.snap

Associated Issue: #5100 
* Fix a flow issue in Popover code
* Adding tests for majority of ManagedTree behavior

Moar testing

---

src/components/Editor/Preview/Popup.js
src/reducers/ast.js
src/test/mochitest/browser_dbg-breakpoints-cond.js
src/test/mochitest/browser_dbg-console-link.js
src/test/mochitest/browser_dbg-editor-highlight.js
src/test/mochitest/browser_dbg-preview.js
src/test/mochitest/browser_dbg-sourcemaps3.js
src/test/mochitest/browser_dbg_keyboard_navigation.js
src/test/mochitest/head.js

* cleans up the reducer a bit
* prevents pre-mature highlighting and arrows
* simplifies logic a bit

Cleanup Preview

---

package.json
yarn.lock

This is needed for Scopes remapping to work

Update devtools-reps to 0.19.1

---

src/actions/project-text-search.js
src/actions/sources/loadSourceText.js
src/actions/sources/tests/loadSource.spec.js
src/actions/tests/__snapshots__/project-text-search.spec.js.snap

#5159
* Removed `loadAllFiles` method
* Started loading files in `searchSources`
- Open https://arewesmoothyet.com/?mode=track&trackedStat=Devtools%20Hangs
- CMD-SHIFT-F for "trackedStat"
- Expect one result instead of two
Before:
After:

[Project Search] Fix duplicate sources

---

src/components/PrimaryPanes/Sources.css
src/components/SecondaryPanes/Scopes.css
src/components/shared/Svg.css

Associated Issue: #5059
- Fixes missing source tab border in rtl 
- Fixes arrow behavior in rtl 
- Makes scope padding dependent on text direction

Fixes rtl styles of source tree

---

src/utils/quick-open.js

Associated Issue: #5142
* Started including third party libraries in QuickOpen sources
After changes:
Before changes:

Added third party libraries to QuickOpen sources

---

postcss.config.js

* Remove tab characters and replace with spaces
* Maintain consistent String quote characters

Fix alignment in postcss.config.js

---

src/utils/tests/clipboard.spec.js

I added some preliminary tests for clipboard.js

Add tests for utils/clipboard

---

src/components/App.css
src/components/SecondaryPanes/CommandBar.css
src/components/shared/Accordion.css

Update dark theme with lower-contrast sidebars.

---

assets/panel/panel.js

See changes made in https://bugzilla.mozilla.org/show_bug.cgi?id=1431127

Add isPaused to assets/panel/panel.js (synchronization from m-c Bug 1431127

---

assets/dictionary.txt
docs/debugging.md
docs/local-development.md
src/client/index.js
src/utils/dbg.js

* This switches `getGlobalsForTesting` to `dbg` 
* makes it a property instead of a function.
* binds selectors and actions so you can do `dbg.getSources()` and it just works

Switch to a simpler helper

---

.travis.yml
package.json
yarn.lock

@juliandescottes recently added other tests that touched the debugger
I had to take them out because the way they were setup were timing out... Here's a new branch that attempts to land them so that they all run

Re-add other tests

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-sources-named-eval.js
src/test/mochitest/browser_dbg-sources.js

Add named-evals test

---

src/components/SecondaryPanes/Expressions.js

Highlight all text on watch expression edit

---

package.json
src/components/shared/tests/__snapshots__/ManagedTree.spec.js.snap
src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
src/test/mochitest/browser_dbg-sources-named-eval.js
src/test/mochitest/browser_dbg-sources.js
yarn.lock

Couldn't be simpler... bump devtools-components to 0.1.4

Bump devtools-components to 0.1.4

---

assets/panel/debugger.properties
src/actions/tests/ui.spec.js
src/actions/ui.js
src/components/PrimaryPanes/SourcesTree.js
src/reducers/ui.js
src/utils/sources-tree/addToTree.js
src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap
src/utils/sources-tree/tests/addToTree.spec.js

Associated Issue: #4121 
* Change the root of sources tree to custom one

[SourcesTree] Set root directory

---

src/utils/editor/tests/editor.spec.js

* Fix a failing test suite that regressed with #5182

🐛: Fix broken test by adding appropriate mocks

---

src/components/PrimaryPanes/Sources.css
src/components/PrimaryPanes/SourcesTree.js
src/test/mochitest/browser_dbg-reload.js

Associated Issue: # 5235
* Removed bright blue left margin.
* Fixed indentation.

Remove the blue left margin from Sources tree & fix indentation

---

src/components/QuickOpenModal.css
src/components/QuickOpenModal.js
src/utils/quick-open.js
src/utils/tests/quick-open.spec.js

Associated Issue: #4488 
* title highlighting
* subtitle highlighting
* Create Tests

[QuickOpen] style matched fuzzy characters

---

package.json
src/components/PrimaryPanes/Sources.css
src/components/SecondaryPanes/Expressions.css
src/components/SecondaryPanes/Scopes.css
yarn.lock

Bump reps + tree styling

---

docs/client.md
src/utils/dbg.js

this should make it easier for others to hack on the debugger protocol

Add docs for sending packets to the actors

---

src/actions/pause/paused.js
src/actions/sources/select.js
src/selectors/visibleSelectedFrame.js
src/test/mochitest/browser_dbg-sourcemaps.js
src/test/mochitest/head.js

Associated Issue: #3842
* added functionality to step through generated files

step through generated files

---

src/test/mochitest/examples/sourcemaps-reload/package.json
src/test/mochitest/examples/sourcemaps3/package.json

Fix wrong license, missing description and invalid main file.

Fix licenses and description for package.json files used in mochitests

---

assets/panel/debugger.properties

Fixing some review comments that were not addressed before merging.

Fix localization notes references

---

assets/panel/index.html

See https://bugzilla.mozilla.org/show_bug.cgi?id=1431533

Synchronize ChromeUtils change from Bug 1431533

---

src/components/Editor/Preview/Popup.js

5241 - [Preview] Show empty values

---

src/utils/tests/path.spec.js

Created simple tests for the functions exported from `src/utils/path.js`

Add tests for utils/path

---

src/components/PrimaryPanes/Outline.css
src/components/PrimaryPanes/Sources.css
src/components/shared/ManagedTree.css
src/test/mochitest/browser_dbg-sources.js
src/test/mochitest/head.js

This reverts commit https://github.com/devtools-html/debugger.html/commit/b892892a0768e96f64df7b2ab3509da75029bb84.

[Sources] - fix paddings in sources tree and outline list

---

src/actions/navigation.js
src/actions/pause/commands.js
src/actions/pause/index.js
src/actions/pause/paused.js
src/actions/types.js
src/client/firefox.js
src/client/firefox/commands.js
src/client/firefox/create.js
src/client/firefox/types.js
src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/CommandBar.css
src/components/SecondaryPanes/CommandBar.js
src/reducers/pause.js

Add basic UI for rewinding when server indicates it can rewind

---

src/components/Editor/SearchBar.css
src/components/shared/Svg.css

@jasonLaster 
* modifier colors and icon colors to match the others.

change icon colors and search modifiers to theme-comment

---

assets/dictionary.txt
docs/README.md
docs/dbg.md
docs/debugging.md
src/client/firefox/commands.js
src/client/index.js
src/utils/dbg.js

* adds docs for `dbg`
* adds `dbg.helpers.findSource`, `dbg.helpers.evaluate`
* binds `dbg.selectors` which makes it super easy to fire off queries like `dbg.selectors.getBreakpoints()`

improve dbg

---

src/components/PrimaryPanes/SourcesTree.js
src/test/mochitest/browser_dbg-sources.js
src/test/mochitest/head.js

Fixes folder toggle in source tree

---

.prettierignore
src/test/tests-setup.js
src/workers/parser/tests/__snapshots__/getScopes.spec.js.snap
src/workers/parser/tests/fixtures/scopes/arrow-function.js
src/workers/parser/tests/fixtures/scopes/block-statement.js
src/workers/parser/tests/fixtures/scopes/class-declaration.js
src/workers/parser/tests/fixtures/scopes/class-expression.js
src/workers/parser/tests/fixtures/scopes/class-property.js
src/workers/parser/tests/fixtures/scopes/for-loops.js
src/workers/parser/tests/fixtures/scopes/function-declaration.js
src/workers/parser/tests/fixtures/scopes/function-expression.js
src/workers/parser/tests/fixtures/scopes/simple-module.js
src/workers/parser/tests/fixtures/scopes/switch-statement.js
src/workers/parser/tests/fixtures/scopes/try-catch.js
src/workers/parser/tests/getScopes.spec.js
src/workers/parser/tests/helpers/index.js
src/workers/parser/visitor.js

Associated Issue: #5253
* Fix a few bugs the tests uncovered
* Exercise getScope calls for various types of nodes

Add unittests for original scope AST visitor

---

bin/ci/check-file-sizes.js
src/components/Editor/SearchBar.js
src/components/Editor/index.js

* Fixes the CI check so that we exit w/ a fail code if the check is too high
* Fixes an import

Fix File sizes

---

src/components/PrimaryPanes/SourcesTree.js
src/test/mochitest/browser_dbg-sources.js

Taking another whack at the test, by cleaning up the sources tree code a bit more

Fix the sources tree test

---

src/components/PrimaryPanes/Outline.css
src/components/PrimaryPanes/Outline.js
src/workers/parser/getSymbols.js

[Outline] clicking class selects source in editor

---

assets/panel/debugger.properties
src/components/App.js
src/components/ShortcutsModal.js

Fix localizations

---

src/utils/tests/utils.spec.js

* Add tests for functions defined in `src/utils/utils`
* Removes a test for utils `throttle()` (which appears to have been deleted this morning from utils)

Add tests for utils/utils

---

assets/images/back.svg
assets/images/forward.svg
assets/panel/debugger.properties
assets/panel/prefs.js
src/actions/index.js
src/actions/replay.js
src/actions/types.js
src/components/PrimaryPanes/index.js
src/components/SecondaryPanes/CommandBar.css
src/components/SecondaryPanes/CommandBar.js
src/reducers/expressions.js
src/reducers/index.js
src/reducers/pause.js
src/reducers/replay.js
src/selectors.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-replay.js
src/test/mochitest/head.js
src/utils/prefs.js

allows going back in time!
Project schlomo < -- @jasonLaster

Feature/history reducer :tada:

---

assets/panel/debugger.properties

Follow up https://github.com/devtools-html/debugger.html/pull/5360

Address localization comments

---

README.md

* updated the link of google doc in read-me
(older link was redirecting to a Archived document)

Updated the link of google doc in Readme

---

src/components/shared/SearchInput.js
src/components/shared/tests/__snapshots__/SearchInput.spec.js.snap
src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap

Removed the result count in the search bar for find in files. 
Post fix: 
Prior to fix:

Find in files result count removed in search bar. 

---

src/actions/pause/mapScopes.js

we should log in development what broke

Mapping - log exceptions in development

---

src/test/mochitest/browser_dbg-babel.js

Extend babel test

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-quick-open.js

still seeing some intermittents
https://treeherder.mozilla.org/#/jobs?repo=try&revision=c667044750ad5dce22ae4f447de87e24ac0cc745&selectedJob=161341812

Fix remaining quick open intermittent

---

src/actions/preview.js
src/actions/tests/__snapshots__/preview.spec.js.snap
src/actions/tests/preview.spec.js
src/reducers/ast.js
src/test/mochitest/browser_dbg-preview-module.js
src/utils/editor/get-expression.js

Associated Issue: #5377 
* Early hacky version. Give it a go and let me what you think.
* It somewhat works... 
- finds lots of expression
- highlighting is off
- is flickery

[WIP] Fast Preview

---

src/workers/parser/getScopes/index.js
src/workers/parser/getScopes/visitor.js
src/workers/parser/getSymbols.js
src/workers/parser/index.js
src/workers/parser/utils/ast.js
src/workers/parser/utils/getFunctionName.js

Babel 7's `@babel/types` includes a `.traverse` function that is much faster than babel-traverse because it doesn't need to do all the bookkeeping to handle AST mutation during traversal. On my machine testing with `Date.now()` with the debugger debugging the debugger itself, this PR say times go from ~8s to ~3.5s for the parse & traverse & toParsedScopes work that is done up front and cached for later calls to `workers/parser/getScopes`.
* Reworked the visitor to use `t.traverse`'s `ancestors` array rather than `babel-traverse`'s `NodePath`.
* A few other small tweaks to help readability with the new visitor approach.
* Use Babel 7's 'unambiguous' logic to avoid doing it.

Update scope parsing visitor to use t.traverse for speed

---

src/components/Editor/Tab.js

Associated Issue: #5323
Adds middle click capability to close edit tab.

Adds middle-click close to editor tabs

---

assets/panel/debugger.properties
src/actions/pause/commands.js
src/actions/pause/paused.js
src/actions/tests/toolbox.spec.js
src/actions/toolbox.js
src/components/Editor/EditorMenu.js
src/reducers/pause.js
yarn.lock

Associated Issue: #3942
* introduces a context menu item to evaluate code in the console.

Adds option to execute selected text in editor right-click menu

---

src/components/SecondaryPanes/Scopes.css

Associated Issue: #5331 
*  Removed extra padding that was making background shifted by some pixels.

Fix scope listing hover background

---

src/components/Editor/ConditionalPanel.js
src/test/mochitest/browser_dbg-breakpoints-cond.js

This reverts commit 01050ebf17f30da384ff6fa564033d646d148347.
I'm not sure why it started failing on master, but it is safer to take it out and take a look than to try and debug it in realtime

Revert "Ensure that conditional panels are focused. (#5409)"

---

src/client/firefox/commands.js
src/utils/editor/get-expression.js

Adds checks for empty expressions because the server crashes if we dont give it something sensible. Also, it is better to be paranoid.

[Preview] Empty Expression

---

package.json
src/test/mochitest/browser_dbg-babel.js
yarn.lock

Update devtools-reps to 0.20.0

---

docs/updates/updates-2-20-2018.md

Apparently @jlaster's earlier update was a WIP, so this should hopefully fix the warnings

Fix 2/20 update text to fix warnings

---

CODEOWNERS

I'd like to be notified of changes to the properties file so that I know when to pay attention at release time. Also will help me quickly track down reviews that have not been handled correctly.

Add @juliandescottes to CODEOWNERS for properties file

---

.storybook/config.js
src/components/stories/ManagedTree.js
src/components/stories/Outline.js
src/components/stories/Preview.js
src/components/stories/ResultList.js
src/components/stories/SearchInput.js
src/components/stories/Workers.js
src/components/stories/frames.js
src/components/stories/tabs.js

The `Provider`/`connect` error still shows for a few storybook items but this gets storybook working.

Fix the storybook enough to run by changing dark theme path

---

src/components/App.js
src/components/Editor/Tabs.js
src/components/SecondaryPanes/Frames/Group.js
src/components/SecondaryPanes/Frames/index.js
src/components/shared/Dropdown.js

Associated Issue:  #5512
* Use functional setState when derived from previous
[ ] Verify that each component still works as expected (I'll flesh this out in the morning)

Use functional setState when derived from previous

---

src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js

Fixes comments on #5539 which didn't make it in before it was merged. cc @jasonLaster

Fix PR comments for #5539

---

src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap

Associated Issue: #5491
Will be adding
Before
After

[Preview] should ignore some labels

---

src/components/Editor/ConditionalPanel.js
src/test/mochitest/browser_dbg-breakpoints-cond.js

Associated Issue: #4823
this fixes up the issue where mochitest wouldn't focus on the input

Fixup conditional bp test

---

package.json
yarn.lock

this pr bumps mochi so that we accurately report the error in babel-stepping.

Bump Mochitest

---

src/test/mochitest/browser_dbg-breakpoints-cond.js
src/test/mochitest/head.js

Small mochitest fix now that travis is properly failing again :)

Fixup Conditional Beakpoint panel test

---

src/workers/parser/findOutOfScopeLocations.js

We want to reuse lodash vendored in mc, and I don't think it includes the fp flavor of lodash.

Replace use of lodash/fp/get by lodash/get

---

src/components/App.js
src/components/Editor/Breakpoint.js
src/components/Editor/CallSites.js
src/components/Editor/HighlightLines.js
src/components/PrimaryPanes/index.js
src/components/SecondaryPanes/ChromeScopes.js
src/components/SecondaryPanes/EventListeners.js
src/components/SecondaryPanes/Expressions.js
src/components/SecondaryPanes/Frames/index.js
src/components/shared/Dropdown.js
src/components/shared/ResultList.js

Replace bind.this with fat arrow functions

---

src/components/App.js
src/components/Editor/SearchBar.js
src/components/Editor/index.js
src/components/ProjectSearch.js
src/components/SecondaryPanes/CommandBar.js
src/components/SecondaryPanes/index.js
src/components/shared/Modal.js

Get rid of prop-types

---

src/components/ProjectSearch.css
src/components/variables.css
src/utils/editor/source-editor.css

Associated Issue: #5566 
* Remove unused css variable
--theme-search-overlays-semitransparent
--theme-search-overlays-semitransparent
--theme-codemirror-gutter-background
* Fix typo with flex-grow css property

Fix css variable

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-babel-stepping.js

Associated Issue: #5585
- this updates the step locations
- the new locations seem better
---

Re-Enable babel-stepping test with the appropriate step positions

---

.eslintrc
package.json
src/actions/tests/__snapshots__/ast.spec.js.snap
src/utils/source.js
src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/utils/formatSymbols.js
yarn.lock

Support typescript mode

---

src/actions/breakpoints.js
src/actions/types.js
src/reducers/breakpoints.js
src/reducers/pending-breakpoints.js
src/test/mochitest/browser_dbg-breakpoints-toggle.js

Update Breakpoints state only once when "Toggle all breakpoints"

---

package.json

Bump node engine

---

configs/development.json
package.json
src/client/index.js
src/components/App.js
src/components/Editor/Editor.css
src/components/Editor/EditorMenu.js
src/components/Editor/index.js
src/main.js
src/reducers/expressions.js
src/test/mochitest/browser_dbg-breaking-from-console.js
src/test/mochitest/browser_dbg-sourcemaps-reloading.js
src/test/mochitest/browser_dbg-sourcemaps.js
src/test/mochitest/browser_dbg-toggling-tools.js
src/utils/bootstrap.js
webpack.config.js

Associated Issue: #4629 
* Stop using launchpad
* exclude libs
This brings the bundle size from 1.5 mb to 1.2mb. It also means we should see smaller diffs w/ the assets properties

Improve Bundle Size

---

webpack.config.js

Leftover comment from PR #5609

Document webpack.config redirecting unused files to flags module

---

src/test/mochitest/browser_dbg-babel-stepping.js
src/test/mochitest/browser_dbg-breakpoints-reloading.js
src/test/mochitest/browser_dbg-chrome-create.js
src/test/mochitest/browser_dbg-editor-select.js
src/test/mochitest/browser_dbg-layout-changes.js
src/test/mochitest/browser_dbg-sourcemaps-bogus.js
src/test/mochitest/browser_dbg-sourcemaps-reloading.js
src/test/mochitest/browser_dbg-sourcemaps.js
src/test/mochitest/browser_dbg-sourcemaps2.js
src/test/mochitest/browser_dbg-sourcemaps3.js

Fixes Issue: #5558
If tests pass CI we should be good to merge.

Fixes 5558 - Move requestLongerTimeout to global space

---

src/actions/sources/newSources.js

Fixes Issue: #4849
Previously, loading perf.html when it used webpack `eval-source-map` took about 17 seconds of heavy work. Now it takes about 4 seconds of less intensive work and feels pretty snappy.
* adds some checks from #5645, which prevent unnecessary updates
* batches all of the calls to `newSources` from `loadSourceMap`
Loading is now pretty snappy
NOTE: this also works for cheap-source-map
- lots of loadSourceMap calls
- lots of updateTree calls
- a few updateTree calls
- minimal loadSourceMap time

Improve loading sources

---

src/actions/ast/setInScopeLines.js

- Removes toJS from setInScopeLines

Removes toJS from setInScopeLines

---

package.json
yarn.lock

- Add mochici
- bump mochi to fix the log issues

Bump mochii

---

.flowconfig

I got pulled into fixing the flow config, which is something that's been on my list for awhile because i couldnt run flow locally.
This is a wip, but atleast it's working for me again

Fix flow config rules

---

src/actions/ast.js
src/actions/preview.js
src/actions/tests/ast.spec.js
src/actions/types.js
src/components/PrimaryPanes/Outline.js
src/reducers/ast.js
src/utils/breakpoint/astBreakpointLocation.js

*  Refactor the loading state of symbols #5554
* Should show a loading message in outline #5267

refactored loading states & added loading in outline

---

src/components/PrimaryPanes/Sources.css

Fix home button color for dark theme

---

src/components/variables.css

Fix #5668 - Restore missing CSS var

---

src/test/mochitest/browser_dbg-pretty-print-console.js
src/test/mochitest/browser_dbg-sourcemaps2.js

I broke a couple mochitests when i landed Rohan's loading PR. It was a slight intermittent.

Fix failing mochitests

---

src/actions/breakpoints/tests/syncing.spec.js
src/actions/pause/commands.js
src/actions/tests/pending-breakpoints.spec.js
src/components/Editor/Breakpoint.js
src/reducers/replay.js

Improves #5677
I looked into this briefly and found 2 issues:
1) hasAwait sometimes cannot get the line of text
2) replay expects to have the previous instance, sometimes it doesn't exist
We also were storing history even when the feature was off, that is now disabled

Fix a couple of stepping typeErrors

---

src/test/mochitest/browser_dbg-content-script-sources.js
src/test/mochitest/browser_dbg-editor-highlight.js
src/test/mochitest/browser_dbg-outline.js
src/test/mochitest/browser_dbg-pretty-print-console.js
src/test/mochitest/browser_dbg-preview-module.js
src/test/mochitest/browser_dbg-reload.js
src/test/mochitest/browser_dbg-sourcemaps2.js
src/test/mochitest/head.js

Fixes an intermittent we're seeing with the hasSymbols and the parser worker sending a message back after the test has finished.

Fixup console pretty print test

---

.travis.yml
src/actions/navigation.js
src/test/mochitest/browser_dbg-chrome-create.js

Backport changes made in mozilla-central for Bug 1382581

---

src/components/PrimaryPanes/SourcesTree.js

Reformat the getIcon code

---

.travis.yml
bin/dev-server.js
circle.yml
package.json
src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
src/components/shared/Svg.css
src/components/shared/tests/__snapshots__/ManagedTree.spec.js.snap
src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
src/test/mochitest/browser_dbg-babel-scopes.js
src/test/mochitest/head.js
webpack.config.js
yarn.lock

Reps 0.21.1

---

src/test/mochitest/browser_dbg-editor-select.js

Editor select has been intermittent recently.

Fix editor-select

---

src/actions/navigation.js

Fixes Issue: #5720, 5731
Clears directory root when moving to another domain

Clear the directory root when navigating domains

---

src/test/mochitest/head.js

The race was causing a promise to stay around

Fix babel-preview leak

---

src/reducers/ast.js
src/selectors/isSelectedFrameVisible.js
src/test/mochitest/browser_dbg-preview-source-maps.js
src/test/mochitest/head.js
src/utils/makeRecord.js

Fixes Issue: #5499
* fixes a simple logic issue w/ generated locations (thanks @AnshulMalik for the code sample)
* adds a new assertion to a mochitest

Fix previewing generated locations

---

src/components/SecondaryPanes/Frames/Frames.css

Fix dark 'show more' button

---

src/actions/tests/helpers/threadClient.js
src/actions/tests/pause.spec.js

We were getting some exceptions in the Jest tests

Add additional mocks

---

src/actions/breakpoints/syncBreakpoint.js
src/actions/expressions.js
src/actions/pause/continueToHere.js
src/actions/preview.js
src/reducers/sources.js

- Removed a bunch more toJS
- cleaned up unused modifier references

Removes toJS in more files

---

docs/dbg.md
src/actions/file-search.js
src/actions/pause/mapScopes.js
src/actions/project-text-search.js
src/actions/sources/prettyPrint.js
src/actions/sources/select.js
src/actions/sources/tests/loadSource.spec.js
src/actions/sources/tests/select.spec.js
src/components/Editor/EditorMenu.js
src/components/Editor/Footer.js
src/components/Editor/Tab.js
src/components/Editor/Tabs.js
src/components/Editor/index.js
src/components/SecondaryPanes/Breakpoints.js
src/test/mochitest/browser_dbg-editor-highlight.js
src/test/mochitest/head.js
src/utils/isMinified.js
src/utils/quick-open.js
src/utils/source.js
src/utils/tabs.js
src/utils/tests/source.spec.js
src/workers/pretty-print/index.js

Fixes Issue: #5738
- First part of removing .get calls
- 1 updated test with Immutable removed

Removes .get - Part 1

---

src/components/PrimaryPanes/SourcesTree.js
src/components/shared/Svg.css

Restore sources tree icons

---

src/components/Editor/EditorMenu.js
src/utils/ast.js
src/utils/breakpoint/astBreakpointLocation.js
src/utils/function.js

This is a precusor PR leading up to #5659. Just a refactor to keep the real PR small. (I'll put it up after this one.)

Refactor findClosestScope -> findClosestFunction 

---

assets/panel/prefs.js
src/actions/pause/fetchScopes.js
src/actions/preview.js
src/actions/types.js
src/components/Editor/Preview/index.js
src/components/SecondaryPanes/FrameworkComponent.js
src/components/SecondaryPanes/index.js
src/reducers/pause.js
src/utils/prefs.js

Fixes Issue: #3800 -- 5: Show component instances in the sidebar.
* Added new FrameworkComponent.
* Separated out function to get extra props.
* Currently validated through the browser, will add tests.

[Preview] React Component pane

---

src/components/shared/ResultList.js

Fixes Issue: #5785 
* Fixed empty item on source search show

Fixed empty item in the search show, issue #5785

---

src/test/mochitest/browser_dbg-navigation.js
src/test/mochitest/browser_dbg-pause-ux.js
src/test/mochitest/browser_dbg-reload.js
src/test/mochitest/browser_dbg-stepping.js
src/test/mochitest/head.js
src/workers/parser/pausePoints.js

Fixes Issue: #5753 
just tightening the tests a bit

Tweak mochitests for pause points

---

src/actions/preview.js
src/actions/tests/__snapshots__/ast.spec.js.snap
src/utils/ast.js
src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/utils/formatSymbols.js

Fixes Issue: #5695
* add literals for computed expressions

added literals for computed member expressions

---

src/workers/parser/pausePoints.js
src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
src/workers/parser/tests/pausePoints.spec.js

I've been seeing the following TypeError in the console when opening HTML files:  `lastStatement is undefined`

Fix TypeError:  lastStatement is undefined

---

src/actions/preview.js
src/types.js
src/utils/ast.js
src/utils/editor/get-expression.js
src/utils/editor/get-token-location.js
src/workers/parser/index.js
src/workers/parser/types.js

#5772 
- Tightens the flow rules.
- trying to find the root of the recursion bug

Tighten flow

---

src/actions/preview.js
src/actions/types.js
src/components/Editor/index.js
src/components/PrimaryPanes/Outline.js
src/reducers/ast.js
src/utils/ast.js
src/utils/editor/get-expression.js
src/utils/editor/source-documents.js
src/utils/quick-open.js
src/utils/tests/__snapshots__/ast.spec.js.snap
src/workers/parser/getSymbols.js
src/workers/parser/index.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/types.js
src/workers/parser/utils/formatSymbols.js
src/workers/parser/utils/inferClassName.js
src/workers/parser/utils/simple-path.js

Fixes Issue: #5707
This PR consists one error message as shown in the screenshot.

Add flow coverage to parser/types.js

---

src/actions/breakpoints/addBreakpoint.js
src/actions/breakpoints/syncBreakpoint.js
src/actions/breakpoints/tests/__snapshots__/syncing.spec.js.snap
src/actions/tests/__snapshots__/breakpoints.spec.js.snap
src/components/SecondaryPanes/Breakpoints.css
src/components/SecondaryPanes/Breakpoints.js
src/utils/breakpoint/index.js
src/utils/source.js

I wanted to show progress on this.  This:
- Removes the `snippet` element as it hasn't been used and we'll not be using it in the redesign
- Stores breakpoint text at a given line

Get breakpoint text

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-preview-module.js
src/test/mochitest/browser_dbg-preview.js
src/test/mochitest/examples/doc-preview.html
src/test/mochitest/examples/preview.js
src/test/mochitest/head.js

Fixes Issue: #5829 
* starts a mochitest to document the current behavior
* update behavior so that we're consistent

Document preview

---

src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/tests/fixtures/callExpressions.js
src/workers/parser/tests/fixtures/object-expressions.js
src/workers/parser/tests/getSymbols.spec.js
src/workers/parser/utils/helpers.js

Issue: #5695
I got this error, when adding my case. Has to do with an Eslint Complexity rule.
* add getAncestor(number) function to find an ancestor of the current path
* allow 'a' in > dispatch({ a }) to be previewed
* allow 'a' in > function evaluate(script, { a } = {a: 2}) to be previewed
Updated
Hit 'stuff' while running debugger on the page below, and try out some break points.
https://flax-sort.glitch.me/ (Updated: 03/26/2018)

[Preview] Evaluate Object properties with an assignment

---

src/components/SecondaryPanes/BreakpointItem.js
src/components/SecondaryPanes/Breakpoints.js
src/types.js
src/workers/parser/getSymbols.js

This is far enough along to request review

Create a BreakpointItem component to make Breakpoints component cleaner

---

.travis.yml
src/test/mochitest/browser_dbg-expressions-error.js

This test was changed in https://bugzilla.mozilla.org/show_bug.cgi?id=1448431#c3

Backport expression error test

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-babel-breakpoint-console.js

Adding mochitest from https://bugzilla.mozilla.org/show_bug.cgi?id=1450145

Add test already added in MC bug 1450145.

---

src/utils/bootstrap.js

[Flow] src/utils/bootstrap.js - add type defs for flow coverage

---

src/actions/pause/paused.js
src/actions/project-text-search.js
src/reducers/expressions.js
src/reducers/types.js

Fixes Issue: #5842 
* Add Record<State> which was needed to make flow happier

add flow header to reducers/types.js

---

src/utils/DevToolsUtils.js

[Flow] src/utils/DevtoolsUtils.js - add type defs for flow coverage

---

src/utils/wasm.js

Fixes Issue: the wasm name section is not used for names
* Attempt to read the section and use it during disassembly
* Open and debug https://yurydelendik.github.io/sqlite-playground/src/playground.html
* Notice that function names are not autogenerated (i.e. starts with `$func`)

Enable reading of the wasm name section to display debug names in text

---

src/actions/preview.js
src/components/Editor/Preview/index.js
src/selectors/isSelectedFrameVisible.js
src/test/mochitest/browser_dbg-preview-source-maps.js
src/test/mochitest/browser_dbg-preview.js

[Preview] stop showing preview for the wrong original files

---

src/components/ProjectSearch.css

Fixes Issue: #5863 
Project Search has a new visual style 
If developer is using keyboard focus shortcuts (tab, arrow down, arrow up) he will be will able to see this design -> https://youtu.be/BmGHVwKNj1Y
cmd+shift+f
type something and enter
tab over to the item

[ProjectSearch] Focus state colors are a bit off #5863

---

src/utils/clipboard.js

[Flow] src/utils/clipboard.js - add type defs for flow

---

src/utils/dbg.js

Fixes Issue: #5120 
- Did I declare the callbacks properly?

[Flow] src/utils/dbg.js - add type defs for flow

---

src/components/SecondaryPanes/BreakpointItem.js

Fix memory leak by setting editor to null

---

src/components/SecondaryPanes/Breakpoint.js
src/components/SecondaryPanes/BreakpointItem.js
src/components/SecondaryPanes/Breakpoints.js

Makes the BPI component way easier to read and maintain

Move BreakPointItem elements to their own rendering functions

---

docs/pull-requests.md

Added link to gif software for ubuntu

---

src/utils/ui.js

Added // @flow header and Object type to getLineNumberWidth() function
Added // @flow header and object type to getLineNumberWidth() function
Added Object type to getLineNumberWidth() function
Revert "Added Object type to getLineNumberWidth() function"
This reverts commit ce4a01aef5934036f9c9f4b0ae82acdc7452aaba.
Revert "Added // @flow header and object type to getLineNumberWidth() function"
This reverts commit 6df2fe30002619238b86603b5642b688b72a3dc9.
Reverted to original, then added Object type to getLineNumberWidth()
Fixes Issue: #5120
* Added // @flow header and Object type to getLineNumberWidth() function in ui.js file …

Added @flow header and Object type to getLineNumberWidth()

---

src/components/Editor/Tabs.css

Fix active tab underline

---

src/components/PrimaryPanes/SourcesTree.js

I'm probably crazy but I swore I sent this in earlier, but I can't find the old PR or the code in master, so I'll submit again....

Fix angular icon in sources tree

---

src/components/SecondaryPanes/CommandBar.js
src/components/SecondaryPanes/UtilsBar.js
src/components/shared/Button/CommandBarButton.js

I thought I could let this go but it bugged me so I just changed it quick.

Move debugBtn to a better spot

---

src/test/mochitest/browser_dbg-babel-preview.js
src/test/mochitest/browser_dbg-babel-scopes.js

this was necessary due to release 34's perf regressions.

Extend babel- timeouts

---

.travis.yml
src/actions/types/ASTAction.js
src/client/firefox/commands.js
src/reducers/ast.js
src/utils/ast.js
src/utils/pause/pausePoints.js
src/workers/parser/getScopes/visitor.js
src/workers/parser/index.js
src/workers/parser/pausePoints.js
src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
src/workers/parser/tests/fixtures/calls.js
src/workers/parser/types.js

Fixes  #5764 
* switches to dictionary
* changes stepOver to step
* will add additional empty pause points

(WIP) Update pause points

---

assets/panel/debugger.properties
src/components/SecondaryPanes/Breakpoints.js

#5932  #5972
Fixes l10n issue.
Is this the appropriate fix?

Fix l10n key (pauseOnExceptions)

---

assets/dictionary.txt
docs/spider-monkey.md

Should help give debugger devs some tips on getting started with spidermonkey
- where the code is
- how to build a shell
- how to run the tests

Start spider monkey docs

---

src/utils/pause/pausePoints.js

This keeps popping up so I may as well commit it :)

Fix linting issue in pausepoints

---

package.json
yarn.lock

Bump source-map to 16

---

src/test/mochitest/browser_dbg-babel-preview.js
src/test/mochitest/head.js

Fixes Issue: #5995 
- we're now clearing via actions as opposed to flaky hovers

Fix preview int

---

assets/images/Svg.js
assets/images/help.svg
postcss.config.js
src/components/SecondaryPanes/CommandBar.css

this updates the svg logic so we can re-use mc svgs

Use mc help svg

---

src/components/SecondaryPanes/Breakpoints.js

Not using this index, don't need it

Remove unused index

---

assets/panel/prefs.js
src/actions/ast.js
src/utils/prefs.js

If someone wants to turn off pause points its important that they can safely do that.

Feature flag pause points

---

src/components/SecondaryPanes/Expressions.js
src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap

Display the expressions input if no expression exists

---

src/components/SecondaryPanes/Breakpoint.js

Change line based on prettyprint or original source

---

src/components/SecondaryPanes/Expressions.css

Update dark theme expression outline to blue-50

---

assets/images/command-chevron.svg
src/components/Editor/Tabs.css
src/components/Editor/Tabs.js
src/components/SecondaryPanes/CommandBar.css

Fixes Issue: #6012
Changed the icon. Although not sure if this is the fix that is required.

[Tabs] Update the show more button 

---

packages/devtools-components/src/tests/tree.js
src/components/Editor/Preview/Popup.js

These keep popping up when I push so I'll just fix them

Lint fixes

---

src/components/Editor/Preview/Popup.css
src/components/Editor/Preview/Popup.js

* #6044 simplified preview for immutable, but removed formatting for react
* This adds it back and adds a new react logo

[Preview] Re-add react preview

---

packages/devtools-source-map/src/index.js
packages/devtools-source-map/src/worker.js
src/components/Editor/Preview/Popup.js
src/components/Editor/SearchBar.js
src/components/QuickOpenModal.js
src/components/SecondaryPanes/index.js

Incorporates linter changes that pop up after every save.

Handles rogue lints

---

src/components/SecondaryPanes/Breakpoints.css
src/components/SecondaryPanes/Expressions.css
src/components/SecondaryPanes/SecondaryPanes.css

Last breakpoint style nits

---

packages/devtools-utils/src/worker-utils.js

Initially made the PR on devtools-core, but in the meantime the package moved here.
https://github.com/devtools-html/devtools-core/pull/1056

Guard against null worker in /devtools-utils/src/worker-utils.js

---

package.json
yarn.lock

update lint staged to a version that supports node 10

update lint staged to a version that supports node 10

---

src/actions/preview.js
src/components/Editor/Preview/Popup.js
src/components/Editor/Preview/index.js
src/components/shared/Popover.js

Fixes Issue: #5406 
The preview window no longer gets stuck when quickly hovering over a given debug expression.

[Preview] avoid windows getting stuck

---

src/components/shared/Modal.js
src/components/shared/tests/Modal.spec.js
src/components/shared/tests/__snapshots__/Modal.spec.js.snap

Adds a few tests to see the Modal component works.

Adds a few Modal tests

---

src/actions/tests/ast.spec.js
src/actions/tests/fixtures/reactFuncComponent.js
src/workers/parser/frameworks.js

Fixes Issue: #6073
Supercedes: https://github.com/devtools-html/debugger.html/pull/6074
Moved @yaeballa's PR to a feature branch and added a modification to prevent test issues.

Find react by import and function

---

src/workers/search/project-search.js
src/workers/search/tests/__snapshots__/project-search.spec.js.snap
src/workers/search/tests/project-search.spec.js

- Refactors project-search
- Adds project-search tests

Works on project-search

---

src/workers/parser/utils/ast.js

Fixes Issue: #5986
This addresses a babel issue so that we dont assume the file is a script. There are other issues now with the server:

[Parser] switch to unambiguous modules

---

src/utils/editor/tests/source-search.spec.js

Added unit test for work for issue: #3829
* Added unit test for function searchSourceForHighlight.
The unit test checks that the function does the following:
* calls into CodeMirror APIs, especially to set the overlay
* calls `alignLine` on the right line
* calls `setSelection` on the right lines and characters

 Added unit test for function searchSourceForHighlight.

---

.travis.yml
src/test/mochitest/browser.ini

Sync test change from https://bugzilla.mozilla.org/show_bug.cgi?id=1098374

Synchronize test changes from Bug 1098374

---

.travis.yml

Updates python to 3.6, which lets us stay upto date with MC .

Fix travis3

---

src/components/SecondaryPanes/Breakpoints.css

Fixes Issue: #6268
@digitarald asked for pointer cursors on breakpoint items and that's what @digitarald gets!
👍 😄

Fix #6268 - Use pointer cursor for breakpoints

---

src/components/SecondaryPanes/Breakpoints.css

Fixes Issue: #6274
Smoother and faster!  Not including a GIF because it wouldn't be representative.

Make breakpoint animation smoother and faster

---

bin/copy-modules.js

makes copy-modules a bit more resiliant

[build] Add try/catch for copy-modules

---

src/actions/utils/middleware/log.js

it was causing exceptions in mochii...

blacklist remove_breakpoint from middleware/log

---

src/components/Editor/Preview/Popup.js

Fix #6201 - Prevent relatedTarget.classList error

---

bin/copy-assets.js
bin/copy-modules.js
bin/copy.js
docs/bundling.md
docs/debugging-firefox.md
docs/running-as-firefox-panel.md
package.json

This unifies the copy-assets and copy-modules stuff

Improve the process for copying changes

---

src/components/WelcomeBox.css
src/components/WelcomeBox.js
src/components/test/__snapshots__/WelcomeBox.spec.js.snap

Make text color dark, cursor pointer for welcome box

---

src/actions/project-text-search.js

All other actions in the file are generated by functions, this was the only one left to be moved.

Moves ADD_SEARCH_RESULTS to own action creator

---

packages/devtools-components/webpack.config.js

- `cd packages/devtools-components;yarn storybook`
- Make sure you can access the storybook

Fix devtools-components storybook config

---

src/components/SecondaryPanes/Breakpoints.css
src/components/SecondaryPanes/Expressions.css

Fix #6333 - Prevent overflow of contents for expressions

---

src/components/Editor/Tabs.css
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-preview.js

A couple of things that were in our release branch, but should have also been in master
Note, I'm also copying over the changes that were in master, but should have been in release [here](https://github.com/devtools-html/debugger.html/compare/28f2817...release-56). Let me know if i missed something that should go here. For example, if some of the CSS was correct in the release branch and wrong here, we should add it to this commit so it doesnt get changed in MC!

sync changes from release 56

---

docs/running-as-firefox-panel.md

browser toolbox

---

.travis.yml
bin/ci/build-firefox.sh

Teach travis to fail if the build fails

Start failing if the build fails

---

src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
src/components/test/__snapshots__/ShortcutsModal.spec.js.snap
src/components/test/__snapshots__/WelcomeBox.spec.js.snap

This happened as a result of a recent photon-related PR.

Fix jest tests from Loading message update

---

src/components/SecondaryPanes/Breakpoint.js
src/components/SecondaryPanes/Breakpoints.js
src/selectors/index.js
src/selectors/mappedBreakpoints.js
src/utils/breakpoint/index.js
src/utils/pause/why.js

* cleans up breakpoint location logic
* will now select the exact location

Add mappedBreakpoints

---

src/components/SecondaryPanes/Expressions.css

Vertically center the expression close button

---

.github/SUPPORT.md

[Docs] Add SUPPORT.md to .github folder.

---

src/workers/parser/utils/helpers.js

[parser] add parent.value check in isObjectShorthand

---

src/test/mochitest/browser_dbg-scopes-mutations.js

Fix scopes-mutation intermittent

---

bin/copy-assets.js

[releases] check if the file exits

---

.travis.yml
src/components/SecondaryPanes/Breakpoints/Breakpoint.js
src/utils/editor/index.js

small tweaks needed to land the new pure component

[Breakpoints] touch up breakpoint class

---

src/actions/preview.js
src/components/Editor/Preview/Popup.js
src/components/Editor/Preview/index.js
src/components/Editor/index.js
src/components/SecondaryPanes/Breakpoints/Breakpoint.js
src/components/shared/Popover.js
src/components/shared/tests/Popover.spec.js
src/components/shared/tests/__snapshots__/Popover.spec.js.snap
src/reducers/ast.js
src/reducers/pause.js
src/test/mochitest/helpers.js
src/utils/editor/index.js
src/utils/editor/token-events.js

Fixes Issue: #6193 
Goals:
1. Display/hide preview via OnToken events
2. A preview should be cleared via OnPreviewLeave when hovering off the popup.

[Preview] Switch to token-over

---

docs/debugging-the-debugger.md

Fixes Issue: #6460
Updates debugging-the-debugger.md to reflect the correct line numbers, filename and source code.

Update line numbers and filename in debugging-the-debugger.md

---

src/components/test/__snapshots__/SourcesTree.spec.js.snap

I think there was a clash between the sources cleanup and relative sources that caused this problem.  Both were green when I merged them.  Weird.

Fix sourcestree snapshot

---

packages/devtools-components/src/tree.js

This code was not being used so removed it.

remove unused code in devtools-components/tree.js

---

package.json
yarn.lock

* We lucked out! No errors upgrading four versions. :tada:

⬆️: Upgrade Flow to latest (0.74.0)

---

flow-typed/npm/lodash_v4.x.x.js
src/components/PrimaryPanes/Outline.js
src/components/shared/PreviewFunction.js
src/selectors/breakpointSources.js
src/utils/pause/frames/annotateFrames.js
src/utils/pause/scopes/getVariables.js

Fixes Issue: #5122
add types for lodash

[flow] type lodash

---

src/utils/editor/tests/get-expression.spec.js

Here is a draft of some tests.  Can you let me know how they look so far?

Tests for utils/editor/get-expressions

---

src/actions/breakpoints.js

[breakpoints] Improve perf of toggle and removing breakpoints

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-pause-points.js
src/test/mochitest/browser_dbg-preview-module.js
src/test/mochitest/helpers.js

Improves the reliability of the preview tests so that we can land @haorchen's work for tokenOver in mc.

[preview] address intermitent failures

---

src/components/Editor/Breakpoint.js

Fixes Issue: #6541
* Change to use `PureComponent`

use PureComponent

---

src/components/Editor/index.js
src/utils/editor/index.js
src/utils/editor/source-documents.js
src/utils/indentation.js

* adds flow types for Editor/index
* there is a funny thing with `nextProps.selectedSource` where we had to refactor to help flow
* the main issue now is that codeMirror is not typed

[Editor] Type editor

---

.babel/transform-mc.js
bin/copy-modules.js
bin/tests/__snapshots__/copy-modules.spec.js.snap
bin/tests/copy-modules.spec.js
bin/tests/fixtures/default-telemetry-import.js
bin/tests/fixtures/imports.js
bin/tests/fixtures/single-telemetry-import.js
bin/tests/fixtures/transforms.js

Fixed telemetry import to point at devtools module using transform-mc.js

[Telemetry] Fixed telemetry import to point at devtools module using transform-mc.js

---

src/components/shared/SourceIcon.css

[Tabs] Show Angular icon properly in tabs

---

src/actions/sources/select.js
src/actions/ui.js
src/reducers/sources.js

Fixes Issue: #6544
Can you let me know if I am on the right track by doing it this way?

[Sources] Update file search results when source changes

---

src/components/PrimaryPanes/index.js

Removes unused function and field annotations. Extracted from #6595.
@jasonLaster

Remove unused function and field annotations

---

bin/copy-modules.js

@nchevobbe switched to this plugin in his unbundle reps PR and it was a pretty good idea 😉 
This gets us some nice perf wins and will also clean up the code. Thanks!

Support object spread

---

src/actions/pause/tests/pause.spec.js

Move the test into a more specific directory

move pause.spec

---

src/components/Editor/Footer.js

Just spotted this and needed to fix it ASAP

Footer.js nit

---

src/components/Editor/index.js

Small touch up. A couple of weeks ago we thought that flow wouldnt support this, it must have been some other issue that was blowing up. It feels great to have a flow "bug" actually be fine.

[flow] remove unnecessary destructuring

---

src/test/mochitest/browser_dbg-tabs-pretty-print.js

@jasonLaster and I talked about adding this to prevent regressions in tab titles.

Add label test for pretty print

---

src/utils/pause/pausePoints.js
src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap

The tests include the # of the point, which is not that useful. It also means that changing a fixture means that everything updates, which is distracting

[Parser] update pause points test fixtures

---

src/actions/pause/paused.js
src/test/mochitest/browser_dbg-returnvalues.js
src/test/mochitest/browser_dbg-sourcemaps.js
src/test/mochitest/browser_dbg-stepping.js

Fixes some issues introduced by #6660

[Parser] tweak pause points to wrt end of functions

---

src/workers/parser/tests/mapBindings.spec.js
src/workers/parser/tests/mapExpression.spec.js

I've been seeing this every time I push so time to fix up!

Fix spec quotes

---

src/test/mochitest/browser_dbg-pause-points.js
src/test/mochitest/browser_dbg-stepping.js
src/workers/parser/pausePoints.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
src/workers/parser/tests/fixtures/calls.js
src/workers/parser/tests/fixtures/func.js
src/workers/parser/tests/fixtures/statements.js
src/workers/parser/tests/pausePoints.spec.js
src/workers/parser/utils/simple-path.js

While we were testing stepping @loganfsmyth and I found two interesting cases
`(1, f())` and `[ f() ]` both cases had some surprising results.
1. `(1, f())` => we should pause at f() not 1
2. `[ f() ]` => we should pause at f(), not [
Jest

[Parser] teach pause points about sequence expressions

---

src/actions/breakpoints/addBreakpoint.js
src/actions/breakpoints/index.js
src/actions/breakpoints/tests/breakpoints.spec.js
src/actions/pause/commands.js
src/actions/sources/blackbox.js
src/actions/sources/prettyPrint.js
src/components/Editor/Footer.js
src/test/tests-setup.js
src/utils/dbg.js
src/utils/telemetry.js
src/utils/test-head.js

 Fix #6533 - Add simple telemetry

---

src/components/ProjectSearch.css
src/test/mochitest/helpers.js

[Search] Updated padding for search results

---

src/utils/telemetry.js

Prevents storing telemetry data locally when running in the panel.

[telemetry] only store events in development and testing

---

src/utils/sources-tree/updateTree.js

[SourceTree] fix left arrow behaviour

---

src/utils/source.js

Supercedes https://github.com/devtools-html/debugger.html/pull/6620
I've added style changes

Disable pretty print when sourcemaps are disabled

---

src/components/shared/tests/Svg.spec.js
src/components/shared/tests/__snapshots__/Svg.spec.js.snap

Add test for Svg.js

---

src/test/mochitest/browser_dbg-sourcemaps-bogus.js

[test] Fix dbg-sourcemaps-bogus intermittent

---

src/actions/sources/newSources.js
src/actions/sources/prettyPrint.js
src/actions/sources/tests/__snapshots__/prettyPrint.spec.js.snap
src/client/firefox/create.js
src/selectors/getRelativeSources.js
src/types.js
src/utils/quick-open.js

remove relative source type

---

src/vendors.js

Remove "url" from vendors.js

---

packages/devtools-reps/src/object-inspector/component.js
packages/devtools-reps/src/object-inspector/tests/component/expand.js
src/vendors.js

Commit fixes introduced automatically when running `yarn lint`.

Commit fixes introduced by running the linter

---

src/components/SecondaryPanes/Breakpoints/ExceptionOption.js
src/components/SecondaryPanes/Breakpoints/index.js
src/components/SecondaryPanes/Breakpoints/tests/ExceptionOption.spec.js
src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/ExceptionOption.spec.js.snap

Fixes Issue: #6403
- refactors createExceptionOption to be ExceptionOption component
- adds render tests to component

[SecondaryPanel] Makes createExceptionOption a component

---

src/utils/pause/scopes/getScope.js

This should have been removed in the upgrade flow-bin pr 2 minutes ago. 
P.S. Jason should not merge things during meetings

Remove BindingContents

---

src/components/SecondaryPanes/Breakpoints/index.js
src/reducers/pause.js
src/types.js
src/utils/pause/mapScopes/index.js
src/utils/pause/scopes/getScope.js
src/utils/pause/scopes/getVariables.js

Fixes: #6746
initial fix, but needs some help with flow

[pause] accomodate with blocks

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg_rr_breakpoints-01.js
src/test/mochitest/examples/doc_rr_basic.html
src/test/mochitest/head.js

Bug 1479058 Part 12 - Test changes, r=jlast.
Bug 1480994 - Only run web replay test on nightly builds, r=aryx.
Bug 1465491 - Add one web replay test.
Bug 1465491 Part 2 - Helper functions for web replay mochitests, r=jryans.

[sync] web replay patches

---

src/utils/sources-tree/addToTree.js
src/utils/sources-tree/collapseTree.js

Fixes Issue: #6769
WTF? @jasonLaster

Cleanup questionable logs and errors

---

src/actions/breakpoints/addBreakpoint.js
src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap
src/actions/breakpoints/tests/breakpoints.spec.js
src/reducers/pending-breakpoints.js
src/selectors/breakpointSources.js

Fixes Issue:  #5570 
addresses the syncing issues, which would come about when enabling a breakpoint after the code has moved.
followed case #1 in this [doc](https://docs.google.com/document/d/1VDSyP4N2WPlmbi1s3ZiJWm9_HBB4nOsngZaeX1lH81s/edit).

[breakpoints] Fix syncing cases with toggling

---

src/actions/preview.js
src/components/Editor/index.js

* we should allow inline preview now for time travel 
* continue to here should be cmd click. I've been meaning to switch it and have always forgotten. This is really useful for time travel

[webreplay] tweak preview and continue to here

---

src/components/Editor/index.js
src/components/PrimaryPanes/SourcesTree.js
src/components/PrimaryPanes/SourcesTreeItem.js
src/components/PrimaryPanes/tests/__snapshots__/SourcesTree.spec.js.snap

Remove unwanted attribute from breadcrumb

---

src/actions/sources/newSources.js

This cleans up a check that has irked me for some time because it should be unnecessary.

[sources] update newSources filter check

---

src/components/Editor/index.js
src/utils/editor/index.js

Fixes Issue: #6353
The issue is determing what the scroll offset of the editor is, which is a bit tricky when the document is loading

[Editor] fix scrolling while loading

---

src/components/PrimaryPanes/SourcesTree.js
src/components/PrimaryPanes/SourcesTreeItem.js
src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js
src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
src/reducers/sources.js

Fixes Issue: #5663 
This addresses the first of three issues with original sources that share a URL with a generated source. The other two issues are saved breakpoints and tabs. I think this is safe to land by itself and we can tackle the other two in their own PRs.
NOTE: the first commit is in another PR

[sources] add [sm] to source tree

---

src/components/PrimaryPanes/SourcesTreeItem.js
src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap

Helps Issue: #6821
Moving the suffix to its own element will help style it for #6821

Move suffix to separate element for easier styling

---

src/selectors/visibleBreakpoints.js

I wanted to file a bug for the debuggers pausing performance and when i gathered a profile I found a ridiculous number of Breakpoint.addBreakpoint calls, so instead I put together a prototype fix that memoizes all the things. To be fair, i don't think this is great code, but it is interesting and I'd like to continue exploring some of these things

[breakpoints] memoize Breakpoints component

---

src/utils/pause/mapScopes/index.js

Issue: #6820 
* checks for line mappings and bails early
* does not try to show a helpful error message

[scopes] detect line-based mappings

---

assets/dictionary.txt
docs/dbg.md
src/utils/dbg.js

- fixes an issue with findSource
- adds findSources

[dbg] update findSource helper

---

package.json
yarn.lock

bump launchpad to 134

---

src/actions/ast.js
src/actions/sources/newSources.js
src/actions/sources/select.js
src/actions/sources/tests/newSources.spec.js
src/actions/sources/tests/select.spec.js
src/actions/tabs.js
src/actions/tests/project-text-search.spec.js
src/actions/tests/tabs.spec.js
src/actions/types/SourceAction.js
src/actions/types/index.js
src/components/Editor/Tab.js
src/components/PrimaryPanes/SourcesTree.js
src/components/PrimaryPanes/SourcesTreeItem.js
src/reducers/sources.js
src/reducers/tabs.js
src/test/mochitest/browser_dbg-tabs-pretty-print.js
src/test/mochitest/helpers.js

Fixes Issue: #6822
This is a very early WIP for creating tabs based on URL *and* original/generated state.
Opening tabs from sources tree works *OK* but sometimes the tab refuses to switch to generated vs. original; it's kinda weird.  Close tab closes both tabs but that's because I've not implemented that functionality yet.

[tabs] Create tabs for sourcemapped files

---

src/components/PrimaryPanes/Sources.css

Fix source mapped label

---

src/actions/pause/mapFrames.js
src/actions/pause/mapScopes.js
src/actions/sources/loadSourceText.js
src/actions/sources/newSources.js
src/client/firefox/commands.js
src/client/firefox/events.js
src/reducers/sources.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-reloading.js

Fixes Issue: #6457
* fixed an issue i saw in the browser console here
We should re-try this STR

[sources] double check whether a source is present

---

src/components/Editor/index.js
src/utils/editor/source-documents.js

some small codemirror optimizations ...

[editor] improve codemirror operations

---

src/components/PrimaryPanes/SourcesTree.js
src/reducers/source-tree.js

Small refactor to help the sources tree logic be more consistent with managed tree which uses a Set for expanded state

[sources] switch expanded field from Immutable to Set

---

src/components/WelcomeBox.css

Fixes Issue: #6941
* Removed transition for hovering links on welcome screen

Removing transition from welcome page links (fixes #6941)

---

packages/devtools-reps/src/reps/accessible.js
packages/devtools-reps/src/reps/rep.js
packages/devtools-reps/src/reps/reps.css
packages/devtools-reps/src/reps/stubs/accessible.js
packages/devtools-reps/src/reps/tests/accessible.js

Fixes Issue: #6932 
* Added accessibility rep, similar but simpler than Element node rep.
* Added tests
Added unit tests for the rep, also tried using it in m-c with a local copy.

Add accessible rep to reps package (#6932)

---

src/actions/ast.js
src/actions/expressions.js
src/actions/pause/mapScopes.js
src/actions/preview.js
src/actions/sources/loadSourceText.js
src/actions/sources/newSources.js
src/components/Editor/Footer.js
src/components/PrimaryPanes/SourcesTreeItem.js
src/components/SecondaryPanes/Breakpoints/Breakpoint.js
src/reducers/pending-breakpoints.js
src/reducers/sources.js
src/selectors/breakpointAtLocation.js
src/selectors/getCallStackFrames.js
src/utils/editor/index.js
src/utils/pause/stepping.js
src/utils/source.js

Supercedes:  https://github.com/devtools-html/debugger.html/pull/6907

Use isOriginal and isGenerated instead of ID checks

---

assets/images/disable-pausing.svg

Fixes #6986 
Added license header in assets/images/disable-pausing.svg
Feel free to suggest changes
Regards,
@nightwarrior-xxx

Added license header in assets/images/disable-pausing.svg #6986

---

src/components/Editor/Editor.css

Fixes #6330 
Changed colors of line numbers to grey color.

Empty line 6330

---

src/utils/sources-tree/getDirectories.js

Remove commented code from getDirectories

---

src/actions/sources/tests/select.spec.js
src/client/index.js
src/components/shared/Button/tests/CommandBarButton.spec.js
src/reducers/tabs.js
src/test/tests-setup.js
src/utils/prefs.js

Fixes #6546 
* Switch to use async storage

Async storage tabs

---

README.md

Fixes #7046 
* Changed hour to earlier
* Added spaces between hours to prevent remark lint errors

[Docs] Change time of community meeting #7046

---

src/components/PrimaryPanes/SourcesTreeItem.js

We literally have a function for this.  Like...I even coded it.  I suppose I should use it.
/me retires

Condense code for getHasMatchingGeneratedSource

---

bin/post-checkout.js
package.json

the script was crashing because GIT_PARAMS was not available

husky updates

---

src/test/mochitest/browser_dbg-asm.js
src/test/mochitest/browser_dbg-chrome-debugging.js

* One missed place from #7043
* One test relying on the left-hand tree behavior from before #7012

Fix two test failures.

---

.travis.yml
src/actions/sources/newSources.js
src/actions/sources/tests/select.spec.js
src/components/Editor/Editor.css
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-sourcemapped-scopes.js
src/test/mochitest/browser_dbg-stepping.js
src/test/mochitest/helpers.js

[sync] backport release 93

---

.circleci/config.yml
package.json

Let's try using the official greenkeeper

use latest greenkeeper

---

src/actions/tabs.js
src/actions/types/index.js
src/components/Editor/EditorMenu.js
src/components/Editor/Tab.js
src/reducers/sources.js
src/reducers/tabs.js
src/selectors/test/getCallStackFrames.spec.js
src/test/mochitest/browser_dbg-tabs.js
src/utils/source.js

Fixes #5102
Continuation of #7082 
* Add tabs for URL-less sources
* Store URL-less tabs in redux but not in prefs
* When having a URL-less tab open and focused, when refreshing the page, the URL-less tab doesn't get focused
* Add mochi test

Add tabs for sources without URLs

---

src/test/mochitest/browser_dbg-xhr-breakpoints.js

Minor comments to describe what's intended by each test

Add comments for each XHR breakpoint test

---

src/utils/result-list.js

added flow to result.js

---

src/global-types.js

one part of #5120 
Added Flow in src/global-types.js

Fixes 5120: Added Flow in src/global-types.js

---

src/actions/breakpoints/remapLocations.js

Added Flow in src/actions/breakpoints/remapLocations.js

---

src/components/SecondaryPanes/Frames/Frame.js
src/components/SecondaryPanes/Frames/Group.js
src/components/SecondaryPanes/Frames/index.js
src/components/SecondaryPanes/Frames/tests/Frame.spec.js
src/components/SecondaryPanes/Frames/tests/Frames.spec.js
src/components/SecondaryPanes/Frames/tests/Group.spec.js
src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.spec.js.snap
src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap
src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap

Render Frame title attribute with a getFrameTitle prop

---

.travis.yml
assets/panel/moz.build
assets/panel/panel.js
src/client/firefox/commands.js
src/client/firefox/events.js
src/client/firefox/types.js
src/test/mochitest/browser_dbg-chrome-debugging.js
src/test/mochitest/browser_dbg-inline-cache.js
src/workers/parser/index.js

I ran into these collisions when doing releases 94 and 95.

Backport mc changes from release 94 and 95

---

package.json
packages/devtools-reps/package.json
yarn.lock

Bump launchpad to 0.139

---

assets/panel/prefs.js
src/components/SecondaryPanes/XHRBreakpoints.js
src/components/SecondaryPanes/index.js
src/utils/prefs.js

Fixes #7145, fixes #7155 
Follow up on the few bugs that were accidently left in initial PR

Don't autofocus xhr input

---

docs/bundling.md

Here are some docs on the process i went through to start bisecting the regression for release 91. The docs should help me remember things like how to specify talos in try.
Please, Please, tell me what is not clear. I wrote it pretty quickly and i think it is too dense.

add docs for release regressions

---

src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap
src/actions/breakpoints/tests/breakpoints.spec.js
src/components/SecondaryPanes/Breakpoints/Breakpoint.js
src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js
src/components/SecondaryPanes/Breakpoints/index.js
src/components/SecondaryPanes/Breakpoints/tests/Breakpoint.spec.js
src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap
src/selectors/breakpointSources.js
src/utils/source-maps.js

* changes the breakpoint locations in the pane based on the selected file context
* jest tests

[breakpoints] map sources in pane

---

src/test/mochitest/helpers.js

This may be more reliable moving forward.

Update debug-expression detection in mochitests

---

src/components/Editor/CallSites.js

Don't show column breakpoints for pretty files

---

assets/panel/prefs.js
src/components/App.js
src/utils/prefs.js

Keeps the panel dimensions saved

Persists the panel sizes

---

src/reducers/breakpoints.js

Fixes #7192 
* Persist XHR breakpoints on navigation
http://g.recordit.co/MD2yA91HM3.gif

[Breakpoints] Persist XHR breakpoints on refresh

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-tabs-without-urls.js
src/test/mochitest/browser_dbg-tabs.js

Should help with: https://bugzilla.mozilla.org/show_bug.cgi?id=1383582

Separate tab tests to prevent intermittents

---

.travis.yml
assets/panel/panel.js
src/components/SecondaryPanes/Workers.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-chrome-debugging.js

Syncing a few things back to prepare for release 102.

[sync] Update a few things from MC

---

src/components/PrimaryPanes/OutlineFilter.js
src/test/mochitest/browser_dbg-outline-filter.js

Fix #7307 - Prevent enter key from submitting in outline

---

src/test/mochitest/browser_dbg-breakpoints-actions.js

This should address the issue from https://github.com/devtools-html/debugger.html/pull/7276#issuecomment-442158877 so that we can land that patch in MC.

Fix breakpoints-actions.js issue introduced with new uncaught rejection patch

---

assets/images/arrow.svg

This fixes the color of the ObjectInspector arrow on m-c

Add context-fill to arrow.svg

---

.circleci/config.yml
jest.config.js

I find the current jest failure output pretty ugly. Hopefully the new thing [jest+circle approved](https://circleci.com/docs/2.0/collect-test-data/#jest) is better

Update jest circle config

---

src/actions/tests/__snapshots__/ast.spec.js.snap
src/components/QuickOpenModal.js
src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
src/test/mochitest/browser_dbg-quick-open.js
src/utils/quick-open.js
src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/utils/helpers.js

Identifiers are very similar to variables in how they are computed, but are more robust.

[Quick Open] remove variables data-source

---

assets/panel/prefs.js
src/utils/bootstrap.js
src/utils/log.js
src/utils/prefs.js
src/utils/tests/log.spec.js

This should make it easier to turn on redux logging in the debugger.

Add conditional logging

---

packages/devtools-reps/src/reps/function.js
src/utils/pause/frames/displayName.js

Fixes #7382
You can experiment at https://bone-farm.glitch.me/

Don't filter out dollar symbols in function names

---

.github/CONTRIBUTING.md

Welcome Tyler!

---

src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js

Add flow types to props for BreakpointContextMenu

Add flow types to BreakpointContextMenu props

---

src/actions/tests/pending-breakpoints.spec.js
src/actions/types/UIAction.js
src/actions/ui.js
src/components/Editor/ConditionalPanel.js
src/components/Editor/GutterMenu.js
src/components/Editor/index.js
src/components/SecondaryPanes/Breakpoints/Breakpoint.js
src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js
src/reducers/breakpoints.js
src/reducers/ui.js
src/test/mochitest/browser_dbg-breakpoints-cond.js
src/utils/breakpoint/index.js
src/utils/breakpoint/tests/index.spec.js

Supercedes https://github.com/devtools-html/debugger.html/pull/7324 for having the conditional breakpoint input update the correct breakpoint.

Change conditional panel to use location

---

docs/getting-setup.md

Fixes #7227 
* Removed from line 101 to 132

Removed Firefox GLCI  information

---

src/components/Editor/EditorMenu.js
src/components/Editor/GutterMenu.js
src/components/Editor/HighlightLines.js
src/components/shared/ResultList.js

None of these appear necessary.

Remove unnecessary constructors

---

src/components/Editor/ColumnBreakpoint.js
src/components/Editor/ColumnBreakpoints.css
src/components/Editor/Editor.css

Having "call site" in some places and "column breakpoint" in other is confusing.  I'm hoping we can change them to simply column breakpoint.

Change all terminology to "column breakpoint", avoid "call site"

---

src/components/SecondaryPanes/Frames/WhyPaused.css

Fixes #7361
This has been bugging me so I'm opting to take it on.

Fix 7361 - Why Paused should wrap

---

renovate.json

Fixes #7433 
* Edit renovate config to stop making frequent updates to dependencies.

Edit renovate section

---

src/components/Editor/Editor.css

Make empty lines line number lighter

---

.babelrc
package.json
yarn.lock

Don't transform object spread

---

bin/copy.js

this will let us land individual commits in a git cinnabar setup. We can add hg functionality to it fairly easily..

(wip) copy commits

---

assets/panel/prefs.js
src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap
src/test/mochitest/browser_dbg-breakpoints-columns.js
src/test/mochitest/browser_dbg-breakpoints-cond.js
src/test/mochitest/browser_dbg-reload.js
src/test/mochitest/helpers.js
src/utils/prefs.js

Prevent intermittence created by:
https://github.com/devtools-html/debugger.html/commit/9845435ee24460835732523cf72f93bc5f1b7d3b

Turn off column breakpoints in dev

---

src/components/App.css

Removes whitespace introduce by me :(

Fix circle CSS linting

---

src/actions/breakpoints/index.js
src/components/Editor/ColumnBreakpoints.js

Fix lint issues

---

src/client/firefox/commands.js
src/client/firefox/create.js
src/client/firefox/types.js
src/client/firefox/workers.js

Address ochameau's review comments from PR 7525.

Address review comments for interface with worker clients.

---

src/workers/parser/getSymbols.js
src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
src/workers/parser/utils/helpers.js

Fixes a pretty big regression introduced by  #7270, which prevented us from previewing a bunch of identifiers in objects and arrays.

[symbols] save object property identifiers

---

src/workers/parser/mapOriginalExpression.js
src/workers/parser/tests/mapExpression.spec.js
src/workers/parser/tests/mapOriginalExpression.spec.js

Fixes #7274
* Add special case covering ObjectProperty
No idea, I relied on tests.

[Parser] Support object destructuring in mapOriginalExpression 

---

.travis.yml
assets/panel/prefs.js
packages/devtools-source-map/src/index.js
packages/devtools-source-map/src/source-map.js
packages/devtools-source-map/src/utils/sourceMapRequests.js
packages/devtools-source-map/src/worker.js
src/actions/sources/blackbox.js
src/client/firefox/commands.js
src/client/firefox/types.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-blackbox-original.js
src/test/mochitest/helpers.js
src/utils/prefs.js

Fixes #7212 
* Allow original sources to be blackboxed
Still need to write tests

[WIP] blackbox original sources

---

assets/images/breakpoint.svg

Fixes blurry Line breakpoint marker

---

.github/CONTRIBUTING.md
docs/debugging-the-debugger.md

Incorrect links in docs are updated

---

assets/panel/prefs.js
src/utils/prefs.js

Thanks to @bomsy's eagle eyes, he was able to spot this.

Fix typo in prefs.js

---

src/components/test/__snapshots__/ProjectSearch.spec.js.snap
src/test/mochitest/browser_dbg-search-project.js

Somehow something changed in between, the tests failed, this aims to fix the tests.

Residual of auto collapse project search results

---

assets/panel/debugger.properties
src/actions/types/UIAction.js
src/actions/ui.js
src/components/Editor/ConditionalPanel.css
src/components/Editor/ConditionalPanel.js
src/components/Editor/GutterMenu.js
src/reducers/ui.js
src/test/mochitest/browser_dbg-breakpoints-columns.js
src/test/mochitest/browser_dbg-breakpoints-cond.js
src/test/mochitest/helpers.js

Log points

---

src/actions/breakpoints/index.js
src/selectors/breakpointSources.js
src/types.js

Tidies up one residual flow issue with the log points work

[breakpoints] fix flow bp log issues

---

src/client/chrome/create.js
src/client/chrome/events.js

Fixes #7560
* add `thread`
* Fixes the debug line
* Enables basic pause functionality (Shows callstack and pause buttons)
To come
* Scopes panel
* Preview

Chrome debug fix

---

src/components/PrimaryPanes/Sources.css

…
Fixes #7618 
* added scroll bar to source outline panel
* removed scroll bar from individual sources.

removed scroll bar from individual source list and added to the source outline panel.

---

assets/panel/debugger.properties
src/components/Editor/GutterMenu.js

fix issues found with the string in debugger.properties

---

.github/CONTRIBUTING.md

Welcome the amazing @princiya to the community team! 💯

Welcome princiya to the community team

---

bin/copy.js

- adds authorship information
- prettier formatting
- a couple of small things that were in the release branch, but weren't copied over to master

[releases] update copy script

---

src/reducers/project-text-search.js

Remove ongoingSearch from state once the we are done with the search.

Cleanup search state after project search

---

src/actions/project-text-search.js
src/actions/tests/project-text-search.spec.js
src/actions/types/index.js
src/reducers/project-text-search.js

We were not using CLEAR_QUERY anywhere.

Remove unused code project-text-search

---

bin/dev-server.js

This path was adjusted changed in #7678.

Update test example file path to match new location.

---

src/components/Editor/Footer.css
src/components/Editor/Footer.js
src/components/Editor/tests/__snapshots__/Footer.spec.js.snap

Fixes #7666 
* changed the position of both the renderers
* minor change in the css

Fix 7666 - Changing the position of cursor location and toggle button in the footer

---

assets/panel/debugger.properties
src/actions/breakpoints/index.js
src/utils/breakpoint/index.js

Fix 7628 - Localize the XHR breakpoint list item labels

---

packages/devtools-reps/src/object-inspector/actions.js
packages/devtools-reps/src/object-inspector/components/ObjectInspectorItem.js
packages/devtools-reps/src/object-inspector/utils/node.js

TRY: https://treeherder.mozilla.org/#/jobs?repo=try&revision=2ec4fabfc8e3cbb7ce561d92c5301d64f9d25bc5

Backport Reps changes from Bug 1515046

---

src/components/Editor/ColumnBreakpoint.js
src/selectors/test/__snapshots__/visibleColumnBreakpoints.spec.js.snap
src/selectors/visibleColumnBreakpoints.js

- adds breakpoint to column breakpoint so that it will be easier to toggle breakpoints in the context menu.
- this also seems more future proof
- added some flow types

[Breakpoints] include breakpoint in column breakpoint

---

src/reducers/event-listeners.js

Remove unwanted console.log

---

src/components/SecondaryPanes/EventListeners.css
src/components/SecondaryPanes/EventListeners.js

As mentioned in today's meeting:

Implement spacing for event listener breakpoints

---

docs/local-development.md

* Fixed two broken links in `local-development.md`

Fix context-menu links in local-development.md

---

src/actions/debuggee.js

This is a temporary fix for part 1 of #7710

Fixes an issue where the selected tab is not visible on refresh

---

bin/copy-modules.js
bin/copy.js

1. fix a bug to preserve authorship
2. support copying over all files for each commit

[releases] Update copy

---

src/components/SecondaryPanes/Breakpoints/Breakpoint.js
src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap

Looks like (#7730) accidentally reverted  (#7673)

[Breakpoint] fix selectBreakpoint

---

bin/post-checkout.js
bin/post-rewrite.js

* use the proper husky env var for scripts

fix: post-checkout and post-rewrite use changed husky env var

---

assets/panel/prefs.js
src/components/Editor/menus/breakpoints.js
src/utils/prefs.js

Move log points behind a flag

---

src/actions/breakpoints/index.js
src/actions/pause/commands.js
src/actions/preview.js
src/actions/tests/toolbox.spec.js
src/actions/toolbox.js
src/actions/types/index.js
src/client/firefox/commands.js
src/client/firefox/types.js
src/reducers/pause.js

This addresses type mis-matches with our actions and the client we expose.

[flow] Fix types with firefox commands

---

src/utils/expressions.js
src/utils/tests/expressions.spec.js

Fixes #7201 
Remove  sanitize inputs as the function was not doing anything
I ran the test suite and all the tests passed.

Remove sanitize inputs

---

src/components/Editor/DebugLine.js
src/components/Editor/tests/DebugLine.spec.js

[DebugLine] line is not cleared

---

src/utils/prefs.js

Fix logging pref

---

src/components/shared/Dropdown.css
src/components/variables.css

Fixes #7764 
Removed `--icon-size` CSS  variable.

remove --icon-size CSS variable

---

src/components/SecondaryPanes/Frames/Frames.css

Fix Frames.css hover/focus

---

src/actions/breakpoints/addBreakpoint.js
src/actions/breakpoints/tests/syncing.spec.js
src/actions/tests/helpers/threadClient.js
src/components/Editor/Breakpoints.js
src/components/Editor/ColumnBreakpoints.js
src/components/SecondaryPanes/Breakpoints/index.js
src/reducers/breakpoints.js
src/selectors/visibleColumnBreakpoints.js
src/utils/breakpoint/index.js

Fixes FIXME from #7796
* Rename makeLocationId to makeBreakpointId, to fit in more with how it is used

Rename makeLocationId to makeBreakpointId

---

README.md
docs/getting-setup.md

Fixes #<issue number>
Add a note about using modern node version
Look at the .md

add note about node version

---

src/components/SecondaryPanes/Expressions.js
src/components/SecondaryPanes/XHRBreakpoints.js
test/mochitest/browser.ini
test/mochitest/browser_dbg-expressions-focus.js
test/mochitest/browser_dbg-expressions.js

Fix 7835 - Focus on inputs if plus is clicked but panel is closed

---

src/workers/parser/mapBindings.js
src/workers/parser/tests/mapBindings.spec.js

Fixes #7830  
* Added support for declarations with no initial values
Well, I rely on tests

Fix 7830 mapBindings throws 

---

src/actions/breakpoints/breakpointPositions.js

Fixes the issues we're seeing on master right now

Add flow to breakpointPositions

---

src/actions/breakpoints/addBreakpoint.js
src/actions/breakpoints/syncBreakpoint.js
src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap
src/actions/breakpoints/tests/__snapshots__/syncing.spec.js.snap
src/actions/breakpoints/tests/breakpoints.spec.js
src/actions/breakpoints/tests/syncing.spec.js
src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap
src/actions/tests/helpers/threadClient.js
src/actions/tests/pending-breakpoints.spec.js
src/actions/types/BreakpointAction.js
src/client/firefox/commands.js
src/client/firefox/create.js
src/client/firefox/types.js
src/reducers/breakpoints.js
src/reducers/pending-breakpoints.js
test/mochitest/browser_dbg-sourcemaps2.js
test/mochitest/browser_dbg-sourcemaps3.js
test/mochitest/helpers.js

Remove obsolete breakpoint sliding code from the client.
Passes jest/flow.

Remove breakpoint sliding code.

---

src/components/SecondaryPanes/Breakpoints/Breakpoint.js

Fixes #6734
We'll want to check this closer with breakpoint specificity and column breakpoints landing, but this is a start....

Fix 6734 - Prevent two active breakpoints

---

src/client/firefox/commands.js
src/client/firefox/create.js
src/client/firefox/types.js

This removes a couple of recent backward compatibility additions.

[client] remove backward compatibility in a couple of cases

---

package.json
src/utils/makeRecord.js
yarn.lock

https://github.com/facebook/flow/releases
It might have some nice things for us :)

Bump flow-bin to 0.92.1

---

docs/debugging-the-debugger.md

The current doc was amazing, but from my perspective was missing clear information about what is expected from the newcomer in order to complete the guide and be ready to work with the debugger.
- Added goals and hints on each step to make a clear description of things that can be done.
- Removed references to the first person singular linking in one case to the contributor and in other changed to the first person plural pronoun.

Improves on debugging the debugger doc to make easier the "inception".

---

.circleci/config.yml
.travis.yml
package.json

Fixes #7864
Not competing with @dhyey35, I just want to see if we can normalize our Travis and Circle on the same version of Node

Upgrade Node in Circle, Travis

---

src/components/PrimaryPanes/SourcesTreeItem.js
src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js

Fixes #7947 
I gave bad flow advice for https://github.com/devtools-html/debugger.html/commit/0ba5f05507c70f41e418bd202ddc29c5376dd581 .    :(

Fix 7947 - Show context menu when right-clicking directory

---

src/actions/file-search.js

Not sure why the repeated args bother me but thought I'd throw this into the mixer.

Make search result code a bit more compact

---

src/client/firefox/commands.js

This is a workaround until issues with setting all breakpoints have been resolved, which will require some work on server side transports.

Only wait for the main thread to set/clear breakpoints.

---

docs/community-team.md

Formatting, punctuation, and style fixes for clarity.
Fixes N/A
* Fixed capitalization errors
* Fixed punctuation errors
* Modified descriptions to follow the same pattern
* Clarified language and expanded some paragraphs for ease of readability
N/A

Fix community-team.md

---

packages/devtools-source-map/src/index.js

Makes originalLocation a task so that it can be queued.

[Breakpoints] Improve column breakpoint performance

---

packages/devtools-reps/src/launchpad/components/Console.css
packages/devtools-reps/src/launchpad/components/Result.js
packages/devtools-reps/src/launchpad/index.js

It was broken, not sure for how long, so I fixed it and added some useful buttons

Fix reps launchpad

---

src/actions/breakpoints/addBreakpoint.js
src/actions/breakpoints/breakpointPositions.js
src/actions/breakpoints/index.js
src/actions/breakpoints/syncBreakpoint.js
src/actions/breakpoints/tests/breakpointPositions.spec.js
src/actions/types/BreakpointAction.js
src/reducers/breakpoints.js
src/utils/defer.js

Memoizes the breakpoint position fetching in a similar manner to loadSourceText

[Breakpoints] memoize breakpoint position fetching

---

src/actions/ast/setInScopeLines.js
src/actions/types/ASTAction.js
src/reducers/ast.js
src/reducers/types.js

Fixes #7931 
* remove immutables
Run `npm run test` and `npm run flow`

Remove immutables 

---

src/utils/pause/frames/getLibraryFromUrl.js
src/utils/pause/frames/tests/getLibraryFromUrl.spec.js

Fixes Regex for React Libraries

---

assets/dictionary.txt
docs/getting-setup.md

Add instructions to install packages with SSL verification turned off.

Update Getting Setup Docs

---

assets/panel/debugger.properties
src/components/Editor/Footer.css
src/components/Editor/Footer.js

Fixes #7840
We don't need this text.

Fix #7840 - Remove blackboxed text to prevent overflow

---

src/components/Editor/Preview/Popup.js
test/mochitest/browser_dbg-inspector-integration.js
test/mochitest/helpers.js

Fixes #8033
Check out the STR here:  https://github.com/firefox-devtools/debugger/issues/8033

Fix #8033 - Open node from the object inspector in popups

---

src/components/Editor/Tabs.js
src/components/shared/AccessibleImage.css
src/components/shared/Dropdown.css

Fix #8081 - Dropdown label and icon style

---

src/components/shared/SearchInput.css

Fixes #8003 
* change base width of a search input

fix: make search input more responsive

---

test/mochitest/browser_dbg-sourcemaps.js
test/mochitest/helpers.js

Fix sourcemaps test click position after SVG update

---

src/components/QuickOpenModal.js
src/components/test/QuickOpenModal.spec.js
src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
src/utils/quick-open.js
src/utils/result-list.js
test/mochitest/browser_dbg-quick-open.js

Reverts firefox-devtools/debugger#8201
I jumped the gun on this -- @jasonLaster found some good improvement ideas.  Let's do a quick revert and let the author adjust per Jason's feedback.

Revert "Improve performance of "Go to file""

---

src/components/QuickOpenModal.js
src/components/test/QuickOpenModal.spec.js
src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
src/utils/quick-open.js
src/utils/result-list.js
test/mochitest/browser_dbg-quick-open.js

Reopened https://github.com/firefox-devtools/debugger/pull/8201 which [was reverted](https://github.com/firefox-devtools/debugger/pull/8206) because [it was merge prematurely](https://github.com/firefox-devtools/debugger/pull/8201#issuecomment-487638958).

Quick open faster
