firefox-devtools/debugger

src/components/SecondaryPanes/SecondaryPanes.css
Fixes Issue: #5762
Should not allow text selections 
- add a breakpoint
- select the breakpoint and drag your mouse down
=> Avoid allow text selection in secondary panels - Fix #5762

src/workers/parser/getScopes/visitor.js, src/workers/parser/tests/__snapshots__/getScopes.spec.js.snap, src/workers/parser/tests/fixtures/scopes/ts-sample.ts, src/workers/parser/tests/getScopes.spec.js, src/workers/parser/tests/helpers/index.js, src/workers/parser/utils/ast.js
* Parse Typescript files with Babylon to expand the original-scope debugging work to TS files
=> Enable original-file Typescript parsing via Babylon.

src/actions/file-search.js, src/components/Editor/SearchBar.js, src/utils/editor/source-search.js, src/utils/editor/tests/source-search.spec.js
part of the toJS removal:
getSearchState is not using modifiers, so they can be removed from a series of functions including:
- getSearchState
- removeOverlay
- clearSearch
- closeFileSearch
=> Removes unused modifiers reference

src/actions/preview.js, src/utils/preview.js
Fixes Issue: #5695
* added `isConsole` function
* hide
=> add function to check for console object or props

src/components/ShortcutsModal.css
Fixes Issue: #5637
Changed ShortcutModal.css to fit larger phrases in french locale.
But the suggested fix enables a scroll bar if the phrase very big.
Here is an example of  [it](http://recordit.co/o8JIh9ru2L).
=> Possible Fix for issue #5637

src/components/PrimaryPanes/Sources.css
@jasonLaster discovered a double scrollbar in the Sources Tree.  I couldn't spot it on Mac but Windows made the problem more visible.
After testing things out, I found what I consider to be the issue: I'm applying CSS code to the `sources-list` at all states when it only needs to be applied when the custom root is showing.
The sources tree layout stuff got complicated when we switched to the directory root button/layout because we always wanted that clear button on top, and so we had to go with absolute positioning and so on, thus the scrollbar situation got complicated.
1.  Go to https://davidwalsh.name
2.  Expand all of the items, toggle the width and height of the sources tree pane, ensure that only one horizontal and vertical scrollbar displays and is on screen at all times (i.e. …
=> Fix double scrollbar issue in SourcesTree

src/actions/ast.js, src/actions/pause/mapFrames.js, src/actions/tests/pause.spec.js, src/selectors/test/getCallStackFrames.spec.js, src/utils/pause/frames/annotateFrames.js, src/utils/pause/frames/displayName.js, src/utils/pause/frames/tests/displayName.spec.js
Fixes Issue: #5659
* 756fedb8955a002bb2b11cb5750dd62d598fea05: When pausing in a generated source, map call stack frame names to the closest corresponding function in the original source. This gets rid of cryptic function names that show up in generated source.
* c418541a45c7743f95baf3b423ae1c6c072889fe Slight update to the Babel async grouping to make things a little easier to read than this  (see how `slowest` and `slower` appear twice): 
1. Go to http://firefox-dev.tools/debugger-examples/examples/babel/
2. Set breakpoint at entry.js:23
3. Click "asyncExample" button. 
4. Expect second screenshot below
=> Map frame display names

src/components/shared/ResultList.css
PR https://github.com/devtools-html/debugger.html/pull/5729 introduced a bug where alignment of line numbers was no longer to the right.  This PR fixes said bug.
=> Fix alignment of line numbers in quick open

src/components/PrimaryPanes/Sources.css
Yesterday's fix created this small side effect:
My fix should have just been the `overflow: hidden;` line.
1.  Go to https://davidwalsh.name/
2.  Squeeze the height and width of the left pane, ensure only one scrollbar and highighted items take up the whole line.  Opening the doubleclick.net dir, which has a few large file names, is helpful in this.
3.  Do the same with a directory root.
=> [Sources] Fixes full width for highlighted items with no root

src/components/Editor/HighlightLine.js
Fixes Issue: #5633
* Stopped highlighting the line being left when using stepping functions
Cases this seems to fix
- Clicking `Resume`, `Step over`, `Step in`, or `Step out` buttons—removes the unwanted grey line on the previous location
- Repeatedly clicking the same breakpoint in the secondary pane—after every click, the breakpoint location is selected and highlighted in grey, as desired
- Clicking on a breakpoint in the secondary pane and then clicking a debugger button (`Step over`, `Step in`, etc.)—the breakpoint location is selected and highlighted in gray, then, when a debugger button is clicked, no line is highlighted in grey, but the new selected location is highlighted in blue as desired
Why this works: upon clicking a debugger button, `isInSteppingUpdate ` is set to `true` and …
=> [Editor] [WIP] Stop highlighting the line being left when stepping

src/components/QuickOpenModal.js, src/components/tests/QuickOpenModal.spec.js
@jasonLaster mentioned that anonymous functions were being listed in the symbol search, which is undesirable.  
1.  Open a source with anonymous functions
2.  Type `Command+Shift+O`
3.  Notice no anonymous functions are listed
=> Prevent anonymous functions from displaying in symbol search

src/components/Editor/HighlightLine.js
Console was showing the "Don't use PureComponent with shouldComponentUpdate" warning.
=> Prevent HighlightLine / shouldComponentUpdate warning

src/actions/expressions.js, src/actions/preview.js, src/utils/dbg.js
* Convert `getMappedExpression` into a real action
* Avoid double-binding all of the actions in `dbg.actions`
=> Make getMappedExpression a real action and fix double-binding action creators

src/reducers/ast.js, src/reducers/expressions.js, src/reducers/file-search.js, src/reducers/pending-breakpoints.js, src/reducers/sources.js
Where possible removes immutable `getIn` calls not needed due to switch to source records.
=> Removes getIn

src/actions/sources/select.js, src/actions/tests/tabs.spec.js
Refactor due to possible performance gains in selectLocation and selectSpecificLocation, which should make the whole application feel snappier by about a quarter of a second each time any of these functions is called.
=> Combines toJS calls in select.js

package.json, yarn.lock
We are not using react test renderer at all. At the same time we have enzyme, which does the same thing. Removing the less versatile option will lower the number of dependencies.
Also prettify insisted on reformatting the code in the files...
=> Removes unused react test renderer

src/actions/tests/helpers/threadClient.js
I recently added this `console.error` [here](https://github.com/devtools-html/debugger.html/commit/06e82dbd659e6ff4c326ad3f41241ede0079e428#diff-ab92a985751230e38d1bb820de8456cbR57)
So we're now seeing syntax errors in our test.
=> Fix tabs.spec.js test errors

src/utils/prefs.js
This is causing too many issues at the moment.  We should turn it off in dev mode until we have the time to tidy everything up.
=> Turn off auto-pretty-print by default for dev mode

src/components/SecondaryPanes/Breakpoints.css, src/components/SecondaryPanes/Breakpoints.js, src/test/mochitest/browser_dbg-breakpoints-toggle.js, src/test/mochitest/browser_dbg-breakpoints.js, src/test/mochitest/browser_dbg-browser-content-toolbox.js, src/test/mochitest/head.js
Fixes Issue: #5796
This is a WIP for the grouping of breakpoints for the new breakpoints UI.  
I'm thinking that syntax highlighting via CodeMirror can be done as a separate PR since it will likely require more thought and, IMO, shouldn't block this.
=> New Breakpoints UI: Group Breakpoints

src/actions/ast.js, src/actions/pause/fetchExtra.js, src/actions/pause/fetchScopes.js, src/actions/pause/index.js, src/actions/pause/mapFrames.js, src/actions/pause/setExtra.js, src/actions/preview.js, src/actions/types.js, src/components/Editor/EditorMenu.js, src/reducers/pause.js, src/utils/ast.js, src/utils/breakpoint/astBreakpointLocation.js, src/utils/function.js, src/workers/parser/index.js
- Changed getExtraProps to use findClosestFunction, which has now been changed to findClosestofSymbolDeclaration to find the name of the component even when in production  code.
Before
After
=> Switched getExtraProps to use findClosestFunction to get the component name.

src/components/SecondaryPanes/Breakpoints.js
This makes breakpoints show up in a predictable spot.  :)
=> Sort breakpoints by file name

src/components/SecondaryPanes/BreakpointItem.js, src/components/SecondaryPanes/Breakpoints.css, src/components/SecondaryPanes/Breakpoints.js, src/utils/breakpoint/create-editor.js, src/utils/breakpoint/index.js, webpack.config.js
Fixes Issue: #5849
* Adds syntax highlighting to Breakpoints pane breakpoints
* Improves the layout of close button (more padding to avoid hover / close button movement)
Add breakpoints, remove breakpoints, disable breakpoints -- ensure all looks good.
=> Syntax-highlight breakpoints

src/components/shared/ResultList.css
Fixes Issue: #5860
* change 1 - Add a feature path to be visible at QuickOpen Modal Dialog  #resolve +review @jasonLaster.
STR:
open QO via cmd+p
press `<escape> button`
Please resize browser. 
My recommendation is width to be `500px` and `600px`
ER: Filenames to be visible. 
Example: https://youtu.be/oNu0U7MDZgo
=> [QuickOpen] Path is too wide #5860

src/components/SecondaryPanes/BreakpointItem.js
Clicking-dragging or double clicking inside individual breakpoints allows text selection per breakpoint text, which we've tried turning off with CSS `user-select` for the entire breakpoints panel;  this PR prevents CodeMirror's internal text selection of breakpoint text.
=> Prevent selection of breakpoint contents

src/components/SecondaryPanes/Breakpoints.css
There's a weird element inside CodeMirror, `.CodeMirror-scroll`, whose height goes like 30 pixels under the breakpoint text:
That element triggers the text cursor for a few pixels under the actual breakpoint text, which feels gross.  This PR prevents that text cursor from ever displaying.
=> Fix odd cursor text issue

src/components/PrimaryPanes/SourcesTree.js, src/components/shared/ManagedTree.js, src/components/tests/__snapshots__/SourcesTree.spec.js.snap, src/test/mochitest/browser_dbg-asm.js, src/test/mochitest/browser_dbg-sources.js
* Expand all nodes in the path of the selected source in sources tree
=> [Sources] Auto expand path of selected source

README.md, docs/local-development.md, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Frames/Frames.css, src/components/shared/reps.css
Synchronization from https://bugzilla.mozilla.org/show_bug.cgi?id=1378108
Fixes Issue: #5881
* removed all references to firebug in css files
* removed mentions of firebug in documentation
I kept the screenshots showing the Firebug theme (eg. in issues.md), felt overkill to recreate screenshots just for that.
=> Remove all references to Firebug theme

src/actions/ui.js
**Fixes Issue: #5869** 
When selecting ` Reveal in tree` from the context menu, it now checks:
- if the left panel is collapsed
- opens if it is
=> [Sources] Reveal in tree opens the left sidebar

src/actions/tests/ui.spec.js, src/components/PrimaryPanes/SourcesTree.js, src/selectors/getRelativeSources.js, src/test/mochitest/browser_dbg-sources.js, src/utils/sources-tree/addToTree.js, src/utils/sources-tree/getDirectories.js, src/utils/sources-tree/getURL.js, src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap, src/utils/sources-tree/tests/__snapshots__/collapseTree.spec.js.snap, src/utils/sources-tree/tests/__snapshots__/sortTree.spec.js.snap, src/utils/sources-tree/tests/__snapshots__/updateTree.spec.js.snap, src/utils/sources-tree/tests/collapseTree.spec.js, src/utils/sources-tree/tests/utils.spec.js
We had an issue where webpack based urls had their paths changed in the tree from `webpack:///src/file.js` to `Webpack/src/file.js` changing the source url meant that the root no longer lined up with the source urls. This patch fixes that!
---
=> Fix webpack roots

src/actions/expressions.js, src/actions/pause/fetchExtra.js, src/actions/pause/paused.js, src/actions/pause/resumed.js, src/actions/preview.js, src/actions/sources/tests/select.spec.js, src/actions/tests/ast.spec.js, src/actions/tests/expressions.spec.js, src/actions/tests/helpers/threadClient.js, src/actions/tests/pause.spec.js, src/actions/tests/preview.spec.js, src/actions/types.js, src/client/firefox/commands.js, src/client/firefox/types.js, src/reducers/expressions.js, src/reducers/pause.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-expressions-error.js, src/test/mochitest/browser_dbg-expressions.js, src/test/mochitest/browser_dbg-navigation.js, src/test/mochitest/browser_dbg-sourcemaps-reload.js, src/test/mochitest/examples/doc-scripts-debugger.html, src/test/mochitest/head.js, src/utils/expressions.js
Fixes Issue: #5509
This is a bunch of improvements to how we think about console evaluations and pause timing. I don't know how much of this we'll want to include in the final version
- clears the frames when we resume
- adds a new `evaluateMessages` helpers
- adds a new `waitForEvaluations` helpers
=> Improve evaluating expressions when pausing

src/components/SecondaryPanes/Breakpoints.css
The bottoms of letters like "g", "j", "y", etc. are being cut off at the bottom due to an unnecessary line-height.
=> Fix breakpoint lineheight

src/components/shared/ManagedTree.css
- Choose any source in the tree
- Toggle on and off blackboxing quickly
-  On master you'll see the height of the tree item change a pixel or two
-  With this PR, the item will stay the same height
=> Avoid tree item heigh bouncing by setting lineheight

src/actions/file-search.js, src/actions/navigation.js, src/components/Editor/index.js, src/components/ProjectSearch.js, src/components/tests/ProjectSearch.spec.js, src/components/tests/__snapshots__/ProjectSearch.spec.js.snap, src/utils/editor/index.js, src/utils/editor/source-search.js
Issue: #3829
I took the function flow used to do what I believe to be file searches and removed some of lines that did not seem necessary if only highlighting was needed.
File search function flow:
`doSearch` (`actions/file-search.js`) --> `searchContents` (`actions/file-search.js`) --> `find` (`utils/editor/source-search.js`)  --> `doSearch` (`utils/editor/source-search.js`) --> `searchNext` (`utils/editor/source-search.js`)
I added these new functions to only get the highlighting without touching the current file search:
`doSearchForHighlight` (`actions/file-search.js`) --> `searchContentsForHighlight` (`actions/file-search.js`) --> `searchSourceForHighlight` (`utils/editor/source-search.js`)  --> `findNextOnLine` (`utils/editor/source-search.js`)
- Started calling …
=> Started highlighting the searched terms when clicking on a ProjectSearch result

assets/images/Svg.js, src/actions/pause/mapFrames.js, src/actions/pause/setExtra.js, src/components/QuickOpenModal.css, src/components/SecondaryPanes/BreakpointsContextMenu.js, src/components/SecondaryPanes/BreakpointsDropdown.css, src/components/SecondaryPanes/BreakpointsDropdown.js, src/components/shared/Badge.css, src/components/shared/Badge.js, src/components/shared/Button/CommandBarButton.css, src/selectors/getRelativeSources.js, src/utils/dbg.js, src/utils/location.js, src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js, src/utils/pause/mapScopes/locColumn.js, src/utils/pause/pausePoints.js, src/utils/source-queue.js, src/workers/parser/mapOriginalExpression.js
Fixes Issue: #5898 
Added missing license headers to files:
=> Add missing license headers

src/actions/expressions.js
At present, if you create a watch expression,  then double click it, don't change anything, and press ENTER, nothing happens -- the input stays there as though nothing happened.
This PR allows the user to submit no change to an expression. (i.e. "Oops, I didn't mean to edit this one")
=> Allow submission of edited expression even if it doesn't change

src/client/firefox/commands.js
Service worker debugging was broken with https://github.com/devtools-html/debugger.html/pull/5761 , my bad! Looks like not all debugging target have a root client defined.
=> Fix blank debugger when debugging service workers

assets/images/Svg.js, assets/images/help.svg, src/components/SecondaryPanes/CommandBar.css, src/components/SecondaryPanes/CommandBar.js, src/components/SecondaryPanes/UtilsBar.js
Fixes Issue: #5917 
* import help photon icon
* export `debugBtn` from `CommandBar`. (should it be exported? should it be in its own file?)
* update shortcuts icon to use exported `debugBtn`
Before:
After:
=> Update shortcuts modal icon to use photon icon

assets/images/Svg.js, assets/images/extension.svg, assets/panel/debugger.properties, src/components/PrimaryPanes/SourcesTree.js, src/components/shared/Svg.css
I thought it would be cool to show an icon for Firefox extensions:
=> Use addons icons for extensions

package.json, src/components/Editor/Preview/Popup.js, src/components/SecondaryPanes/FrameworkComponent.js, src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap, yarn.lock
The only breaking change was the one made in createNode, which
is used a few time in the debugger. Call-sites were updated, as
well as some snapshots.
The jest tests are green, and manual testing on the different
places the OI is used showed no issue.
=> Update devtools-reps to 0.22.0.

src/actions/pause/mapScopes.js, src/utils/pause/mapScopes/filtering.js, src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js
* Finally get around to using binary search to look up the generated bindings that may be applicable for a mapped location, taking lookup times from `O(N * M)` to `O(N * log(N))`
This is a first step for performance optimization for original scopes. We'll also want to implement batched location mapping like @jasonLaster had in https://github.com/devtools-html/debugger.html/pull/5892, though that will have to wait for some additional work around range mapping.
=> [scopes] Optimize the performance of looking up the generated binding for a mapped original location

src/components/shared/ResultList.js, src/components/shared/tests/__snapshots__/ResultList.spec.js.snap, src/components/tests/__snapshots__/QuickOpenModal.spec.js.snap
Fixes Issue: #5936 
* Don't add `img` element if there is no icon
Before:
After:
=> Fix function search results formatting

src/utils/source.js
Fixes Issue: #5935 
* Use default (`file`) icon for CSS files as CSS-specific icon doesn't exist.
Before:
After:
=> Use file icon for CSS files

src/components/PrimaryPanes/Sources.css
If you quickly click the Blackbox icon in the Editor footer, you'll notice a shift in not only the SourcesTree icon position but text of the tree item;  this happens because the JS icon is set to 15x15 and blackbox is 13x13.  
I've updated this PR to (1) vertically and horizontally center blackbox icon and (2) prevent the weird text movement.
=> Prevent blackbox icon from causing jump in SourcesTree

src/test/mochitest/browser_dbg-babel-scopes.js, src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js
* Fixes the binding filtering to more strict
* If an optimized-out value is encountered while resolving import bindings, used it if no better value is found
=> [Scopes] Show "optimized out" instead of "unmapped" when resolving import declarations

.stylelintrc, src/components/Editor/Editor.css, src/components/Editor/EmptyLines.css, src/components/Editor/EmptyLines.js, yarn.lock
Fixes Issue: #5603 
* Add hover effect to gutter line numbers.
Before:
After:
=> [Editor] Add gutter hover effect

src/components/shared/Accordion.js, src/components/shared/tests/__snapshots__/Accordion.spec.js.snap
Fixes part of the 2nd check box (Need to be able to navigate to headers with keyboard) of Issue #4080
In src/components/shared/accordion.js, we changed header-buttons tabIndex from 0 to -1.
This prevents the header-buttons divs (which contain the refresh and add buttons) from being erroneously focused when user cannot interact with them.
Test Plan:
-  [x] Opened search in files with ctrl+shift+f
_Before we changed header-buttons tab index to -1, there was a focusing issue where the button was focused when user couldn't interact with it._
_After change, header-buttons are no longer focused while the user cannot interact with them._
Will continue to work on Issue #4080 2nd check box to remove other focusing issues. Just wanted to submit our progress so far! (With @chan750 and @denigrise)
=> Tab Order Improvements

src/components/SecondaryPanes/Breakpoints.js
I thought I already submitted this but maybe not; I think it would be good to sort breakpoints by filename so groups don't look like they're randomly ordered
=> Sort breakpoint groups by file name

src/utils/ast.js
Fixes Issue: #6003
Add an additional guard for when we can't find any pause points
=> [Breakpoints] only set empty lines when there are pause points

assets/panel/debugger.properties, assets/panel/prefs.js, src/actions/pause/extra.js, src/actions/tests/__snapshots__/preview.spec.js.snap, src/actions/tests/preview.spec.js, src/components/SecondaryPanes/ReactComponentStack.js, src/components/SecondaryPanes/index.js, src/utils/prefs.js
Related issue: #3792 
* Add a "Components" pane that appears when pausing in a React component. For now, it just lists the component and all its ancestors all the way up to the root.
* This is hidden behind a feature flag for now.
Todo in a future PR: 
* Ability to "select" components. Right now it's just a plain list.
* Improve styling?
* Improve handling for container components created with `connect`? 
1. Hit a breakpoint at [Frame/index.js#174](https://github.com/calebstdenis/debugger.html/blob/12363ee0bddab3819b781e98bacf00b530015937/src/components/SecondaryPanes/Frames/index.js#L174)
2. Observe the "Components" pane as in the screenshot below
=> Initial Components pane for React

docs/dbg.md, src/client/index.js, src/test/tests-setup.js, src/utils/bootstrap.js, src/workers/parser/index.js, src/workers/pretty-print/index.js, src/workers/search/index.js
This adds `dbg.worker` references so that developers can debug the debugger's workers
=> Add the workers to dbg

src/workers/parser/utils/helpers.js
Fixes  
`console.error: (new TypeError("parent.value is null", "resource://devtools/client/debugger/new/parser-worker.js", 1501))`
https://babeljs.io/docs/core-packages/babel-types/#objectproperty
=> Tighten babel type

src/components/SecondaryPanes/Breakpoints.css
This PR ensures that the second checkbox indents properly in RTL:
=> Ensure exception checkbox indents in RTL

src/components/Editor/Tabs.js
- Follows up on #6019 
- defers updating hidden tabs which prevents doing expensive work on mount
=> Defer updating hidden tabs

src/components/SecondaryPanes/FrameworkComponent.js, src/utils/source-maps.js
Fixes two type errors
1. framework component is a new component, which was missing a guard
2. getGeneratedLocation is a timing issue with hot reloading
=> Fix two type errors

src/workers/parser/getScopes/visitor.js, src/workers/parser/tests/__snapshots__/getScopes.spec.js.snap, src/workers/parser/tests/fixtures/scopes/jsx-component.js, src/workers/parser/tests/getScopes.spec.js
* Ensure that JSXIdentifier nodes inside opening JSX elements are considered JSX variables, excluding all the JSXIdentifiers that _aren_ just property/attribute names.
Here `UnorderedList` shows up properly.
=> [scopes] Detect JSX elements as variables in scope visitor.

src/actions/sources/newSources.js, src/actions/sources/tests/newSources.spec.js, src/utils/test-head.js
Fixes #5028
- We used to crash when the sourcemaps service was not available. 
- This now adds a check so it doesn't fail.
=> Fix sourcemaps off

src/components/Editor/Breakpoint.js, src/components/SecondaryPanes/Breakpoint.js, src/components/SecondaryPanes/Breakpoints.js, src/types.js
Fixes Issue: #6032
Previously we were only showing the generated line. Now we show the correct text based on the context
=> [Breakpoints] Show original breakpoint text

src/workers/parser/mapOriginalExpression.js, src/workers/parser/tests/mapOriginalExpression.spec.js
* Ensure that we traverse `ThisExpression` nodes when renaming local variables
=> Handle 'this' in expression mappings.

src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
Fixes Issue: #6063
Testing:
1.  Click in and out of new expression input, ensure border is on at proper times
2.  Edit and blur from existing input
3.  Click the "+" button to add another input
=> Fix 6063 - Ensure the expressions box is properly outlined upon focus & blur

src/components/SecondaryPanes/Breakpoints.js
Fixes Issue: #6066
Winding down my day by reopening this.
- Files of the same name are no longer grouped
- Files are sorted by name
- Clicking a group heading opens the given resource
=> Fix 6066 - Improve Breakpoint Grouping Uniqueness and Functionality

src/components/SecondaryPanes/Breakpoints.css
Fixes Issue: #6065
I halved the vertical space:
=> Fix 6065 - Tighten up the breakpoint spacing

src/actions/tests/ui.spec.js, src/components/PrimaryPanes/SourcesTree.js
Updates regarding of PR: #6052 
Fix a minor bug when setting domain directory as root.
STR:
1. Go to http://firefox-dev.tools/debugger-examples/examples/todomvc/
2. On the left panel, right click on "firefox-dev.tools" and Click on "Set directory root"
3. Notice the root name is not displayed correctly.
Added ui test case in regarding to this bug.
=> [Sources] updated fix "set directory root" bug

src/components/Editor/Preview/Popup.js
Fixes Issue: #5757 
* Get all the nodes before hand, filter out the node thats of type prototype.
Before:
After:
=> [Preview] Remove the root node in the immutable preview and the prototype.

src/utils/function.js, src/workers/parser/getScopes/index.js, src/workers/parser/getScopes/visitor.js, src/workers/parser/mapOriginalExpression.js, src/workers/parser/tests/mapOriginalExpression.spec.js
* Use the parser worker's scope visitor to ensure that only variables in the proper scope are rewritten in the console
=> [scopes] Use the scope visitor to avoid rewriting shadowed bindings in console expressions

src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js
* Consider all bindings bad if there are too many
All the tests pass with this, so I'm happy with these numbers. We can always tune them in the future.
=> [scopes] If there are too many possible bindings, assume they are all bad.

src/components/SecondaryPanes/Expressions.css
There's a sizable jump between an existing expression and the input box; a jump we should prevent.  Here's how it looks now:
=> Ensure expressions input matches display height

src/components/SecondaryPanes/index.js, src/test/mochitest/browser_dbg-expressions-error.js, src/test/mochitest/browser_dbg-expressions.js
As off now, we show the "refresh" and "+" buttons for Expressions but ... they don't do anything when there are no expressions made.  This PR hides those buttons when no expressions exist.
=> Don't show buttons that aren't usable

src/components/SecondaryPanes/Breakpoints.css
Fixes Issue: #5978 
Pull this down, build into Firefox, then try to scroll over breakpoints
I figured this out via:
``` ./mach run --jsdebugger --devtools ```, setting this CSS value with the console, and then scrolling worked as desired.
=> Prevent CodeMirror from preventing scroll in breakpoints

src/components/PrimaryPanes/Outline.js
since every .toJS() call is about a quarter of a second we should be able to shave off half a second with this refactor every time Outline is called.
=> Removes repeating .toJS() calls in Outline.js

packages/devtools-source-map/src/utils/index.js, src/workers/parser/tests/__snapshots__/getScopes.spec.js.snap, src/workers/parser/tests/fixtures/scopes/vue-sample.vue, src/workers/parser/tests/getScopes.spec.js, src/workers/parser/tests/helpers/index.js, src/workers/parser/utils/ast.js
* Support parsing of `.vue` files for JS content
This allows getSymbols and preview to work in .vue files, among other things. This doesn't currently enable original-scope debugging with Vue, because the sourcemaps generated by Vue aren't quite adequate. It does at least allow for the possibility if the sourcemaps improve in the future however.
=> [scopes] Support parsing .vue files from original maps.

src/actions/breakpoints/addBreakpoint.js, src/actions/breakpoints/syncBreakpoint.js, src/actions/sources/newSources.js, src/actions/sources/select.js, src/components/Editor/CallSites.js, src/utils/source-maps.js
- Moves .toJS() inside `getGeneratedLocation` instead of having to call it every time (maybe we will be able to remove it altogether in future?).
- Removes a few instances of toJS() that do not result in a full object being dispatched.
=> Removes a few instances of toJS()

src/actions/expressions.js, src/actions/tests/__snapshots__/expressions.spec.js.snap, src/actions/tests/expressions.spec.js, src/actions/types/PauseAction.js, src/client/firefox/commands.js, src/client/firefox/types.js, src/reducers/expressions.js
Fixes Issue: #5467
* Added `autocomplete` client api
* Added a new `autocomplete` action
* Added tests for the action
* Add reducer to locally cache the matches
=> add the client api for autocomplete

src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/index.js, src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap, src/components/shared/Accordion.css
This addresses two nits from #6166:
- Removes outline
- Opens accordion item if not open and the "+" is clicked
Also:
- Now always shows the "+", since the pane could be closed and someone might know how to open it to add an expression
Test plan:
- Click the "+" icon with the pane closed and opened, ensure the input gets focused
- Edit an existing expression, ensure the editing experience is good.
I'll address the last item in that issue once we prefect breakpoints.
=> Fix a few nits from #6166

src/components/PrimaryPanes/SourcesTree.js
`getSourceClassnames()` works the same way when it gets a clean object or something from immutable. The result is the same.
=> Removes a toJS()

src/components/Editor/Preview/Popup.js, src/components/Editor/Preview/index.js
Fixes Issue:  #5406
I feel like we're writing industrial strength hover protection. Anyways, this fixes two phenomenons 
1. there is no relatedTarget (small mistake on the last pr)
2. the scenario that the user moused away before the preview was shown...
=> [Preview] an additional tweak

src/actions/pause/pauseOnExceptions.js
Fixes Issue: #5509 #4360
We had a race case where we would call `pauseOnExceptions` which would do an interrupt and a resume, but not block on other actions. This caused some pretty unpredictable behavior.
The order of events was
- start pausing
- start loading a source
- POE triggers resume
- pausing cant do things like fetch environments or evaluate expressions
=> [PauseOnExceptions] should wait while setting

src/components/SecondaryPanes/Breakpoints.css
When we added `pointer-events: none` to fix that really odd breakpoints scroll error, it bricked out `cursor: default` and thus the text cursor is showing when hovering over breakpoints.
Moving this CSS to an element higher in the stack fixes the problem.
=> Restore cursor default for breakpoint sidebar

src/components/SecondaryPanes/Breakpoints.js
I noticed that setting breakpoints between pretty and original URLs was creating two groups (`:formatted`); that's not the best.
=> Group breakpoints for files set in pretty or original URLs

src/components/PrimaryPanes/SourcesTree.js
…s.id instead of contents.get("id").
Fixes Issue: #5738 
* Modified SourceTree.js to use content.id instead of content.get("id").
We ran the testing suite using Yarn and we opened the debugger and tested the primary features.
=> [Sources] Refactored component to use contents.id

src/components/PrimaryPanes/SourcesTree.js
Reverts devtools-html/debugger.html #6184
We're seeing SourcesTree failures and I think this may be the source of those problems.
=> Revert "[Sources] Refactored component to use contents.id"

src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/Frames.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap
This prop prevents the debugger from truncating the frames
and show all of them on first render, as well as hide the
toggle button.
This will be useful for the console when we share this module
so we have a similar behavior with the current console stacktrace.
=> Add a disableFrameTruncate to the Frames component.

src/components/shared/BracketArrow.css, src/components/shared/Popover.css, src/components/shared/Popover.js, src/components/shared/tests/__snapshots__/Popover.spec.js.snap
Fixes Issue: #6051 
Most of the changes are in getPopoverCoords, now it's doing 3 things mainly:
1. calculates the popover orientation - should it be placed on top/bottom/right of the token, using the target, popover and editor positions.
2. Using the orientation to calculate the left and top of the popover
3. To determine where the popover arrow should be - calculates `targetMid`
- Set a breakpoint and stop
On large window, behavior should remain unchanged:
- Enlarge the debugger window to max size
- Pick an object to test
- Place the token in the top of the editor.
- Preview opens **under** the token.
- Place the token in the vertical middle of the editor.
- Preview opens **under** the token.
- Place the token in the bottom of the editor
- Preview opens **above** the token.
On Small …
=> Preview to the right

src/components/SecondaryPanes/SecondaryPanes.css
@violasong's eagle eyes spotted this issue in dark mode (the bottom margin causing the ~30 pixels of light gray):
It's a result of the accessibility work and turning the accordion into a list.  Fixed the issue by removing bottom margin from the list.
=> Remove unwanted border from accordion

src/actions/ast.js, src/actions/types/ASTAction.js, src/reducers/ast.js
`setSymbols` currently passes the whole source when it only usues the Id. This allows us to get rid of an unneeded toJS() call
=> Makes setSymbols dependent on Id only 

.babel/transform-mc.js, .eslintignore, .gitignore, .travis.yml, .vscode/launch.json, assets/panel/dist.moz.build, assets/panel/index.html, assets/panel/moz.build, bin/copy-assets.js, bin/copy-modules.js, configs/mozilla-central-mappings.js, package.json, src/components/Editor/CallSite.js, src/utils/bootstrap.js, src/vendors.js, webpack.config.js, yarn.lock
This is a work in progress PR, intended for collaboration and discussion, do not merge!
cc @jasonLaster @ochameau  
I started doing some cleanup, and rebased on latest master.
In my opinion, TODOs:
=> [WIP] Transpile debugger modules for DevTools loader

assets/panel/dist.moz.build, assets/panel/index.html, assets/panel/moz.build, bin/copy-assets.js, webpack.config.js
- keep generating the debugger bundle in both development/nonDevelopment configurations
- modify copy assets to delete the debugger.js bundle
- update moz.build to remove references to debugger.js and debugger.css
- udpate dist/moz/build to add reference to debugger.css
- update references to new/debugger.css to new/dist/debugger.cdd
=> Generate debugger bundle when copying assets and keep only CSS artifact

bin/copy-modules.js, docs/debugging-firefox.md, docs/mochitests.md, docs/running-as-firefox-panel.md, package.json
- adds the ability to watch files so that we can incrementally transpile changed files while testing...
- adds a new `yarn watch` command that replaces `copy-assets-watch`
=> add --watch to copy-modules

src/actions/ast.js, src/actions/types/ASTAction.js, src/reducers/ast.js, src/utils/ast.js
setPausePoints only really uses id and text, so in order to get rid of the toJS it needed some scope changes in arguments passed.
=> Removes toJS from setPausePoints

src/components/Editor/SearchBar.css
Fixes Issue: #6179 
* change 1
Added align-items: center; to .search-bar class in SearchBar.css file.
* change 2
Removed `margin-top: 12px;` and added `align-self: center;` to `.search-field .close-btn`
Issue only showed up when opening the search files Modal and search text in file search bar. For testing we only needed to open the search fields and see that the "X" button was vertically centered and it IS.
=> [Search] Fix file search input close button alignment

src/components/shared/SearchInput.css
The 'Find in Files'  magnifying glass | input spacing is a bit tight, so this fixes the issue:
=> Improve 'find in files' layout

src/actions/sources/select.js, src/actions/sources/tabs.js, src/actions/types/SourceAction.js, src/actions/types/index.js, src/reducers/sources.js
`addTab` and `ADD_TAB` only use the source url, so in order to clear up some things further down the line it would be really useful to decouple `addTab` from needing the whole source object.
=> Makes addTab only dependent on url

src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
Provides a nice hover title for longer expressions; this is consistent with breakpoint items.
=> Add title for each expression

src/actions/pause/breakOnNext.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-pause-on-next.js, src/test/mochitest/helpers.js
Fixes Issue: #5446 
* added pause on next test (browser_dbg-pause-on-next.js)
* added pause selector under "selectors" in head.js to support clicking
on pause button
Current version of the test adds an expression to evaluate the function 
instead of using invokeInTab() to trigger pause in the debugger. When 
invokeInTab() is used, it does not seem to activate simple() in 
`src/test/mochitest/examples/simple3.js`
=> [Tests] add pause on next mochitest

src/actions/pause/index.js, src/actions/pause/selectComponent.js, src/actions/types/PauseAction.js, src/components/SecondaryPanes/ReactComponentStack.js, src/reducers/pause.js
For now this doesn't do anything other than highlight the selected component in the component stack. Eventually it should update the pane below it and also jump to a relevant location in the source.
=> WIP - [ComponentStack] Add ability to select component

src/components/QuickOpenModal.js, src/components/shared/SearchInput.css, src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
When we (I) merged the initial QuickOpen style updates for Photon, it became apparent the new CSS was too broad and that elements were enlarged that shouldn't have been -- just QuickOpen should have been increased in size.  This has been bugging me so I've taken the time to fix it.
Command+F (Find in File) and Command+G (Search Again)
Command+P (Quick Open)
Command + Shift + F (Full Project Search)
Command + Shift + O (Function Search)
Command + ; (Go to line)
=> Fix Photon styling for search inputs

packages/devtools-reps/src/object-inspector/tests/__mocks__/long-string-client.js, packages/devtools-reps/src/object-inspector/tests/component/create-long-string-client.js, packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-full-text.js, packages/devtools-reps/src/object-inspector/types.js, packages/devtools-reps/src/object-inspector/utils/client.js, packages/devtools-reps/src/object-inspector/utils/load-properties.js, packages/devtools-reps/src/object-inspector/utils/node.js, packages/devtools-reps/src/reps/rep.js, packages/devtools-reps/src/reps/stubs/long-string.js, packages/devtools-reps/src/reps/tests/long-string.js
Since I didn't have time to add these when the longstring expansion feature was
shipped, due to the then receeding deadline, I had left these out.
There's still need for some more unit tests (`setNodeFullText`,
`getFullText`) and integration tests such as the expand funtionality on the OI
component, but it's a start!
=> [ObjectInspector] Add some fulltext tests & minor optimisations

docs/mochitests.md
#Fixes #6297 
* Added information regarding troubleshooting test harness due to loss of symbolic links
* Added information regarding handling missing Rust compiler issue with test harness
=> Fixes #6297

src/components/Editor/SearchBar.js
Fixes Issue: #6255
Changes:
makes SearchBar recalculate results
Cause:
Pressing enter after a tab switch relied on the old state and did not update the result count. This lead to a series of undesired outcomes including bad error emoji state and stale count of found items.
Vid after change:
=> [Search] Makes SearchBar update results on enter press

src/actions/breakpoints.js
Fixes Issue: #6277 
* When enabling a breakpoint, we don't wait for the response from server, but the breakpoint is enabled optimistically
=> optimistically enable breakpoint in UI

packages/devtools-reps/src/reps/array.js, packages/devtools-reps/src/reps/object.js, packages/devtools-reps/src/reps/rep.js, packages/devtools-reps/src/reps/tests/array.js, packages/devtools-reps/src/reps/tests/failure.js, packages/devtools-reps/src/reps/tests/grip.js, packages/devtools-reps/src/reps/tests/object.js, packages/devtools-reps/src/reps/tests/string-with-url.js
`noGrip` defaults to `false` so the default rep should be `Grip` instead of `Obj`. The current behavior causes problems like https://bugzil.la/1377668 and https://bugzil.la/1457701. Better fail fast and loud and require `noGrip = true` for raw objects or arrays.
- The default rep is now `Grip` instead of `Obj`.
- The `Obj` and `ArrayRep` reps will refuse to render the object if `noGrip = true` is not specified.
- Fixed various tests that relied on the previous bad behavior.
I ported the changes to my mozilla-central repo and ensured that [browser_net_json-long.js](https://searchfox.org/mozilla-central/source/devtools/client/netmonitor/test/browser_net_json-long.js) fails, because netmonitor needs `noGrip = true` (https://bugzil.la/1457701). Better fail fast and loud than only in hard to …
=> Render object as grip when noGrip is false

.gitignore, circle.yml, docs/local-development.md, jest-lint.config.js, jest-stylelint.config.js, jest-test.config.js, jest.config.js, package.json, packages/devtools-components/jest.config.js, packages/devtools-components/package.json, packages/devtools-reps/jest.config.js, packages/devtools-reps/package.json, packages/devtools-source-map/jest.config.js, packages/devtools-source-map/package.json, packages/devtools-utils/jest.config.js, packages/devtools-utils/package.json, yarn.lock
Fixes Issue: #<issue number>
* Introduce `jest-runner-eslint` and `jest-runner-stylelint` in place of normal runners.
This is essentially a reopening of #6272 but split up from the work updating Jest.
@jasonLaster suggested doing this and opening up for discussion.
A good starting point is this [Jest as a Platform](https://www.youtube.com/watch?v=NtjyeojAOBs) talk  but I've bought in and love the idea of Jest as a platform because of the number of possibilities it opens up and the best in class tooling that Jest has. Jest is an awesome platform and having runners for linting makes for a nicer experience in terms of consistency but also pure developer experience as you can now have `yarn jest --watch` running and it'll lint your recently changed code and test it concurrently.
I'd love more …
=> ✨: Utilize Jest Runners for ESlint and Stylelint

packages/devtools-reps/src/object-inspector/component.js, packages/devtools-reps/src/object-inspector/tests/component/events.js
We weren't checking the appropriate event property on non-mac OSes.
This still need some webpack configuration, because I don't want to get devtools-modules into the reps bundle.
=> Fix onCmdCtrlClick handler.

src/actions/pause/paused.js, src/reducers/pause.js, src/utils/pause/stepping.js
Fixes #5941
Fixes two issues I was seeing
1. pausing at an IF condition w/ a breakpoint would not work 
- IF was an empty breakpoint
- should step was not checking if it was a "break" point
2. the debugger was pausing at the same position several time because should step was not taking into account previous locations from resumes or step in
- this was fixed by updating getPauseLocation
=> [pause] Additional pause point guards

src/actions/sources/loadSourceText.js, src/components/Editor/Footer.js, src/reducers/sources.js
`getGeneratedSource` only checks if source exists exists and grabs the `id` off of it. The same can be done with a `Record`, so there should be no need for a `toJS()` here.
=> Removes toJS from getGeneratedSource

src/components/Editor/Tab.js, src/components/Editor/Tabs.css, src/components/SecondaryPanes/Breakpoints.css, src/components/SecondaryPanes/Breakpoints.js, src/components/shared/SourceIcon.css, src/components/shared/SourceIcon.js, src/components/shared/Svg.css, src/utils/source.js, src/utils/tabs.js
Fixes Issue: #5999, #6000, #6001(?)
Debugger uses many icons throughout the App, most of the time based on characteristics of a source, yet we have multiple places where icons are calculated, and thus having one component to do all that repeated work would help with consistency of UI and maintainability of code.
Since this PR is only meant to cover the breakpoints pane and tabs, open tabs in blackboxed, pretty-print, and react states, and ensure they look good.  Ensure the same in the breakpoints pane.  Check out the tree that icons look good there as well.
I don't want this PR to grow out of control but there are a few things that still need to happen:
=> Introduce and Implement a SourceIcon Component

src/components/test/__snapshots__/SourcesTree.spec.js.snap, src/utils/source.js
The breakpoint function currently covered by `SourceIcon` is based on URL; this fixes that test.  We can address icons based on stuff other than URL in the next PR where we change the SourcesTree.
=> Fix dbg-breakpoint problem

bin/copy-assets.js, bin/copy.js
When i compared these two runs:
* `node bin/copy-assets.js --mc ../gecko --assets; node bin/copy-modules.js --mc ../gecko`
* `yarn copy --mc ..gecko` 
I was seeing that copy unintentionally had smaller parser and css bundles. This was causing mochitest failures and was the result of a weird timing issue i'd like to not think to hard about.
=> [releases] fix timing issue with bin/copy

packages/devtools-components/src/tree.js
bgrins is looking into removing explicitOriginalTarget from the platform,
and here, replacing it with relatedTarget has no effect on the Tree component.
- Pull this patch
- `cd packages/devtools-reps; yarn; yarn start`
- Open the reps test app and launch a new Firefox window
- In the app, evaluate `[]`
- Click on the TINY mode array to expand it
- Make sure that clicking the `length` property does select the length node
- Hit <kbd>Tab</kbd> to focus the SHORT array and make sure the node gets selected
=> Replace explicitOriginalTarget usage with relatedTarget in Tree

docs/local-development.md, package.json
* Also, document the `test:js` command which runs just the Jest unit test project
* Turns out there is an issue with the list format lint-staged uses and Jest. This fixes it by using
the CLI flag added here https://github.com/facebook/jest/pull/1678
=> 📝: Tweak developer experience for testing and linting

src/utils/source.js
Fixes Issue: source.text.split is not a function error message appears if source is wasm one.
* Return empty string for wasm source.
=> Fix getTextAtPosition() for wasm sources.

assets/panel/debugger.properties, src/components/SecondaryPanes/Breakpoints.js
We accidentally reverted pauseOnExceptionsItem2 when we synced between master and release.
https://bugzilla.mozilla.org/show_bug.cgi?id=1462630#c8
=> replace pauseOnExceptionsItem with pauseOnExceptionsItem2

src/components/Editor/index.js
all other `getSymbols` lack toJS, missed this one.
=> Removes stray toJS from getSymbols

src/components/Editor/Footer.js, src/components/Editor/Tab.js, src/components/Editor/Tabs.js
`getFilename` uses the `id` and `url` of the source record to find the name of the file and as such can live without the expensive `toJS` call. Properties on a Record can be accessed via the dot notation (it should even be possible to destructure them).
`getFileUrl` is in a similar situation.
=> Removes toJS from getFilename

packages/devtools-source-map/src/source-map.js
It is possible that a generated location does not map to a specific original location, in that case we might want to search for the best match given a bias.
=> add a search field for getOriginalLocation

src/components/shared/SearchInput.css
The alignment of the results line could be improved.
=> Better vertically center the result line in searches

src/components/QuickOpenModal.js, src/components/shared/SearchInput.css, src/components/shared/SearchInput.js
Fixes Issue: #6180 
* Move Loading message inside the SearchInput component and update font color
* Add test for loading message in SearchInput.spec
* Update QuickOpenModal snapshot
Simulate it by telling SearchInput we’re loading
=> [QuickOpen] Loading prompt

docs/getting-setup.md
Fixes Issue: none opened. 
* Removed redundant issue word before [issue](...) link.
=> Fix typo in getting-setup.md

src/actions/pause/extra.js, src/components/Editor/Preview/Popup.js, src/components/SecondaryPanes/Frames/WhyPaused.js, src/components/SecondaryPanes/FrameworkComponent.js, src/types.js, src/utils/pause/why.js, src/utils/preview.js
When we switched to using inComponent, we stopped differentiating between hovering on `this` and other properties as a result, Popup always assumed we wanted to preview the component.
=> [Preview] identify if it is react

packages/devtools-components/src/tree.js
Not having it was causing issue in the console (See [Bug 1463057](https://bugzilla.mozilla.org/show_bug.cgi\?id\=1463057)),
and I think it's safe to stop the propagation since click events are handled
through renderItem result.
- Made sure all the object inspectors could be expanded (watch expression, scopes panel and preview popup)
- Made sure you can still edit a watch expression
- Made sure you can still select a source clicking on an item in the Source panel
=> Stop the propagation on tree node click.

configs/mozilla-central-mappings.js, packages/devtools-reps/package.json, packages/devtools-reps/src/object-inspector/component.js, packages/devtools-reps/webpack.config.js, yarn.lock
We add an alias for Services so we use the one from mozilla-central.
This means we also need to add a moduleMapper entry for jest test to pass.
---
**TEST PLAN**
- `cd packages/devtools-reps; yarn; yarn start`
- Make sure you can access the reps test app and evaluate things
- Creating the reps bundle should work, and it shouldn't include devtools-modules code
- Running the debugger in launchpad should work as well
=> [reps] Don't include devtools-modules in the reps bundle.

src/components/Editor/Tab.js, src/utils/source.js, src/utils/sources-tree/getURL.js, src/utils/tests/source.spec.js
Fixes Issue: #5977
* Adds Unicode support in source.js so that URL & Filename & Domain name labels display readable Unicode text.
The invovled labels are: groups of source trees, filenames of tabs, tooltips of
filename tabs, filenames of breakpoints.
* Adds Unicode tests for source.js.
* Unicode support for filename parts can be tested at https://dbg-unicode.glitch.me/
* Unicode support for domain name parts can be tested at http://nic.世界
=> [Tabs] Add Unicode support for various URL & filename & Domain name labels

src/utils/source.js, src/utils/sources-tree/tests/utils.spec.js, src/utils/sources-tree/utils.js
`getExtension` only ever uses the url, it doesn't need the whole source object.
=> Refactors getExtension to only use url

package.json, yarn.lock
Fixes Issue: it is not possible to locate/step/break at end of the wasm function
* wasmparser disassembly now assigns right offset to the end of the function (parenthesis)
=> Update wasmparser dep: allows to index end of function by offset.

src/components/Editor/Tabs.css
=> Add a max-width to sourcetabs to avoid chevron overlap

src/components/ProjectSearch.css, src/components/shared/SearchInput.css
This fixes a few minor nits to the search inputs, including:
- The change between smily and magnifying glass looked weird, I think because of the difference in the overall design, so I shifted the smily and the transition feels smoother.
- The close button was a few pixels low 
- Added end spacing to result summary; it looks lit now
=> Minor tweeks to search input icons and close button

src/components/SecondaryPanes/Breakpoints.css
There are approximately 3 pixels above the codemirror breakpoint text that shows the default cursor, and I found this legacy CSS.
=> Fix edge of breakpoints cursor

src/components/Editor/Tab.js, src/utils/tests/text.spec.js, src/utils/text.js
Fixes Issue: #5019 
* Create a utility method to truncate text in the middle (...)
* Create test for this utility method
=> [Tabs] Improve truncation of long filenames

src/components/ShortcutsModal.css
Firefox supports the unprefixed version since version 52, so I’m removing the unnecessary prefix.
- [bug 1308587](https://bugzil.la/1308587 "Use script to remove -moz- prefixes from all usages of CSS multi-column properties in the tree (except for code that adds/intentionally-targets prefixed aliases)")
=> Remove unnecessary `-moz-column-width` property

src/utils/source.js
the isWasm check doesn't use line numbers and it also returns, so we can safely merge it with the other insta-return conditions.
=> Moves isWasm up

src/client/index.js, src/utils/editor/source-documents.js, src/utils/path.js, src/utils/result-list.js, src/utils/task.js, src/utils/text.js, src/utils/utils.js, src/utils/wasm.js, src/vendors.js
Tracking functions and constants seems easier with all information in one place.
If we separate out the export statement there is an additional step required to check if the function we are looking at is actually being exported.
=> Moves export statements in front of functions and consts

src/components/Editor/Preview/Popup.js
I noticed when a class is `class Foo extends React.Component {}` that we dynamically notice we're in react, but statically miss this. This check mandates that both checks are positive.
=> [preview] check to see if we statically found a react class

src/actions/pause/extra.js
Fixes Issue: #6315
@gregtatum didn't have STR but tracing through our code, `getExtra` can return `undefined` if there's no `selectedFrame`.  Instead of requiring a check for `if(extra && extra.whatever)` everywhere, I think we should return an empty object in this case.
=> Prevent extra from being undefined

src/utils/source.js, src/utils/sources-tree/index.js, src/utils/sources-tree/utils.js
Renames getExtension to getFileExtension to make it clear it gets the File extension and not any other we might have introduced in the codebase.
=> Renames getExtension to getFileExtension

packages/devtools-reps/src/reps/element-node.js, packages/devtools-reps/src/reps/reps.css, packages/devtools-reps/src/reps/tests/element-node.js
* Set pointer cursor to `.objectBox-node` element in case of the element was clickable
* Set pointer cursor to `.open-inspector` element
This changes are for https://bugzilla.mozilla.org/show_bug.cgi?id=1463780
Please run yarn test
=> Bug 1463780 - Set cursor style to element-node rep

packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/tests/string-with-url.js
Fixes Issue: #6448
* Pass event object when openLink is called on click in the string rep.
Components that specify openLink will now be able to access click event's properties like (meta/ctrl/shift keys).
=> Pass event object when calling openLink in reps(#6448)

src/components/shared/Accordion.js, src/components/shared/tests/__snapshots__/Accordion.spec.js.snap
Fixes Issue: # 4080 (Expand/Collapse headers with Keyboard)
**Summary of Changes**
- We have a bug fix though the we can expand and collapse the headers with the spacebar and Enter key only.
**Test Plan**
- Going though the debugger panel we can shift to the next object with tab when landing on the headers "Watch Expressions" and "Breeakpoints" we can then expand and collapse them with using the space bar and Enter key only, other keys do not do anything.
=> accordion accessibility #4080 Need to be able to collapse expand headers with keyboard

.travis.yml, src/components/Editor/index.js, src/components/PrimaryPanes/SourcesTree.js, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/utils/editor/index.js, src/utils/editor/source-editor.js
Fixes Issue: #6439 
* adds a new CodeMirror field to the SourceEditor so that we can use the class before an editor is intantiated 
* this will need a similar fix in the m-c SourceEditor before the tests pass
* hopefully this simplifies things too
=> [Breakpoints] show before a file is shown

src/utils/editor/source-editor.js, src/utils/source.js, src/utils/tests/source.spec.js
Fixes Issue: #6445
* Added syntax highlighting for Haxe (.hx) files within the debugger.
* I've implemented this by simply matching against the .hx file extension in the url. I felt I could not use content type to match against as it was always reported as text/plain for haxe files.
I've added a unit test to source.spec.js for the getMode function. 
I've also noticed that the test style is a bit inconsistent among the suites. 
I prefer the it("should...") style but I kept it consistent with tests in the same suite. 
I would like to know If a test cleanup would ever be on the table.
I'd be happy to help with that.
Before:
After:
=> Added haxe syntax highlighting support

src/components/PrimaryPanes/SourcesTree.js, src/components/QuickOpenModal.js, src/selectors/getRelativeSources.js, src/utils/quick-open.js, src/utils/sources-tree/addToTree.js, src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap, src/utils/sources-tree/tests/addToTree.spec.js
Fixes Issue: #6027
I believe this should fix this use case by re-creating the source tree with relative sources. There are a couple of up-sides:
1. perf - the work is done in the selector so we no longer need to figure out what goes in and out of the tree
2. simplicity - i started removing projectRootUrl from all of the tree code, which is a great cleanup
yep, we should write some more mochitests here
=> [tree] switch to relative sources

src/components/SecondaryPanes/Breakpoints/Breakpoints.css
A few breakpoint alignment modifications; the breakpoint text looked low on both Mac and Windows, while the line number looked too high.
=> Improve breakpoint alignment

src/components/SecondaryPanes/Scopes.js
Adding the `openLink` prop to `ObjectInspector` allows our users to open a link from the scopes pane.  Yay!
1.  Open https://davidwalsh.name in the debugger
2.  Open and pretty-print `main.js`, add a breakpoint to line 42 (`z.isDebug && sessionStorage.clear();`)
3.  Refresh the debugee tab, wait for breakpoint to hit
4.  Expand `Window: Global` in the scopes pane
5.  Expand `z`, then `d`, then click the URL property's value.
Link should open in new window
=> Clicking a link in a scopes object opens link

src/components/SecondaryPanes/SecondaryPanes.css
Fixes Issue: #6478
Allows users to copy scope properties and values.  This declaration was overly broad.
- Set a breakpoint, refresh your source page, wait for breakpoint to hit
- Hover over and copy values in the Scopes' pane tree
- @digitarald will be very happy when this is in
=> Allow for clicking and copying scopes information

src/utils/sources-tree/getURL.js, src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap, src/utils/sources-tree/tests/utils.spec.js
Fixes Issue: #5759
Adds separation for plugins and resources displayed in source tree by host:
Screenshot:
=> Separates plugins and resources by host

src/components/Editor/Editor.css
Fixes Issue: #6451
When you scroll the editor horizontally and then hover a line, the breakpoint hover arrow doesn't display because we aren't allowing the `left` property to change.  Setting a negative margin works much better.
1.  Hover over a line, ensure the breakpoint arrow displays
2.  Scroll horizontally, hover over a line, ensure the breakpoint arrow displays
=> Fix #6451 - Ensure breakpoint hover is always correct

src/components/Editor/Breakpoint.js
Fixes Issue: #6355
* remove `shouldComponentUpdate` in Breakpoint.js
If the editor is not ready before the breakpoint tries to render, the breakpoint never gets shown.
`shouldComponentUpdate` stops the breakpoint from updating after the editor is ready.
**Note:** One concern was the possible performance hit, but i don't think that is an issue because it still feels instant, as i think react figures out how to not re-render the breakpoints. see (after screenshot)
-  debug http://firefox-dev.tools/debugger-examples/examples/todomvc/
- open `backbone.js` in the debugger
- set breakpoint on line 12
- close `backbone.js`
- refresh the debugger
- click to open `backbone.js` from the source tree
AR:
No breakpoint set on line 12 in the editor
ER:
Breakpoint should be set on line 12
On reload & …
=> allow update always

src/components/Editor/Editor.css
While my #6485 works well for most JS files, it doesn't look good in WASM, so we should revert and try again.
=> Reverts 6485; Restore breakpoint arrow calculation

configs/mozilla-central-mappings.js
This is really a nit, but this should make it easier to isolate the hacky usage of devtools/shared/flags.
=> Extract "excluded" mc mappings to dedicated object

src/components/SecondaryPanes/Breakpoints/index.js
`:formatted` is showing at the end of URLs in breakpoint heading `title` attributes.  Boooo.
=> Remove :formatted from breakpoint heading title

package.json, src/actions/tests/__snapshots__/ast.spec.js.snap, src/components/SecondaryPanes/Frames/Frame.js, src/reducers/ast.js, src/reducers/sources.js, src/workers/parser/getSymbols.js, src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap, src/workers/parser/utils/formatSymbols.js, yarn.lock
=> [Flow] Upgrade to 68

src/components/shared/Popover.js, src/components/shared/tests/Popover.spec.js, src/components/shared/tests/__snapshots__/Popover.spec.js.snap
Fixes Issue: #6474 
* Added code to the `getTooltipCoords` function in `Popover.js` to set the top position below the target when there is not enough room between the editor.top and target.top.
* Added 2 new test cases and updated a snapshot.
**Tell us a little a bit about how you tested your patch.**
I ran the debugger and verified that tooltips for targets at the top line of the editor now show below the target and no longer extend past the editor.  I also added two unit tests but will need help getting them to work if you want to keep them.  The problem is that in the test environment [this line](https://github.com/devtools-html/debugger.html/blob/7eb88759712140709d56f6df2020396701c6bddd/src/components/shared/Popover.js#L139) reports the height of the popover as `0` which messes up the …
=> display tooltip below target when not enough space above

.travis.yml, bin/ci/clone-gecko.sh
We have been seeing intermittent travis failures for the past month or so. David noticed early on that it looks like it is an out of memory issue. 
This PR tries to fix that by doubling our RAM from 4gb to 7.5gb (i think). [link](https://docs.travis-ci.com/user/reference/overview/).
I think I have some evidence to show that we have an OOM issue:
A recent build had this output for the `hg clone`. The `killed!` output is weird, but I think the important thing is the `137` exit code which looks like a standard linux and docker code for memory issues.
Another indicator that the clone failed is when the update includes the message `untracked file differs` and has this error message `abort: untracked files in working directory differ from files in requested revision`
=>  Fix Travis intermittent failures

.flowconfig, flow-typed/npm/reselect_v3.x.x.js, src/actions/ast.js, src/actions/breakpoints.js, src/actions/pause/continueToHere.js, src/actions/pause/extra.js, src/actions/pause/paused.js, src/actions/preview.js, src/actions/sources/blackbox.js, src/actions/sources/loadSourceText.js, src/actions/sources/select.js, src/actions/types/SourceAction.js, src/actions/utils/middleware/promise.js, src/reducers/ast.js, src/reducers/debuggee.js, src/reducers/pause.js, src/reducers/replay.js, src/reducers/sources.js, src/selectors/inComponent.js
Fixes Issue: #5122 
This adds flow type definitions for reselect, which is important for validating PropTypes and improving our redux action and selector coverage
=> [flow] add types for reselect

package.json, src/actions/pause/mapFrames.js, src/components/QuickOpenModal.js, src/components/test/__snapshots__/QuickOpenModal.spec.js.snap, src/types.js, src/utils/ast.js, src/utils/pause/frames/annotateFrames.js, src/utils/pause/frames/collapseFrames.js, src/utils/pause/frames/getLibraryFromUrl.js, src/utils/quick-open.js, src/workers/parser/getSymbols.js, yarn.lock
Fixes Issue: #5687
* starting with 68 here #6501
=> [Flow] Upgrade to 70

packages/devtools-components/src/tree.js, src/components/PrimaryPanes/SourcesTree.js, src/components/test/__snapshots__/SourcesTree.spec.js.snap
One thing that bugs me is when I click an item in the source tree and then navigate over to the editor, the focused source's highlight disappears.  IMO it shouldn't -- the focused file should always be highlighted in the tree.
=> [SourceTree] Don't blur when tree is no longer focused

assets/panel/prefs.js, src/actions/pause/skipPausing.js, src/client/firefox/commands.js, src/components/SecondaryPanes/CommandBar.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-breakpoint-skipping.js, src/test/mochitest/helpers.js, src/utils/prefs.js
Fixes Issue: #6512
- `yarn copy`
- `cd firefox && ./mach build faster`
- `./mach run`
- Go into `about:config` and turn on `debugger.features.skip-pausing`
- Restart Firefox (`./mach run`)
- Toggle on and off the button and ensure breakpoints are either hit or not.
=> [Breakpoints] Enable skip all pausing button in dev

src/components/shared/ManagedTree.js, src/components/test/SourcesTree.spec.js, src/utils/sources-tree/addToTree.js, src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap, src/utils/sources-tree/tests/addToTree.spec.js
Fixes Issue: #5918
This `else` clause is causing mischief in the SourcesTree, and I don't see its value, so removing.
1.  Go to https://davidwalsh.name
2.  Click on "(index)"; the item should highlight
3.  Expand `ad.doubleclick.net` and its subfolders; click on the oddly named files; they should also highlight
1.  This also seems to fix #6462
=> [SourceTree]  Prevent index weirdness

configs/mozilla-central-mappings.js, docs/local-development.md, packages/devtools-reps/package.json, src/actions/sources/loadSourceText.js
This patch adds a telemetry stub and points it at the real `telemetry.js` for code that lives on Mozilla Central.
We also now use `telemetry.start()` and `telemetry.finish()` for the timing inside `src/actions/sources/loadSourceText.js` instead of calculating the duration ourselves.
=> Stop using Services.telemetry directly. Fixes #6258

src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-breakpoints-actions.js, src/test/mochitest/helpers.js
Fixes Issue: #6519 
* Add a breakpoints prop to Breakpoint compnent that gets data from redux selector
Ran the debugger as a web app and set some breakpoints.  Then I right clicked on a breakpoint and verified the context menu displayed and the error did not come up in the console anymore.  I tried the features of the context menu and they all seemed to work properly.  
**Note:** after thinking about this I realized the data from the selector I chose might not be what the component is expecting.  Someone more familiar with the design of the component might want to verify this is the correct data for the breakpoints prop.
=> [Breakpoints] fix missing redux prop

src/components/Editor/Tabs.js
We started seeing this error once we converted from immutable to plain source objects. It would be nice to improve our Props so we don't have to hand-encode the props or they check to see if it is the right signature.
=> [Tabs] fix selectedSource reference

flow-typed/npm/react-redux_v5.x.x.js, src/components/App.js, src/components/Editor/Footer.js, src/components/Editor/Preview/index.js, src/components/Editor/SearchBar.js, src/components/Editor/Tab.js, src/components/Editor/Tabs.js, src/components/Editor/index.js, src/components/PrimaryPanes/Outline.js, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/index.js, src/components/ProjectSearch.js, src/components/QuickOpenModal.js, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/index.js, src/components/SecondaryPanes/CommandBar.js, src/components/SecondaryPanes/EventListeners.js, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/FrameworkComponent.js, src/components/SecondaryPanes/Scopes.js, src/components/SecondaryPanes/index.js, src/components/WelcomeBox.js
Fixes Issue: #5072
* Adds flow support for react-redux
* Fixes all the ambiguous flow types - i like that one consequence is that we now only pass in the actions that we use
* This inspires me to add coverage to some components and component types that are lacking
We now catch warnings like this!
=> [flow] type react-redux

src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js
Most of the breakpoints context menu items are broken because those props aren't provided to the context menu.
Note: We should add tests but I'm hoping a contributor can help with those.
=> Fix breakpoints panel context menu items

src/actions/breakpoints.js, src/actions/breakpoints/syncBreakpoint.js, src/actions/sources/newSources.js, src/utils/source.js
* fixes an intermittent with [dbg-navigation][dbg] [graph][g]
* The underlying issue is that the test does 3 navigates, the second navigate starts before we are done syncing a breakpoint, the result is that a source is not available mid-sync and the command fails. 
It's hard to see a timing issue and not have some thoughts:
1. the flow types are really helpful - we should continue investing
2. the code assumes via `getSourceFromId` that we will definitely have it, that is a bit naive. It is better to be conservative.
3. it would be cool if before navigating we we could cancel in progress actions 
4. alternatively, it would be cool if we could see that there were in progress actions and wait for them to finish...
these are just thoughts... largely, i think our system is getting more stable …
=> [breakpoints] Fix timing issue with syncing breakpoints

packages/devtools-components/src/tree.js
This introduced a regression in the ObjectInspector (see [Bug 1469959](https://bugzilla.mozilla.org/show_bug.cgi\?id\=1469959)).
Let's see how to handle the removal of explicitOriginalTarget later.
=> Rollback PR #6335.

src/components/Editor/Footer.js
We don't allow blackboxing for pretty-printed sources so there's no reason to show a button that does nothing.
=> Don't show the blackbox button for a pretty printed source

src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js, src/workers/parser/getScopes/visitor.js, src/workers/parser/tests/__snapshots__/getScopes.spec.js.snap, src/workers/parser/tests/fixtures/scopes/expressions.js
Refs Issue: #6400
* Ignore matching import bindings to `__webpack_require__.i` to handle Webpack 2
This approach isn't the best since it'll fail for code that has been minified, but I'm struggling to think of any other way for us to handle it with the way things are now.
In the future it'd be awesome if we could rely on Spidermonkey itself to have a "speculative execute" to get a value without side-effects, but until that happens, this seems like the only way.
=> [scopes] Handle Webpack 2-style ESM identity wrapper fn

src/components/Editor/Tab.js, src/components/PrimaryPanes/SourcesTree.js, src/components/SecondaryPanes/Breakpoints/index.js, src/reducers/sources.js, src/selectors/breakpointSources.js, src/utils/source.js, src/utils/sources-tree/addToTree.js, src/utils/sources-tree/getDirectories.js, src/utils/sources-tree/getURL.js, src/utils/sources-tree/tests/addToTree.spec.js, src/utils/sources-tree/tests/getUrl.spec.js, src/utils/sources-tree/tests/utils.spec.js, src/utils/tests/source.spec.js
Fixes Issue: #6394
* re-uses getURL in getFilename which is the main other call site
* memoizes getURL so that we only parse a url once, this is one of the top slow downs for the tree
* removes getFileNameFromUrl because it can't be memoized
* unit tests
Go to youtube.com, look at video_masthead, embed (index)
* hover on tabs,  breakpoint file groups, source tree items
=> [Tabs] Title Not Matching Tree Title

src/components/SecondaryPanes/CommandBar.js
* When recording/replaying, fix bug where pressing resume when paused has no effect.
* When recording/replaying, always show pause button when unpaused.  Per email discussion this is nice to have to interrupt an execution and start rewinding (or interrupt a rewinding execution and pause or play forward).
=> Web replay tweaks

src/components/Editor/tests/Editor.spec.js, src/utils/editor/source-documents.js
Fixes Issue: #6507
* fetch editor mode option from the editor as opposed to the doc
* this should speed up stepping large documents that might have had a big syntax highlighting component
lets write a jest unit test to assert that we don't call setMode more than once
=> [Editor] get mode from editor

src/utils/telemetry.js, src/utils/tests/telemetry.spec.js
This greatly simplifies debugger telemetry... of course, the appropriate events need to be present inside `Events.yaml` for them to work.
```js
import { recordEvent } from "src/utils/telemetry"; // Correct the path as appropriate
// Event without extra properties
recordEvent("add_breakpoint");
// Event with extra properties
recordEvent("pause", {
"reason": "debugger-statement",
"collapsed_callstacks": 1
});
```
=> [Telemetry] Add recordTelemetryEvent() helper to debugger util fixes #6529

bin/copy.js
looks like we broke copy with the work to update transformModule for devtools-modules
=> [release] switch to copyModules.run

src/actions/tests/__snapshots__/preview.spec.js.snap, src/actions/tests/preview.spec.js, src/selectors/inComponent.js, src/workers/parser/getSymbols.js, src/workers/parser/utils/helpers.js
Fixes Issue: #6331 
* Pretty much followed @jasonLaster comments on the issue. 
- Open https://firefox-debugger-example-react-js.glitch.me/ debugger test page
- Select parse-worker from workers
- Command-P opens the panel and look for getSymbols.js
- Put a breakpoint in line 148
- Reload the target debug page
- It'll hit the breakpoint, then step over
- `symbols.classes` array has the `UnorderedList` object with the parent as shown in the screenshot
Object in parser-worker.js, parent added as React.Component
=> [Preview] Recognize React.Component as a parent class.

src/reducers/sources.js
When we removed immutable we added a `get` shim for a test. The shim had bug, which we should fix now because it is causing sources to always be different. We should then try to remove the shim as soon as possible here #6600
=> [sources] fix isTesting

.travis.yml, src/reducers/sources.js, src/test/mochitest/browser_dbg-search-project.js, src/test/mochitest/browser_dbg-sources.js
this is a shim we added so that one of the console mochitests would still pass. We should remove it now that we've landed the immutable work and can easily update the MC mochitest.
=> [Sources] remove get shim

src/actions/tests/ui.spec.js, src/selectors/breakpointSources.js, src/selectors/getRelativeSources.js, src/utils/source.js, src/utils/sources-tree/addToTree.js, src/utils/sources-tree/createTree.js, src/utils/sources-tree/getURL.js, src/utils/sources-tree/updateTree.js, src/utils/sources-tree/utils.js
This is a really nice performance win I saw by looking at perf.html and I thought that I'd get the win while i could. Last week we switched to memoizing getURL, this opened up the opportunity to prevent doing a ton of unnecessary parsing:
- debuggeeHost 
- file extensions
- relative urls...
=> [sources] prevent unnecessary parsing

src/components/Editor/Editor.css
An awesome contributor made a valiant effort in creating a breakpoint hover effect in this PR:
https://github.com/devtools-html/debugger.html/pull/5979
Unfortunately it doesn't work properly when the editor is scrolled to the right (https://github.com/devtools-html/debugger.html/issues/6451) and creates a weird shifting side effect when code-folding is enabled.
Since neither the old debugger or Chrome have a hover effect, and this effect was just introduced a few months ago, I think it's safe to remove the hover effect for now and try a different solution.
=> Revert breakpoint hover effect

src/components/Editor/Editor.css
Fixes Issue: #5603, #6627
Add grey hover effect to the breakpoints in gutter
* Open a JS file.
* Hover over the gutter line numbers.
* Line numbers should be highlighted.
* Empty lines shouldn't be highlighted.
* Existing breakpoints shouldn't be highlighted.
=> Add breakpoint hover effect in gutter

src/reducers/sources.js, src/vendors.js
Fixes Issue: #6640
* import lodash-move as `import move from "lodash-move"`
* import without destructuring in vendors.js
=> Fix vendoring of lodash-move

src/actions/file-search.js, src/actions/tests/file-search.spec.js, src/utils/editor/source-search.js
Fixes Issue: #6608
During the file search, instead of simply ignoring the case where the search string is empty, I call the clearSearch function which is imported from source-search.js.
=> fix(search): highlight stays after deleting a search string

src/components/Editor/Footer.js
Fixes Issue: #6643
In https://github.com/devtools-html/debugger.html/commit/8e773b9911579b4dfa114600c184b23b14612942#diff-701eb9ae1383078fc8b17995acdd81bbR341 we made a change to return the source instead of `null`, so now we need this check.
=> Don't show mapped source footer link when source is original

src/components/Editor/Editor.css
- The quotes were keeping the svg from being copied from github ` mask: url('/images/breakpoint.svg') no-repeat;`
- the rest was just prettier
=> include breakpoint.svg

src/actions/breakpoints.js, src/actions/breakpoints/tests/breakpoints.spec.js, src/actions/tests/helpers/breakpoints.js, src/components/Editor/index.js, src/selectors/breakpointAtLocation.js, src/selectors/index.js, src/test/mochitest/browser_dbg-breakpoints-actions.js, src/test/mochitest/browser_dbg-editor-gutter.js
Fixes Issue: #5833
There's a fair amount of repetition here but it's a good starting off point for discussion.  
1.  Go to https://davidwalsh.name/ , open tab for `main.js`, pretty print it
2.  Create breakpoints at various lines in the pretty printed tab
3.  Switch over to the original `main.js` tab
4.  Click the breakpoint marker on line 1
5.  All breakpoint should disappear.
=> Fix 5833 - Remove all breakpoints on a line

src/actions/tests/__snapshots__/ast.spec.js.snap, src/workers/parser/pausePoints.js, src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
Currently step over stops twice at the end of functions with a return value. This is because the first pause is the `onStep` and the second is the `onPop`. We want to prevent the first one because it doesn't show the completion value and is redundant.
```js
function f() {
return 2;
}  // <--- pauses twice here
```
=> [Parser] prevent step over from pausing at the end of functions

src/actions/breakpoints/addBreakpoint.js, src/actions/breakpoints/index.js, src/actions/breakpoints/syncBreakpoint.js, src/actions/breakpoints/tests/syncing.spec.js
the goal here is to organize the breakpoint actions so that it is similar to sources and pause actions where each action is in its own module.
- moves the action file into the directory so it is easier to split up going forward
- moves the add and sync actions into their appropriate files
=> [Breakpoints] move actions file

src/components/Editor/Preview/Popup.css, src/components/Editor/Preview/Popup.js, src/components/shared/Popover.js, src/components/shared/tests/__snapshots__/Popover.spec.js.snap
Fixes Issue: #5134
Supercedes https://github.com/devtools-html/debugger.html/pull/6537
=> [Preview] Don't allow popover to move outside editor boundaries

src/components/Editor/Preview/Popup.js, src/components/shared/Popover.js, src/components/shared/tests/Popover.spec.js, src/components/shared/tests/__snapshots__/Popover.spec.js.snap
Fixes Issue: #6648 
A keyDown event listener has been added to the component popover so that it closes on "esc" key press.
=> fix(popover) hitting esc closes popover

src/actions/sources/select.js
@jasonLaster, Here is the refactor for getting rid of the duplicate code in `selectLocation` and `selectSpecificLocation` that we discussed in the [PR](https://github.com/devtools-html/debugger.html/pull/6559/commits/b5bf774f258ae6d7c5675e945502384c06ef3ae9#r199635659) we just did.
=> [Sources] eliminate duplicate code in selectSpecificLocation action

package.json, packages/devtools-source-map/package.json, packages/devtools-utils/package.json, yarn.lock
Should fix issue #6679 
@nchevobbe I am absolutely not sure about what I did, especially specifying "workspaces" inside of the packages themselves. The one change I would love to see in the next debugger bundle is https://github.com/devtools-html/debugger.html/commit/9048eb7e0bfc88946411bde0c7af223acc30e6f8
Have fun poking at this, mobile network is not the best to `yarn install` stuff :)
=> Use local devtools-utils, use explicit version for workspace packages

packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/reps.css, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap
At the moment when one try to copy and paste the stacktrace
of an error object, everything gets mangled in the same line,
making it very hard to read.
This patch adds a tab character before each function name as
well as a new line after each frame so what the user gets in
the clipboard looks more like what they see on the output.
1. Launch the reps test app (`cd packages/devtools-reps && yarn start`)
1. Open a firefox window and select a tab as a target
1. In the reps test app (with the purple header), click on the "errors" button. This will log 3 different error object in different mode
1. Copy an error object with a stacktrace (either small or long mode)
1. Paste it in an editor/textarea
-> It should be nicely formatted
---
A mochitest will probably be added in mozilla-central to make …
=> Make stacktrace copy/paste more useful

src/actions/file-search.js, src/utils/wasm.js
Fixes Issue: #6584
Quick fix
* handle wasm sources
1) Load http://janodvarko.cz/test/wasm/basic1/
2) Press `Load Module & Execute Exported Function` button
3) Go to the debugger and select `test.wasm` file
4) Press Ctrl+F (win) or ⌘⇧F (mac) to open an input field for searching in the current file
5) Type `module`
6) There is no result and the text turns red eve though the text is there -> BUG
=> handle search for wasm files

src/components/shared/Popover.js
The top value was persistently 0, which is odd; I'm wondering if it's to do with "Do not use setState in componentDidMount (react/no-did-mount-set-state)"
=> Fix Popover - Ensure top is enforced

src/components/WelcomeBox.css
Fixes Issue: #6251
Is no longer full length:
=> Fix #6251 - Better contian the length of shortcut buttons

packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/stubs/error.js, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap, packages/devtools-reps/src/reps/tests/error.js
In order to build the stacktrace we parse the string we
receive from the server. In some cases, the stacktrace
can be very long and a longString is sent instead of a
string. This means that the property that we check might
have a cut-off location at the end.
Due to a placement error in an if, it could happen that
this last cut-off element would throw.
The fix is made by correctly guarding the property we
are checking.
We take this as an opportunity to change how we handle
the last frame (we don't include it in the stack array
we build, instead of putting it and then removing it).
A snapshot test is added to make sure everything is
working as expected.
=> Fix bug in Error stacktrace generation when stacktrace is a longString.

src/test/mochitest/browser_dbg-sourcemapped-scopes.js, src/utils/pause/mapScopes/getApplicableBindingsForOriginalPosition.js, src/utils/pause/mapScopes/index.js
Refs Issue: #6400
cc @jasonLaster 
* Remove the range-merging logic so we work directly with the ranges from the sourcemap, since I don't think it's actually doing anything useful.
* Move the full-line range test to _after_ we assign `hadApplicableBindings` so that bindings in full-line ranges properly cause a binding to not count as `(optimized out)`.
=> Perform the line-range check later so that we still search for applicable bindings for (optimized out) handling.

src/components/Editor/Tab.js, src/components/Editor/Tabs.css, src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Breakpoints/index.js, src/reducers/sources.js, src/utils/source.js, src/utils/tests/source.spec.js
Gets unique name with path for breakpoints
Fixes Issue: #6005
* Show directories for files with same names in the breakpoint list
* Open a project which has files with same filenames
* Add breakpoints in line of two files with same name, and one breakpoint in a file with unique filename
* Directory should be visible with the common filenames in the breakpoint list, and should not be visible in the file with unique filename
=> Solves issue 6005 - files with same filename

src/actions/breakpoints/tests/__snapshots__/syncing.spec.js.snap, src/actions/breakpoints/tests/syncing.spec.js, src/actions/sources/newSources.js, src/actions/tests/pending-breakpoints.spec.js, src/reducers/pending-breakpoints.js, src/reducers/types.js, src/utils/bootstrap.js
issue: #6279
* switches pending breakpoints to a plain object
* this will make it easier to persist / serialize 
* it also will help us flow type breakpoints
flow and jest were clutch here
=> [Breakpoints] Switch Pending BPs from Immutable to Pojo

src/components/PrimaryPanes/Sources.css
Fixes Issue: #6718 
1.  Open the sources pane so that there should be scrollbars.  Ensure there's only one scrollbar for vertical and one for horizontal.  Same for Outline pane.
2.  Set a directory root.  Ensure there's only one scrollbar for vertical and one for horizontal.  Same for outline pane.
=> Fix 6718 - Allow scrolling in sources tree and outline panes

packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap
This is what happen when we rush things :/
=> Add missing space between function name and location in stacktrace 

src/actions/sources/newSources.js, src/actions/sources/prettyPrint.js
Fixes Issue: #6704 
Since `addSources` doesn't gets called for pretty sources, so we missed checking for pending breakpoints.
=> breakpoints set on pretty source visible on reload

src/actions/pause/pauseOnExceptions.js, src/actions/pause/tests/__snapshots__/pauseOnExceptions.spec.js.snap, src/actions/pause/tests/pauseOnExceptions.spec.js
Fixes Issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1463117
We should wait on https://github.com/devtools-html/debugger.html/pull/6671 being merged first
=> Fix 1463117 - Add telemetry for pause on (caught) exceptions

packages/devtools-reps/src/launchpad/components/Result.js, packages/devtools-reps/src/object-inspector/component.js, packages/devtools-reps/src/object-inspector/tests/component/expand.js
This calls recordTelemetry event with the object_expanded event name
when the object inspector is expanded.
A test is added to make sure this works as expected.
Also, we now pass a recordTelemetryEvent prop to the ObjectInspector in the reps-launchpad for manual testing sake.
=>  Instrument object expansion with telemetry

src/components/A11yIntention.css, src/components/A11yIntention.js, src/components/App.css, src/components/App.js, src/components/Editor/Footer.css, src/components/Editor/SearchBar.css, src/components/PrimaryPanes/Sources.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/Scopes.css, src/components/shared/Accordion.css, src/components/shared/Button/styles/CloseButton.css, src/components/shared/Button/styles/CommandBarButton.css, src/components/shared/SearchInput.css, src/components/test/A11yIntention.spec.js, src/components/test/__snapshots__/A11yIntention.spec.js.snap
Fixes Issue: #6628 
* Introduces a React component which detects keyboard vs mouse interaction
* Applies a class indicating what mode of interaction is being used
* Styles focus outlines so that they only show up when the keyboard is being used
* Removes `outline: 0` from everywhere else, so that keyboard users can see what has focus
Coming soon...
=> Conditionally show focus indicators

.babel/transform-mc.js, configs/mozilla-central-mappings.js, docs/dbg.md, src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap, src/actions/tests/pending-breakpoints.spec.js, src/client/index.js, src/reducers/pending-breakpoints.js, src/test/mochitest/browser_dbg-sourcemapped-breakpoint-console.js, src/test/mochitest/helpers.js, src/utils/asyncStoreHelper.js, src/utils/bootstrap.js, src/utils/dbg.js, src/utils/prefs.js, src/utils/tests/asyncStoreHelper.spec.js
Fixes #6279 
- Switches from prefs to asyncStore.
- because asyncStore is _async_ we need to fetch the initial state before creating the store and pass it in.
unit and integration tests should pass
=> [breakpoints] Save breakpoints to asyncStorage

assets/panel/prefs.js, flow-typed/npm/@babel/template_vx.x.x.js, package.json, src/actions/expressions.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-console-async.js, src/utils/prefs.js, src/workers/parser/mapAwaitExpression.js, src/workers/parser/mapBindings.js, src/workers/parser/mapExpression.js, src/workers/parser/mapOriginalExpression.js, src/workers/parser/tests/mapExpression.spec.js, src/workers/parser/utils/ast.js, src/workers/parser/utils/helpers.js, yarn.lock
CC https://bugzilla.mozilla.org/show_bug.cgi?id=1410820
- Adds client-side top-level await support. 
- returns the pending promise and logs the return value when it is complete
- relies on the fact that babel fails to parse top-level awaits, and attempts to wrap top level awaits in an async iife. We probably could do better than that :)
✅  `await sleep(10)` => `10`
✅   `let x = await sleep(10); x + x` => `20`
=> Add top-level await support

src/utils/source.js, src/utils/tests/source.spec.js
Fixes Issue: #6733
* Add logic that hides the extended file information when both files are same just pretty-printed
Add the test cases for the following:
* duplicate file path,  different name
* duplicate file path, same name (pretty print)
=> Better format duplicate filename text

src/actions/ast.js, src/actions/pause/commands.js, src/actions/sources/newSources.js, src/actions/sources/prettyPrint.js, src/client/firefox/create.js, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/SourcesTreeItem.js, src/selectors/getRelativeSources.js, src/test/mochitest/browser_dbg-sources-named-eval.js, src/types.js, src/utils/function.js, src/utils/isMinified.js, src/utils/source.js, src/utils/sources-tree/updateTree.js, src/workers/parser/utils/ast.js
Fixes Issue: #<issue number>
Types for JS and WASM Sources
* Add `WASM` and `JS` Types
* Fix issues
* TODO : Fix all issues
=> fix the WASM and JS Sources

assets/panel/debugger.properties, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/SourcesTreeItem.js, src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js, src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
Fixes Issue: #5815
In some refactoring, I think we lost the addon icon in the sources tree.
I left the following in `debugger.properties`:
```
extensionsText=Extensions
```
... in the case that we use this text again.  Seems reasonable
=> Fix 5815 - Show addon icon for addon path

src/actions/index.js, src/actions/sources/index.js, src/actions/sources/select.js, src/actions/tabs.js, src/reducers/index.js, src/reducers/sources.js, src/reducers/tabs.js, src/reducers/types.js, src/selectors/index.js, src/utils/quick-open.js
Fixes #3279.  This is to finish the work started in PR #5672 as discussed in #6711.
Tasks:
=> [Tabs] Move actions and reducer for the editor tabs into their own files

src/components/Editor/Tab.js
Fixes Issue: #6781
The Tab component outer div has an onMouseUp handler that seems to fire before the close button onClick handler and sets this tab active before the CloseButton onClick handler closes the tab.  By setting the Tab div handler to onClick as well, the CloseButton handler fires first and prevents the Tab `handleTabClick` handler from firing as well.  Is this something that a mochi test will work to test for?  If so, I'll try to write one for it.
=> [Tabs] change Tab click handler event from onMouseUp to onClick

src/reducers/sources.js, src/reducers/tabs.js
Helps Issue: #6774 
* memoizes sourceByUrl queries so that they're cheaper to do
* this will help us show ` [sm]` in the source tree, which requires doing this check quickly
* it helps us clean up this [profile][p] quite a bit
[p]: https://perf-html.io/public/6bd671a68bd75516a407a408eeffd982cd38984b/flame-graph/?hiddenThreads=1-2-3-4-5-6-7-8&implementation=js&range=0.9551_1.0781&thread=0&threadOrder=0-2-3-4-5-6-7-8-1&v=3
=> [sources] Cache sources by url

src/components/Editor/Tab.js
I just found that I broke closing tabs on middle click in 6a3f5ae. 😱 
Here is one fix for it.  Is this something that can be tested with a mochi test?
=> Move tab middle-click close hander to onMouseUp event

src/utils/pause/frames/getLibraryFromUrl.js, src/utils/pause/frames/tests/getLibraryFromUrl.spec.js, src/utils/source.js, src/utils/sources-tree/getURL.js, src/utils/tests/source.spec.js
Fixes Issue: #6793
This PR fixes the detection problem of different Vue build types.
It also trims any query parts of file extensions in order to show the correct file logo. [Vue adds a hash value to the filename](https://forum.vuejs.org/t/cant-get-sourcemaps-to-work-properly-please-help/22246/2) and because of that the file logo couldn't be found.
=> Fix detection of different VueJS builds

src/utils/tests/result-list.spec.js
Related https://github.com/devtools-html/debugger.html/issues/5100 
Trying to get familiar with the code base here. Let me know if I missed something and this is already tested somewhere pls.
Two of the tests below don't make much sense because I'm not sure how to set `clientHeight` so we can assert properly on `scrollTop` for the chrome scenario. Should it provide a complete mock object to the test instead?
Also for the [delayed branch](https://github.com/devtools-html/debugger.html/blob/3a530479dd10ed05a0394e714153dcb30a8bce03/src/utils/result-list.js#L23) would assert on `setTimeout`being called enough?
cheers
=> Introduce utils/result-list spec

src/components/PrimaryPanes/Outline.css, src/components/PrimaryPanes/Sources.css
Corrects visual alignment issue when switching from `Sources` to `Outline` panes.
Fixes Issue: #6804
* Adds `4px` vertical padding to the `Sources` pane content container
* Updates the `10px` vertical padding on `Outlines` pane to be consistent with the `Sources` pane 
Tested visually by switching between `Sources` and `Outline` panes (see animated screenshots).
|Before|After|
|----------|------|
|![before](https://user-images.githubusercontent.com/7773718/44064479-ff47e738-9f19-11e8-83c1-cfb5d67dfbf9.gif)|![after](https://user-images.githubusercontent.com/7773718/44064483-07c53c76-9f1a-11e8-8321-dab1cb0a550b.gif)|
=> Add consistent vertical padding to panes

src/actions/sources/newSources.js, src/actions/tests/pending-breakpoints.spec.js, src/reducers/pending-breakpoints.js
Fixes Issue: #5663
- Adds support for only adding one bp.
- tested it here https://q7mmol9xy9.codesandbox.io/
- blocked on the `[sm]` pr because we need `getSourcesByUrl`
- one jest test
- added a breakpoint in `index.js [sm]` on line 12 and refreshed. when it worked there was one bp, when it failed there were 2, the second was on line 11
=> [sources] add support for only adding one bp per source

package.json
When running `yarn install` the package.json gets auto-formatted for me, and this is the result.
I'm on yarn 1.9.4. Tried with Node 8.11.3 and 10.6.0.
Not sure if we actually want these changes or not, and if we don't that's cool.
=> Auto-format package.json

src/test/mochitest/browser_dbg-pause-points.js, src/workers/parser/pausePoints.js, src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
Fixes Issue: #6761 
Simplifies pause points logic so that we always pause at assignments and returns
unit tests / mochitests
> when i tested it previously lines 61,62, and 63 were all skipped
=> [pausepoints] pause at assignments and returns

packages/devtools-reps/src/object-inspector/stubs/grip.js, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/expand.js.snap, packages/devtools-reps/src/object-inspector/tests/component/expand.js, packages/devtools-reps/src/object-inspector/utils/node.js
When we have a getter value, it is stored in a different property
in the node. Which means that if the getter returns a longString,
we couldn't assign the fullText to the non-getter property (and as
a result, an exception was thrown).
This is not a common bug since we only automatically evaluate safe
getters, i.e. native property getters that we know are side-effect
free.
A test is added to make sure we handle this as expected.
=> Fix expanding longString when the property is a getter.

src/components/shared/ResultList.js, src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
I spotted this issue and it bugged me.  If the subtitle and title match, there's no point in showing a subtitle:
=> Don't repeat filename in subtitle for result list

src/test/mochitest/browser_dbg-console-async.js
* change preference name in call to match the real preference's name which fixes test in beta simulations
=> Bug 1482401 - Fix preference name devtools.debugger.features.map-await-expression in test

src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Expressions.css, src/components/WelcomeBox.css
Fixes Issue: #6670
* Add renamed css properties `offset-*` to `inset-*` following https://bugzilla.mozilla.org/show_bug.cgi?id=1464782
1.  Test at your localhost:8000 that the close button still displays properly
2.  Open Firefox, open Tools -> Web Developer -> Browser Toolbox, and use the inspector to manually set the same CSS change and confirm the [x] shows up in the right spot! :)
=> Fix position of watch expression "delete" button

packages/devtools-components/src/tree.css
Fixes Issue: #6686 
* removed unneeded css block for `.tree` with the declaration `overflow: auto`
1. At your localhost:8000 debugging, for example:`https://30926wj5o5.codesandbox.io/`.
2. Open debugger tool > Sources > `index.js`
2. Add a breakpoint at line 34
3. Reload `https://30926wj5o5.codesandbox.io/`
4. When the execution is halted at line 34 hover over `myLongObject` variable
3. Notice how after the fix the horizontal scrollbar is visible at any time independently from  the vertical scroll position.
=> Fix preview popup horizontal scrollbar

src/actions/ast.js, src/actions/sources/select.js, src/actions/sources/tests/select.spec.js, src/actions/tabs.js, src/actions/tests/tabs.spec.js, src/actions/types/SourceAction.js, src/actions/types/index.js, src/components/shared/SourceIcon.js, src/reducers/tabs.js, src/test/mochitest/browser_dbg-tabs.js, src/test/mochitest/helpers.js, src/utils/tabs.js
Fixes Issue: #6725 
* Change tabs structure from [url] to [{url, framework}]
* Cache the framework 
Test it:
- Go to [ahfarmer.github.io](https://ahfarmer.github.io/calculator/)
- Open a few components
=> [Tabs/Framework] Cache tabs icon 

packages/devtools-components/src/tree.css, packages/devtools-components/src/tree.js, packages/devtools-reps/src/launchpad/components/Result.js
According to James Teh in https://bugzilla.mozilla.org/show_bug.cgi?id=1424159#c8 , the check we were doing in the Tree was preventing interacting with them in a given mode of screenreaders.
The original check was made to make sure we only automatically select the first node of a Tree if the focus was not set in the Tree. We did that by relying on `explicitOriginalTarget`.
But we already bail out if there's already a `focused` prop. So it makes sense to simply remove the extra check. According to my manual testing in the Reps test app (and in the console with the reps bundle updated), it seems to work fine. 
I pushed to [TRY](https://treeherder.mozilla.org/#/jobs?repo=try&revision=69647b885a2dfa7eec3fa4ee0b7e04201457ad9b) to see if everything is okay
=> Remove unecessary check when focusing Tree

src/reducers/sources.js
Issue: #6829 
* speeds up updateSource by a lot. 
https://perfht.ml/2OUOQKH
https://perfht.ml/2OVCMsz
now the time spent is almost entirely in the UI which is the bigger blips next to the longer bars in the old perf graph
=> [sources] improve updateSource performance

src/utils/prefs.js
Since the tabs pref went from an array of strings to an array of objects, we should bump prefs.  The change doesn't appear to be causing an error but this seems like the right thing to do.
=> Bump prefs for new tabs format

src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/tests/SourcesTree.spec.js
Fixes #6829 
- it is possible for two sources with the same URL to be added to the tree 
- this updates the tree path so that it is always unique
- we should have a unit test for this case
=> [sources] update tree-node path so it is always unique

src/actions/expressions.js, src/reducers/pause.js, src/test/mochitest/browser_dbg-preview-source-maps.js
Fixes Issue: #6868
- prevents mapping expressions when there arent mappings
- this fixes a slow case in the debugger when the debugger tries to map an expression while the parser worker is buy calculating original and generated scopes
- next steps - in the future it would be better to show a "loading" indicator when hovering and wait until we have the mappings to calculate the mapped expression. This is a significant amount of work that I think we can prioritize later.
1. debug the debugger or another [app] w/ sourcemaps 
2. add a breakpoint in an original file
3. pause and quickly hover or use the console
[app]: https://firefox-debugger-example-react-js.glitch.me/
=> Preview - speed up the previews

src/actions/sources/select.js
Fixes Issue: #6348
Made minor changes to selectLocation action
* add check if activeSearch is truthy before trying to close it
* add check if a source is already in the tabs state before adding it
=> [sources] don't displatch ADD_TAB and TOGGLE_ACTIVE_SEARCH when not needed

packages/devtools-components/src/tree.js
The check that was made there prevented the first
item of the Tree to be selected if the click happened
inside it. Without this check, the first item is automatically
selected and scrolled to, which is causing some weirdness in
the console (probably in the debugger as well).
The fix was made in mozilla-central directly in the reps bundle
as well.
=> Roll back Tree component onFocus change.

package.json
Update to latest launchpad that simply removes an unused css variable. Will need to update the browser_parsable_css test when releasing to mozilla-central.
=> Bump launchpad to 0.0.132

src/components/shared/SearchInput.css
Fixes Issue: #6858
* style search-field input so in shrinks more giving more space for nav buttons in a narrow window
* style search nav buttons to have same width as breakpoint buttons
* for search summary, add 5px left padding and change right padding from 10px to 5px
With this change the main panel width can be made a good deal smaller before the buttons get clipped.  Then I think we might be OK not having to move them to the modifiers bar.  
**Before**
**After**
=> [search] collapse search input box to make room for buttons

src/components/SecondaryPanes/Expressions.css, src/components/shared/SearchInput.css
Fixes #6901
Removes focus rings for input bars
=> [Search] remove focus ring for search inputs

CODEOWNERS
The main reason I added myself to the properties file codeowners was to keep an eye on localization change before accepting new releases to m-c. 
Since I no longer do much m-c release review, I don't need to notifications anymore, and I think it can be a little overwhelming for contributors to see 2 reviewers automatically popping up when they touch the localization file :)
=> Remove jdescottes from properties file codeowners

packages/devtools-source-map/src/source-map.js, packages/devtools-source-map/src/utils/convertToJSON.js, packages/devtools-source-map/src/utils/fetchSourceMap.js, packages/devtools-source-map/src/utils/getOriginalStackFrames.js, packages/devtools-source-map/src/utils/wasmXScopes.js, packages/devtools-source-map/src/worker.js
(Continuation of #6870 and #6795)
Using [dwarf-to-json](https://github.com/yurydelendik/dwarf-to-json), it materializes additional [x-scopes](https://gist.github.com/yurydelendik/802f36983d50cedb05f984d784dc5159) field in the source maps JSON.
Sample debuggee demo at https://yurydelendik.github.io/old-man-sandbox/rust-wasm-hey/hey.dbg.html (set breakpoint at .../libcore/fmt/mod.rs:381)
/cc @fitzgen @jimblandy
=> [WASM] Provides information about inlined functions and their original function names

src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-sources-arrow-keys.js, src/test/mochitest/browser_dbg-sources.js, src/test/mochitest/helpers.js
Fixes Issue: #6700 
* Adds keyboard integrations tests for source-tree
- I wasn't sure if it was okay to add a second `add_task` inside one mochitest file. It looks like it has been done before, but I am not sure if it's not recommended.
- I had some issues knowing _what to wait for_ after triggering a `pressKey`. I made a function that waits for a specific node to gain focus. This does work, but if that test is going to fail and the node won't gain focus, the test will just timeout not giving the best error message. Any idea what I should be waiting for instead?
=> [SourceTree] Keyboard arrow behaviour integration tests

docs/mochitests.md, docs/most-common-issues.md
Fixes Issue: #6928 
* Change instances of `yarn copy-assets` to `yarn copy`
* Change instances of `yarn copy-assets-watch` to `yarn watch`
=> Update copy-assets and copy-assets-watch to copy and watch

src/components/ProjectSearch.js, src/components/test/__snapshots__/ProjectSearch.spec.js.snap
Fixes Issue: #6953 
* Remove `setExpanded` from `ProjectSearch` `renderFile` method
* the `Tree` component handles expanding and collapsing on its own
=> Make search results files collapse / expand

packages/devtools-utils/src/worker-utils.js
We might start the worker from places where we don't
have a `window` reference, which we would make the
function fail when creating the worker.
In this patch we allow to pass a window object to the
function which is then used to create the worker.
=> Allow to pass a window in WorkerDispatcher.start.

.github/PULL_REQUEST_TEMPLATE
If you want github to [automatically close](https://help.github.com/articles/closing-issues-using-keywords/) the associated issue when you merge a PR this change should do it.  If you prefer to keep it the way it is now please just go ahead and close this PR.
=> enable github autoclose issues on PR merging

packages/devtools-reps/src/reps/accessible.js
Fixes #6932
* Fixed misnamed separator property and renamed to separatorText.
=> Fix misnamed property in accessible rep (#6932)

.github/CONTRIBUTING.md
Updates the Contributing.md doc where there is a link to view availabe issues.  The current link shows issues with the [available label](https://github.com/devtools-html/debugger.html/labels/available).  It doesn't seem like this label is used anymore so I think querying for the label ['help wanted' that doesn't have the 'in progress' label](https://github.com/devtools-html/debugger.html/issues?q=is:issue+is:open+label:%22help+wanted%22+-label:%22in+progress%22) gives a better result.
=> [Docs] update contributing.md available issues link

packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/tests/string-with-url.js
Fixes #6843
- Removed logic that cuts non-URL text, providing inconsistent results.
- Used existing method `getCroppedString` to ensure that consistent results are displayed back as a header value.
Steps to reproduce in this [link](https://bugzilla.mozilla.org/show_bug.cgi?id=1483891#c4).
Before click:
After click:
=> [reps] getLinkifiedElements doesn't properly linkify strings #6843

src/components/SecondaryPanes/CommandBar.css
Fixes #6978
* Updated mask-size for the help (shortcuts) icon used in bottom toolbar. The icon was updated to Photon styling in mc and the size needs to be set to ```contain```
=> Update mask-size for the new photon style help icon, fixes #6978.

assets/panel/debugger.properties, package.json, packages/devtools-reps/package.json, src/components/Editor/EditorMenu.js, src/components/Editor/GutterMenu.js, src/components/Editor/index.js, yarn.lock
Fixes #3673 
Associated PR: https://github.com/devtools-html/devtools-core/pull/1087
* Add context menu accelerator for existing shortcuts
* Also add a shortcut for watch expressions
* Update string for copy source to be more accurate
- Manual testing
=> feat: Set accelerator text for context menu items

src/actions/expressions.js, src/actions/preview.js, src/test/mochitest/browser_dbg-sourcemapped-preview.js, src/workers/parser/mapAwaitExpression.js, src/workers/parser/mapBindings.js, src/workers/parser/mapExpression.js, src/workers/parser/mapOriginalExpression.js, src/workers/parser/tests/mapExpression.spec.js
In `mapExpression`, we now return an object instead of the mapped expression directly.
The object contains the mapped expression, as well as a `mapped` object containing
all the mapping the happened on the expression or not (await, originalExpression, bindings).
We take this as an opprtunity to clean-up `mapAwaitExpression`:
- the default exported function is renamed to `mapTopLevelAwait` to match other mapping functions
- we add a `.catch` in which we `console.error` to catch any promise rejection or Exception.
=> Return what was mapped in mapExpression.

src/test/mochitest/browser_dbg-quick-open.js
Corresponds to https://bugzilla.mozilla.org/show_bug.cgi?id=1438778
* in browser_dbg-quick-open.js, stop using search results with 2 files before selecting file, to avoid failure from non-deterministic items order
* reorder tests for clarity
This is a fix for testcase
=> Use results with single file in browser_dbg-quick-open.js

src/components/SecondaryPanes/CommandBar.js, src/components/SecondaryPanes/tests/CommandBar.spec.js
Fixes #6963
Update the `CommandBar.js` component so the handler for the F8 key press will call either `props.breakOnNext` or `props.resume` depending on the state of `props.isPaused`.  Previously two F8 event handlers were created.  One called `props.resume` always regardless of paused state.  The other one called a non-existant `props.pause` function.
=> Use F8 for both pause and breakOnNext commands

src/components/Editor/Tabs.css, src/components/PrimaryPanes/Sources.css, src/components/SecondaryPanes/CommandBar.css
Fixes #6803
The alternative approach suggested in the issue where the file tab design does not change. Original approach: https://github.com/devtools-html/debugger.html/pull/7006
* Changed height of Debugger's tab bar to 28px excluding borders
* Adjusted file tab labels to align
-Tested hovering action
-Tested multiple tabs open
=> Alternative UX changes for issue 6803

src/utils/quick-open.js
When we changed the tabs list from an array of URLS to an array of objects we stopped showing the tab icon in quick open.
Write a new mochitest
=> [Quick Open] Fix tabs icon in modal

src/actions/expressions.js, src/actions/preview.js
Now that Bug 1491354 landed, the console will expect
`getMappedExpression` function to return the same object
than parser's `mapExpression` function, or null if the
expression doesn't need any mapping.
=> In getMappedExpression, return the result of parser.mapExpression.

src/selectors/visibleBreakpoints.js, src/utils/memoize.js, src/utils/tests/memoize.spec.js
Fixes #6938
* We can now use Memoize to cache upto n arguments serially
=> Tweak memoize to use n keys

src/components/Editor/index.js
when we introduced some of the codemirror operations we began to see the breakpoint sizes update  late when we switched files. This fixes that by removing one of the operation groups.
=> [Editor] continue resizing breakpoints

src/components/PrimaryPanes/SourcesTreeItem.js, src/reducers/sources.js
Fixes #7026
I was going to give this issue to @ZhangYue-vhyt but, in reviewing the code, I realized I wasn't very concise with my original `isOriginal` pull request.
`getSourcesByURL` should return all sources with a given URL; `isOriginal` shouldn't be in play with that function.
=> Fix 7026 - Only show (mapped) when duplicate file names

src/components/SecondaryPanes/Frames/Frames.css
Fixes [#17 from the UX repository](https://github.com/devtools-html/ux/issues/17)
This is a small fix to make the reading easier at the Call Stack on the right of the Debugger window.
* CSS: change font-weight from lighter to normal. Selector is .frames .location (important to know, in case it affects other panels)
Location: _src/components/SecondaryPanes/Frames/Frames.css_
If you want to check the visibility, please open a page with a working Javascript file.
The change is very subtle, so there are a couple of screenshots below.
Before fix:
After fix:
=> [Call Stack] Text visibility fix

README.md
We haven't promoted the thursday call in awhile. Lets drop it and instead do more impromptu calls when folks are free.
=> Update community call

src/components/SecondaryPanes/Frames/Frames.css
Unfortunately we need to revert https://github.com/devtools-html/debugger.html/pull/7014 for now.
There's an side effect of the first PR that cause a formatting issue:
To reproduce:
1.  Open the following site in the debugger:  https://firefox-dev.tools/debugger-examples/examples/todomvc/
2.  Open backbone.js, add breakpoint to lines 1590, 1593
3.  Refresh todomvc
You'll see the top stack item looking huge.  @danny6514 Care to have another try?
=> Revert call stack formatting change

jest-test.config.js
Add ` modulePathIgnorePatterns: ["src/test/mochitest", "firefox"]` to jest config.  
This fixes the following errors I am getting when running jest.
```
jest-haste-map: @providesModule naming collision:
Duplicate module name: sorted-es6
Paths: debugger.html/firefox/devtools/client/debugger/new/test/mochitest/examples/sourcemaps3/package.json collides with debugger.html/src/test/mochitest/examples/sourcemaps3/package.json
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
Duplicate module name: sourcemaps-reload
Paths: debugger.html/firefox/devtools/client/debugger/new/test/mochitest/examples/sourcemaps-reload/package.json collides with …
```
=> Ignore mochi test and firefox build directories on jest test runs

src/utils/prefs.js, src/workers/parser/getSymbols.js, src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap, src/workers/parser/tests/fixtures/callExpressions.js
=> extend callExpressions to include a.b().c()

src/workers/search/get-matches.js, src/workers/search/tests/get-matches.spec.js
Fixes #6896
* Add check in the search worker regex search loop to catch if the regex index is not being updated
=> prevent a regex infinite loop in the search worker

packages/devtools-utils/src/worker-utils.js, src/actions/ast.js, src/actions/tests/ast.spec.js, src/components/SecondaryPanes/Frames/Frame.js, src/reducers/ast.js, src/workers/parser/frameworks.js, src/workers/parser/index.js, src/workers/parser/mapExpression.js, src/workers/parser/pausePoints.js, src/workers/parser/steps.js, src/workers/parser/types.js, src/workers/parser/utils/simple-path.js, src/workers/parser/validate.js
Fixes Issue: #<issue number>
I had discussed a couple options for typing the functions. The first, using a generic `Task` type, worked fine for flow typing and was more terse but didn't give useful information to developers (e.g. the flow tooltip in vscode) because it only presented the generic (e.g. `Task<[SourceId], string>`) which required understanding of the generic.
The second option is to document the function signature explicitly (e.g. `(sourceId: SourceId) => Promise<string>`). While more verbose, the type support is identical and provides a better DX so was chosen for this PR.
* Adds types to dispatcher tasks for the parser worker
* Fixes a few related type issues
* Removes `replaceOriginalVariableName` and `getClosestExpression` worker exports which do not appear to be …
=> Add types to parser worker methods

.travis.yml, assets/panel/prefs.js, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/SourcesTreeItem.js, src/reducers/sources.js, src/reducers/tabs.js, src/test/mochitest/helpers.js
- adds a failing webconsole test
- it fails because #6867 changed the definition of getSourceByURL to either look for original or generated sources
we might need to reintroduce an agnostic search. This could look like three separate selectors: `getSourceByUR`, `getOriginalSourceByURL`, `getGeneratedSourceByURL`
=> [sources] add a webconsole sourcemap test

package.json
Fixes issue where the jest tests are breaking while trying to run babel 7
thanks for help @loganfsmyth 
* use specific hash of workerjs
Tests run fine
=> rollback to a specific commit of workerjs that works

src/selectors/test/getCallStackFrames.spec.js, src/utils/pause/frames/getLibraryFromUrl.js, src/utils/pause/frames/tests/getLibraryFromUrl.spec.js
Improve regex pattern for determining whether a particular frame belongs to the React library or not.
Fixes #6792 
* Improve React regex pattern to detect React files correctly. Previously, if the word `react` appeared anywhere in the URL, the debugger will classify it as React library file. Now, the debugger will look for the word `react` in the filename rather than just the path.
Before:
After:
=> Improve regex pattern for determining React library files

src/components/Editor/SearchBar.css, src/components/ProjectSearch.css, src/components/shared/SearchInput.css
Fixes #7017
* Fixed extra pixel of space on right of Find in Files search bar
* Made transparent border the same color as the rest of the bar
=> Fix Find in Files border/spacing

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/Frame.spec.js, src/components/SecondaryPanes/Frames/tests/Frames.spec.js, src/utils/source.js
This props will allow the component to be rendered with the full URL of the frame, instead of just the filename as its currently the case.
This is needed by the webconsole where we do have a lot more space to display information.
=> Add a displayFullUrl prop to the Frame component.

assets/panel/debugger.properties, src/test/mochitest/browser.ini
- Label nit was something @flodolo had pointed out but we missed.
- The condition for a test goes underneath it, so we accidentally added a condition to the xhr breakpoint test and removed it from its desired test.
=> Properly set permissions for testing, label nit

src/components/SecondaryPanes/Frames/index.js
This will allow other panels (e.g. Console, Netmonitor, …) to import it and passing the appropriate props.
For some reasons, this triggered Flow errors (which I fixed)
=> Export non-connected Frames component.

src/utils/pause/frames/displayName.js, src/utils/pause/frames/tests/displayName.spec.js
The maxLength will default to the current length
we use (25), but could be overrided to whatever
the consumer wants. Setting it to null will not
truncate the string at all.
=> Add a maxLength option to formatDisplayName.

packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap, packages/devtools-reps/src/reps/tests/error.js
This will allow us to use the same component
in the console and in reps for example.
If the prop is not passed, it defers to the
current stacktrace rendering.
Fixes #7130
=> Use renderStacktrace prop if provided to render Error rep stacktrace

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/Frames/Group.css, src/components/SecondaryPanes/Frames/Group.js
Fixes #7131 
The Frames component has limited space available,
and it might happen that we need to truncate some
information.
Previouysly, this was done by manually setting a
length limit on the string we were displaying.
This is a bit unfortunate since CSS has some useful
properties we can use to show whatever fits on the
screen.
So now, in Frames, we don't truncate strings anymore,
and, in CSS, we set the text-overflow we want.
Furthermore, we make the Frame element wrap, so when
the panel gets smaller, the location is put on a
new line instead of shrinking (and then shrinks if
it needs to).
In order to have such feature, we needed to have the
location element to not have display: flex. This was
not hard to fix since flex was only used to place an
optional icon after the framework name, …
=> Handle Frame overflow (function and location) in CSS.

src/test/mochitest/browser_dbg-scopes.js
Backport fix from https://bugzilla.mozilla.org/show_bug.cgi?id=1460440
=> Avoid race condition in browser_dbg-scopes test.

src/components/Editor/SearchBar.js
Fixes #7013
* Modifiers on the Find in File search bar no longer need to be clicked twice when the search bar is in focus.
=> Change onClick to onMouse/KeyDown for search bar modifiers

assets/panel/debugger.properties, src/client/firefox/create.js, src/components/shared/PreviewFunction.js, src/components/shared/tests/__snapshots__/PreviewFunction.spec.js.snap, src/utils/pause/frames/displayName.js, src/utils/pause/frames/tests/displayName.spec.js, src/utils/pause/scopes/getScope.js
Anonymous function name was not displayed
at all in the callstack panel, neither it was
in PreviewFunction. In the scopes panel, it was
displayed in another way (`(anonymous)`) than
in the toolbox, where we use `<anonymous>`.
With this patch, we make sure to have anonymous
functions displayed in a consistent way in the debugger,
and matching other panels in the toolbox.
In order to do that, the anonymous item in the properties
file is updated to match the existing ones in mozilla-central.
=> Handle anonymous functions more consistently.

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/Group.js, src/components/shared/PreviewFunction.js, src/utils/pause/frames/displayName.js, src/utils/pause/frames/tests/displayName.spec.js
This was only used from `formatCopyName`, where it
also make sense to get the full function name and
not truncate it.
Tests are modified accordingly.
=> Remove formatDisplayName maxLength option.

package.json, yarn.lock
Fixes #7093
Removes redux-saga from package.json and updates yarn.lock accordingly
=> remove unused redux-saga dependency

assets/panel/debugger.properties, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
Fixes #7199 
* Added item to debugger.properties
* Added tooltip prop to CloseButton in `debugger.html/src/components/SecondaryPanes/Expressions.js`
=> Add tooltip to remove expression

src/components/Editor/Tab.js, src/components/Editor/Tabs.css, src/components/PrimaryPanes/Sources.css
Fixes #7034 
* Added blue border style to the Source/Outline and file tabs
Light theme
Dark theme
=> Change tab interface to have blue borders WIP

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/FrameMenu.js, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/Frame.spec.js, src/components/SecondaryPanes/Frames/tests/Group.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap
This will be used in mozilla-central where we might
want different entries. Until we figure out a nice
way of dealing with this kind of usage, let's disable
the context menu to not throw exceptions.
=> Allow to disable context menu in Frames.

src/actions/file-search.js, src/utils/editor/source-documents.js, src/utils/source.js, src/utils/tests/wasm.spec.js, src/utils/wasm.js
Fixes #6570 
* Change `getTextAtPosition` to consider wasm sources
- Add a breakpoint in wasm file
We can do it two ways, one is we can directly store the parsed text in the `source` but the downside with this is that the text will only be needed when user opens the wasm file. So the whole parsing will be a waste of time.
Currently, we delay the conversion of binary to text till the user opens the wasm file.
=> show wasm breakpoints in panel

src/components/Editor/Tab.js, src/components/Editor/Tabs.css
Enhances #7034
* Before, I used an empty `<span>` tag to create the file tab borders. I'm replacing this with the `::before` pseudo-element.
=> Replace file tab span border with ::before

src/components/SecondaryPanes/XHRBreakpoints.css
Showing the text label hints to the user that double-clicking allows them to change the text.
=> Change XHR breakpoint label cursor to text to make editing intuitive

src/components/SecondaryPanes/XHRBreakpoints.js
Fixes: #7220
Usability ftw!
This mirrors the behavior of the expressions input.  
To test, click the "+" in the header and you should see the input box highlighted.  Double-clicking an existing XHR breakpoint should do the same.
=> Show input focus styles for XHR breakpoints

src/components/SecondaryPanes/XHRBreakpoints.js, src/reducers/breakpoints.js, src/test/mochitest/browser_dbg-xhr-breakpoints.js
References:  #7194 
This ensures text-based XHR breakpoints are checked before choosing not to display the XHR breakpoint input element.
=> Always display the XHR breakpoint input if no explicit XHR breakpoints

src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/Frames/WhyPaused.css, src/components/SecondaryPanes/Frames/WhyPaused.js, src/components/test/__snapshots__/WhyPaused.spec.js.snap
Fixes #7136
In the Call Stack ui, the `<li>` for each stack frame are 28.5667px high.  I changed the height for the "paused on breakpoint" text from 35px to 28.5667  and changed the "expand rows" button height from 47px to 28.5667 so everything is uniform and about 25px of space is saved.
Before and After:
=> [CallStack] Adjust height for WhyPaused and ExpandRows

assets/panel/prefs.js, src/components/Editor/CallSites.js, src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap, src/test/mochitest/helpers.js, src/utils/prefs.js
* Pressing Option/Alt only shows column breakpoints on lines that have a breakpoint already set.
=> Show column breakpoints when line breakpoint is set, remove Alt/Option key dependency

package.json
Reverts devtools-html/debugger.html#7243
This triggers jest issues I didn't get locally and I don't want to prioritize this right now, so I'd rather just revert.
=> Revert "Update eslint-plugin-jest to the latest version 🚀"

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/tests/Frame.spec.js, src/components/SecondaryPanes/Frames/tests/Frames.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.spec.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap, src/components/shared/Badge.js, src/components/shared/tests/__snapshots__/Badge.spec.js.snap
This will allow easier styling for consumers outside
of the debugger, as well as handling user copy easier.
Tests are modified accordingly.
I checked any visual regression that might occurred but found none
=> Frames component markup changes.

src/actions/breakpoints/index.js, src/actions/breakpoints/remapLocations.js, src/actions/breakpoints/tests/breakpoints.spec.js, src/actions/breakpoints/tests/syncing.spec.js, src/actions/breakpoints/tests/toggleBreakpointsAtLine.spec.js, src/actions/tests/pending-breakpoints.spec.js, src/components/Editor/Breakpoints.js, src/components/Editor/CallSites.js, src/components/Editor/tests/Breakpoints.spec.js, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js, src/components/SecondaryPanes/index.js, src/reducers/breakpoints.js, src/reducers/tests/breakpoints.spec.js, src/reducers/types.js, src/selectors/breakpointAtLocation.js, src/selectors/breakpointSources.js, src/selectors/breakpoints.js, src/selectors/visibleBreakpoints.js, src/test/mochitest/browser_dbg-breakpoints-actions.js, src/test/mochitest/browser_dbg-breakpoints.js, src/test/mochitest/browser_dbg-editor-gutter.js, src/test/mochitest/browser_dbg-reload.js, src/test/mochitest/browser_dbg-sourcemaps-reload.js, src/test/mochitest/browser_dbg-sourcemaps-reloading.js, src/test/mochitest/browser_dbg-sourcemaps.js, src/test/mochitest/browser_dbg-sourcemaps2.js, src/test/mochitest/browser_dbg-sourcemaps3.js, src/test/mochitest/helpers.js, src/types.js
Fixes #7202
Updates breakpoint reducer to not use immutable.js wrappers.  Also updates anything that uses the reducer and selectors to work with the updated data structures.
=> [Breakponts] remove immutable.js wrappers

src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/tests/Frame.spec.js, src/components/SecondaryPanes/Frames/tests/Frames.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.spec.js.snap
This does not modify the layout of the component,
but includes those chars in the clipboard when
the user copy text.
Needed for console tests to pass.
=> Add tab and new line character in Frame component;

.travis.yml, assets/images/command-chevron.svg, assets/images/help.svg, assets/panel/moz.build, bin/copy-assets.js, packages/devtools-components/postcss.config.js, packages/devtools-reps/postcss.config.js, packages/devtools-splitter/src/SplitBox.css, postcss.config.js, src/components/Editor/Tabs.css, src/components/SecondaryPanes/CommandBar.css, src/test/mochitest/browser.ini
- this updates yarn copy so that the next release uses the new images format
- `v=2` was a silly hack so that 2 SVGs could be in debugge/new/images and devtools/client/themes even though they are the same
- `updateManifest` will copy the manifest over so that we don't get crazy bundle changes when we run `yarn copy`
=> Update yarn-copy so that assets are accurately created

src/reducers/breakpoints.js, src/reducers/tests/breakpoints.spec.js
A simplification of getBreakpointsForSource based on [this comment](https://github.com/devtools-html/debugger.html/pull/7226#issuecomment-437555166).  I made it so it no longer re-creates new breakpoint objects and also used getBreakpointsList instead of getBreakpointsMap so it can just use Array.filter to get the results.
=> Simplify the getBreakpointsForSource selector function

src/components/Editor/Tab.js, src/components/PrimaryPanes/SourcesTreeItem.js, src/components/SecondaryPanes/Breakpoints/BreakpointHeading.js, src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Breakpoints/index.js, src/reducers/sources.js, src/test/mochitest/browser_dbg-sources-querystring.js, src/utils/source.js, src/utils/tests/source.spec.js
Fixes #7159 
1. Open the test URL https://shimmer-ostrich.glitch.me/
2. Open debugger.
3. Reload the test URL.
4. Open one of the `script.js` source and observe the query string appended to the name in the tab
5. Add a debugger to the `script.js` and observe the query string appended to the name in the breakpoints sidebar
Mochitests
I considered moving `https://github.com/wenincode/debugger.html/blob/7159-source-querystring-logic-tabs-sidebar/src/reducers/sources.js#L434-L449` into a separate `utils` because they aren't actual `reducers` and aren't actually being used by the `reducer` in this file. I _think_ they are in here because the code is a bit tied to the `OuterState` type. I was going to move it and change the types to just be an array of sources to try and decouple it from this …
=> Share querystring logic with tabs & breakpoints sidebar 

src/workers/parser/mapAwaitExpression.js, src/workers/parser/mapBindings.js, src/workers/parser/mapOriginalExpression.js, src/workers/parser/tests/mapBindings.spec.js, src/workers/parser/tests/mapExpression.spec.js, src/workers/parser/utils/ast.js
Fixes #7222
* Added support for simple top-level destructuring assignments - ~still working on the nested destructuring with default values~ (already implemented). The change affects all cases, not just the ones with await statements.
* Built an IIFE with `@babel/types` in mapAwaitExpression.js.
Just by writing tests. No specific test plan.
=> Support destructuring assignments

src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js, src/components/SecondaryPanes/Breakpoints/tests/BreakpointsContextMenu.spec.js, src/selectors/breakpointSources.js, src/test/mochitest/browser_dbg-breakpoints-actions.js
Fixes #7268 
* update BreakpointContextMenu.js logic that finds other breakpoints.  A formatted breakpoint object was being compared to a breakpoint object using object equality which was always returning that they were not the same breakpoint.  I changed it to compare using breakpoint id.
* added the breakpoint id property to FormattedBreakpoint objects
=> [Breakpoints] fix breakpoint context menu logic

bin/port.js
Now that we have original sources in the debugger, it should be easier to backport changes in m-c for a given sha back to github.
This script looks at a commit, filters out the files outside of the debugger, and copies the others back to github. 
I'm sure that this can be improved:
1. we will now copy any changes including dist changes
2. we will miss changes from reps...
3. we could also write a commit message if we want
4. this assumes you're using hg... we can generalize this as well...
=> Add a backport script

.gitignore
We've been getting loads of PRs with errant changes to this file, so IMO we should ignore it and then force-update it when we do a release.
=> Ignore module manifest unless forced

assets/panel/debugger.properties, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/tests/Group.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap
Fixes #7209.
This adds a title to the group component
that indicates it can be expanded/collapsed.
Two location entries are added to handle both
collapsed and expanded state.
=> Add a title to Group component description element.

packages/devtools-source-map/package.json, packages/devtools-source-map/src/tests/source-map.js, yarn.lock
Upgrade to `source-map@0.8.0-beta.0` with https://github.com/mozilla/source-map/pull/371
=> Upgrade to source-map@0.8.0-beta.0 with WHATWG URL support.

src/utils/pause/frames/getLibraryFromUrl.js, src/utils/pause/frames/tests/getLibraryFromUrl.spec.js
Some file used by libraries can't get really be identified
as part of the framework since their name can be quite
common (like zone.js).
In those case, it would be nice to check the whole callstack
to find if there's at least another frame matching a library.
(for zone.js, we should identify as Angular only if there's
another frame identified as an Angular frame).
---
See [Bug 1507327 🐛](https://bugzilla.mozilla.org/show_bug.cgi?id=1507327)
=> Add context check in getLibraryFromUrl.

src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/test/mochitest/browser_dbg-breakpoints-cond.js
Fixes #7272 
In BreakpointContextMenu the `setBreakpointCondition` prop is undefined.  I added it to `mapStateToProps` in Breakpoint which passes it to BreakpointContextMenu.  I also added a mochi test.
=> [WIP] Add missing 'setBreakpointCondition' action to Breakpoint props

src/actions/ast.js, src/actions/utils/symbols.js, src/components/Editor/CallSites.js, src/workers/parser/getSymbols.js
Fixes #7248
This is far enough along that I need eyes on it @loganfsmyth @jasonLaster ; ignore the flow errors.
I used @jasonLaster's `hasConflictingGeneratedPosition` suggestion but I'd like more scrutiny on that.
=> Prevent duplicated generated locations from displaying in call sites

packages/devtools-reps/src/object-inspector/component.js, packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/getter-setter.js.snap, packages/devtools-reps/src/object-inspector/tests/component/getter-setter.js, packages/devtools-reps/src/object-inspector/tests/utils/get-children.js, packages/devtools-reps/src/object-inspector/tests/utils/make-node-for-properties.js, packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-indexed-properties.js, packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-non-indexed-properties.js, packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-prototype.js, packages/devtools-reps/src/object-inspector/tests/utils/should-load-item-symbols.js, packages/devtools-reps/src/object-inspector/utils/node.js, src/test/mochitest/browser_dbg-expressions-error.js, src/test/mochitest/browser_dbg-expressions.js
Fixes #7288.
---
i'm not super happy with the tests changes, but, maybe we can revamp them a bit when doing #6140 (which I will as soon as this is merged)
=>  Display <get> and <set> node as sibling as the property with accessors.

src/utils/pause/frames/annotateFrames.js, src/utils/pause/frames/getLibraryFromUrl.js, src/utils/pause/frames/tests/annotateFrames.spec.js, src/utils/pause/frames/tests/getLibraryFromUrl.spec.js
This patch also fixes a mistake in `getLibraryFromUrl`,
which wasn't working at all, with a poorly written test.
=> Pass callstack to getLibraryFromUrl in annotateFrames.

src/actions/sources/tests/querystrings.spec.js, src/reducers/sources.js
I noticed that `getSourcesUrlsInSources` is returning all sources and not a matching source, so querystrings are showing up in the tree when they don't need to.
This PR ensures that querystrings only display when they need to.
=> Fix getSourcesUrlsInSources so it returns only matching URLs

src/components/App.js, src/components/Editor/Tabs.js
Fixes #7016
* File tabs now get added/removed from the dropdown when the editor pane is resized
=> Fixing file tabs disappearing when resizing editor pane

src/components/Editor/CallSites.js, src/utils/editor/index.js
CodeMirror has a really hard time when we inject every marker for a given line if the line is very long:
One idea was to "cut off" column breakpoints after a certain column value (https://github.com/devtools-html/debugger.html/pull/7291), but this may be a better, more flexible solution, as I attempt to accommodate only lines and characters in range of the view port.  It debounces for additional perf win.
This already feels way better than current performance, when there's massive lag when switching between tabs.
=> Show only column breakpoints in viewport

src/actions/sources/newSources.js
In release 103 we had to exclude the source-map upgrade because of flakiness on Windows. It seems to be that we were just uncovering existing flakiness in the existing test, but it varies depending on source-map timing.
=> Ensure that we don't overwrite a loaded source with a loading source to fix flakiness.

src/components/Editor/CallSites.js
I noticed that the breakpoint markers don't display when a source is blackboxed, so nor should their column breakpoint markers.
=> Hide column breakpoints when source is blackboxed

src/components/SecondaryPanes/Breakpoints/index.js, src/utils/breakpoint/index.js, src/utils/breakpoint/tests/index.spec.js
This sorts breakpoints in the right sidebar by: line number, line number length (so `143` is after `62`), and line number.
=> Sort breakpoints by line number, then column number

src/components/SecondaryPanes/Frames/Frames.css
In dark mode, the Angular icon wasn't legible: 
The fix is to remove the case for angular since the icon looks fine in dark mode too.
=> Fix Angular icon in dark mode

src/components/QuickOpenModal.js, src/components/test/QuickOpenModal.spec.js, src/reducers/tabs.js, src/test/mochitest/browser_dbg-sources-querystring.js, src/utils/quick-open.js
Fixes #7217 
- It seems like the search was expecting `tabs` to be an array of strings, but it was really a `TabList`. Updated the `showTopSources` function to convert the tab array into array of source urls for comparison. Now if you have no query in your search, it will show the top sources (open tabs).
- Updated the search source subtitle to be a truncated copy of the sources `relativeUrl` + `query`.
- Updated the search source value to be the sources `relativeUrl` + `query` so that searching by query string works.
Before:
After:
=> Make sources search work with query params

src/test/mochitest/browser_dbg-breakpoints-actions.js, src/test/mochitest/browser_dbg-breakpoints-cond.js, src/test/mochitest/helpers.js
Changes the `selectMenuItem` helper function in mochi tests
- renames it to `selectContextMenuItem` to better describe which menu it is used for
- Instead of selecting a menu item by index, use a css id.  So if the menu items change the test doesn't break.  Also the id makes the test more readable compared to an arbitrary number.
=> [Tests] In mochi tests, use id instead of index to select context menu items

assets/images/column-marker.svg, src/components/Editor/ColumnBreakpoint.js, src/components/Editor/ColumnBreakpoints.css, src/components/Editor/Editor.css
* Break point colors have been changed and a border has been added according to this mockup:
* There's still one issue that I'm not sure how to fix. The --blue-40 variable is not set, so those borders don't actually appear.
=> Restyling breakpoint colors

src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/test/mochitest/browser_dbg-breakpoints.js, src/test/mochitest/helpers.js
This fixes the "enable" and "disable" breakpoint context menu items not working in #7272.  The issue was just the `toggleDissabledBreakpoints` was not being added to the props that eventually get passed along to the BreakpointContextMenu.
=> [breakpoints] fix context menu actions for enable and disable

src/components/Editor/Editor.css
The orange color used wasn't provided by @mcroud but we should address the yucky blue ASAP
=> Fix conditional breakpoint marker stroke

src/components/Editor/Footer.js
Saw this error when opening a new source:
Using proper event.
=> Choose proper event to unregister editor cursor activity event

src/components/SecondaryPanes/XHRBreakpoints.js
This is super minor but, at present, a grey border displays under the "Pause on any URL" once it's been clicked, even if there are no string-based XHR BPs, which is kinda weird.  This is a nice fix.
=> Only show the XHR breakpoint checkbox underline if there are real XHR breakpoints

src/actions/breakpoints/addBreakpoint.js, src/actions/breakpoints/index.js, src/components/Editor/index.js, src/utils/breakpoint/astBreakpointLocation.js
Mostly just smaller fixes to easy review of upcoming work. Typechecking is great and also enforcing the line number seems to just make sense here, since they already early-return when it is falsy anyway.
=> Typecheck addBreakpoint and require breakpoint line numbers in editor gutter fns

assets/dictionary.txt, docs/debugger-html-react-redux-overview.md
Fixed spelling: debbuger.html -> debugger.html.
Added `debbuger.html` string to dictionary.txt so that it can be caught in case the typo occurs again.
=> Fix typo in debugger-html-react-redux-overview.md

src/utils/editor/index.js
I like the idea of just being able to pass the `editor` object around, but in most cases, we only care about `codeMirror`
=> Clean up editor functions

src/components/PrimaryPanes/Sources.css
I looked at the PR where this came in and it's unclear why it was added.  In any event, we've changed the styling the three a lot and I don't believe we need it.
=> Remove 4px gap between the source file name and the primary pane separator

src/components/Editor/Tab.js
The `.size` checks were undefined since we likely moved away from immutables.  Additionally, I dislike show/hide of menu items; simply disabling them keeps menu integrity while only allowing desired functionality.
=> Fix tab context menu item size checks

src/components/Editor/ColumnBreakpoint.js, src/components/Editor/index.js
As it turns out now, column breakpoints don't display in the editor until you scroll, so it's imperative we trigger the scroll handler immediately upon editor setup.
=> Immediately render column breakpoints before scroll

assets/panel/debugger.properties, src/components/Editor/index.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-tabs-keyboard.js, src/test/mochitest/browser_dbg-tabs-without-urls.js, src/test/mochitest/browser_dbg-tabs.js, src/test/mochitest/helpers.js
I try doing this all the time.  Since it's a tabbed interface, it seems to make sense to me that C+W would close a tab.  This doesn't work in launchpad but does in panel.
=> Allow closing source tabs via keyboard

src/components/PrimaryPanes/SourcesTreeItem.js, src/reducers/sources.js, src/test/mochitest/browser_dbg-sources-querystring.js, src/utils/quick-open.js, src/utils/source.js
Fixes #7283 
* `getHasSiblingOfSameName` was returning true if there was ever more than one source returned from `getSourcesUrlsInSources`, which means that it would be true in almost any case. I've updated it to only return true if there is actually a match. I would like to write a unit test for this function, but I was having a hard time understanding how to build the initial `OuterState`
* Update `getSourceQueryString` to return the sources query string, with any `:formatted` stripped from the end. I was going to check `source.isPrettyPrinted` before replacing, but I believe that value is set using pretty much the same regex I was using.
Added the following to the existing query string mochitest:
* Pretty print a source and ensure the tab has the query string still, but no `:formatted` …
=> 7283/fix :formatted showing in tabs/breakpoints sidebar

src/components/Editor/ColumnBreakpoint.js, src/components/Editor/ColumnBreakpoints.css, src/selectors/test/__snapshots__/visibleColumnBreakpoints.spec.js.snap, src/selectors/visibleColumnBreakpoints.js
This lays the groundwork for having column breakpoints show the proper color when they have a condition.  You have to hardcode a condition in the code now to test until https://github.com/devtools-html/debugger.html/pull/7366 is merged.
=> Provide conditional comment styling

src/components/Editor/Footer.css, src/components/Editor/Footer.js, src/components/Editor/tests/__snapshots__/Footer.spec.js.snap
I don't like this informational lock being flush up against commands for the given source.  It looks a lot better on the opposite side.
=> Float cursor position to the right

src/components/SecondaryPanes/Breakpoints/Breakpoints.css
I just noticed that clicking the "Pause on Exception" and "Pause on any xhr" checkboxes quickly results in their text being highlighted, which we don't want.
=> Prevent the breakpoint exception labels from being highlighted

src/components/ShortcutsModal.css
At present you can highlight text in the welcome box modal, which has no value.  Let's prevent that.
=> Avoid text selection in welcome box modal

src/utils/source.js
Fixes #7295
This PR gives pretty and blackbox priority over framework, which makes sense; the variable classes should have that priority.
=> Give pretty print priority over framework

src/components/PrimaryPanes/Outline.js
Clicking on a function in the outline only highlights a given line, which isn't all that useful on a generated/minified line.  Providing the column allows the editor to scroll to the given function's location.
=> Go to column when outline function is clicked

src/components/PrimaryPanes/Outline.css, src/components/PrimaryPanes/OutlineFilter.css
Fixes #7426 
* Changed active dark mode outline-footer button background color to --theme-selection-background
* Changed focused dark mode outline-filter-input border color to --blue-50
=> Dark mode color polish

assets/panel/debugger.properties, src/components/Editor/Footer.js, src/components/Editor/tests/__snapshots__/Footer.spec.js.snap
I can see how the line and column text could be confusing or meaningless to some devs.  This tooltip lets them know what the numbers mean.
=> Provide title text for line and column position

src/components/PrimaryPanes/Sources.css
=> Remove unnecessary tree spacing

src/components/Editor/Breakpoints.js, src/components/SecondaryPanes/Breakpoints/index.js, src/selectors/index.js, src/selectors/visibleBreakpoints.js, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-breakpoints-columns.js, src/test/mochitest/helpers.js, src/utils/breakpoint/index.js, src/utils/breakpoint/tests/index.spec.js
I'm super excited about this.
At present, a breakpoint gutter item is added for every breakpoint (whether column is `undefined` or present), which makes the gutter weird;
1.  Clicking an active column breakpoint marker removes the gutter marker, even though there are more breakpoints active on that column
2.  It's hard to understand which breakpoint that marker's context menu actually represents.
This PR makes the gutter marker represent a single column breakpoint (the first found in the list);  in the future, we'd want to sort the breakpoints first so that the gutter marker represents the first breakpoint *on that line*, instead of the first one found.
=> Make gutter marker or breakpoint represent first breakpoint on line

src/actions/pause/continueToHere.js, src/components/Editor/GutterMenu.js, src/components/Editor/index.js
Provides the same context menu for individual column breakpoint markers as the left line/gutter marker.
=> Repurpose context menu

src/components/Editor/Tab.js, src/utils/editor/index.js
References;  https://github.com/devtools-html/debugger.html/issues/7113
We're using different logic for showing the pretty print option in the tab context menu and the footer.  This PR ensures the same logic is used in both places.
=> Use same logic for pretty print option in footer and tab

src/components/Editor/SearchBar.js, src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
This was brought up by @violasong during our meeting last week.
=> Add separator between search box/navigation and modifiers

src/components/Editor/Tab.js
The disabled property expects a Boolean, and not a function
=> Fix disabled property in tab context menu

assets/panel/panel.js, packages/devtools-reps/src/reps/reps.css, src/actions/toolbox.js, src/actions/types/index.js, src/components/Editor/Preview/Popup.js, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/FrameworkComponent.js, src/components/SecondaryPanes/Scopes.js, src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap, src/test/mochitest/browser.ini, src/test/mochitest/browser_dbg-expressions.js, src/test/mochitest/browser_dbg-inspector-integration.js, src/test/mochitest/helpers.js
Fixes #1427
This provides a method to open DOM elements from within the Object inspector.  This works in all places the OI is used.
=> Provide initial implementation of opening DOM nodes in inspector

packages/devtools-reps/src/object-inspector/components/ObjectInspectorItem.js, packages/devtools-reps/src/object-inspector/utils/node.js
To invoke getter, we were retrieving the parent node
so we could access the getter. This works fine unless
the getter is itself somewhere in the prototype chain
and refers to a property set by an upper level.
This patch changes how we retrieve the context to
invoke the getter in to be the top-most, non-prototype
grip, which should cover this case.
Fixes #7397 
---
Still WIP as I'm trying to find ways I could break it :) 
@Loirooriol , would you have complex test cases I can test against to ensure this is a solid fix? :)
=> Invoke getter in the root object.

packages/devtools-reps/src/reps/attribute.js, packages/devtools-reps/src/reps/element-node.js, packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/stubs/element-node.js, packages/devtools-reps/src/reps/tests/element-node.js
Fixes #6121
This PR crops long attributes and provides a `title` attribute for the attribute itself.
=> Fix 6121 - Crop attributes and provide title after specified length

src/selectors/test/__snapshots__/visibleColumnBreakpoints.spec.js.snap, src/selectors/visibleColumnBreakpoints.js
Simply because a column breakpoint is found doesn't mean it's enabled...
=> Ensure found breakpoint isn't disabled

src/actions/breakpoints/index.js, src/components/SecondaryPanes/XHRBreakpoints.js, src/reducers/breakpoints.js, src/selectors/breakpoints.js, src/utils/bootstrap.js
Fixes #7414
Updates the xhrBreakpoints reducer, selectors and related code not to use immutable.js.
=> [Breakpoints] remove immutable.js from xhrBreakpoint reducer

src/components/App.css
Fixes #7505
* Fixing the unwanted scrollbar when hiding the end panel in debugger
Open the debugger. Close the end panel. And see if a horizontal scrollbar is visible.
=> 🐛 Adding display css styling for splitter to hide uwanted scroll

src/components/PrimaryPanes/Sources.css, src/components/shared/SourceIcon.css
@fvsch Reported the following:
Selected source icons have a white background we don't want.
This PR:
* Removes the white background
* Removes what appears to be a border around the `<img>` icons, which I'm presuming is a windows thing.
=> Remove white background for source icon images in tree, also remove border

src/actions/ast/setPausePoints.js, src/utils/pause/pausePoints.js
Fixes #7485
- backports https://phabricator.services.mozilla.com/D14346
- also adds a second performance fix, which is slightly less impactful
=> [Pause points] speed it up

src/client/firefox/commands.js
The function does not seem to be called anywhere,
and make use of target.form, which we want to remove
in Bug 1513565.
=> Remove unused debuggeeCommand function.

src/components/PrimaryPanes/Sources.css
It's really hard to see, but at present, the horizontal scrollbars for the sources pane starts and ends 4px before the top of the DIV, due to `display: flex` and `padding: 4 0px`.  Moving the spacing to the top of the tree is our best option.
=> Avoid odd scrollbar positioning in sources pane

src/actions/sources/newSources.js, src/actions/sources/tests/newSources.spec.js, src/client/firefox/events.js, src/utils/source-queue.js, src/utils/test-head.js
Fixes #7301 
The fix involves:
- making newSources() not wait for source maps to be loaded
- making loadSourceMaps() add each map to the state asap, instead of doing one big add once all the source maps are loaded
I added two tests that model the current bug and that fail if the two changes above are reverted.
=> Fix debugger hanging with slow loading source maps

src/actions/ast.js, src/actions/tests/preview.spec.js
We were previously fetching symbols again when we were loading because hasSymbols ignores loading.
=> [symbols] stop fetching symbols when loading

src/components/PrimaryPanes/Sources.css, src/components/shared/SourceIcon.css
My last attempt at this wasn't helpful in our current image/border predicament, so we should remove it.  This is much simpler.
=> Simplify the Sources Tree  icon highlight color

src/components/PrimaryPanes/Sources.css
The two recent PRs to improve these icons overlapped and this PR wraps them together, fixing the highlight color for light mode icons.  yay!
=> Update blackbox styles for focused node in tree

src/client/chrome.js, src/client/chrome/commands.js, src/client/chrome/create.js, src/client/chrome/events.js, src/client/chrome/types.js, src/client/index.js
re-adds support for chrome's client, which will let us investigate CDP support and compare firefox and chrome's clients
- show debug line
- support preview
- show scopes (reps is out of scope (pun not intended))
- support watch expressions
=> re-add support chrome

src/components/SecondaryPanes/Expressions.js
Fixes #7464
Fixed expression-input-container so that it clears the input box on blur.
=> Clear the watch expression input box on blur

src/actions/ast/setPausePoints.js, src/actions/types/ASTAction.js, src/client/firefox/commands.js, src/reducers/ast.js, src/reducers/types.js, src/selectors/visiblePausePoints.js, src/utils/ast.js, src/utils/pause/pausePoints.js, src/workers/parser/index.js, src/workers/parser/pausePoints.js, src/workers/parser/tests/pausePoints.spec.js, src/workers/parser/types.js
Fixes #7485
This is a follow up to #7496 where we stop using mapLocations and restrict convertToList to one call site. This should be a nice perf win as well as generally easier to reason about code.
Some considerations:
1. accessing a single pause point will be slower (we might need to store the map if this is too slow)
2. the flow types are a bit funky because of the distinction w/ columns
=> [breakpoints] convert pause points to a list

assets/panel/debugger.properties, src/actions/breakpoints/index.js, src/components/SecondaryPanes/Breakpoints/BreakpointHeading.js, src/components/SecondaryPanes/Breakpoints/BreakpointHeadingsContextMenu.js
Fixes #7474 
* Created another `PureComponent` similar to `BreakpointsContextMenu.js` to show the context menu with items.
* Create `{enable,disable,remove}BreakpointsInSource` as Redux actions in `breakpoints`, using the already available `getBreakpointsForSource` function
* Connect them to `BreakpointHeading.js` and pass them through into the new `PureComponent`, to be called on `click`
=> Add context menu to breakpoint headings #7474

src/components/ProjectSearch.css
Fixes #7558 
* Update file icon in Search Results from grey to white when a search result is selected
1. `yarn start`
2. Visit `localhost:8000` and open Firefox or Chrome
3. Select a sample project, and then press `cmd + shift + f` to search
4. Select one of the files (the file icon is now visible)
=> Improve File Icon Visibility in Search Results On File Selection

assets/panel/debugger.properties, src/components/SecondaryPanes/CommandBar.js
Fixes #7360 
*  Replaced "Skip all pausing" with "Deactivate breakpoints" in assets/panel/debugger.properties
* Ran ```yarn start``` and made sure it was changed to "Deactivate breakpoints". 
=> Updated the "skip pausing" button to "Deactivate breakpoints".

packages/devtools-source-map/src/utils/index.js, src/utils/source.js, src/utils/tests/source.spec.js
Fixes #6578
* Add correct [file name extension->content type] mappings for cljc and cljs
* Add correct [content type->CodeMiror mode] mapping for cljs
The following are the "before" and "after" screenshots of syntax highlighting cljc and cljs sources.
cljc (before)
cljc (after)
cljs (before)
cljs (after, there should be no change in this case)
=> Enable Syntax Highlighting for ClojureScript

src/components/Editor/index.js
Currently, if `conditionalPanelLocation` is undefined we attempt to open the conditional panel at that location. Unsurprisingly, this fails as we do not know which source file or line to open at.
This change passes the source and line at which the shortcut was triggered.
While debugging this issue I spotted that the keyboard event for the shortcut is not being fired in Firefox. If the key combination is changed to say, `CmdOrCtrl+E`, it is fired. Chrome has no such issue.
Fixes #7572
=> Fix cmd/ctrl+shift+b shortcut to toggle conditional breakpoint

src/components/SecondaryPanes/Breakpoints/Breakpoints.css
Fixes #7184
* display: none is changed to color: transparent on line 151 in src/components/SecondaryPanes/Breakpoints/Breakpoints.css
The debugger too is launched and breakpoints are hovered.
[After fixing the issue](https://user-images.githubusercontent.com/23102198/50486818-8f9f8100-09b0-11e9-9f93-d97da0a62174.gif)
=> Fixed breakpoints-issue-7184

src/components/Editor/GutterMenu.js, src/test/mochitest/browser_dbg-breakpoints-cond.js
Fixes an issue where the context menu list no longer changes even if a breakpoint exists (see screenshot below), meaning you can no longer remove a breakpoint, edit a conditional breakpoint etc using the context menu, once the breakpoint is added.
seems to introduced by
https://github.com/devtools-html/debugger.html/commit/9845435ee24460835732523cf72f93bc5f1b7d3b
* stop checking `column` to show the menu for conditional breakpoints
=> Gutter menu fix

src/actions/sources/newSources.js
Fixes #7633 
* original source thread should be same as generated source thread
=> original source thread should be same as generated source thread

src/components/SecondaryPanes/index.js
Fixes #7626
Use xhrBreakpoints.label instead of xhrBreakpoints.placeholder for tooltip of button to add XHR breakpoint.
1. Open debugger.
2. In right column, go to "XHR breakpoints".
3. Move mouse over "+" button to add breakpoint.
=> Tooltip to add XHR breakpoint should use correct l10n string (#7626)

.eslintrc.jsx-a11y, src/components/SecondaryPanes/Expressions.js, src/components/SecondaryPanes/XHRBreakpoints.js
Remove the `autoFocus` attribute from the watch expression and xhr breakpoint input elements. These elements are both given focus manually.
Raise the severity of the jsx-a11y/no-autofocus rule from `"warn"` to `"error"` to avoid future warnings.
Fixes #7543
=> Fix jsx-a11y/no-autofocus warnings

.eslintrc.jsx-a11y, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap
Fixes #7541
* changed eslint rule declaration for labels
* slightly changed structure of labels in src/components/SecondaryPanes/Breakpoints/Breakpoint.js to fulfill rules:
** had to create a child element, because the eslint plugin says ["(2) has an htmlFor attribute and that the label tag has text content."](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md#label-has-associated-control)
=> Fix jsx label associated control

src/utils/location.js
Fixes #7477 
* Pass line number as is, from utils/location.js
=> pretty print exception bug

.eslintrc.jsx-a11y, src/components/SecondaryPanes/Scopes.css, src/components/SecondaryPanes/Scopes.js
Raise the severity of the `anchor-is-valid` rule to `error` to prevent any future warnings.
Change the 'Show generated/original scope' element to a use a `<button>` rather than a `<a>`. The styling of this element is updated such that it remains the same.
Fixes #7545.
Note - the cursor is a pointer but this doesn't appear in the gif.
=> Fix jsx-a11y/anchor-is-valid warnings

src/components/SecondaryPanes/CommandBar.js
Fixes #7306 
Same shortcuts in Linux and Windows.
Changed the Linux keys and tested with the new shortcuts. 
Operating System: Manjaro Linux 
KDE Plasma Version: 5.14.3
Qt Version: 5.11.2
KDE Frameworks Version: 5.52.0
Kernel Version: 4.19.1-1-MANJARO
OS Type: 64-bit
=> Step In Button Shortcuts differs in Linux, Windows (#7306)

src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/tests/Group.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap, src/test/mochitest/browser_dbg-call-stack.js, src/utils/pause/frames/displayName.js, src/utils/pause/frames/index.js, src/utils/pause/scopes/getScope.js
`formatDisplayName` was called without the `l10n`
object, which caused an exception if the last
frame of a stack was anonymous (because we then
use `l10n`).
The fix is simple, pass the `l10n` object to
`formatDisplayName`.
A test is added to ensure we cover this case.
The test do fails without the fix in `Group.js`
Fixes #7579 
1. Go to https://angular-quickstart.glitch.me/
1. Open the debugger
1. In the debugger, open `app.component.ts`
1. Put a breakpoint on the `export` line
1. Reload the debuggee tab to make the debugger pause
1. Make sure the callstack panel is expanded
1. You should see an `<anonymous> Angular` group in it
=> Fix CallStack Group with anonymous function.

.eslintrc.jsx-a11y, src/components/SecondaryPanes/Workers.js
Fixes #7539
* change `jsx-a11y/alt-text` lint rule from **warn** to **error**
* fix `jsx-a11y/alt-text` error by using `AccesibleImage` instead of `img`
Used inspector to check the rendered output:
Before:
After:
Note:  There may be some other issue with this component because clicking on a worker doesn't seem to do anything.  This happens both before and after this change so I think it is unrelated to this change.
=> Use AccessibleImage component instead of img in Workers

assets/panel/debugger.properties, src/actions/debuggee.js, src/actions/navigation.js, src/actions/tabs.js, src/actions/tests/navigation.spec.js, src/actions/types/index.js, src/client/firefox/commands.js, src/components/Editor/Tab.js, src/components/PrimaryPanes/Sources.css, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/index.js, src/components/SecondaryPanes/Breakpoints/BreakpointHeading.js, src/components/SecondaryPanes/CommandBar.css, src/components/SecondaryPanes/Worker.js, src/components/SecondaryPanes/Workers.css, src/components/SecondaryPanes/Workers.js, src/components/SecondaryPanes/index.js, src/components/shared/Svg.css, src/reducers/debuggee.js, src/reducers/pause.js, src/reducers/sources.js, src/reducers/types.js, src/test/mochitest/helpers.js, src/types.js, src/utils/workers.js
- cleans up source tree
- cleans up workers pane
=> [Workers] polish the ui

src/components/PrimaryPanes/Sources.css, src/components/PrimaryPanes/index.js
The PR to add worker sources to the tree (https://github.com/devtools-html/debugger.html/commit/efcda91d682b3e3818ed53e2f430ae70f1a7ac60) sort of broke the sources tree -> custom root functionality.
When a custom root is set, the tree portion of the panel appears empty.  It's not actually empty but the newly introduced `<div>{this.renderThreadSources()}</div>` wrapper displays at 0 height.
This PR fixes that issue.
=> Fix sources tree not displaying when custom root

src/components/Editor/Tabs.css, src/components/Editor/Tabs.js, src/components/shared/Button/styles/CloseButton.css, src/components/shared/Button/styles/CommandBarButton.css, src/components/shared/Button/styles/PaneToggleButton.css, src/components/shared/Dropdown.css, src/components/shared/Dropdown.js
Fixes #7494
* Removed `left and right 1px border` from Tabs in editor's source-header.
* Added a few css properties to `toggle-button` since i tried to add `devtools-separator` but wouldn't display on correct side when panels collapsed, since icon rotates.
* Added `min-width` to `PaneToogleButton` as requested in ticket in order to align the separator to editor number's line, when displaying 2 to 3 digits lines.
* Removed CloseButton.js `transition: all ...;` property as mentioned.
* Removed `.source-tab` and `source-tab active` 1px transparent border from left and right side to reflect demo attached to issue #7585 (img-b)
`devtools-separator as requested` 
`The close button's cross should use the tab's text color (blue when active, gray otherwise) as requested` 
As I was working through …
=> Restyle tabs

src/components/Editor/Breakpoint.js, src/components/Editor/Breakpoints.js, src/components/Editor/HighlightLine.js, src/components/Editor/index.js
Fixes #7289 
breakpoints and other components wont try rendering unless there's a doc
=> [Breakpoints] Fix timing issue with showing breakpoints

packages/devtools-components/src/tree.js, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/SourcesTreeItem.js, src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js, src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap, src/components/shared/ManagedTree.js
First, remove the expansion code in the `SourcesTreeItem` `onClick` event as the expansion is already handled in the `onClick` event of the tree component.
Next, pass the `altKey` status from the `tree onClick` event to the `ManagedTree onCollapse` function so that we know whether to collapse the children. This allows us to add the ability to collapse all children too.
Fixes #7663
=> Improve the expand/collapse all behaviour of the Sources tree

docs/getting-setup.md
Fixes #7683
* changed the git clone URL in `docs/getting-setup.md` from the SSH URL to the HTTPS URL.
=> changed git clone url in getting-setup.md

README.md, assets/dictionary.txt
By default, the image links to its own source (opening the image in a new window),
which is not as useful as a link to the repo's page on Circle CI would be.
Hereby :)
=> [docs] Link CI badge to CI status page

assets/panel/debugger.properties, src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/SourcesTreeItem.js, src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js, src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
Reintroduce the `setExpanded` function to the `SourcesTreeItem` component. Use this function to collapse/expand all for the selected item.
Add two new resource strings for each menu option.
In the future perhaps we could disable the option if all of the children are already collapsed/expanded.
Fixes #7665
=> Add 'Collapse all' and 'Expand all' sources context menu options

src/workers/parser/mapAwaitExpression.js, src/workers/parser/mapBindings.js, src/workers/parser/mapExpression.js, src/workers/parser/mapOriginalExpression.js, src/workers/parser/tests/mapBindings.spec.js, src/workers/parser/tests/mapExpression.spec.js, src/workers/parser/tests/mapOriginalExpression.spec.js, src/workers/parser/utils/ast.js
In mapExpression, if we fail to get an AST
from the expression this means the expression
has a syntax error in it.
In order to get a meaningful error when evaluating
top-level await expression, we still need to
wrap the expression in an async iife.
This required some changes in mapExpression in order
to not bail completely if parsing the expression
threw.
We also take this as an opportunity to only parse
the expression once for the all the transforms.
=> Fix unhelpful error in top-level await malformed expression.

assets/module-manifest.json, packages/devtools-reps/src/reps/error.js, packages/devtools-reps/src/reps/tests/__snapshots__/error.js.snap, src/components/SecondaryPanes/Frames/Frame.js, src/components/SecondaryPanes/Frames/FrameIndent.js, src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/Frames/Group.css, src/components/SecondaryPanes/Frames/Group.js, src/components/SecondaryPanes/Frames/index.js, src/components/SecondaryPanes/Frames/tests/Frame.spec.js, src/components/SecondaryPanes/Frames/tests/Frames.spec.js, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.spec.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap, src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap, test/mochitest/helpers.js
This PR adds a `selectable` props to the Frames component,
which, when true, will cause some white-space only nodes to
be added into the DOM.
We also switch list from `<ul>`s to `<div>`s with proper aria roles. This is unfortunate but this is the only way of not having the engine adding empty lines around the copied text (See [nsXHTMLContentSerializer.cpp#560,567](https://searchfox.org/mozilla-central/rev/c3ebaf6de2d481c262c04bb9657eaf76bf47e2ac/dom/base/nsXHTMLContentSerializer.cpp#560,567))
This is mainly aimed for the console where stacktraces can be
copied and where we want the clipboard output to be as helpful
as what is shown in the console output.
---
The testing is pretty light here because none of the component in the debugger should make use of the `selectable` prop.
It will be …
=> Make the Frames component copy-friendly

src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js, src/components/SecondaryPanes/Breakpoints/index.js, src/components/SecondaryPanes/Breakpoints/tests/Breakpoint.spec.js, src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap, src/selectors/breakpointSources.js, src/utils/breakpoint/index.js, src/utils/breakpoint/tests/index.spec.js
This is a small opinionated refactor, which is necessitated by our increased use of flow. The lesson is that `FormattedBreakpoint` can't be passed into functions that expect a `Breakpoint`
=> replace formatted breakpoint

src/components/shared/Svg.css
The previous PR for SVG's was too broad; this PR styles the top margin for only icons appearing in the SourcesTree.
=> Specify top alignment for sources tree icons only

src/components/Editor/Editor.css
This adds a short-term fix when the user scrolls in the editor in nightly
https://bugzilla.mozilla.org/show_bug.cgi?id=1519462#c8
=> [Editor] add overflow-anchor:none as a temporary fix

src/components/shared/SearchInput.css
I found a few icons we missed:
- Project search loader
- Search results next + previous.
=> Restore search's loader, previous, and next icons

images/arrow.svg, packages/devtools-components/src/images/arrow.svg, packages/devtools-components/src/tree.css, src/components/PrimaryPanes/Sources.css, src/components/shared/Svg.css
Fixes #7566 
* Implemented new `arrow.svg` icon found in mozilla-central
* Edited stylesheets to ensure proper sizing of new arrow icon in debugger.
Examined arrow icons with Firefox's DevTools' Inspector, in the Layout panel, and ran `yarn run test:all`.
=> Fix #7566 Use the same expand arrow icon as Inspector, Console etc.

docs/getting-setup.md
Fixes #7727 
* Removed the `Open Firefox` section in `docs/getting-setup.md` and  moved the instructions to the `Open Debugger` Section
=> Removed the 'Open Firefox' Section in docs/getting-setup.md

src/actions/breakpoints/addBreakpoint.js, src/actions/breakpoints/index.js, src/actions/breakpoints/syncBreakpoint.js, src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap, src/actions/breakpoints/tests/__snapshots__/syncing.spec.js.snap, src/actions/breakpoints/tests/breakpoints.spec.js, src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap, src/actions/tests/helpers/breakpoints.js, src/actions/tests/helpers/threadClient.js, src/actions/tests/pending-breakpoints.spec.js, src/actions/types/BreakpointAction.js, src/client/firefox/commands.js, src/client/firefox/types.js, src/components/Editor/Breakpoint.js, src/components/Editor/ColumnBreakpoint.js, src/components/Editor/ConditionalPanel.js, src/components/Editor/menus/breakpoints.js, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js, src/components/SecondaryPanes/Breakpoints/tests/Breakpoint.spec.js, src/reducers/breakpoints.js, src/reducers/pending-breakpoints.js, src/selectors/breakpointSources.js, src/types.js, src/utils/breakpoint/index.js, src/utils/prefs.js, test/mochitest/browser_dbg-breakpoints-cond.js
* Separately track breakpoint conditions and log values, storing them in a BreakpointOptions object.
* The options are converted into a single condition string before passing onto the source client / breakpoint client.  Bug 1520972 will take care of remaining changes to push this down into the server.
=> Distinguish between condition and log value in breakpoints

src/components/Editor/Preview/index.js
It's possible to hover on a token when paused and see nothing. This currently happens when you have closed and re-opened devtools and pause. 
STR:
1. open devtools
2. pause
3. close devtools
4. open devtools
5. pause
6. hover
The underlying bug was that we would add a second tokenEvent handler, which meant that we would respond twice to every `tokenenter`, etc. The fix opts for a simpler solution where we handle every event, but bail out quickly if we're not paused.
=> [Preview] Ensure correct event listening

src/components/App.js
Fixes #7765 
* Changing the max-width boundaries for horizontalLayoutBreakpoint and verticalLayoutBreakpoint so that they do not clash.
=> Change max-width boundaries for verticalLayoutBreakpoint

src/components/SecondaryPanes/XHRBreakpoints.js, src/reducers/breakpoints.js
Hi all!
This PR fixes #7700. 
I added an onClick function to each XHR breakpoint list item that toggles the respective breakpoint.
I had to change the callback for the filter in removeXHRBreakpoint since the new toggle feature was altering the state of the breakpoints (when using isEqual, the **_same_** breakpoint passed in through the `action` and `state` args would now have different toggle statuses, ie. disabled vs enabled, resulting in a falsey value being returned).
In addition to this issue, updateXHRBreakpoint was being called after the breakpoint was removed. This caused an error since updateXHRBreakpoint tried to update with a now non-existent breakpoint. I resolved this through checking if the breakpoint exists when a toggle action is called and returning the state accordingly. …
=> [XHR Breakpoints] Clicking text toggles breakpoint

src/actions/pause/resumed.js, src/actions/pause/tests/pause.spec.js, src/actions/tabs.js
Addresses #7710 part 2
* Fixes bug where refreshing a page that pauses at startup and has workers ends up in a messed up state where pause information is shown incorrectly.  The problem is that updating the redux state after a thread resumes updated the state of the current thread, instead of the thread that actually resumed.
* Fixes bug where loading devtools where persistent state referred to a worker source could access an undefined source object and throw an exception that prevents the debugger from loading.
Manually verified issues were fixed.  These are hard to write tests for unfortunately :/
=> Fix a couple bugs with windowless worker debugging.

src/components/Editor/Editor.css, src/components/Editor/HighlightLine.js, src/types.js, src/utils/editor/source-documents.js
Fixes #7757 
* Fixed the issue of breakpoint line getting highlighted whenever it came into view.
There wasn't any major change in the UI so I am planning to modify the tests later if required.
=> Fixes Line Highlight Bug

src/components/shared/Svg.css
The arrows that display in our tree components (preview, scopes) are very dark, unlike our accordion items and sources tree.  This small patch fixes that issue while @jaril and I work on unifying our styles from the Svg.css change
=> Fix color of arrows in trees

images/reload.svg, src/components/shared/Svg.css
The refresh icon isn't displaying properly since the SVG PR (https://github.com/devtools-html/debugger.html/commit/45c9d2636712cc11b50ade0e85ebd382f5dc6e0f);  this fixes said issue.
=> Show proper icon for watch expression refresh

src/components/shared/Button/styles/PaneToggleButton.css
Pane toggle buttons regressed from the switch away from inline SVGs, as noted by @fvsch. The right collapse/expand toggle button was pointing left when it was supposed to be pointing right, and vice versa. It also wasn't switching from pointing left/right to up/down when in vertical mode. 
<details>
<summary>Click here for GIFs from before the fix</summary>
</details>
<br>
Updated the selectors from `svg` to `.img` and they're working fine now.
<details>
<summary>Click here for GIFs from after the fix</summary>
</details>
=> Fixed selectors for pane toggle buttons

src/utils/pause/frames/tests/annotateFrames.spec.js, src/utils/pause/frames/tests/displayName.spec.js, src/utils/pause/frames/tests/getLibraryFromUrl.spec.js, src/utils/pause/scopes/tests/getFramePopVariables.spec.js, src/utils/pause/scopes/tests/scopes.spec.js, src/utils/test-head.js, src/utils/test-mockup.js
Partial fix for #7797
* Flow-ize and eliminate object literals for core structures in src/utils/pause unit tests.
* Add a test-mockup.js shared test file for use by unit tests in #7797 test refactoring.
=> Refactor src/utils/pause unit tests.

.travis.yml, test/mochitest/browser.ini
Temporarily disable `browser_webconsole_sourcemap_nosource` while we wait for the view-source fix to land in MC
=> [test] disable browser_webconsole_sourcemap_nosource

src/actions/expressions.js, src/workers/parser/mapAwaitExpression.js, src/workers/parser/mapBindings.js, src/workers/parser/tests/mapExpression.spec.js, src/workers/parser/utils/ast.js
`mapExpression` used to try to map bindings everytime, even when the debugger wasn't paused, which causes some issue ([See 1494318](https://bugzilla.mozilla.org/show_bug.cgi?id=1494318)).
With this PR, `mapExpression` will map the bindings only when paused, which brings other issue, in `mapAwait`.
In `mapAwait`, we wrap the expression into an async iife in order to get a Promise to listen for. This was working great when the bindings are mapped (because variables were put as `self` properties).
When we don't bind, we have an issue with assignments.
Say the user want to do `let a = await 123`, we can't simply return 
```js
(async () => {
let a = await 123;
})()
```
because then the user won't have access to `a`.
What we want instead is: 
```js
let a;
(async () => {
return a = await 123; …
```
=> Don't map bindings when not paused

src/reducers/sources.js, test/mochitest/browser.ini
Fixes browser_dbg-browser-content-toolbox.js failures after #7796
* Make sure duplicate source actors are not added to the redux store.  While the newSources action also checks for duplicates, the checks there do not work when the server sends a sources packet containing duplicate entries.  The checks in the action could be removed (there is a similar one for sources) but this patch preserves them as checking for duplicates early is marginally more efficient (especially when a source map needs to be loaded).
=> Don't allow duplicate source actors in redux store

src/components/PrimaryPanes/SourcesTreeItem.js, src/components/shared/SourceIcon.css
Fixes #7784 
Pretty printing a source now shows the pretty print icon beside the source in the source list pane.
<details><summary>GIF</summary>
</details><br/>
=> Fix pretty printing in source list

src/actions/pause/paused.js, src/reducers/pause.js
Fixes a bug when using web replay where reverse stepping can keep landing in the same place.  The problem is that when a step goes to an invalid pause location we issue another step, but we always issue a forward step-over which will undo any reverse-step that just happened.
* Keep track of the last command issued to each thread in redux state.
* Use new redux state to issue steps in the correct direction past invalid pause points.
=> When rewinding, reverse step past invalid step locations

src/workers/parser/tests/mapExpression.spec.js, src/workers/parser/utils/ast.js
This is done by adding the dynamicImport plugin
to babelParser.parse.
A test is added to ensure this works as expected.
---
I copied an updated parser-worker bundle to my m-c build and was able to use dynamic imports as expected :)
=> Fix mapAwaitExpression for expression with dynamic import.

src/components/Editor/Tabs.css
Fixes #7833
A bug in Firefox around `flex` and `overflow: hidden` made this work
in Firefox. @emilio figured out the root cause and suggested this
fix. Works in Chrome now and still works in Firefox.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1518715
*  add `vertical-align: bottom;` to `.source-tab`
=> Align tabs with source items.

packages/devtools-source-map/src/index.js, packages/devtools-source-map/src/source-map.js, packages/devtools-source-map/src/utils/fetchSourceMap.js, packages/devtools-source-map/src/utils/index.js, src/components/SecondaryPanes/Frames/Group.js, src/utils/bootstrap.js
Fixes #7822 
Similar to #6625, I added types to the dispatcher tasks for the source maps worker API. Some of the underlying methods were not typed, so I tried to add types to them.
- In some of the methods, types are not named. For example:
```
...
): Promise<
Array<{
line: number,
columnStart: number,
columnEnd: number
}>
...
```
Should I create named types for them? Or leave it for another PR?
- I couldn't find any reference to `getLocationScopes`. Should it be removed?
- About this snippet:
```
import * as self from "devtools-source-map";
export default self;
```
I am not sure whether this is the best way to deal with mixed: [default](https://github.com/devtools-html/debugger.html/blob/master/src/utils/test-head.js#L13) and [named](https://github.com/devtools-html/debugger.html/blob/5d8 …
=> add types to source-maps API

images/pane-collapse.svg, images/pane-expand.svg, images/toggle-panes.svg, src/components/App.css, src/components/Editor/Tabs.js, src/components/WelcomeBox.js, src/components/shared/AccessibleImage.css, src/components/shared/Button/PaneToggleButton.js, src/components/shared/Button/styles/PaneToggleButton.css, src/components/shared/Button/tests/PaneToggleButton.spec.js, src/components/shared/Button/tests/__snapshots__/PaneToggleButton.spec.js.snap, src/components/shared/Svg.css, src/components/test/__snapshots__/WelcomeBox.spec.js.snap
Fixes #7742
- Gets updated CSS (variables.css, common.css) from mozilla-central
- Use the new `--theme-icon-color` for icon color
- Sets button font-size and font-family to inherit; on Linux they tend to inherit the system font-size, was 16px (and a 21px line-height) in my case, can be 14.5px by default (11pt), etc. This creates a bunch of alignment issues due to the big line-height. Note: there is a similar style in m-c's common.css, but for some reason it doesn't seem to apply here. Maybe the `html|button` selector syntax doesn't work for the Debugger or doesn't work in all contexts?
- Make sure we have two different icon designs for "expand panes" and "collapse panes". The arrow in "expand" should point away from the sidebar, and the arrow in "collapse" should point towards the …
=> Fix styling issues with Toggle Panes buttons (fixes #7742)

src/components/Editor/ColumnBreakpoints.css
=> Fix padding for column breakpoint background

src/components/Editor/index.js
No filed issue.
This rogue semicolon gets rendered as a text node in the DOM. It doesn't seem to break anything, but it's best not to have it.
=> Remove rogue semicolon in Editor JSX

src/components/Editor/Footer.js, src/components/Editor/tests/Footer.spec.js, src/components/Editor/tests/__snapshots__/Footer.spec.js.snap
Fixes #7870
I forgot to update one call site of PaneToggleButton in a previous PR.
Test plan:
1. Open a source file in Debugger, so that the SourceFooter appears.
2. Resize the window width until the layout switches to vertical (with breakpoints at the bottom).
3. The "Toggle panes" button should now be functional (it's broken on master, always setting the UI state to the current state so nothing changes).
A note about the changed test spec and snapshot: it looks like when doing the snapshot, `props.endPanelCollapsed` is undefined, so the `collapsed` attribute is not generated in the JSX snapshot. I added this prop manually in `Footer.spec.js#generateDefaults`, but I'm not sure that's the correct approach. Happy to change it if it's not.
=> Pass the correct collapsed value to PaneToggleButton in SourceFooter

src/components/App.css, src/components/Editor/Editor.css, src/components/Editor/Footer.css, src/components/Editor/SearchBar.css, src/components/Editor/Tabs.css, src/components/PrimaryPanes/Sources.css, src/components/SecondaryPanes/CommandBar.css, src/components/variables.css
- Move header/footer height variables to root, so we can use them for the header and sidebars too
- Fix footer height so that the content area is 24px instead of 23px (#7842)
- Harmonize the CSS implementation of the Sources/Outline and file tabs (same metrics, adds animation to :hover in left sidebar)
Fixes #7842 and a few more visual inconsitencies.
Also for some reason the editor container was using a `height: calc(100% - 1px)` height, making it hard to align footers between the main area and the sidebars (which use a 100% height). I changed it to a 100% height which doesn't seem to have a negative impact, but maybe I'm missing something.
=> Align source header and footer heights to guidelines

src/components/WelcomeBox.css, src/components/WelcomeBox.js, src/components/shared/Button/styles/PaneToggleButton.css, src/components/test/__snapshots__/WelcomeBox.spec.js.snap
Looks like I introduced a small issue with the WelcomeBox height in vertical mode in #7873, and I hadn't correctly tested the PaneToggleButton changes in #7862 in right-to-left.
So here are two followup fixes.
Also fixes a button size / icon alignment issue with the bottom PaneToggleButton used in WelcomeBox in vertical mode.
=> Fix WelcomeBox height, PaneToggleButton icon direction in RTL

src/components/App.css, src/components/shared/Button/styles/CommandBarButton.css
Background color on hover of the following buttons have been fixed (made consistent with the higher level tabs)-
In the debugger mode,
1)Collapse panes both right and left
2)Pause F8
3)Step over F10
4)Step in F11
5)Step out Shift + F11
6)Deactivate breakpoints
7)Keyboard Shortcuts
=> Improving the contrast of the hover background for the buttons in the dark mode - BUG ID - 1513414.

src/components/PrimaryPanes/Outline.css, src/components/PrimaryPanes/Outline.js, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap, src/components/test/__snapshots__/Outline.spec.js.snap
Fixes #7844
* Use `.devtools-monospace` in Breakpoints pane (right sidebar)
=> Fix 7844: Implement ".devtools-monospace" CSS class

src/actions/breakpoints/addBreakpoint.js, src/actions/breakpoints/breakpointPositions.js, src/actions/breakpoints/syncBreakpoint.js, src/actions/breakpoints/tests/syncing.spec.js, src/actions/types/BreakpointAction.js, src/client/firefox/commands.js, src/client/firefox/types.js, src/components/SecondaryPanes/Frames/Group.js, src/reducers/ast.js, src/reducers/breakpoints.js, src/selectors/index.js, src/selectors/visibleBreakpoints.js, src/types.js, test/mochitest/helpers.js
Adds "possible breakpoints" which are positions that the server says would be good places to place breakpoints. This is something we want for a couple of reasons:
1. when we place a breakpoint we want to know it'll be good
2. we want to know what lines the engine considers empty
=> [breakpoints] Add possible breakpoints positions

src/actions/navigation.js
@jswalden and i noticed that the `await` was causing a timing issue while clearing the store. Hopefully this is no longer needed.
=> Stop waiting for sourceMaps.clearSourceMaps

src/actions/pause/paused.js, src/actions/pause/resumed.js, src/actions/pause/tests/pause.spec.js, src/actions/types/PauseAction.js, src/components/Editor/Tabs.css, src/components/Editor/Tabs.js, src/reducers/pause.js
Display the command bar in the tab bar if the debugger is paused and the secondary panel is closed. This allows users to step while keeping the secondary panel closed.
Fixes #7667 
- Can the appearance be improved? Is the command bar is the wrong place here?
- The secondary panel will continue to open automatically if a breakpoint is hit and the user is not stepping.
- Should this be a opt-in via an option?
=> Show command bar if paused and secondary panel hidden

renovate.json
According to https://renovatebot.com/docs/configuration-options/#recreateclosed , we shouldn't need this, but it's worth a shot to prevent renovate from reopening the same PR over and over.
=> Prevent renovate from reopening PRs

src/actions/breakpoints/addBreakpoint.js, src/actions/breakpoints/tests/syncing.spec.js, src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap, src/actions/tests/helpers/breakpoints.js, src/components/SecondaryPanes/Breakpoints/tests/BreakpointsContextMenu.spec.js, src/reducers/tests/breakpoints.spec.js, src/utils/breakpoint/index.js
Fixes #7817
we now have an `options` object on the `pendingBreakpoint` which needs to be flattened into `overrrides `
=> spread the options object inside the pendingBreakpoint

assets/panel/debugger.properties, src/actions/breakpoints/index.js, src/components/Editor/menus/breakpoints.js, src/utils/prefs.js
It's the last item here:  https://github.com/devtools-html/debugger.html/issues/7241
Adds context menu items for disabling/enabling/removing all breakpoints *on a line*.
=> Add context menus for handling breakpoints on a line

src/actions/sources/tests/blackbox.spec.js, src/reducers/sources.js
Fixes #7851 
This issue was caused by splitting source into source/sourceActor PR#7796.
I've added another function to update relative sources as sources are being updated. 
Demo:
relativeSources and sources have same values for attributes like isBlackBoxed, isPrettyPrinted, loadedState:
sourcesTreeItem now has blackbox icon when the source is blackboxed:
=> [Fix for #7851] After #7796 relativeSources attributes were not updated

.travis.yml
This adds all the smartrace component tests, as
well as copy message/export all context menu entries tests.
=> Run mozilla-central Frames dependent tests on Travis.

src/components/Editor/ConditionalPanel.css, src/components/Editor/ConditionalPanel.js, src/utils/editor/source-editor.js, test/mochitest/helpers.js
Fixes #7800 
Please let me know your thoughts and what can be improved. Thank you!
* Used CodeMirror to implement syntax highlighting for the conditional panel. This affects both conditional breakpoints and conditional log points. 
* Deleted code for placeholder/keyDown attributes on the input since the functionality is replaced by the CodeMirror instance
[x] Added conditional breakpoint condition and saw syntax highlighting was in effect
[x] Edited conditional breakpoint condition and saw syntax highlighting was in effect
[x] Ensured code did not pause when condition was not met
[x] Ensured code paused when condition was met
[x] Removed conditional breakpoint
=> Add syntax highlighting to conditional panel

docs/getting-setup.md
Fixes N/A
* Modified title ("Setup" should be two words in the context of the title, instead of one).
* Changed style of Q+A headers from italics to bold, so they stand out better.
* Capitalized proper nouns
* Uncapitalized non-proper nouns
* Added link to Node homepage for Step 1
* Fixed punctuation
* Changed phrasing for clarity
N/A
=> Fix getting-setup.md

assets/panel/debugger.properties, src/components/Editor/Breakpoint.js, src/components/Editor/ColumnBreakpoint.js, src/components/Editor/ColumnBreakpoints.css, src/components/Editor/ConditionalPanel.js, src/components/Editor/Editor.css, src/components/Editor/menus/breakpoints.js, src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js, src/types.js, test/mochitest/browser_dbg-breakpoints-cond.js, test/mochitest/helpers.js
* The log points are shown as conditional breakpoints
* On editing the log point nothing shows up in the conditional breakpoint panel
* The context menu for a log point should not show any item relating to conditional breakpoints and vice versa
* change  log points color to purple
* cleanup unused menu items
* fix `logValue`
=> Fix logpoints bug

images/arrow.svg, packages/devtools-components/src/tree.css, packages/devtools-reps/src/reps/reps.css, src/components/Editor/Footer.css, src/components/SecondaryPanes/CommandBar.css, src/components/shared/ResultList.css
Fixes #7743 and #7936.
With #7890 we started using the `--theme-icon(-*)-color` variables that landed in m-c's `variables.css` last cycle. This applies those colors to a few more icons that were not using the `.img` class.
Since #7936 was a related icon color issue, I included it in the same patch.
=> Use --theme-icon-* colors for all Debugger icons (#7743, #7936)

images/breakpoint.svg, images/column-breakpoint.svg, images/column-marker.svg, src/components/Editor/ColumnBreakpoints.css, src/components/Editor/Editor.css, src/components/variables.css, src/utils/editor/source-editor.css, test/mochitest/browser_dbg-preview-module.js, test/mochitest/helpers.js
Fixes #7929 (rationale for the change is explained there)
- Specify line-height in Editor as `calc(15 / 11)` (resulting in 15px for a 11px font-size; we could used a fixed value but they don't inherit well when changing the font-size, while ratio values do).
- Tweak the breakpoint SVGs and relevant styles to be 15px tall (line breakpoint) and 13px tall (column breakpoint); remove duplicate column-breakpoint.svg
- Change line number hover style that used a background-color on the element itself and a `::after` pseudo-element for the right part to just use a `::after` pseudo-element painted behind the number; removes some extra CSS.
- Remove legacy styles for `.CodeMirror-linenumber:before` that was used for breakpoint indicators in the past, but don't seem used at all anymore.
=> Change editor line-height to 15px (#7929)

assets/panel/debugger.properties, src/components/shared/Button/PaneToggleButton.js, src/components/shared/Button/tests/PaneToggleButton.spec.js, src/components/shared/Button/tests/__snapshots__/PaneToggleButton.spec.js.snap
Fixes #7741
Warning: removes 2 L10N strings and adds 4!
I don't know if there's a special process to follow up with people who work on localization?
I've tried to restrict the flow type for position to an enum with 2 strings, and fix the tests accordingly. I'm pretty new to flow so I did it by ear, but it seems alright.
=> Use different labels for start and end PaneToggleButtons (#7741)

src/components/SecondaryPanes/Frames/Group.css
The CSS was wrongfully reverted to an older version,
which means that we weren't styling those
elements anymore.
Fixes #7953.
(I'll follow up on the icon issue)
=> Fix Frames Group style.

assets/panel/prefs.js, src/utils/editor/create-editor.js, src/utils/prefs.js
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1108132
Wanting code to be wrapped seems completely reasonable to me -- I sometimes do it in my local text editor.
We could consider providing a UI for this in the settings pane or even a toggle-able checkbox in the Editor footer.
=> Fix Bugzilla 1108132 - Provide code wrapping pref for debugger

src/components/SecondaryPanes/EventListeners.css, src/components/SecondaryPanes/EventListeners.js
#7879 - Improve UI implementation of EventListeners list
* Moved the arrow icon to outside the label, so when it's clicked, it doesn't trigger the checkbox
* Fixed the vertical alignment of the checkbox and text inside the label
* Fixed height of rows according to UI spec(at 20px)
* Wrapped a button element around the arrow icon so it can be used with keyboard
=> Improve EventListener UI

docs/local-development.md, postcss.config.js, src/components/ProjectSearch.css, src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/CommandBar.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/XHRBreakpoints.css, src/components/WelcomeBox.css, src/components/shared/Dropdown.css, src/components/shared/SearchInput.css
Fixes #7941
* Remove postcss-bidirection from `postcss.config.js`
* Fix the RTL magnifying glass icon position in RTL
* Change a few text-align values to start|end
I've tested a few things and things look alright in Chrome and Firefox.
More hands on testing would be welcome though. (We may find RTL issues that already exist on master, by the way.)
=> Remove postcss-bidirection

src/utils/pause/frames/getLibraryFromUrl.js, src/utils/pause/frames/tests/annotateFrames.spec.js, src/utils/pause/frames/tests/getLibraryFromUrl.spec.js, test/mochitest/browser_dbg-call-stack.js
Fixes #7901
Modified `getLibraryFromUrl()` so that it only matches Angular's core framework sub folder, not its components.
- Matches `/turbo_modules/@angular/core@7.0.1/bundles/core.umd.js`
- Doesn't match `/~/src/app/hello.component.ts`
Note that in the image below, `ngOnInit` (which is defined in hello.component.ts) isn't collapsed into the Angular frame group:
=> Modified the Angular regex

assets/dictionary.txt, docs/mochitests.md
Wrote this based off of my own experience with Mochitests and what I would have found useful as I first started working with it. If I missed anything that could be valuable or there's a better approach to certain parts, let me know :)
Updated mochitests.doc. Changes include:
- Clarified `Initial Setup` steps for both Mac and Windows users
- Updated steps with the Firefox build process (`./firefox/mach build`)
- Added Mochitests `Folder Overview`
- Added step-by-step tutorial of a basic Mochitests test with examples
- Consolidated sections related to debugging tests under `Debugging your tests`, which now includes logs, pausing with timeouts and pausing with debugger statements. Added examples where necessary
- Added `Test Writing Tips` which elaborates on common test patterns, e.g., …
=> Update mochitests docs

src/components/WelcomeBox.css, src/utils/text.js
Fixes #7892
* Removed spaces from formatKeyShortcut function for MacOS consistency
1. I verified manually that the fix updated the shortcuts on the initial load of debugger
2. I run `yarn test` (Tests: 10 skipped, 1649 passed, 1659 total)
=> fixed keyboard shortcuts on MacOS [#7892]

src/components/PrimaryPanes/SourcesTreeItem.js, src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js, src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap, src/utils/sources-tree/getURL.js, src/utils/sources-tree/tests/getUrl.spec.js
I noticed when going to https://w2x2oypmqk.codesandbox.io/ that the sources tree cited "external%20file" but, when opened, the tab said "(index)", as did a sources search.
Simply checking for no "." is far too basic.
I've also unescaped the text in the tree, as it used to be.
=> Ensure consistent filenames throughout tabs, tree, and search

src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/tests/SourcesTree.spec.js, src/components/PrimaryPanes/tests/__snapshots__/SourcesTree.spec.js.snap
Fixes #7874
Fixes the issue when focused source would not be selected via keyboard using Enter/Space keys.
=> Fixing source selection with the keyboard (fixes #7874) (#7874)

src/components/Editor/ColumnBreakpoints.css, src/components/Editor/Editor.css
Fixes #8004 
* Deleted 2 CSS properties on disabled breakpoints that were changing the color of all disabled breakpoints/logpoints to blue
* Also deleted the CSS variables related to the deleted CSS properties because they are now unused
* Note that this change helps fix both conditional breakpoints and conditional logpoints. Works in both light and dark theme
=> [Breakpoints] Fix color for disabled conditional breakpoints and logpoints

README.md
Updated doc to reflect new name of repository (_debugger_) and removed references to old repository name (_debugger.html_), as decided in PR #8009 .
Fixes N/A
* Replaced any instances of _debugger.html_ with _debugger_ (or removed them altogether)
* Fixed capitalization of "debugger" on line 60.
=> Update name of repository

docs/debugging-the-debugger.md
Added file name for the CSS variables file, which is in node_modules, and not immediately apparent.
Maybe helpful for newbies like me!
Fixes #<issue number>
https://firefox-dev.tools/debugger/docs/pull-requests.html
* Added path for CSS variables:
~/debugger/node_modules/devtools-mc-assets/assets/devtools/client/themes/variables.css
This is my first PR - thanks for any advice/help on testing!
Don't think I need to run any tests for this basic doc update?
=> Docs update: debugging-the-debugger.md

README.md
Updates the community call link to reflect the new appear.in room (https://appear.in/firefox-debugger), as discussed with @jasonLaster in PR #8018.
Jason's comment can be viewed here:
https://github.com/firefox-devtools/debugger/pull/8018#issuecomment-466485945
* Changed community call link to https://appear.in/firefox-debugger
=> Update community call link

packages/devtools-reps/src/object-inspector/tests/utils/should-render-roots-in-reps.js, packages/devtools-reps/src/object-inspector/utils/node.js, packages/devtools-reps/src/reps/big-int.js, packages/devtools-reps/src/reps/rep.js, packages/devtools-reps/src/reps/stubs/big-int.js, packages/devtools-reps/src/reps/tests/big-int.js
Fixes #7974.
The server will send a grip of the following shape: 
```json
{
"type": "BigInt",
"value": "1",
}
```
where `value` is `myBigInt.toString()` (we can send the actual BigInt as they're not serializable).
We can display it by taking `value` and appending `n` to it (e.g. `1n`).
=> Add a BigInt rep.

src/actions/preview.js
Fixes #7956 
Investigated the issue and found that it applied to other falsy values, such as `0` and `''`.
Within `src/actions/preview.js` we have a piece of code that exits/returns from `setPreview` when the `result` of evaluating the `expression` is a falsy value.
This code originated from PR [#3363](https://github.com/firefox-devtools/debugger/pull/3363). It looks like the use case for this code might be to exit `setPreview` if the `expression` evaluates to something undesired. However, it's also the reason we see unintended behavior with certain falsy values. I  deleted this code to fix the issue.
Let me know what you think and if there is anything I can improve, thank you!
=> Update setPreview to properly display falsy values in preview tooltip

README.md, docs/getting-setup.md
The current Firefox launcher in launchpad launches the stable Firefox release, where setting breakpoints is broken. This PR adds instructions in the documentation for contributors to launch Firefox Nightly instead with the CLI.
- Added instructions for launching Firefox Nightly with CLI in `getting-setup.md`
- Added a note after the Quick Setup section in the project's `README.md` to launch Firefox Nightly
=> Added Firefox Nightly CLI launch instructions

src/components/SecondaryPanes/Breakpoints/Breakpoint.js, src/components/SecondaryPanes/Breakpoints/tests/Breakpoint.spec.js, src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap
Fixes #8026 
* Replace breakpoint's `label` tag for a `span`, including `aria-labelledby` to the breakpoint's checkbox
* Update breakpoint test snapshot
Being quite straightforward, I followed @fvsch's advice in the issue's comments but think I bumped into #6965. If anyone can confirm that the change solves the issue I would appreciate it. Thanks!
=> Fix 8026 - Prevent breakpoint label from triggering checkbox focus

src/actions/preview.js
Reverts firefox-devtools/debugger#8027
While reviewing the latest release (https://phabricator.services.mozilla.com/D21608), the following caused the debugger to go blank:
1.  Go to https://davidwalsh.name
2.  Add breakpoint to line 1 of main.js
3.  Refresh browser, breakpoint will hit
4.  Hover over "hash"
5.  Debugger bricks
The following error is shown:
```
console.error: (new TypeError("value is null", "resource://devtools/client/debugger/new/src/components/Editor/Preview/index.js", 149))
JavaScript error: resource://devtools/client/debugger/new/src/components/Editor/Preview/index.js, line 149: TypeError: value is null
```
After removing this commit, the debugger no longer bricks.
We need to further investigate why but in the mean time we should revert this commit.
cc @ravefalcon92
=> Revert "Update setPreview to properly display falsy values in preview tooltip"

src/components/Editor/Tab.js
Fixes #7799 
Essentially reverts https://github.com/firefox-devtools/debugger/commit/04ee6a4b2d805ba5ba53eb48f167897182366099
=> Fix 7799 - Restore pretty print shim to tab context menu

src/components/SecondaryPanes/index.js
So I was just chilling in `SecondaryPanes/index.js` and noticed that a bit of code was using `items = [ ...items, newItem ]` to basically do an `items.push(newItem)` (unlike all of the surrounding code) and thought I would harmonize that.
I also moved `renderHorizontalLayout` just before `renderVerticalLayout` to organize things a bit. Since it's a very short method it's not too big of a change.
So, nothing major, and if you don't like it you can also close the PR. :)
=> Unify array creation style in SecondaryPanes getStartItems and getEndItems

src/components/SecondaryPanes/Breakpoints/Breakpoints.css
Fixes #8012
I keep the `:hover` feature intact for users using a mouse. I added `:focus-with` for keyboard users. I'm new to accessibility practices, so I'd like to listen to feedback and follow up with the discussion. After deciding for breakpoints, we should keep the behavior consistent for watch expressions' delete button.
* Added :focus-within property
1) Hovering the label: delete button displays; mouse out: delete button hides.
2) Using tab. Tabbing to the check box: delete button displays; tab out: button hides.
3) One potential "side effect": I use the mouse to check off the box then move my mouse out. Since the checkbox is still in focus, the delete buttons still shows. I need to click somewhere else to get the checkbox out of focus, then delete button can hide. Not sure if it's …
=> Add focus-within for showing breakpoint's delete button

src/components/SecondaryPanes/Frames/Frames.css, src/components/SecondaryPanes/Frames/Group.css
- Fixes #7993
- Fixes global selectors in SecondaryPanes/Frames (#7905)
Result looks like this:
Monochrome icons use the label's text color. We had some outdated targetting SVG paths that was doing that, so I replicated the effect:
Multicolor icons don't change depending on the normal/expanded state:
=> #7993 Fix callstack frame-group icon and avoid global selectors

src/workers/parser/getSymbols.js, src/workers/parser/utils/helpers.js
Fixes #8057
* Make getUniqueIdentifiers() O(N) instead of O(N^2), fixing performance of this function on large workloads.
Tested on #8057 testcase
=> Use O(N) algorithm in getUniqueIdentifiers.

src/components/SecondaryPanes/Frames/Frames.css, src/components/shared/AccessibleImage.css, src/components/shared/SourceIcon.css
Fixes #8084
Ideally it would be great if we could return the framework name as `"Vue.js"` and the className as `vuejs`, rather than supporting two names (`"Vue"` and `"VueJS"`) and two classes (`"vue"` and `"vuejs"`), but I'm not sure how to do that and the CSS fix seems less risky.
=> Fix #8084 - Vue.js icon missing in Frames

src/actions/preview.js, test/mochitest/browser_dbg-preview.js
Fixes #7956
Good manual testing:  
- Basic: http://breezy-join.glitch.me/
- Previously found brick case:  https://github.com/firefox-devtools/debugger/pull/8056#issue-257591385
I also updated the test that had these values commented out.
=> Fix #7956 - Show falsy values in preview

images/plus.svg, src/components/shared/Accordion.css, src/components/shared/Accordion.js, src/components/shared/tests/__snapshots__/Accordion.spec.js.snap
This restores:
- the old "+" icon, to avoid shipping a lonely Photon icon in Firefox 67
- correct padding in the accordion header ()
Small improvements:
- Small improvements to spacing to match Matt's spec
- Fix button alignment in RTL
- Add spacing between buttons (e.g. in Watch expressions)
- If we are short on room, cut the label, instead of letting the text push the buttons to the right (sometimes outside of the header).
__Testing plan:__
We need to test this with mochitest because last time we had similar changes to accordion headers, some tests broke. :(
A real possibility is that removing the `height:24px` (so that the header can be 25px, including the bottom border) shuffles some content around and a synthetic click misses. Or there is a synthetic click near the end of the header …
=> Fix #8040 - Correct Accordion header spacing and restore thin plus.svg icon

src/components/SecondaryPanes/tests/XHRBreakpoints.spec.js
Very low hanging fruit for removing some of the noisy eslint warnings on `yarn lint`:
> debugger/src/components/SecondaryPanes/tests/XHRBreakpoints.spec.js
>  132:5  warning  Unexpected var, use let or const instead  mozilla/var-only-at-top-level
>  162:5  warning  Unexpected var, use let or const instead  mozilla/var-only-at-top-level
>  204:5  warning  Unexpected var, use let or const instead  mozilla/var-only-at-top-level
I wanted to use `const` in every instance, but one is actually reassigned later in the same function, so I used a `let` there.
=> Fix eslint warnings in XHRBreakpoints.spec.js

src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/XHRBreakpoints.css, src/components/shared/SearchInput.css
Fixes #8017
I'm setting left:x and right:x properties manually for the `ltr` and `rtl` directions.
Absolute positioning is rare in Debugger, so it's not a lot of work.
I've left two uses of `inset-inline-start|end` around:
- `WelcomeBox.css`: that usage should be removed in #8039
- `Dropdown.css`: addressed in #8081
=> Fix #8017 - Work around unsupported inset-inline-start|end in Chrome

src/components/PrimaryPanes/SourcesTree.js, src/components/PrimaryPanes/tests/SourcesTree.spec.js, src/components/PrimaryPanes/tests/__snapshots__/SourcesTree.spec.js.snap
Fixes #7966
* Added a "No Sources" message in the sources pane when there are no sources on a page
=> added no sources message in Sources Pane

src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Breakpoints/index.js, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/SecondaryPanes.css, src/components/SecondaryPanes/XHRBreakpoints.css, src/components/shared/Accordion.css, test/mochitest/browser_dbg-breakpoints-actions.js, test/mochitest/browser_dbg-breakpoints-cond.js, test/mochitest/browser_dbg-breakpoints.js
These are the Breakpoints and XHR Breakpoints changes from the [UX Alignment](https://github.com/firefox-devtools/ux/issues/45) issue. I put them together in the same PR since they share some styles in `Breakpoints.css`.
- Changed breakpoints, XHR breakpoint, and option rows to 20px height
- Changed font sizes to 11px
- Changed pane content indentation to 20px
- Changed nesting indentation to 16px
- Removed inset-inline-end selector for XHR Breakpoints
=> Aligned breakpoints and XHR breakpoints panes

src/components/SecondaryPanes/Expressions.css
Fixes <#7868>
Mimic what we have for breakpoint delete button.
* Hide the button outside of view.
* Display it when hover the container or tab to the delete button.
* Mouse
* Tab. Hit enter at the end.
=> Switch watch expression's delete button

assets/panel/debugger.properties, src/actions/sources/tests/__snapshots__/newSources.spec.js.snap, src/components/Editor/index.js, src/components/Editor/menus/breakpoints.js, src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js, src/components/ShortcutsModal.js, src/components/test/__snapshots__/ShortcutsModal.spec.js.snap
Fixes #7692
* Created new keyboard shortcut(`CmdOrCtrl+Shift+Y`) for toggling conditional panel for log points
* Updated log points context menu accelerator 
* Updated ShortcutsModal with new keyboard shortcut for log points
* Changed shortcut description for `shortcuts.toggleCondPanel` from `Toggle Conditional Panel` to `Edit Conditional Breakpoint`
* Updated snapshot testing
=> [Log Point] Fix log point context menu accelerator

src/components/shared/ResultList.css, src/utils/quick-open.js
Fixes #8124 
Implemented a version with showing only the end of the path.
I am not sure if we need ellipsis in the middle, because in most cases we care about last directories.
* removed truncation in JS 
* added an ellipsis on the start of the line
=> [QuickOpen] show the end of the path

package.json, packages/devtools-reps/package.json, packages/devtools-reps/src/reps/date-time.js, packages/devtools-reps/src/reps/tests/date-time.js
Fixes #6153
* change date from` toISOString` to `toString` format
I modified the already existing tests to accommodate the new feature since the return values of the date time was changed.
=> Display Date object using `toString` instead of `toISOString`

postcss.config.js
Fixes #8155
In the postcss config for the dev environment (aka for launchpad started with `yarn start`), remove two postcss plugins:
1. Re-remove `postcss-bidirection`, which was removed in #7941 together with its dependencies and reintroduced in Sync 130 _without_ its dependencies (https://github.com/firefox-devtools/debugger/commit/c4524619ee9f0ca50bda5c73505f08ce19085119#diff-b19118abc8e2dbd959e8a14a8c0edcd7R37). As far as I know, we don't want to use it anymore because both Firefox and Chrome have support for CSS logical properties and this polyfill creates selectors with higher specificity which leads to selector specificity battles.
2. Remove `postcss-class-namespace` because A) in practice we don't use it, the only usage I'm seeing is in …
=> Remove postcss-bidirection and postcss-class-namespace from dev build

packages/devtools-components/src/tree.css, packages/devtools-reps/src/object-inspector/components/ObjectInspector.css, src/components/PrimaryPanes/Sources.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Scopes.css
These are the Watch Expressions and Scopes changes from the [UX alignment issue](https://github.com/firefox-devtools/ux/issues/45) adapted to the [Event Listeners](#7937). I put them together in the same PR since they split the Object Rep styles between the two of them.
* Changed rows to 20px height
* Changed watched expression font to monospace
* Changed monospace font size to 11px
* Changed pane content indent to 20px
* Changed tree indents to 14px to match arrow spacing
* Removed [inset-inline-end](#8017) selectors 
@fvsch @mcroud Thoughts?
=> Align watch expressions and scopes pane

docs/local-development.md
Follow-up to previous SVG work and #8121 which removes react-inlinesvg and the Svg component.
=> Rewrite SVG section of Local Development doc

packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/tests/string-with-url.js
Fixes #6108.
The attribute was removed because in some places
the link could be opened directly in the panel's
frame, which isn't good.
But this is breaking JSON Viewer links, and also
prevent some context menu entries to work in the
console (open link, copy link, …).
This patch adds the `href` attribute back, but only
if the reps are meant to be displayed in content
page, or if an `openLink` function is provided.
=> Render href attribute in String rep URLs.

packages/devtools-reps/src/reps/rep-utils.js, packages/devtools-reps/src/reps/string.js, packages/devtools-reps/src/reps/tests/string-with-url.js
This fixes https://bugzilla.mozilla.org/show_bug.cgi\?id\=1204728
The String Rep linkification was too greedy and would
include unwanted character in the URL itself, although
it shouldn't (e.g.  would include the closing parens).
We switch to a regex solution, taking inspiration from
the mail app in Firefox OS (https://github.com/mozilla-b2g/gaia-email-libs-and-more/blob/convoy-status/js/clientapi/bodies/linkify.js).
Test cases are added to ensure this works as expected.
=> Fix string linkification greediness.

src/components/App.js
Fixes #8144.
In the original code, the `onEscape` function is only responsible for dismissing Quick Open and Active Search. It does not dismiss the Shortcuts Modal. 
I decided to remain consistent with the logic used for the “Cmd+/” shortcut to dismiss the Shortcuts Modal. Below is a code snippet showing how the `onCommandSlash` function dismisses the Shortcuts Modal.
[Code Snippet](https://github.com/firefox-devtools/debugger/blob/12ad6bed134b11f05ea30d0aa751edda49ee9cfe/src/components/App.js#L167-L169)
**Demonstration of the Unwanted Behavior:**
Above: The Shortcuts Modal button (orange arrow) or “Cmd+/” has been used to pull up the Shortcuts Modal.
Above: “Escape” has been used to dismiss the Shortcuts Modal, but it is not dismissed. 
**Demonstration of the Changed Behavior:**
Above: …
=> Enable dismissing keyboard shortcut info modal with “Escape” key

src/components/SecondaryPanes/Breakpoints/Breakpoints.css, src/components/SecondaryPanes/Expressions.css, src/components/SecondaryPanes/Scopes.css, src/components/SecondaryPanes/SecondaryPanes.css, src/components/SecondaryPanes/XHRBreakpoints.css, src/components/shared/Accordion.css
Fixes #8129
* Fixed the horizontal overflow of the headers in the debugger secondary panel.
=> Fixed Horizontal scrolling in the debugger secondary panel

src/components/QuickOpenModal.js, src/components/test/QuickOpenModal.spec.js
Fixes #8119 
https://firefox-dev.tools/debugger/docs/pull-requests.html
Added a conditional to keep resultCount (number returned from getResultCount) at 100 or less.  
This is contained in the traverseResults method, within QuickOpenModal.js. 
Tested behavior based upon expected behavior described by @fvsch.
This is my first code PR, so greatly appreciate any and all feedback.  
Sorry for the extraneous commits (issues with git).
Thanks!
=> Keep QuickOpenModal resultCount in bounds

src/utils/sources-tree/addToTree.js, src/utils/sources-tree/treeOrder.js, test/mochitest/browser_dbg-sources-querystring.js
Fixes #7160 
* Sort by entire url (including parameters) rather than name alone when files share same name
* Only sorts when naming conflicts exist
* Modified mochitest (`doc-sources-querystring.html`) to test for sources in order
1. Open https://fortunate-skunk.glitch.me/ 
2. Open debugger
3. See sources in order
Before/After
=> [SourcesTree] Sort SourcesTree by url when files share same name

src/components/Editor/Footer.css, src/components/Editor/Footer.js, src/components/Editor/tests/__snapshots__/Footer.spec.js.snap
Fixes #8064 
https://firefox-dev.tools/debugger/docs/pull-requests.html
* Split controls to the left and rest of icons on the right
* Check with different permutations of what can appear/not appear
For example the 'pretty print' button will show on minified source, the "from" information will show if there's a source map
=> 8064-footer

configs/README.md, docs/bundling.md, docs/community-team.md, docs/debugger-react-redux-overview.md, docs/debugging-the-debugger.md, docs/getting-setup.md, docs/lerna.md, docs/maintainer.md, docs/mochitests.md, docs/most-common-issues.md, docs/pull-requests.md, docs/remotely-debuggable-browsers.md, docs/running-as-firefox-panel.md, packages/devtools-reps/README.md
Replace all outdated references to `debugger.html` with references to `debugger`, [as discussed with](https://github.com/firefox-devtools/debugger/pull/8009#issuecomment-466031447) @jasonLaster in PR #8009. 
Fixes N/A. 
* Replace all instances of *debugger.html* with *debugger* (14 files changed total)
* Add simple formatting (bolding, code formatting, etc.) in limited cases, in order to avoid confusing the name of the repository (*debugger*) with the regular noun "debugger"
=> Replace outdated references to debugger.html

packages/devtools-reps/src/reps/grip.js, packages/devtools-reps/src/reps/tests/grip.js
Fixes #6147
* remove skipp from `Grip - Object with uninteresting properties -> renders as expected test`
Tweaked the tests a little and changed LONG MODE not to use default output for tests to pass
=> remove skip from grip.js test

src/components/Editor/Footer.css, src/components/WelcomeBox.css
Fixes #8192 
- Decreased footer width by 1 px for consistency within the editor pane (also prevents footer from covering the border)
- Added overflow: hidden to welcomeBox.css
=> Fix issue#8192 Remove white bottom bar 

src/components/shared/Popover.css, src/components/shared/Popover.js, src/components/shared/tests/__snapshots__/Popover.spec.js.snap
Fixes #8107 
In the unchanged code, the gap is placed above the popover if the orientation is right.
I decided to use `flex-direction: row` in the popover.css file in order to change the placement of the gap, from above the popover to the left.  I then had to make some minor adjustments to the `calculateLeft` function and the `getPopoverArrow` function in the popover.js file to accommodate the changes made.
**Gap placement before change:**
**Gap placement after change:**
=> Changed gap placement on popover orientation-right

src/components/QuickOpenModal.js, src/components/test/QuickOpenModal.spec.js, src/components/test/__snapshots__/QuickOpenModal.spec.js.snap, src/utils/quick-open.js, src/utils/result-list.js, test/mochitest/browser_dbg-quick-open.js
* avoid allocating intermediary array
* use sets to avoid linear look-up
* debounce source transformations and filtering
* avoid unnecessary layout computations when scrolling
=> Improve performance of "Go to file"

src/components/SecondaryPanes/index.js
-Removed unnecessary div from SecondaryPanes.js that was causing the splitter from filling the box
Before:
After:
=> Update SecondaryPanes splitter

docs/debugger-react-redux-overview.md
Spelling, grammar, punctuation and style fixes.
Fixes N/A
* Fixed spelling, grammar, punctuation, style, and capitalization
* Cleaned up links in Markdown to match style used in rest of repository
* Added link to CodeMirror
* Added `code` formatting to all file, component, object, reducer, and action names
* Fixed naming of elements where necessary to match with rest of repository
* Replaced all "code" html tags with backticks
=> Fix debugger-react-redux-overview.md

src/components/SecondaryPanes/CommandBar.js
Fixes #6993
I've been away a while so I thought I would try an easy one to get reacquainted with the project.  It looks like no one has touched this in 3 months so I took it.  I hope you don't mind.
* Add parenthesis and 'or' to step button tool tips to make them more readable
**Before**
**After**
=> Improve readability of stepping button tool tips labels
