firefox-devtools/debugger

README.md
environment.sample
js/components/SplitBox.js
js/lib/themes/components-h-split-box.css
webpack.config.js

This patch removes the firefox dependency:
+ moves split-box.css into lib
+ removes the webpack.config dependency on environment.json
+ updates the readme so environment.json is optional
It also:
+ adds an environment.json.sample file

Remove Firefox Dependency

---

js/actions/sources.js
js/prefs.js

+ Support Prefs via PrefsHelper
+ Pull in SourceClient via ff-devtools-lib
I have not tested the action associated with showing prettified
source, so there are probably still bugs. This is nice because it
uncomments code in loadSourceText.

Get closer to supporting pretty printing

---

package.json
stylelint.config.js

[Stylelint](http://stylelint.io/) is a popular CSS linter with lots of [rules](http://stylelint.io/user-guide/rules/), which will let us keep the CSS clean.
I added a simple config, which checks for bad hex, 2 space indentation, and a couple other small knits. There's a good [example](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js) with many more rules we can add in the future.
Questions:
+ are we in consensus that we want a linter?
+ not a blocker, but would we like to add linting on PRs with a service like travis?
+ what kind of rules would like to add?
Example:
I ran stylelint on our codebase and got this [gist](https://gist.github.com/536309bfd7d8f17bb23e47abfc6f9ba7), which is an argument for adding a linter sooner rather than later.

Add CSS Linter

---

js/actions/index.js
js/actions/tabs.js
js/client.js
js/components/Breakpoints.js
js/components/TabList.css
js/components/TabList.js
js/components/Tabs.css
js/components/Tabs.js
js/constants.js
js/main.js
js/queries.js
js/reducers/index.js
js/reducers/tabs.js

The tabs landing page shows the tabs that are ready to be debugged.
Currently, you re-select the tab you want to debug each time you
refresh, but we'll hopefully make it possible to select a tab and
refresh, without losing your selection shortly. I think the most natural
approach is to add a hash url.
http://recordit.co/otL3a1ly8C
Changes:
There's a new Toolbox component, Tabs component, action, and reducer.
At some point it would be nice to pull these pieces out of the debugger.
The protocol logic was moved into a thread-client module, which exposes
connectToClient and connectToTab methods. This is probably the most
important thing to review.

Add a Tabs landing page

---

js/components/Tabs.js

When the event handlers were extracted, the store and actions
references were lost. This fixes that by accessing newSource
with bindActionCreator.

Fix newSource event

---

js/components/Editor.js

React.render is deprecated.  This clears a console warning and is the only instance of the code using React.render.

ReactDOM.render instead of React.render

---

bin/test
bin/test-loader.js
js/components/App.js
js/components/Breakpoints.js
js/components/SplitBox.js
js/reducers/tests/sources-2.js
js/reducers/tests/sources.js
package.json

This adds a test runner.
It's pretty janky. We need to compile each test with webpack which makes things a lot harder. Currently we compile everything as a separate entry point with a single webpack command in to the `build/tests` directory, and invoke the xpcshell runner on that. The `build/tests` directory is recursively removed each run to make sure it's fresh.
It works. We'll have to use it a little bit to see if it works well enough. All we need is something that will run for 3 months until we merge it.
I don't think mocha is a good idea because we will already have a lot of to when merging our code back in. I think it would be just too obtrusive to the merge, but we can investigate other solutions.
**Don't merge this yet**, because I want to test it some more. Just wanted to put it …

add test runner

---

js/actions/breakpoints.js
js/actions/sources.js
js/actions/tabs.js
js/main.js
js/util/thunk-middleware.js

This fixes chrome devtools pause crash, which would happen when there
was a destructured param.
old 
```js
return ({ dispatch, getState, threadClient }) => {}
```
new
```js
return (dispatch, getState, threadClient) => {}
```

Convert Action argument destructuring to list

---

package.json
server.js

+ uses webpack-dev-middleware
+ replaces starting node serve-static
+ eventually we can add other niceties here (cache busting, hmr, ...)
Benefits of webpack-dev-middleware:
+ doesn't write to file
+ on refresh, will hold the request if there isn't a build ready

Start simple node express server

---

js/actions/breakpoints.js
js/components/Editor.js
js/components/Sources.js
js/queries.js
js/reducers/breakpoints.js

**Not ready to be merged**
This makes it so you can remove breakpoints and makes our immutable usage more consistent. We still need to figure some things out: right now we are treating anything passed through actions as normal JS objects. This is because you frequently do `this.props.fireAction({ x: 1})` so you can easily pass an object. However now we need to remember to do `this.props.fireAction(obj.toJS())` if we are using something from the existing state, like a breakpoint location. I'm sure we can figure this out; we could make actions detect if a parameter is immutable and coerce it to a JS object or something like that. Not exactly sure yet.
We also need to make the editor render breakpoints better. This still adds/removes a breakpoint on gutter click, but we really need to always …

improve breakpoints

---

.travis.yml
bin/test-node
circle.yml
karma.conf.js

Moves the Karma tests out of Travis and into Circle Ci. There are two benefits with the move:
1) the tests are run with an up to date version of chrome
2) the slower karma tests are run in along side the faster tests, which hopefully will keep our tests faster.
Signing up for circle ci is as easy as going to (https://circleci.com/) and enabling debugger.html

Move Karma tests to circle-ci

---

js/components/Editor.css
js/components/Editor.js

This sets the line number font to white and moves the breakpoint below
the linenumber.
I couldn't find where Firefox did that work, so I thought I'd share the
PR incase there's a better way of doing it. One thing I noticed for
example, is if the breakpoint appears ahead in the DOM structure, then
it doesn't need any z-index treatment.

Add breakpoint styling

---

bin/test-node
js/actions/tests/loadSourceText.js
package.json

I took a stab at adding a test watcher for node.
Most of the diff is linting test-node. Notable changes are:
+ commander for parsing arguments
+ fs.watch for watching for changes
Here is the [error](https://gist.github.com/jasonLaster/e1eded70e37820c5a9ca50348b8e6c53) I'm seeing. I didn't spend too long debugging it, but it looks like an issue with ff-devtools-libs, where these two shams are not being requested the second time:
```
Cc sham for @mozilla.org/io-util;1
CC sham for @mozilla.org/scriptableinputstream;1 nsIScriptableInputStream init
```
I double checked that the build file is updated and I'm pretty sure babelified.

(WIP) Test watcher

---

.storybook/webpack.config.js
bin/test-node
public/js/actions/tests/loadSourceText.js
public/js/actions/tests/newSource.js
public/js/actions/tests/selectSource.js
public/js/components/stories/Breakpoints.js
public/js/test/fixtures.json
public/js/util/test-head.js

Added two select source tests
Refactoring:
+ created a fixtures.json (cleaned up some fixture drift)
+ removed intermediate describe/beforeEach
I'd like to considering having a util file for actions so that the two mock clients could go there. One problem is that currently any non-hidden file in a test dir will be considered a test file. What do you think of having a suffix like spec (e.g. selectSource.spec.js)?

SelectSource Tests + Refactoring

---

public/js/actions/pause.js
public/js/components/RightSidebar.css
public/js/components/RightSidebar.js
public/js/reducers/pause.js
public/js/selectors.js

This resolves issue #96.
I believe there is an existing error with waiting for the next break point that involves loading in source code. However despite that error I believe this will correctly handle the possible button states.
There is a slight flicker on the play/pause button when stepping over code. This is due to the way that the inline svg module loads in the SVG. I also took the liberty to refactor some of the CSS to make the button hit areas more consistent.
What's the current state of testing? I noticed there wasn't too much in there, so I didn't include any with this pull request.

Add proper states for debugging command buttons

---

public/js/components/RightSidebar.css
public/js/components/RightSidebar.js
public/js/components/Sources.js
public/js/reducers/sources.js

Started working on Call Stacks and saw an opportunity to cleanup Sources. Nothing scary here.
+ add _updateText formatting function for sources
+ cleanup sources component

Refactor Sources

---

circle.yml
package.json

I've noticed that it's common for me to create a PR without first
linting. This change updates `npm test` so that it runs node mocha as
well as the linters.
When that happens, circle ci also becomes a bit simpler.

Update npm test scripts

---

.eslintrc
public/js/actions/pause.js
public/js/actions/tabs.js
public/js/components/App.js
public/js/components/Breakpoints.js
public/js/components/RightSidebar.js
public/js/components/SourceTabs.js
public/js/components/Sources.js
public/js/components/stories/Breakpoints.js
public/js/components/stories/accordion.js
public/js/util/editor.js

This will enforce a whitespace character between objects and their
properties. It does not force nested object curlies to have whitespace
e.g. { x: { a: 2 }} is okay.
I think it is okay to change eslint if we're becoming stricter, of course going the other way is different.

Add Eslint object-curly-spacing rule

---

public/js/components/Scopes.css
public/js/components/Scopes.js
public/js/components/stories/Breakpoints.js
public/js/components/stories/Scopes.js
public/js/components/stories/index.js
public/js/components/stories/utils.js
public/js/test/fixtures/backbone.pause.onEnter.json

Updates:
+ Refactored Storybook's `createStore` to support fixtures
+ Change block scope behavior to always show (consistent w/ firefox)
+ Change function scope labels to support anonymous and always have the word function.
+ Add scope accordions for styling and collapsing large scopes

Scopes (Part 2)

---

bin/server.js
package.json

This PR makes the proxy a dependency of the server. The rationale is that both the  firefox-proxy and server are useful for the local development environment, but not necessarily useful when the debugger is in the FF toolbox. 
Going forward, I'd like to refactor the proxy so that it has a better api `proxy.start({ clientPort: 9000, browserPort: 6080 })`.
Also, I've noticed that if integration tests are running in the background and you happen to be testing manually as well, there can be miscommunications between the two debuggers and two debuggees. The solution, would be to have the testing environment communicate over different ports 9001, 6081. We could do that by adding the clienPort to the config.js and maybe having a testing config as well, although from experience, the testing …

add proxy to dev-server

---

public/js/components/Accordion.js
public/js/components/Editor.js
public/js/components/Sources.js
public/js/components/util/ManagedTree.js
public/js/lib/tree.js

I'm reviewing the new tree sources, and the display names were missing on several components. I added them here so that the React add-on displays better information.

Add displayName to all components.

---

bin/development-server.js
package.json
public/js/configs/development.json

Before I open my devtools PR, I wanted to merge in these changes.
I rebased on master and found a few surprising things: `npm start` actually opens a new tab in my browser, which is very surprising. I'd like to remove this behavior, it's more annoying than helpful. If I'm debugging something that's requiring me to restart the server, a new tab is opened every single time even though I already have it open. I personally prefer to make tools more focused and not surprising. Developers can copy (or in iTerm, cmd+click) the URL in the terminal.
Additionally, chrome debugging is turned on by default, which makes Firefox continually spin because the request for chrome tabs never completes (I don't have it on). I definitely think it should be turned off by default. This makes the first run …

small tweaks to make first run experience better

---

public/js/clients/firefox.js
public/js/components/Tabs.js
public/js/main.js
webpack.config.devtools.js

This will quickly conflict with your work on Chrome, but here is what I did to get it working as an external bundle. I think the key thing is that the bootstrapping process lives outside of the core system. So `debugTab` does not exist anymore, it's more broken down into smaller pieces that whatever is driving the system can choose what to run.
Saw your other PR and will comment in there as well.

support library compilation mode for usage inside devtools

---

package.json

Fixes #156
There were a couple of package.json tweaks needed to publish a debugger.html package
+ add version number
+ add prepublish step
+ add a fields field for public/build

Prepare debugger for npm

---

public/js/actions/breakpoints.js
public/js/actions/sources.js
public/js/actions/tests/loadSourceText.js
public/js/actions/tests/selectSource.js
public/js/clients/chrome.js
public/js/clients/firefox.js
public/js/clients/index.js
public/js/types.js

I'm already running into several situations where I need to wrap the Firefox protocol to translate something because we changed actors to ids. I think we need to go ahead and create a base API implementation for talking with servers.
This nice thing is that we don't have to deal with client/server communication at all. All we need is a simple programmatic API to talk about debugger data. I don't think we should do it the object-oriented way like the Firefox `main.js` currently is. I suppose eventually we may want to group these functions into separate namespaces, but I'd like them to stay simple functions that take ids on which to operate (for example, `sourceContents` takes a `sourceId`).
I also tweaked `chrome.js` to consolidate the APIs for the client modules into something more …

consolidate client APIs into a generic API interface

---

public/js/actions/pause.js
public/js/clients/chrome.js
public/js/components/Editor.js

I feel like doing some polish work today :)
Chrome expects 0-based line locations everywhere. We use 1-based lines. Not only were we using `functionLocation` instead of `location`, but we were setting breakpoints on the wrong line (we should be setting them on `line - 1`).
This makes Chrome debugging work as expected.

fix locations of chrome breakpoints and improve debug line

---

public/js/actions/pause.js
public/js/actions/sources.js
public/js/components/Editor.js
public/js/reducers/pause.js
public/js/reducers/sources.js

The editor must rely on some sort of paused state because if you switch to a file where the engine is paused, it needs to highlight the line that it is paused on. If can't only highlight the line the first time, and then switching away and back (via the source tree) not highlight the line again.
I also realized that we don't just want to highlight the line of the top frame. That's what we did before: highlight the line if the `pause.frame` (which is the top frame) has a location. But what if it's a file that is paused deeper in the stack?
Additionally, what if it's a file that has *multiple* stack entries? It's paused in several locations in that file.
I played around with Chrome and realized that they don't always highlight all the locations in the stack. They only highlight the …

make the editor highlighted line much more robust and remove selectedSourceOpts

---

public/js/actions/breakpoints.js
public/js/clients/chrome.js
public/js/clients/firefox.js
public/js/components/Breakpoints.js
public/js/components/Editor.js
public/js/reducers/breakpoints.js
public/js/types.js

Breakpoints were pretty broken before: sliding breakpoints wouldn't work, and the data returned from each client was actually a bit different. I went ahead and improved the protocol so that "breakpoint clients" are only something the Firefox client has to be concerned with now. Breakpoints should be a lot more robust: sliding works, and adding & removing seems to always work now (previously sometimes I couldn't remove a breakpoint because it got into a bad state).
I also fixed "snippets" with sliding breakpoints: previously it would show "undefined" if the breakpoint moved. Now it properly gets the text from the line that it moved to.
r?

make breakpoints more robust and improve protocol interface

---

public/images/stepOut.svg

This is going to look fine on retina macs, but I'm going to file a follow-up bug to check that it's pixelsnapped on non-retina screens (can't check until I'm work with my other monitor).

Fix #230, stepOut icon now has lines along bottom

---

mocha-runner.html
public/js/actions/tests/loadSourceText.js
public/js/actions/tests/selectSource.js
public/js/components/Accordion.js
public/js/components/Breakpoints.css
public/js/components/Breakpoints.js
public/js/components/Editor.js
public/js/components/RightSidebar.js
public/js/components/Scopes.js
public/js/components/stories/Breakpoints.js
public/js/components/stories/Editor.js
public/js/components/stories/Sources.js
public/js/components/stories/index.js
public/js/components/test-utils.js
public/js/components/tests/Breakpoints.js
public/js/components/tests/Editor.js
public/js/test/cypress/commands.js
public/js/test/cypress/commands/debugger.js
public/js/test/cypress/commands/todomvc.js
public/js/test/fixtures/foobar.json
public/js/test/integration/fixtures.js
public/js/test/integration/todomvc.js
public/js/test/utils/debuggee.js
public/js/test/utils/renderComponentFromFixture.js

Adds several more steps to the integration tests:
+ enabling / disabling breakpoints
+ selecting a breakpoint (for source navigational purposes)
+ selecting a scope
+ step in, out, over ...
As I went, I refactored the debugger commands so that common selectors
were re-used to avoid painful test refactoring when the UI changes.
Writing the tests were actually pretty fun. Surprising/Unsuprisingly,
there were no hiccups along the way.
I cleaned up some of the CSS as I went so that the class names were
clearer.

Add more integration tests

---

public/js/components/Sources.js
public/js/util/sources-tree.js
public/js/util/tests/sources-tree.js

This is the simpler implementation of the collapsed sources that maintains the collapsed tree state on the component.

Collapsed sources

---

config/feature.js
public/js/main.js

This is the last tweak to configs that I'm going to make. Jason, we can talk about this when you get back.
It feels weird to me that the configs should know about how to parse query strings and stuff like that. That is solely part of the initialization process, and I really like that new developers can just open up `main.js`, read it from top to bottom, and see exactly how it works without having to dig into other abstractions.
I see the config system as mostly server-side. As mentioned in another PR, the client should be given a set of flags somehow that just tweaks a few things (are sourcemaps enabled, etc). When we integrate with Firefox, we'll use it's pref system to hand the client its configs.
Definitely something we'll talk more about when you get back!

More config tweaks

---

bin/development-server.js
public/js/components/Sources.css
public/js/components/SourcesTree.js
webpack.config.js

This enables CSS hot reloading by not extracting CSS into a single file in dev mode. It also moves the hot reloading config from development-server.js where it didn't belong.

consolidate webpack dev/prod config into webpack.config.js

---

public/js/components/ObjectInspector.js
public/js/components/RightSidebar.js
public/js/components/Scopes.css
public/js/components/Scopes.js
public/js/components/util/ManagedTree.js
public/js/lib/devtools-sham/shared/DevToolsUtils.js
public/js/lib/tree.js
public/js/reducers/pause.js
public/js/util/sources-tree.js
webpack.config.js

This is a heavy refactoring of scopes that I've been wanting to do. There is now a standalone `ObjectInspector.js` component that will be easy to share. The only thing is that it depends on our tree stuff, and we've tweaked the tree from m-c and we have `ManagedTree`. But it shouldn't be hard to reconcile the tree component, and once that's done that component can be shared.
This greatly improves performance. If you have the window scope expanded with a million items, the tree is still fully interactive and you don't notice any slowdown.
Additionally, it's more accurate as to what values it shows. There are still things missing, and we should show things like functions better, but there's also much clearer places in the code to implement those kinds of things now.

greatly improve scope inspector, split out object inspector component and optimize it

---

public/js/components/Breakpoints.js

Currently breakpoint info includes only line number and a truncated snippet of code.
I wish there was also the file name, but I couldn't find it in the breakpoint object.
I would ultimately do 2 lines in the breakpoint - first line with `filename.js:line` and second line with smaller grey text of the truncated snippet, plus a tooltip of the full snippet.
This pull request adds only a tooltip of the full snippet.

Add tooltip to breakpoint snippet

---

public/js/components/Breakpoints.css
public/js/components/Breakpoints.js
public/js/components/stories/Breakpoints.js
public/js/components/tests/Breakpoints.js
public/js/components/tests/Frames.js
public/js/test/fixtures/pythagorean.json
public/js/test/fixtures/todomvc.json
public/js/test/fixtures/todomvc.updateOnEnter.json
public/js/test/integration/fixtures.js

This creates style classes for breakpoints so I could make the font colour lighter to match the disabled state.  Needs @helenvholmes review.
I also added an option for the paused state so we could style that separately as well but couldn't find a style that I liked.  Maybe @helenvholmes has ideas for this or it can remain the same.  I used CSS animations to make the breakpoint "flash" a background color which worked pretty well but needs more thought into the timing because it distracted from the editor text location.
@jasonLaster I changed the storybook to be 3 breakpoints from 1 so I could have one of each type.  The last, disabled, breakpoint disappears when you check the box and I wasn't sure how to handle this.  I assuming it is the click handler running and then finding that …

Style disabled breakpoints in the list

---

public/js/components/Frames.css
public/js/components/Frames.js
public/js/components/tests/Frames.js

adds a line number to the source location if the source location exists
if there is no source location it no longer adds an empty element
also lightens the text a bit, hopefully @helenvholmes is cool with that

add line numbers to frame source location

---

bin/development-server.js
bin/firefox-driver.js
config/development.json
public/js/clients/firefox.js
public/js/lib/devtools-sham/transport/ws-transport.js

Turn on the Firefox WebSocket debugger server and use it instead of the proxy:
- enable the `devtools.debugger.remote-use-websocket` pref
- comment out spawning the proxy
- change the `webSocketPort` to 6080 - we are connecting directly to Firefox now
Your Firefox needs to be built with the WebSocket patch from [bug 1286281](https://bugzilla.mozilla.org/show_bug.cgi?id=1286281).

Use Firefox WebSocket transport instead of the WS/TCP proxy

---

public/js/components/ObjectInspector.js
public/js/reducers/pause.js

**Don't merge this**. As I was typing this out I realized that this work should happening in the `ObjectInspector` component. I will probably make the `loadedObjects` map contain all the info needed to construct this data. I'll change this PR tomorrow.

show the __proto__ value in the object inspector (fixes #319)

---

public/js/components/Autocomplete.css

Since longhand background-position-* are only implemented starting firefox 49, I thought they aren't necessary in this case.
Also, I thought that using the border rather than outline is better for focus state in this case since otherwise both of them show up

autocomplete UI tweaks: center icon and focus outline

---

public/js/components/Autocomplete.css

This is not part of issue #338, but I believe it is better to have the overflow on the UL element so that scrolling a long list of sources doesn't cause the input to escape the viewport

file search overflow should not lose the input

---

public/js/actions/breakpoints.js
public/js/selectors.js
public/js/util/source-map.js

I can't believe how much cleaner this approach is from before. 
Things fell in line really nicely:
+ selectors translate locations
+ source map acquired a couple useful helpers
+ client is wrapped so that it receives generated locations
This probably could be dried up further, but it shows promise

Translate breakpoint locations to original locations

---

package.json
public/js/reducers/index.js
public/js/reducers/sources.js
public/js/reducers/tests/sources.js
public/js/selectors.js
public/js/utils/dehydrate-state.js
public/js/utils/makeRecord.js

Don't merge this quite yet, I might make a final round of tweaks. But this shows you what it will look like.
Unfortunately, as the comment explains, it's not quite as clean as I would like. I would have loved for the selectors to just take the "sources" state and work with it directly, but unfortunately that's hard. We still want to expose a single module that the UI can require to get access to the selectors, and be able pass top-level app state into them (`getSources(appState, ...)`). This means we need to import all the selectors, "wrap" them so they pick off the right sub-state, and call the selector from the reducer.
But that's impossible to type. This is as close as I got: https://gist.github.com/jlongster/591b785b74a9ba0627e8e5241a30607f Unfortunately, because Flow requires …

(wip) proposal for moving selectors into reducers

---

public/js/components/SourceTabs.js

I find it helpful in tab situations when the full URL or path to file is show-on-hover with the tab.  
Just a suggestion, feel free to close.

Add full URL as tab title

---

README.md

Per https://github.com/ChromeDevTools/debugger-protocol-viewer/issues/41, the official name is `Chrome Debugging Protocol`

Update name of CDP to the official name

---

karma.conf.js
public/js/actions/breakpoints.js
public/js/actions/types.js
public/js/components/App.js
public/js/components/Breakpoints.js
public/js/components/Editor.js
public/js/components/EditorBreakpoint.js
public/js/reducers/breakpoints.js
public/js/reducers/index.js
public/js/reducers/sources.js
public/js/selectors.js
public/js/test/fixtures/foobar.json
public/js/utils/dehydrate-state.js
public/js/utils/makeRecord.js
public/js/utils/utils.js

This is a large PR, but it can't really be helped. When converting things from immutable to JS and applying types we need to change everything that uses it.
I want to start writing more tests for the reducers and actions so this helps a lot (and we won't need to update tests if we do these changes now).
A breakpoint in the app state is now a normal JS object. We use it far more than we update it, so it's easier, but the main reason is so that we can have a single `Breakpoint` type and use it everywhere. If we want it to be immutable, we would still use a record type and all the external uses would use normal property lookup (`breakpoint.location`), so we could make that change later if we really wanted.

apply flow to breakpoints reducer, move breakpoints selectors, and convert to JS types

---

config/development.json
public/js/actions/sources.js
public/js/clients/firefox/events.js
public/js/lib/acorn.js
public/js/lib/pretty-fast.js
public/js/lib/source-map.js
public/js/utils/pretty-print-worker.js
public/js/utils/source-map.js
public/js/utils/utils.js
webpack.config.js

This is a first pass on client side pretty printing.
Adds:
* a pretty print worker that generates the prettified text and ugly to pretty mappings
* adds a createSourceMap function that creates a map from ugly to pretty
Next steps:
* store the pretty text and show it in the editor
* write and extend function that will extend an original source map if the ugly source is mapped
Question:
* i'm not sure what to do with the pretty-fast lib and deps. At the moment they're in lib... I think they should have the same mc path `devtools/<same-mc-path`. We will probably need to update the paths to reflect their chrome nature. In addition, the worker will probably have to be a ChromeWorker for this as well... All of this to say there's some work to do once we land the bundle to wire up the …

Pretty print

---

.eslintrc

This rule makes it difficult for functions to return null values e.g.
```js
function getSourceId(id) {
const source = findSource(id);
if (!source) {
return;
} 
return source.id
}
```
More importantly, this rule is less expressive than what is possible with flow typing returns.

Drop eslint constent-return

---

bin/firefox-proxy
public/js/clients/firefox.js
public/js/components/Tabs.js

This is a small change to the Firefox connect lib with some other lint fixes to the `firefox-proxy`.
The web socket connection change allows for another computer (work local network access) to connect to the `firefox-proxy` web socket server and debug Firefox remote-remotely.
I don't have this change working for Chrome debugging yet.  The tab list request is being blocked, possibly because Chrome is connected to localhost doesn't naturally allow external access.  Not sure there is a way around this but I was only targeting Firefox for now.
I should finish with some better error handling for Chrome so when the tab list times out you can continue to work with Firefox.
A very similar change to the Tabs page allows for Node debugging so I broke that out into a separate commit because the Tabs …

Connect to the Firefox web socket proxy remotely

---

public/js/actions/sources.js
public/js/actions/tests/loadSourceText.js
public/js/actions/types.js
public/js/reducers/sources.js
public/js/types.js
public/js/utils/source-map.js

**do not merge**
WIP pretty print patch for saving pretty sources and showing them in the editor w/ breakpoint support.
Architecture:
* saves a new "pretty" source, with a different url and id. Works well for source maps as the map points from ugly source to pretty source
* locations do a better job of maintaining column data, which is useful for going from generated locations to original locations when the server comes back with an actual breakpoint location.
* moves source text from a state field to a source field. I found it simpler to reason about and the patch was minor. I prefer thinking about sources w/ text that could either be not loaded, loading, done, but it's not a big deal
* caching came for free.
What works well:
* source is shown
* breakpoints work
* tabs reflect different …

(WIP) Save Pretty Print Sources

---

public/js/components/RightSidebar.css

I just added to the right side bar css file. I am having issues testing in chrome but this appears to work in Firefox. Note that when you pause on a breakpoint we still get a one line wrap on the source name but I would think that is what you would want it to do.

Right Sidebar element wrapping (#439)

---

config/feature.js
public/js/main.js
public/js/test/node-unit-tests.js

The unit tests were not getting the config values, which were needed for getting the source map base url.
The fix is to change the way the config was being set so that it's always set with `setConfig` at the right time.
There are two cases to keep in mind:
+ **local scripts** (dev-server, unit tests, ...) need to set the config at the top if they're going to use features.
+ **app** needs to set the config at the top of main.js, based off of the DebuggerConfig global. I'd prefer if debuggerConfig were a module that could be required, but i'm not sure if that's possible.

Fix unit tests

---

public/js/components/EditorBreakpoint.js
public/js/components/stories/Editor.js

This adds a second story for the Editor, which has a selected source and some breakpoints. Unfortunately, I found that for toggling between stories breaks the editor. I believe it has something to do with the provider not supporting changing the store, but i'm not sure.

Add editor story

---

bin/development-server.js
public/js/components/App.js
public/js/lib/devtools-sham/client/shared/key-shortcuts.js
public/js/lib/devtools/client/shared/shim/Services.js
public/js/test/cypress/commands.js
public/js/test/cypress/commands/debugger.js
public/js/test/integration/todomvc.js
public/js/utils/event-emitter.js
webpack.config.js

Fixes #360.
This PR adds the key-shortcuts library, Services Shim, and EventEmitter.
Notes:
+ key shortcuts library gives us an api for setting keyboard events. It did not support preventDefault, so i added a patch that I will also land in m-c.
+ services shim - adds lots of useful properties that are de-privileged. I'm most excited about prefs. Prefs however tried tor read local storage items with the assumption that they were all JSON parseable, which was not the case because todomvc shoves some random stuff in there. Consequently I moved the debugger examples to port 7999.
+ EventEmitter is a general purpose utility in m-c. It is being added to our utils directory because I had to rip out the `logEvent` function which assumes dump is available. There's also a lot of factory setup, …

Add Key Shortcuts library

---

public/js/actions/index.js
public/js/actions/navigation.js
public/js/utils/source-map-worker.js
public/js/utils/source-map.js

Fixes #480. 
The problem is that source map data in the worker is not being cleared during debuggee navigation.
There are a couple ways to clear the data:
+ data is kept in a weak map with object references
+ data is kept in a reducer, which observes the navigation event
+ the navigate action calls a source map method to clear the data
We discussed this problem a week or two ago and agreed it would be nice to use either option 1 or 2. Unfortunately, I'm not sure how to do that when the data is kept in the worker. I don't think option 3, is that bad though, as it is quite common for an action to do the side-effect work, whether it's talking to a stateful store, client, or in this case worker through an API.

Clear source maps on navigation

---

public/js/clients/chrome/events.js

found this small bug while comparing chrome and firefox source events for the sources tree expand/collapse issue.

Exclude internal sources

---

circle.yml
config/config.js
public/js/clients/chrome.js
public/js/test/cypress/commands/debugger.js
public/js/test/integration/todomvc.js

Fixes #405. 
Notes:
* Adds an env flag for debugging chrome
* Adds the "Inspectable Pages" tab to the list
* Adds a test for debugging an app with source maps
Note: the test is actually flakey now and half the time does not pause even though the breakpoint is added and button clicked... Looking into the protocol now

Add chrome tests for source maps

---

config/README.md
config/development.json
docs/feature-flags.md

Need to add flag docs for `watchExpressions`.  This situation also has me thinking that I want a CI test or bot who looks for feature flag usage and warns if you didn't add it to the development.json file; too big a job for now.
I also wanted to have some docs to point to to help guide issues like #437

add watchExpressions feature flag and related docs

---

bin/development-server.js
package.json

currently accessing localhost:7999 results in 404, so initially I thought is was broken (I knew about it from the console of the development server)
So this adds the directory listing from which the examples are accessible

add direcory listing for examples folder

---

public/js/clients/firefox.js

This is not technically needed, but I feel better explicitly disabling these two features so that we can a) operate confidently that they are disabled, b) rip out the functionality later.

Disable source maps + blackboxing

---

public/js/clients/firefox.js

There would be certain times where I couldn't connect to Firefox, and I realized it was because of this timeout. For various reasons my computer would be slow sometimes. Let's kick this really high because it's *super* annoying to have a flaky connection.

increase Firefox timeout (avoids false positives)

---

public/js/components/Sources.css
public/js/components/utils/ManagedTree.js
public/js/lib/tree.js

I think the only reason we couldn't do this before is because keys weren't properly computed for the object inspector, but now they are. Keys should always be unique, so we can use that to track which ones are expanded or not. This solves the issues with the sources tree because the collapsing generates a new tree each time. Now it properly expands initially.

make ManagedTree use item's key as index instead of instance

---

public/js/clients/firefox.js

When the debuggee is paused it stops sending "will-navigate" events, which means that it's possible to refresh the debuggee and still show all of the pause data in the debugger.

Fix refreshing while paused

---

bin/firefox-driver.js

If the `firefox-driver` script is given the `--websocket` option, it didn't really start the WebSocket server, because of how the `--start-debugger-server` option works:
- `--start-debugger-server` use pref values `d.d.remote-port` and `d.d.remote-websocket`. This is new behavior for the port pref after landing [bug 1286281](https://bugzilla.mozilla.org/show_bug.cgi?id=1286281). Before that, the port pref wasn't consulted at all and the default port was hardcoded as 6000.
- `--start-debugger-server 6578` start the classic (non-WebSocket) server on port 6578, don't look at any prefs (that's why we're adding the `ws:` prefix in this patch)
- `--start-debugger-server ws:6578` start the WebSocket server on port 6578.
If the `firefox-driver` script didn't have to be compatible with builds …

Fixed starting Firefox debugging server with the WebSocket option

---

public/js/main.js

This is a stopgap solution so the Firefox panel has the ability to select a source from other places like the console. Eventually, we probably want to be explicit about the global API we expose and only expose things like `selectSource`.

expose actions to rest of devtools

---

public/js/components/Editor.js

The editor is blank after a file search. This is due to the fact that a render happens with the default text "..." and the source text is not updated.
We fix this by always calling setText when the component mounts, in most cases it's a no-op, but it does fix the case where the editor is dis-mounted and then mounted again.

Fix #334 - editor loses context

---

bin/firefox-driver.js

In #453 the examples directory began running off the port `7999`, this was forgotten in the update.

update the todomvc port for npm run firefox

---

public/js/clients/firefox/commands.js
public/js/utils/source-map-worker.js

Fixes #486.
There was an issue where firefox would not pause when a breakpoint was set in an original source. It turns out that the issue stemmed from the column being passed in as 0, which firefox treated as a column number that had to be deciphered. 
https://dxr.mozilla.org/mozilla-central/source/devtools/server/actors/source.js#859

Fix source map breakpoints

---

public/js/clients/firefox/events.js

It looks like debugger evals were being added as sources. There's an ignore clause above that checks for debugger code eval source urls, is that needed?

Exclude debugger eval sources

---

public/images/Svg.js
public/js/components/Accordion.css

The CSS for the accordion arrow was nearly identical to the arrow CSS
except for an additional 2px of margin-right.
I ended up hunting in Svg.js and saw this odd combination of template
literals and string addition that I needed to fix.
This fixes #430

remove accordion isvg svg css selector

---

public/js/components/Breakpoints.css

I’ve been seeing a falling float in the breakpoint list.  The pause icon keeps wrapping around and falling into the next line.  This changes the list items to use flex box instead which won’t allow for the same float issues.

use flex box for breakpoint component

---

public/js/components/App.js
public/js/components/Editor.js
public/js/lib/codemirror.css
public/js/lib/themes/dark-theme.css
public/js/lib/themes/light-theme.css

+ Adds light + dark theme
+ Enables light theme                     
I discuss changing themes in https://github.com/devtools-html/debugger.html/issues/134#issuecomment-238379361. At the end of the day, i think that's a new issue that we can resolve separately. What this does is bring consistency between the old debugger and new debugger.

Fix light theme syntax highlighting

---

public/js/clients/chrome/commands.js
public/js/clients/firefox.js
public/js/clients/firefox/commands.js
public/js/components/Frames.js
public/js/test/cypress/commands.js
public/js/test/cypress/commands/debugger.js
public/js/test/integration/todomvc.js
public/js/test/utils/debuggee.js

@jbhoosreddy and I noticed when we were working on adding an integration test for watch expressions that the expressions were not evaluated until the debugger had resumed. 
The reason for this was that the debugger pauses in the integration tests by running a console evaluation like `dbg.click("button")`, which does not return until the debugger resumes. The console has a mechanism for only running one evaluation at a time, so it blocks subsequent evals. 
We get around this problem by creating a new evaluate method that includes a timeout, which will simulate an evaluation response. In the case of firefox, we also have to clear the internal pending requests store.

Stub debuggee evaluation

---

public/js/components/Sources.css

This PR would change the sources header to use the darker default colour text.
Here's a comparison of the sources header with and without the grey colour.
@helenvholmes ?

sources header uses the default colour

---

public/js/actions/sources.js
public/js/components/Editor.js
public/js/components/SourceFooter.js
public/js/test/cypress/commands.js
public/js/test/cypress/commands/debugger.js

I've been noticing an increase in cypress intermittents, this is not necessarily a surprise because we've added a lot more tests and increased the steps in the existing tests.
I think these fixes are a step in the right direction:
1. I noticed that some tests were attempting to pretty print a file before it had loaded. now the tests waits until the button is active, which is only the case after it has loaded. And if for any reason the action is invoked early, it bails.
2. I noticed many cases where the tests did not pause. I believe this is due to pretty print sending two client evals in quick succession. Now all evals have a mandatory 1 second wait period.
After these fixes, i did not see any errors when i ran the pretty print test 20 times.

Fix Pretty Print tests

---

public/js/clients/chrome.js
public/js/clients/chrome/events.js
public/js/lib/chrome-remote-debug-protocol/docs.md

_This isn't a priority but only affects the Chrome code._
By adding the `setOverlayMessage` method to both the pause and resume events we get the Chrome overlay in the debugger.  The overlay has working buttons, they seem to send messages directly to the debugger and our interface receives the new state and behaves correctly.
**NOTE** the method [setOverlayMethod](https://chromedevtools.github.io/debugger-protocol-viewer/1-1/Debugger/#method-setOverlayMessage) is part of the 1.1 stable debug protocol.  Though as you can see it is listed in the Debugger domain and yet it was [moved to the Page](https://codereview.chromium.org/801363004/) domain a while back.  Finally it appears to have been removed completely from future versions, Chrome Canary returns an error when this method is sent. …

adds overlay message to Chrome

---

public/js/utils/source-map-utils.js
public/js/utils/source-map-worker.js
public/js/utils/source-map.js

This fixes a small inconsistency with `makeOriginalSource`. It also introduces a shared utility for source maps, which we can now use because the worker is being bundled with webpack.
Please ignore the irony that the source map worker is itself source mapped :P

Move makeOriginalSource to source-map-utils

---

public/js/components/Editor.css
public/js/components/EditorBreakpoint.js

Using just "breakpoint" clashes with m-c. It pulls in CSS that applies a style to `.breakpoint` so it messes with our breakpoint (and actually adds the old breakpoint on top of ours). The reason I didn't see this before was that we aren't loading the SVGs so I didn't see the SVG that m-c CSS was adding.
Tweaking our class with avoid all these issues. It's a little unfortunate, but an easy change that will avoid any clashing for now.
I initially tried to move the breakpoint-specific CSS from CodeMirror to the old debugger, but that doesn't work because it pulls it in in an iframe, so you can't style it from the outside. This will have to do for now.

use unique breakpoint class to not clash with mozilla-central

---

public/js/test/cypress/commands.js
public/js/test/cypress/commands/todomvc.js

1. Add a wait before the debuggee command.
The theory is that maybe the breakpoint is not set or something like
that that's keeping the debuggee from pausing
2. Clear localstorage
I have no idea how many todos are saved, it could be in the thousands by
now. This clears the list so that it doesn't create performance issues.

Fix some of the flakiness in the integration tests

---

public/js/components/Tabs.css
public/js/components/Tabs.js
public/js/main.js

When I want to connect to node, I open the debugger and click on the "connect to node" link.
But the "not connected" message doesn't show until the Firefox connection times out. We should just go ahead and show the "not connected" message by default, and when it finds tabs it will re-render and show the normal tabs page. The `Tabs` component is already listening to the tab state so all we need to do is render the `Tabs` component immediately.
I also updated the styles because the styles for the "not connected" component don't really apply on the main tabs page.

always render connect message immediately & tweak styles

---

public/js/components/RightSidebar.js

I noticed in the test runs that #558 broke the "break on next" ux. It also caused the stepping buttons to always be active, which might have contributed to some of the flakiness. Also, the #556 caused an issue with updating the right sidebar on subsequent changes.
Unfortunately, I believe the test flakiness has caused me to question the test results and not re-run when I see a failure. I'm going to continue investigate some the flakiness and also make sure that I confirm that a test is truly intermittent before merging.

Fix Break on next

---

public/js/components/Editor.css
public/js/components/Editor.js
public/js/components/EditorBreakpoint.js

Hi,
I came across #548 through up-for-grabs.net, thought i'd have a look at it 😃
This will show disabled breakpoint gutter markers but faded out so you can tell the difference.
It looks as though the Editor isn't ready for unit tests yet? (Correct me if i'm wrong!) So i didn't write any for this but existing unit tests pass.
Please let me know if there's any problems or i've missed anything.
Thanks,
Matt

Add disabled state for breakpoint markers

---

CONTRIBUTING.md

* `up for grabs` should have difficulty rating
* anything assigned indicates intent to implement
* stale issues should be closed
* created table to explain label system
* reorganized up for grabs work

add docs for issues to contributing fixes #349

---

public/js/components/Scopes.js
public/js/test/integration/tests.js

Fixes #579 
@JasonWeathersby the change ended up being larger than I expected and certainly larger than your one line change! The big difference is that here the scopes pane uses the selectedFrame as a data source as opposed to updating the pause info directly.

Fix scopes with selected frame

---

public/js/clients/firefox/events.js
public/js/test/cypress/commands/debugger.js
public/js/test/integration/tests.js
public/js/types.js

It turned out that we were no longer showing the <this> property in the scopes pane. This happened because `this` wasn't being added to frames.

Show "this" in the scopes pane

---

public/js/test/cypress/commands/debugger.js

This helps address the cypress intermittent problem where we see that the call stack frames are empty when we expect to be paused.
I believe the problem is largely due to adding a breakpoint and not waiting for the breakpoint to be active. This can take a little longer on CI because the app pauses and resumes as well.

Toggle breakpoint should wait for breakpoint to be active

---

public/js/test/cypress/commands/debuggee.js
public/js/test/cypress/commands/debugger.js
public/js/test/integration/tests.js

Adds a test that walks through all of the navigation commands and makes sure the sources list is uptodate.
We'll be able to incorporate source tabs and breakpoint behavior when the other PRs land.

Add test for navigation

---

public/js/components/Scopes.js
public/js/test/integration/tests.js

* Fix #593 : Use a variable for pausedScope actor instead of function
* Fix #593 : Return an object for 'this' variable instead of an array
* Add <this> test for second scope

Fix #593 : Add this variable for inner scope

---

public/images/Svg.js
public/js/components/App.css
public/js/components/App.js

Associated with #584 adds the file search close button. I noticed a bug with `Svg` when I passed the `onClick` without the `className` prop also existing. Fixed this in a single commit that I can roll back and put in another PR.
Also still working on styling. Need some guidance there on what CSS is appropriate (in terms of units to use, flexbox, etc)
Screenshot

File search close

---

public/js/components/RightSidebar.css

The scroll came from the `overflow-y` value, I changed this to `auto` which gives us the expected behavior and no scrollbar till needed.

Fix for issue 627 - scrollbar added

---

public/js/components/SourcesTree.js
public/js/utils/utils.js

We shouldn't be debouncing. Previously the action was throttled, which means you are guaranteed to render about every 50ms, instead of lots of sources continually debouncing and not rendering anything for several seconds. This changes when we moved this logic into the component.
I noticed this when trying to load a site with lots of sources: the sources tree is just blank for 5-10 seconds while it's loading. Not it continually renders the tree as they come in.

throttle sources tree instead of debounce

---

public/js/components/Breakpoints.js

Fixes #479.
This is a simple fix. I'd like to re-think how we're storing breakpoints later when we introduce a localstorage backed pref system. My thinking is that it would be nice to store breakpoints in local storage so that we can access them after the debugger is closed/re-opened. If we start doing that, it might make sense to only load breakpoints for a page when the debugger starts.

Hide breakpoints from other pages

---

public/js/main.js

This is the second half the `fix-console` work.
We can land the m-c part separately because it doesn't break the old debugger, but this will have to land in the bundle so that the new debugger works.

Export a bootstrap function

---

public/js/clients/firefox.js
public/js/reducers/sources.js
public/js/test/integration/tests.js

Fixes #526.
There's a similar problem with tabs, which this does not address.

Persist selected source across debuggee refreshes

---

.eslintignore
.gitignore
bin/download-firefox-artifact
bin/make-firefox-bundle
bin/prepare-mochitests-dev
bin/run-mochitests-docker
circle.yml
docs/mochitests.md
package.json
public/js/main.js
public/js/test/mochitest/.eslintrc
public/js/test/mochitest/browser.ini
public/js/test/mochitest/browser_dbg_add-breakpoint.js
public/js/test/mochitest/code_simple.js
public/js/test/mochitest/code_simple2.js
public/js/test/mochitest/doc_event-listeners-02.html
public/js/test/mochitest/doc_simple.html
public/js/test/mochitest/head.js
webpack.config.devtools.js

This is my final pass on the mochitest infrastructure. It should actually work! This implements running them locally and on try. Locally it downloads an artifact build of Firefox and you should be up an running in ~10 min, and future builds should be almost instantaneous. For debugging you'll probably want to cd into the Firefox directory itself and use mochitests like normal, not through `npm run mochitests`. On CI, it runs them in a pre-built docker container.
This pulls over @jasonLaster's great work from bug [1294686](https://bugzilla.mozilla.org/show_bug.cgi?id=1294686) because we need to actually commit the mochitests here. We still need to land a few bits in that bug to make these run (modifying other `moz.build`s etc), but the `head.js` and a simple test was copied into here. It …

Add mochitest infrastructure

---

bin/download-firefox-artifact
bin/prepare-mochitests-dev

* `download-firefox-artifact` 
* checks for the `hg` command using `command -v` which I believe is the recommended style.  Offers the homebrew command to install mercurial.
* checks that `hg clone` exits successfully for any reason, otherwise the `cd $FIREFOX_PATH` fails and the script continues to write a mozconfig file
* `prepare-mochitests-dev`
* checks that the download command exited successfully before continuing 
My bash scripting is really rusty :shipit:

check for hg command and successful exit of it

---

public/js/components/Editor.js

A few more code paths came up while testing. The breakpoint won't show if a source text hasn't been loaded yet, because it'll try to added the breakpoint icons to the editor while showing "Loading...", and then it won't re-add them when the real text appears. This is because we've optimized the breakpoints so that they only touch the editor when needed (they don't always re-add themselves).
Also if you close all the tabs and open them the `isSourceForFrame` errors of paused, so that's fixed.

Make editor handle edge cases better: only render breakpoints when text isn't loading

---

public/js/components/App.css
public/js/components/App.js
public/js/components/Autocomplete.css
public/js/components/Editor.css
public/js/components/Editor.js
public/js/components/SourceFooter.js

I made these changes a little quickly, so I'm open to a better way. This always renders the editor in the background, and renders everything else "above" it. The nice thing (I think) is that now the source header (and eventually the footer) is always rendered which I think makes it look more consistent.
This is required so that we only ever create 1 CodeMirror instance, and it makes our `Editor` component more reliable because on the initial render the `this.editor` instance is null (it hasn't been mounted yet). Not all renders are "updates" so `this.editor` will always reliably be there, so breakpoints will always show up, etc.

Always render editor so only 1 CodeMirror instance is created

---

config/config.js

It's dangerous to pull in the local config when targeting the Firefox panel, as you most likely have development prefs on.

Never merge in local config when targeting the Firefox panel

---

public/js/components/App.js

Right now we are bundling in the theme CSS and we definitely shouldn't be doing that. We need to let the toolbox apply the themes for us.

Do not include any theme CSS when compiling for the panel

---

webpack.config.devtools.js

React and CodeMirror are the two modules I really wanted to share with mozilla-central. The rest of the libraries are smaller and not required as much for interop, so I'm not as concerned about them. This reduces the size of our bundle from 2.3MB to 1.5MB (excluding both react and codemirror), and makes sure we are compatible with the rest of devtools.
This depends on [bug 1301147](https://bugzilla.mozilla.org/show_bug.cgi?id=1301147) landing before we can merge.

Use local React when in panel

---

public/js/test/mochitest/browser_dbg-editor-select.js
public/js/test/mochitest/head.js

Cleaned up an *older* test with some of the new helpers
+ introduce invokeInTab
+ add some helper functions
+ remove selectors
it might be easier to look at the commit as i needed to include another commit for the work

Cleanup editor-select test

---

public/js/components/Editor.js
public/js/utils/source-editor.js
webpack.config.devtools.js

This will pass once [bug 1295213](https://bugzilla.mozilla.org/show_bug.cgi?id=1295213) lands. All tests currently still pass, which is great. From here we could play with enabling code search, maybe?
Hoping to land that bug today, or at the latest tomorrow. Should have this before enabling it on nightly tomorrow.

Use CodeMirror from mozilla-central when in panel

---

public/js/utils/source-map.js

This fixes the leak problem for mochitests. I'm not sure why the worker doesn't die with the page, but maybe creating a worker in a chrome context is different somehow.

Only start sourcemap worker if enabled (fixes memory leak in panel)

---

public/js/components/Breakpoints.css
public/js/components/Breakpoints.js
public/js/utils/source-map.js

This changes the breakpoint list to show filename and line as "foo.js: 5" instead of "foo.js5". It also fixed a margin issue with the "no breakpoints" message; there was a big margin on the bottom of it. The HTML/CSS has been simplified too so that the whole area is a clickable breakpoint item (previously, only the file/line was).
There's a new proposal in here: in order to simplify the markup and CSS, I wanted see what it would be like to avoid flexbox for this small thing, and it works pretty well. The only hard-ish part was the paused icon, and personally I think it would be better if we just highlighted the breakpoint:
(The background color could be whatever)
I'm not sure of the benefit of an icon here, as it's not a button or anything. What do you all think?
I can revert some of this …

breakpoint list formatting tweaks

---

public/js/components/Editor.js
public/js/main.js
public/js/utils/source-editor.js
public/js/utils/source-map.js

This should fix all our testing problems. The editor is properly cleaned up (required because the mozilla-central needs to do some cleanup or else it will leak) and the sourcemap worker is terminated. We expose a new `destroy` method which is called from the panel.

Propery clean up the editor and sourcemap worker on shutdown

---

public/js/components/Autocomplete.js

With this change the first item in the search list will always be selected such that if you only have one file matching your query you can open it by hitting enter instead of navigating to it first.
I added an `INITIAL_SELECTED_INDEX` const to handle the two locations where the initial selected index needs to be set.  Though it felt like it might be overkill given the situation the default param isn't really necessary for this to work properly as the other value will be changed as soon as there is typing activity.
Multiple items:
Only one item:

default to selecting the first item in the search list

---

docs/mochitests.md

This adds instructions for Windows users to set up their mochitest environment and running their tests.
@jasonLaster this was what I was talking about.

add mochitest instructions for windows users

---

bin/make-firefox-bundle

If you don’t have web installed globally this script fails, this change uses the local webpack location.

uses the local install of webpack

---

public/js/components/SourceFooter.js

Right now we should the pretty-print button even though it doesn't work. It depends on sourcemaps being enabled. Let's hide it for now.

Do not show source footer is no features are enabled

---

public/js/test/mochitest/browser_dbg-console.js

The console test was 404ing because it wasn't using the right example page. Also, you don't need to wait on any sources if you're not going to actually test them. You only need to list ones you care about.

Fix console test

---

public/js/test/mochitest/browser_dbg-navigation.js
public/js/test/mochitest/head.js

This will close #646. Adds a few assertions to the navigation test to make sure the selected source is correct after reloads.

Add test for making sure selected source persists across reloads

---

bin/download-firefox-artifact
bin/make-firefox-bundle
bin/prepare-mochitests-dev
docs/mochitests.md

There are a few ways we could improve the scripts, but the biggest pain right now is `prepare-mochitests-dev` doesn't actually make sure everything is up-to-date. If will fail to update Firefox after the first run because `hg pull` will fail because there are local changes. This cleans up the repo to make sure there are no local changes.

Make `download-firefox-artifact` properly clean up so it can update Firefox

---

docs/remotely-debuggable-browsers.md

add a table of contents to the remote debuggable targets doc

---

bin/download-firefox-artifact

When the firefox directory didn’t exist the `cd` command in FIREFOX_PATH would fail.  However we do want the absolute path so we reset the variable after we check the directory does exist.

fix download firefox artifact script

---

package.json

Feel free to close this PR in case we don't want to use it. I tried it out and it is not restrictive to developers from what I see.
It is funny because for whatever reason my master branch already has a lot of linting errors.
So I had to use
```
git push origin --no-verify
```
to bypass the hooks.
It allows you to bypass the hooks if you want to.

add husky (#569)

---

config/development.json
public/js/components/App.css
public/js/components/App.js
public/js/components/Editor.css
public/js/components/Editor.js
public/js/components/SourceFooter.css
public/js/components/SourceFooter.js
public/js/utils/source-editor.js

This reverts commit 10902f9c41df0451a2d7a4bca81e79038548ee2c.
This is needed because CSS changes are still being applied even when the feature is off. This needs to bake a little more before we should merge it in. Right now I cut releases off master so it needs to be in a production-ready state.

Revert "Add search input"

---

circle.yml

This will ping us in #devtools-html when master fails or succeeds. 
It's helpful if we remove the protected branch.

Add circle master success/fail notifications

---

package.json

Fixes #763 
This sets a minimum node version. I'm personally not sure if 5 is the minimum, we might be at 4.x http://node.green/#let.
* adds engine to check for outer installs
* add check to start because this is where most people will hit it
* removes prepublish as i don't think we use that.

Check Node version

---

package.json

This change will allow us to try out using greenkeeper and not be annoyed by PRs for modules we cannot update.
Here are the dependencies we currently have: (checked the ones I thought we wanted to pin, might have missed some)
> we should remove `tcomb`, will do in a separate PR
I didn't do anything on the `devDependencies` as I think getting those PRs could be useful.

adds greenkeeper attribute with ignore to package.json

---

docs/mochitests.md

Accidentally removed this entirely when removing the `hg purge` requirement.

Add mercurial back to requirements for mochitests

---

.storybook/config.js
.storybook/webpack.config.js
CONTRIBUTING.md
docs/local-development.md
package.json

I followed the `getstorybook` steps to see if there was a better way to install storybook, ofcourse now that i did, i learned that it was just an install tool and i had been tricked into upgrading. 
That's not all bad:
* we got access to `build-storybook` which will be great for the website
* we can use their awesome suite of plugins
* we're up to date
I think at this point it would make more sense to encourage people to install storybook globally and run it that way. Then it's not a flakey step in our install process.

Upgrade Storybook

---

bin/development-server.js
index.html
package.json

This removes the index.html styles link as we now have a different index in the panel, which is fine because they're doing different things.
I've heard from contributors that the error is confusing and it'd be nice to smooth out the getting started experience

Remove styles link

---

public/js/actions/navigation.js
public/js/actions/sources.js
public/js/components/Editor.js
public/js/utils/source-documents.js
public/js/utils/source-editor.js
public/js/utils/source-map-worker.js
public/js/utils/source-map.js

I'm sharing this version early because this is the core logic as I see it now. It does some things well, it doesn't try to do others :)
Things it does:
* keep a list of docs per source
* swaps between them so big sources are only loaded once
* keeps scroll position
* handles breakpoints (probably re-renders every time)
Things it doesn't do:
* doesn't delete docs when a tab is closed or navigation - handling closed tabs is easier than navigation as the state is in the component. I might move the state somewhere else to handle navigation, we'll see. 
* doesn't handle loading - i'm planning on adding a spinner
* doesn't handle errors - i'm working on the assumption that errors are permanent, a.k.a the source text is not re-fetched and can become valid. 
Things it might do:
* it probably …

Add codemirror documents

---

CONTRIBUTING.md
config/development.json
public/js/clients/firefox.js
public/js/clients/index.js
public/js/main.js

I was talking with a contributor and the question of getting setup with chrome came up and I found it was very complicated. He ran into two problems:
1. Firefox had to be on
2. enabling local.json was not intuitive
Neither of these things is a deal breaker, but for many people there's already going on when getting started and any extra steps can be intimidating.
This fixes that by enabling chrome by default and fixing the firefox connection so that it handles not connecting gracefully.
I also sped up the timeouts so that the toolbox shows pretty fast.

Enable chrome locally

---

public/js/components/SourceTabs.css
public/js/components/SourceTabs.js

Associated Issue: #791
* show the close button only when hovering over tab
* highlight close button when hovering over it

Polish tab close button UX

---

CONTRIBUTING.md

Associated Issue: #764 
* Add note about current limitations of Node.js as a debugging target

Add note about current limitations of Node.js as a debugging target

---

public/js/test/mochitest/browser_dbg-editor-select.js

This makes me a little sad, but for some reason this test runs for too long on linux debug frequently. Linux debug is a very slow machine, so it's not too surprising, but this test is not huge so I'd like to figure out what is so slow. I'm sure we'll see this in other tests eventually too and hopefully we can cross-check what these tests are doing and find a pattern of something we do a lot. Maybe pausing is slow. I know that currently we convert the whole pause packet to immutable and avoiding that will speed it up a lot, but I'd be surprised if there was *this* big of a perf hit.

Allow longer timeout for browser_dbg-editor-select.js

---

.flowconfig
public/js/utils/create-store.js
public/js/utils/source.js
public/js/utils/sources-tree.js
public/js/utils/text.js

* add two `module.name_mapper` options to the flowconfig that allows for flow to find most of the devtools modules and the Services module shim
* add flow typing support to a couple of utils files
* ended up rewriting the `getURL` function to make it clearer and simpler.  always returns an object now and we check for an empty path before continuing

add more flow typing support to some utils

---

public/js/components/SourceTabs.js

* fix a missing import caused by a bad rebase.

Fix missing import of `Svg` in `SourceTabs.js`.

---

package.json

We've seen some weird issues with eslint today, and I figured it would be good to be on the latest version to make sure we're not hitting any bugs. I hit a weird bug complaining about the recent flow type changes, and I have no idea why others aren't seeing it. Updating to 3.6.0 made it go away.

Update eslint to 3.6.0

---

public/js/components/Sources.css

This prevents the keyboard shortcut label in the source header from wrapping and overflowing on the list of sources below it when the sidebar is small.
With this simple CSS change, resizing the sidebar now looks like this:

Prevent source header info from wrapping

---

public/js/components/App.js

Associated Issue: #823 
* adjust the initial widths of the sidebars to give the editor more room
I tried to make the initial widths work out so that the editor is 60% of the content and the sidebars are 20% a piece.

Adjust Splitbox initial widths

---

public/js/actions/breakpoints.js
public/js/clients/firefox/commands.js
public/js/lib/devtools-sham/shared/client/main.js

After [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1305079) lands, we'll have the ability to turn off breakpoint sliding when setting breakpoints. We want to do this when setting breakpoint on sourcemapped sources (this is how the old debugger behaved) because sliding is a "nice to have" but ridiculously infuriating when it goes wrong (see [bug 1230345](https://bugzilla.mozilla.org/show_bug.cgi?id=1230345)). And sliding is almost always wrong with sourcemaps.
This is because the engine does sliding on the generated source, and then we'll sourcemap the final location back. But who knows where that maps to. I've seen cases in Firefox/Chrome where the breakpoint literally slides **up**.
We can't merge this until that bug lands, but that should be tomorrow.

Disable breakpoint sliding on sourcemapped sources

---

public/js/components/App.css
public/js/lib/themes/variables.css

The transparent overlay of the search box isn't working in the Firefox panel on master because this CSS var doesn't exist in the themes, we added it. We shouldn't added anything to `variables.css` that's also not added on mozilla-central.

Isolate the CSS var --theme-search-overlays-semitransparent so it's available in the toolbox

---

public/js/clients/chrome.js

Associated Issue: #855 
* change the require call to get the whole export instead of attempting to destructure which caused the error

Fix `networkRequest` is not a function error in chrome client

---

package.json
public/js/utils/sources-tree.js

* adds `npm run test` to the `prepush` script
* replaces `[].includes` with `_.includes` in sources-tree because node < 6 does not support `[].includes`. As a side-note, we run the unit tests on CI with node 6.3, so we don't run into this issue there.

Run unit tests on prepush

---

public/js/components/Accordion.css
public/js/components/Breakpoints.css
public/js/components/Frames.css
public/js/components/RightSidebar.css
public/js/components/SourceFooter.css
public/js/components/Sources.css

Associated Issue: #700 
Very small updates to the right sidebar so everything is left-aligned, including:
* Aligning debugger actions with accordion
* Aligning breakpoints and frames with their accordion headers
* Using @jasonLaster's self-proclaimed ugly hack to fix the splitter not extending to bottom of right pane
* Declaration of ```12px``` to fix the ```<message-box>``` styling issue in which right-pane elements sometimes appeared 1px larger than their headers
One thing this PR _doesn't_ do (but I think it would be nice if it did) is change the event scopes to no longer be bolded (but it seemed like that was library code from FF that I didn't want to touch).

Vertical Rhythm, #700

---

bin/firefox-driver.js

Associated Issue: #874
* update the minimist options to use an array for the boolean values
* https://github.com/substack/minimist#var-argv--parseargsargs-opts
* use the correct pref `devtools.debugger.remote-websocket` for enabling the remote websocket 
* https://dxr.mozilla.org/mozilla-central/source/devtools/client/devtools-startup.js#161
* also some odd white space that crept in

fix up args and prefs for firefox-driver

---

public/js/test/mochitest/browser_dbg-breaking.js
public/js/test/mochitest/browser_dbg-call-stack.js
public/js/test/mochitest/browser_dbg-debugger-buttons.js
public/js/test/mochitest/browser_dbg-editor-gutter.js
public/js/test/mochitest/browser_dbg-editor-highlight.js
public/js/test/mochitest/browser_dbg-editor-mode.js
public/js/test/mochitest/browser_dbg-editor-select.js
public/js/test/mochitest/browser_dbg-iframes.js
public/js/test/mochitest/browser_dbg-pause-exceptions.js
public/js/test/mochitest/browser_dbg_keyboard-shortcuts.js
public/js/test/mochitest/head.js

Now that the toolbox doesn't signal that the debugger is ready until all sources exist, we don't need to wait for specific sources any more. There were some tests that were listing them unnecessarily; you *only* needed to pass them to `initDebugger` if you explicitly used them afterwards. If you call `waitForPaused` first and wait for it to pause, you don't need to list the source; you're not using it until it exists anyway.
But this is a little simpler. We cannot simplify `navigate` or `reload` because that is another API entirely, and only signifies that the page is changing. There we will need a way to know when it is "completed", and you specify that by giving it any sources you need afterwards. Again, you do *not* need to list anything if you do not *directly* use a source. If you're …

Simplify initDebugger mochitest helper

---

public/js/components/Editor.js
public/js/components/SourceFooter.js

Fixes: #869
Disables the keyboard shortcut that triggered the search UI in the firefox panel.

Disable search key

---

package.json
public/js/test/node-unit-tests.js

This switches the default cli mocha reporter to *dot*. The main advantage is that running `git push` will no longer result in a wall of output.

Add mocha dot reporter

---

public/js/utils/sources-tree.js
public/js/utils/tests/sources-tree.js

Associated Issue: #743
* Expanded the file sort ability.
* Added testing coverage for sorts.
* Slightly reworded variables in the `addToTree()`

Sort file tree by index -> folders -> file. Fixes #743

---

public/js/components/Breakpoints.css
public/js/components/Editor.css
public/js/components/Frames.css
public/js/components/RightSidebar.css
public/js/components/SourceFooter.css
public/js/components/SourceTabs.css
public/js/components/Sources.css

Associated Issue: #841 
* add `user-select: none` to various parts of the debugger so selection/ctrl+a only gets the things we expect (note, bare `user-select` seems to not work so adding the vendor prefixes for full support.)

Add `user-select: none` to several parts of the debugger.

---

public/js/utils/log.js
public/js/utils/utils.js

The `devtoolsRequire` problem in the source map worker was caused by #860 because it loads the `utils` file in `source.js` now, which tries to load in our config system... You can't load the config system in the worker, nothing is set up. The only thing that needs the config system in `utils` is the log function, so I extracted it out. I looked through our codebase and couldn't even find any uses of it though.
Not sure if there's a better solution.

Extract `log` into its own module to make `utils` avoid config dependency

---

public/js/components/Autocomplete.css

* disable selection for the autocomplete result list
I had forgotten to include this in the previous PR and we didn't remember it in the issue either.

Disable selections for the autocomplete result list.

---

public/js/components/Breakpoints.css
public/js/lib/codemirror-mozilla.css

Associated Issue: #871 
* `.breakpoints-list .breakpoint.paused` will use `--breakpoint-active-color` to highlight
* Adds `--breakpoint-active-color-hover` variable, and uses this when the user hovers over a `.breakpoints-list .breakpoint.paused`
* Also switches `.breakpoints-list .breakpoint` from using`margin` and `padding` to just `padding` so that the highlight color wraps the entire breakpoint without awkward whitespace
**Awkward whitespace issue is more prominent when we turn the breakpoint blue**
-![screen shot 2016-10-09 at 3 49 09 pm](https://cloud.githubusercontent.com/assets/1445834/19223204/254c4374-8e38-11e6-9519-22e849187d20.png)
**Hover color**

Align breakpoint-list highlight color with codemirror

---

public/js/lib/codemirror-mozilla.css

Associated issue: #871 
In https://github.com/devtools-html/debugger.html/pull/907 I accidentally overrode `--breakpoint-active-color` in dark mode instead of adding `--breakpoint-active-color-hover`. This fixes the error.

Fix breakpoint var name typo on dark mode

---

public/js/components/Breakpoints.css
public/js/components/Breakpoints.js

Turns out that using a `border` was easier than a `::before` element. Its `height` wasn't cooperating at `100%`, and I wasn't sure if setting something like `height: 95%` would be reliable. A `border`, on the other hand, seems to be rendering correctly.
Associated Issue: #871 
* Resets the background color of `.breakpoint.paused` to its state before 6441b2 
* Adds a transparent `border-left` to `.breakpoint`s, which turns `--breakpoint-active-color` on `.paused`
* Adjusts margins and padding to compensate for the border, including adding a new `.breakpoint-checkbox` class to the `<input>` and removing its `margin-left`
**Hover**

Call out active breakpoint with border

---

public/js/components/EditorSearchBar.js

* use `CmdOrCtrl` rather than just `Cmd` for shortcut, to make it compatible with linux/windows

Fix the key shortcut in code search to be compatible with linux/windows.

---

public/js/components/Editor.js

Since we implemented CodeMirror documents, we may not correctly clear the debug line, so you may end up seeing multiple green debug lines. The problem is that it cleared if after setting the new source text, so it wasn't properly clearing it on the previous "document", so loading that document again (when switching) back will still show the previous line.
The fix is pretty simple: make sure to clear it before we update the source text.

Make sure to clear the debug line in the correct CodeMirror document

---

public/js/components/Editor.css

Associated Issue: #875
* Fixed breakpoint gutter height
* Realigned breakpoint arrow svg

Fix breakpoint arrow and gutter heights

---

package.json

the `babel` package in 6.x currently doesn't do anything, so you should be seeing the deprecation message from `babel` (noticed this from seeing https://github.com/yarnpkg/yarn/issues/638)
```
warning babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
```
As an aside I don't `babel-preset-es2015` or `babel-preset-stage-0` being used atm? (and maybe give 
https://github.com/babel/babel-preset-env a shot)

remove `babel` dependency since it's moved to `babel-cli`

---

public/js/components/Scopes.js
public/js/lib/devtools/client/shared/components/reps/window.js

Associated Issue: #884 
* Window rep will display either `"Window"` or `"Global"` depending on whether its preview has a truthy `isGlobal` property or not
* Top-level Window will override its preview to `{ kind: "Window", isGlobal: true }`
This feels like a hack to me, and I'm submitting this PR more to start a discussion than because I'm confident in its ability to fix the issue. I don't understand the code path that renders the reps very well, but this is what I was able to figure out.
The problem that I found is that the top-level Window — the one we want to say `Global` — has a `preview` with `{ kind: "ObjectWithURL" }` rather than `{ kind: "Window" }`. But, apparently, the `view` property in `e` is correctly marked as `{ kind: "Window" }`. I have no idea why it is, or where the …

Display Window or Global on Window class reps

---

public/js/components/Editor.js

Based on the [bug 1308510](https://bugzilla.mozilla.org/show_bug.cgi?id=1308510)
We decide to use non-experimental WebAssembly format in devtools. However formal grammar (and highlight rules) are not defined for it yet. Proposing to disable the wasm mode in the devtools editor.

Disable highlight for non-experimental WebAssembly format.

---

CONTRIBUTING.md

Associated Issue: #877 
* remove references to the defunct `first-timers-only` label in favor of the `difficulty:easy` label

Update documentation to refer new contributors to `difficulty:easy` labeled issues

---

.gitignore
packages/devtools-local-toolbox/public/js/clients/chrome/commands.js
packages/devtools-local-toolbox/public/js/clients/firefox/commands.js
public/js/actions/breakpoints.js
public/js/actions/types.js
public/js/reducers/breakpoints.js
public/js/types.js

Associated Issue: #547
* Implement the toggleAllBreakpoint feature for Firefox and Chrome
* Minor changes on `actions/breakpoints.js`
* Rework of the Firefox `commands.js` file to keep disabled breakpoints in memory, used when enabling all breakpoints again

547 toggle breakpoint preserve state  rework

---

packages/devtools-config/configs/development.json
packages/devtools-config/configs/firefox-panel.json
public/js/actions/sources.js
public/js/components/SourceFooter.js
public/js/main.js
public/js/reducers/sources.js
public/js/utils/pretty-print-worker.js
public/js/utils/pretty-print.js
public/js/utils/source-map-worker.js

This is a simple implementation of pretty-printing.
I intentionally simplified some of the logic. We should take this in steps, because there are some very weird situations with pretty-printing: if you pretty-print a generated source that has a sourcemap, do you "replace" its sourcemap? That would make sense, but then what happens to the old "original" source? In the old debugger this is temporary, and un-pretty-printing it would restore the old sourcemap. Various things like that.
Right now this only allows pretty-printing an unsourcemapped source. If it has a sourcemap, it replaces it.
Because sourcemaps work, all breakpoint/stepping/etc related things should "just work".

Fix pretty-printing & enable it

---

packages/devtools-local-toolbox/bin/development-server.js

Associated Issue: #936 (sort of)
* while `npm install` still fails when run without `npm run preinstall` first, this fixes a config error by loading the right file. There may still be more work to do to get the issue closed and further documentation to write to improve things in regards to the mono-repo workflow, but this should at least get things working for most.

Fix the dev server config loading issue

---

packages/devtools-local-toolbox/bin/development-server.js

Associated Issue: no known associated issue number 🙃
* Changes the ```const { foo } = require(..)``` syntax to ```const foo = require(...).foo``` in ```development-server.js```
```bash
> debugger.html@0.0.5 test /Users/hholmes/code/debugger.html
> node public/js/test/node-unit-tests.js
/Users/hholmes/code/debugger.html/public/js/test/node-unit-tests.js:11
const { registerConfig } = require("../../../packages/devtools-config/registerConfig");
^
SyntaxError: Unexpected token {
```

Make development server work for node v5

---

public/js/test/mochitest/browser.ini

This change happened on mozilla-central but should have happened here. Linux32 debug is unable to run out tests, as its so slow even the smallest debugger test because intermittent because it runs so slowly. We ran into this on the old debugger and disabled those as well, so this isn't specific to the new debugger. We're still running the tests on linue32 opt, and linux64 debug and opt.

Disable mochitests on linux32 debug

---

public/js/components/Editor.css
public/js/components/ObjectInspector.css
public/js/components/RightSidebar.css
public/js/components/SourceFooter.css
public/js/components/SourceTabs.css
public/js/components/Sources.css
public/js/components/utils/ManagedTree.css

Associated Issue: #867 
1. I chose to use html[dir="rtl"] as an indicator for RTL. The :dir pseudo-class is only supported in Firefox, so I wasn't sure if it's a good choice. I have a feeling you're going to tell me to go with :dir :-)
2. I explicitly separated directional properties to html:not([dir="rtl"]) for (a) declarative style (b) avoid property reset under the RTL rule. I felt it was too verbose, but better than the alternative.
e.g. 
```
.some-class {
width: 10px;
margin-left: 8px;
}
```
becomes:
```
.some-class {
width: 10px;
}
html:not([dir="rtl"]) .some-class {
margin-left: 8px;
}
html[dir="rtl"] .some-class {
margin-right: 8px;
}
```
3. I want to raise my concern about the ability to maintain this. Maybe unit test coverage can help, but I would suggest some automatic …

Polish RTL

---

.flowconfig
public/js/utils/source.js

Associated Issue: #942
* remove the options section from the flowconfig
* use the shared Source type, remove TODO

update flowconfig, use shared Source type

---

public/js/components/App.js
public/js/components/SourceSearch.css
public/js/components/SourceSearch.js

* Move Source Search to its own component
* I'd appreciate any review on this initial part
* [in progress] I'm working on saving the last thing you searched for in the input
* For example, you search for `inc` and select the first item, it turns out to be wrong, so you search again but now you have to enter your search terms all over again.  I would like to re-run the last search but leave the text selected so you can easily start typing something else.
* [in progress] allow for tabbing to the next item when the search results are open
Not yet.

move source search out of app into a separate component [WIP]

---

package.json
packages/devtools-local-toolbox/package.json

We were seeing a couple of issues recently related git cloning and installing the project. #936 #954 #946
This fixes (i hope) the last issue, where `npm install devtools-local-toolbox` failed due to bin not being exported.
Here's a quick summary for those interested. NPM 3 runs the top level lifecycle hooks after installing dependencies [here](https://github.com/npm/npm/blob/master/lib/install.js#L263). This requires us to a) publish packages, b) have these packages be installable. 
For the record, yarn runs preinstall before installing dependencies [here](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/install.js#L709). Yarn's code is also significantly easier to follow if you ask me :)

Fix fresh NPM install

---

.flowconfig
packages/devtools-config/configs/development.json
packages/devtools-local-toolbox/public/js/clients/firefox/commands.js
packages/devtools-sham-modules/shared/client/main.js
public/js/actions/breakpoints.js
public/js/actions/types.js
public/js/components/Editor.css
public/js/components/Editor.js
public/js/components/EditorBreakpoint.js
public/js/reducers/breakpoints.js

Associated Issue: #101
I paired with Giorgio @ppold on this feature last night. This PR is an initial conditional breakpoints implementation, it satisfies the basic requirements and will be polished in subsequent PRs.
User steps:
* click to add a breakpoint
* cmd+click to edit breakpoint
* add a condition
* enter to save
Next steps:
* clicking on the breakpoint while the panel is open should close the panel and remove the breakpoint
* the panel input should be focused when the panel is opened
* style the panel. Perhaps move the description to input placeholder text (shorten dramatically)
* perhaps add a close button
* perhaps update the breakpoint in the breakpoint list to either show it's a conditional or show the condition. Chrome does not do anything here...

Add conditional breakpoints

---

packages/devtools-local-toolbox/webpack.config.devtools.js
packages/devtools-modules/index.js
public/js/test/mochitest/.eslintrc
public/js/test/mochitest/browser.ini
public/js/test/mochitest/browser_dbg-scopes.js
public/js/test/mochitest/head.js

This fixes an issue I was seeing expanding the scope pane. It also adds some tests to ensure that the Scopes and object properties load correctly. We likely want some other integration style tests where [getScopes](https://github.com/devtools-html/debugger.html/blob/master/public/js/components/Scopes.js#L75) is concerned.

Fix scopes

---

public/js/components/Frames.css
public/js/components/Frames.js

Associated Issue: https://github.com/devtools-html/debugger.html/issues/961
* Changed Frames to a React Class
* Refactored logic to prior to the return
* Logic consists of conditional statement depending on number of frames
* Added expand/collapse rows button
For best testing, use breakpoint on line 52 of todo MVC app with a refresh. Lots of frames there.
* [ X ] passes `npm test`

Call stack collapse frames

---

public/js/components/Breakpoints.js

Associated Issue: #940 
* Added an `onClick` to `breakpoint-checkbox` that will only stop propagation of the click to its surrounding div. This allows the `handleCheckbox` to be called without also calling the `selectBreakpoint` call of its parent div.

Prevent breakpoint checkbox from selecting a breakpoint

---

public/images/Svg.js
public/images/sad-face.svg
public/js/components/EditorSearchBar.js

Associated Issue: #967 
* When code search returns 0 results, this PR shows a "no results" summary and changes from magnifying glass to sad smiley.
* Also I added an extra check for query, to see if it's empty. If it is empty, we don't show a sad smiley. Would like to hear your thoughts on this, since this was not mentioned in the issue. Hope you guys don't mind about this :)
* [ x] passes `npm test`
* [ x] passes `npm run lint`

Show "no results" label and sad face for no results

---

public/js/actions/breakpoints.js
public/js/actions/sources.js
public/js/actions/types.js

* moved `ThunkArgs` into `actions/types` and typed the sources action
* removed the unused `blackbox` function from the sources action module

add flow typing to sources actions

---

public/js/components/App.css
public/js/components/Dropdown.css
public/js/components/Dropdown.js
public/js/components/SourceTabs.css
public/js/components/SourceTabs.js
public/js/reducers/sources.js

Fixes some of the styling issues we've seen with the sources dropdown. @wldcordeiro this should address the evil three dots and other related things.
This also pulls in the great work @jacobjzhang did with refactoring the dropdowns.
Some of the styling issues were with:
* the center pane scrolling when a source tab was too big for the header
* a source tab not shrinking to the width of the header
* the subsetting button not adjusting to the width of the header
* the dropdown font height, and text overflowing... this is still not a great dropdown component (even though it is now extracted) there are clipping issues in narrow widths and in general we should probably consider a more mature library, but it gets the job done for now.

Fixes layout issues with the sources dropdown

---

public/js/components/Autocomplete.css

Associated Issue: #780 
* add color vars for backgrounds/colors to make the input match theme style.

Add theme coloring to the input field for file search

---

public/js/components/EditorSearchBar.css

Associated Issue: #988 (part of)
* add backgrounds to the code search so it matches the theme.

Color the background of code search input to match the theme.

---

packages/devtools-local-toolbox/public/js/components/Root.css

Small fix to make the chrome scrollbars in chrome consistent with the panel
I double checked to make sure the codemirror filler style was okay in the panel.
**Why does this matter?** 
1. having a nice dev environment will make it easier to spot other visual inconsistencies
2. the standalone app will be electron, which will need this cleanup

(dark-theme) Cleanup the scrollbar on chrome

---

public/js/components/Editor.css

* adjust the height of the editor to properly account for source footer, move rule down file to cascade properly

Adjust the editor height for when the code search is visible so the scrollbar doesn't sit under the footer

---

public/js/lib/codemirror-mozilla.css

Associated Issue: #1012
* Added background for the breakpoint line in dark theme
Before:
After:

Fix #1012: dark theme bg for breakpoint line added

---

public/js/components/Breakpoints.css
public/js/components/Editor.css
public/js/lib/codemirror-mozilla.css

Associated Issue: #1010, also follow-up from #1012
As a caveat to these changes: I'm not _in love_ with the hover states in the breakpoints pane. However, I still think they're improvements and I think the work necessary to make them 💫 great 🌟 requires m-c changes that should be done in follow-ups.
* Update ```--breakpoint-active-color-hover``` for dark theme to be ```--breakpoint-active-color``` with slightly more opacity
* Make the hover color for the breakpoints in the sidebar less intense, but _more_ intense in light theme
* Recenter the close button (before it was slightly too close to the top)
Before:
After:
Before (hover state):
After (hover state):
Before (hover state, light theme):
After (hover state, light theme):

(dark theme+light theme) Fix breakpoint gutter color, breakpoint hover color, re-center close button

---

circle.yml

* adds `~/downloads` as a cache directory for circleci (does not use that directory yet)
* change 2
This PR has really no effect on anything just yet, it creates a custom cache directory.  Which you can learn more about [here](https://circleci.com/docs/how-cache-works/)  I'm working to cache more of what we download in Circle and I believe we are losing the downloads directory because it only exists in my branch.  
Here's the rest of my branch work: https://github.com/clarkbw/debugger.html/tree/fast-circleci

create a downloads cache directory in circleci

---

public/js/components/Dropdown.js

Associated Issue: #1015 
* Replace the existing sources overflow button with the guillemet »
**Before:**
**After:**

Update sources overflow button for consistent styling

---

public/js/components/Dropdown.css

Associated Issue: #1008
* Changes hardcoded white background in dark theme theme for the tab overflow
* Adds transitions to background color changes
* Adds drop-shadow on dropdown
* Removes per-```<li>``` background color changes
Before:
After, including hover state:
After, in light theme, with hover state:

Fix #1008: Change hardcoded white value in tab overflow

---

CONTRIBUTING.md

Associated Issue: #1042
* Updated links to devtools config in CONTRIBUTING.md
* Updated link to README.md in CONTRIBUTING.md

Fix broken links to configuration and README, fixes #1042

---

public/js/components/Editor.js

A few things are going on here. For some reason, redux always rerenders a connected component no matter what if you accept the `props` argument. Even if the state you return is the same as before, it'll rerender. We don't use the `props` arg here, so we can just remove it.
For some reason, in React 0.14.7, the editor was rerendering but `componentWillReceiveProps` wasn't being called. We do most of our heavy work in there, so it was skipping it. In React 15, that lifecycle method is always called, which seems like the correct behavior. I haven't been able to reduce this into a simple test case, but let's go ahead and clean this code up which I think will allow us to run against React 15. I'd like to understand this more at some point.

Optimize editor rendering by removing props arg in redux state mapping function

---

public/js/components/SourceTabs.css

There's no reason we should have a max tab width in my opinion. The current CSS is broken, leading to this when it's too wide:
For now let's just remove this. We can think of how to solve this better later.

Remove max tab width

---

public/js/components/Frames.js

I didn't know this, but prop warnings actually fail on try, which is kinda cool. I think it's an accident; I think the test harness catches it just because it has the word "failed" in the warning message.
Anyway, on the last push to try, it was failing because of this. `selectedFrame` isn't required; we render the frames component without any frames.

Make `selectedFrame` prop of Frames not required

---

public/js/components/EditorSearchBar.js

Associated Issue: #1041
* add query const to render method so that we only apply the "empty" className if the query is not empty, thereby only changing the cursor to orange if empty search result and NOT when search input is first visible.
* [ X] passes `npm test`
* [ X] passes `npm run lint`

#1041: File Search - blinking orange cursor

---

public/js/components/SourceSearch.js

Fixes #1044 - so that both pretty sources and sources w/o a url are excluded
as a side note - I was surprised to learn while debugging this that in the backbone example jquery and underscore have new source events with the introduction type Function and scriptSource. Didn't expect that...
@jacobjzhang mind double checking my fix here.

Fix source search filter

---

public/js/components/Frames.css
public/js/components/Frames.js
public/js/test/mochitest/browser_dbg-call-stack.js

Helen was asking how to detect when a frame is "focused", and I discovered that all we have to do is add a "tabindex" to it to allow it to be focus-able. This is allows us to style it with `li:focus` and everything just works. When you click on a frame, it'll be a bold blue, but when you click away it'll change to a more subtle color.
We should able to use this technique in the tree component as well. Right now it uses a hidden button to allow each item to be focus-able, but it just needs a `tabindex` property to work.
I also had to change the click event to `mouseDown` because that's when the element gets focused. Otherwise it's too easy for a call frame to be "focused" but not "selected", just by pressing the mouse down on a frame but the moving the cursor outside of it. Previously this …

Allow frames to be focus-able

---

packages/devtools-config/src/feature.js
public/js/utils/assert.js

The last Flow PR introduced two issues:
1. types to feature.js which broke `npm test` and `npm start`. I'm not sure how CI passed
2. it left out a `// @flow` comment

Fix flow statements

---

packages/devtools-local-toolbox/public/js/lib/themes/variables.css
public/js/components/App.css

Associated Issue: #994
* Changes the ```theme-faded-tab-color``` in dark theme to a slightly lighter color
* Moves the tab variables out of ```variables.css``` into ```App.css```, as there's no corresponding m-c commit to add that variable

Fix #994: Fix tab colors in dark theme

---

public/js/components/EditorSearchBar.js

Associated Issue: #968
* Created a new search function which is debounced

debounce the code search with a wait of 250ms

---

public/js/components/Accordion.css
public/js/components/Frames.css

Associated Issues: #1011, #999
* Changes accordion header hovers in dark theme
* Changes selected state color in call stack, in dark theme, to white
* Changes hover state on "Expand rows" in dark theme
Light theme:
Dark theme, call stack hover state:
Dark theme, selected stack:

Fix #1011, #999: Fix call stack and accordion headers' colors in dark theme

---

CONTRIBUTING.md
README.md

* Fix the spelling of "GitHub"

Fix the capitalization of "GitHub" in two files.

---

packages/devtools-config/configs/development.json
public/js/components/Editor.js
public/js/components/EditorSearchBar.js
public/js/main.js

Associated Issue: #1067 
* enables search, which turns on the new search bar in the panel
* update the L10N bootstrap logic so that it expects L10N to be passed in. Previously, the assumption was that L10N was a global on the window, but that was a bad assumption
* there's an associated m-c change as well that i'll link to soon

Enable search in the panel

---

public/js/components/Accordion.js
public/js/components/App.js
public/js/components/Expressions.js
public/js/components/RightSidebar.js
public/js/components/SourceSearch.js
public/js/components/Sources.js
public/js/components/SourcesTree.js
public/js/components/utils/ManagedTree.js
public/js/utils/sources-tree.js

Associated Issue: #999 
* made changes to indentation because npm run lint was reporting these as errors
@jasonLaster here's that separate PR you were requesting. I made a new branch from my master fork and npm run lint, getting the same indentation errors that I referenced in issue #999. For the record I'm running the packages `linter-eslint version 8.0.0` `linter version 1.11.18`  and `editorconfig version 2.0.1` in Atom on an Ubuntu VM. I did not touch any of settings in those packages, so that could be why `npm run lint` reported those errors in the first place. 
Let me know what questions you have.

changes because of eslint issues that npm run lint was reporting

---

public/js/components/EditorSearchBar.js

Associated Issue: #1092 
* Runs `escapeRegExp` on `query` passed to `countMatches`. Searching for something like `val(` would previously throw an error for an unterminated parenthetical in a regular expression.

Escape EditorSearchBar queries before using as RegExp

---

public/js/components/SourceSearch.css
public/js/lib/codemirror-mozilla.css
public/js/utils/source-search.js

Associated Issue: #800
* Added new search overlay for outlining matches
* Added css for styling outlines

Outline matches

---

public/js/utils/source-search.js

Associated Issue: #800
* Use Lodash's `escapeRegExp` function instead
* Improvement on work done for Issue 800

use lodash's escapeRegExp instead

---

public/debugger.properties
public/js/components/SourceTabs.js
public/js/strings.json

Associated Issue: I need to learn how to create mochitests so I can write tests for these kinds of things.
* add a context menu to the source tab
* add the close and close all tabs options to the source tab context menu
Note that there is no context menu available from the tab overflow menu.  I actually feel like there could be inline close buttons for closing those tabs in the menu and the "Close All" option can be used from anywhere else.

create a context menu for the source tabs with close and close all

---

public/js/test/mochitest/.eslintrc
public/js/test/mochitest/browser.ini
public/js/test/mochitest/browser_dbg-searching.js
public/js/test/mochitest/head.js

Associated Issue: #1067 
* Adds some mochi tests for source search. I'd like to add some unit tests later as most of this is more suited for that
* I tried really hard to get file search tests in, but for whatever reason I kept opening the content search bar and not the editor search bar. 
here's a small patch for the file search tests
```js
// Testing file search
add_task(function* () {
const dbg = yield initDebugger("doc-script-switching.html");
yield selectSource(dbg, "switching-01");
// window.dbg = dbg;
// yield pauseTest();
const el = findElementWithSelector(dbg, ".CodeMirror-line").focus();
console.log("el", el);
pressKey(dbg, "fileSearch");
type(dbg, "fun");
debugger;
});
```

Add Search tests

---

packages/devtools-local-toolbox/public/js/utils/utils.js
public/js/components/SourceSearch.js

Associated Issue: #866
* passes in the full URL when there is no path
When a URL like about:home is passed to the URL module it doesn't return a path.  The path is returned on all other parses even if you are missing the protocol.
```
> url.parse("about:home")
Url {
protocol: 'about:',
slashes: null,
auth: null,
host: 'home',
port: null,
hostname: 'home',
hash: null,
search: null,
query: null,
pathname: null,
path: null,
href: 'about:home' }
```

handle about: urls in the source search fixes #866

---

public/js/utils/source-search.js

Associated Issue: #1101
* Add regexp to ignore doing matching on whitespaces below 3

Ignore whitespaces

---

public/js/components/Frames.js
public/js/reducers/pause.js
public/js/utils/pause.js

Associated Issue: #1056 
* Consistently passes `frames` as type `Seq`, even when there are 0 frames. 
Previously, 0 frames would be stored in state as `null` and returned from the selector as `[]`. This confusion between whether `frames` is an `Array` with a `length` or a `Seq` with a `size` was part of what caused the bug resulting in #1056. https://github.com/devtools-html/debugger.html/pull/1083 fixed the buggy behavior but it left the type inconsistency, so this PR corrects that.

Consistently return Seq from getFrames

---

bin/firefox-driver.js

Associated Issue: #906 
This commit modifies the Firefox launch script to make sure the
driver gets configured and the debugging server gets initialized.

Set debugger server when launching Firefox

---

packages/devtools-local-toolbox/public/js/clients/firefox/commands.js
public/js/actions/pause.js

Associated Issue: #916 
I took a look at some of the redux work for watch expressions so that we can scope out the work we want to do to get watch expressions functional. I think this is also blocking #917. 
I found a couple of things:
1. the evaluate call needs the current frame
2. we should not eval when we aren't paused
3. we should evaluate after the store has been updated
there are some other quirks with this work that should be ironed out as well 
- for instance it might try to eval while you type
- and likely some other things as well

(WIP) fix some issues with watch expressions

---

CONTRIBUTING.md
package.json

Thought it might be useful after working on https://github.com/devtools-html/debugger.html/pull/1130 and getting a linting error.
Adds a command to run autofix with eslint
`npm run fix`

Add a fix command to autofix js linting errors

---

public/js/utils/source.js
public/js/utils/tests/source.js

Associated Issue: #1110 
* Added in a default of (index) when we have a directory.
* Added in a test to check that we get the correct name back.

Fixing tab without name.

---

public/js/components/Editor.js

Associated Issue: #1096
* Trigger focus when the breakpoint input field appears.
Thank you for the diff! That really helps a lot for me to understand the code.

js/components/Editor.js: Focus on breakpoint input

---

public/js/components/Editor.js
public/js/components/menu.css

Associated Issue: #1109 
@jasonLaster 
- Added the separator and have it automatically be loaded into context menus.
- Added CSS for the separators in the debugger context menu.

Add separators to the debugger context menu.

---

public/js/components/SourceTabs.js
public/js/utils/menu.js
public/js/utils/tests/menu.js

Associated Issue: #1139
* Added new buildMenu function and tests
* Use the buildMenu function to generate the list of menuitem that should be visible

Hide close items

---

public/js/components/ObjectInspector.js

This took a while to figure out, but the fix is easy. The problem is that if an object has already been rendered, it is cached based off the actor id, and if there is any other place in the tree where it is referenced, it will end up using the cached value. We don't want that, as that will cause the tree's depth-first-search algorithm to go into an infinite loop if there is a circular reference.
By using the path as the key value instead, we force it to recreate a new child array for each instance in the tree, which fixes the infinite recursion.

Fix possible infinite recursion in object inspector by caching based off path (fixes #1120)

---

public/js/components/Autocomplete.css

Associated Issue: #1071
* Add the word-break property which is supported everywhere.
https://v.usetapes.com/a79pIE1ONH

Autocomplete.css: wrap title and subtitle in smaller views

---

public/js/components/App.css
public/js/components/menu.css

Associated Issue: #1102 
@jasonLaster 
* Changed the background color of the context menu, drop shadow color, and `menuitem` hover color.
* Changed the padding of the `menuitem` class.
* Changed the font sizing for the context menu.

Change debugger context menu styles to be closer to native OSX styling.

---

public/js/test/mochitest/.eslintrc
public/js/test/mochitest/browser.ini
public/js/test/mochitest/browser_dbg-sources.js
public/js/test/mochitest/examples/doc-sources.html
public/js/test/mochitest/examples/nested/nested-source.js
public/js/test/mochitest/head.js

Been trying to do this for a while, sorry. Kept getting distracted, and took a while to decide the right way to do this. This covers the core cases from the previous mochitests. This doesn't test the specific nesting, but we have a lot of unit tests for that kind of stuff.

Add mochitest for source tree (fixes #648)

---

public/js/components/Dropdown.css
public/js/components/Dropdown.js
public/js/components/SourceTabs.css
public/js/components/SourceTabs.js

This is an emergency fix. I'm trying to push out a bundle update today, but the following UI is broken:
The best I can do is at least make the dropdown button the same size as our other icons:
The color is different than the new tab button, and the new tab button is not positioned correctly when tabs are hidden. But this is the best I can do for the release.

Fix dropdown button size

---

public/js/components/CloseButton.css
public/js/components/EditorSearchBar.css
public/js/components/SourceSearch.css

* standardize the large close button for use in both source and file search
* move toward flex based model for both source and file search
Here's the original problem I was seeing in Firefox
And now we see this for results
And this for empty states
Padding and spacing could use some additional followup PRs but this is a nice improvement from before and works on Chrome as well.

use flex to clean up search, fix overflow issue with close button

---

packages/devtools-config/configs/development.json
public/js/components/Editor.js
public/js/components/EditorSearchBar.js

The custom code search we have is far too buggy for us to enable it in dev edition. This PR disables it and Cmd+F will bring up the default code search in the devtools codemirror which works well.
Watch this movie: http://jlongster.com/s/editor-bugs.mp4
In that movie, I found the following bugs:
* Cmd-g and Cmd-shift-g don't work, an extremely command shortcut for find next and prev
* At 20s, the text isn't highlighted when you open it (happens if you click in the editor before opening it)
* The worst one, at 47s, is that you can still see the old file search somehow when clicking away from the search bar (if it's open) and either pressing escape or cmd+f (can't remember which one). Now pressing cmd+f again open the custom search bar and there are TWO open. Hilariousness ensues.
It's way …

Disable custom code search because of bugs

---

bin/update-docker
circle.yml

- moved docker pull into a new script
- `update-docker` attempts to cache the docker image and reuse the cache on future runs
GO FASTER

cache the mochitest-runner docker image on circleci

---

public/js/components/Autocomplete.js
public/js/components/SourceSearch.js

Associated Issue: #1173
This commits wraps the handler call in the CloseButton component so that the close
function doesn't receive the event object as an argument
- rename `handleClose` to `close` because it is not a handler anymore
- inline the handler when passing it down from autocomplete to the close button
`e => close()`

Wrap the click handler passed to CloseButton

---

.eslintignore
package.json
packages/chrome-remote-debugging-protocol/index.js
packages/devtools-config/index.js
packages/devtools-config/registerConfig.js
packages/devtools-config/src/config.js

Associated Issue: None. Discussed problem directly with @jasonLaster in IRC.
* JS Lint script in `package.json` checks the `packages` js as well as all js files within `public` instead of only direct children.
* Updated `.eslintignore` to ignore new things that aren't needed to be checked with this change.
* Fixed any eslint errors with the current files where appropriate.
* Also updated a file path in `devtools-config` to not have an extra folder slash.

Fix main package eslint script to check package contents as well.

---

CONTRIBUTING.md
README.md
circle.yml

Reading through the getting started docs, i think we could do another pass to help people get started.
perhaps a separate page that we host at `https://devtools-html.github.io/debugger.html/getting-started/` This way we could have images, gifs, and a screencast :)

Update CI + Docs to use yarn

---

src/components/EditorSearchBar.css

Fixes this atrocity. 
Looks fine in light mode.

Style search bar in dark mode

---

circle.yml

CI is failing when it comes to re-installing yarn. This will keep it
from doing that.

Add install yarn script

---

package.json
packages/devtools-local-toolbox/src/utils/utils.js
src/utils/utils.js

This is another version of #1170 with small fixes to make it work. It didn't have anything to do with the record types, it just needed some more specific subtyping.

Update flow-bin to 0.35

---

bin/firefox-driver.js

Associated Issue: No direct issue. Precursor to simplifying the getting started flow brought up in issue #1127.
Firefox startup bin now takes an **optional** location parameter. If not provided, it defaults to `about:blank` as that is safe for a fast startup for a developer to use it. We also know that exists always, so it won't cause the terminal to dump out needlessly.

Allow user to provide location when starting Firefox.

---

assets/locales/debugger.properties
src/components/Scopes.js
src/strings.json

Associated Issue: #<1143>
*Replaced a hardcoded string using L10N strings from debugger.properties 
* [29 ] passes `npm test`
My First merge request to this project! I was unable to run `npm run lint on my system so couldn't update the number of passes.

[L10N] Fix hardcoded strings

---

src/components/EditorSearchBar.js

Associated Issue: #1176 
* pressing the `ctrl+g`/`ctrl+shift+g` shortcut with no previous search now toggles the search

Open code search when pressing ctrl+g/ctrl+shift+g with no selection

---

.flowconfig
packages/devtools-local-toolbox/src/index.js
public/js/global-types.js
src/components/Frames.js
src/main.js
src/types.js

* Refactor some functions in Frames.js to be more type-safe and less coupled to `this.props`
* Add Flow type-checking to Frames.js
Flow doesn't like `L10N` being a global. I had to redeclare it at the top of the file in order to get Flow to cooperate.
I feel like `L10N` ought to be `require`d just like everything else, especially if we need to do that in every file that we add Flow to.

Refactor some functions in Frames.js, add Flow types

---

CONTRIBUTING.md
README.md

Associated Issue: #1216 
* Add yarn install step for 0.16.1
* Update yarn explainer text
* Add screenshots + gifs where it helps.

Update getting started docs

---

src/types.js

https://github.com/devtools-html/debugger.html/pull/1121 accidentally introduced a redundant type.

Drop redundant frame type

---

circle.yml

We've seen some occasional flakiness due to Circle having a 4GB Ram limit.
Here's an example [fail](https://circleci.com/gh/devtools-html/debugger.html/1817)
Here's a [memory-usage](https://1817-54585418-gh.circle-artifacts.com/0/tmp/memory-usage.txt) overview
This fix removes unused processes from when circle was used and we ran some unit tests in the browser in CI.
We can also limit flow's memory foot print with these four commands:
```
--sharedmemory-dep-table-pow      The exponent for the size of the shared memory dependency table. The default is 17, implying a size of 2^17 bytes
--sharedmemory-dirs               Directory in which to store shared memory heap (default: /dev/shm/)
--sharedmemory-hash-table-pow     The exponent for the size of the shared memory hash table. The default …
```

Remove unecessary CI processes

---

packages/devtools-local-toolbox/bin/development-server.js
packages/devtools-local-toolbox/package.json
packages/devtools-local-toolbox/webpack.config.js
webpack.config.js

This PR is the outcome of the integration work between devtools-local-toolbox and the inspector. 
The corresponding bugzilla entry is https://bugzilla.mozilla.org/show_bug.cgi?id=1291049 , which contains patches to apply on mc, and that should be compatible with the changes proposed in this PR.
* add a development.customIndex configuration value in order to disable the default route serving index.html
* allow webpack-config to merge plugins, externals and module loaders
* allow tools to define a custom regexp to exclude requests from being transpiled by babel (babelExcludes in the tool's webpackConfig)
@jasonLaster can you have a look and let me know what you think?

update devtools-local-toolbox for inspector integration

---

src/actions/pause.js
src/components/CommandBar.css
src/components/CommandBar.js
src/components/RightSidebar.css
src/components/RightSidebar.js

Associated Issue: #1266
* Extracts Command Bar so that it can be re-used in the vertical layout
* cleans up the watch expression buttons so that it is more clear what is going on

Extract command bar

---

src/components/Autocomplete.css

Associated Issue: #1162
* break long search queries to stop "no files matching" message from overflowing
Long query before:
Long query after:
Short query after:

Do not overflow "No files matching" message.

---

src/components/Editor.js

Associated Issue: #1228 
* Moved to a system of merging objects instead of switching labels to allow for each label to have a different id

use unique context menu ids for each breakpoint menu

---

packages/devtools-local-toolbox/webpack.config.js

cc @jasonLaster 
I was trying to setup the inspector.html development environment on windows, and it looks like the babel exclude regexp needs to be updated to accept both posix and win32 path styles.
I was looking for a better way to do this than replacing `\/` by `(\/|\\), but didn't find any.

support windows development environment for devtools-local-toolbox

---

.eslintrc
packages/devtools-local-toolbox/src/utils/DevToolsUtils.js
packages/devtools-local-toolbox/src/utils/assert.js
packages/devtools-local-toolbox/src/utils/event-emitter.js
packages/devtools-local-toolbox/src/utils/utils.js
src/actions/sources.js
src/components/Accordion.js
src/components/App.js
src/components/CloseButton.js
src/components/Editor.js
src/components/ObjectInspector.js
src/components/Scopes.js
src/components/Sources.js
src/components/SourcesTree.js
src/reducers/breakpoints.js
src/reducers/sources.js
src/utils/DevToolsUtils.js
src/utils/assert.js
src/utils/menu.js
src/utils/path.js
src/utils/pretty-print-worker.js
src/utils/pretty-print.js
src/utils/source-map-util.js
src/utils/source-map-worker.js
src/utils/source-map.js
src/utils/source.js
src/utils/sources-tree.js
src/utils/test-head.js
src/utils/utils.js

In general template performance is about the same to slightly better, however I believe they are much more readable than string concatenation.  With the given eslint rule we can make the code base more consistent overall.
NOTE: This is one of this diff where I need lots of eyes because tiny changes in white space can really make a difference here.  I combed over it all carefully but I don't want to introduce errors here.
* add `prefer-template` to the eslint rules
* move all instances of string concatenation to string templates
Ran tests, played with the debugger in both todomvc and increment

use eslint prefer-template and move from string concatenation

---

.github/PULL_REQUEST_TEMPLATE

We're currently suggesting that people file test plans with incomplete checkboxes, which I believe is the opposite thing we want :)
@clarkbw mind taking a look?

switch test plan template to completed checkboxes

---

src/utils/source-search.js

Associated Issue: #1315 
* Set `opaque` param to `false` on the CodeMirror overlay for matched search terms
Before:
After:

[Editor] Fix matched text color

---

packages/devtools-local-toolbox/src/clients/chrome.js

@jasonLaster 
Found a small issue introduced by #1295 while verifying #1323. 
When `chrome.debug` is false createTabs is called with a single argument `createTabs([])`. Added a default value. Would be fine with updating the different call sites as well, let me know if you want me to change it.

fix local-toolbox error when chrome.debug is false

---

packages/devtools-local-toolbox/src/lib/themes/dark-theme.css
packages/devtools-local-toolbox/src/lib/themes/light-theme.css
src/lib/codemirror-mozilla.css

Associated Issue: #1111
* Change selected match to yellow
* Lighten the match outlines

(WIP) File search style outline matches

---

src/components/ObjectInspector.css
src/components/ObjectInspector.js
src/components/Scopes.js

I had most of this done before break but didn't get it finished. This is actually pretty simple. It will show variables and arguments that have been optimized out with a special message:

Show optimized out variables in object inspector

---

CONTRIBUTING.md
README.md
bin/chrome-driver.js
configs/local.sample.json
docs/debugging-the-debugger.md
docs/getting-setup.md
docs/local-development.md
package.json

Associated Issue: #1233 
We've gotten lots of feedback on our getting started docs. Here are some takeaways
* beginners need a simpler *focused* getting started guide
* beginners need more help with certain gotchas along the process
* beginners could benefit from screenshots / gifs
* beginners can benefit by having common questions answered (i.e. why yarn)
* beginners don't always feel ready to jump into an up for grab. Having a good first activity is helpful
* advanced users will figure it out. They're a minority compared to the many beginners who are good devs, but have questions
* the docs are currently spread out and have too much information that comes before the setup instructions. they can always learn the local dev stuff after they're setup.
1. add getting started doc 
2. add …

Re-write getting started docs

---

src/utils/source-map-worker.js

The problem with sourcemapped breakpoints was that it was searching backwards to find the nearest generated location, which means if there is no mapping for column 0 is would move to the previous line. It's important that we resolve forwards, so it will find the first mapping on the same line (which is a common occurrence, to only map the first piece of code on the line that's indented).

Make sourcemapped location resolve forward instead of back (fixes #1252)

---

packages/devtools-local-toolbox/package.json
packages/devtools-local-toolbox/webpack.config.js

This PR should fix adding breakpoints when debugging Chrome.
The devtools-client-adapters required in main.js (used to get {firefox, getClient}) was generating a separate instance from the one required in devtools-local-toolbox.
This first adapters instance was never properly initialized with a call to startDebugging, so when calling getClient in 
```javascript
const createStore = configureStore({
log: getValue("logging.actions"),
makeThunkArgs: (args, state) => {
return Object.assign({}, args, { client: getClient(state) });
}
});
```
the clientType was always null and defaulting to the firefox client. For now I just forwarded the necessary exports from devtools-client-adapters to devtools-local-toolbox, so that we only ever create one instance of the adapters.
cc @jasonLaster

fix clientType null when calling makeThunkArgs

---

src/utils/sources-tree.js
src/utils/tests/sources-tree.js

So the problem appeared whenever there was a **javascript:** URI - because in you getURL switch you do this: 
```
case "javascript:":
// Ignore `javascript:` URLs for now
return def;
```
but that just returns `def = { path: "", group: "" };` which is then merged into the tree as an entry with an empty string as its url.

[Source Tree] Don't show empty root. Fixes #1338

---

CONTRIBUTING.md
docs/local-development.md

Associated Issue: #1233 
* add svg toc
* add feature flagging

update local development

---

packages/devtools-client-adapters/src/firefox/commands.js
packages/devtools-client-adapters/src/firefox/events.js
src/actions/event-listeners.js
src/reducers/event-listeners.js
src/reducers/index.js
src/selectors.js
src/utils/utils.js

* upgrades event listener reducer
* upgrades event listener action for fetching event listeners
* adds a call for fetching events in newSource behind a flag
* moves asPaused over to eventListners

Upgrade Event Listeners redux backend

---

configs/development.json
src/components/RightSidebar.js
src/components/WhyPaused.css
src/components/WhyPaused.js
src/types.js
src/utils/pause.js

Just a proof of concept for now, if anyone wants to take this further feel free to pick this up.  I think we want input from @helenvholmes first.  I'm not sure the sidebar is actually a good location, the way it pushes everything down doesn't seem like the best design.  A good path forward could be to move the logic out of the component and into a util function such that we can try a couple different variants of the components.
* Create a new component that displays why the debugger is paused

[POC] show the reason why the debugger is paused

---

configs/application.json
configs/development.json
configs/firefox-panel.json
packages/devtools-config/README.md
packages/devtools-local-toolbox/src/components/LandingPage.js
packages/devtools-network-request/networkRequest.js

This fixes the issue with loading source maps by hardcoding the dev server origin.
I also updated the app to read directly from "http://localhost:8000" instead of "file://index.html" https://github.com/jasonLaster/debugger.app/commit/aa482bcf83bf1181837ce300995c1fc4f26b1720
* I wrote a book on `devServerOrigin` [here](https://github.com/devtools-html/debugger.html/pull/1346#issuecomment-263962730), which is not needed now
* I filed a PR on removing `isTesting` [here](https://github.com/devtools-html/debugger.html/pull/1362) which i still think is a good idea

Hardcode origin

---

src/components/EditorSearchBar.js

#1321
Calling `setState()` inside `componentDidUpdate()` may create an infinite loop if there is no break condition for state (http://stackoverflow.com/questions/30528348/setstate-inside-of-componentdidupdate); therefore, I moved the code for re-search to `componentWillReceiveProps()`.

Cleanup editor re-search work

---

src/components/App.js

Associated Issue: #1357
* replaced non-standard way of adding listener to matchMedia object (`onchange =`) with a standard one (`addListener`)

Vertical layout - add firefox support.

---

src/components/SourcesTree.js
src/components/utils/ManagedTree.js

@gregtatum found a pretty serious memory leak. The problem is that the tree component keeps a reference to all items has seen ([here](https://github.com/devtools-html/debugger.html/blob/master/packages/devtools-sham-modules/client/shared/components/tree.js#L203)), so if you keep the same tree around forever and keep adding items, it will continually grow.
Usually the tree is used once and disposed of, like the object inspector. But the source tree is mounted once and used forever, so sources keep building up. Somehow it looks like there's a 1.6MB string being retained per item, which is crazy... I don't understand why it's so big, but making sure the tree releases sources fixes the leak at least.
We achieve this simply be forcing a re-mount of the source tree if it becomes empty. This …

Fix source tree leak

---

src/components/Accordion.css
src/components/Accordion.js

Associated Issue: #N/A but somewhat #1304 
* remove default styling from buttons give by browsers

Fix styling for watch expression buttons.

---

packages/devtools-sham-modules/client/shared/components/tree.js
src/components/SourcesTree.js

* Correct the itemHeight property which is passed to ManagedTree.
* Re-enable the onScroll listener within Tree
The goal of these two changes is to avoid the odd jumpy scrolling behavior in the source tree when clicking on a file while scrolled down in the sources list.
- Attach the debugger
- Load a page with a large number of sources, and expand them (such as gmail)
- scroll about halfway down, and click on a source item
- Before this patch, the tree would scroll down dramatically, after this patch the tree scrolls an appropriate amount to move the selected item into the viewport.
CC @jasonLaster who helped me figure this out.

Avoid jumping around when clicking on tree items

---

src/components/Editor.js
src/test/mochitest/browser_dbg-console.js
src/test/mochitest/head.js
yarn.lock

Associated Issue: #1404 
* remove default codemirror shortcut for escape (which was calling the singleSelection command)
* add a custom key shortcut for escape that calls the singleSelection command if necessary, but doesn't if singleSelection would have no impact.
I tested this in a tab only and not in a panel, just trying to check that I could catch the keypress event when using the escape key while the focus is in the codemirror editor.
(I wanted to add a dedicated testcase but I can't get firefox to build for now for some reason ...)

override escape shortcut in codemirror to fix split console toggle

---

src/test/mochitest/browser_dbg-sources.js

devtools in m-c upgraded to React 15.3.2 in bug [1312236](https://bugzilla.mozilla.org/show_bug.cgi?id=1312236). One of the necessary changes was fixing the `browser_dbg-sources.js` mochitest.
This PR introduces the change that's already in m-c also to the `debugger.html` repo.
You'll need to upgrade to React 15.3.2 before merging this. I'm not sure if it's as simple as changing the version number in `package.json` or if more changes are needed.

Fix mochitests after upgrade to React 15

---

docs/README.md

* Adds a README file to the docs directory which gives us an index page thanks to [some changes at GitHub](https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3)
[x] Checked that it worked at http://clarkbw.github.io/debugger.html/

add README to docs directory

---

CONTRIBUTING.md
README.md
docs/debugger-html-react-redux-overview.md
docs/debugging-the-debugger.md
docs/getting-setup.md
docs/videos.md

Associated Issue: #582
I had a chance to record some screencasts the other day.  I found the process enjoyable, so instead of just creating one getting started video I created a couple extra feature videos as well.
* PR is blocked by actually uploading screencasts and linking to them
* Added a videos section
* Linked to Jason's overview
* Fixed some contributing TOC links
* Added a contributing sharing section

Add screencast docs

---

src/components/Autocomplete.js
src/components/SourceSearch.js

Associated Issue: #1426 
* only truncate the subtitle
For now I am passing the full path around such that we can have it in the title and I'm only truncating the subtitle, the path shown below the file match name.  I was going to use CSS but this actually seems simpler if the `endTruncateStr` function was doing a decent job before.

end truncate only subtitle and pass the full value to the HTML title

---

bin/firefox-driver.js

Associated Issue: #1309 
* prepended the `../node_modules/geckodriver` path for a windows machine so it can successfully find the `geckodriver.exe` 
* Note that using `../node_modules/geckodriver/bin` does not find the `.exe` version which is why I used the parent directory
fixes #1309

change path for windows in firefox driver

---

src/components/SourceTabs.js
src/utils/source.js

Associated Issue: #1388
* Removes ":formatted" from tab tooltips
- Hover over tab title, view true URL in tooltip
@jasonLaster proposed a different solution in #1388 but this is a fix specific to just this issue -- we can use the new `getRawSourceURL` function as part of #1460

Fix #1388 - Remove :formatted text from tab tooltip

---

src/components/Sources.css

Tree rows will be completely highlighted instead of just their labels, per "[#1]" in #1460:

#1460 Polish: Full row highlighting for sources

---

src/components/SourceTabs.js

Associated Issue: Closes #1254
* create a debounced onResize method to attach to the window resize call
* Fun fact: Chrome sends endless resize events while the window is changing while Firefox sends a single event after a resize is finished.

update the hidden source tabs on resize of the window

---

src/components/Accordion.js
src/components/RightSidebar.js
src/components/Scopes.js

Associated Issue: #1280 
Right Sidebar gets the pause data from the state, and the Accordion items now have a shouldOpen prop. Just like @jasonLaster suggested.

callstack and scope panes open on pause

---

circle.yml

This gets us back to using the tip of Yarn, which hopefully is more reliable now.

Install Yarn 0.18.1

---

configs/development.json
src/components/SourcesTree.js

Associated Issue:
When we reveal on a non selected source, the file is shown correctly in `Sources`, but the non selected source is not focused and shown in the editor.
(GIF provided by @jasonLaster )
* Revealing and focusing the non selected source

Fix "revealing and focusing the non selected source"

---

circle.yml

We need to remove the `./` to save files relative to the build directory.  See: https://circleci.com/docs/configuration/#artifacts

look for the yarn-error.log file relative to the build directory

---

package.json

I tracked down the issue with React updating to 15.3 and found that
`react-dom` has an index.js file with just a `module.exports = require('react/lib/reactDOM)`, which our single-module-plugin turns into `module.exports = require()` and fails to load react dom.
The easy fix is to the flow coverage report so that we don't load react 15.3 and we can fix single module plugin in january
https://github.com/devtools-html/devtools-core/issues/23

remove flow coverage rport

---

bin/post-merge
package.json

This looks at the latest changes from when you `git pull` or merge changes into your local branch.  If the `yarn.lock` file is included in those change it will remind you to run `yarn install`.  I decided on just a message instead of automatically running because I felt it was safer to remind people instead of possibly interrupting workflow.
* add a post-merge hook that checks if `yarn.lock` has changed and lets the dev know to run `yarn install`

adding a post merge reminder to run yarn install as needed

---

src/components/ObjectInspector.js
src/components/Scopes.css

Associated Issue: #1470
* set `not-enumerable` class on objects which are not enumerable
* create a class in the Scopes.css file to set opacity of not-enumerable class to `0.6` - toyed with several versions and this seemed like the right level.  Open to discussion.
Originally in 1470 I chose just the label and then decided on the whole node (which includes the description like `Object` because it helps the others stand out even more.
Here's a small example:
And here's what it looks like for the Window:

fadeout non enumerable props in the scope list

---

assets/locales/debugger.properties
configs/development.json
src/components/RightSidebar.js
src/components/WhyPaused.css
src/components/WhyPaused.js
src/strings.json
src/utils/pause.js

Associated Issue: #1345 
* enable the "why paused" feature by default
* use L10N for all strings

enable the why paused feature

---

src/components/App.css
src/components/App.js

Associated Issue: #1358 
* Refactor the `App` component to have two distinct render functions for vertical and horizontal layouts to simplify rendering the right layouts.
* Move the editor and source tree into a sibling start pane for the vertical `Splitbox`
Note: the `endPane` of the vertical layout will be broken but will be addressed in a separate PR for issue #1359 
Note 2: the collapse buttons will also be fixed in their own PR for issue #1537

Rework source tree and editor layout for vertical debugger layout

---

src/components/SourceTabs.css

All other clickable icons have this cursor -- updating to use the same cursor for integrity.

Set collapse/expand cursor to pointer to show it's clickable

---

src/components/Autocomplete.css
src/components/EditorSearchBar.css

Associated Issue: #1507
adjusted the styling to support rtl, with the postcss-bidirection thing.
please note that I forced some strings to be ltr-displayed with css, because their text comes from strings.json so I figured they should always be ltr, right?

changed search bars styling for rtl

---

src/main.js

There were two lint warnings.  Also ES6-ized it.

Cleanup for main.js

---

src/components/SourceTabs.css

Fix #1571 - Fix first tab being a pixel off

---

src/components/SourceTabs.css

This is just an idea; I've removed borders from inactive tabs to prevent the weird-ish look of empty space to the right of inactive tabs when the "x" isn't displaying.

Remove borders from inactive tabs

---

README.md

I've been thinking for the past month that office hours is not the best name for the call for a couple reasons:
1) it's actually very vague. Most people ask me what it is
2) it creates an employee / volunteer distinction. Office hours is like seeing the professor and has office in the title. In fact that is the opposite of what we're trying to do here. We are all working on the project together and the call is about discussing goals, plans, etc
Why "Community Call"?
- it communicates that it is open to everyone
Other ideas?
CC @clarkbw, @bomsy, @wldcordeiro

Switch "Office Hours" to "Community Call"

---

src/components/EditorSearchBar.js

Associated Issue: #1568
* Move reoccurring code into doSearch
* Call from multiple places

Fix Cmd+F with selected text issue

---

package.json

`yarn run firefox` will now open [debugger-examples](https://devtools-html.github.io/debugger-examples/) by default.

Launch Debugger Examples

---

src/actions/pause.js

Associated Issue: #1525
* When not paused, expressions will be evaluated with global scope
* When paused expressions will be evaluated with selected frame
http://g.recordit.co/smSN9UDFzL.gif

evaluate expression when not paused (#1525)

---

src/actions/pause.js
src/components/Expressions.css
src/components/Expressions.js
src/components/ObjectInspector.js
src/components/WhyPaused.js
src/reducers/pause.js

Polish the Expressions UI

---

src/components/menu.css
src/utils/menu.js

Associated Issue: #1607 
* Prevent the onclick handler from being registered if the item is disabled.
* Adds styling for the disabled state.
Am not that familiar with the project so didn't know a better way, I just hardcoded a line to disable the first menu item, here's a patch:
```diff
diff --git a/src/utils/menu.js b/src/utils/menu.js
index 0c3b85a..375a57e 100644
--- a/src/utils/menu.js
+++ b/src/utils/menu.js
@@ -63,6 +63,7 @@ function onShown(menu, popup) {
function showMenu(e, items) {
const menu = new Menu();
+  items[0].disabled = true;
items.forEach(item => menu.append(new MenuItem(item)));
if (isFirefoxPanel()) {
```
Then:
1. Open any source file
2. Right click on some code
3. Notice that the first item in the context menu is disabled, clicking it does nothing.
Hope that's what …

Disable menu items with disabled property

---

src/components/Sources.css
src/components/Sources.js

Associated Issue: #1621 
* Added on click handler for "Cmd+P to search" search label

Create onClick handler to show file search ui

---

src/components/SourceTabs.js

Associated Issue: #1626 
* add a pretty print source context menu entry to the source tabs

Add a pretty print context menu option to the source tabs.

---

assets/default-prefs.js
bin/publish-assets.js
bin/run-mochitests-docker

Associated Issue: #1616
This is a somewhat *dangerous* move, but I think it is okay. This adds a new `default-prefs.js` file that will be copied over to the mc on mochitest runs. This lets us add new default prefs in github. 
The obvious improvement will come in a couple days when we can limit the default prefs to just the debugger and copy the file over to `debugger.js`instead of devtools so its less risky.
r? @tromey

Add default prefs

---

bin/run-mochitests-docker
src/components/Accordion.js
src/components/SecondaryPanes.js
src/utils/prefs.js

Associated Issue: #960
* Add new prefs for callstack and scopes
* Pass in the pref name as properties to the accordion
* When the user clicks the accordion update the pref accordingly
* Check the pref value when new props are passed to the accordion.
If the user does not interact with the accordion explicitly (clicking). The current behaviour is maintained else the user's pref takes precedence.

Add prefs for the callstack and the scopes panes

---

src/components/SourceTabs.js

Associated Issue: #1494 
Renamed the context menu item in source tab from "Show source" to "Reveal in Tree"

Rename "Show source" to "Reveal in Tree"

---

src/components/SecondaryPanes.js

Associated Issue: #1648
* Check for breakpoint(s) existence before rendering the toggle button.
Open up clean debugger profile. See by default there is no breakpoint toggle checkbox. Set a breakpoint somewhere and verify the checkbox then renders.
No Breakpoints:
Breakpoints:

Do not render breakpoint toggle if none exist.

---

package.json
src/components/Rep.js
yarn.lock

Associated Issue: #1601 
This switches from using `devtools-modules/reps`  to using `devtools-reps` from Github.
This probably looks like a relatively small PR, but it is massive:
reps is updated here https://github.com/devtools-html/devtools-reps/pull/33
* there's a new publish entry point
* the bundle works in the panel as well
CC @juliandescottes, @nchevobbe, @tromey, @bgrins

Import reps

---

src/components/Editor.js
src/utils/editor.js

Associated Issue: #1510 
We would need to keep lastJumpLine for every tab separately (not just one globally) - so the easiest thing to do to fix this is to go through all bp lines instead.

Fix #1510. [Editor] Multiple Highlight Lines

---

configs/firefox-panel.json
src/components/Editor.js

Associated Issue: #1194 
* removes codemirror cmd-f, cmd-g handlers
* enables the feature

Fixes search bar

---

src/lib/codemirror-mozilla.css

Associated Issue: #1671 
* Added rounded borders for highlight
* Added slight padding to prevent it cutting off lines.

tweak editor selection highlight (#1671)

---

package.json

Fixes #1356
This will ensure that our `prepush` hook runs successfully so contributors don't post a PR that fails linting in the CI.
* Using `&&` instead of `;` to combine commands will require that both commands are successful
* change `lint` script to `yarn run lint-css -s && yarn run lint-js -s` from `yarn run lint-css -s; yarn run lint-js -s`
* change `prepush` script to `yarn run lint && yarn run test -- --dots` from `yarn run lint; yarn run test -- --dots`

run lint and prepush scripts serially

---

src/components/Breakpoints.css

Associated Issue: #1506 
Changed some styles in `Editor/Breakpoints.css` to make it more RTL friendly

RTL friendly styles for breakpoints component

---

src/components/SourceTabs.js
src/components/shared/Button/PaneToggle.js

Associated Issue: #1695
Previously the PaneToggleButton was re-rendering every time there was a change with SourceTabs.  Now the button is a Component and keys off the `collapsed` and `horizontal` prop values coming from the SourceTabs component.

convert PaneToggle to a React Class

---

src/components/SourceTabs.js
src/utils/source.js

I found while updating the bundle that we were not showing source tabs for eval'd sources that paused.
This fixes that by re-using some of the existing logic:
@clarkbw, @darkwing

Show source tab for paused evals

---

_config.yml

This should make 
https://devtools-html.github.io/debugger.html/
consistent with
github.com/devtools-html/debugger.html

update markdown parser

---

src/components/SourceTabs.css

I was going to submit an issue for this but fixing this was easier so I'm submitting this pull request.
In RTL layout, toggle pane button and tabs overlap
Fix spacing to avoid overlap between toggle pane button and tabs by changing some styles in `SourceTabs.css`

RTL friendly styles for source tab component

---

src/components/ChromeScopes.js

Associated Issue: #1689 
* Use the scopes unavailable localization string instead of outputting "hi" with empty chrome scopes

Use proper empty message for ChromeScopes

---

src/components/CommandBar.css

Fixes #1086
Replaces `stroke` with `fill`
Thanks @nt1m for pointing this out

Fix pause on exceptions button

---

package.json

Associated Issue: #1709
* Open debugger examples on launching chrome

Load examples page on launching chrome

---

package.json
src/components/App.css
src/components/App.js
src/components/Editor.js
src/components/SourceFooter.js
src/components/WelcomeBox.css
src/components/WelcomeBox.js
src/utils/editor.js

Associated Issue: #1537 
**Requires devtools-html/devtools-core#88 to land to actually work properly.**
* add the pane collapse button to the source footer and wire up logic to toggle end pane collapse
@jasonLaster One of the only issues I have with this approach is that the collapse button isn't visible until you open a file. I may instead render it as part of the "editorPane" in `App.js` so that it's always visible. @

Collapsible End Pane in Vertical Layout

---

README.md

App overview link in `README.md` file had a minor mistake.

Fix app overview link in README

---

src/components/Breakpoints.css
src/components/Frames.css

Associated Issue: #1085
* Made dark theme secondary text look more alive in the dark theme
Before
After (made it use the [theme-highlight-bluegrey](https://github.com/devtools-html/debugger.html/search?utf8=%E2%9C%93&q=bluegrey&type=Code) color)
Firebug - unchanged
Light theme - unchanged

#1085 fixed dark theme secondary color

---

.babelrc
webpack.config.js

Associated Issue: #1640 
* .babelrc webpack.json - adding react-dom file to the resolve which will prevent require issue in webpack
running the debugger.html and check the log for exceptions

fixing issue where react = react-dom

---

assets/locales/debugger.properties
src/components/WhyPaused.css
src/components/WhyPaused.js
src/strings.json
src/utils/pause.js

added localisation keys for exception on conditional breakpoint
added message error to indicate reason for breaking
left aligned the WhyPaused message
Associated Issue: #1611 
added localisation keys for exception on conditional breakpoints
added message error to indicate reason for breaking
left aligned the WhyPaused message
followed the instructions provided by the original issue (defined a conditional breakpoint with an undefined variable)
#GoodnessSquad

resolved [WhyPaused] handle breakpointConditionThrown - #1611

---

src/components/Breakpoints.js
src/components/Expressions.js
src/components/Frames.js
src/components/Scopes.js

Breakpoints, Expressions, Frames, and Scopes were all re-rendering based on changes unrelated to their responsibilities.
You can reproduce this easily right now.  Set a breakpoint on the render method for any of the Accordions in the secondary pane.  Then expand or collapse any of the other accordions and you'll hit that breakpoint.
* Added `shouldComponentUpdate` to each component so it only renders as needed per component

add shouldComponentUpdate to default accordions

---

src/components/shared/ObjectInspector.js

Gain 160ms back from expansion time.
* Move the `Object.getOwnPropertyNames(window)` call outside of the function
Before
After

move the properties to a const outside the isDefault function

---

CONTRIBUTING.md

Associated Issue: Closes #1762
* Replaced references to labeling issues by external contributors with "we will tag with `xyz`" sentences

CONTRIBUTING.md - remove references to labelling issues by external contributors

---

bin/publish-assets.js
package.json
src/main.js
webpack.config.js
yarn.lock

This will be needed as soon as we upgrade to a new devtools-launchpad (see https://github.com/devtools-html/devtools-core/pull/90).
It defines the method that should be used to load external dependencies when loaded in a firefox panel.

add externalsRequire in webpack config

---

src/components/Editor.js
src/utils/source-map.js

Associated Issue: #1749
* Add a handler to show jump to original location only if the source has an original source.
Visual testing

Conditionally show jump to original location option (#1749)

---

src/test/mochitest/browser.ini

Workaround for #1794 , disabling failing tests while we figure out issues with the new docker image.
Let's see if CI is green with this one.

skip tests failing with new docker image

---

src/components/Editor/SearchBar.js

This fixes a warning we were seeing that the SearchBar was not receiving `editor` and `sourceText` after we made them required props. The reason that they were not always passed in was:
* sometimes there isn't a source to show
* editor is created after the tree is mounted, not before. the first render had no editor!
I think this is better, *safer*, code. so all good

Fix proptype warnings

---

src/components/Editor/Tabs.css
src/components/shared/Button/PaneToggle.css
src/components/shared/Dropdown.css

Toggle pane buttons were switched in RTL layout. This cause following issue
There is also some duplication of styles for toggle pane button in [components/SourceTabs.css#L122](https://github.com/devtools-html/debugger.html/blob/master/src/components/SourceTabs.css#L122) and [components/shared/Button/PaneToggle.css](https://github.com/devtools-html/debugger.html/blob/master/src/components/shared/Button/PaneToggle.css). I wasn't sure which styles should be removed so I modified both for now. 
Let me know which styles should be removed so I can update this pull request
* Update position of toggle pane button for RTL layout
* Update rotation of toggle pane button

Fix positioning of toggle pane button in RTL

---

src/actions/breakpoints.js
src/actions/expressions.js
src/actions/pause.js
src/actions/sources.js
src/actions/types.js
src/components/SecondaryPanes/Frames.js
src/reducers/breakpoints.js
src/reducers/expressions.js
src/reducers/pause.js
src/reducers/sources.js
src/types.js
src/utils/pause.js
src/utils/source-map-worker.js
src/utils/source.js

#979 
This helps clean up our flow type references so that you don't need to know about devtools-client-adapters. Lots of things can be exported from `types.js`
CC @arthur801031, @clarkbw

Clenaup flow references

---

src/components/Sources.js

Associated Issue: #1798 
* Force RTL mode on the search hint
If I understand correctly this patch needs to be verified by someone who's language is RTL as the issue occurs due to the way non-English RTL works.
- Open panel with native RTL language and verify the search hint displays without `P` at the start of the string.
N/A - English user so my RTL mode doesn't trigger the problem as described.

Force LTR for search hint

---

src/components/SecondaryPanes/Breakpoints.css
src/components/SecondaryPanes/Breakpoints.js

Break point snippets are truncated after 30 chars #1802

use CSS text-overflow: ellipsis for breakpoint snippet truncate (#1802)

---

configs/firefox-panel.json

We were running into a race condition with the development and firefox config being set. This should let the firefox config be used the entire time. 
@juliandescottes we likely want to move the `process.env.TARGET` assignment to the top of publish assets.

Adds a firefox prop to the firefox config

---

src/components/Editor/index.js
src/components/shared/menu.js

Fix issue #1789:
- Hide Watch Expressions menu item if no text is selected
- Don't show empty context menus
I removed the `return` statement from `return menu.popup`, as it suggests the `popup` function returns a meaningful value, when in fact it just returns `undefined`.

Conditionally hide watch expressions label

---

src/components/shared/Button/Close.css

Associated Issue: #1807
*Removed fill for '.close-btn-big path' making the icon less darker.
Inspected button using dev tools - modified the fill color of '.close-btn-big' and found that the fill was not required in order to match the other icons.

Removed fill for .close-btn-bigpath to make close button less dark.

---

src/components/SecondaryPanes/CommandBar.css
src/components/SecondaryPanes/CommandBar.js

Associated Issue: #1773 
* `debugBtn` returns a button element and takes a `disabled` parameter
*  styling updated to handle buttons instead of spans for CommandBar items.
* Also addressed minor styling error with generated markup using the `pointer` cursor for disabled items.
Load up the debugger and verify the CommandBar still looks the way it should. Upon clicking in the right area to make sure it is first in line for tab order, press tab to see the "Pause on next execution" and then Exception buttons highlight.

Use native buttons for CommandBar

---

CONTRIBUTING.md
docs/issues.md
docs/pull-requests.md

Docs on issues. Turned out that writing about pull requests prompted more writing on issues. 
My main goal here is that we can encourage good practices in the community and help teach. Having these points in the docs will let us point to them. It will also be a baseline we can improve over time.
CC @clarkbw, @TheLarkInn

Add docs on issues

---

src/test/mochitest/head.js

* adds dbg for waitForSources call
In most of the cases we call reload() without second argument, so this was not exposed earlier. browser_dbg-navigation.js test did not regress for me locally.

Adds missing dbg parameter in reload()

---

src/components/Editor/Tabs.js
src/reducers/sources.js

Associated Issue: #1705 
* Return list of source tabs even when no tab is selected
* If no tab is selected, select the first tab.
Question: Should we persist the selected tab for the user so that the application brings the user back to the same tab? @jasonLaster @clarkbw 

SourceTabs: render tabs without selected tab

---

src/components/shared/Button/PaneToggle.css

Associated Issue: #1834
added !important to explicitly state that the rule should be applied in vertical mode.

fixed pane toggle button direction

---

src/components/Editor/Footer.css
src/components/Editor/Footer.js

Associated Issue: #1837
* Fixed commands height for footer.
* Center aligned the inlined svg contents
* Moved padding into actions from the command bar itself on the bottom to give more touch area
* Moved a11y attributes onto parent button from the SVG for more surface area to trigger.
* Added aria-label while I was here for the code coverage button
* Removed `debugbtn` method used only once for the footer.
Boot up debugger and check out the pretty print button. Functions the same as the CommandBar does now.
- Hover pretty print button area to see the title shows for the full surface area instead of just over the icon.
- See icon is centered and not oddly placed higher than the center of the line.

Cleaned up pretty print button and other footer actions

---

src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-asm.js
src/test/mochitest/examples/asm.js
src/test/mochitest/examples/doc-asm.html
src/utils/client.js

Associated Issue: #1767
* onFirefoxConnect was modified to call reconfigure()
* onFirefoxConnect and onConnect are async functions
A mochitest is included.

Reconfigures Firefox to disable asm.js AOT for debuggger.

---

.babelrc
package.json
src/components/SecondaryPanes/WhyPaused.js
src/components/SecondaryPanes/index.js
yarn.lock

* Minimally converted the `WhyPaused` component to use es6 classes 
* Tried to use `PureComponent` but it doesn't seem to be defined in `react` where it should.  Needs more investigation.
If we want to really clean up the syntax to make things cleaner and more readable I think we might need to go even further down this rabbit hole which includes JSX #1747 (which would remove the need for the `createFactory` calls).
Our webpack config continues to confound me so I don't think I've done that correctly but it didn't like me using `export` so I needed a new transform plugin.  I gave up trying to do anymore as I think the presets would handle most of this.  I need a 12 week intensive course with Julian and Jason on webpack sorcery to make any more progress here.
This does show that its …

convert WhyPaused to use es6 class

---

assets/images/refresh.svg
src/components/SecondaryPanes/Expressions.css

Styling of watch expression pane was not consistent with others in secondary pane. These are few changes to correct that.
* Add viewbox attribute for `refresh.svg`
* Change color of placeholder for chrome and firefox
* Change font-size of `input-expression`
|-|Firefox|Chrome|
|-|-|-|
|Before changes|![before-change-firefox](https://cloud.githubusercontent.com/assets/1755089/22258132/695e3408-e286-11e6-9742-11dd80e03d1b.png)|![before-change-chrome](https://cloud.githubusercontent.com/assets/1755089/22258140/74062910-e286-11e6-95fb-d95fc11f2b94.png)|
|After changes|![after-change-firefox](https://cloud.githubusercontent.com/assets/1755089/22258165/8feceef2-e286-11e6-95c5-47ee91589d42.png)|![after-change-chrome](https://cloud.githubusercontent.com/assets/1755089/22258184/9bd62dc8-e286-11e6-84 …

Tweak styles of watch expression pane

---

bin/post-merge.js

`execFIle` needs the pure executable binary as the first param. Every option/argument in the array following. This moves `diff-tree` into the arguments.
To test, you can setup a branch and reset it back a ways so you have a `yarn.lock` mismatch. Then, have another branch fully updated and apply this patch. Then run `git merge {latest-branch-with-patch}` while in the reset branch and it will complete fine and tell you to run `yarn install` as expected.

Fix postmerge script

---

package.json
src/actions/pause.js
src/actions/types.js
src/components/SecondaryPanes/ChromeScopes.js
src/reducers/pause.js
src/selectors.js
src/types.js
yarn.lock

associated issue #1298 
This work was done in december and cleaned up during the community call. This and the client update will help us show chrome scopes along side firefox scopes.
lets wait on https://github.com/devtools-html/devtools-core/pull/131 to pull this in

Update how Chrome Scopes are shown

---

src/components/SecondaryPanes/CommandBar.css
src/components/SecondaryPanes/SecondaryPanes.css
src/components/SecondaryPanes/WhyPaused.css

Associated Issue: #1882 
* Set proper flex values to SecondaryPane's contents.
Open up the debugger in Chrome and FF, get it paused where it will show a reason why. Then make the *height* of the viewport smaller. Before this caused the height of the Commandbar to shrink, now it stays at 30px with no overflow.

Fix SecondaryPanes contents to flex properly.

---

assets/locales/debugger.properties
src/components/Editor/index.js
src/components/SecondaryPanes/Frames.js
src/components/SourcesTree.js
src/strings.json
src/utils/clipboard.js
src/utils/sources-tree.js

… tree
Associated Issue: #1490
Added the ability to copy source URL to:
* Editor.js
* Frames.js
* SourceTree.js
Opened to-do MVC app and tested across different options.
- Right clicked editor, copied source.
- Right clicked stack frame, copied source.
- Right clicked left source tree, copied source.

Adding copy source URL to context menu for editor, frames, and source

---

src/components/Editor/SearchBar.js
src/components/Editor/index.js
src/test/node-unit-tests.js
src/types.js
src/utils/build-query.js
src/utils/source-search.js
src/utils/tests/build-query.js
src/utils/tests/source-search.js

Associated Issue: #1637 
This PR extracts the source-search utils from #1644 and adds some unit tests around `buildQuery`

Add search modifiers to utils

---

docs/getting-setup.md

This dramatically simplifies the setup guide based on the amazing work @bomsy did with the launch buttons. 
It also adds helpful information about **node 7** and links people to install guides for yarn. I found that including `brew install yarn` added more confusion tonight. I think it's better to bring people to yarn install and let them sort it out and then come back... 
Curious to see what people think

simplified getting setup

---

README.md

* Mostly lots of little fixes to the links
* Updated the last sentence of the first second paragraph
* Updated the debugger screenshot
* Changed ‘Getting Setup’ to ‘Quick Setup’

Revamped the README

---

README.md

This fixes the README badges which were broken by #1915 and moves them up to the title.

move the badges up to the title

---

README.md

Found broken link in README for Chrome debugging protocol viewer. Old link is for version 1-1, while the new version is 1-2.
Changed  https://chromedevtools.github.io/debugger-protocol-viewer/1-1/ to https://chromedevtools.github.io/debugger-protocol-viewer/1-2/.

fix broken link in README for chrome-rdp

---

src/utils/sources-tree.js
src/utils/tests/sources-tree.js

Associated Issue: #1352 
* Change `isDirectory` function
* Edit test
The assumption here is that all urls point to files.
I'm completely sure about changes I made here. These changes seem to resolve the issue.
Let me know what you think.

Change isDirectory logic for source-tree

---

src/components/shared/Dropdown.css

Associated Issue: #1941 
Add `no-wrap` in `Dropdown.css` so that ellipsis show up in dropdown when file name is too long.
|Before|After|
|-|-|
|![before](https://cloud.githubusercontent.com/assets/1755089/22750074/7bc12030-ee55-11e6-9353-72188c4d25bc.png)|![after](https://cloud.githubusercontent.com/assets/1755089/22750078/7d7bd2c6-ee55-11e6-8839-b8d8220bf6fe.png)|

Fix filename wrap in dropdown

---

package.json
src/actions/types.js
src/utils/prefs.js
src/utils/pretty-print-worker.js
src/utils/redux/middleware/promise.js
src/utils/redux/middleware/thunk.js

Associated Issue: #1785 
This makes progress on some of the remaining util files. After this there are only a handful...
* src/utils/prefs.js                    
* src/utils/pretty-print-worker.js      
* src/utils/redux-devtools.js           
* src/utils/redux/middleware/promise.js 
* src/utils/redux/middleware/thunk.js   
There are still some issues here, but it's most of the way there.
https://gist.github.com/e16ffd76edb9399d4ae00d5f4a9af139
CC @jbhoosreddy, @clarkbw you might be interested in taking a look at some of the redux stuff.

Type more utilities

---

.remarkrc
CONTRIBUTING.md
circle.yml
configs/README.md
docs/README.md
docs/client.md
docs/debugger-html-react-redux-overview.md
docs/feature-flags.md
docs/issues.md
docs/local-development.md
docs/pull-requests.md
package.json
src/test/fixtures/README.md
yarn.lock

Associated Issue: #1944
* Add `remark-lint`, `remark-validate-links`
* Fix links in various files
* Remove fixtures link
* Remove flow links from table of contents in `local-development.md`
I've just added `validate-links` to `.remarkrc`. We should also include `"presets": ["lint-recommended"],` in future.
Let me know if I missed something.

Add remark for markdown lint

---

src/components/Editor/SearchBar.js
src/utils/editor/source-search.js

Associated Issue: #1930
* Add a regex to check if the query only contains whitespace. If this is true, we do not search this query. Otherwise, we perform a search.

Fix white space queries breaking the editor

---

.flowconfig
src/types.js
src/utils/editor/source-documents.js
src/utils/editor/source-editor.js

Associated Issue: #1785
* Add flow to source-documents.js and source-editor.js
- Passed 
`yarn run flow`
`npm run lint-css -s; npm run lint-js -s`
`node src/test/node-unit-tests.js --dots`

Add flow to source-documents.js and source-editor.js

---

src/reducers/sources.js

At some point we stopped showing the welcome box when you would close all of the sources.
This fixes that by not selecting sources with empty URLs.
* TODO: add an integration test

Stop selecting sources with no url

---

README.md

Associated Issue: #2024 
* Remove front matter from `README.md`
* Move badges below title
Current version
* Github: [https://github.com/devtools-html/debugger.html/blob/361b79b1c5206a8d5bf5cd97b064f943b60d66ac/README.md](https://github.com/devtools-html/debugger.html/blob/361b79b1c5206a8d5bf5cd97b064f943b60d66ac/README.md)
* Github pages: [https://irfanhudda.github.io/debugger.html/](https://irfanhudda.github.io/debugger.html/)

[Docs] Remove README front matter

---

src/components/Editor/Footer.css

There were some redundant styles which were causing problems with code coverage button position.
* Remove redundant CSS
|Before|After|
|-|-|
|![footer-old](https://cloud.githubusercontent.com/assets/1755089/22984222/b00ca254-f3ca-11e6-8612-b0203472586f.png)|![footer](https://cloud.githubusercontent.com/assets/1755089/22984154/82b883fe-f3ca-11e6-9a52-7f1bfeab61a5.png)|

[SourceFooter] Remove redundant css in source

---

assets/panel/debugger.properties
src/components/SourceSearch.css
src/components/shared/Autocomplete.css
src/components/shared/Autocomplete.js
src/strings.json

Actively working on this.
Associated Issue:  #1845
* move the summary info into the search bar container
* added keyshortcut for `Esc`
*

move the results summary into the search container

---

src/components/SecondaryPanes/Expressions.css
src/components/shared/ManagedTree.css

I hadn't seen that @arthur801031 had claimed the issue but talked to him on Slack about opening the PR.
Associated Issue: #1970
* remove flex box and change width to account for close button

Fix watch expression tree not expanding

---

assets/panel/debugger.properties
src/components/Editor/index.js
src/components/shared/Autocomplete.js
src/strings.json

Followup to PR: #2037
Associated Issue:  #1845
* actually adds the `Esc` key
* bumps the l10n key to `sourceSearch.resultsSummary1`

function search updates

---

src/components/Editor/Tabs.css

Associated Issue: #2041 
* make the tabs into inline flexboxes and remove absolute positioning from the close button.
Seems like the close button is a little too close to the tab title. 🤔

Fix tab close button positioning

---

package.json
src/components/Editor/SearchBar.js
src/components/Editor/index.js
src/utils/editor/index.js
src/utils/editor/source-search.js

Associated Issue: #2065
* I'll first land #2067 and then rebase
* I moved the search results state to the editor to simplify the state. We can further organize this later now that the state is better grouped
* the main issue was that we were not clear the search index any time the user clicked away
* **typing/deleting query**
* should search after each character, index
* the index and count should be correct
* the match should be  to right of the cursor
* **(enter/shift enter |  cmd+g/cmd+shift+g)**
* increments and decrements by one
* wraps from first to last of the list and vice versa
* **moving the cursor**
* updates the match and index to be to the right of the cursor
* **click on document**
* **cmd+g** should research from that location.
* **cmd+f** should refocus the search bar with …

Fix search selection

---

src/components/Editor/Breakpoint.js
src/components/SecondaryPanes/Scopes.js
src/components/shared/ManagedTree.js
src/components/shared/ObjectInspector.js

Associated Issue: #1617
* Added get and set functions which enable us cache the `actors` and `expanded` states across `ObjectInspector` component mounts.
* Fixed a key bug in the `getChildren` function. The loaded children were cached against the `actor` rather than the `key`. ( Finding this was the nightmare)  :)

Persist scopes

---

src/components/Editor/ConditionalPanel.css
src/components/Editor/ConditionalPanel.js
src/components/Editor/Editor.css

Associated Issue: #1946 
* Moved Conditional Breakpoint Panel style from editor.css to its own file at ConditionalPanel.css
* Changed ConditionalPanel.js to include the guillemet
I used the instructions on the wiki to run the source code and saw the guillemet in the correct position.

Issue 1946: adding Conditional Breakpoint guillemet

---

src/components/SecondaryPanes/CommandBar.js

Associated Issue: #2097
* Restore tooltips

Restore tooltips for debug buttons

---

src/components/SourcesTree.js

Associated Issue: #2085 
* to match expected UX from editors like Atom/Sublime I've modified the source tree to expand directories on click. Since this change was made the double click behavior seemed redundant and was removed.

Expand source directories on click

---

.remarkrc
configs/application.json
configs/development.json
docs/getting-setup.md

* Fix typo in the config key `webSocketHost`
* Improve styling of Firefox getting started docs
* Add new docs about the WebSocket workflow
This should make it easier for people to choose the WebSocket transport with Firefox if they'd like to.

Document Firefox WebSocket workflow

---

src/components/Editor/SearchBar.css
src/components/Editor/SearchBar.js

Associated Issue: #2078 and #2000
* Add a bottom bar to the searchbar
* Move the modifiers to the bottom bar
@jasonLaster I know we want the modifiers on the right side and I'll get that once function search is moved too. 😄

Add a search bottom bar and move the search modifiers to the bottom bar.

---

docs/integration-tests.md
src/components/shared/ObjectInspector.js
src/utils/object-inspector.js
src/utils/tests/object-inspector.js

Associated Issue: #2025
This adds the logic for bucketing objects and arrays with lots of keys. It's still pretty rough, so it would be great to get some thoughts on how to clean it up.

Add buckets for objects and keys

---

src/components/Editor/SearchBar.css
src/components/Editor/SearchBar.js

Associated Issue: #2066 
* Add the initial dummy UI for where function search will be toggled.

Phase one of moving the function search into the editor search bar

---

src/components/SecondaryPanes/CommandBar.css

Associated Issue: #1918 
* Sticky `.command-bar` to the top using `position: sticky`.
* z-index so the static elements don't go on top of it.
* Background-color to prevent the command bar from showing the scrolled elements underneath it.
Start up debugger, set a breakpoint, open the `window` scope variables. Scroll some.

Stick the commandbar to the top of the seconday panel.

---

src/components/Editor/index.js
src/utils/editor/source-editor.js

Associated Issue: #2127
* unlink codemirror document on editor destroy
* try to set codemirror document from existing source documents rather than plain text when possible
(or see gif in #2127 )

unlink codemirror doc on component unmount

---

CONTRIBUTING.md
README.md
docs/integration-tests.md
docs/local-development.md

* makes the integration tests linkable
* updates integration test overview
* adds a more prominent section in the readme for dev information as people lose in the contributing guide
* changes "local development" to "development guide",

clean up testing docs

---

src/components/SecondaryPanes/Expressions.css

Associated Issue: #2123
- Vertically align the text inside the Watch Expressions section in the panel
- Make the Watch Expressions section the same height as other sections by default
[1]: https://cloud.githubusercontent.com/assets/7751418/23325233/e5b2f61c-fac1-11e6-9024-3d2dc2f0f98d.png

Align Text Vertically in Watch Expressions Panel Section

---

src/components/Editor/index.js

Fixes two tests, which were broken by the recent vertical layout bug fix. The issue came from trying to get a source document that did not exist.
* devtools/client/webconsole/test/browser_webconsole_bug_766001_JS_Console_in_Debugger.js  
* devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_location_debugger_link.js

fix console link test

---

package.json

Fixed a typo in the package.json file (`yarn.log` => `yarn.lock`)

Fix the nom command to remove yarn.lock file

---

src/components/SecondaryPanes/Frames.css

Associated Issue: #2083
* Removed CSS that changes the frame location's color on hover
* Removed it for all themes (let me know if you'd like to put it back for the dark theme)

fix frame location color change on hover

---

src/components/Editor/SearchBar.js
src/components/shared/Autocomplete.js
src/components/shared/ResultList.js
src/utils/result-list.js

Associated Issue: #2106 
* Replace scrolling function to prefer scrollIntoView method for scrolling
|Firefox|Chrome|
|-------|--------|
|![](http://g.recordit.co/EdZaIkO0yU.gif)|![](http://g.recordit.co/mqpBAUXAw3.gif)|

use scrollIntoView to improve result scrolling (#2106)

---

src/components/Editor/SearchBar.js

* Missed this reference to the right refs, fixed the call

Fix call to `scrollList` to pass the right ref.

---

src/components/Editor/SearchBar.css

Associated Issue: #2169
* Add a max-height to the searchbar
* Disable shrinking on the bottom bar to avoid squashing by result list

Style the searchbar height so the result list doesn't go on forever

---

src/components/shared/ManagedTree.css

Modify minimum width of tree to be 100% so that
the selected source highlight is full width.
Fixes #2082
* Add `min-width` property to source tree

[Sources] Make selected source highlight full width

---

src/components/Editor/Tabs.css
src/components/SecondaryPanes/SecondaryPanes.css
src/components/Sources.css

Associated Issue: #2163
* Changed close icons in Tabs to be more visible
* Changed arrow icons in Sources & Secondary Panes to be more visible

Fix icons dark theme

---

assets/panel/debugger.properties
src/components/Editor/Breakpoint.js
src/components/Editor/ConditionalPanel.js
src/strings.json

Associated Issue: #1945
* Using the 'x' saves and closes the panel
* Pressing "Escape" closes without saving
* Pressing "Enter" always saves. If there is no content, it converts to a "regular" breakpoint

[Editor] Add close button to conditional breakpoint panel

---

src/components/Editor/SearchBar.js
yarn.lock

Associated Issue: #2164 
* remove `isRequired` from `selectedSource`
* add if guards to satisfy flow

Remove required status from  prop in searchbar and fix flow issues.

---

src/components/Editor/SearchBar.js

Associated Issue: #2154
avoids doing a search when the search bar is closed. This will help the initial source load time significantly for large files

Speed up opening the editor

---

src/components/Editor/SearchBar.js

Associated Issue: #2171 
* Only run the function search when it's enabled rather than both it and code search

When function search is enabled don't run the code search.

---

src/components/Editor/SearchBar.css

Associated Issue: #2196 
* Adding width/height to fix chrome rendering issue with the buttons

Add a width/height to the search modfier svgs to fix a chrome render issue

---

src/utils/editor/build-query.js
src/utils/editor/source-search.js
src/utils/tests/build-query.js

Associated Issue: #2105 #2199 
* Match against the built query in `searchOverlay` rather than the raw query
* Initialize our matchIndex as zero rather than null

Fix whole word search modifier clearing search and count showing as NaN

---

src/components/Editor/SearchBar.css
src/components/Editor/SearchBar.js

Associated Issue: #2195 
* disable the search modifiers when function search is enabled

Disable the search modifiers when function search is enabled.

---

src/components/shared/SearchInput.css

Associated Issue: #2204 
* `SearchInput` needed `flex-shrink: 0` to not collapse

Add `flex-shrink: 0` to the search input so it doesn't shrink on chrome.

---

src/components/Editor/SearchBar.css
src/components/Editor/SearchBar.js

Associated Issue: #2208 
* <kbd>ESC</kbd> and the close button both clear and close search
* <kbd>ctrl</kbd>/<kbd>cmd</kbd>+<kbd>shift</kbd>+o always opens function search
* function search button jumps between function and code search

Polish search toggle UX

---

src/components/Editor/SearchBar.css

Associated Issue: #2205 #2214 
* Fix the borders the list and items
* Pad the items better and fix up the flex layout to avoid wrapping

Fix border stacking for the result list in function search.

---

src/components/shared/Dropdown.css

Associated Issue: #2075 
- Make the tab-overflow dropdown visible in RTL mode. 
| LTR | RTL | 
|---|---|
| ![screenshot from 2017-02-28 16-24-55](https://cloud.githubusercontent.com/assets/7751418/23440462/0cf365ec-fdea-11e6-92fc-4aff40f5bb50.png) | ![screenshot from 2017-02-28 16-20-23](https://cloud.githubusercontent.com/assets/7751418/23440461/0cef36b6-fdea-11e6-9c68-9619bd5a77e9.png) |

Fix Tab Dropdown in RTL Mode

---

src/components/Editor/Editor.css
src/components/Editor/Preview.css
src/components/SecondaryPanes/CommandBar.css
src/components/SourceSearch.css
src/components/Sources.css
src/components/shared/Button/PaneToggle.css

Associated Issue: #2178
* Sidebar pane headers are the same dark grey as tabs
* Toggle buttons are grey
* Changed colors for comments & subtitle text under search results from grey to blue
* Dark theme for Editor Preview
* I could reproduce the source search jumping the other night but after the most recent rebase, I can't reproduce it. 

Polish dark theme ui

---

src/actions/sources.js
src/components/Editor/SearchBar.js
src/reducers/sources.js
src/utils/parser.js
src/utils/tests/parser.js

Associated Issue: #2230 #2215 #2213
* moved parsing out of loading a source file
* memoized function declarations
* made sure we closed the search bar when we selected an item
* added `id` to sourceText, which should have always had it
* solves the pretty print problem too
* replaced  `state.functionDeclarations` with `getFunctionDeclarations`

Function Search wins

---

src/components/Editor/SearchBar.js
src/utils/parser.js
src/utils/tests/parser.js

Associated Issue: #2221 
* more intelligently detect if we're dealing with a function and extract the names for ES6 shorthand and ES6 class methods

Add parsing support for ES6 object method shorthand and class methods.

---

src/components/SecondaryPanes/Expressions.css

Associated Issue: #2235 
* Fix the CSS related to the close button on watch expression (inspired by what is done for breakpoints)
Just manual testing.

Fix #2235 : Fix close button display for watch expression

---

src/test/mochitest/browser.ini

Let's skip all new debugger tests on debug platforms until they run regularly during development.
Otherwise this makes the release process too random.

disable all new debugger tests on debug platforms

---

src/components/App.css
src/components/App.js
src/components/Editor/Tabs.css
src/components/SecondaryPanes/Breakpoints.css
src/components/SecondaryPanes/Expressions.css
src/components/SecondaryPanes/Frames.css
src/components/shared/Accordion.css
src/components/shared/Dropdown.css
src/components/variables.css

Associated Issue: #2232 
* replace --theme-search-overlays-semitransparent by --search-overlays-semitransparent
* create new file variables.css required by App.js
* add definitions for --search-overlays-semitransparent in variables.css
* remove rules using --theme-faded-tab-color which was not defined and therefore not evaluated
Started the debugger and checked I didn't see visual regressions.

Add variables.css to debugger.html and remove references to undefined css var

---

src/utils/editor/source-search.js

Associated Issue: #2228 
* when we remove overlay reset our selection to the beginning of the document (essentially clearing it)

Polish overlay clearing

---

src/components/Editor/SearchBar.css

Associated Issue: #2240 
* Changed the max height of the result list to fit about 7 items.
* Considering the box model of each item, its height comes to be 33px. With that in mind, 230px should be enough to limit the visualization to about 7 items.

Fixed max-height in Result List

---

src/utils/object-inspector.js
src/utils/tests/object-inspector.js

This changes the object inspector to quote property names when quotes
would be required by JS object literal syntax.
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1137281.

Quote property names when required

---

src/components/Editor/SearchBar.js
src/utils/parser.js
src/utils/tests/parser.js

Associated Issue: #2249 
* Rework `getFunctions` into `getSymbols` function that traverses an AST and extracts variable, function and class declaration names and locations

Rework function parser helpers into symbol parser helpers that parse functions, variables, and classes

---

src/components/Editor/Tabs.css
src/components/shared/Button/Close.css

* Center close tab button
* Increase size of close tab icon
| Before | After |
| --- | --- |
|![old](https://cloud.githubusercontent.com/assets/1755089/23558800/e901fd74-005a-11e7-8434-b70115600e69.png)|![new](https://cloud.githubusercontent.com/assets/1755089/23558807/ed26ce02-005a-11e7-8870-c60f375ab41e.png)|
Let me know what you think about these changes.

[SourceTabs] Center tab close button and increase its size

---

src/test/mochitest/browser_dbg-editor-select.js
src/test/mochitest/head.js

sadly, these `isVisible` checks are intermittent in debug mode, so they're being commented out for the time being.
For what it's worth, they're still enabled in the web test runner equivelent so we're doing the checks there.
Next week or in paris we can look at why the web test runner was intermittent in debug mode and these checks were as well

remove isVisible checks

---

assets/module-manifest.json
package.json

* bump debugger to version 0.1.0 
* add a module manifest for consistent bundles so our modules don't bounce around in the bundle. Thanks @TheLarkInn for the tip!
@juliandescottes

version debugger

---

src/components/Editor/Tabs.css
src/components/shared/Button/PaneToggle.css

Associated Issue: #2141
* Increased size of pane toggle buttons
* Reduced starting tab margin size to account for toggle button moving further right
* Added left and right margin increase to toggle buttons on horizontal, and bottom margin in vertical for bottom toggle
Debugger's Testing doc

Increase pane toggle button size and margin

---

src/components/Editor/EditorMenu.js

Associated Issue: #2294
* `addExpression` action expect `input: string` but received an object when dispatched

addExpression expected string not object

---

src/components/Editor/SearchBar.js

* I missed this use of L10N and had the placeholders where I didn't want them

Accidentally used the placeholder L10N strings in place of the button labels

---

src/components/Editor/index.js
src/components/shared/Button/Close.css

Associated Issue: #2287 
This is a partial fix making the close button appear correctly upon opening of the conditional panel. It is still possible to cover the button by dragging the right panel over it, however.  This does not always happen, but I was able to reproduce it.
When it becomes possible to catch drag events this issue should be revisited.  
I also added a bit of space between the button and the right panel. 
* Open source code with very long lines (ie. jQuery) in the debugger and press 
CTRL-SHIFT-b to open the conditional panel.  The close button should be visible 
in the conditional panel to the right of the editor.

Make close button appear correctly upon opening the conditional panel

---

src/components/Editor/SearchBar.js
src/components/Editor/index.js

This is not pretty, but an ok solution.. I think, please review
The logic is a bit too spread out and I function deliberately ignored function search.
Luckily there is a refactor planned I understood from jlast
Associated Issue: #2103 
* Make sure that last search is in the search bar even if it becomes unmarked in
the editor.
* Selection in the editor becomes the search.  Not 100% sure this is the right approach.
Simple
Again
Typing
Selection

[EditorSearch] cmd+f without a selection should refocus the search bar

---

src/utils/editor/source-editor.js
src/utils/source.js
src/utils/tests/source.js

Associated Issue: #2307
* Add support for clojure syntax
I looked quite a lot to find a closure sample I could run locally, or even add to debugger-examples. But I'll come back it it.
**Old**
**New**

add clojure syntax mode for editor (#2307)

---

src/components/Editor/Preview.js
src/components/Editor/index.js
src/components/shared/ObjectInspector.js
src/components/shared/Popover.js

Associated Issue: #2300
* EditorPreview now appears when `this` is selected & in scope

show `this` when it’s in scope

---

src/components/Editor/SearchBar.js

Associated Issue: #2310 
* Update search results when the type of symbol searched changes

#2310 : Trigger search when changing the type of symbol searched

---

src/test/node-unit-tests.js

Associated Issue: #1925 
Previous expriment goes here https://github.com/devtools-html/devtools-core/pull/228
Let webpack `require` the correct node's `path` module in  https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-network-request/stubNetworkRequest.js
On Windows, run `yarn test`,  all test passed
On Ubuntu, run `yarn test`,  all test passed

Fix failing test on windows

---

src/components/Editor/SearchBar.js
src/utils/editor/source-search.js

Associated Issue: #2154
* Cache `debounce`-ed `searchResults` function
* Avoid generating a cursor and iterating over the results for an empty query

[EditorSearch] Improve searchbar and search performance on large files

---

src/components/shared/Button/Close.css

* `close-btn-big` is used in file search and conditional breakpoint panel.
* Fix another typo in `transition-timing-function` property value
|File search|
|--------------|
|![no-hover-file-search](https://cloud.githubusercontent.com/assets/1755089/23908241/7221fa0e-08f9-11e7-9c81-c98f18ab80eb.png)|
|![hover-file-search](https://cloud.githubusercontent.com/assets/1755089/23908246/73a2a6bc-08f9-11e7-8dc6-fc6c0ddd4665.png)|

Add hover effect to close-btn-big

---

src/components/SecondaryPanes/Expressions.js

Associated Issue: #2347
* Use the updating state passed in from the reducer

remove flash of 'not avaliable'

---

src/components/SecondaryPanes/Breakpoints.js
src/components/SecondaryPanes/ChromeScopes.js
src/components/SecondaryPanes/CommandBar.js
src/components/SecondaryPanes/EventListeners.js
src/components/SecondaryPanes/Expressions.js
src/components/SecondaryPanes/Frames.js
src/components/SecondaryPanes/Scopes.js
src/components/SecondaryPanes/index.js

* Updated the following components to use ES6 classes
* BreakPoints
* ChromeScopes
* CommandBar
* EventListeners
* Expressions
* Frames
* Scopes
* SecondaryPanels (index.js)
I haven't used Flow outside of this project so I made some assumptions on how to handle the errors that I saw (e.g. defining state and instance functions that are bound in the constructor).

Convert SecondaryPanes to ES6 classes

---

assets/panel/debugger.properties
src/components/Sources.css
src/components/SourcesTree.js
src/strings.json

Associated Issues: #2371 #2231 
When a page doesn't have sources, show an indicative message "This page has no sources". Right now nothing is shown.
- Go to https://devtools-html.github.io/debugger-examples/
- Attach debugger to that tab
- Check if there is a message "This page has no sources."
- Go to a page with sources
- Check that the tree loads normally

Show message when there are no sources for a page (no files to debug)

---

src/components/Editor/Tabs.css
src/components/SecondaryPanes/Breakpoints.css
src/components/shared/Button/Close.css
src/components/shared/Button/Close.js

* Move `close-btn` styles to `Close.css`
* Change `.close-btn-big` to `.close-btn.big` to avoid duplication of CSS
* Use flex box for all close buttons
* Change `display: none` in `Breakpoint.css` to `visibility: hidden` to make it work with flexbox (conflicts with `display: inline-flex`)
|Conditional Breakpoint panel|
|-----|
|![big-btn](https://cloud.githubusercontent.com/assets/1755089/24049538/668d6d3a-0b52-11e7-9fd7-f980d0efb887.png)|
|![big-after](https://cloud.githubusercontent.com/assets/1755089/24049548/6c4c0e02-0b52-11e7-82fe-39c2b49d1be8.png)|

Tweak close-btn styles

---

src/components/ProjectSearch.js

Fixes #2396
This problem was caused because `close` function was passed down to `CloseButton` where it was being called with `SyntheticMouseEvent`. (`inputValue` parameter was object) 
* Remove `inputValue` parameter from close function

Fix close function in ProjectSearch

---

src/utils/fromJS.js
src/utils/tests/fromJS.js

Associated Issue: #2407
* ensure *value.constructor* before *dereferencing value.constructor.meta*
* ensure *value.hasOwnProperty* before calling it

accommodate objects without a prototype (fixes #2407)

---

src/components/SecondaryPanes/Expressions.js
src/reducers/expressions.js
src/utils/prefs.js

Associated Issue: #2290
* Add prefs for expressions
* Add store and restore functions to the reducer
* Call `evaluateExpressions` from `componentDidMount` to evaluate if expressions exist

Persist expressions

---

src/components/shared/Popover.css

Previously masked by conditional breakpoint, right panel
Associated Issue: #2397 
---------
---------

Bring editor preview to foreground

---

src/components/shared/Accordion.css

In https://github.com/devtools-html/debugger.html/pull/2386 we accidentally removed a style that's not autoprefixed for button focus states
Associated Issue: #2419

Re-add accordion focus inner style

---

src/components/Editor/index.js

Associated Issue: #1964 
Stoped the pervioulsy highlighted line flashing after the debugger was reloaded.
(Tested comment to see if it worked).

Stop the previously highlighted line flashing after refreshing the debugger.

---

configs/development.json
configs/firefox-panel.json
package.json
src/test/tests-boot.js
src/utils/parser/index.js
src/utils/pretty-print/index.js
src/utils/pretty-print/worker.js
webpack.config.js
yarn.lock

Associated Issue: #2427
we're currently seeing issues running the unit tests that touch workers like parser, source maps. The reason for this is that we're no longer pre-bundling the workers. The solution I want to go with is to stop building the workers and instead use workerjs to point to the worker entry file directly. 
* update bootstrap to provide worker paths
* convert pretty print to the same directory format
* update worker URLs to a new config structure
TO DO:
* add workerTask to devtools-modules
* update source map worker to use the new config.

[tests] Fix requiring workers in jest

---

src/components/Editor/Editor.css

Associated Issue: #2447
* Added _fade-highlight-out-dark_ animation for the dark theme. This sets the starting transition color to be a darker, blue-ish gray.
New color:
http://g.recordit.co/KEEn6tvCCX.gif

Add a separate highlight animation for dark theme

---

src/components/Editor/index.js
src/utils/editor/index.js

This is very similar to some of the work that @wldcordeiro did last month to cleanup the editor component. Ideally nothing should change, but the component will be easier to reason about. The focus of the work here is to simplify `componentDidMount`
* introduced a new method `setupEditor`
* moved some anonymous event handlers to the prototype
* created a  couple of utilities

Refactor editor

---

src/reducers/event-listeners.js

* changed to import from require and added export 

converted event listeners reducer to es modules

---

src/reducers/event-listeners.js
src/reducers/expressions.js

* Changed to import and added exports to functions
* fixed issue with yarn flow

Es 6 expressions

---

src/actions/breakpoints.js
src/actions/coverage.js
src/actions/event-listeners.js
src/actions/expressions.js
src/actions/index.js
src/actions/navigation.js
src/actions/pause.js
src/actions/sources.js
src/actions/tests/breakpoints.js
src/actions/tests/sources.js
src/actions/tests/ui.js
src/actions/ui.js
src/utils/test-head.js

* modify the actions to use ES6 imports/exports
- add/remove/enable/disable breakpoints
- toggle UI states
- add watch expressions
- etc

Convert actions to use ES6 import/exports

---

src/components/Editor/SearchBar.js

Associated Issue: #2467
* Passed default necessary index value in symbolic search as prop.
1) Command-F in Editor opens Search.
2) Choose function search and look for a function.
3) Click the function and watch it highlight.
4) Escape out of the search box and Command-F again.
5) Check upper right hand corner.
Before: http://g.recordit.co/VNsJHS8jhC.gif

Fix NaN bug when toggling function search

---

src/components/Editor/SearchBar.css

Cursor for disabled search modifier was not correct
* Change cursor of disabled search modifier to `default`.
* Add hover background for search modifier.
Hover style

[SearchBar] Fix cursor for disabled search modifier

---

bin/run-mochitests-docker
bin/update-docker

* Gecko in CI Docker image includes devtools-source-map v0.3.0, which will be needed to use source maps from the toolbox (upcoming work)
* Changed to referencing the Docker image repo by hash, which should avoid the need to create a new repo name for each update

Update Gecko in CI Docker image to include devtools-source-map v0.3.0

---

package.json
yarn.lock

Leaves the devDependency for husky at the more recent version.
Associated Issue: #2460
* remove husy from package.json
* run `yarn` to generate a new `yarn.lock` file.

remove the extra husky dependency

---

circle.yml
package.json
src/client/index.js
src/main.js
src/test/tests-framework.js
src/test/tests-setup.js
src/utils/bootstrap.js
src/utils/parser/index.js
src/utils/pretty-print/index.js
src/utils/teardown.js
yarn.lock

We were seeing `DebuggerConfig` errors in our unit tests because the new source map worker was using DebuggerConfig. The new version of the debugger bypasses that with a new explicit start/stop call to the workers.

Fix worker test failures

---

src/actions/expressions.js
src/actions/types.js
src/components/Editor/index.js
src/components/SecondaryPanes/Expressions.js
src/reducers/expressions.js
src/selectors.js
src/types.js

Associated Issue: #2219
* As a follow up from #2421, including changes.
* Refactor of the reducers to support separate states for `hidden` and `visible` expressions.
* Persisting only `visible` expressions.
* Adding the `visible` argument to expression actions. e.g `addExpression(value, visible)` . If the visible argument is not passed, it defaults to `true`, creating a visible expression. Passing in `false` creates a hidden expression.

Hiding Expressions

---

bin/run-mochitests-docker

When I made the latest Docker image, I edited the name of the `WORKDIR` without realizing it needed to match the paths over here, so the mochitests weren't being run against the latest changes.
To make it easier to track these things, I created a tiny repo with the Docker stuff: https://github.com/devtools-html/debugger-docker. We might trash it soon if the approach changes, but seems useful to share for now.
The test run here should be broken for now (that's expected). Tomorrow we can look into adding fixes to make the tests pass again.

Fix up Docker mapping to use latest files again

---

assets/panel/moz.build
assets/panel/panel.js
bin/run-mochitests-docker
circle-2.0.yml
configs/application.json
configs/firefox-panel.json
src/actions/breakpoints.js
src/actions/navigation.js
src/actions/pause.js
src/actions/sources.js
src/actions/types.js
src/client/index.js
src/components/Editor/EditorMenu.js
src/main.js
src/utils/bootstrap.js
src/utils/pause.js
src/utils/teardown.js
src/utils/test-head.js
webpack.config.js

* When used as a Firefox panel, the debugger gets a `sourceMapService` object from the toolbox, which manages the worker itself, etc. Those details are hidden from the debugger.
* When used in a tab, the debugger starts the source map worker like it did before.

Use source map service from toolbox in Firefox

---

bin/prettier.js

Fixes up `bin/prettier` options to match those in `package.json`.

Standardize prettier options

---

assets/panel/debugger.properties
src/components/Editor/SearchBar.js

Associated Issue: #2242  
* Added tooltips to regex, case, and whole word match
Debugger's Testing doc

Add search modifier tooltips

---

src/components/Editor/Breakpoint.js
src/components/Editor/index.js

- Breakpoint.js
- Convert to class syntax
- Convert require statements to import syntax

Convert Editor/Breakpoint.js to ES6 class

---

src/components/shared/ResultList.js

* Convert `ResultList` to ES6 class.
* Additional changes for `flow`

Convert ResultList to es6 class

---

src/utils/parser/utils.js
src/utils/parser/worker.js
src/utils/tests/parser.js

Some cleanup to make it easier to test `inScope` directly

Convert parser to es6

---

src/components/App.js

Associated Issue: #2004 
* Added onResize with splitter

Fixes tabs dropdown button now shown onResize

---

src/actions/expressions.js
src/actions/tests/expressions.js

Associated Issue: #2265
* Get the frameId of the current selected scope
* Pass the frameId to `evaluateExpressions`
* Added tests

Scoped expression evaluation

---

configs/application.json
configs/development.json
configs/local.sample.json
src/components/Editor/Breakpoint.js
src/components/Editor/Editor.css
src/components/Editor/codemirror-mozilla.css
src/components/Editor/index.js
src/utils/editor/index.js
src/utils/editor/source-editor.js

Associated Issue: #2465 
* Adds code folding to the editor

Add code folding to the editor

---

src/components/shared/Accordion.js
src/components/shared/ManagedTree.js
src/components/shared/ObjectInspector.js

Convert Accordion, ManagedTree, and ObjectInspector to ES6 classes

Convert Accordion, ManagedTree, and ObjectInspector to ES6 classes

---

src/components/SecondaryPanes/Breakpoints.js

I've been seeing yellow borders for BPs when they're not conditional for some time and have forgotten to make an issue :/

Fix BP conditional check

---

src/components/Editor/SearchBar.js
src/components/Editor/index.js

* Converted SearchBar to es6 class

Convert SearchBar to es6

---

src/components/SecondaryPanes/Scopes.css
src/components/shared/ObjectInspector.js
src/utils/object-inspector.js

Associated Issue: #2434
* Switched display of functions in Object Inspector to be condensed
* Styled the condensed version to be inline if in the object inspector.

Object Inspector - Formatting Functions

---

src/components/SecondaryPanes/Frames.js
src/utils/function.js
src/utils/tests/function.js

* This decodes Firefox's totally crazy interpretation of anonymous function names.
* **Why do decode the string, and not use babel** 
* the string is a very clear spec with many rules, it is better than what we do w/ inference now
* we don't want to load and parse every file we get in the call stack if we don't have to
* **will this work?** if the regex's fail to match we'll show the original. This code will not throw errors. (i think)
You bet!

Simplify function names

---

src/components/Editor/Preview.css
src/components/Editor/Preview.js
src/components/shared/Popover.css
src/components/shared/Popover.js
src/components/shared/previewFunction.css

Associated Issue: #2565 
* Added popover direction

WIP Display popover intelligently

---

assets/panel/debugger.properties
src/components/Editor/SearchBar.js

Associated Issue: #2529
- Changed Summary message to `%d of %d results`
@wldcordeiro @jasonLaster  - What should be done for a `1 of 1 results` output?

FunctionSearch - show index in summary, Fixes #2529

---

src/client/chrome.js

Associated Issue: https://github.com/devtools-html/debugger.html/issues/2616
* Trivial fix to update the initialization in chrome.js to correctly accommodate the parameters passed into `onConnect`.
Just start up debugging against a Chrome tab. Before it would fail, now it works.

Fix breakage in Chrome initialization logic

---

src/components/shared/ObjectInspector.js
src/components/shared/previewFunction.js

This fixes the broken function preview, a possible regression.
* change `div` to `span`
* use `item` instead of `item.contents.value` to get the function details for preview
* If `parameterNames` does not exist the UI breaks

basic fix for broken function preview

---

src/components/shared/previewFunction.js
src/test/integration/tests/editor-preview.js
src/test/integration/utils/commands.js
src/test/integration/utils/mocha.js
src/utils/object-inspector.js
src/utils/tests/object-inspector.js

Associated Issue: #2280
* Added  a function `makeDefaultPropsBucket` to render all the default properties under one `[default properties]` bucket
* Numerical bucketing are only used for rendering large array objects
* Updated the tests
Before (example)
After (examples)
this

Default props bucket

---

src/components/shared/previewFunction.js

When we moved the previewFunction css to its own file, we didn't require it, so the formatting got lost.

formatting functions

---

src/components/Editor/Editor.css
src/components/Editor/SearchBar.css
src/components/Editor/index.js

Associated Issue: #2424 
* Fixes Tabs from being masked by the search bar
* Stops the bottom scroll bar being pushed off by search bar

Don't push bottom scroll bar off screen when search is opened for files that don't need to be prettyifyed

---

src/components/Editor/Tabs.js

Associated Issue: #2553 
* Hide `Reveal in Tree` menu item for pretty-printed tabs
* Right click on pretty-printed tabs to see if `Reveal in Tree` menu item is gone.

'Reveal in tree' should also work for tabs with pretty printed source 

---

package.json
src/components/tests/__snapshots__/closeButton.js.snap
src/test/__mocks__/svgMock.js

Resolve #2630 
* Update css|svg mock to apply to only css
* Add mock for svg

Resolve svg src warning in jest tests

---

src/components/Editor/SearchBar.js

Associated Issue: #2641 
* Added `F3` as a hotkey.
* Expecting `Enter` and `F3` to be used as a way to navigate search terms.

Added F3 hotkey for searching.

---

src/components/Editor/Tabs.js

Resolve #2015
* If hidden tab is requested, it is put at the first place.

Hidden tab shown when clicked from tree node

---

src/utils/sources-tree.js
src/utils/tests/sources-tree.js

Associated Issue: #2569
* Fix `isDirectory` function

Fix isDirectory function

---

src/test/integration/runner.js
src/test/integration/tests/index.js
src/test/integration/tests/scopes-mutations.js
src/test/mochitest/browser.ini
src/test/mochitest/browser_dbg-scopes-mutations.js
src/test/mochitest/examples/doc-script-mutate.html
src/test/mochitest/examples/script-mutate.js
src/test/mochitest/head.js

Associated Issue: #2631
Add a WRT test and a mochitest one to test that the expanded scopes
__does not__ behave as expected when stepping over a code that mutates an object
in the scopes panel.

Add scopes mutation integration tests

---

docs/updates/call-stack-4-10-2017.md

Associated Issue:  None.
Simple typo in a doc.
No need to test, just a doc change.

Correct Libarary typo in callstack doc

---

.eslintignore
package.json
src/utils/tests/fixtures/allSymbols.js
src/utils/tests/fixtures/class.js
src/utils/tests/fixtures/expression.js
src/utils/tests/fixtures/func.js
src/utils/tests/fixtures/math.js
src/utils/tests/fixtures/proto.js
src/utils/tests/fixtures/resolveToken.js
src/utils/tests/fixtures/thisExpression.js
src/utils/tests/fixtures/var.js
src/utils/tests/parser.js

* moved the fixtures to their own files
* had to change some source locations
WHY?
We're doing a lot of parsing already and that's going to keep happening. We are building a debugger after all. So, lets invest in our fixtures and move them to their own files so that they can be better organized and we can get syntax highlighting and other things for free.

Move parser fixtures to files

---

src/components/Editor/SearchBar.js

Also, refactored other `e.preventDefault()` calls in the `onKeyDown` handler. Theoretically, it shouldn't break anything.
Associated Issue: #2641

Adding missing e.preventDefault(). 

---

src/components/Editor/SearchBar.js
src/utils/result-list.js

Found a problem which can be fixed with a minor change
* Open TodoMVC example in browser
* Open `js/views/app-view.js` file in debugger.html
* Open function search in editor and enter `a`.
* Navigate to lower result by pressing `down` arrow key a few times
* Now enter `a` in function search to narrow the result
* check before scrolling list

[SearchBar] Check before scrolling to result in result-list

---

src/components/Editor/index.js
src/utils/parser/utils.js
src/utils/tests/parser.js

Associated Issue: #2536
Previously, we would determine if a node was in scope by seeing if it's most local scope contained it. We now get all of the variables defined along the scope chain. So get all the variables in the narrowest scope up to the program. 
I tried to tidy up some of the parsing logic along the way so that it would be more consistent.
We now have more methods that are more specific to what we want to do:
+  getClosestPath,
+  getClosestScope,
+  getClosestExpression,
+  getVariablesInLocalScope,

[WIP] Address some scope inconsistencies

---

README.md
docs/getting-setup.md

Github's recommended method for cloning is HTTPS.
This avoids the need for ssh keys.
No Associated Issue
Updated the Quick Setup section of README and GETTING_SETUP to avoid error due to missing SSH/GPG Keys
Single line markdown changes. 
Opened both documents and made sure they rendered properly in github and standalone.

Docs: Changed git clone  to use https

---

src/components/Editor/Editor.css
src/components/Editor/index.js

Associated Issue: #2588 
* Add event listener on code mirror gutter to toggle visibility of fold marker
The problems here is `mouseenter` and `mouseleave` doesn't work as expected on gutter. I'm not sure why.
Let me know if you have any suggestions.

[WIP] CodeFolding - hide fold markers unless hovering on the gutter

---

src/utils/parser/utils.js
src/utils/tests/parser.js

Fixes a recent bug with previewing `this`

Fix previewing this

---

src/components/SecondaryPanes/Frames.css

Associated Issue: #2659 
* updated line-height for call stack logos
* applied white color to logo when the frame is selected

Fix call stack logos styling

---

src/utils/parser/utils.js
src/utils/tests/parser.js

This fixes the algorithm for determing if a location is in scope by checking if it is at the start or end of a scope

Fix previewing scope params

---

webpack.config.js

Associated Issue: #2117
Fixes the warning about mocha.js being a prebuilt file during the webpack build.
* add the module.noParse webpack config to ignore the prebuilt mocha.js file

issue #2117: add module: noParse to ignore mocha

---

configs/development.json
src/components/Editor/Preview.css
src/components/Editor/Preview.js
src/components/shared/Popover.css
src/components/shared/Popover.js

Associated Issue: #2578 
- Created UI as suggested
- Somehow [`addExpression`](https://github.com/devtools-html/debugger.html/compare/master...ruturajv:bug-2578-save-preview-to-watch-expressions?expand=1#diff-358af90c482e216b601199f75f64a27bR103) isn't working as I hoped, @jasonLaster @wldcordeiro  could you please check ?
- please ignore the mouseLeave comment
- regarding a comment on the mock, `input - updates preview`should the expression be listed in an input box and then user can play around with it to see preview changing ... and then add ?

WIP: Adding to watch Expressions, commented mouseLeave

---

src/utils/parser/utils.js

Cleans up some small errors with the public APIs.
We should invert the relationship so that it is safe by default, but that's for later

Return on null AST

---

src/components/tests/WhyPaused.js
src/utils/tests/scopes.js

L10N is globally setup [here](https://github.com/devtools-html/debugger.html/blob/master/src/test/tests-setup.js#L27) so this is not required.
Associated Issue: #2728
* Remove L10N setup from `utils/tests/scopes.js`

Remove L10N setup from utils/tests/scopes.js

---

src/reducers/sources.js
src/reducers/tests/sources.js

* update sources reducer to use ES modules
* update sources reducer test to use ES modules
* set sources reducer's state argument's state to `any` to silence Flow error
Note about last point:
Without it Flow complained about missing annotation after addition of 
`export` statement.  After setting it to `SourcesState` it complained 
about unrecognized methods, which I suspect come from Immutable. 
Since this PR isn't about type-checking, I left it at `any`, as suggested
in [this comment](https://github.com/devtools-html/debugger.html/issues/1884#issuecomment-280710019).

Convert sources reducer to ES modules

---

package.json
src/reducers/async-requests.js
src/reducers/breakpoints.js
src/reducers/coverage.js
src/reducers/event-listeners.js
src/reducers/expressions.js
src/reducers/index.js
src/reducers/pause.js
src/reducers/sources.js
src/reducers/tests/sources.js
src/reducers/ui.js
src/utils/bootstrap.js
src/utils/test-head.js

Converted following reducers to ES modules:
- async requests,
- breakpoints,
- coverage,
- index,
- pause,
- ui.
All reducers has been updated to export `update` reducer by default. This allowed to somewhat simplify main reducer (`reducers/index`).
Also, type definitions for `update` functions' `state` argument have been added.
Another small change is addition of `yarn flow` command to the `yarn test-all` one. Lack of the former in the latter proved to be somewhat inconvenient when I wanted to manually check if everything is fine - the shortest way was `yarn test-all && yarn flow`. I completely agree this change is unrelated to the topic of this PR and won't mind to revert it if it's a problem.

Convert remaining of reducers to ES modules

---

src/components/Outline.js

Associated Issue: #2731
The high CPU usage was due to an infinite loop. `componentWillUpdate` is called any time that props _or state_ are changed. So by triggering a process that will call `setState` inside of it, we then change the state and trigger it to happen again, ad infinitum. For this case, we only want to do the work if props are changing from above, so the correct callback to use is `componentWillReceiveProps`.
In running the tests, I found an unrelated failure that was already present on master. One of the unit tests needed a mocked `L10N` object, so I added it.
* Changed callback that triggers symbol lookup from  `componentWillUpdate` to `componentWillReceiveProps` 
* Added a mock `L10N` object before test that requires it.

Fix Outline CPU usage (and unrelated test failure)

---

src/components/shared/Autocomplete.js
src/components/shared/ManagedTree.js
src/components/shared/ObjectInspector.js
src/components/shared/Svg.js

Refactor the following files to use ES module syntax:
- ManagedTree
- Autocomplete
- ObjectInspector
- Svg

Convert shared components to es6 modules

---

src/components/Editor/Breakpoint.js
src/components/Editor/ConditionalPanel.js
src/components/Editor/Preview.js
src/components/Editor/SearchBar.js
src/components/Editor/Tabs.js
src/components/Editor/index.js
src/components/SecondaryPanes/index.js

Refactor the following files to use ES module syntax:

Convert components to ES modules

---

src/components/Editor/SearchBar.js
src/components/ProjectSearch.js
src/components/shared/Autocomplete.js

On selecting the source from list, the source was not
being opened in the editor
- Fixes #2742 
- In search bar, on press enter, move to next result (previously broken)

Fix broken source search

---

assets/panel/debugger.properties
src/components/shared/SearchInput.css
src/components/shared/SearchInput.js

Associated Issue: [#2589](https://github.com/devtools-html/debugger.html/issues/2589)
Adds hover styling to the up/down arrow navigation buttons in SeachInput Component. The following styles have been added:
* `cursor: pointer` on hover
* tooltip(s) on hover
* adds `background` color and  `transition` change on hover to match behavior found in [CommandBar Buttons](https://github.com/devtools-html/debugger.html/blob/master/src/components/SecondaryPanes/CommandBar.css#L17-L34)

adds hover styles and tooltips to search arrow buttons

---

configs/application.json
configs/ci.json
configs/development.json
configs/firefox-panel.json
configs/local.sample.json
src/components/Editor/SearchBar.js
src/components/Editor/index.js

* removed all references to the searchModifiers flag 
Open the debugger with no mention of searchModifiers in your config/local.json
Open a JS file and hit Ctrl+F. You should see functions and variables as check options in the left and in the right the regex, case sensitive and wholewords options.

removed feature flag for search modifiers #2685
